
include ..\Makefile.inc

EFLAGS = -I .. -pz ..

OUTDIR = ..
SOURCES = $(wildcard *.erl)
BEAMS = $(addprefix $(OUTDIR)/,$(SOURCES:.erl=.beam))

ALL : $(BEAMS)

CLEAN :
	-@erase $(BEAMS)

$(OUTDIR)\mod_muc.beam : mod_muc.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) mod_muc.erl

$(OUTDIR)\mod_muc_log.beam : mod_muc_log.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) mod_muc_log.erl

$(OUTDIR)\mod_muc_room.beam : mod_muc_room.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) mod_muc_room.erl
