%% -*- coding: utf-8 -*-
{" has set the subject to: "," změnil(a) téma na: "}.
{"A password is required to enter this room","Pro vstup do místnosti musíte zadat heslo"}.
{"Accept","Přijmout"}.
{"Access denied by service policy","Přístup byl zamítnut nastavením služby"}.
{"Action on user","Akce aplikovaná na uživatele"}.
{"Add Jabber ID","Přidat Jabber ID"}.
{"Add New","Přidat nový"}.
{"Add User","Přidat uživatele"}.
{"Administration of ","Administrace "}.
{"Administration","Administrace"}.
{"Administrator privileges required","Potřebujete práva administrátora"}.
{"All activity","Všechny aktivity"}.
{"All Users","Všichni uživatelé"}.
{"Allow users to change the subject","Povolit uživatelům měnit téma místnosti"}.
{"Allow users to query other users","Povolit uživatelům odesílat požadavky (query) ostatním uživatelům"}.
{"Allow users to send invites","Povolit uživatelům posílání pozvánek"}.
{"Allow users to send private messages","Povolit uživatelům odesílat soukromé zprávy"}.
{"Allow visitors to change nickname","Povolit návštěvníkům měnit přezdívku"}.
{"Allow visitors to send private messages to","Povolit návštěvníkům odesílat soukromé zprávy"}.
{"Allow visitors to send status text in presence updates","Povolit návštěvníkům posílat stavové zprávy ve statusu"}.
{"Announcements","Oznámení"}.
{"April",". dubna"}.
{"August",". srpna"}.
{"Automatic node creation is not enabled","Automatické vytváření uzlů není povoleno"}.
{"Backup Management","Správa zálohování"}.
{"Backup of ~p","Záloha ~p"}.
{"Backup to File at ","Záloha do souboru na "}.
{"Backup","Zálohovat"}.
{"Bad format","Nesprávný formát"}.
{"Birthday","Datum narození"}.
{"Both the username and the resource are required","Uživatelské jméno i zdroj jsou požadované položky"}.
{"Bytestream already activated","Bytestream již byl aktivován"}.
{"Cannot remove active list","Aktivní seznam nelze odebrat"}.
{"Cannot remove default list","Výchozí seznam nelze odebrat"}.
{"Change Password","Změnit heslo"}.
{"Change User Password","Změnit heslo uživatele"}.
{"Changing password is not allowed","Změna hesla není povolena"}.
{"Changing role/affiliation is not allowed","Změna role/příslušnosti není povolena"}.
{"Characters not allowed:","Nepřípustné znaky:"}.
{"Chatroom configuration modified","Nastavení diskuzní místnosti bylo změněno"}.
{"Chatroom is created","Místnost vytvořena"}.
{"Chatroom is destroyed","Místnost zrušena"}.
{"Chatroom is started","Místnost spuštěna"}.
{"Chatroom is stopped","Místnost zastavena"}.
{"Chatrooms","Místnosti"}.
{"Choose a username and password to register with this server","Zadejte jméno uživatele a heslo pro registraci na tomto serveru"}.
{"Choose storage type of tables","Vyberte typ úložiště pro tabulky"}.
{"Choose whether to approve this entity's subscription.","Zvolte, zda chcete schválit odebírání touto entitou."}.
{"City","Město"}.
{"Commands","Příkazy"}.
{"Conference room does not exist","Místnost neexistuje"}.
{"Configuration","Konfigurace"}.
{"Connected Resources:","Připojené zdroje:"}.
{"Country","Země"}.
{"CPU Time:","Čas procesoru:"}.
{"Database failure","Chyba databáze"}.
{"Database Tables at ~p","Databázové tabulky na ~p"}.
{"Database Tables Configuration at ","Konfigurace databázových tabulek "}.
{"Database","Databáze"}.
{"December",". prosince"}.
{"Default users as participants","Uživatelé jsou implicitně členy"}.
{"Delete message of the day on all hosts","Smazat zprávu dne na všech hostitelích"}.
{"Delete message of the day","Smazat zprávu dne"}.
{"Delete Selected","Smazat vybrané"}.
{"Delete User","Smazat uživatele"}.
{"Description:","Popis:"}.
{"Disc only copy","Jen kopie disku"}.
{"Displayed Groups:","Zobrazené skupiny:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Nikdy nikomu nesdělujte své heslo, ani administrátorovi serveru Jabberu."}.
{"Dump Backup to Text File at ","Uložit zálohu do textového souboru na "}.
{"Dump to Text File","Uložit do textového souboru"}.
{"Duplicated groups are not allowed by RFC6121","Duplicitní skupiny nejsou povoleny dle RFC6121"}.
{"Edit Properties","Upravit vlastnosti"}.
{"Either approve or decline the voice request.","Povolit nebo odmítnout voice žádost."}.
{"ejabberd MUC module","ejabberd MUC modul"}.
{"ejabberd Multicast service","Služba ejabberd Multicast"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe modul"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams modul"}.
{"ejabberd vCard module","ejabberd vCard modul"}.
{"ejabberd Web Admin","Webová administrace ejabberd"}.
{"Elements","Položek"}.
{"Email","E-mail"}.
{"Enable logging","Zaznamenávat konverzace"}.
{"Enabling push without 'node' attribute is not supported","Aktivováno push bez atributu 'node' není podporováno"}.
{"End User Session","Ukončit sezení uživatele"}.
{"Enter nickname you want to register","Zadejte přezdívku, kterou chcete zaregistrovat"}.
{"Enter path to backup file","Zadajte cestu k souboru se zálohou"}.
{"Enter path to jabberd14 spool dir","Zadejte cestu k jabberd14 spool adresáři"}.
{"Enter path to jabberd14 spool file","Zadejte cestu k spool souboru jabberd14"}.
{"Enter path to text file","Zadajte cestu k textovému souboru"}.
{"Enter the text you see","Zadejte text, který vidíte"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Chyba"}.
{"Export all tables as SQL queries to a file:","Zálohovat všechny tabulky jako SQL dotazy do souboru:"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Exportovat všechny uživatele do souboru ve formátu PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Exportovat uživatele na hostiteli do souboru ve formátu PIEFXIS (XEP-0227):"}.
{"External component failure","Chyba externí komponenty"}.
{"External component timeout","Timeout externí komponenty"}.
{"Failed to activate bytestream","Chyba při aktivaci bytestreamu"}.
{"Failed to extract JID from your voice request approval","Došlo k chybě při získávání Jabber ID z vaší žádosti o voice práva"}.
{"Failed to map delegated namespace to external component","Chyba při mapování namespace pro externí komponentu"}.
{"Failed to parse HTTP response","Chyba parsování HTTP odpovědi"}.
{"Family Name","Příjmení"}.
{"February",". února"}.
{"File larger than ~w bytes","Soubor větší než ~w bytů"}.
{"Friday","Pátek"}.
{"From","Od"}.
{"Full Name","Celé jméno"}.
{"Get Number of Online Users","Získat počet online uživatelů"}.
{"Get Number of Registered Users","Získat počet registrovaných uživatelů"}.
{"Get User Last Login Time","Získat čas podleního přihlášení uživatele"}.
{"Get User Password","Získat heslo uživatele"}.
{"Get User Statistics","Získat statistiky uživatele"}.
{"Given Name","Křestní jméno"}.
{"Group ","Skupina "}.
{"Groups","Skupiny"}.
{"has been banned","byl(a) zablokován(a)"}.
{"has been kicked because of a system shutdown","byl(a) vyhozen(a), protože dojde k vypnutí systému"}.
{"has been kicked because of an affiliation change","byl(a) vyhozen(a) kvůli změně přiřazení"}.
{"has been kicked because the room has been changed to members-only","byl(a) vyhozen(a), protože mísnost je nyní pouze pro členy"}.
{"has been kicked","byl(a) vyhozen(a) z místnosti"}.
{"Host unknown","Neznámý hostitel"}.
{"Host","Hostitel"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Pokud zde nevidíte obrázek CAPTCHA, přejděte na webovou stránku."}.
{"Import Directory","Import adresáře"}.
{"Import File","Import souboru"}.
{"Import user data from jabberd14 spool file:","Importovat uživatele z jabberd14 spool souborů:"}.
{"Import User from File at ","Importovat uživatele ze souboru na "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importovat uživatele ze souboru ve formátu PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importovat uživatele z jabberd14 spool souborů:"}.
{"Import Users from Dir at ","Importovat uživatele z adresáře na "}.
{"Import Users From jabberd14 Spool Files","Importovat uživatele z jabberd14 spool souborů"}.
{"Improper domain part of 'from' attribute","Nesprávná část s doménou atributu 'from'"}.
{"Improper message type","Nesprávný typ zprávy"}.
{"Incoming s2s Connections:","Příchozí s2s spojení:"}.
{"Incorrect CAPTCHA submit","Nesprávné odeslání CAPTCHA"}.
{"Incorrect data form","Nesprávný datový formulář"}.
{"Incorrect password","Nesprávné heslo"}.
{"Incorrect value of 'action' attribute","Nesprávná hodnota atributu 'action'"}.
{"Incorrect value of 'action' in data form","Nesprávná hodnota atributu 'action' v datovém formuláři"}.
{"Incorrect value of 'path' in data form","Nesprávná hodnota atributu 'path' v datovém formuláři"}.
{"Insufficient privilege","Nedostatečné oprávnění"}.
{"Invalid 'from' attribute in forwarded message","Nesprávný atribut 'from' v přeposlané zprávě"}.
{"Invitations are not allowed in this conference","Pozvánky nejsou povoleny v této místnosti"}.
{"IP addresses","IP adresy"}.
{"is now known as","se přejmenoval(a) na"}.
{"It is not allowed to send private messages of type \"groupchat\"","Není dovoleno odeslání soukromé zprávy typu \"skupinová zpráva\" "}.
{"It is not allowed to send private messages to the conference","Není povoleno odesílat soukromé zprávy v této místnosti"}.
{"It is not allowed to send private messages","Je zakázáno posílat soukromé zprávy"}.
{"Jabber Account Registration","Registrace účtu Jabberu"}.
{"Jabber ID","Jabber ID"}.
{"January",". ledna"}.
{"joins the room","vstoupil(a) do místnosti"}.
{"July",". července"}.
{"June",". června"}.
{"Last Activity","Poslední aktivita"}.
{"Last login","Poslední přihlášení"}.
{"Last month","Poslední měsíc"}.
{"Last year","Poslední rok"}.
{"leaves the room","opustil(a) místnost"}.
{"List of rooms","Seznam místností"}.
{"Low level update script","Nízkoúrovňový aktualizační skript"}.
{"Make participants list public","Nastavit seznam účastníků jako veřejný"}.
{"Make room CAPTCHA protected","Chránit místnost pomocí CAPTCHA"}.
{"Make room members-only","Zpřístupnit místnost jen členům"}.
{"Make room moderated","Nastavit místnost jako moderovanou"}.
{"Make room password protected","Chránit místnost heslem"}.
{"Make room persistent","Nastavit místnost jako stálou"}.
{"Make room public searchable","Nastavit místnost jako veřejnou"}.
{"Malformed username","Chybně formátováné jméno uživatele"}.
{"March",". března"}.
{"Maximum Number of Occupants","Počet účastníků"}.
{"May",". května"}.
{"Members:","Členové:"}.
{"Membership is required to enter this room","Pro vstup do místnosti musíte být členem"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Svoje heslo si zapamatujte, nebo si jej poznamenejte na papírek a ten uschovejte v bezpečí. Jabber nemá žádný automatizovaný způsob obnovy hesla."}.
{"Memory","Paměť"}.
{"Message body","Tělo zprávy"}.
{"Message not found in forwarded payload","Zpráva nebyla nalezena v přeposlaném obsahu"}.
{"Middle Name","Druhé jméno"}.
{"Moderator privileges required","Potřebujete práva moderátora"}.
{"Modified modules","Aktualizované moduly"}.
{"Module failed to handle the query","Modul chyboval při zpracování dotazu"}.
{"Monday","Pondělí"}.
{"Multicast","Multicast"}.
{"Multiple <item/> elements are not allowed by RFC6121","Vícenásobný element <item/> není povolen dle RFC6121"}.
{"Multi-User Chat","Víceuživatelský chat"}.
{"Name","Jméno"}.
{"Name:","Jméno:"}.
{"Neither 'jid' nor 'nick' attribute found","Nebyl nalezen atribut 'jid' ani 'nick'"}.
{"Neither 'role' nor 'affiliation' attribute found","Nebyl nalezen atribut 'role'  ani 'affiliation'"}.
{"Never","Nikdy"}.
{"New Password:","Nové heslo:"}.
{"Nickname Registration at ","Registrace přezdívky na "}.
{"Nickname","Přezdívka"}.
{"No 'affiliation' attribute found","Chybějící atribut 'affiliation'"}.
{"No available resource found","Nebyl nalezen žádný dostupný zdroj"}.
{"No body provided for announce message","Zpráva neobsahuje text"}.
{"No data form found","Nebyl nalezen datový formulář"}.
{"No Data","Žádná data"}.
{"No features available","Žádné funce nejsou dostupné"}.
{"No hook has processed this command","Žádný hook nebyl zpracován tímto příkazem"}.
{"No info about last activity found","Nebyla žádná informace o poslední aktivitě"}.
{"No 'item' element found","Element 'item' nebyl nalezen"}.
{"No items found in this query","Žádné položky nebyly nalezeny v tomto dotazu"}.
{"No limit","Bez limitu"}.
{"No module is handling this query","Žádný modul neobsluhuje tento dotaz"}.
{"No node specified","Žádný uzel nebyl specifikován"}.
{"No 'password' found in data form","Chybějící atribut 'password' v datovém formuláři"}.
{"No 'password' found in this query","Chybějící atribut 'password' v tomto dotazu"}.
{"No 'path' found in data form","Chybějící atribut 'path' v datovém formuláři"}.
{"No pending subscriptions found","Žádné čekající předplatné nebylo nalezeno"}.
{"No privacy list with this name found","Žádný privacy list s tímto jménem nebyl nalezen"}.
{"No private data found in this query","Žádná soukromá data nebyla nalezena tímto dotazem"}.
{"No running node found","Nebyl nalezen žádný běžící uzel"}.
{"No services available","Žádné služby nejsou dostupné"}.
{"No statistics found for this item","Nebyly nalezeny statistiky pro uvedenou položku"}.
{"No 'to' attribute found in the invitation","Chybějící atribut 'to' v pozvánce"}.
{"Node already exists","Uzel již existuje"}.
{"Node index not found","Index uzlu nebyl nalezen"}.
{"Node not found","Uzel nenalezen"}.
{"Node ~p","Uzel ~p"}.
{"Nodeprep has failed","Nodeprep chyboval"}.
{"Nodes","Uzly"}.
{"None","Nic"}.
{"Not Found","Nenalezeno"}.
{"Not subscribed","Není odebíráno"}.
{"November",". listopadu"}.
{"Number of online users","Počet online uživatelů"}.
{"Number of registered users","Počet registrovaných uživatelů"}.
{"October",". října"}.
{"Offline Messages","Offline zprávy"}.
{"Offline Messages:","Offline zprávy:"}.
{"OK","OK"}.
{"Old Password:","Současné heslo:"}.
{"Online Users","Připojení uživatelé"}.
{"Online Users:","Připojení uživatelé:"}.
{"Online","Online"}.
{"Only <enable/> or <disable/> tags are allowed","Pouze značky <enable/> nebo <disable/>jsou povoleny"}.
{"Only <list/> element is allowed in this query","Pouze element <list/> je povolen v tomto dotazu"}.
{"Only members may query archives of this room","Pouze moderátoři mají povoleno měnit téma místnosti"}.
{"Only moderators and participants are allowed to change the subject in this room","Jen moderátoři a účastníci mají povoleno měnit téma této místnosti"}.
{"Only moderators are allowed to change the subject in this room","Jen moderátoři mají povoleno měnit téma místnosti"}.
{"Only moderators can approve voice requests","Pouze moderátoři mohou schválit žádosti o voice práva"}.
{"Only occupants are allowed to send messages to the conference","Jen členové mají povolené zasílat zprávy do místnosti"}.
{"Only occupants are allowed to send queries to the conference","Jen členové mohou odesílat požadavky (query) do místnosti"}.
{"Only service administrators are allowed to send service messages","Pouze správci služby smí odesílat servisní zprávy"}.
{"Organization Name","Název firmy"}.
{"Organization Unit","Oddělení"}.
{"Outgoing s2s Connections","Odchozí s2s spojení"}.
{"Outgoing s2s Connections:","Odchozí s2s spojení:"}.
{"Owner privileges required","Jsou vyžadována práva vlastníka"}.
{"Packet","Paket"}.
{"Password Verification","Ověření hesla"}.
{"Password Verification:","Ověření hesla:"}.
{"Password","Heslo"}.
{"Password:","Heslo:"}.
{"Path to Dir","Cesta k adresáři"}.
{"Path to File","Cesta k souboru"}.
{"Pending","Čekající"}.
{"Period: ","Čas: "}.
{"Ping query is incorrect","Ping dotaz je nesprávný"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Podotýkáme, že tato nastavení budou zálohována do zabudované databáze Mnesia. Pokud používáte ODBC modul, musíte zálohovat svoji SQL databázi samostatně."}.
{"Please, wait for a while before sending new voice request","Prosím, počkejte chvíli před posláním nové žádosti o voice práva"}.
{"Pong","Pong"}.
{"Possessing 'ask' attribute is not allowed by RFC6121","Atribut 'ask' není povolen dle RFC6121"}.
{"private, ","soukromá, "}.
{"Publish-Subscribe","Publish-Subscribe"}.
{"PubSub subscriber request","Žádost odběratele PubSub"}.
{"Queries to the conference members are not allowed in this room","Požadavky (queries) na členy místnosti nejsou v této místnosti povolené"}.
{"Query to another users is forbidden","Dotaz na jiné uživatele je zakázán"}.
{"RAM and disc copy","Kopie RAM a disku"}.
{"RAM copy","Kopie RAM"}.
{"Really delete message of the day?","Skutečně smazat zprávu dne?"}.
{"Recipient is not in the conference room","Příjemce se nenachází v místnosti"}.
{"Register a Jabber account","Zaregistrujte si účet Jabberu"}.
{"Registered Users","Registrovaní uživatelé"}.
{"Registered Users:","Registrovaní uživatelé:"}.
{"Register","Zaregistrovat se"}.
{"Remote copy","Vzdálená kopie"}.
{"Remove All Offline Messages","Odstranit všechny offline zprávy"}.
{"Remove User","Odstranit uživatele"}.
{"Remove","Odstranit"}.
{"Replaced by new connection","Nahrazeno novým spojením"}.
{"Resources","Zdroje"}.
{"Restart Service","Restartovat službu"}.
{"Restart","Restart"}.
{"Restore Backup from File at ","Obnovit zálohu ze souboru na "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Obnovit binární zálohu při následujícím restartu ejabberd (vyžaduje méně paměti):"}.
{"Restore binary backup immediately:","Okamžitě obnovit binární zálohu:"}.
{"Restore plain text backup immediately:","Okamžitě obnovit zálohu z textového souboru:"}.
{"Restore","Obnovit"}.
{"Room Configuration","Nastavení místnosti"}.
{"Room creation is denied by service policy","Pravidla služby nepovolují vytvořit místnost"}.
{"Room description","Popis místnosti"}.
{"Room Occupants","Počet účastníků"}.
{"Room title","Název místnosti"}.
{"Roster size","Velikost seznamu kontaktů"}.
{"Roster","Seznam kontaktů"}.
{"RPC Call Error","Chyba RPC volání"}.
{"Running Nodes","Běžící uzly"}.
{"Saturday","Sobota"}.
{"Script check","Kontrola skriptu"}.
{"Search Results for ","Výsledky hledání pro "}.
{"Search users in ","Hledat uživatele v "}.
{"Send announcement to all online users on all hosts","Odeslat oznámení všem online uživatelům na všech hostitelích"}.
{"Send announcement to all online users","Odeslat oznámení všem online uživatelům"}.
{"Send announcement to all users on all hosts","Odeslat oznámení všem uživatelům na všech hostitelích"}.
{"Send announcement to all users","Odeslat oznámení všem uživatelům"}.
{"September",". září"}.
{"Server:","Server:"}.
{"Set message of the day and send to online users","Nastavit zprávu dne a odeslat ji online uživatelům"}.
{"Set message of the day on all hosts and send to online users","Nastavit zprávu dne a odeslat ji online uživatelům"}.
{"Shared Roster Groups","Skupiny pro sdílený seznam kontaktů"}.
{"Show Integral Table","Zobrazit kompletní tabulku"}.
{"Show Ordinary Table","Zobrazit běžnou tabulku"}.
{"Shut Down Service","Vypnout službu"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Někteří klienti umí uložit vaše heslo na disk počítače. Tuto funkci používejte, pouze pokud věříte zabezpečení svého počítače."}.
{"Statistics of ~p","Statistiky ~p"}.
{"Statistics","Statistiky"}.
{"Stopped Nodes","Zastavené uzly"}.
{"Stop","Stop"}.
{"Storage Type","Typ úložiště"}.
{"Store binary backup:","Uložit binární zálohu:"}.
{"Store plain text backup:","Uložit zálohu do textového souboru:"}.
{"Subject","Předmět"}.
{"Submit","Odeslat"}.
{"Submitted","Odeslané"}.
{"Subscription","Přihlášení"}.
{"Subscriptions are not allowed","Předplatné není povoleno"}.
{"Sunday","Neděle"}.
{"That nickname is already in use by another occupant","Přezdívka je již používána jiným členem"}.
{"That nickname is registered by another person","Přezdívka je zaregistrována jinou osobou"}.
{"The CAPTCHA is valid.","CAPTCHA souhlasí."}.
{"The CAPTCHA verification has failed","Ověření CAPTCHA se nezdařilo"}.
{"The feature requested is not supported by the conference","Požadovaná vlastnost není podporována touto místností"}.
{"The password contains unacceptable characters","Heslo obsahuje nepovolené znaky"}.
{"The password is too weak","Heslo je příliš slabé"}.
{"the password is","heslo je"}.
{"The password of your Jabber account was successfully changed.","Heslo vašeho účtu Jabberu bylo úspěšně změněno."}.
{"The query is only allowed from local users","Dotaz je povolen pouze pro místní uživatele"}.
{"The query must not contain <item/> elements","Dotaz nesmí obsahovat elementy <item/>"}.
{"The stanza MUST contain only one <active/> element, one <default/> element, or one <list/> element","Stanza MUSÍ obsahovat pouze jeden element  <active/>, jeden element <default/> nebo jeden element <list/>"}.
{"There was an error changing the password: ","Při změně hesla došlo k chybě: "}.
{"There was an error creating the account: ","Při vytváření účtu došlo k chybě:"}.
{"There was an error deleting the account: ","Při mazání účtu došlo k chybě: "}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Zde nezáleží na velikosti písmen: macbeth je stejný jako MacBeth a Macbeth."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Na této stránce si můžete vytvořit účet na tomto serveru Jabberu. Vaše JID (Jabber IDentifikátor) bude mít tvar: uživatelskéjméno@server. Přečtěte si prosím pozorně instrukce pro vyplnění údajů."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Zde můžete zrušit registraci účtu na tomto serveru Jabberu."}.
{"This room is not anonymous","Tato místnost není anonymní"}.
{"Thursday","Čtvrtek"}.
{"Time delay","Časový posun"}.
{"Time","Čas"}.
{"Token TTL","Token TTL"}.
{"Too many active bytestreams","Příliš mnoho aktivních bytestreamů"}.
{"Too many CAPTCHA requests","Přiliš mnoho CAPTCHA žádostí"}.
{"Too many <item/> elements","Příliš mnoho elementů <item/>"}.
{"Too many <list/> elements","Přilíš mnoho elementů <list/>"}.
{"Too many unacked stanzas","Příliš mnoho nepotvrzených stanz"}.
{"Too many users in this conference","Přiliš mnoho uživatelů v této místnosti"}.
{"To","Pro"}.
{"Total rooms","Celkem místností"}.
{"Traffic rate limit is exceeded","Byl překročen limit"}.
{"Transactions Aborted:","Transakcí zrušených:"}.
{"Transactions Committed:","Transakcí potvrzených:"}.
{"Transactions Logged:","Transakcí zaznamenaných:"}.
{"Transactions Restarted:","Transakcí restartovaných:"}.
{"Tuesday","Úterý"}.
{"Unable to generate a CAPTCHA","Nebylo možné vygenerovat CAPTCHA"}.
{"Unable to register route on existing local domain","Není možné zaregistrovat routu na existující místní doménu"}.
{"Unauthorized","Nemáte oprávnění"}.
{"Unexpected action","Neočekávaná akce"}.
{"Unregister a Jabber account","Zrušte registraci účtu Jabberu"}.
{"Unregister","Zrušit registraci"}.
{"Unsupported <index/> element","Nepodporovaný <index/> element"}.
{"Update message of the day (don't send)","Aktualizovat zprávu dne (neodesílat)"}.
{"Update message of the day on all hosts (don't send)","Aktualizovat zprávu dne pro všechny hostitele (neodesílat)"}.
{"Update ~p","Aktualizovat ~p"}.
{"Update plan","Aktualizovat plán"}.
{"Update script","Aktualizované skripty"}.
{"Update","Aktualizovat"}.
{"Uptime:","Čas běhu:"}.
{"User already exists","Uživatel již existuje"}.
{"User (jid)","Uživatel (JID)"}.
{"User Management","Správa uživatelů"}.
{"User session not found","Sezení uživatele nebylo nalezeno"}.
{"User session terminated","Sezení uživatele bylo ukončeno"}.
{"Username:","Uživatelské jméno:"}.
{"Users are not allowed to register accounts so quickly","Je zakázáno registrovat účty v tak rychlém sledu"}.
{"Users Last Activity","Poslední aktivita uživatele"}.
{"Users","Uživatelé"}.
{"User","Uživatel"}.
{"Validate","Ověřit"}.
{"Value 'get' of 'type' attribute is not allowed","Hodnota 'get' atrubutu 'type' není povolena"}.
{"Value 'set' of 'type' attribute is not allowed","Hodnota 'set' atrubutu 'type' není povolena"}.
{"vCard User Search","Hledání uživatelů ve vizitkách"}.
{"Virtual Hosts","Virtuální hostitelé"}.
{"Visitors are not allowed to change their nicknames in this room","Návštěvníkům této místnosti je zakázáno měnit přezdívku"}.
{"Visitors are not allowed to send messages to all occupants","Návštevníci nemají povoleno zasílat zprávy všem účastníkům v této místnosti"}.
{"Voice requests are disabled in this conference","Voice žádosti jsou v této místnosti zakázány"}.
{"Voice request","Žádost o voice práva"}.
{"Wednesday","Středa"}.
{"You can later change your password using a Jabber client.","Později můžete své heslo změnit pomocí klienta Jabberu."}.
{"You have been banned from this room","Byl jste vyloučen z této místnosti"}.
{"You have joined too many conferences","Vstoupil jste do příliš velkého množství místností"}.
{"You must fill in field \"Nickname\" in the form","Musíte vyplnit políčko \"Přezdívka\" ve formuláři"}.
{"You need a client that supports x:data and CAPTCHA to register","Pro registraci potřebujete klienta s podporou x:data a CAPTCHA"}.
{"You need a client that supports x:data to register the nickname","Pro registraci přezdívky potřebujete klienta s podporou x:data"}.
{"You need an x:data capable client to search","K vyhledávání potřebujete klienta podporujícího x:data"}.
{"Your active privacy list has denied the routing of this stanza.","Vaše nastavení soukromí znemožnilo směrování této stance."}.
{"Your contact offline message queue is full. The message has been discarded.","Fronta offline zpráv pro váš kontakt je plná. Zpráva byla zahozena."}.
{"Your Jabber account was successfully created.","Váš účet Jabberu byl úspěšně vytvořen."}.
{"Your Jabber account was successfully deleted.","Váš účet Jabberu byl úspěšně smazán."}.
{"You're not allowed to create nodes","Nemáte povoleno vytvářet uzly"}.
