%% -*- coding: utf-8 -*-
{" has set the subject to: "," puxo o asunto: "}.
{"A password is required to enter this room","Necesítase contrasinal para entrar nesta sala"}.
{"Accept","Aceptar"}.
{"Access denied by service policy","Acceso denegado pola política do servizo"}.
{"Action on user","Acción no usuario"}.
{"Add Jabber ID","Engadir ID Jabber"}.
{"Add New","Engadir novo"}.
{"Add User","Engadir usuario"}.
{"Administration of ","Administración de "}.
{"Administration","Administración"}.
{"Administrator privileges required","Necesítase privilexios de administrador"}.
{"All activity","Toda a actividade"}.
{"All Users","Todos os usuarios"}.
{"Allow users to change the subject","Permitir aos usuarios cambiar o asunto"}.
{"Allow users to query other users","Permitir aos usuarios consultar a outros usuarios"}.
{"Allow users to send invites","Permitir aos usuarios enviar invitacións"}.
{"Allow users to send private messages","Permitir aos usuarios enviar mensaxes privadas"}.
{"Allow visitors to change nickname","Permitir aos visitantes cambiarse o alcume"}.
{"Allow visitors to send private messages to","Permitir aos visitantes enviar mensaxes privadas a"}.
{"Allow visitors to send status text in presence updates","Permitir aos visitantes enviar texto de estado nas actualizacións depresenza"}.
{"Announcements","Anuncios"}.
{"April","Abril"}.
{"August","Agosto"}.
{"Automatic node creation is not enabled","A creación automática de nodos non está habilitada"}.
{"Backup Management","Xestión de copia de seguridade"}.
{"Backup of ~p","Copia de seguridade de ~p"}.
{"Backup to File at ","Copia de seguridade de arquivos en "}.
{"Backup","Copia de seguridade"}.
{"Bad format","Mal formato"}.
{"Birthday","Aniversario"}.
{"Both the username and the resource are required","Tanto o nome de usuario como o recurso son necesarios"}.
{"Bytestream already activated","Bytestream xa está activado"}.
{"Cannot remove active list","Non se pode eliminar a lista activa"}.
{"Cannot remove default list","Non se pode eliminar a lista predeterminada"}.
{"Change Password","Cambiar contrasinal"}.
{"Change User Password","Cambiar contrasinal de usuario"}.
{"Changing password is not allowed","Non se permite cambiar o contrasinal"}.
{"Changing role/affiliation is not allowed","O cambio de rol/afiliación non está permitido"}.
{"Characters not allowed:","Caracteres non permitidos:"}.
{"Chatroom configuration modified","Configuración da sala modificada"}.
{"Chatroom is created","Creouse a sala"}.
{"Chatroom is destroyed","Destruíuse a sala"}.
{"Chatroom is started","Iniciouse a sala"}.
{"Chatroom is stopped","Detívose a sala"}.
{"Chatrooms","Salas de charla"}.
{"Choose a username and password to register with this server","Escolle un nome de usuario e contrasinal para rexistrarche neste servidor"}.
{"Choose storage type of tables","Selecciona tipo de almacenamento das táboas"}.
{"Choose whether to approve this entity's subscription.","Decidir se aprobar a subscripción desta entidade."}.
{"City","Cidade"}.
{"Commands","Comandos"}.
{"Conference room does not exist","A sala de conferencias non existe"}.
{"Configuration","Configuración"}.
{"Connected Resources:","Recursos conectados:"}.
{"Country","País"}.
{"CPU Time:","Tempo da CPU:"}.
{"Database failure","Erro na base de datos"}.
{"Database Tables at ~p","Táboas da base de datos en ~p"}.
{"Database Tables Configuration at ","Configuración de táboas da base de datos en "}.
{"Database","Base de datos"}.
{"December","Decembro"}.
{"Default users as participants","Os usuarios son participantes por defecto"}.
{"Delete message of the day on all hosts","Borrar a mensaxe do día en todos os dominios"}.
{"Delete message of the day","Borrar mensaxe do dia"}.
{"Delete Selected","Eliminar os seleccionados"}.
{"Delete User","Borrar usuario"}.
{"Description:","Descrición:"}.
{"Disc only copy","Copia en disco soamente"}.
{"Displayed Groups:","Mostrar grupos:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Non digas o teu contrasinal a ninguén, nin sequera os administradores do servidor Jabber."}.
{"Dump Backup to Text File at ","Exporta copia de seguridade a ficheiro de texto en "}.
{"Dump to Text File","Exportar a ficheiro de texto"}.
{"Duplicated groups are not allowed by RFC6121","Os grupos duplicados non están permitidos por RFC6121"}.
{"Edit Properties","Editar Propiedades"}.
{"Either approve or decline the voice request.","Aproba ou rexeita a petición de voz."}.
{"ejabberd MUC module","Módulo de MUC para ejabberd"}.
{"ejabberd Multicast service","Servizo Multicast de ejabberd"}.
{"ejabberd Publish-Subscribe module","Módulo de Publicar-Subscribir de ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","Módulo SOCKS5 Bytestreams para ejabberd"}.
{"ejabberd vCard module","Módulo vCard para ejabberd"}.
{"ejabberd Web Admin","ejabberd Administrador Web"}.
{"Elements","Elementos"}.
{"Email","Email"}.
{"Enable logging","Gardar históricos"}.
{"Enabling push without 'node' attribute is not supported","Non se admite a activación do empuxe sen o atributo 'nodo'"}.
{"End User Session","Pechar sesión de usuario"}.
{"Enter nickname you want to register","Introduce o alcume que queiras rexistrar"}.
{"Enter path to backup file","Introduce ruta ao ficheiro de copia de seguridade"}.
{"Enter path to jabberd14 spool dir","Introduce a ruta ao directorio de jabberd14 spools"}.
{"Enter path to jabberd14 spool file","Introduce ruta ao ficheiro jabberd14 spool"}.
{"Enter path to text file","Introduce ruta ao ficheiro de texto"}.
{"Enter the text you see","Introduza o texto que ves"}.
{"Erlang Jabber Server","Servidor Jabber en Erlang"}.
{"Error","Erro"}.
{"Export all tables as SQL queries to a file:","Exportar todas as táboas a un ficheiro SQL:"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Exportar datos de todos os usuarios do servidor a ficheros PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Exportar datos dos usuarios dun dominio a ficheiros PIEFXIS (XEP-0227):"}.
{"External component failure","Fallo de compoñente externo"}.
{"External component timeout","Paso o tempo de espera do compoñente externo"}.
{"Failed to activate bytestream","Fallo ao activar bytestream"}.
{"Failed to extract JID from your voice request approval","Fallo ao extraer o Jabber ID da túa aprobación de petición de voz"}.
{"Failed to map delegated namespace to external component","O mapeo de espazo de nomes delegado fallou ao compoñente externo"}.
{"Failed to parse HTTP response","Non se puido analizar a resposta HTTP"}.
{"Family Name","Apelido"}.
{"February","Febreiro"}.
{"File larger than ~w bytes","O ficheiro é maior que ~w bytes"}.
{"Friday","Venres"}.
{"From","De"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Ver número de usuarios conectados"}.
{"Get Number of Registered Users","Ver número de usuarios rexistrados"}.
{"Get User Last Login Time","Ver data da última conexión de usuario"}.
{"Get User Password","Ver contrasinal de usuario"}.
{"Get User Statistics","Ver estatísticas de usuario"}.
{"Given Name","Nome"}.
{"Group ","Grupo "}.
{"Groups","Grupos"}.
{"has been banned","foi bloqueado"}.
{"has been kicked because of a system shutdown","foi expulsado porque o sistema vaise a deter"}.
{"has been kicked because of an affiliation change","foi expulsado debido a un cambio de afiliación"}.
{"has been kicked because the room has been changed to members-only","foi expulsado, porque a sala cambiouse a só-membros"}.
{"has been kicked","foi expulsado"}.
{"Host unknown","Dominio descoñecido"}.
{"Host","Host"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Si non ves a imaxe CAPTCHA aquí, visita a páxina web."}.
{"Import Directory","Importar directorio"}.
{"Import File","Importar ficheiro"}.
{"Import user data from jabberd14 spool file:","Importar usuario de ficheiro spool de jabberd14:"}.
{"Import User from File at ","Importa usuario desde ficheiro en "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importar usuarios en un fichero PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importar usuarios do directorio spool de jabberd14:"}.
{"Import Users from Dir at ","Importar usuarios desde o directorio en "}.
{"Import Users From jabberd14 Spool Files","Importar usuarios de ficheiros spool de jabberd-1.4"}.
{"Improper domain part of 'from' attribute","Parte de dominio impropio no atributo 'from'"}.
{"Improper message type","Tipo de mensaxe incorrecta"}.
{"Incoming s2s Connections:","Conexións S2S saíntes:"}.
{"Incorrect CAPTCHA submit","O CAPTCHA proporcionado é incorrecto"}.
{"Incorrect data form","Formulario de datos incorrecto"}.
{"Incorrect password","Contrasinal incorrecta"}.
{"Incorrect value of 'action' attribute","Valor incorrecto do atributo 'action'"}.
{"Incorrect value of 'action' in data form","Valor incorrecto de 'action' no formulario de datos"}.
{"Incorrect value of 'path' in data form","Valor incorrecto de 'path' no formulario de datos"}.
{"Insufficient privilege","Privilexio insuficiente"}.
{"Invalid 'from' attribute in forwarded message","Atributo 'from'' non é válido na mensaxe reenviada"}.
{"Invitations are not allowed in this conference","As invitacións non están permitidas nesta sala"}.
{"IP addresses","Direccións IP"}.
{"is now known as","agora coñécese como"}.
{"It is not allowed to send private messages of type \"groupchat\"","Non está permitido enviar mensaxes privadas do tipo \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Impedir o envio de mensaxes privadas á sala"}.
{"It is not allowed to send private messages","Non está permitido enviar mensaxes privadas"}.
{"Jabber Account Registration","Rexistro de conta Jabber"}.
{"Jabber ID","Jabber ID"}.
{"January","Xaneiro"}.
{"joins the room","entra na sala"}.
{"July","Xullo"}.
{"June","Xuño"}.
{"Last Activity","Última actividade"}.
{"Last login","Última conexión"}.
{"Last month","Último mes"}.
{"Last year","Último ano"}.
{"leaves the room","sae da sala"}.
{"List of rooms","Lista de salas"}.
{"Low level update script","Script de actualización a baixo nivel"}.
{"Make participants list public","A lista de participantes é pública"}.
{"Make room CAPTCHA protected","Protexer a sala con CAPTCHA"}.
{"Make room members-only","Sala só para membros"}.
{"Make room moderated","Facer sala moderada"}.
{"Make room password protected","Protexer a sala con contrasinal"}.
{"Make room persistent","Sala permanente"}.
{"Make room public searchable","Sala publicamente visible"}.
{"Malformed username","Nome de usuario mal formado"}.
{"March","Marzo"}.
{"Maximum Number of Occupants","Número máximo de ocupantes"}.
{"May","Maio"}.
{"Membership is required to enter this room","Necesitas ser membro desta sala para poder entrar"}.
{"Members:","Membros:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Memorice o seu contrasinal ou escribilo nun papel colocado nun lugar seguro. En Jabber non hai unha forma automatizada para recuperar o seu contrasinal si a esquece."}.
{"Memory","Memoria"}.
{"Message body","Corpo da mensaxe"}.
{"Message not found in forwarded payload","Mensaxe non atopada no contido reenviado"}.
{"Middle Name","Segundo nome"}.
{"Moderator privileges required","Necesítase privilexios de moderador"}.
{"Modified modules","Módulos Modificados"}.
{"Module failed to handle the query","O módulo non puido xestionar a consulta"}.
{"Monday","Luns"}.
{"Multicast","Multicast"}.
{"Multiple <item/> elements are not allowed by RFC6121","Múltiples elementos <item/> non están permitidos por RFC6121"}.
{"Multi-User Chat","Salas de Charla"}.
{"Name","Nome"}.
{"Name:","Nome:"}.
{"Neither 'jid' nor 'nick' attribute found","Non se atopou o atributo 'jid' nin 'nick'"}.
{"Neither 'role' nor 'affiliation' attribute found","Non se atopou o atributo 'role' nin 'affiliation'"}.
{"Never","Nunca"}.
{"New Password:","Novo contrasinal:"}.
{"Nickname Registration at ","Rexistro do alcume en "}.
{"Nickname","Alcume"}.
{"No 'affiliation' attribute found","Non se atopou o atributo de 'affiliation'"}.
{"No available resource found","Non se atopou ningún recurso"}.
{"No body provided for announce message","Non se proporcionou corpo de mensaxe para o anuncio"}.
{"No data form found","Non se atopou formulario de datos"}.
{"No Data","Sen datos"}.
{"No features available","Non hai características dispoñibles"}.
{"No hook has processed this command","Ningún evento procesou este comando"}.
{"No info about last activity found","Non se atopou información sobre a última actividade"}.
{"No 'item' element found","Non se atopou o elemento 'item'"}.
{"No items found in this query","Non se atoparon elementos nesta consulta"}.
{"No limit","Sen límite"}.
{"No module is handling this query","Ningún módulo manexa esta consulta"}.
{"No node specified","Non se especificou nodo"}.
{"No 'password' found in data form","Non se atopou 'password' no formulario de datos"}.
{"No 'password' found in this query","Non se atopou 'password' nesta solicitude"}.
{"No 'path' found in data form","Non se atopou 'path' neste formulario de datos"}.
{"No pending subscriptions found","Non se atoparon subscricións pendentes"}.
{"No privacy list with this name found","Non se atopou ningunha lista de privacidade con este nome"}.
{"No private data found in this query","Non se atopou ningún elemento de datos privado nesta solicitude"}.
{"No running node found","Non se atoparon nodos activos"}.
{"No services available","Non hai servizos dispoñibles"}.
{"No statistics found for this item","Non se atopou ningunha estatística para este elemento"}.
{"No 'to' attribute found in the invitation","O atributo 'to' non se atopou na invitación"}.
{"Node already exists","O nodo xa existe"}.
{"Node index not found","Non se atopou índice de nodo"}.
{"Node not found","Nodo non atopado"}.
{"Node ~p","Nodo ~p"}.
{"Nodeprep has failed","Nodeprep fallou"}.
{"Nodes","Nodos"}.
{"None","Ningún"}.
{"Not Found","Non atopado"}.
{"Not subscribed","Non subscrito"}.
{"November","Novembro"}.
{"Number of online users","Número de usuarios conectados"}.
{"Number of registered users","Número de usuarios rexistrados"}.
{"October","Outubro"}.
{"Offline Messages","Mensaxes diferidas"}.
{"Offline Messages:","Mensaxes sen conexión:"}.
{"OK","Aceptar"}.
{"Old Password:","Contrasinal anterior:"}.
{"Online Users","Usuarios conectados"}.
{"Online Users:","Usuarios conectados:"}.
{"Online","Conectado"}.
{"Only <enable/> or <disable/> tags are allowed","Só se permiten etiquetas <enable/> ou <disable/>"}.
{"Only <list/> element is allowed in this query","Só se admite o elemento <list/> nesta consulta"}.
{"Only members may query archives of this room","Só membros poden consultar o arquivo de mensaxes da sala"}.
{"Only moderators and participants are allowed to change the subject in this room","Só os moderadores e os participantes se lles permite cambiar o tema nesta sala"}.
{"Only moderators are allowed to change the subject in this room","Só os moderadores están autorizados a cambiar o tema nesta sala"}.
{"Only moderators can approve voice requests","Só os moderadores poden aprobar peticións de voz"}.
{"Only occupants are allowed to send messages to the conference","Só os ocupantes poden enviar mensaxes á sala"}.
{"Only occupants are allowed to send queries to the conference","Só os ocupantes poden enviar solicitudes á sala"}.
{"Only service administrators are allowed to send service messages","Só os administradores do servizo teñen permiso para enviar mensaxes de servizo"}.
{"Organization Name","Nome da organización"}.
{"Organization Unit","Unidade da organización"}.
{"Outgoing s2s Connections","Conexións S2S saíntes"}.
{"Outgoing s2s Connections:","Conexións S2S saíntes:"}.
{"Owner privileges required","Requírense privilexios de propietario da sala"}.
{"Packet","Paquete"}.
{"Password Verification","Verificación da contrasinal"}.
{"Password Verification:","Verificación da Contrasinal:"}.
{"Password","Contrasinal"}.
{"Password:","Contrasinal:"}.
{"Path to Dir","Ruta ao directorio"}.
{"Path to File","Ruta ao ficheiro"}.
{"Pending","Pendente"}.
{"Period: ","Periodo: "}.
{"Ping query is incorrect","A solicitude de Ping é incorrecta"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Ten en conta que estas opcións só farán copia de seguridade da base de datos Mnesia. Se está a utilizar o módulo de ODBC, tamén necesita unha copia de seguridade da súa base de datos SQL por separado."}.
{"Please, wait for a while before sending new voice request","Por favor, espera un pouco antes de enviar outra petición de voz"}.
{"Pong","Pong"}.
{"Possessing 'ask' attribute is not allowed by RFC6121","Posuír o atributo 'ask' non está permitido por RFC6121"}.
{"private, ","privado, "}.
{"Publish-Subscribe","Publicar-Subscribir"}.
{"PubSub subscriber request","Petición de subscriptor de PubSub"}.
{"Queries to the conference members are not allowed in this room","Nesta sala non se permiten solicitudes aos membros da sala"}.
{"Query to another users is forbidden","É prohibido enviar solicitudes a outros usuarios"}.
{"RAM and disc copy","Copia en RAM e disco"}.
{"RAM copy","Copia en RAM"}.
{"Really delete message of the day?","¿Está seguro que quere borrar a mensaxe do dia?"}.
{"Recipient is not in the conference room","O receptor non está na sala de conferencia"}.
{"Register a Jabber account","Rexistrar unha conta Jabber"}.
{"Registered Users","Usuarios rexistrados"}.
{"Registered Users:","Usuarios rexistrados:"}.
{"Register","Rexistrar"}.
{"Remote copy","Copia remota"}.
{"Remove All Offline Messages","Borrar Todas as Mensaxes Sen conexión"}.
{"Remove User","Eliminar usuario"}.
{"Remove","Borrar"}.
{"Replaced by new connection","Substituído por unha nova conexión"}.
{"Resources","Recursos"}.
{"Restart Service","Reiniciar o servizo"}.
{"Restart","Reiniciar"}.
{"Restore Backup from File at ","Restaura copia de seguridade desde o ficheiro en "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Restaurar copia de seguridade binaria no seguinte reinicio de ejabberd (require menos memoria):"}.
{"Restore binary backup immediately:","Restaurar inmediatamente copia de seguridade binaria:"}.
{"Restore plain text backup immediately:","Restaurar copias de seguridade de texto plano inmediatamente:"}.
{"Restore","Restaurar"}.
{"Room Configuration","Configuración da Sala"}.
{"Room creation is denied by service policy","Denegar crear a sala por política do servizo"}.
{"Room description","Descrición da sala"}.
{"Room Occupants","Ocupantes da sala"}.
{"Room title","Título da sala"}.
{"Roster size","Tamaño da lista de contactos"}.
{"Roster","Lista de contactos"}.
{"RPC Call Error","Erro na chamada RPC"}.
{"Running Nodes","Nodos funcionando"}.
{"Saturday","Sábado"}.
{"Script check","Comprobación de script"}.
{"Search Results for ","Buscar resultados por "}.
{"Search users in ","Buscar usuarios en "}.
{"Send announcement to all online users on all hosts","Enviar anuncio a todos os usuarios conectados en todos os dominios"}.
{"Send announcement to all online users","Enviar anuncio a todos os usuarios conectados"}.
{"Send announcement to all users on all hosts","Enviar anuncio a todos os usuarios en todos os dominios"}.
{"Send announcement to all users","Enviar anuncio a todos os usuarios"}.
{"September","Setembro"}.
{"Server:","Servidor:"}.
{"Set message of the day and send to online users","Pór mensaxe do dia e enviar a todos os usuarios conectados"}.
{"Set message of the day on all hosts and send to online users","Pór mensaxe do día en todos os dominios e enviar aos usuarios conectados"}.
{"Shared Roster Groups","Grupos Compartidos"}.
{"Show Integral Table","Mostrar Táboa Integral"}.
{"Show Ordinary Table","Mostrar Táboa Ordinaria"}.
{"Shut Down Service","Deter o servizo"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Algúns clientes Jabber pode almacenar o contrasinal no computador, pero debe facer isto só no seu computador persoal por razóns de seguridade."}.
{"Statistics of ~p","Estatísticas de ~p"}.
{"Statistics","Estatísticas"}.
{"Stop","Deter"}.
{"Stopped Nodes","Nodos detidos"}.
{"Storage Type","Tipo de almacenamento"}.
{"Store binary backup:","Gardar copia de seguridade binaria:"}.
{"Store plain text backup:","Gardar copia de seguridade en texto plano:"}.
{"Subject","Asunto"}.
{"Submit","Enviar"}.
{"Submitted","Enviado"}.
{"Subscriptions are not allowed","Non se permiten subscricións"}.
{"Subscription","Subscripción"}.
{"Sunday","Domingo"}.
{"That nickname is already in use by another occupant","Ese alcume xa está a ser usado por outro ocupante"}.
{"That nickname is registered by another person","O alcume xa está rexistrado por outra persoa"}.
{"The CAPTCHA is valid.","O CAPTCHA é válido."}.
{"The CAPTCHA verification has failed","A verificación de CAPTCHA fallou"}.
{"The feature requested is not supported by the conference","A sala de conferencias non admite a función solicitada"}.
{"The password contains unacceptable characters","O contrasinal contén caracteres inaceptables"}.
{"The password is too weak","O contrasinal é demasiado débil"}.
{"the password is","a contrasinal é"}.
{"The password of your Jabber account was successfully changed.","O contrasinal da súa conta Jabber cambiouse correctamente."}.
{"The query is only allowed from local users","A solicitude só se permite para usuarios locais"}.
{"The query must not contain <item/> elements","A solicitude non debe conter elementos <item/>"}.
{"The stanza MUST contain only one <active/> element, one <default/> element, or one <list/> element","A estroa DEBEN conter un elemento <active/>, un elemento <default/> ou un elemento <list/>"}.
{"There was an error changing the password: ","Produciuse un erro ao cambiar o contrasinal: "}.
{"There was an error creating the account: ","Produciuse un erro ao crear a conta: "}.
{"There was an error deleting the account: ","Produciuse un erro ao eliminar a conta: "}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Esta é insensible: Macbeth é o mesmo que MacBeth e Macbeth."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Esta páxina permite crear unha conta Jabber neste servidor Jabber. o seu JID (Jabber IDentificador) será da forma: nomeusuario@servidor. Por favor le coidadosamente as instrucións para encher correctamente os campos."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Esta páxina permite anular o rexistro dunha conta Jabber neste servidor Jabber."}.
{"This room is not anonymous","Sala non anónima"}.
{"Thursday","Xoves"}.
{"Time delay","Atraso temporal"}.
{"Time","Data"}.
{"Token TTL","Token TTL"}.
{"Too many active bytestreams","Demasiados bytestreams activos"}.
{"Too many CAPTCHA requests","Demasiadas solicitudes CAPTCHA"}.
{"Too many <item/> elements","Demasiados elementos <item/>"}.
{"Too many <list/> elements","Demasiados elementos <list/>"}.
{"Too many unacked stanzas","Demasiadas mensaxes sen recoñecer recibilos"}.
{"Too many users in this conference","Demasiados usuarios nesta sala"}.
{"To","Para"}.
{"Total rooms","Salas totais"}.
{"Traffic rate limit is exceeded","Hase exedido o límite de tráfico"}.
{"Transactions Aborted:","Transaccións abortadas:"}.
{"Transactions Committed:","Transaccións finalizadas:"}.
{"Transactions Logged:","Transaccións rexistradas:"}.
{"Transactions Restarted:","Transaccións reiniciadas:"}.
{"Tuesday","Martes"}.
{"Unable to generate a CAPTCHA","No se pudo generar un CAPTCHA"}.
{"Unable to register route on existing local domain","Non se pode rexistrar a ruta no dominio local existente"}.
{"Unauthorized","Non autorizado"}.
{"Unexpected action","Acción inesperada"}.
{"Unregister a Jabber account","Eliminar o rexistro dunha conta Jabber"}.
{"Unregister","Eliminar rexistro"}.
{"Unsupported <index/> element","Elemento <index/> non soportado"}.
{"Update message of the day (don't send)","Actualizar mensaxe do dia, pero non envialo"}.
{"Update message of the day on all hosts (don't send)","Actualizar a mensaxe do día en todos os dominos (pero non envialo)"}.
{"Update ~p","Actualizar ~p"}.
{"Update plan","Plan de actualización"}.
{"Update script","Script de actualización"}.
{"Update","Actualizar"}.
{"Uptime:","Tempo desde o inicio:"}.
{"User already exists","O usuario xa existe"}.
{"User (jid)","Usuario (jid)"}.
{"User Management","Administración de usuarios"}.
{"User session not found","Sesión de usuario non atopada"}.
{"User session terminated","Sesión de usuario completada"}.
{"Username:","Nome de usuario:"}.
{"Users are not allowed to register accounts so quickly","Os usuarios non están autorizados a rexistrar contas con tanta rapidez"}.
{"Users Last Activity","Última actividade dos usuarios"}.
{"Users","Usuarios"}.
{"User","Usuario"}.
{"Validate","Validar"}.
{"Value 'get' of 'type' attribute is not allowed","O valor \"get\" do atributo 'type' non está permitido"}.
{"Value 'set' of 'type' attribute is not allowed","O valor \"set\" do atributo 'type' non está permitido"}.
{"vCard User Search","vCard busqueda de usuario"}.
{"Virtual Hosts","Hosts Virtuais"}.
{"Visitors are not allowed to change their nicknames in this room","Os visitantes non teñen permitido cambiar os seus alcumes nesta sala"}.
{"Visitors are not allowed to send messages to all occupants","Os visitantes non poden enviar mensaxes a todos os ocupantes"}.
{"Voice request","Petición de voz"}.
{"Voice requests are disabled in this conference","As peticións de voz están desactivadas nesta sala"}.
{"Wednesday","Mércores"}.
{"You can later change your password using a Jabber client.","Máis tarde, pode cambiar o seu contrasinal utilizando un cliente Jabber."}.
{"You have been banned from this room","Fuches bloqueado nesta sala"}.
{"You have joined too many conferences","Entrou en demasiadas salas de conferencia"}.
{"You must fill in field \"Nickname\" in the form","Debes encher o campo \"Alcumo\" no formulario"}.
{"You need a client that supports x:data and CAPTCHA to register","Necesitas un cliente con soporte de x:data e CAPTCHA para rexistrarche"}.
{"You need a client that supports x:data to register the nickname","Necesitas un cliente con soporte de x:data para poder rexistrar o alcume"}.
{"You need an x:data capable client to search","Necesitas un cliente con soporte de x:data para poder buscar"}.
{"Your active privacy list has denied the routing of this stanza.","A súa lista de privacidade activa negou o encaminamiento desta estrofa."}.
{"Your contact offline message queue is full. The message has been discarded.","A túa cola de mensaxes diferidas de contactos está chea. A mensaxe descartouse."}.
{"Your Jabber account was successfully created.","A súa conta Jabber creouse correctamente."}.
{"Your Jabber account was successfully deleted.","A súa conta Jabber eliminouse correctamente."}.
{"You're not allowed to create nodes","Non tes permiso para crear nodos"}.
