%% -*- coding: latin-1 -*-
{"Access Configuration","Configurazione dell'accesso"}.
{"Access Control List Configuration","Configurazione dei diritti di accesso (ACL)"}.
{"Access control lists","Diritti di accesso (ACL)"}.
{"Access Control Lists","Diritti di accesso (ACL)"}.
{"Access denied by service policy","Accesso impedito dalle politiche del servizio"}.
{"Access rules","Regole di accesso"}.
{"Access Rules","Regole di accesso"}.
{"Action on user","Azione sull'utente"}.
{"Add Jabber ID","Aggiungere un Jabber ID (Jabber ID)"}.
{"Add New","Aggiungere nuovo"}.
{"Add User","Aggiungere un utente"}.
{"Administration","Amministrazione"}.
{"Administration of ","Amministrazione di "}.
{"Administrator privileges required","Necessari i privilegi di amministratore"}.
{"A friendly name for the node","Un nome comodo per il nodo"}.
{"All activity","Tutta l'attività"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Consentire a questo Jabber ID l'iscrizione a questo nodo pubsub?"}.
{"Allow users to change the subject","Consentire agli utenti di cambiare l'oggetto"}.
{"Allow users to query other users","Consentire agli utenti query verso altri utenti"}.
{"Allow users to send invites","Consentire agli utenti l'invio di inviti"}.
{"Allow users to send private messages","Consentire agli utenti l'invio di messaggi privati"}.
{"Allow visitors to change nickname","Consentire ai visitatori di cambiare il nickname"}.
{"Allow visitors to send private messages to","Consentire agli ospiti l'invio di messaggi privati a"}.
{"Allow visitors to send status text in presence updates","Consentire ai visitatori l'invio di testo sullo stato in aggiornamenti sulla presenza"}.
{"Allow visitors to send voice requests","Consentire agli ospiti l'invio di richieste di parola"}.
{"All Users","Tutti gli utenti"}.
{"Announcements","Annunci"}.
{"anyone","tutti"}.
{"A password is required to enter this room","Per entrare in questa stanza è prevista una password"}.
{"April","Aprile"}.
{"August","Agosto"}.
{"Backup Management","Gestione dei salvataggi"}.
{"Backup","Salvare"}.
{"Backup to File at ","Salvataggio sul file "}.
{"Bad format","Formato non valido"}.
{"Birthday","Compleanno"}.
{"CAPTCHA web page","Pagina web CAPTCHA"}.
{"Change Password","Modificare la password"}.
{"Change User Password","Cambiare la password dell'utente"}.
{"Characters not allowed:","Caratteri non consentiti:"}.
{"Chatroom configuration modified","Configurazione della stanza modificata"}.
{"Chatroom is created","La stanza è creata"}.
{"Chatroom is destroyed","La stanza è eliminata"}.
{"Chatroom is started","La stanza è avviata"}.
{"Chatroom is stopped","La stanza è arrestata"}.
{"Chatrooms","Stanze"}.
{"Choose a username and password to register with this server","Scegliere un nome utente e una password per la registrazione con questo server"}.
{"Choose modules to stop","Selezionare i moduli da arrestare"}.
{"Choose storage type of tables","Selezionare una modalità di conservazione delle tabelle"}.
{"Choose whether to approve this entity's subscription.","Scegliere se approvare l'iscrizione per questa entità"}.
{"City","Città"}.
{"Commands","Comandi"}.
{"Conference room does not exist","La stanza per conferenze non esiste"}.
{"Configuration","Configurazione"}.
{"Configuration of room ~s","Configurazione per la stanza ~s"}.
{"Connected Resources:","Risorse connesse:"}.
{"Connections parameters","Parametri delle connessioni"}.
{"Country","Paese"}.
{"CPU Time:","Tempo CPU:"}.
{"Database","Database"}.
{"Database Tables Configuration at ","Configurazione delle tabelle del database su "}.
{"December","Dicembre"}.
{"Default users as participants","Definire per default gli utenti come partecipanti"}.
{"Delete message of the day","Eliminare il messaggio del giorno (MOTD)"}.
{"Delete message of the day on all hosts","Eliminare il messaggio del giorno (MOTD) su tutti gli host"}.
{"Delete Selected","Eliminare gli elementi selezionati"}.
{"Delete User","Eliminare l'utente"}.
{"Deliver event notifications","Inviare notifiche degli eventi"}.
{"Deliver payloads with event notifications","Inviare il contenuto del messaggio con la notifica dell'evento"}.
{"Description:","Descrizione:"}.
{"Disc only copy","Copia su disco soltanto"}.
{"Displayed Groups:","Gruppi visualizzati:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Non comunicare la tua password a nessuno, neppure agli amministratori del server Jabber."}.
{"Dump Backup to Text File at ","Trascrivere il salvataggio sul file di testo "}.
{"Dump to Text File","Trascrivere su file di testo"}.
{"Edit Properties","Modificare le proprietà"}.
{"Either approve or decline the voice request.","Approva oppure respingi la richiesta di parola."}.
{"ejabberd IRC module","Modulo IRC per ejabberd"}.
{"ejabberd MUC module","Modulo MUC per ejabberd"}.
{"ejabberd Publish-Subscribe module","Modulo Pubblicazione/Iscrizione (PubSub) per ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","Modulo SOCKS5 Bytestreams per ejabberd"}.
{"ejabberd vCard module","Modulo vCard per ejabberd"}.
{"ejabberd Web Admin","Amministrazione web ejabberd"}.
{"Elements","Elementi"}.
{"Email","E-mail"}.
{"Enable logging","Abilitare i log"}.
{"Encoding for server ~b","Codifica per il server ~b"}.
{"End User Session","Terminare la sessione dell'utente"}.
{"Enter list of {Module, [Options]}","Immettere un elenco di {Modulo, [Opzioni]}"}.
{"Enter nickname you want to register","Immettere il nickname che si vuole registrare"}.
{"Enter path to backup file","Immettere il percorso del file di salvataggio"}.
{"Enter path to jabberd14 spool dir","Immettere il percorso della directory di spool di jabberd14"}.
{"Enter path to jabberd14 spool file","Immettere il percorso del file di spool di jabberd14"}.
{"Enter path to text file","Immettere il percorso del file di testo"}.
{"Enter the text you see","Immettere il testo visibile"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","Immettere il nome utente e le codifiche che si desidera utilizzare per la connessione ai server IRC. Premere \"Avanti\" per vedere i successivi campi da compilare. Premere \"Fatto\" per salvare le impostazioni."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","Immettere il nome utente, le codifiche, le porte e le password che si desidera utilizzare per la connessione ai server IRC"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Errore"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","Esempio: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"segreto\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.serverdiprova.net\", \"utf-8\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","Escludi degli ID Jabber dal passaggio CAPTCHA"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Esportare i dati di tutti gli utenti nel server in file PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Esportare i dati degli utenti di un host in file PIEFXIS (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","Impossibile estrarre il JID dall'approvazione della richiesta di parola"}.
{"Family Name","Cognome"}.
{"February","Febbraio"}.
{"Fill in fields to search for any matching Jabber User","Riempire i campi per la ricerca di utenti Jabber corrispondenti ai criteri"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Riempire il modulo per la ricerca di utenti Jabber corrispondenti ai criteri (Aggiungere * alla fine del campo per la ricerca di una sottostringa"}.
{"Friday","Venerdì"}.
{"From","Da"}.
{"From ~s","Da ~s"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Ottenere il numero di utenti online"}.
{"Get Number of Registered Users","Ottenere il numero di utenti registrati"}.
{"Get User Last Login Time","Ottenere la data di ultimo accesso dell'utente"}.
{"Get User Password","Ottenere la password dell'utente"}.
{"Get User Statistics","Ottenere le statistiche dell'utente"}.
{"Grant voice to this person?","Dare parola a questa persona?"}.
{"Group ","Gruppo "}.
{"Groups","Gruppi"}.
{"has been banned","è stata/o bandita/o"}.
{"has been kicked because of an affiliation change","è stato espulso a causa di un cambiamento di appartenenza"}.
{"has been kicked because of a system shutdown","è stato espulso a causa dello spegnimento del sistema"}.
{"has been kicked because the room has been changed to members-only","è stato espulso per la limitazione della stanza ai soli membri"}.
{"has been kicked","è stata/o espulsa/o"}.
{" has set the subject to: "," ha modificato l'oggetto in: "}.
{"Host","Host"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Se qui non vedi l'immagine CAPTCHA, visita la pagina web."}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","Se si vogliono specificare differenti porte, password, codifiche per i server IRC, si riempia questo elenco con valori nel formato '{\"server IRC\", \"codifica\", porta, \"password\"}'. Per default questo servizio utilizza la codifica \"~s\", la porta ~p, la password vuota."}.
{"Import Directory","Importare una directory"}.
{"Import File","Importare un file"}.
{"Import user data from jabberd14 spool file:","Importare i dati utente da file di spool di jabberd14:"}.
{"Import User from File at ","Importare un utente dal file "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importare i dati utenti da un file PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importare i dati utenti da directory di spool di jabberd14:"}.
{"Import Users from Dir at ","Importare utenti dalla directory "}.
{"Import Users From jabberd14 Spool Files","Importare utenti da file di spool di jabberd14"}.
{"Improper message type","Tipo di messaggio non corretto"}.
{"Incorrect password","Password non esatta"}.
{"Invalid affiliation: ~s","Affiliazione non valida: ~s"}.
{"Invalid role: ~s","Ruolo non valido: ~s"}.
{"IP addresses","Indirizzi IP"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","Canale IRC (senza il # iniziale)"}.
{"IRC server","Server IRC"}.
{"IRC settings","Impostazioni IRC"}.
{"IRC Transport","Transport IRC"}.
{"IRC username","Nome utente IRC"}.
{"IRC Username","Nome utente IRC"}.
{"is now known as","è ora conosciuta/o come"}.
{"It is not allowed to send private messages","Non è consentito l'invio di messaggi privati"}.
{"It is not allowed to send private messages of type \"groupchat\"","Non è consentito l'invio di messaggi privati di tipo \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Non è consentito l'invio di messaggi privati alla conferenza"}.
{"Jabber Account Registration","Registrazione account Jabber"}.
{"Jabber ID","Jabber ID (Jabber ID)"}.
{"Jabber ID ~s is invalid","Il Jabber ID ~s non è valido"}.
{"January","Gennaio"}.
{"Join IRC channel","Entra nel canale IRC"}.
{"joins the room","entra nella stanza"}.
{"Join the IRC channel here.","Entra nel canale IRC qui."}.
{"Join the IRC channel in this Jabber ID: ~s","Entra nel canale IRC in questo ID Jabber: ~s"}.
{"July","Luglio"}.
{"June","Giugno"}.
{"Last Activity","Ultima attività"}.
{"Last login","Ultimo accesso"}.
{"Last month","Ultimo mese"}.
{"Last year","Ultimo anno"}.
{"leaves the room","esce dalla stanza"}.
{"Listened Ports at ","Porte in ascolto su "}.
{"Listened Ports","Porte in ascolto"}.
{"List of modules to start","Elenco dei moduli da avviare"}.
{"Low level update script","Script di aggiornamento di basso livello"}.
{"Make participants list public","Rendere pubblica la lista dei partecipanti"}.
{"Make room CAPTCHA protected","Rendere la stanza protetta da CAPTCHA"}.
{"Make room members-only","Rendere la stanza riservata ai membri"}.
{"Make room moderated","Rendere la stanza moderata"}.
{"Make room password protected","Rendere la stanza protetta da password"}.
{"Make room persistent","Rendere la stanza persistente"}.
{"Make room public searchable","Rendere la sala visibile al pubblico"}.
{"March","Marzo"}.
{"Maximum Number of Occupants","Numero massimo di occupanti"}.
{"Max # of items to persist","Numero massimo di elementi da conservare persistentemente"}.
{"Max payload size in bytes","Dimensione massima del contenuto del messaggio in byte"}.
{"May","Maggio"}.
{"Membership is required to enter this room","Per entrare in questa stanza è necessario essere membro"}.
{"Members:","Membri:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Memorizza la password, o scrivila su un foglio di carta da conservare in un luogo sicuro. Jabber non prevede una modalità automatica per il recupero di una password dimenticata."}.
{"Memory","Memoria"}.
{"Message body","Corpo del messaggio"}.
{"Middle Name","Altro nome"}.
{"Minimum interval between voice requests (in seconds)","Intervallo minimo fra due richieste di parola (in secondi)"}.
{"Moderator privileges required","Necessari i privilegi di moderatore"}.
{"moderators only","moderatori soltanto"}.
{"Modified modules","Moduli modificati"}.
{"Module","Modulo"}.
{"Modules","Moduli"}.
{"Monday","Lunedì"}.
{"Name:","Nome:"}.
{"Name","Nome"}.
{"Never","Mai"}.
{"New Password:","Nuova password:"}.
{"Nickname","Nickname"}.
{"Nickname Registration at ","Registrazione di un nickname su "}.
{"Nickname ~s does not exist in the room","Il nickname ~s non esiste nella stanza"}.
{"nobody","nessuno"}.
{"No body provided for announce message","Nessun corpo fornito per il messaggio di annuncio"}.
{"No Data","Nessuna informazione"}.
{"Node ID","ID del nodo"}.
{"Node not found","Nodo non trovato"}.
{"Nodes","Nodi"}.
{"No limit","Nessun limite"}.
{"None","Nessuno"}.
{"No resource provided","Nessuna risorsa fornita"}.
{"Not Found","Non trovato"}.
{"Notify subscribers when items are removed from the node","Notificare gli iscritti quando sono eliminati degli elementi dal nodo"}.
{"Notify subscribers when the node configuration changes","Notificare gli iscritti quando la configurazione del nodo cambia"}.
{"Notify subscribers when the node is deleted","Notificare gli iscritti quando il nodo è cancellato"}.
{"November","Novembre"}.
{"Number of occupants","Numero di presenti"}.
{"Number of online users","Numero di utenti online"}.
{"Number of registered users","Numero di utenti registrati"}.
{"October","Ottobre"}.
{"Offline Messages:","Messaggi offline:"}.
{"Offline Messages","Messaggi offline"}.
{"OK","OK"}.
{"Old Password:","Vecchia password:"}.
{"Online","Online"}.
{"Online Users:","Utenti connessi:"}.
{"Online Users","Utenti online"}.
{"Only deliver notifications to available users","Inviare le notifiche solamente agli utenti disponibili"}.
{"Only moderators and participants are allowed to change the subject in this room","La modifica dell'oggetto di questa stanza è consentita soltanto ai moderatori e ai partecipanti"}.
{"Only moderators are allowed to change the subject in this room","La modifica dell'oggetto di questa stanza è consentita soltanto ai moderatori"}.
{"Only moderators can approve voice requests","Soltanto i moderatori possono approvare richieste di parola"}.
{"Only occupants are allowed to send messages to the conference","L'invio di messaggi alla conferenza è consentito soltanto ai presenti"}.
{"Only occupants are allowed to send queries to the conference","L'invio di query alla conferenza è consentito ai soli presenti"}.
{"Only service administrators are allowed to send service messages","L'invio di messaggi di servizio è consentito solamente agli amministratori del servizio"}.
{"Options","Opzioni"}.
{"Organization Name","Nome dell'organizzazione"}.
{"Organization Unit","Unità dell'organizzazione"}.
{"Outgoing s2s Connections:","Connessioni s2s in uscita:"}.
{"Outgoing s2s Connections","Connessioni s2s in uscita"}.
{"Owner privileges required","Necessari i privilegi di proprietario"}.
{"Packet","Pacchetto"}.
{"Password ~b","Password ~b"}.
{"Password:","Password:"}.
{"Password","Password"}.
{"Password Verification:","Verifica della password:"}.
{"Password Verification","Verifica della password"}.
{"Path to Dir","Percorso della directory"}.
{"Path to File","Percorso del file"}.
{"Pending","Pendente"}.
{"Period: ","Periodo:"}.
{"Persist items to storage","Conservazione persistente degli elementi"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","N.B.: Queste opzioni comportano il salvataggio solamente del database interno Mnesia. Se si sta utilizzando il modulo ODBC, è necessario salvare anche il proprio database SQL separatamente."}.
{"Please, wait for a while before sending new voice request","Attendi qualche istante prima di inviare una nuova richiesta di parola"}.
{"Pong","Pong"}.
{"Port ~b","Porta ~b"}.
{"Port","Porta"}.
{"Present real Jabber IDs to","Rendere visibile il Jabber ID reale a"}.
{"private, ","privato, "}.
{"Protocol","Protocollo"}.
{"Publish-Subscribe","Pubblicazione-Iscrizione"}.
{"PubSub subscriber request","Richiesta di iscrizione per PubSub"}.
{"Purge all items when the relevant publisher goes offline","Cancella tutti gli elementi quando chi li ha pubblicati non è più online"}.
{"Queries to the conference members are not allowed in this room","In questa stanza non sono consentite query ai membri della conferenza"}.
{"RAM and disc copy","Copia in memoria (RAM) e su disco"}.
{"RAM copy","Copia in memoria (RAM)"}.
{"Raw","Grezzo"}.
{"Really delete message of the day?","Si conferma l'eliminazione del messaggio del giorno (MOTD)?"}.
{"Recipient is not in the conference room","Il destinatario non è nella stanza per conferenze"}.
{"Register a Jabber account","Registra un account Jabber"}.
{"Registered Users:","Utenti registrati:"}.
{"Registered Users","Utenti registrati"}.
{"Register","Registra"}.
{"Registration in mod_irc for ","Registrazione in mod_irc per "}.
{"Remote copy","Copia remota"}.
{"Remove All Offline Messages","Eliminare tutti i messaggi offline"}.
{"Remove","Eliminare"}.
{"Remove User","Eliminare l'utente"}.
{"Replaced by new connection","Sostituito da una nuova connessione"}.
{"Resources","Risorse"}.
{"Restart","Riavviare"}.
{"Restart Service","Riavviare il servizio"}.
{"Restore Backup from File at ","Recuperare il salvataggio dal file "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Recuperare un salvataggio binario dopo il prossimo riavvio di ejabberd (necessita di meno memoria):"}.
{"Restore binary backup immediately:","Recuperare un salvataggio binario adesso:"}.
{"Restore plain text backup immediately:","Recuperare un salvataggio come semplice testo adesso:"}.
{"Restore","Recuperare"}.
{"Room Configuration","Configurazione della stanza"}.
{"Room creation is denied by service policy","La creazione di stanze è impedita dalle politiche del servizio"}.
{"Room description","Descrizione della stanza"}.
{"Room Occupants","Presenti nella stanza"}.
{"Room title","Titolo della stanza"}.
{"Roster groups allowed to subscribe","Gruppi roster abilitati alla registrazione"}.
{"Roster","Lista dei contatti"}.
{"Roster of ","Lista dei contatti di "}.
{"Roster size","Dimensione della lista dei contatti"}.
{"RPC Call Error","Errore di chiamata RPC"}.
{"Running Nodes","Nodi attivi"}.
{"~s access rule configuration","Configurazione delle regole di accesso per ~s"}.
{"Saturday","Sabato"}.
{"Script check","Verifica dello script"}.
{"Search Results for ","Risultati della ricerca per "}.
{"Search users in ","Cercare utenti in "}.
{"Send announcement to all online users","Inviare l'annuncio a tutti gli utenti online"}.
{"Send announcement to all online users on all hosts","Inviare l'annuncio a tutti gli utenti online su tutti gli host"}.
{"Send announcement to all users","Inviare l'annuncio a tutti gli utenti"}.
{"Send announcement to all users on all hosts","Inviare l'annuncio a tutti gli utenti su tutti gli host"}.
{"September","Settembre"}.
{"Server ~b","Server ~b"}.
{"Server:","Server:"}.
{"Set message of the day and send to online users","Impostare il messaggio del giorno (MOTD) ed inviarlo agli utenti online"}.
{"Set message of the day on all hosts and send to online users","Impostare il messaggio del giorno (MOTD) su tutti gli host e inviarlo agli utenti online"}.
{"Shared Roster Groups","Gruppi di liste di contatti comuni"}.
{"Show Integral Table","Mostrare la tabella integrale"}.
{"Show Ordinary Table","Mostrare la tabella normale"}.
{"Shut Down Service","Terminare il servizio"}.
{"~s invites you to the room ~s","~s ti invita nella stanza ~s"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Alcuni client Jabber possono conservare la password nel tuo computer. Utilizza tale funzione soltanto se ritieni che il tuo computer sia sicuro."}.
{"Specify the access model","Specificare il modello di accesso"}.
{"Specify the event message type","Specificare il tipo di messaggio di evento"}.
{"Specify the publisher model","Definire il modello di pubblicazione"}.
{"~s's Offline Messages Queue","Coda di ~s messaggi offline"}.
{"Start","Avviare"}.
{"Start Modules at ","Avviare moduli su "}.
{"Start Modules","Avviare moduli"}.
{"Statistics of ~p","Statistiche di ~p"}.
{"Statistics","Statistiche"}.
{"Stop","Arrestare"}.
{"Stop Modules","Arrestare moduli"}.
{"Stop Modules at ","Arrestare moduli su "}.
{"Stopped Nodes","Nodi arrestati"}.
{"Storage Type","Tipo di conservazione"}.
{"Store binary backup:","Conservare un salvataggio binario:"}.
{"Store plain text backup:","Conservare un salvataggio come semplice testo:"}.
{"Subject","Oggetto"}.
{"Submit","Inviare"}.
{"Submitted","Inviato"}.
{"Subscriber Address","Indirizzo dell'iscritta/o"}.
{"Subscription","Iscrizione"}.
{"Sunday","Domenica"}.
{"That nickname is already in use by another occupant","Il nickname è già in uso all'interno della conferenza"}.
{"That nickname is registered by another person","Questo nickname è registrato da un'altra persona"}.
{"The CAPTCHA is valid.","Il CAPTCHA è valido."}.
{"The CAPTCHA verification has failed","La verifica del CAPTCHA ha avuto esito negativo"}.
{"The collections with which a node is affiliated","Le collezioni a cui è affiliato un nodo"}.
{"the password is","la password è"}.
{"The password is too weak","La password è troppo debole"}.
{"The password of your Jabber account was successfully changed.","Il cambio di password del tuo account Jabber è andato a buon fine."}.
{"There was an error changing the password: ","Si è verificato un errore nel cambio di password: "}.
{"There was an error creating the account: ","Si è verificato un errore nella creazione dell'account: "}.
{"There was an error deleting the account: ","Si è verificato un errore nella cancellazione dell'account: "}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Non fa differenza fra minuscolo e maiuscolo: macbeth, MacBeth e Macbeth si equivalgono."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Questa pagina consente di creare un account Jabber in questo server Jabber. Il tuo JID (Jabber IDentifier) avrà la forma: nome_utente@server. Leggi attentamente le istruzioni per compilare i campi correttamente."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Questa pagina consente di eliminare un account Jabber da questo server Jabber."}.
{"Thursday","Giovedì"}.
{"Time delay","Ritardo"}.
{"Time","Ora"}.
{"To","A"}.
{"Too many CAPTCHA requests","Troppe richieste CAPTCHA"}.
{"To ~s","A ~s"}.
{"Traffic rate limit is exceeded","Limite di traffico superato"}.
{"Transactions Aborted:","Transazioni abortite:"}.
{"Transactions Committed:","Transazioni avvenute:"}.
{"Transactions Logged:","Transazioni con log:"}.
{"Transactions Restarted:","Transazioni riavviate:"}.
{"Tuesday","Martedì"}.
{"Unable to generate a CAPTCHA","Impossibile generare un CAPTCHA"}.
{"Unauthorized","Non autorizzato"}.
{"Unregister a Jabber account","Elimina un account Jabber"}.
{"Unregister","Elimina"}.
{"Update","Aggiornare"}.
{"Update message of the day (don't send)","Aggiornare il messaggio del giorno (MOTD) (non inviarlo)"}.
{"Update message of the day on all hosts (don't send)","Aggiornare il messaggio del giorno (MOTD) su tutti gli host (non inviarlo)"}.
{"Update plan","Piano di aggiornamento"}.
{"Update script","Script di aggiornamento"}.
{"Uptime:","Tempo dall'avvio:"}.
{"Use of STARTTLS required","Utilizzo di STARTTLS obbligatorio"}.
{"User JID","JID utente"}.
{"User Management","Gestione degli utenti"}.
{"Username:","Nome utente:"}.
{"Users are not allowed to register accounts so quickly","Non è consentito agli utenti registrare account così rapidamente"}.
{"Users Last Activity","Ultima attività degli utenti"}.
{"Users","Utenti"}.
{"User","Utente"}.
{"Validate","Validare"}.
{"vCard User Search","Ricerca di utenti per vCard"}.
{"Virtual Hosts","Host Virtuali"}.
{"Visitors are not allowed to change their nicknames in this room","Non è consentito ai visitatori cambiare il nickname in questa stanza"}.
{"Visitors are not allowed to send messages to all occupants","Non è consentito ai visitatori l'invio di messaggi a tutti i presenti"}.
{"Voice request","Richiesta di parola"}.
{"Voice requests are disabled in this conference","In questa conferenza le richieste di parola sono escluse"}.
{"Wednesday","Mercoledì"}.
{"When to send the last published item","Quando inviare l'ultimo elemento pubblicato"}.
{"Whether to allow subscriptions","Consentire iscrizioni?"}.
{"You can later change your password using a Jabber client.","Potrai in seguito cambiare la password utilizzando un client Jabber."}.
{"You have been banned from this room","Sei stata/o bandita/o da questa stanza"}.
{"You must fill in field \"Nickname\" in the form","Si deve riempire il campo \"Nickname\" nel modulo"}.
{"You need a client that supports x:data and CAPTCHA to register","La registrazione richiede un client che supporti x:data e CAPTCHA"}.
{"You need a client that supports x:data to register the nickname","Per registrare il nickname è necessario un client che supporti x:data"}.
{"You need an x:data capable client to configure mod_irc settings","Per la configurazione del modulo IRC è necessario un client che supporti x:data"}.
{"You need an x:data capable client to configure room","Per la configurazione della stanza è necessario un client che supporti x:data"}.
{"You need an x:data capable client to search","Per effettuare ricerche è necessario un client che supporti x:data"}.
{"Your active privacy list has denied the routing of this stanza.","In base alla tua attuale lista privacy questa stanza è stata esclusa dalla navigazione."}.
{"Your contact offline message queue is full. The message has been discarded.","La coda dei messaggi offline del contatto è piena. Il messaggio è stato scartato"}.
{"Your Jabber account was successfully created.","La creazione del tuo account Jabber è andata a buon fine."}.
{"Your Jabber account was successfully deleted.","La cancellazione del tuo account Jabber è andata a buon fine."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","I messaggi verso ~s sono bloccati. Per sbloccarli, visitare ~s"}.
