%% -*- coding: latin-1 -*-
{"Accept","許可"}.
{"Access Configuration","アクセス設定"}.
{"Access Control List Configuration","アクセスコントロールリスト設定"}.
{"Access control lists","アクセスコントロールリスト"}.
{"Access Control Lists","アクセスコントロールリスト"}.
{"Access denied by service policy","サービスポリシーによってアクセスが禁止されました"}.
{"Access rules","アクセスルール"}.
{"Access Rules","アクセスルール"}.
{"Action on user","ユーザー操作"}.
{"Add Jabber ID","Jabber ID を追加"}.
{"Add New","新規追加"}.
{"Add User","ユーザーを追加"}.
{"Administration of ","管理: "}.
{"Administration","管理"}.
{"Administrator privileges required","管理者権限が必要です"}.
{"A friendly name for the node","ノードのフレンドリネーム"}.
{"All activity","すべて"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","この Jabber ID に、この pubsubノードの購読を許可しますか ?"}.
{"Allow users to change the subject","ユーザーによる件名の変更を許可"}.
{"Allow users to query other users","ユーザーによる他のユーザーへのクエリーを許可"}.
{"Allow users to send invites","ユーザーによる招待を許可"}.
{"Allow users to send private messages","ユーザーによるプライベートメッセージの送信を許可"}.
{"Allow visitors to change nickname","傍聴者のニックネームの変更を許可"}.
{"Allow visitors to send private messages to","傍聴者によるプライベートメッセージの送信を次の相手に許可"}.
{"Allow visitors to send status text in presence updates","傍聴者によるプレゼンス更新のステータス文の送信を許可"}.
{"Allow visitors to send voice requests","傍聴者による発言権の要求を許可"}.
{"All Users","全ユーザー"}.
{"Announcements","アナウンス"}.
{"anyone","誰にでも"}.
{"A password is required to enter this room","このチャットルームに入るにはパスワードが必要です"}.
{"April","4月"}.
{"August","8月"}.
{"Backup","バックアップ"}.
{"Backup Management","バックアップ管理"}.
{"Backup of ~p","バックアップ: ~p"}.
{"Backup to File at ","ファイルにバックアップ: "}.
{"Bad format","不正なフォーマット"}.
{"Birthday","誕生日"}.
{"CAPTCHA web page","CAPTCHA ウェブページ"}.
{"Change Password","パスワードを変更"}.
{"Change User Password","パスワードを変更"}.
{"Characters not allowed:","使用できない文字:"}.
{"Chatroom configuration modified","チャットルームの設定が変更されました"}.
{"Chatroom is created","チャットルームを作りました"}.
{"Chatroom is destroyed","チャットルームを終了しました"}.
{"Chatroom is started","チャットルームを開始しました"}.
{"Chatroom is stopped","チャットルームを停止しました"}.
{"Chatrooms","チャットルーム"}.
{"Choose a username and password to register with this server","サーバーに登録するユーザー名とパスワードを選択してください"}.
{"Choose modules to stop","停止するモジュールを選択"}.
{"Choose storage type of tables","テーブルのストレージタイプを選択"}.
{"Choose whether to approve this entity's subscription.","このエントリを承認するかどうかを選択してください"}.
{"City","都道府県"}.
{"Commands","コマンド"}.
{"Conference room does not exist","会議室は存在しません"}.
{"Configuration of room ~s","チャットルーム ~s の設定"}.
{"Configuration","設定"}.
{"Connected Resources:","接続リソース:"}.
{"Connections parameters","接続パラメーター"}.
{"Country","国"}.
{"CPU Time:","CPU時間:"}.
{"Database","データーベース"}.
{"Database Tables at ~p","データーベーステーブル: ~p"}.
{"Database Tables Configuration at ","データーベーステーブル設定 "}.
{"December","12月"}.
{"Default users as participants","デフォルトのユーザーは参加者"}.
{"Delete message of the day on all hosts","全ホストのお知らせメッセージを削除"}.
{"Delete message of the day","お知らせメッセージを削除"}.
{"Delete Selected","選択した項目を削除"}.
{"Delete User","ユーザーを削除"}.
{"Deliver event notifications","イベント通知を配送する"}.
{"Deliver payloads with event notifications","イベント通知と同時にペイロードを配送する"}.
{"Description:","説明:"}.
{"Disc only copy","ディスクだけのコピー"}.
{"Displayed Groups:","表示グループ:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","パスワードは誰にも教えないようにしてください。Jabber サーバーの管理者があなたにパスワードを尋ねることはありません。"}.
{"Dump Backup to Text File at ","テキストファイルにバックアップ: "}.
{"Dump to Text File","テキストファイルに出力"}.
{"Edit Properties","プロパティを編集"}.
{"Either approve or decline the voice request.","発言権の要求を承認または却下します。"}.
{"ejabberd IRC module","ejabberd IRC module"}.
{"ejabberd MUC module","ejabberd MUCモジュール"}.
{"ejabberd Multicast service","ejabberdマルチキャストサービス"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe モジュール"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams モジュール"}.
{"ejabberd vCard module","ejabberd vCard モジュール"}.
{"ejabberd Web Admin","ejabberd ウェブ管理"}.
{"Elements","要素"}.
{"Email","メールアドレス"}.
{"Empty Rooms","空のルーム"}.
{"Enable logging","ロギングを有効"}.
{"Enable message archiving","メッセージアーカイブを有効化"}.
{"Encoding for server ~b","サーバーのエンコーディング ~b"}.
{"End User Session","エンドユーザーセッション"}.
{"Enter list of {Module, [Options]}","{モジュール, [オプション]}のリストを入力してください"}.
{"Enter nickname you want to register","登録するニックネームを入力してください"}.
{"Enter path to backup file","バックアップファイルのパスを入力してください"}.
{"Enter path to jabberd14 spool dir","jabberd14 spool ディレクトリのディレクトリを入力してください"}.
{"Enter path to jabberd14 spool file","jabberd14 spool ファイルのパスを入力してください"}.
{"Enter path to text file","テキストファイルのパスを入力してください"}.
{"Enter the text you see","見えているテキストを入力してください"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","IRC サーバーに接続先するためのユーザー名と文字エンコーディングを入力してください。'Next' を押して次の項目に進みます。'Complete' を押すと設定が保存されます。"}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","IRC サーバーに接続先するために使用するユーザー名、文字エンコーディング、ポート、パスワードを入力してください"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","エラー"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","例: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","CAPTCHA 入力を免除する Jabber ID"}.
{"Export all tables as SQL queries to a file:","すべてのテーブルをSQL形式でファイルにエクスポート: "}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","サーバーにあるすべてのユーザーデータを PIEFXIS ファイルにエクスポート (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","ホストのユーザーデータを PIEFXIS ファイルにエクスポート (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","発言権要求の承認から JID を取り出すことに失敗しました"}.
{"Family Name","姓"}.
{"February","2月"}.
{"Fill in fields to search for any matching Jabber User","項目を入力してユーザーを検索してください"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","項目を入力してユーザーを検索を行えます (* を使用すると部分文字列にマッチします)"}.
{"Friday","金曜日"}.
{"From ~s","From ~s"}.
{"From","差出人"}.
{"Full Name","氏名"}.
{"Get Number of Online Users","オンラインユーザー数を取得"}.
{"Get Number of Registered Users","登録ユーザー数を取得"}.
{"Get User Last Login Time","最終ログイン時間を取得"}.
{"Get User Password","パスワードを取得"}.
{"Get User Statistics","ユーザー統計を取得"}.
{"Grant voice to this person?","この人に発言権を与えますか ?"}.
{"Group ","グループ"}.
{"Groups","グループ"}.
{"has been banned","はバンされました"}.
{"has been kicked","はキックされました"}.
{"has been kicked because of an affiliation change","は分掌が変更されたためキックされました"}.
{"has been kicked because of a system shutdown","はシステムシャットダウンのためキックされました"}.
{"has been kicked because the room has been changed to members-only","はチャットルームがメンバー制に変更されたためキックされました"}.
{" has set the subject to: "," は件名を設定しました: "}.
{"Host","ホスト"}.
{"If you don't see the CAPTCHA image here, visit the web page.","ここに CAPTCHA 画像が表示されない場合、ウェブページを参照してください。"}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","別のポートやパスワード、文字エンコーディングを使用したい場合、'{\"irc server\", \"encoding\", port, \"password\"}' という形式のリストを入力してください。デフォルトでエンコーディングは \"~s\" を使用し、ポートは ~p、パスワードは空になっています。"}.
{"Import Directory","ディレクトリインポート"}.
{"Import File","ファイルからインポート"}.
{"Import user data from jabberd14 spool file:","ユーザーデータを jabberd14 Spool ファイルからインポート:"}.
{"Import User from File at ","ファイルからユーザーをインポート: "}.
{"Import users data from a PIEFXIS file (XEP-0227):","ユーザーデータを PIEFXIS ファイルからインポート (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","ユーザーデータを jabberd14 Spool ディレクトリからインポート:"}.
{"Import Users from Dir at ","ディレクトリからユーザーをインポート: "}.
{"Import Users From jabberd14 Spool Files","jabberd14 Spool ファイルからユーザーをインポート"}.
{"Improper message type","誤ったメッセージタイプです"}.
{"Incoming s2s Connections:","内向き s2s コネクション:"}.
{"Incorrect password","パスワードが違います"}.
{"Invalid affiliation: ~s","無効な分掌です: ~s"}.
{"Invalid role: ~s","無効な役です: ~s"}.
{"IP addresses","IP アドレス"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","IRC チャンネル (先頭に#は不要)"}.
{"IRC server","IRC サーバー"}.
{"IRC settings","IRC 設定"}.
{"IRC Transport","IRCトランスポート"}.
{"IRC username","IRC ユーザー名"}.
{"IRC Username","IRC ユーザー名"}.
{"is now known as","は名前を変更しました: "}.
{"It is not allowed to send error messages to the room. The participant (~s) has sent an error message (~s) and got kicked from the room","このルームにエラーメッセージを送ることは許可されていません。参加者(~s)はエラーメッセージを(~s)を送信してルームからキックされました。"}.
{"It is not allowed to send private messages of type \"groupchat\"","種別が\"groupchat\" であるプライベートメッセージを送信することはできません"}.
{"It is not allowed to send private messages to the conference","この会議にプライベートメッセージを送信することはできません"}.
{"It is not allowed to send private messages","プライベートメッセージを送信することはできません"}.
{"Jabber Account Registration","Jabber アカウント登録"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s は無効です"}.
{"January","1月"}.
{"Join IRC channel","IRC チャンネルに参加"}.
{"joins the room","がチャットルームに参加しました"}.
{"Join the IRC channel here.","この IRC チャンネルに参加します。"}.
{"Join the IRC channel in this Jabber ID: ~s","Jabber ID: ~s でこの IRC チャンネルに参加"}.
{"July","7月"}.
{"June","6月"}.
{"Last Activity","活動履歴"}.
{"Last login","最終ログイン"}.
{"Last month","先月"}.
{"Last year","去年"}.
{"leaves the room","がチャットルームから退出しました"}.
{"Listened Ports at ","Listen ポート "}.
{"Listened Ports","Listen ポート"}.
{"List of modules to start","起動モジュールの一覧"}.
{"List of rooms","チャットルームの一覧"}.
{"Low level update script","低レベル更新スクリプト"}.
{"Make participants list public","参加者一覧を公開"}.
{"Make room CAPTCHA protected","チャットルームを CAPTCHA で保護"}.
{"Make room members-only","チャットルームをメンバーのみに制限"}.
{"Make room moderated","チャットルームをモデレート化"}.
{"Make room password protected","チャットルームをパスワードで保護"}.
{"Make room persistent","チャットルームを永続化"}.
{"Make room public searchable","チャットルームを検索可"}.
{"March","3月"}.
{"Maximum Number of Occupants","最大在室者数"}.
{"Max # of items to persist","アイテムの最大保存数"}.
{"Max payload size in bytes","最大ぺイロードサイズ (byte)"}.
{"May","5月"}.
{"Members:","メンバー:"}.
{"Membership is required to enter this room","このチャットルームに入るにはメンバーでなければなりません"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","パスワードは記憶するか、紙に書いて安全な場所に保管してください。もしあなたがパスワードを忘れてしまった場合、Jabber ではパスワードのリカバリを自動的に行うことはできません。"}.
{"Memory","メモリ"}.
{"Message body","本文"}.
{"Middle Name","ミドルネーム"}.
{"Minimum interval between voice requests (in seconds)","発言権の要求の最小時間間隔 (秒)"}.
{"Moderator","モデレーター"}.
{"Moderator privileges required","モデレーター権限が必要です"}.
{"moderators only","モデレーターにのみ"}.
{"Modified modules","更新されたモジュール"}.
{"Module","モジュール"}.
{"Modules","モジュール"}.
{"Modules at ~p","モジュール ~p"}.
{"Monday","月曜日"}.
{"Multicast","マルチキャスト"}.
{"Multi-User Chat","マルチユーザーチャット"}.
{"Name","名"}.
{"Name:","名前:"}.
{"Never","なし"}.
{"New Password:","新しいパスワード:"}.
{"Nickname","ニックネーム"}.
{"Nickname Registration at ","ニックネーム登録: "}.
{"Nickname ~s does not exist in the room","ニックネーム ~s はこのチャットルームにいません"}.
{"No body provided for announce message","アナウンスメッセージはありませんでした"}.
{"nobody","誰にも許可しない"}.
{"No Data","データなし"}.
{"Node ID","ノードID"}.
{"Node not found","ノードが見つかりません"}.
{"Node ~p","ノード ~p"}.
{"Nodes","ノード"}.
{"No limit","制限なし"}.
{"None","なし"}.
{"No resource provided","リソースが指定されていません"}.
{"Not Found","見つかりません"}.
{"Notify subscribers when items are removed from the node","アイテムがノードから消された時に購読者へ通知する"}.
{"Notify subscribers when the node configuration changes","ノード設定に変更があった時に購読者へ通知する"}.
{"Notify subscribers when the node is deleted","ノードが削除された時に購読者へ通知する"}.
{"November","11月"}.
{"Number of occupants","在室者の数"}.
{"Number of online users","オンラインユーザー数"}.
{"Number of registered users","登録ユーザー数"}.
{"October","10月"}.
{"Offline Messages:","オフラインメッセージ:"}.
{"Offline Messages","オフラインメッセージ"}.
{"OK","OK"}.
{"Old Password:","古いパスワード:"}.
{"Online","オンライン"}.
{"Online Users:","オンラインユーザー:"}.
{"Online Users","オンラインユーザー"}.
{"Only deliver notifications to available users","有効なユーザーにのみ告知を送信する"}.
{"Only members may query archives of this room","メンバーのみがこのルームのアーカイブを取得できます"}.
{"Only moderators and participants are allowed to change the subject in this room","モデレーターと参加者のみがチャットルームの件名を変更できます"}.
{"Only moderators are allowed to change the subject in this room","モデレーターのみがチャットルームの件名を変更できます"}.
{"Only moderators can approve voice requests","モデレーターだけが発言権の要求を承認できます"}.
{"Only occupants are allowed to send messages to the conference","在室者のみがこの会議にメッセージを送ることができます"}.
{"Only occupants are allowed to send queries to the conference","在室者のみが会議にクエリーを送信することができます"}.
{"Only service administrators are allowed to send service messages","サービス管理者のみがサービスメッセージを送信できます"}.
{"Options","オプション"}.
{"Organization Name","会社名"}.
{"Organization Unit","部署名"}.
{"Outgoing s2s Connections:","外向き s2s コネクション:"}.
{"Outgoing s2s Connections","外向き s2s コネクション"}.
{"Owner privileges required","主宰者の権限が必要です"}.
{"Packet","パケット"}.
{"Participant","参加者"}.
{"Password:","パスワード:"}.
{"Password","パスワード"}.
{"Password ~b","パスワード ~b"}.
{"Password Verification:","パスワード (確認):"}.
{"Password Verification","パスワード (確認)"}.
{"Path to Dir","ディレクトリのパス"}.
{"Path to File","ファイルのパス"}.
{"Pending","保留"}.
{"Period: ","期間: "}.
{"Permanent rooms","永続チャットルーム"}.
{"Persist items to storage","アイテムをストレージに保存する"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","これらのオプションは組み込みの Mnesia データーベースのバックアップのみを行うことに注意してください。もし ODBC モジュールを使用している場合は、SQL データーベースのバックアップを別に行う必要があります。"}.
{"Please specify file name.","ファイル名を指定してください。"}.
{"Please specify file size.","ファイルサイズを指定してください。"}.
{"Please, wait for a while before sending new voice request","新しい発言権の要求を送るまで少し間をおいてください"}.
{"Pong","Pong"}.
{"Port","ポート"}.
{"Port ~b","ポート ~b"}.
{"Present real Jabber IDs to","本当の Jabber ID を公開"}.
{"private, ","プライベート、"}.
{"Protocol","プロトコル"}.
{"Publish-Subscribe","Publish-Subscribe"}.
{"PubSub subscriber request","PubSub 購読者のリクエスト"}.
{"Purge all items when the relevant publisher goes offline","公開者がオフラインになるときに、すべてのアイテムを削除"}.
{"Queries to the conference members are not allowed in this room","このチャットルームでは、会議のメンバーへのクエリーは禁止されています"}.
{"RAM and disc copy","RAM, ディスクコピー"}.
{"RAM copy","RAM コピー"}.
{"Raw","Raw"}.
{"Really delete message of the day?","本当にお知らせメッセージを削除しますか ?"}.
{"Recipient is not in the conference room","受信者はこの会議室にいません"}.
{"Register a Jabber account","Jabber アカウントを登録"}.
{"Registered nicknames","登録ニックネーム"}.
{"Registered Users:","登録ユーザー:"}.
{"Registered Users","登録ユーザー"}.
{"Register","登録"}.
{"Registration in mod_irc for ","mod_irc での登録: "}.
{"Remote copy","リモートコピー"}.
{"Remove All Offline Messages","すべてのオフラインメッセージを削除"}.
{"Remove User","ユーザーを削除"}.
{"Remove","削除"}.
{"Replaced by new connection","新しいコネクションによって置き換えられました"}.
{"Resources","リソース"}.
{"Restart Service","サービスを再起動"}.
{"Restart","再起動"}.
{"Restore","リストア"}.
{"Restore Backup from File at ","ファイルからバックアップをリストア: "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","ejabberd の再起動時にバイナリバックアップからリストア (メモリ少):"}.
{"Restore binary backup immediately:","直ちにバイナリバックアップからリストア:"}.
{"Restore plain text backup immediately:","直ちにプレーンテキストバックアップからリストア:"}.
{"Roles for which Presence is Broadcasted","プレゼンスをブロードキャストするロール"}.
{"Room Configuration","チャットルームの設定"}.
{"Room creation is denied by service policy","サービスポリシーによってチャットルームの作成が禁止されています"}.
{"Room description","チャットルームの説明"}.
{"Room Occupants","在室者"}.
{"Room title","チャットルームのタイトル"}.
{"Roster groups allowed to subscribe","名簿グループは購読を許可しました"}.
{"Roster of ","名簿: "}.
{"Roster size","名簿サイズ"}.
{"Roster","名簿"}.
{"RPC Call Error","RPC 呼び出しエラー"}.
{"Running Nodes","起動ノード"}.
{"~s access rule configuration","~s アクセスルール設定"}.
{"Saturday","土曜日"}.
{"Script check","スクリプトチェック"}.
{"Search Results for ","検索結果: "}.
{"Search users in ","ユーザーの検索: "}.
{"Send announcement to all online users on all hosts","全ホストのオンラインユーザーにアナウンスを送信"}.
{"Send announcement to all online users","すべてのオンラインユーザーにアナウンスを送信"}.
{"Send announcement to all users on all hosts","全ホストのユーザーにアナウンスを送信"}.
{"Send announcement to all users","すべてのユーザーにアナウンスを送信"}.
{"September","9月"}.
{"Server:","サーバー:"}.
{"Server","サーバー"}.
{"Server ~b","サーバー ~b"}.
{"Set message of the day and send to online users","お知らせメッセージを設定し、オンラインユーザーに送信"}.
{"Set message of the day on all hosts and send to online users","全ホストのお知らせメッセージを設定し、オンラインユーザーに送信"}.
{"Shared Roster Groups","共有名簿グループ"}.
{"Show Integral Table","累積の表を表示"}.
{"Show Ordinary Table","通常の表を表示"}.
{"Shut Down Service","サービスを停止"}.
{"~s invites you to the room ~s","~s はあなたをチャットルーム ~s に招待しています"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Jabber クライアントはコンピューターにパスワードを記憶できます。コンピューターが安全であると信頼できる場合にのみ、この機能を使用してください。"}.
{"Specify the access model","アクセスモデルを設定する"}.
{"Specify the event message type","イベントメッセージ種別を設定"}.
{"Specify the publisher model","公開モデルを指定する"}.
{"~s's Offline Messages Queue","~s' のオフラインメッセージキュー"}.
{"Start Modules at ","モジュールを開始: "}.
{"Start Modules","モジュールを起動"}.
{"Start","開始"}.
{"Statistics of ~p","~p の統計"}.
{"Statistics","統計"}.
{"Stop Modules at ","モジュールを停止: "}.
{"Stop Modules","モジュールを停止"}.
{"Stopped Nodes","停止ノード"}.
{"Stop","停止"}.
{"Storage Type","ストレージタイプ"}.
{"Store binary backup:","バイナリバックアップを保存:"}.
{"Store plain text backup:","プレーンテキストバックアップを保存:"}.
{"Subject","件名"}.
{"Submitted","送信完了"}.
{"Submit","送信"}.
{"Subscriber Address","購読者のアドレス"}.
{"Subscription","認可"}.
{"Sunday","日曜日"}.
{"That nickname is already in use by another occupant","そのニックネームは既にほかの在室者によって使用されています"}.
{"That nickname is registered by another person","ニックネームはほかの人によって登録されています"}.
{"The CAPTCHA is valid.","CAPTCHA は有効です。"}.
{"The CAPTCHA verification has failed","CAPTCHA 検証は失敗しました"}.
{"The collections with which a node is affiliated","提携されたノードの集合です"}.
{"the password is","パスワードは"}.
{"The password is too weak","このパスワードは単純過ぎます"}.
{"The password of your Jabber account was successfully changed.","Jabber アカウントのパスワード変更に成功しました。"}.
{"There was an error changing the password: ","パスワードの変更中にエラーが発生しました: "}.
{"There was an error creating the account: ","アカウントの作成中にエラーが発生しました: "}.
{"There was an error deleting the account: ","アカウントの削除中にエラーが発生しました: "}.
{"This IP address is blacklisted in ~s","このIPアドレスはアクセスを禁止されています ~s"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","大文字と小文字は区別しません: macbeth は MacBeth や Macbeth と同じです。"}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","ここはこの Jabber サーバーにアカウントを作成するページです。あなたの JID (JabberID) は username@server のような形式になります。注意事項どおり、正しく項目を記入してください。"}.
{"This page allows to unregister a Jabber account in this Jabber server.","このページはサーバー上のJabberアカウントを削除するページです。"}.
{"Thursday","木曜日"}.
{"Time delay","遅延時間"}.
{"Time","時間"}.
{"Too many CAPTCHA requests","CAPTCHA 要求が多すぎます"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","~p回の認証に失敗しました。このIPアドレス(~s)は~s UTCまでブロックされます。"}.
{"Too many unacked stanzas","多くのスタンザが応答していません"}.
{"To ~s","宛先 ~s"}.
{"Total rooms","チャットルーム数"}.
{"To","To"}.
{"Traffic rate limit is exceeded","トラフィックレートの制限を超えました"}.
{"Transactions Aborted:","トランザクションの失敗:"}.
{"Transactions Committed:","トランザクションのコミット:"}.
{"Transactions Logged:","トランザクションのログ: "}.
{"Transactions Restarted:","トランザクションの再起動:"}.
{"Tuesday","火曜日"}.
{"Unable to generate a CAPTCHA","CAPTCHA を生成できません"}.
{"Unauthorized","認証されていません"}.
{"Unregister a Jabber account","Jabber アカウントを削除"}.
{"Unregister","削除"}.
{"Update message of the day (don't send)","お知らせメッセージを更新 (送信しない)"}.
{"Update message of the day on all hosts (don't send)","全ホストのお知らせメッセージを更新 (送信しない)"}.
{"Update plan","更新計画"}.
{"Update ~p","更新 ~p"}.
{"Update script","スクリプトの更新"}.
{"Update","更新"}.
{"Uptime:","起動時間:"}.
{"Use of STARTTLS required","STARTTLS の使用が必須です"}.
{"User","ユーザー"}.
{"User JID","ユーザー JID"}.
{"User Management","ユーザー管理"}.
{"Username:","ユーザー名:"}.
{"Users","ユーザー"}.
{"Users are not allowed to register accounts so quickly","それほど速くアカウントを登録することはできません"}.
{"Users Last Activity","ユーザーの活動履歴"}.
{"User ~s","ユーザー ~s"}.
{"Validate","検証"}.
{"vCard User Search","vCard検索"}.
{"Virtual Hosts","バーチャルホスト"}.
{"Visitors are not allowed to change their nicknames in this room","傍聴者はこのチャットルームでニックネームを変更することはできません"}.
{"Visitors are not allowed to send messages to all occupants","傍聴者はすべての在室者にメッセージを送信することはできません"}.
{"Visitor","傍聴者"}.
{"Voice requests are disabled in this conference","この会議では、発言権の要求はできません"}.
{"Voice request","発言権を要求"}.
{"Wednesday","水曜日"}.
{"When to send the last published item","最後の公開アイテムを送信するタイミングで"}.
{"Whether to allow subscriptions","購読を許可するかどうか"}.
{"You can later change your password using a Jabber client.","あなたは後で Jabber クライアントを使用してパスワードを変更できます。"}.
{"You have been banned from this room","あなたはこのチャットルームからバンされています"}.
{"You must fill in field \"Nickname\" in the form","フォームの\"ニックネーム\"欄を入力する必要があります"}.
{"You need a client that supports x:data and CAPTCHA to register","登録を行うには x:data と CAPTCHA をサポートするクライアントが必要です"}.
{"You need a client that supports x:data to register the nickname","ニックネームを登録するには x:data をサポートするクライアントが必要です"}.
{"You need an x:data capable client to configure mod_irc settings","mod_irc の設定には x:data をサポートするクライアントが必要です"}.
{"You need an x:data capable client to configure room","チャットルームを設定するには x:data をサポートするクライアントが必要です"}.
{"You need an x:data capable client to search","検索を行うためには x:data をサポートするクライアントが必要です"}.
{"Your active privacy list has denied the routing of this stanza.","あなたのプライバシーリストはこのスタンザのルーティングを拒否しました。"}.
{"Your contact offline message queue is full. The message has been discarded.","相手先のオフラインメッセージキューが一杯です。このメッセージは破棄されます。"}.
{"Your Jabber account was successfully created.","Jabber アカウントの作成に成功しました。"}.
{"Your Jabber account was successfully deleted.","Jabber アカウントの削除に成功しました。"}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","~s 宛のメッセージはブロックされています。解除するにはこちらを見てください ~s"}.
