%% -*- coding: utf-8 -*-
{" has set the subject to: "," veranderde het onderwerp in: "}.
{"A password is required to enter this room","U hebt een wachtwoord nodig om deze chatruimte te kunnen betreden"}.
{"Access denied by service policy","De toegang werd geweigerd door het beleid van deze dienst"}.
{"Action on user","Actie op gebruiker"}.
{"Add Jabber ID","Jabber ID toevoegen"}.
{"Add New","Toevoegen"}.
{"Add User","Gebruiker toevoegen"}.
{"Administration of ","Beheer van "}.
{"Administration","Beheer"}.
{"Administrator privileges required","U hebt beheerdersprivileges nodig"}.
{"All activity","Alle activiteit"}.
{"All Users","Alle gebruikers"}.
{"Allow users to change the subject","Sta gebruikers toe het onderwerp te veranderen"}.
{"Allow users to query other users","Gebruikers mogen naar andere gebruikers verzoeken verzenden"}.
{"Allow users to send invites","Gebruikers mogen uitnodigingen verzenden"}.
{"Allow users to send private messages","Gebruikers mogen privéberichten verzenden"}.
{"Allow visitors to change nickname","Sta bezoekers toe hun naam te veranderen"}.
{"Allow visitors to send private messages to","Gebruikers mogen privéberichten verzenden aan"}.
{"Allow visitors to send status text in presence updates","Sta bezoekers toe hun statusbericht in te stellen"}.
{"Announcements","Mededelingen"}.
{"April","April"}.
{"August","Augustus"}.
{"Backup Management","Backup"}.
{"Backup of ~p","Backup maken van ~p"}.
{"Backup to File at ","Binaire backup maken op "}.
{"Backup","Backup"}.
{"Bad format","Verkeerd formaat"}.
{"Birthday","Geboortedatum"}.
{"Change Password","Wachtwoord wijzigen"}.
{"Change User Password","Verander Gebruikerswachtwoord"}.
{"Characters not allowed:","Niet-toegestane karakters:"}.
{"Chatroom configuration modified","De instellingen van de chatruimte werden veranderd"}.
{"Chatroom is created","Gespreksruimte gecreëerd"}.
{"Chatroom is destroyed","Gespreksruimte vernietigd"}.
{"Chatroom is started","Gespreksruimte gestart"}.
{"Chatroom is stopped","Gespreksruimte gestopt"}.
{"Chatrooms","Groepsgesprekken"}.
{"Choose a username and password to register with this server","Kies een gebruikersnaam en een wachtwoord om u te registreren op deze server"}.
{"Choose storage type of tables","Opslagmethode voor tabellen kiezen"}.
{"Choose whether to approve this entity's subscription.","Beslis of dit verzoek tot abonneren zal worden goedgekeurd"}.
{"City","Plaats"}.
{"Commands","Commando's"}.
{"Conference room does not exist","De chatruimte bestaat niet"}.
{"Configuration","Instellingen"}.
{"Connected Resources:","Verbonden bronnen:"}.
{"Country","Land"}.
{"CPU Time:","Processortijd:"}.
{"Database Tables at ~p","Databasetabellen van ~p"}.
{"Database Tables Configuration at ","Instellingen van databasetabellen op "}.
{"Database","Database"}.
{"December","December"}.
{"Default users as participants","Gebruikers standaard instellen als deelnemers"}.
{"Delete message of the day on all hosts","Verwijder bericht-van-de-dag op alle hosts"}.
{"Delete message of the day","Bericht van de dag verwijderen"}.
{"Delete Selected","Geselecteerde verwijderen"}.
{"Delete User","Verwijder Gebruiker"}.
{"Description:","Beschrijving:"}.
{"Disc only copy","Harde schijf"}.
{"Displayed Groups:","Weergegeven groepen:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Geef Uw wachtwoord aan niemand, zelfs niet aan de beheerders van deze Jabber-server."}.
{"Dump Backup to Text File at ","Backup naar een tekstbestand schrijven op "}.
{"Dump to Text File","Backup naar een tekstbestand schrijven"}.
{"Edit Properties","Eigenschappen bewerken"}.
{"Either approve or decline the voice request.","Keur stemaanvraag goed of af."}.
{"ejabberd MUC module","ejabberd's MUC module"}.
{"ejabberd Multicast service","ejabberd Multicast service"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe module"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams module"}.
{"ejabberd vCard module","ejabberd's vCard-module"}.
{"ejabberd Web Admin","ejabberd Webbeheer"}.
{"Elements","Elementen"}.
{"Email","E-mail"}.
{"Enable logging","Logs aanzetten"}.
{"End User Session","Verwijder Gebruikers-sessie"}.
{"Enter nickname you want to register","Voer de bijnaam in die u wilt registreren"}.
{"Enter path to backup file","Voer pad naar backupbestand in"}.
{"Enter path to jabberd14 spool dir","Voer pad naar jabberd14-spool-directory in"}.
{"Enter path to jabberd14 spool file","Voer pad naar jabberd14-spool-bestand in"}.
{"Enter path to text file","Voer pad naar backupbestand in"}.
{"Enter the text you see","Voer de getoonde tekst in"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Fout"}.
{"Export all tables as SQL queries to a file:","Exporteer alle tabellen als SQL-queries naar een bestand:"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Exporteer data van alle gebruikers in de server naar PIEFXIS-bestanden (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Exporteer data van alle gebruikers van een host naar PIEXFIS-bestanden (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","Er kon geen JID worden ontleend uit deze stemaanvraag"}.
{"Family Name","Achternaam"}.
{"February","Februari"}.
{"Friday","Vrijdag"}.
{"From","Van"}.
{"Full Name","Volledige naam"}.
{"Get Number of Online Users","Aantal Aanwezige Gebruikers Opvragen"}.
{"Get Number of Registered Users","Aantal Geregistreerde Gebruikers Opvragen"}.
{"Get User Last Login Time","Tijd van Laatste Aanmelding Opvragen"}.
{"Get User Password","Gebruikerswachtwoord Opvragen"}.
{"Get User Statistics","Gebruikers-statistieken Opvragen"}.
{"Group ","Groep "}.
{"Groups","Groepen"}.
{"has been banned","is verbannen"}.
{"has been kicked because of a system shutdown","is weggestuurd omdat het systeem gestopt wordt"}.
{"has been kicked because of an affiliation change","is weggestuurd vanwege een affiliatieverandering"}.
{"has been kicked because the room has been changed to members-only","is weggestuurd omdat de chatruimte vanaf heden alleen toegankelijk is voor leden"}.
{"has been kicked","is weggestuurd"}.
{"Host","Host"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Als U het CAPTCHA-plaatje niet ziet, bezoek dan de webpagina."}.
{"Import Directory","Directory importeren"}.
{"Import File","Bestand importeren"}.
{"Import user data from jabberd14 spool file:","Importeer gebruikersdata via spool-bestanden van jabberd14"}.
{"Import User from File at ","Importeer gebruiker via bestand op "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importeer gebruikersdata van een PIEFXIS-bestand (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importeer gebruikersdata via spool-bestanden van jabberd14"}.
{"Import Users from Dir at ","Gebruikers importeren vanaf directory op "}.
{"Import Users From jabberd14 Spool Files","Importeer gebruikers via spool-bestanden van jabberd14"}.
{"Improper message type","Onjuist berichttype"}.
{"Incorrect password","Foutief wachtwoord"}.
{"IP addresses","IP-adres"}.
{"is now known as","heet nu"}.
{"It is not allowed to send private messages of type \"groupchat\"","Er mogen geen privéberichten van het type \"groupchat\" worden verzonden"}.
{"It is not allowed to send private messages to the conference","Er mogen geen privéberichten naar de chatruimte worden verzonden"}.
{"It is not allowed to send private messages","Het is niet toegestaan priveberichten te sturen"}.
{"Jabber Account Registration","Jabber-account registratie"}.
{"Jabber ID","Jabber ID"}.
{"January","Januari"}.
{"joins the room","betrad de chatruimte"}.
{"July","Juli"}.
{"June","Juni"}.
{"Last Activity","Laatste activiteit"}.
{"Last login","Laatste Aanmelding"}.
{"Last month","Afgelopen maand"}.
{"Last year","Afgelopen jaar"}.
{"leaves the room","verliet de chatruimte"}.
{"List of rooms","Lijst van groepsgesprekken"}.
{"Low level update script","Lowlevel script voor de opwaardering"}.
{"Make participants list public","Deelnemerslijst publiek maken"}.
{"Make room CAPTCHA protected","Chatruimte beveiligen met een geautomatiseerde Turing test"}.
{"Make room members-only","Chatruimte enkel toegankelijk maken voor leden"}.
{"Make room moderated","Chatruimte gemodereerd maken"}.
{"Make room password protected","Chatruimte beveiligen met een wachtwoord"}.
{"Make room persistent","Chatruimte blijvend maken"}.
{"Make room public searchable","Chatruimte doorzoekbaar maken"}.
{"March","Maart"}.
{"Maximum Number of Occupants","Maximum aantal aanwezigen"}.
{"May","Mei"}.
{"Members:","Groepsleden:"}.
{"Membership is required to enter this room","U moet lid zijn om deze chatruimte te kunnen betreden"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Onthou het wachtwoord, of schrijf het op en bewaar het op een veilige plaats. Met Jabber is er geen geautomatiseerde manier om het wachtwoord terug te halen als U het vergeet."}.
{"Memory","Geheugen"}.
{"Message body","Bericht"}.
{"Middle Name","Tussennaam"}.
{"Moderator privileges required","U hebt moderatorprivileges nodig"}.
{"Modified modules","Gewijzigde modules"}.
{"Monday","Maandag"}.
{"Multicast","Multicast"}.
{"Multi-User Chat","Groepschat"}.
{"Name","Naam"}.
{"Name:","Naam:"}.
{"Never","Nooit"}.
{"New Password:","Nieuw Wachtwoord:"}.
{"Nickname Registration at ","Registratie van een bijnaam op "}.
{"Nickname","Bijnaam"}.
{"No body provided for announce message","De mededeling bevat geen bericht"}.
{"No Data","Geen gegevens"}.
{"No limit","Geen limiet"}.
{"Node not found","Node niet gevonden"}.
{"Node ~p","Node ~p"}.
{"Nodes","Nodes"}.
{"None","Geen"}.
{"Not Found","Niet gevonden"}.
{"November","November"}.
{"Number of online users","Aantal Aanwezige Gebruikers"}.
{"Number of registered users","Aantal Geregistreerde Gebruikers"}.
{"October","Oktober"}.
{"Offline Messages","Offline berichten"}.
{"Offline Messages:","Offline berichten:"}.
{"OK","OK"}.
{"Old Password:","Oud Wachtwoord:"}.
{"Online Users","Online gebruikers"}.
{"Online Users:","Online gebruikers:"}.
{"Online","Online"}.
{"Only moderators and participants are allowed to change the subject in this room","Alleen moderators en deelnemers mogen het onderwerp van deze chatruimte veranderen"}.
{"Only moderators are allowed to change the subject in this room","Alleen moderators mogen het onderwerp van deze chatruimte veranderen"}.
{"Only moderators can approve voice requests","Alleen moderators kunnen stemaanvragen goedkeuren"}.
{"Only occupants are allowed to send messages to the conference","Alleen aanwezigen mogen berichten naar de chatruimte verzenden"}.
{"Only occupants are allowed to send queries to the conference","Alleen aanwezigen mogen verzoeken verzenden naar de chatruimte"}.
{"Only service administrators are allowed to send service messages","Alleen beheerders van deze dienst mogen mededelingen verzenden naar alle chatruimtes"}.
{"Organization Name","Organisatie"}.
{"Organization Unit","Afdeling"}.
{"Outgoing s2s Connections","Uitgaande s2s-verbindingen"}.
{"Outgoing s2s Connections:","Uitgaande s2s-verbindingen:"}.
{"Owner privileges required","U hebt eigenaarsprivileges nodig"}.
{"Packet","Pakket"}.
{"Password Verification","Wachtwoord Bevestiging"}.
{"Password Verification:","Wachtwoord Bevestiging:"}.
{"Password","Wachtwoord"}.
{"Password:","Wachtwoord:"}.
{"Path to Dir","Pad naar directory"}.
{"Path to File","Pad naar bestand"}.
{"Pending","Bezig"}.
{"Period: ","Periode: "}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Merk op dat volgende opties enkel backups maken van de ingebouwde database Mnesia. Als U de ODBC module gebruikt dan moeten daarvan afzonderlijke backups gemaakt worden."}.
{"Please, wait for a while before sending new voice request","Wacht s.v.p. met het maken van een nieuwe stemaanvraag."}.
{"Pong","Pong"}.
{"private, ","privé, "}.
{"Publish-Subscribe","Publish-Subscribe"}.
{"PubSub subscriber request","PubSub abonnee verzoek"}.
{"Queries to the conference members are not allowed in this room","Er mogen geen verzoeken verzenden worden naar deelnemers in deze chatruimte"}.
{"RAM and disc copy","RAM en harde schijf"}.
{"RAM copy","RAM"}.
{"Really delete message of the day?","Wilt u het bericht van de dag verwijderen?"}.
{"Recipient is not in the conference room","De ontvanger is niet in de chatruimte"}.
{"Register a Jabber account","Registreer een Jabber-account"}.
{"Registered Users","Geregistreerde gebruikers"}.
{"Registered Users:","Geregistreerde gebruikers:"}.
{"Register","Registreer"}.
{"Remote copy","Op andere nodes in de cluster"}.
{"Remove All Offline Messages","Verwijder alle offline berichten"}.
{"Remove User","Gebruiker verwijderen"}.
{"Remove","Verwijderen"}.
{"Replaced by new connection","Vervangen door een nieuwe verbinding"}.
{"Resources","Bronnen"}.
{"Restart Service","Herstart Service"}.
{"Restart","Herstarten"}.
{"Restore Backup from File at ","Binaire backup direct herstellen op "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Binaire backup herstellen na herstart van ejabberd (vereist minder geheugen):"}.
{"Restore binary backup immediately:","Binaire backup direct herstellen:"}.
{"Restore plain text backup immediately:","Backup in een tekstbestand direct herstellen:"}.
{"Restore","Binaire backup direct herstellen"}.
{"Room Configuration","Instellingen van de chatruimte"}.
{"Room creation is denied by service policy","De aanmaak van de chatruimte is verhinderd door de instellingen van deze server"}.
{"Room description","Beschrijving"}.
{"Room Occupants","Aantal aanwezigen"}.
{"Room title","Naam van de chatruimte"}.
{"Roster size","Contactlijst Groote"}.
{"Roster","Roster"}.
{"RPC Call Error","RPC-oproepfout"}.
{"Running Nodes","Draaiende nodes"}.
{"Saturday","Zaterdag"}.
{"Script check","Controle van script"}.
{"Search Results for ","Zoekresultaten voor "}.
{"Search users in ","Gebruikers zoeken in "}.
{"Send announcement to all online users on all hosts","Mededeling verzenden naar alle online gebruikers op alle virtuele hosts"}.
{"Send announcement to all online users","Mededeling verzenden naar alle online gebruikers"}.
{"Send announcement to all users on all hosts","Stuur aankondiging aan alle gebruikers op alle hosts"}.
{"Send announcement to all users","Mededeling verzenden naar alle gebruikers"}.
{"September","September"}.
{"Server:","Server:"}.
{"Set message of the day and send to online users","Bericht van de dag instellen en verzenden naar online gebruikers"}.
{"Set message of the day on all hosts and send to online users","Stel bericht-van-de-dag in op alle hosts en stuur naar aanwezige gebruikers"}.
{"Shared Roster Groups","Gedeelde rostergroepen"}.
{"Show Integral Table","Volledige tabel laten zien"}.
{"Show Ordinary Table","Deel van tabel laten zien"}.
{"Shut Down Service","Stop Service"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Sommige Jabber-clienten kunnen het wachtwoord opslaan op Uw computer. Gebruik deze mogelijkheid alleen als U vertrouwd dat Uw computer afdoende beveiligd is."}.
{"Statistics of ~p","Statistieken van ~p"}.
{"Statistics","Statistieken"}.
{"Stopped Nodes","Gestopte nodes"}.
{"Stop","Stoppen"}.
{"Storage Type","Opslagmethode"}.
{"Store binary backup:","Binaire backup maken:"}.
{"Store plain text backup:","Backup naar een tekstbestand schrijven:"}.
{"Subject","Onderwerp"}.
{"Submitted","Verzonden"}.
{"Submit","Verzenden"}.
{"Subscription","Inschrijving"}.
{"Sunday","Zondag"}.
{"That nickname is already in use by another occupant","Deze bijnaam is al in gebruik door een andere aanwezige"}.
{"That nickname is registered by another person","Deze bijnaam is al geregistreerd door iemand anders"}.
{"The CAPTCHA is valid.","De geautomatiseerde Turing-test is geslaagd."}.
{"The CAPTCHA verification has failed","De CAPTCHA-verificatie is mislukt"}.
{"The password is too weak","Het wachtwoord is te zwak"}.
{"the password is","het wachtwoord is"}.
{"The password of your Jabber account was successfully changed.","Het wachtwoord van Uw Jabber-account is succesvol veranderd."}.
{"There was an error changing the password: ","Er was een fout bij het veranderen van het wachtwoord:"}.
{"There was an error creating the account: ","Er was een fout bij het creeern van de account:"}.
{"There was an error deleting the account: ","Er was een fout bij het verwijderen van de account."}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Dit is niet hoofdlettergevoelig: macbeth is hetzelfde als MacBeth en Macbeth."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Deze pagina maakt het mogelijk een Jabber-account te registreren op deze server. Uw JID (Jabber IDentiteit) zal er als volg uit zien: gebruikersnaam@server. Lees de instructies zorgvuldig teneinde de velden correct in te vullen."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Deze pagina maakt het mogelijk een Jabber-account op deze server op te heffen."}.
{"This room is not anonymous","Deze chatruimte is niet anoniem"}.
{"Thursday","Donderdag"}.
{"Time delay","Vertraging"}.
{"Time","Tijd"}.
{"To","Aan"}.
{"Too many CAPTCHA requests","Te veel CAPTCHA-aanvragen"}.
{"Too many unacked stanzas","Te veel niet-bevestigde stanzas"}.
{"Total rooms","Aantal groepsgesprekken"}.
{"Traffic rate limit is exceeded","Dataverkeerslimiet overschreden"}.
{"Transactions Aborted:","Afgebroken transacties:"}.
{"Transactions Committed:","Bevestigde transacties:"}.
{"Transactions Logged:","Gelogde transacties:"}.
{"Transactions Restarted:","Herstarte transacties:"}.
{"Tuesday","Dinsdag"}.
{"Unable to generate a CAPTCHA","Het generen van een CAPTCHA is mislukt"}.
{"Unauthorized","Niet geautoriseerd"}.
{"Unregister a Jabber account","Opheffen van Jabber-account"}.
{"Unregister","Opheffen"}.
{"Update message of the day (don't send)","Bericht van de dag bijwerken (niet verzenden)"}.
{"Update message of the day on all hosts (don't send)","Verander bericht-van-de-dag op alle hosts (niet versturen)"}.
{"Update plan","Plan voor de opwaardering"}.
{"Update ~p","Opwaarderen van ~p"}.
{"Update script","Script voor de opwaardering"}.
{"Update","Bijwerken"}.
{"Uptime:","Uptime:"}.
{"User Management","Gebruikersbeheer"}.
{"User","Gebruiker"}.
{"Username:","Gebruikersnaam:"}.
{"Users are not allowed to register accounts so quickly","Het is gebruikers niet toegestaan zo snel achter elkaar te registreren"}.
{"Users Last Activity","Laatste activiteit van gebruikers"}.
{"Users","Gebruikers"}.
{"Validate","Bevestigen"}.
{"vCard User Search","Gebruikers zoeken"}.
{"Virtual Hosts","Virtuele hosts"}.
{"Visitors are not allowed to change their nicknames in this room","Het is bezoekers niet toegestaan hun naam te veranderen in dit kanaal"}.
{"Visitors are not allowed to send messages to all occupants","Bezoekers mogen geen berichten verzenden naar alle aanwezigen"}.
{"Voice requests are disabled in this conference","Stemaanvragen zijn uitgeschakeld voor deze chatruimte"}.
{"Voice request","Stemaanvraag"}.
{"Wednesday","Woensdag"}.
{"You can later change your password using a Jabber client.","U can het wachtwoord later veranderen met een Jabber-client."}.
{"You have been banned from this room","U werd verbannen uit deze chatruimte"}.
{"You must fill in field \"Nickname\" in the form","U moet het veld \"bijnaam\" invullen"}.
{"You need a client that supports x:data and CAPTCHA to register","U hebt een client nodig die x:data en CAPTCHA ondersteunt om een bijnaam te registreren"}.
{"You need a client that supports x:data to register the nickname","U hebt een client nodig die x:data ondersteunt om een bijnaam te registreren"}.
{"You need an x:data capable client to search","U hebt een client nodig die x:data ondersteunt om te zoeken"}.
{"Your active privacy list has denied the routing of this stanza.","Uw actieve privacy-lijst verbied het routeren van dit stanza."}.
{"Your contact offline message queue is full. The message has been discarded.","Te veel offline berichten voor dit contactpersoon. Het bericht is niet opgeslagen."}.
{"Your Jabber account was successfully created.","Uw Jabber-account is succesvol gecreeerd."}.
{"Your Jabber account was successfully deleted.","Uw Jabber-account is succesvol verwijderd."}.
