%% -*- coding: latin-1 -*-
{"Access Configuration","Tilgangskonfigurasjon"}.
{"Access Control List Configuration","Konfigurasjon for Tilgangskontroll lister"}.
{"Access Control Lists","Tilgangskontrollister"}.
{"Access control lists","Tilgangskontroll lister"}.
{"Access denied by service policy","Tilgang nektes på grunn av en tjeneste regel"}.
{"Access rules","Tilgangsregler"}.
{"Access Rules","Tilgangsregler"}.
{"Action on user","Handling på bruker"}.
{"Add Jabber ID","Legg til Jabber ID"}.
{"Add New","Legg til ny"}.
{"Add User","Legg til Bruker"}.
{"Administration","Administrasjon"}.
{"Administration of ","Administrasjon av "}.
{"Administrator privileges required","Administratorprivilegier kreves"}.
{"A friendly name for the node","Et vennlig navn for noden"}.
{"All activity","All aktivitet"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Tillat denne Jabber ID å abonnere på denne pubsub "}.
{"Allow users to change the subject","Tillat brukere å endre emne"}.
{"Allow users to query other users","Tillat brukere å sende forespørsel til andre brukere"}.
{"Allow users to send invites","Tillat brukere å sende invitasjoner"}.
{"Allow users to send private messages","Tillat brukere å sende private meldinger"}.
{"Allow visitors to change nickname","Tillat besøkende å endre kallenavn"}.
{"Allow visitors to send private messages to","Tillat brukere å sende private meldinger til"}.
{"Allow visitors to send status text in presence updates","Tillat besøkende å sende status tekst i "}.
{"Allow visitors to send voice requests","Tillat brukere å sende lyd forespørsler"}.
{"All Users","Alle Brukere"}.
{"Announcements","Kunngjøringer"}.
{"anyone","hvem som helst"}.
{"A password is required to enter this room","Et passord kreves for tilgang til samtalerommet"}.
{"April","april"}.
{"August","august"}.
{"Backup Management","Håndtere Sikkerehetskopiering"}.
{"Backup","Sikkerhetskopier"}.
{"Backup to File at ","Sikkerhetskopiere til Fil på "}.
{"Bad format","Feil format"}.
{"Birthday","Fødselsdag"}.
{"CAPTCHA web page","CAPTCHA web side"}.
{"Change Password","Endre Passord"}.
{"Change User Password","Endre Brukers Passord"}.
{"Characters not allowed:","Ikke godtatte tegn:"}.
{"Chatroom configuration modified","Samtalerommets konfigurasjon er endret"}.
{"Chatroom is created","Samtalerom er opprettet"}.
{"Chatroom is destroyed","Samtalerom er fjernet"}.
{"Chatroom is started","Samtalerom er startet"}.
{"Chatroom is stopped","Samtalerom er stoppet"}.
{"Chatrooms","Samtalerom"}.
{"Choose a username and password to register with this server","Velg et brukernavn og passord for å registrere på "}.
{"Choose modules to stop","Velg hvilke moduler som skal stoppes"}.
{"Choose storage type of tables","Velg lagringstype for tabeller"}.
{"Choose whether to approve this entity's subscription.","Velg om du vil godkjenne denne eksistensens abonement"}.
{"City","By"}.
{"Commands","Kommandoer"}.
{"Conference room does not exist","Konferanserommet finnes ikke"}.
{"Configuration","Konfigurasjon"}.
{"Configuration of room ~s","Konfigurasjon for rom ~s"}.
{"Connected Resources:","Tilkoblede Ressurser:"}.
{"Connections parameters","Tilkoblings parametere"}.
{"Country","Land"}.
{"CPU Time:","CPU Tid:"}.
{"Database","Database"}.
{"Database Tables Configuration at ","Database Tabell Konfigurasjon på "}.
{"December","desember"}.
{"Default users as participants","Standard brukere som deltakere"}.
{"Delete message of the day on all hosts","Slett melding for dagen på alle maskiner"}.
{"Delete message of the day","Slett melding for dagen"}.
{"Delete Selected","Slett valgte"}.
{"Delete User","Slett Bruker"}.
{"Deliver event notifications","Lever begivenhets kunngjøringer"}.
{"Deliver payloads with event notifications","Send innhold sammen med kunngjøringer"}.
{"Description:","Beskrivelse:"}.
{"Disc only copy","Kun diskkopi"}.
{"Displayed Groups:","Viste grupper:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Ikke fortell passordet til noen, ikke en gang til administratoren av Jabber serveren."}.
{"Dump Backup to Text File at ","Dump Sikkerhetskopi til Tekstfil på "}.
{"Dump to Text File","Dump til Tekstfil"}.
{"Edit Properties","Redigere Egenskaper"}.
{"Either approve or decline the voice request.","Enten godkjenn eller forby lyd forespørselen"}.
{"ejabberd IRC module","ejabberd IRC modul"}.
{"ejabberd MUC module","ejabberd MUC modul"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe modul"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams modul"}.
{"ejabberd vCard module","ejabberd vCard modul"}.
{"ejabberd Web Admin","ejabberd Web Admin"}.
{"Elements","Elementer"}.
{"Email","Epost"}.
{"Enable logging","Slå på logging"}.
{"Encoding for server ~b","Tekstkoding for server ~b"}.
{"End User Session","Avslutt Bruker Sesjon"}.
{"Enter list of {Module, [Options]}","Skriv inn en liste av {Module, [Options]}"}.
{"Enter nickname you want to register","Skriv inn kallenavnet du ønsker å registrere"}.
{"Enter path to backup file","Skriv inn sti til sikkerhetskopi filen"}.
{"Enter path to jabberd14 spool dir","Skriv inn sti til jabberd14 spoolkatalog"}.
{"Enter path to jabberd14 spool file","Skriv inn sti til jabberd14 spoolfil"}.
{"Enter path to text file","Skriv inn sti til tekstfil"}.
{"Enter the text you see","Skriv inn teksten du ser"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","Angi brukernavn og kodinger du ønsker å bruke for å koble til IRC servere. Trykk 'Neste' for å få flere felt for å fylle i. Trykk 'Fullfør' for å lagre innstillingene."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","Skriv brukernavn, tekstkoding, porter og passord du ønsker å bruke for tilkobling til IRC servere"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Feil"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","Eksempel: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","Ekskluder Jabber IDer fra CAPTCHA utfordring"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Eksporter data om alle brukere i en server til PIEFXIS filer"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Eksporter data om alle brukere i en host til PIEFXIS filer (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","Feilet i forsøk på å hente JID fra din lyd forespørsel godkjenning"}.
{"Family Name","Etternavn"}.
{"February","februar"}.
{"Fill in fields to search for any matching Jabber User","Fyll inn felt for å søke etter Jabber brukere"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Fyll inn skjemaet for å søke etter Jabber bruker (Legg til * på slutten av feltet for å treffe alle som starter slik)"}.
{"Friday","fredag"}.
{"From","Fra"}.
{"From ~s","Fra ~s"}.
{"Full Name","Fullstendig Navn"}.
{"Get Number of Online Users","Vis Antall Tilkoblede Brukere"}.
{"Get Number of Registered Users","Vis Antall Registrerte Brukere"}.
{"Get User Last Login Time","Vis Brukers Siste Påloggings Tidspunkt"}.
{"Get User Password","Hent Brukers Passord"}.
{"Get User Statistics","Vis Bruker Statistikk"}.
{"Grant voice to this person?","Gi lyd til denne personen?"}.
{"Group ","Gruppe "}.
{"Groups","Grupper"}.
{"has been banned","har blitt bannlyst"}.
{"has been kicked because of an affiliation change","har blitt kastet ut på grunn av en tilknytnings endring"}.
{"has been kicked because of a system shutdown","har blitt kastet ut på grunn av at systemet avslutter"}.
{"has been kicked because the room has been changed to members-only","har blitt kastet ut på grunn av at rommet er endret til kun-for-medlemmer"}.
{"has been kicked","har blitt kastet ut"}.
{" has set the subject to: "," har satt emnet til: "}.
{"Host","Maskin"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Dersom du ikke ser CAPTCHA bilde her, besøk web siden. "}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","Om du ønsker å spesifisere tekstkoding for IRC tjenere, fyller du ut en liste med verdier i formatet '{\"irc server\", \"encoding\", port, \"password\"}'. Denne tjenesten bruker \"~s\" som standard, port ~p, empty password."}.
{"Import Directory","Importer Katalog"}.
{"Import File","Importer File"}.
{"Import user data from jabberd14 spool file:","Importer bruker data fra jabberd14 spoolfiler:"}.
{"Import User from File at ","Importer Bruker fra Fil på "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importer brukeres data fra en PIEFXIS fil (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importer brukeres data fra jabberd14 spoolfil katalog:"}.
{"Import Users from Dir at ","Importer Brukere fra Katalog på "}.
{"Import Users From jabberd14 Spool Files","Importer Brukere Fra jabberd14 Spoolfiler"}.
{"Improper message type","Feilaktig meldingstype"}.
{"Incorrect password","Feil passord"}.
{"Invalid affiliation: ~s","Ugyldig rang: ~s"}.
{"Invalid role: ~s","Ugyldig rolle: ~s"}.
{"IP addresses","IP adresser"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","IRC kanal (ikke skriv den første #)"}.
{"IRC server","IRC server"}.
{"IRC settings","IRC instillinger"}.
{"IRC Transport","IRC Transport"}.
{"IRC username","IRC brukernavn"}.
{"IRC Username","IRC Brukernavn"}.
{"is now known as","er nå kjent som"}.
{"It is not allowed to send private messages","Det er ikke tillatt å sende private meldinger"}.
{"It is not allowed to send private messages of type \"groupchat\"","Det er ikke tillatt å sende private meldinger med typen "}.
{"It is not allowed to send private messages to the conference","Det er ikke tillatt å sende private meldinger til "}.
{"Jabber Account Registration","Jabber Konto Registrering"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Ugyldig Jabber ID ~s"}.
{"January","januar"}.
{"Join IRC channel","Bli med i IRC kanal"}.
{"joins the room","kommer inn i rommet"}.
{"Join the IRC channel here.","Bli med i IRC kanalen her. "}.
{"Join the IRC channel in this Jabber ID: ~s","Bli med i IRC kanalen med denne Jabber ID: ~s"}.
{"July","juli"}.
{"June","juni"}.
{"Last Activity","Siste Aktivitet"}.
{"Last login","Siste pålogging"}.
{"Last month","Siste måned"}.
{"Last year","Siste året"}.
{"leaves the room","forlater rommet"}.
{"Listened Ports at ","Lyttende Porter på "}.
{"Listened Ports","Lyttende Porter"}.
{"List of modules to start","Liste over moduler som skal startes"}.
{"Low level update script","Lavnivå oppdaterings skript"}.
{"Make participants list public","Gjør deltakerlisten offentlig"}.
{"Make room CAPTCHA protected","Gjør rommet CAPTCHA beskyttet"}.
{"Make room members-only","Gjør rommet tilgjengelig kun for medlemmer"}.
{"Make room moderated","Gjør rommet redaktørstyrt"}.
{"Make room password protected","Passordbeskytt rommet"}.
{"Make room persistent","Gjør rommet permanent"}.
{"Make room public searchable","Gjør rommet offentlig søkbart"}.
{"March","mars"}.
{"Maximum Number of Occupants","Maksimum Antall Deltakere"}.
{"Max # of items to persist","Høyeste # elementer som skal lagres"}.
{"Max payload size in bytes","Største innholdsstørrelse i byte"}.
{"May","mai"}.
{"Membership is required to enter this room","Medlemskap kreves for tilgang til samtalerommet"}.
{"Members:","Medlemmer:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Husk passordet, eller skriv det ned på et papir lagret på et trygt sted. I Jabber er det ingen automatisert måte å gjenskape passordet om du glemmer det. "}.
{"Memory","Minne"}.
{"Message body","Meldingskropp"}.
{"Middle Name","Mellomnavn"}.
{"Minimum interval between voice requests (in seconds)","Minimums interval mellom lyd forespørsler (i sekunder)"}.
{"Moderator privileges required","Redaktørprivilegier kreves"}.
{"moderators only","kun for redaktører"}.
{"Modified modules","Endrede moduler"}.
{"Module","Modul"}.
{"Modules","Moduler"}.
{"Monday","mandag"}.
{"Name:","Navn:"}.
{"Name","Navn"}.
{"Never","Aldri"}.
{"New Password:","Nytt Passord:"}.
{"Nickname","Kallenavn"}.
{"Nickname Registration at ","Registrer Kallenavn på "}.
{"Nickname ~s does not exist in the room","Kallenavn ~s eksisterer ikke i dette rommet"}.
{"nobody","ingen"}.
{"No body provided for announce message","Ingen meldingskropp gitt for kunngjørings melding"}.
{"No Data","Ingen Data"}.
{"Node ID","Node ID"}.
{"Node not found","Noden finnes ikke"}.
{"Nodes","Noder"}.
{"No limit","Ingen grense"}.
{"None","Ingen"}.
{"No resource provided","Ingen ressurs angitt"}.
{"Not Found","Finnes Ikke"}.
{"Notify subscribers when items are removed from the node","Informer abonnenter når elementer fjernes fra noden"}.
{"Notify subscribers when the node configuration changes","Informer abonnenter når node konfigurasjonen endres"}.
{"Notify subscribers when the node is deleted","Informer abonnenter når noden slettes"}.
{"November","november"}.
{"Number of occupants","Antall deltakere"}.
{"Number of online users","Antall tilkoblede brukere"}.
{"Number of registered users","Antall registrerte brukere"}.
{"October","oktober"}.
{"Offline Messages:","Frakoblede Meldinger:"}.
{"Offline Messages","Frakoblede Meldinger"}.
{"OK","OK"}.
{"Old Password:","Gammelt Passord:"}.
{"Online","Tilkoblet"}.
{"Online Users:","Tilkoblede Brukere:"}.
{"Online Users","Tilkoblede Brukere"}.
{"Only deliver notifications to available users","Send kunngjøringer bare til tilgjengelige brukere"}.
{"Only moderators and participants are allowed to change the subject in this room","Bare redaktører og deltakere kan endre emnet i dette rommet"}.
{"Only moderators are allowed to change the subject in this room","Bare ordstyrer tillates å  endre emnet i dette rommet"}.
{"Only moderators can approve voice requests","Bare ordstyrer kan godkjenne lyd forespørsler"}.
{"Only occupants are allowed to send messages to the conference","Bare deltakere får sende normale meldinger til konferansen"}.
{"Only occupants are allowed to send queries to the conference","Bare deltakere er tillatt å sende forespørsler til "}.
{"Only service administrators are allowed to send service messages","Bare tjeneste administratorer er tilatt å sende tjeneste "}.
{"Options","Alternativer"}.
{"Organization Name","Organisasjonsnavn"}.
{"Organization Unit","Organisasjonsenhet"}.
{"Outgoing s2s Connections:","Utgående s2s Koblinger"}.
{"Outgoing s2s Connections","Utgående s2s Koblinger"}.
{"Owner privileges required","Eierprivilegier kreves"}.
{"Packet","Pakke"}.
{"Password ~b","Passord ~b"}.
{"Password:","Passord:"}.
{"Password","Passord"}.
{"Password Verification:","Passord Bekreftelse:"}.
{"Password Verification","Passord Bekreftelse"}.
{"Path to Dir","Sti til Katalog"}.
{"Path to File","Sti til Fil"}.
{"Pending","Ventende"}.
{"Period: ","Periode: "}.
{"Persist items to storage","Vedvarende elementer til lagring"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Merk at disse valgene vil bare sikkerhetskopiere den innebygde Mnesia databasen. Dersom du bruker ODBC modulen må du også ta backup av din SQL database."}.
{"Please, wait for a while before sending new voice request","Vennligst vent en stund før du sender en ny lyd forespørsel"}.
{"Pong","Pong"}.
{"Port ~b","Port ~b"}.
{"Port","Port"}.
{"Present real Jabber IDs to","Presenter ekte Jabber IDer til"}.
{"private, ","privat, "}.
{"Protocol","Protokoll"}.
{"Publish-Subscribe","Publish-Subscribe"}.
{"PubSub subscriber request","PubSub abonements forespørsel"}.
{"Purge all items when the relevant publisher goes offline","Rydd alle elementer når den aktuelle utgiveren logger av"}.
{"Queries to the conference members are not allowed in this room","Forespørsler til konferanse medlemmene er ikke tillat i dette rommet"}.
{"RAM and disc copy","RAM og diskkopi"}.
{"RAM copy","RAM kopi"}.
{"Raw","Rå"}.
{"Really delete message of the day?","Virkelig slette melding for dagen?"}.
{"Recipient is not in the conference room","Mottakeren er ikke i konferanserommet"}.
{"Register a Jabber account","Registrer en Jabber konto"}.
{"Registered Users:","Registrerte Brukere:"}.
{"Registered Users","Registrerte Brukere"}.
{"Register","Registrer"}.
{"Registration in mod_irc for ","Registrering i mod_irc for "}.
{"Remote copy","Lagres ikke lokalt"}.
{"Remove All Offline Messages","Fjern Alle Frakoblede Meldinger"}.
{"Remove","Fjern"}.
{"Remove User","Fjern Bruker"}.
{"Replaced by new connection","Erstattet av en ny tilkobling"}.
{"Resources","Ressurser"}.
{"Restart Service","Start Tjeneste på Nytt"}.
{"Restart","Starte på nytt"}.
{"Restore Backup from File at ","Gjenopprett fra Sikkerhetsopifil på "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Gjenopprette binær backup etter neste ejabberd omstart (krever mindre minne):"}.
{"Restore binary backup immediately:","Gjenopprette binær backup umiddelbart:"}.
{"Restore","Gjenopprett"}.
{"Restore plain text backup immediately:","Gjenopprette rentekst sikkerhetskopi umiddelbart:"}.
{"Room Configuration","Rom Konfigurasjon"}.
{"Room creation is denied by service policy","Oppretting av rom nektes av en tjenste regel"}.
{"Room description","Rom beskrivelse"}.
{"Room Occupants","Samtalerom Deltakere"}.
{"Room title","Romtittel"}.
{"Roster groups allowed to subscribe","Kontaktliste grupper som tillates å abonnere"}.
{"Roster","Kontaktliste"}.
{"Roster of ","Kontaktliste for "}.
{"Roster size","Kontaktliste størrelse"}.
{"RPC Call Error","RPC Kall Feil"}.
{"Running Nodes","Kjørende Noder"}.
{"~s access rule configuration","tilgangsregel konfigurasjon for ~s"}.
{"Saturday","lørdag"}.
{"Script check","Skript sjekk"}.
{"Search Results for ","Søke Resultater for "}.
{"Search users in ","Søk etter brukere i "}.
{"Send announcement to all online users on all hosts","Send kunngjøring til alle tilkoblede brukere på alle "}.
{"Send announcement to all online users","Send kunngjøring alle tilkoblede brukere"}.
{"Send announcement to all users on all hosts","Send kunngjøring til alle brukere på alle maskiner"}.
{"Send announcement to all users","Send kunngjøring til alle brukere"}.
{"September","september"}.
{"Server ~b","Server ~b"}.
{"Server:","Server:"}.
{"Set message of the day and send to online users","Angi melding for dagen og send til tilkoblede brukere"}.
{"Set message of the day on all hosts and send to online users","Angi melding for dagen på alle maskiner og send til "}.
{"Shared Roster Groups","Delte Kontaktgrupper"}.
{"Show Integral Table","Vis Integral Tabell"}.
{"Show Ordinary Table","Vis Ordinær Tabell"}.
{"Shut Down Service","Avslutt Tjeneste"}.
{"~s invites you to the room ~s","~s inviterer deg til rommet ~s"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Noen Jabber klienter kan lagre passordet på datamaskinen. Bruk bare den funksjonen dersom du er sikker på at maskinen er trygg."}.
{"Specify the access model","Spesifiser aksess modellen"}.
{"Specify the event message type","Spesifiser hendelsesbeskjed type"}.
{"Specify the publisher model","Angi publiserings modell"}.
{"~s's Offline Messages Queue","~ss kø for Frakoblede Meldinger"}.
{"Start Modules at ","Start Moduler på "}.
{"Start Modules","Start Moduler"}.
{"Start","Start"}.
{"Statistics of ~p","Statistikk for ~p"}.
{"Statistics","Statistikk"}.
{"Stop Modules at ","Stopp Moduler på "}.
{"Stop Modules","Stop Moduler"}.
{"Stopped Nodes","Stoppede Noder"}.
{"Stop","Stoppe"}.
{"Storage Type","Lagringstype"}.
{"Store binary backup:","Lagre binær sikkerhetskopi:"}.
{"Store plain text backup:","Lagre rentekst sikkerhetskopi:"}.
{"Subject","Tittel"}.
{"Submit","Send"}.
{"Submitted","Innsendt"}.
{"Subscriber Address","Abonnements Adresse"}.
{"Subscription","Abonnement"}.
{"Sunday","søndag"}.
{"That nickname is already in use by another occupant","Det kallenavnet er allerede i bruk av en annen deltaker"}.
{"That nickname is registered by another person","Det kallenavnet er registrert av en annen person"}.
{"The CAPTCHA is valid.","Captchaen er ikke gyldig"}.
{"The CAPTCHA verification has failed","CAPTCHA godkjenningen har feilet"}.
{"The collections with which a node is affiliated","Samlingene som en node er assosiert med"}.
{"the password is","passordet er"}.
{"The password is too weak","Passordet er for svakt"}.
{"The password of your Jabber account was successfully changed.","Passordet for din Jabber konto ble endret."}.
{"There was an error changing the password: ","En feil skjedde under endring av passordet:"}.
{"There was an error creating the account: ","En feil skjedde under oppretting av kontoen:"}.
{"There was an error deleting the account: ","En feil skjedde under sletting av kontoen: "}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Denne er ufølsom for små og store bokstaver: macbeth er det samme som MacBeth og Macbeth. "}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Denne siden lar deg lage en Jabber konto på denne Jabber serveren. Din JID (Jabber ID) vil være i formatet: brukernavn@server. Vennligst les instruksjonene nøye slik at du fyller ut skjemaet riktig."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Denne siden lar deg avregistrere en Jabber konto på denne Jabber serveren."}.
{"Thursday","torsdag"}.
{"Time delay","Tids forsinkelse"}.
{"Time","Tid"}.
{"Too many CAPTCHA requests","For mange CAPTCHA forespørsler"}.
{"To ~s","Til ~s"}.
{"To","Til"}.
{"Traffic rate limit is exceeded","Trafikkmengde grense overskredet"}.
{"Transactions Aborted:","Avbrutte Transasksjoner:"}.
{"Transactions Committed:","Sendte Transaksjoner:"}.
{"Transactions Logged:","Loggede Transasksjoner:"}.
{"Transactions Restarted:","Omstartede Transasksjoner:"}.
{"Tuesday","tirsdag"}.
{"Unable to generate a CAPTCHA","Umulig å generere en CAPTCHA"}.
{"Unauthorized","Uautorisert"}.
{"Unregister a Jabber account","Avregistrer en Jabber konto"}.
{"Unregister","Avregistrer"}.
{"Update message of the day (don't send)","Oppdater melding for dagen (ikke send)"}.
{"Update message of the day on all hosts (don't send)","Oppdater melding for dagen på alle maskiner (ikke send)"}.
{"Update","Oppdatere"}.
{"Update plan","Oppdaterings plan"}.
{"Update script","Oppdaterings skript"}.
{"Uptime:","Oppetid:"}.
{"Use of STARTTLS required","Bruk av STARTTLS kreves"}.
{"User","Bruker"}.
{"User JID","Bruker JID"}.
{"User Management","Bruker Behandling"}.
{"Username:","Brukernavn:"}.
{"Users are not allowed to register accounts so quickly","Brukere får ikke lov til  registrere kontoer så fort"}.
{"Users","Brukere"}.
{"Users Last Activity","Brukers Siste Aktivitet"}.
{"Validate","Bekrefte gyldighet"}.
{"vCard User Search","vCard Bruker Søk"}.
{"Virtual Hosts","Virtuella Maskiner"}.
{"Visitors are not allowed to change their nicknames in this room","Besøkende får ikke lov å endre kallenavn i dette "}.
{"Visitors are not allowed to send messages to all occupants","Besøkende får ikke sende meldinger til alle deltakere"}.
{"Voice request","Lyd forespørsel"}.
{"Voice requests are disabled in this conference","Lyd forespørsler er blokkert i denne konferansen"}.
{"Wednesday","onsdag"}.
{"When to send the last published item","Når skal siste publiserte artikkel sendes"}.
{"Whether to allow subscriptions","Om man skal tillate abonnenter"}.
{"You can later change your password using a Jabber client.","Du kan når som helst endre passordet via en Jabber klient."}.
{"You have been banned from this room","Du har blitt bannlyst i dette rommet."}.
{"You must fill in field \"Nickname\" in the form","Du må fylle inn feltet \"Nickname\" i skjemaet"}.
{"You need a client that supports x:data and CAPTCHA to register","Du trenger en klient som støtter x:data og CAPTCHA for registrering "}.
{"You need a client that supports x:data to register the nickname","Du trenger en klient som støtter x:data for å registrere kallenavnet"}.
{"You need an x:data capable client to configure mod_irc settings","Du trenger en x:data kompatibel klient for å konfigurere mod_irc instillinger"}.
{"You need an x:data capable client to configure room","Du trenger en klient som støtter x:data for å "}.
{"You need an x:data capable client to search","Du tregner en klient som støtter x:data for å kunne "}.
{"Your active privacy list has denied the routing of this stanza.","Din aktive privat liste har blokkert rutingen av denne strofen."}.
{"Your contact offline message queue is full. The message has been discarded.","Kontaktens frakoblede meldingskø er full. Meldingen har blitt kassert."}.
{"Your Jabber account was successfully created.","Din Jabber konto ble opprettet"}.
{"Your Jabber account was successfully deleted.","Dni Jabber konto er blitt sltettet."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Dine meldinger til ~s blir blokkert. For å åpne igjen, besøk ~s"}.
