%% -*- coding: latin-1 -*-
{"Accept","Zaakceptuj"}.
{"Access Configuration","Konfiguracja dostępu"}.
{"Access Control List Configuration","Konfiguracja listy dostępowej"}.
{"Access Control Lists","Lista dostępowa"}.
{"Access control lists","Listy dostępowe"}.
{"Access denied by service policy","Dostęp zabroniony zgodnie z zasadami usługi"}.
{"Access rules","Reguły dostępu"}.
{"Access Rules","Zasady dostępu"}.
{"Action on user","Wykonaj na użytkowniku"}.
{"Add Jabber ID","Dodaj Jabber ID"}.
{"Add New","Dodaj nowe"}.
{"Add User","Dodaj użytkownika"}.
{"Administration","Administracja"}.
{"Administration of ","Zarządzanie "}.
{"Administrator privileges required","Wymagane uprawnienia administratora"}.
{"A friendly name for the node","Przyjazna nazwa węzła"}.
{"All activity","Cała aktywność"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Pozwól temu Jabber ID na zapisanie się do tego węzła PubSub"}.
{"Allow users to change the subject","Pozwól użytkownikom zmieniać temat"}.
{"Allow users to query other users","Pozwól użytkownikom pobierać informacje o innych użytkownikach"}.
{"Allow users to send invites","Pozwól użytkownikom wysyłać zaproszenia"}.
{"Allow users to send private messages","Pozwól użytkownikom wysyłać prywatne wiadomości"}.
{"Allow visitors to change nickname","Pozwól uczestnikom na zmianę nicka"}.
{"Allow visitors to send private messages to","Pozwól użytkownikom wysyłać prywatne wiadomości"}.
{"Allow visitors to send status text in presence updates","Pozwól uczestnikom na wysyłanie statusów opisowych"}.
{"Allow visitors to send voice requests","Pozwól użytkownikom wysyłać zaproszenia"}.
{"All Users","Wszyscy użytkownicy"}.
{"Announcements","Powiadomienia"}.
{"anyone","wszystkich"}.
{"A password is required to enter this room","Aby wejść do pokoju wymagane jest hasło"}.
{"April","Kwiecień"}.
{"August","Sierpień"}.
{"Backup Management","Zarządzanie kopiami zapasowymi"}.
{"Backup of ~p","Kopia zapasowa ~p"}.
{"Backup to File at ","Zapisz kopię w pliku na "}.
{"Backup","Wykonaj kopie"}.
{"Bad format","Błędny format"}.
{"Birthday","Data urodzenia"}.
{"CAPTCHA web page","Strona internetowa CAPTCHA"}.
{"Change Password","Zmień hasło"}.
{"Change User Password","Zmień hasło użytkownika"}.
{"Characters not allowed:","Te znaki są niedozwolone:"}.
{"Chatroom configuration modified","Konfiguracja pokoju zmodyfikowana"}.
{"Chatroom is created","Pokój został stworzony"}.
{"Chatroom is destroyed","Pokój został usunięty"}.
{"Chatroom is started","Pokój został uruchomiony"}.
{"Chatroom is stopped","Pokój został zatrzymany"}.
{"Chatrooms","Pokoje rozmów"}.
{"Choose a username and password to register with this server","Wybierz nazwę użytkownika i hasło aby zarejestrować się na tym serwerze"}.
{"Choose modules to stop","Wybierz moduły do zatrzymania"}.
{"Choose storage type of tables","Wybierz typ bazy dla tablel"}.
{"Choose whether to approve this entity's subscription.","Wybierz, czy akceptować subskrypcję tej jednostki"}.
{"City","Miasto"}.
{"Commands","Polecenia"}.
{"Conference room does not exist","Pokój konferencyjny nie istnieje"}.
{"Configuration","Konfiguracja"}.
{"Configuration of room ~s","Konfiguracja pokoju ~s"}.
{"Connected Resources:","Zasoby zalogowane:"}.
{"Connections parameters","Parametry połączeń"}.
{"Country","Państwo"}.
{"CPU Time:","Czas CPU:"}.
{"Database","Baza danych"}.
{"Database Tables at ~p","Tabele bazy na ~p"}.
{"Database Tables Configuration at ","Konfiguracja tabel bazy na "}.
{"December","Grudzień"}.
{"Default users as participants","Domyślni użytkownicy jako uczestnicy"}.
{"Delete message of the day on all hosts","Usuń wiadomość dnia ze wszystkich hostów"}.
{"Delete message of the day","Usuń wiadomość dnia"}.
{"Delete Selected","Usuń zaznaczone"}.
{"Delete User","Usuń użytkownika"}.
{"Deliver event notifications","Dostarczaj powiadomienia o zdarzeniach"}.
{"Deliver payloads with event notifications","Dostarczaj zawartość publikacji wraz z powiadomieniami o zdarzeniach"}.
{"Description:","Opis:"}.
{"Disc only copy","Kopia tylko na dysku"}.
{"Displayed Groups:","Wyświetlane grupy:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Nie podawaj swojego hasła nikomu, nawet administratorowi serwera Jabber."}.
{"Dump Backup to Text File at ","Zapisz kopię zapasową w pliku tekstowym na "}.
{"Dump to Text File","Wykonaj kopie do pliku tekstowego"}.
{"Edit Properties","Edytuj właściwości"}.
{"Either approve or decline the voice request.","Zatwierdź lub odrzuć żądanie głosowe"}.
{"ejabberd IRC module","Moduł IRC ejabberd"}.
{"ejabberd MUC module","Moduł MUC"}.
{"ejabberd Multicast service","Serwis multicast ejabbera"}.
{"ejabberd Publish-Subscribe module","Moduł Publish-Subscribe"}.
{"ejabberd SOCKS5 Bytestreams module","Moduł SOCKS5 Bytestreams"}.
{"ejabberd vCard module","Moduł vCard ejabberd"}.
{"ejabberd Web Admin","ejabberd: Panel Administracyjny"}.
{"Elements","Elementy"}.
{"Email","Email"}.
{"Empty Rooms","Puste pokoje"}.
{"Enable logging","Włącz logowanie"}.
{"Enable message archiving","Włącz archiwizowanie rozmów"}.
{"Encoding for server ~b","Kodowanie znaków dla serwera ~b"}.
{"End User Session","Zakończ sesję uzytkownika"}.
{"Enter list of {Module, [Options]}","Wprowadź listę {Moduł, [Opcje]}"}.
{"Enter nickname you want to register","Wprowadz nazwę użytkownika którego chcesz zarejestrować"}.
{"Enter path to backup file","Wprowadź scieżkę do pliku kopii zapasowej"}.
{"Enter path to jabberd14 spool dir","Wprowadź ścieżkę do roboczego katalogu serwera jabberd14"}.
{"Enter path to jabberd14 spool file","Wprowadź ścieżkę do roboczego pliku serwera jabberd14"}.
{"Enter path to text file","Wprowadź scieżkę do pliku tekstowego"}.
{"Enter the text you see","Przepisz tekst z obrazka"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","Wprowadź nazwę użytkownika i kodowania których chcesz używać do łączenia z serwerami IRC. Wciśnij \"Dalej\" aby ustawić więcej parametrów połączenia. Wciśnij \"Zakończ\" aby zapisać ustawienia."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","Wprowadź nazwę użytkownika, port i kodowanie, których chcesz używać do łączenia z serwerami IRC"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Błąd"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","Przykład: [{\"wroclaw.irc.pl\",\"utf-8\"}, {\"warszawa.irc.pl\", \"iso8859-2\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","Pomiń Jabber ID z żądania CAPTCHA"}.
{"Export all tables as SQL queries to a file:","Wyeksportuj wszystkie tabele jako zapytania SQL do pliku:"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Eksportuj dane wszystkich użytkowników serwera do plików w formacie PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Eksportuj dane użytkowników z hosta do plików w formacie PIEFXIS (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","Nie udało się wydobyć JID-u z twojego żądania"}.
{"Family Name","Nazwisko"}.
{"February","Luty"}.
{"Fill in fields to search for any matching Jabber User","Wypełnij pola aby znaleźć pasujących użytkowników Jabbera"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Wypełnij formularz aby wyszukać użytkowników Jabbera (dodaj * na koniec zapytania aby wyszukać po fragmencie)"}.
{"Friday","Piątek"}.
{"From","Od"}.
{"From ~s","Od ~s"}.
{"Full Name","Pełna nazwa"}.
{"Get Number of Online Users","Pokaż liczbę zalogowanych użytkowników"}.
{"Get Number of Registered Users","Pokaż liczbę zarejestrowanych użytkowników"}.
{"Get User Last Login Time","Pokaż czas ostatniego zalogowania uzytkownika"}.
{"Get User Password","Pobierz hasło użytkownika"}.
{"Get User Statistics","Pobierz statystyki użytkownika"}.
{"Grant voice to this person?","Udzielić głosu tej osobie?"}.
{"Group ","Grupa "}.
{"Groups","Grupy"}.
{"has been banned","został wykluczony"}.
{"has been kicked because of an affiliation change","został wyrzucony z powodu zmiany przynależności"}.
{"has been kicked because of a system shutdown","został wyrzucony z powodu wyłączenia systemu"}.
{"has been kicked because the room has been changed to members-only","został wyrzucony z powodu zmiany pokoju na \"Tylko dla Członków\""}.
{"has been kicked","został wyrzucony"}.
{" has set the subject to: "," zmienił temat na: "}.
{"Host","Host"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Jeśli nie widzisz obrazka CAPTCHA, odwiedź stronę internetową."}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","Jeśli chcesz ustawić inne hasła, porty lub kodowania dla poszczególnych serwerów IRC, wypełnij tą listę wartościami w formacie '{\"irc server\",\"encoding\", port, \"password\"}'. Domyślne ta usługa używa kodowania \"~s\", portu ~p, bez hasła."}.
{"Import Directory","Importuj katalog"}.
{"Import File","Importuj plik"}.
{"Import user data from jabberd14 spool file:","Importuj dane użytkownika z pliku roboczego serwera jabberd14:"}.
{"Import User from File at ","Importuj użytkownika z pliku na "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importuj dane użytkowników z pliku w formacie PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importuj użytkowników z katalogu roboczego serwera jabberd14"}.
{"Import Users from Dir at ","Importuj użytkowników z katalogu na "}.
{"Import Users From jabberd14 Spool Files","Importuj użytkowników z plików roboczych serwera jabberd14"}.
{"Improper message type","Nieprawidłowy typ wiadomości"}.
{"Incoming s2s Connections:","Przychodzące połączenia s2s:"}.
{"Incorrect password","Nieprawidłowe hasło"}.
{"Invalid affiliation: ~s","Nieprawidłowa przynależność: ~s"}.
{"Invalid role: ~s","Nieprawidłowa rola: ~s"}.
{"IP addresses","Adresy IP"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","Kanał IRC (nie używaj #)"}.
{"IRC server","Serwer IRC"}.
{"IRC settings","Ustawienia IRC"}.
{"IRC Transport","Transport IRC"}.
{"IRC username","Nazwa użytkownika IRC"}.
{"IRC Username","Nazwa użytkownika IRC"}.
{"is now known as","jest teraz znany jako"}.
{"It is not allowed to send error messages to the room. The participant (~s) has sent an error message (~s) and got kicked from the room","Użytkownik nie może wysyłać wiadomości o błędach do pokoju. Użytkownik (~s) wysłał błąd (~s) i został wyrzucony z pokoju"}.
{"It is not allowed to send private messages of type \"groupchat\"","Nie można wysyłać prywatnych wiadomości typu \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Nie wolno wysyłac prywatnych wiadomości na konferencję"}.
{"It is not allowed to send private messages","Wysyłanie prywatnych wiadomości jest zabronione"}.
{"Jabber Account Registration","Zakładanie konta Jabber"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s jest niepoprawny"}.
{"January","Styczeń"}.
{"Join IRC channel","Dołącz do kanału IRC"}.
{"joins the room","dołącza do pokoju"}.
{"Join the IRC channel here.","Dołącz do kanału IRC."}.
{"Join the IRC channel in this Jabber ID: ~s","Dołącz do kanału IRC pod tym Jabber ID: ~s"}.
{"July","Lipiec"}.
{"June","Czerwiec"}.
{"Last Activity","Ostatnia aktywność"}.
{"Last login","Ostatnie logowanie"}.
{"Last month","Miniony miesiąc"}.
{"Last year","Miniony rok"}.
{"leaves the room","opuszcza pokój"}.
{"Listened Ports at ","Porty nasłuchujące na "}.
{"Listened Ports","Porty nasłuchujące"}.
{"List of modules to start","Lista modułów do uruchomienia"}.
{"List of rooms","Lista pokoi"}.
{"Low level update script","Skrypt aktualizacji niskiego poziomu"}.
{"Make participants list public","Upublicznij listę uczestników"}.
{"Make room CAPTCHA protected","Pokój zabezpieczony captchą"}.
{"Make room members-only","Pokój tylko dla członków"}.
{"Make room moderated","Pokój moderowany"}.
{"Make room password protected","Pokój zabezpieczony hasłem"}.
{"Make room persistent","Utwórz pokój na stałe"}.
{"Make room public searchable","Pozwól wyszukiwać pokój"}.
{"March","Marzec"}.
{"Maximum Number of Occupants","Maksymalna liczba uczestników"}.
{"Max # of items to persist","Maksymalna liczba przechowywanych przedmiotów"}.
{"Max payload size in bytes","Maksymalna wielkość powiadomienia w bajtach"}.
{"May","Maj"}.
{"Members:","Członkowie:"}.
{"Membership is required to enter this room","Musisz być na liście członków tego pokoju aby do niego wejść"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Zapamiętaj swoje hasło lub zapisz je na kartce i zachowaj w bezpiecznym miejscu. Na Jabberze nie ma zautomatyzowanego systemu odzyskiwania haseł."}.
{"Memory","Pamięć"}.
{"Message body","Treść wiadomości"}.
{"Middle Name","Drugie imię"}.
{"Minimum interval between voice requests (in seconds)","Minimalny odstęp między żądaniami głosowymi (w sekundach)"}.
{"Moderator","Moderatorzy"}.
{"Moderator privileges required","Wymagane uprawnienia moderatora"}.
{"moderators only","tylko moderatorzy"}.
{"Modified modules","Zmodyfikowane moduły"}.
{"Module","Moduł"}.
{"Modules at ~p","Moduły na ~p"}.
{"Modules","Moduły"}.
{"Monday","Poniedziałek"}.
{"Multicast","Multicast"}.
{"Multi-User Chat","Wieloosobowa rozmowa"}.
{"Name","Imię"}.
{"Name:","Nazwa:"}.
{"Never","Nigdy"}.
{"New Password:","Nowe hasło:"}.
{"Nickname","Nazwa użytkownika"}.
{"Nickname Registration at ","Rejestracja nazwy użytkownika na "}.
{"Nickname ~s does not exist in the room","Nie ma nicka ~s w tym pokoju"}.
{"nobody","nikt"}.
{"No body provided for announce message","Brak treści powiadomienia"}.
{"No Data","Brak danych"}.
{"Node ID","ID węzła"}.
{"Node not found","Węzeł nie został znaleziony"}.
{"Node ~p","Węzeł ~p"}.
{"Nodes","Węzły"}.
{"No limit","Bez limitu"}.
{"None","Brak"}.
{"No resource provided","Nie podano zasobu"}.
{"Not Found","Nie znaleziono"}.
{"Notify subscribers when items are removed from the node","Informuj subskrybentów o usunięciu elementów węzła"}.
{"Notify subscribers when the node configuration changes","Informuj subskrybentów o zmianach konfiguracji węzła"}.
{"Notify subscribers when the node is deleted","Informuj subskrybentów o usunięciu węzła"}.
{"November","Listopad"}.
{"Number of occupants","Liczba uczestników"}.
{"Number of online users","Liczba zalogowanych użytkowników"}.
{"Number of registered users","Liczba zarejestrowanych użytkowników"}.
{"October","Październik"}.
{"Offline Messages:","Wiadomości offline:"}.
{"Offline Messages","Wiadomości offline"}.
{"OK","OK"}.
{"Old Password:","Stare hasło:"}.
{"Online","Dostępny"}.
{"Online Users:","Użytkownicy zalogowani:"}.
{"Online Users","Użytkownicy zalogowani"}.
{"Only deliver notifications to available users","Dostarczaj powiadomienia tylko dostępnym użytkownikom"}.
{"Only members may query archives of this room","Tylko moderatorzy mogą przeglądać archiwa tego pokoju"}.
{"Only moderators and participants are allowed to change the subject in this room","Tylko moderatorzy i uczestnicy mogą zmienić temat tego pokoju"}.
{"Only moderators are allowed to change the subject in this room","Tylko moderatorzy mogą zmienić temat tego pokoju"}.
{"Only moderators can approve voice requests","Tylko moderatorzy mogą zatwierdzać żądania głosowe"}.
{"Only occupants are allowed to send messages to the conference","Tylko uczestnicy mogą wysyłać wiadomości na konferencję"}.
{"Only occupants are allowed to send queries to the conference","Tylko uczestnicy mogą wysyłać zapytania do konferencji"}.
{"Only service administrators are allowed to send service messages","Tylko administratorzy mogą wysyłać wiadomości"}.
{"Options","Opcje"}.
{"Organization Name","Nazwa organizacji"}.
{"Organization Unit","Dział"}.
{"Outgoing s2s Connections:","Wychodzące połączenia s2s:"}.
{"Outgoing s2s Connections","Wychodzące połączenia s2s"}.
{"Owner privileges required","Wymagane uprawnienia właściciela"}.
{"Packet","Pakiet"}.
{"Participant","Uczestnicy"}.
{"Password ~b","Hasło ~b"}.
{"Password:","Hasło:"}.
{"Password","Hasło"}.
{"Password Verification:","Weryfikacja hasła:"}.
{"Password Verification","Weryfikacja hasła"}.
{"Path to Dir","Ścieżka do katalogu"}.
{"Path to File","Scieżka do pliku"}.
{"Pending","Oczekuje"}.
{"Period: ","Przedział czasu: "}.
{"Permanent rooms","Stałych pokoi"}.
{"Persist items to storage","Przechowuj na stałe dane PubSub"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Te opcje kopii zapasowych dotyczą tylko wbudowanej bazy danych typu Mnesia. Jeśli korzystasz z modułu ODBC, musisz wykonać kopie bazy we własnym zakresie."}.
{"Please specify file name.","Proszę podać nazwę pliku."}.
{"Please specify file size.","Proszę podać rozmiar pliku."}.
{"Please, wait for a while before sending new voice request","Proszę poczekać chwile, zanim wyślesz nowe żądanie głosowe"}.
{"Pong","Pong"}.
{"Port ~b","Port ~b"}.
{"Port","Port"}.
{"Present real Jabber IDs to","Prawdziwe Jabber ID widoczne dla"}.
{"private, ","prywatny, "}.
{"Protocol","Protokół"}.
{"Publish-Subscribe","PubSub"}.
{"PubSub subscriber request","Żądanie subskrybcji PubSub"}.
{"Purge all items when the relevant publisher goes offline","Usuń wszystkie elementy w momencie kiedy publikujący rozłączy się"}.
{"Queries to the conference members are not allowed in this room","Informacje o członkach konferencji nie są dostępne w tym pokoju"}.
{"RAM and disc copy","Kopia na dysku i w pamięci RAM"}.
{"RAM copy","Kopia w pamięci RAM"}.
{"Raw","Żródło"}.
{"Really delete message of the day?","Na pewno usunąć wiadomość dnia?"}.
{"Recipient is not in the conference room","Odbiorcy nie ma w pokoju"}.
{"Register a Jabber account","Załóż konto Jabber"}.
{"Registered nicknames","Zarejestrowanych nicków"}.
{"Registered Users:","Użytkownicy zarejestrowani:"}.
{"Registered Users","Użytkownicy zarejestrowani"}.
{"Register","Zarejestruj"}.
{"Registration in mod_irc for ","Rejestracja w mod_irc dla "}.
{"Remote copy","Kopia zdalna"}.
{"Remove All Offline Messages","Usuń wszystkie wiadomości typu 'Offline'"}.
{"Remove User","Usuń użytkownika"}.
{"Remove","Usuń"}.
{"Replaced by new connection","Połączenie zostało zastąpione"}.
{"Resources","Zasoby"}.
{"Restart Service","Restart usługi"}.
{"Restart","Uruchom ponownie"}.
{"Restore Backup from File at ","Odtwórz bazę danych z kopii zapasowej na "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Odtwórz kopię binarną podczas następnego uruchomienia ejabberd (wymaga mniej zasobów):"}.
{"Restore binary backup immediately:","Natychmiast odtwórz kopię binarną:"}.
{"Restore plain text backup immediately:","Natychmiast odtwórz kopię z postaci tekstowej:"}.
{"Restore","Przywróć z kopii"}.
{"Roles for which Presence is Broadcasted","Role dla których wysyłane są statusy"}.
{"Room Configuration","Konfiguracja pokoju"}.
{"Room creation is denied by service policy","Zasady serwera zabraniają tworzyć nowe pokoje"}.
{"Room description","Opis pokoju"}.
{"Room Occupants","Lista uczestników"}.
{"Room title","Tytuł pokoju"}.
{"Roster groups allowed to subscribe","Grupy kontaktów uprawnione do subskrypcji"}.
{"Roster","Lista kontaktów"}.
{"Roster of ","Lista kontaktów "}.
{"Roster size","Rozmiar listy kontaktów"}.
{"RPC Call Error","Błąd żądania RPC"}.
{"Running Nodes","Uruchomione węzły"}.
{"~s access rule configuration","~s konfiguracja zasad dostępu"}.
{"Saturday","Sobota"}.
{"Script check","Sprawdź skrypt"}.
{"Search Results for ","Wyniki wyszukiwania dla "}.
{"Search users in ","Wyszukaj użytkowników w "}.
{"Send announcement to all online users on all hosts","Wyślij powiadomienie do wszystkich zalogowanych użytkowników na wszystkich hostach"}.
{"Send announcement to all online users","Wyślij powiadomienie do wszystkich zalogowanych użytkowników"}.
{"Send announcement to all users on all hosts","Wyślij powiadomienie do wszystkich użytkowników na wszystkich hostach"}.
{"Send announcement to all users","Wyślij powiadomienie do wszystkich użytkowników"}.
{"September","Wrzesień"}.
{"Server ~b","Serwer ~b"}.
{"Server:","Serwer:"}.
{"Server","Serwer"}.
{"Set message of the day and send to online users","Wyślij wiadomość dnia do wszystkich zalogowanych użytkowników"}.
{"Set message of the day on all hosts and send to online users","Ustaw wiadomość dnia dla wszystkich hostów i wyślij do zalogowanych uzytkowników"}.
{"Shared Roster Groups","Wspólne grupy kontaktów"}.
{"Show Integral Table","Pokaż tabelę całkowitą"}.
{"Show Ordinary Table","Pokaż zwykłą tabelę"}.
{"Shut Down Service","Wyłącz usługę"}.
{"~s invites you to the room ~s","~s zaprasza Cię do pokoju ~s"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Niektóre klienty Jabber mogą zapisywać Twoje hasło na komputerze. Używaj tej opcji tylko jeśli ufasz komputerowi na którym pracujesz."}.
{"Specify the access model","Określ model dostępu"}.
{"Specify the event message type","Określ typ wiadomości"}.
{"Specify the publisher model","Określ model publikującego"}.
{"~s's Offline Messages Queue","Kolejka wiadomości offline użytkownika ~s"}.
{"Start Modules at ","Uruchom moduły na "}.
{"Start Modules","Uruchom moduły"}.
{"Start","Uruchom"}.
{"Statistics of ~p","Statystyki ~p"}.
{"Statistics","Statystyki"}.
{"Stop Modules at ","Zatrzymaj moduły na "}.
{"Stop Modules","Zatrzymaj moduły"}.
{"Stopped Nodes","Zatrzymane węzły"}.
{"Stop","Zatrzymaj"}.
{"Storage Type","Typ bazy"}.
{"Store binary backup:","Zachowaj kopię binarną:"}.
{"Store plain text backup:","Zachowaj kopię w postaci tekstowej:"}.
{"Subject","Temat"}.
{"Submitted","Wprowadzone"}.
{"Submit","Wyślij"}.
{"Subscriber Address","Adres subskrybenta"}.
{"Subscription","Subskrypcja"}.
{"Sunday","Niedziela"}.
{"That nickname is already in use by another occupant","Ta nazwa użytkownika jest używana przez kogoś innego"}.
{"That nickname is registered by another person","Ta nazwa użytkownika jest już zarejestrowana przez inną osobę"}.
{"The CAPTCHA is valid.","Captcha jest poprawna."}.
{"The CAPTCHA verification has failed","Weryfikacja CAPTCHA nie powiodła się."}.
{"The collections with which a node is affiliated","Grupy, do których należy węzeł"}.
{"the password is","hasło to:"}.
{"The password is too weak","Hasło nie jest wystarczająco trudne"}.
{"The password of your Jabber account was successfully changed.","Hasło do Twojego konta zostało zmienione."}.
{"There was an error changing the password: ","Podczas próby zmiany hasła wystąpił błąd:"}.
{"There was an error creating the account: ","Wystąpił błąd podczas tworzenia konta:"}.
{"There was an error deleting the account: ","Podczas usuwania konta wystąpił błąd:"}.
{"This IP address is blacklisted in ~s","Ten adres IP został zablokowany w ~s"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Pole nie rozróżnia wielkości liter: słowo Hanna jest takie samo jak hAnna lub haNNa."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Niniejsza strona pozwala na założenie konta Jabber na tym serwerze. Twój JID (Jabber IDentyfikator) będzie miał postać: nazwa_użytkownika@serwer. Przeczytaj dokładnie instrukcję i wypełnij pola."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Ta strona pozwala usunąć konto Jabber z tego serwera."}.
{"Thursday","Czwartek"}.
{"Time","Czas"}.
{"Time delay","Opóźnienie"}.
{"To","Do"}.
{"Too many CAPTCHA requests","Za dużo żądań CAPTCHA"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Zbyt wiele (~p) nieudanych prób logowanie z tego adresu IP (~s). Ten adres zostanie odblokowany o ~s UTC"}.
{"Too many unacked stanzas","Zbyt wiele niepotwierdzonych pakietów"}.
{"To ~s","Do ~s"}.
{"Total rooms","Wszystkich pokoi"}.
{"Traffic rate limit is exceeded","Limit transferu przekroczony"}.
{"Transactions Aborted:","Transakcje anulowane:"}.
{"Transactions Committed:","Transakcje zakończone:"}.
{"Transactions Logged:","Transakcje zalogowane:"}.
{"Transactions Restarted:","Transakcje uruchomione ponownie:"}.
{"Tuesday","Wtorek"}.
{"Unable to generate a CAPTCHA","Nie można wygenerować CAPTCHA"}.
{"Unauthorized","Nie autoryzowano"}.
{"Unregister a Jabber account","Usuń konto Jabber"}.
{"Unregister","Wyrejestruj"}.
{"Update","Aktualizuj"}.
{"Update message of the day (don't send)","Aktualizuj wiadomość dnia (bez wysyłania)"}.
{"Update message of the day on all hosts (don't send)","Aktualizuj wiadomość dnia na wszystkich hostach (bez wysyłania)"}.
{"Update plan","Plan aktualizacji"}.
{"Update ~p","Uaktualnij ~p"}.
{"Update script","Skrypt aktualizacji"}.
{"Uptime:","Czas pracy:"}.
{"Use of STARTTLS required","Wymagane jest użycie STARTTLS"}.
{"User JID","Użytkownik "}.
{"User Management","Zarządzanie użytkownikami"}.
{"Username:","Nazwa użytkownika:"}.
{"Users are not allowed to register accounts so quickly","Użytkowncy nie mogą tak szybko rejestrować nowych kont"}.
{"Users Last Activity","Ostatnia aktywność użytkowników"}.
{"Users","Użytkownicy"}.
{"User ~s","Użytkownik ~s"}.
{"User","Użytkownik"}.
{"Validate","Potwierdź"}.
{"vCard User Search","Wyszukiwanie vCard użytkowników"}.
{"Virtual Hosts","Wirtualne Hosty"}.
{"Visitor","Odwiedzający"}.
{"Visitors are not allowed to change their nicknames in this room","Uczestnicy tego pokoju nie mogą zmieniać swoich nicków"}.
{"Visitors are not allowed to send messages to all occupants","Odwiedzający nie mogą wysyłać wiadomości do wszystkich obecnych"}.
{"Voice requests are disabled in this conference","Głosowe żądania są wyłączone w tym pokoju"}.
{"Voice request","Żądanie głosowe"}.
{"Wednesday","Środa"}.
{"When to send the last published item","Kiedy wysłać ostatnio opublikowaną rzecz"}.
{"Whether to allow subscriptions","Czy pozwolić na subskrypcje"}.
{"You can later change your password using a Jabber client.","Możesz później zmienić swoje hasło za pomocą dowolnego klienta Jabber."}.
{"You have been banned from this room","Zostałeś wykluczony z tego pokoju"}.
{"You must fill in field \"Nickname\" in the form","Musisz wypełnić pole \"Nazwa użytkownika\" w formularzu"}.
{"You need a client that supports x:data and CAPTCHA to register","Potrzebujesz klienta obsługującego x:data aby zarejestrować nick"}.
{"You need a client that supports x:data to register the nickname","Potrzebujesz klienta obsługującego x:data aby zarejestrować nick"}.
{"You need an x:data capable client to configure mod_irc settings","Potrzebujesz klienta obsługującego x:data aby skonfigurować mod_irc"}.
{"You need an x:data capable client to configure room","Potrzebujesz klienta obsługującego x:data aby skonfigurować pokój"}.
{"You need an x:data capable client to search","Potrzebujesz klienta obsługującego x:data aby wyszukiwać"}.
{"Your active privacy list has denied the routing of this stanza.","Aktualna lista prywatności zabrania przesyłania tej stanzy"}.
{"Your contact offline message queue is full. The message has been discarded.","Kolejka wiadomości offline adresata jest pełna. Wiadomość została odrzucona."}.
{"Your Jabber account was successfully created.","Twoje konto zostało stworzone."}.
{"Your Jabber account was successfully deleted.","Twoje konto zostało usunięte."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Twoje wiadomości do ~s są blokowane. Aby je odblokować, odwiedź ~s"}.
