%% -*- coding: utf-8 -*-
{" has set the subject to: "," mudou o assunto para: "}.
{"A friendly name for the node","Um nome familiar para o nó"}.
{"A password is required to enter this room","Se necessita senha para entrar nesta sala"}.
{"Accept","Aceito"}.
{"Access denied by service policy","Acesso negado pela política do serviço"}.
{"Action on user","Ação no usuário"}.
{"Add Jabber ID","Adicionar ID jabber"}.
{"Add New","Adicionar novo"}.
{"Add User","Adicionar usuário"}.
{"Administration of ","Administração de "}.
{"Administration","Administração"}.
{"Administrator privileges required","Se necessita privilégios de administrador"}.
{"All activity","Todas atividades"}.
{"All Users","Todos os usuários"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Autorizar este Jabber ID para a inscrição neste tópico pubsub?"}.
{"Allow users to change the subject","Permitir a usuários modificar o assunto"}.
{"Allow users to query other users","Permitir a usuários pesquisar informações sobre os demais"}.
{"Allow users to send invites","Permitir a usuários envio de convites"}.
{"Allow users to send private messages","Permitir a usuários enviarem mensagens privadas"}.
{"Allow visitors to change nickname","Permitir mudança de apelido aos visitantes"}.
{"Allow visitors to send private messages to","Permitir visitantes enviar mensagem privada para"}.
{"Allow visitors to send status text in presence updates","Permitir atualizações de status aos visitantes"}.
{"Allow visitors to send voice requests","Permitir aos visitantes o envio de requisições de voz"}.
{"Announcements","Anúncios"}.
{"April","Abril"}.
{"August","Agosto"}.
{"Automatic node creation is not enabled","Criação automatizada de nós está desabilitada"}.
{"Backup Management","Gestão de Backup"}.
{"Backup of ~p","Backup de ~p"}.
{"Backup to File at ","Salvar backup para arquivo em "}.
{"Backup","Salvar cópia de segurança"}.
{"Bad format","Formato incorreto"}.
{"Birthday","Aniversário"}.
{"Both the username and the resource are required","Nome de usuário e recurso são necessários"}.
{"Bytestream already activated","Bytestream já foi ativado"}.
{"Cannot remove active list","Não é possível remover uma lista ativa"}.
{"Cannot remove default list","Não é possível remover uma lista padrão"}.
{"CAPTCHA web page","CAPTCHA web page"}.
{"Change Password","Mudar senha"}.
{"Change User Password","Alterar Senha do Usuário"}.
{"Characters not allowed:","Caracteres não aceitos:"}.
{"Chatroom configuration modified","Configuração da sala de bate-papo modificada"}.
{"Chatroom is created","A sala de chat está criada"}.
{"Chatroom is destroyed","A sala de chat está destruída"}.
{"Chatroom is started","A sala de chat está iniciada"}.
{"Chatroom is stopped","A sala de chat está parada"}.
{"Chatrooms","Salas de Chat"}.
{"Choose a username and password to register with this server","Escolha um nome de usuário e senha para registrar-se neste servidor"}.
{"Choose storage type of tables","Selecione o tipo de armazenamento das tabelas"}.
{"Choose whether to approve this entity's subscription.","Aprovar esta assinatura."}.
{"City","Cidade"}.
{"Commands","Comandos"}.
{"Conference room does not exist","A sala de conferência não existe"}.
{"Configuration of room ~s","Configuração para ~s"}.
{"Configuration","Configuração"}.
{"Connected Resources:","Recursos conectados:"}.
{"Country","País"}.
{"CPU Time:","Tempo de CPU"}.
{"Database Tables at ~p","Tabelas da Base de dados em ~p"}.
{"Database Tables Configuration at ","Configuração de Tabelas de Base de dados em "}.
{"Database","Base de dados"}.
{"December","Dezembro"}.
{"Default users as participants","Usuários padrões como participantes"}.
{"Delete message of the day on all hosts","Apagar a mensagem do dia em todos os hosts"}.
{"Delete message of the day","Apagar mensagem do dia"}.
{"Delete Selected","Remover os selecionados"}.
{"Delete User","Deletar Usuário"}.
{"Deliver event notifications","Entregar as notificações de evento"}.
{"Deliver payloads with event notifications","Enviar payloads junto com as notificações de eventos"}.
{"Description:","Descrição:"}.
{"Disc only copy","Somente cópia em disco"}.
{"Dump Backup to Text File at ","Exportar backup para texto em "}.
{"Dump to Text File","Exportar para arquivo texto"}.
{"Duplicated groups are not allowed by RFC6121","Grupos duplicados não são permitidos pela RFC6121"}.
{"Edit Properties","Editar propriedades"}.
{"Either approve or decline the voice request.","Você deve aprovar/desaprovar a requisição de voz."}.
{"ejabberd MUC module","Módulo de MUC para ejabberd"}.
{"ejabberd Multicast service","ejabberd Multicast service"}.
{"ejabberd Publish-Subscribe module","Módulo para Publicar Tópicos do ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","Modulo ejabberd SOCKS5 Bytestreams"}.
{"ejabberd vCard module","Módulo vCard para ejabberd"}.
{"ejabberd Web Admin","ejabberd Web Admin"}.
{"Elements","Elementos"}.
{"Email","Email"}.
{"Enable logging","Permitir criação de logs"}.
{"Enable message archiving","Habilitar arquivamento de mensagens"}.
{"Enabling push without 'node' attribute is not supported","Abilitar push sem o atributo 'node' não é suportado"}.
{"End User Session","Terminar Sessão do Usuário"}.
{"Enter nickname you want to register","Introduza o apelido que quer registrar"}.
{"Enter path to backup file","Introduza o caminho do arquivo de backup"}.
{"Enter path to jabberd14 spool dir","Introduza o caminho para o diretório de fila do jabberd14"}.
{"Enter path to jabberd14 spool file","Insira o caminho para a fila (arquivo) do jabberd14"}.
{"Enter path to text file","Introduza caminho para o arquivo texto"}.
{"Enter the text you see","Insira o texto que você vê"}.
{"Error","Erro"}.
{"Exclude Jabber IDs from CAPTCHA challenge","Excluir IDs Jabber de serem submetidos ao CAPTCHA"}.
{"Export all tables as SQL queries to a file:","Exportar todas as tabelas como SQL para um arquivo:"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Exportar todos os dados de todos os usuários no servidor, para arquivos formato PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Exportar dados dos usuários em um host, para arquivos PIEFXIS (XEP-0227):"}.
{"External component failure","Falha de componente externo"}.
{"External component timeout","Tempo esgotado à espera de componente externo"}.
{"Failed to activate bytestream","Falha ao ativar bytestream"}.
{"Failed to extract JID from your voice request approval","Não foi possível extrair o JID (Jabber ID) da requisição de voz"}.
{"Failed to map delegated namespace to external component","Falha ao mapear namespace delegado ao componente externo"}.
{"Failed to parse HTTP response","Falha ao analisar resposta HTTP"}.
{"Failed to process option '~s'","Falha ao processar opção '~s'"}.
{"Family Name","Sobrenome"}.
{"February","Fevereiro"}.
{"File larger than ~w bytes","Arquivo maior que ~w bytes"}.
{"Friday","Sexta"}.
{"From","De"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Obter Número de Usuários Online"}.
{"Get Number of Registered Users","Obter Número de Usuários Registrados"}.
{"Get User Last Login Time","Obter a Data do Último Login"}.
{"Get User Password","Obter Senha do Usuário"}.
{"Get User Statistics","Obter Estatísticas do Usuário"}.
{"Grant voice to this person?","Dar voz a esta pessoa?"}.
{"Group","Grupo"}.
{"Groups","Grupos"}.
{"has been banned","foi banido"}.
{"has been kicked because of a system shutdown","foi desconectado porque o sistema foi desligado"}.
{"has been kicked because of an affiliation change","foi desconectado porque por afiliação inválida"}.
{"has been kicked because the room has been changed to members-only","foi desconectado porque a política da sala mudou, só membros são permitidos"}.
{"has been kicked","foi removido"}.
{"Host unknown","Máquina desconhecida"}.
{"Host","Máquina"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Se você não conseguir ver o CAPTCHA aqui, visite a web page."}.
{"Import Directory","Importar diretório"}.
{"Import File","Importar arquivo"}.
{"Import user data from jabberd14 spool file:","Importar dados dos usuários de uma fila jabberd14:"}.
{"Import User from File at ","Importar usuário a partir do arquivo em "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importar usuários de um arquivo PIEFXIS (XEP-0227): "}.
{"Import users data from jabberd14 spool directory:","Importar dados dos usuários de um diretório-fila jabberd14:"}.
{"Import Users from Dir at ","Importar usuários a partir do diretório em "}.
{"Import Users From jabberd14 Spool Files","Importar usuários de arquivos jabberd14 (spool files)"}.
{"Improper domain part of 'from' attribute","Atributo 'from' contém domínio incorreto"}.
{"Improper message type","Tipo de mensagem incorreto"}.
{"Incoming s2s Connections:","Conexões s2s de Entrada:"}.
{"Incorrect CAPTCHA submit","CAPTCHA submetido incorretamente"}.
{"Incorrect password","Senha incorreta"}.
{"Incorrect value of 'action' attribute","Valor incorreto do atributo 'action'"}.
{"Incorrect value of 'action' in data form","Valor incorreto de 'action' no formulário de dados"}.
{"Incorrect value of 'path' in data form","Valor incorreto de 'path' no formulário de dados"}.
{"Insufficient privilege","Privilégio insuficiente"}.
{"Invalid 'from' attribute in forwarded message","Atributo 'from' inválido na mensagem reenviada"}.
{"IP addresses","Endereços IP"}.
{"is now known as","é agora conhecido como"}.
{"It is not allowed to send error messages to the room. The participant (~s) has sent an error message (~s) and got kicked from the room","Não é permitido o envio de mensagens de erro a esta sala. O membro (~s) enviou uma mensagem de erro (~s) e foi desconectado (\"kicked\")."}.
{"It is not allowed to send private messages of type \"groupchat\"","Não é permitido enviar mensagens privadas do tipo \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Não é permitido enviar mensagens privadas para a sala de conferência"}.
{"It is not allowed to send private messages","Não é permitido enviar mensagens privadas"}.
{"Jabber ID","ID Jabber"}.
{"January","Janeiro"}.
{"joins the room","Entrar na sala"}.
{"July","Julho"}.
{"June","Junho"}.
{"Last Activity","Última atividade"}.
{"Last login","Último login"}.
{"Last month","Último mês"}.
{"Last year","Último ano"}.
{"leaves the room","Sair da sala"}.
{"List of rooms","Lista de salas"}.
{"Low level update script","Script de atualização low level"}.
{"Make participants list public","Tornar pública a lista de participantes"}.
{"Make room CAPTCHA protected","Tornar protegida a senha da sala"}.
{"Make room members-only","Tornar sala apenas para membros"}.
{"Make room moderated","Tornar a sala moderada"}.
{"Make room password protected","Tornar sala protegida à senha"}.
{"Make room persistent","Tornar sala persistente"}.
{"Make room public searchable","Tornar sala pública possível de ser encontrada"}.
{"March","Março"}.
{"Max # of items to persist","Máximo # de elementos que persistem"}.
{"Max payload size in bytes","Máximo tamanho do payload em bytes"}.
{"Maximum Number of Occupants","Número máximo de participantes"}.
{"May","Maio"}.
{"Membership is required to enter this room","É necessário ser membro desta sala para poder entrar"}.
{"Members:","Membros:"}.
{"Memory","Memória"}.
{"Message body","Corpo da mensagem"}.
{"Message not found in forwarded payload","Mensagem não encontrada em conteúdo encaminhado"}.
{"Middle Name","Nome do meio"}.
{"Minimum interval between voice requests (in seconds)","O intervalo mínimo entre requisições de voz (em segundos)"}.
{"Moderator privileges required","Se necessita privilégios de moderador"}.
{"Moderator","Moderador"}.
{"Modified modules","Módulos atualizados"}.
{"Module failed to handle the query","Módulo falhou ao processar a consulta"}.
{"Monday","Segunda"}.
{"Multicast","Multicast"}.
{"Multiple <item/> elements are not allowed by RFC6121","Vários elementos <item/> não são permitidos pela RFC6121"}.
{"Multi-User Chat","Chat multi-usuário"}.
{"Name","Nome"}.
{"Name:","Nome:"}.
{"Neither 'jid' nor 'nick' attribute found","Nem o atributo 'jid' nem 'nick' foram encontrados"}.
{"Neither 'role' nor 'affiliation' attribute found","Nem o atributo 'role' nem 'affiliation' foram encontrados"}.
{"Never","Nunca"}.
{"New Password:","Nova Senha:"}.
{"Nickname Registration at ","Registro do apelido em "}.
{"Nickname ~s does not exist in the room","O apelido ~s não existe na sala"}.
{"Nickname","Apelido"}.
{"No 'affiliation' attribute found","Atributo 'affiliation' não foi encontrado"}.
{"No available resource found","Nenhum recurso disponível foi encontrado"}.
{"No body provided for announce message","Nenhum corpo de texto fornecido para anunciar mensagem"}.
{"No Data","Nenhum dado"}.
{"No features available","Nenhuma funcionalidade disponível"}.
{"No hook has processed this command","Nenhum hook processou este comando"}.
{"No info about last activity found","Não foi encontrada informação sobre última atividade"}.
{"No items found in this query","Nenhum item encontrado nesta consulta"}.
{"No limit","Ilimitado"}.
{"No module is handling this query","Nenhum módulo está processando esta consulta"}.
{"No node specified","Nenhum nó especificado"}.
{"No 'password' found in data form","'password' não foi encontrado em formulário de dados"}.
{"No 'password' found in this query","'password' não foi encontrado nesta consulta"}.
{"No 'path' found in data form","'path' não foi encontrado em formulário de dados"}.
{"No pending subscriptions found","Não foram encontradas subscrições"}.
{"No privacy list with this name found","Nenhuma lista de privacidade encontrada com este nome"}.
{"No private data found in this query","Nenhum dado privado encontrado nesta consulta"}.
{"No services available","Não há serviços disponíveis"}.
{"No statistics found for this item","Não foram encontradas estatísticas para este item"}.
{"No 'to' attribute found in the invitation","Atributo 'to' não foi encontrado no convite"}.
{"Node already exists","Nó já existe"}.
{"Node ID","ID do Tópico"}.
{"Node not found","Nó não encontrado"}.
{"Node ~p","Nó ~p"}.
{"Nodeprep has failed","Processo de identificação de nó falhou (nodeprep)"}.
{"Nodes","Nós"}.
{"None","Nenhum"}.
{"Not Found","Não encontrado"}.
{"Not subscribed","Não subscrito"}.
{"Notify subscribers when items are removed from the node","Notificar assinantes quando itens forem eliminados do nó"}.
{"Notify subscribers when the node configuration changes","Notificar assinantes a configuração do nó mudar"}.
{"Notify subscribers when the node is deleted","Notificar assinantes quando o nó for eliminado se elimine"}.
{"November","Novembro"}.
{"Number of occupants","Número de participantes"}.
{"Number of online users","Número de usuários online"}.
{"Number of registered users","Número de usuários registrados"}.
{"October","Outubro"}.
{"Offline Messages","Mensagens offline"}.
{"Offline Messages:","Mensagens offline"}.
{"OK","OK"}.
{"Old Password:","Senha Antiga:"}.
{"Online Users","Usuários conectados"}.
{"Online Users:","Usuários online"}.
{"Online","Conectado"}.
{"Only deliver notifications to available users","Somente enviar notificações aos usuários disponíveis"}.
{"Only <enable/> or <disable/> tags are allowed","Apenas tags <enable/> ou <disable/> são permitidas"}.
{"Only <list/> element is allowed in this query","Apenas elemento <list/> é permitido nesta consulta"}.
{"Only members may query archives of this room","Somente os membros podem procurar nos arquivos desta sala"}.
{"Only moderators and participants are allowed to change the subject in this room","Somente os moderadores e os participamentes podem alterar o assunto desta sala"}.
{"Only moderators are allowed to change the subject in this room","Somente os moderadores podem alterar o assunto desta sala"}.
{"Only moderators can approve voice requests","Somente moderadores podem aprovar requisições de voz"}.
{"Only occupants are allowed to send messages to the conference","Somente os ocupantes podem enviar mensagens à sala de conferência"}.
{"Only occupants are allowed to send queries to the conference","Somente os ocupantes podem enviar consultas à sala de conferência"}.
{"Only service administrators are allowed to send service messages","Apenas administradores possuem permissão para enviar mensagens de serviço"}.
{"Organization Name","Nome da organização"}.
{"Organization Unit","Departamento/Unidade"}.
{"Outgoing s2s Connections","Conexões s2s de Saída"}.
{"Outgoing s2s Connections:","Conexões s2s de Saída"}.
{"Owner privileges required","Se requer privilégios de proprietário da sala"}.
{"Packet","Pacote"}.
{"Participant","Participante"}.
{"Password Verification","Verificação de Senha"}.
{"Password Verification:","Verificação de Senha"}.
{"Password","Senha"}.
{"Password:","Senha:"}.
{"Path to Dir","Caminho para o diretório"}.
{"Path to File","Caminho do arquivo"}.
{"Pending","Pendente"}.
{"Period: ","Período: "}.
{"Persist items to storage","Persistir elementos ao armazenar"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Observe que tais opções farão backup apenas da base de dados Mnesia. Caso você esteja utilizando o modulo ODBC, você precisará fazer backup de sua base de dados SQL separadamente."}.
{"Please, wait for a while before sending new voice request","Por favor, espere antes de enviar uma nova requisição de voz"}.
{"Pong","Pong"}.
{"Possessing 'ask' attribute is not allowed by RFC6121","Possuir atributo 'ask' não é permitido pela RFC6121"}.
{"Present real Jabber IDs to","Tornar o Jabber ID real visível por"}.
{"private, ","privado, "}.
{"Publish-Subscribe","Publicação de Tópico"}.
{"PubSub subscriber request","PubSub requisição de assinante"}.
{"Purge all items when the relevant publisher goes offline","Descartar todos os itens quando o publicante principal estiver offline"}.
{"Queries to the conference members are not allowed in this room","Nesta sala de conferência, consultas aos membros não são permitidas"}.
{"Query to another users is forbidden","Consultar a outro usuário é proibido"}.
{"RAM and disc copy","Cópias na RAM e disco rígido"}.
{"RAM copy","Cópia em RAM"}.
{"Really delete message of the day?","Deletar realmente a mensagem do dia?"}.
{"Recipient is not in the conference room","O receptor não está na sala de conferência"}.
{"Registered Users:","Usuários registrados"}.
{"Registered Users","Usuários Registrados"}.
{"Register","Registrar"}.
{"Remote copy","Cópia remota"}.
{"Remove All Offline Messages","Remover Todas as Mensagens Offline"}.
{"Remove User","Remover usuário"}.
{"Remove","Remover"}.
{"Replaced by new connection","Substituído por nova conexão"}.
{"Resources","Recursos"}.
{"Restart Service","Reiniciar Serviço"}.
{"Restart","Reiniciar"}.
{"Restore Backup from File at ","Restaurar backup a partir do arquivo em "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Restaurar backup binário após reinicialização do ejabberd (requer menos memória):"}.
{"Restore binary backup immediately:","Restaurar backup binário imediatamente"}.
{"Restore plain text backup immediately:","Restaurar backup formato texto imediatamente:"}.
{"Restore","Restaurar"}.
{"Roles for which Presence is Broadcasted","Para quem a presença será notificada"}.
{"Room Configuration","Configuração de salas"}.
{"Room creation is denied by service policy","Sala não pode ser criada devido à política do serviço"}.
{"Room description","Descrição da Sala"}.
{"Room Occupants","Número de participantes"}.
{"Room title","Título da sala"}.
{"Roster groups allowed to subscribe","Listar grupos autorizados"}.
{"Roster size","Tamanho da Lista"}.
{"RPC Call Error","Erro de chamada RPC"}.
{"Running Nodes","Nós em execução"}.
{"Saturday","Sábado"}.
{"Script check","Verificação de Script"}.
{"Search Results for ","Resultados de pesquisa para "}.
{"Search users in ","Procurar usuários em "}.
{"Send announcement to all online users on all hosts","Enviar anúncio a todos usuários online em todas as máquinas"}.
{"Send announcement to all online users","Enviar anúncio a todos os usuárions online"}.
{"Send announcement to all users on all hosts","Enviar aviso para todos os usuários em todos os hosts"}.
{"Send announcement to all users","Enviar anúncio a todos os usuários"}.
{"September","Setembro"}.
{"Server:","Servidor:"}.
{"Set message of the day and send to online users","Definir mensagem do dia e enviar a todos usuários online"}.
{"Set message of the day on all hosts and send to online users","Definir mensagem do dia em todos os hosts e enviar para os usuários online"}.
{"Shared Roster Groups","Grupos Shared Roster"}.
{"Show Integral Table","Mostrar Tabela Integral"}.
{"Show Ordinary Table","Mostrar Tabela Ordinária"}.
{"Shut Down Service","Parar Serviço"}.
{"Specify the access model","Especificar os modelos de acesso"}.
{"Specify the event message type","Especificar o tipo de mensagem para o evento"}.
{"Specify the publisher model","Especificar o modelo do publicante"}.
{"Statistics of ~p","Estatísticas de ~p"}.
{"Statistics","Estatísticas"}.
{"Stop","Parar"}.
{"Stopped Nodes","Nós parados"}.
{"Storage Type","Tipo de armazenamento"}.
{"Store binary backup:","Armazenar backup binário:"}.
{"Store plain text backup:","Armazenar backup em texto:"}.
{"Subject","Assunto"}.
{"Submit","Enviar"}.
{"Submitted","Submetido"}.
{"Subscriber Address","Endereço dos Assinantes"}.
{"Subscriptions are not allowed","Subscrições não estão permitidas"}.
{"Subscription","Subscrição"}.
{"Sunday","Domingo"}.
{"That nickname is already in use by another occupant","O apelido (nick) já está sendo utilizado"}.
{"That nickname is registered by another person","O apelido já está registrado por outra pessoa"}.
{"The CAPTCHA is valid.","O CAPTCHA é inválido."}.
{"The CAPTCHA verification has failed","A verificação do CAPTCHA falhou"}.
{"The collections with which a node is affiliated","As coleções com as quais o nó está relacionado"}.
{"The feature requested is not supported by the conference","A funcionalidade solicitada não é suportada pela sala de conferência"}.
{"The password contains unacceptable characters","A senha contém caracteres proibidos"}.
{"The password is too weak","Senha considerada muito fraca"}.
{"the password is","a senha é"}.
{"The query is only allowed from local users","Esta consulta só é permitida a partir de usuários locais"}.
{"The query must not contain <item/> elements","A consulta não pode conter elementos <item/>"}.
{"The stanza MUST contain only one <active/> element, one <default/> element, or one <list/> element","A instância DEVE conter apenas um elemento <active/>, um elemento <default/>, ou um elemento <list/>"}.
{"This room is not anonymous","Essa sala não é anônima"}.
{"Thursday","Quinta"}.
{"Time delay","Intervalo (Tempo)"}.
{"Time","Tempo"}.
{"To register, visit ~s","Para registrar, visite ~s"}.
{"Token TTL","Token TTL"}.
{"Too many CAPTCHA requests","Número excessivo de requisições para o CAPTCHA"}.
{"Too many <item/> elements","Número excessivo de elementos <item/>"}.
{"Too many <list/> elements","Número excessivo de elementos <list/>"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Número excessivo (~p) de tentativas falhas de autenticação (~s). O endereço será desbloqueado às ~s UTC"}.
{"Too many unacked stanzas","Número excessivo de instâncias sem confirmação"}.
{"To","Para"}.
{"Total rooms","Salas no total"}.
{"Traffic rate limit is exceeded","Limite de banda excedido"}.
{"Transactions Aborted:","Transações abortadas:"}.
{"Transactions Committed:","Transações salvas:"}.
{"Transactions Logged:","Transações de log:"}.
{"Transactions Restarted:","Transações reiniciadas:"}.
{"Tuesday","Terça"}.
{"Unable to generate a CAPTCHA","Impossível gerar um CAPTCHA"}.
{"Unable to register route on existing local domain","Não foi possível registrar rota no domínio local existente"}.
{"Unauthorized","Não Autorizado"}.
{"Unexpected action","Ação inesperada"}.
{"Unregister","Deletar registro"}.
{"Unsupported <index/> element","Elemento <index/> não suportado"}.
{"Update message of the day (don't send)","Atualizar mensagem do dia (não enviar)"}.
{"Update message of the day on all hosts (don't send)","Atualizar a mensagem do dia em todos os host (não enviar)"}.
{"Update ~p","Atualizar ~p"}.
{"Update plan","Plano de Atualização"}.
{"Update script","Script de atualização"}.
{"Update","Atualizar"}.
{"Uptime:","Uptime:"}.
{"User already exists","Usuário já existe"}.
{"User (jid)","Usuário (jid)"}.
{"User JID","Usuário JID"}.
{"User Management","Gerenciamento de Usuários"}.
{"User session terminated","Sessão de usuário terminada"}.
{"Username:","Usuário:"}.
{"Users are not allowed to register accounts so quickly","Usuários não estão autorizados a registrar contas imediatamente"}.
{"Users Last Activity","Últimas atividades dos usuários"}.
{"Users","Usuários"}.
{"User","Usuário"}.
{"Validate","Validar"}.
{"Value 'get' of 'type' attribute is not allowed","Valor 'get' não permitido para atributo 'type'"}.
{"Value of '~s' should be boolean","Value de '~s' deveria ser um booleano"}.
{"Value of '~s' should be datetime string","Valor de '~s' deveria ser data e hora"}.
{"Value of '~s' should be integer","Valor de '~s' deveria ser um inteiro"}.
{"Value 'set' of 'type' attribute is not allowed","Valor 'set' não permitido para atributo 'type'"}.
{"vCard User Search","Busca de Usuário vCard"}.
{"Virtual Hosts","Hosts virtuais"}.
{"Visitors are not allowed to change their nicknames in this room","Nesta sala, os visitantes não podem mudar seus apelidos"}.
{"Visitors are not allowed to send messages to all occupants","Os visitantes não podem enviar mensagens a todos os ocupantes"}.
{"Visitor","Visitante"}.
{"Voice request","Requisição de voz"}.
{"Voice requests are disabled in this conference","Requisições de voz estão desabilitadas nesta sala de conferência"}.
{"Wednesday","Quarta"}.
{"When to send the last published item","Quando enviar o último tópico publicado"}.
{"Whether to allow subscriptions","Permitir subscrições"}.
{"You have been banned from this room","Você foi banido desta sala"}.
{"You have joined too many conferences","Você entrou em um número excessivo de salas de conferência"}.
{"You must fill in field \"Nickname\" in the form","Você deve completar o campo \"Apelido\" no formulário"}.
{"You need a client that supports x:data and CAPTCHA to register","Você precisa de um cliente com suporte de x:data para poder registrar o apelido"}.
{"You need a client that supports x:data to register the nickname","Você precisa de um cliente com suporte a x:data para registrar o seu apelido"}.
{"You need an x:data capable client to search","Necessitas um cliente com suporte de x:data para poder buscar"}.
{"Your active privacy list has denied the routing of this stanza.","Sua lista de privacidade ativa negou o roteamento desta instância."}.
{"Your contact offline message queue is full. The message has been discarded.","Sua fila de mensagens offline esta cheia. Sua mensagem foi descartada"}.
{"Your subscription request and/or messages to ~s have been blocked. To unblock your subscription request, visit ~s","Suas mensagens para ~s estão bloqueadas. Para desbloqueá-las, visite: ~s"}.
