%% -*- coding: latin-1 -*-
{"Access Configuration","Configuração de acessos"}.
{"Access Control List Configuration","Configuração da Lista de Controlo de Acesso"}.
{"Access control lists","Listas de Controlo de Acesso"}.
{"Access Control Lists","Listas de Controlo de Acesso"}.
{"Access denied by service policy","Acesso negado pela política de serviço"}.
{"Access rules","Regras de acesso"}.
{"Access Rules","Regras de Acesso"}.
{"Action on user","Acção no utilizador"}.
{"Add New","Adicionar novo"}.
{"Add User","Adicionar utilizador"}.
{"Administration of ","Administração de "}.
{"Administrator privileges required","São necessários privilégios de administrador"}.
{"All Users","Todos os utilizadores"}.
{"Backup","Guardar cópia de segurança"}.
{"Backup Management","Gestão de cópias de segurança"}.
{"Backup to File at ","Guardar cópia de segurança para ficheiro em "}.
{"Birthday","Data de nascimento"}.
{"Change Password","Mudar palavra-chave"}.
{"Choose a username and password to register with this server","Escolha um nome de utilizador e palavra-chave para se registar neste servidor"}.
{"Choose modules to stop","Seleccione os módulos a parar"}.
{"Choose storage type of tables","Seleccione o tipo de armazenagem das tabelas"}.
{"City","Cidade"}.
{"Conference room does not exist","A sala não existe"}.
{"Configuration","Configuração"}.
{"Connected Resources:","Recursos conectados:"}.
{"Country","País"}.
{"Delete Selected","Eliminar os seleccionados"}.
{"Disc only copy","Cópia apenas em disco"}.
{"Dump Backup to Text File at ","Exporta cópia de segurança para ficheiro de texto em "}.
{"Dump to Text File","Exportar para ficheiro de texto"}.
{"Edit Properties","Editar propriedades"}.
{"ejabberd IRC module","Módulo de IRC ejabberd"}.
{"ejabberd MUC module","Módulo MUC de ejabberd"}.
{"ejabberd vCard module","Módulo vCard de ejabberd"}.
{"Enter list of {Module, [Options]}","Introduza lista de {módulos, [opções]}"}.
{"Enter nickname you want to register","Introduza a alcunha que quer registar"}.
{"Enter path to backup file","Introduza o caminho do ficheiro de cópia de segurança"}.
{"Enter path to jabberd14 spool dir","Introduza o caminho para o directório de spools do jabberd14"}.
{"Enter path to jabberd14 spool file","Introduza o caminho para o ficheiro de spool do jabberd14"}.
{"Enter path to text file","Introduza caminho para o ficheiro de texto"}.
{"Erlang Jabber Server","Servidor Jabber em Erlang"}.
{"Family Name","Apelido"}.
{"Fill in fields to search for any matching Jabber User","Preencha os campos para procurar utilizadores Jabber coincidentes"}.
{"From","De"}.
{"From ~s","De ~s"}.
{"Full Name","Nome completo"}.
{"Groups","Grupos"}.
{" has set the subject to: "," colocou o tópico: "}.
{"Import Directory","Importar directório"}.
{"Import File","Importar ficheiro"}.
{"Import User from File at ","Importar utilizador a partir do ficheiro em "}.
{"Import Users from Dir at ","Importar utilizadores a partir do directório em "}.
{"Improper message type","Tipo de mensagem incorrecto"}.
{"Incorrect password","Palavra-chave incorrecta"}.
{"Invalid affiliation: ~s","Afiliação inválida: ~s"}.
{"Invalid role: ~s","Papel inválido: ~s"}.
{"IRC Username","Nome do utilizador de IRC"}.
{"It is not allowed to send private messages of type \"groupchat\"","Não é permitido enviar mensagens privadas do tipo \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Impedir o envio de mensagens privadas para a sala"}.
{"Jabber ID ~s is invalid","O Jabber ID ~s não é válido"}.
{"Last Activity","Última actividade"}.
{"Listened Ports at ","Portas em escuta em "}.
{"List of modules to start","Lista de módulos a iniciar"}.
{"Make room moderated","Tornar a sala moderada"}.
{"Memory","Memória"}.
{"Middle Name","Segundo nome"}.
{"Moderator privileges required","São necessários privilégios de moderador"}.
{"Module","Módulo"}.
{"Modules","Módulos"}.
{"Name","Nome"}.
{"Never","Nunca"}.
{"Nickname","Alcunha"}.
{"Nickname Registration at ","Registo da alcunha em "}.
{"Nickname ~s does not exist in the room","A alcunha ~s não existe na sala"}.
{"Node not found","Nodo não encontrado"}.
{"Nodes","Nodos"}.
{"None","Nenhum"}.
{"No resource provided","Não foi passado nenhum recurso"}.
{"OK","OK"}.
{"Online","Ligado"}.
{"Online Users","Utilizadores ligados"}.
{"Only occupants are allowed to send messages to the conference","Só os ocupantes podem enviar mensagens para a sala"}.
{"Only occupants are allowed to send queries to the conference","Só os ocupantes podem enviar consultas para a sala"}.
{"Only service administrators are allowed to send service messages","Só os administradores do serviço têm permissão para enviar mensagens de serviço"}.
{"Options","Opções"}.
{"Organization Name","Nome da organização"}.
{"Organization Unit","Unidade da organização"}.
{"Owner privileges required","São necessários privilégios de dono"}.
{"Packet","Pacote"}.
{"Password:","Palavra-chave:"}.
{"Password","Palavra-chave"}.
{"Path to Dir","Caminho para o directório"}.
{"Path to File","Caminho do ficheiro"}.
{"Pending","Pendente"}.
{"Port","Porta"}.
{"private, ","privado"}.
{"Queries to the conference members are not allowed in this room","Nesta sala não são permitidas consultas aos seus membros"}.
{"RAM and disc copy","Cópia em RAM e em disco"}.
{"RAM copy","Cópia em RAM"}.
{"Recipient is not in the conference room","O destinatário não está na sala"}.
{"Registration in mod_irc for ","Registo no mod_irc para"}.
{"Remote copy","Cópia remota"}.
{"Remove","Remover"}.
{"Remove User","Eliminar utilizador"}.
{"Restart","Reiniciar"}.
{"Restore Backup from File at ","Restaura cópia de segurança a partir do ficheiro em "}.
{"Restore","Restaurar"}.
{"Room title","Título da sala"}.
{"Roster","Lista de contactos"}.
{"Roster of ","Lista de contactos de "}.
{"Running Nodes","Nodos a correr"}.
{"~s access rule configuration","Configuração das Regra de Acesso ~s"}.
{"Search users in ","Procurar utilizadores em "}.
{"Start Modules at ","Iniciar os módulos em "}.
{"Start Modules","Iniciar módulos"}.
{"Statistics","Estatísticas"}.
{"Stop Modules at ","Parar módulos em "}.
{"Stop Modules","Parar módulos"}.
{"Stop","Parar"}.
{"Stopped Nodes","Nodos parados"}.
{"Storage Type","Tipo de armazenagem"}.
{"Submit","Enviar"}.
{"Subscription","Subscrição"}.
{"Time","Data"}.
{"To","Para"}.
{"To ~s","A ~s"}.
{"Update","Actualizar"}.
{"Users","Utilizadores"}.
{"User","Utilizador"}.
{"Visitors are not allowed to send messages to all occupants","Os visitantes não podem enviar mensagens para todos os ocupantes"}.
{"You have been banned from this room","Foi banido desta sala"}.
{"You need an x:data capable client to configure mod_irc settings","É necessário um cliente com suporte de x:data para configurar as opções do mod_irc"}.
{"You need an x:data capable client to configure room","É necessário um cliente com suporte de x:data para configurar a sala"}.
{"You need an x:data capable client to search","É necessário um cliente com suporte de x:data para poder procurar"}.
