%% -*- coding: latin-1 -*-
{"Access Configuration","Конфигурация доступа"}.
{"Access Control List Configuration","Конфигурация списков управления доступом"}.
{"Access control lists","Списки управления доступом"}.
{"Access Control Lists","Списки управления доступом"}.
{"Access denied by service policy","Доступ запрещён политикой службы"}.
{"Access rules","Правила доступа"}.
{"Access Rules","Правила доступа"}.
{"Action on user","Действие над пользователем"}.
{"Add Jabber ID","Добавить Jabber ID"}.
{"Add New","Добавить"}.
{"Add User","Добавить пользователя"}.
{"Administration of ","Администрирование "}.
{"Administration","Администрирование"}.
{"Administrator privileges required","Требуются права администратора"}.
{"A friendly name for the node","Легко запоминаемое имя для узла"}.
{"All activity","Вся статистика"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Разрешить этому Jabber ID подписаться на данный узел?"}.
{"Allow users to change the subject","Разрешить пользователям изменять тему"}.
{"Allow users to query other users","Разрешить iq-запросы к пользователям"}.
{"Allow users to send invites","Разрешить пользователям посылать приглашения"}.
{"Allow users to send private messages","Разрешить приватные сообщения"}.
{"Allow visitors to change nickname","Разрешить посетителям изменять псевдоним"}.
{"Allow visitors to send private messages to","Разрешить посетителям посылать приватные сообщения"}.
{"Allow visitors to send status text in presence updates","Разрешить посетителям вставлять текcт статуса в сообщения о присутствии"}.
{"Allow visitors to send voice requests","Разрешить посетителям запрашивать право голоса"}.
{"All Users","Все пользователи"}.
{"Announcements","Объявления"}.
{"anyone","всем участникам"}.
{"A password is required to enter this room","Чтобы войти в эту конференцию, нужен пароль"}.
{"April","апреля"}.
{"August","августа"}.
{"Backup Management","Управление резервным копированием"}.
{"Backup of ~p","Резервное копирование ~p"}.
{"Backup to File at ","Резервное копирование в файл на "}.
{"Backup","Резервное копирование"}.
{"Bad format","Неправильный формат"}.
{"Birthday","День рождения"}.
{"CAPTCHA web page","Ссылка на капчу"}.
{"Change Password","Сменить пароль"}.
{"Change User Password","Изменить пароль пользователя"}.
{"Characters not allowed:","Недопустимые символы:"}.
{"Chatroom configuration modified","Конфигурация комнаты изменилась"}.
{"Chatroom is created","Комната создана"}.
{"Chatroom is destroyed","Комната уничтожена"}.
{"Chatroom is started","Комната запущена"}.
{"Chatroom is stopped","Комната остановлена"}.
{"Chatrooms","Комнаты"}.
{"Choose a username and password to register with this server","Выберите имя пользователя и пароль для регистрации на этом сервере"}.
{"Choose modules to stop","Выберите модули, которые следует остановить"}.
{"Choose storage type of tables","Выберите тип хранения таблиц"}.
{"Choose whether to approve this entity's subscription.","Решите: предоставить ли подписку этому объекту."}.
{"City","Город"}.
{"Commands","Команды"}.
{"Conference room does not exist","Конференция не существует"}.
{"Configuration of room ~s","Конфигурация комнаты ~s"}.
{"Configuration","Конфигурация"}.
{"Connected Resources:","Подключённые ресурсы:"}.
{"Connections parameters","Параметры соединения"}.
{"Country","Страна"}.
{"CPU Time:","Процессорное время:"}.
{"Database Tables at ~p","Таблицы базы данных на ~p"}.
{"Database Tables Configuration at ","Конфигурация таблиц базы данных на "}.
{"Database","База данных"}.
{"December","декабря"}.
{"Default users as participants","Сделать пользователей участниками по умолчанию"}.
{"Delete message of the day on all hosts","Удалить сообщение дня со всех виртуальных серверов"}.
{"Delete message of the day","Удалить сообщение дня"}.
{"Delete Selected","Удалить выделенные"}.
{"Delete User","Удалить пользователя"}.
{"Deliver event notifications","Доставлять уведомления о событиях"}.
{"Deliver payloads with event notifications","Доставлять вместе с уведомлениями o публикациях сами публикации"}.
{"Description:","Описание:"}.
{"Disc only copy","только диск"}.
{"Displayed Groups:","Видимые группы:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Не говорите никому свой пароль, даже администраторам сервера."}.
{"Dump Backup to Text File at ","Копирование в текстовый файл на "}.
{"Dump to Text File","Копирование в текстовый файл"}.
{"Edit Properties","Изменить параметры"}.
{"Either approve or decline the voice request.","Подтвердите или отклоните право голоса."}.
{"ejabberd IRC module","ejabberd IRC модуль"}.
{"ejabberd MUC module","ejabberd MUC модуль"}.
{"ejabberd Multicast service","ejabberd Multicast сервис"}.
{"ejabberd Publish-Subscribe module","Модуль ejabberd Публикации-Подписки"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams модуль"}.
{"ejabberd vCard module","ejabberd vCard модуль"}.
{"ejabberd Web Admin","Web-интерфейс администрирования ejabberd"}.
{"Elements","Элементы"}.
{"Email","Электронная почта"}.
{"Enable logging","Включить журналирование"}.
{"Enable message archiving","Включить хранение сообщений"}.
{"Encoding for server ~b","Кодировка сервера ~b"}.
{"End User Session","Завершить сеанс пользователя"}.
{"Enter list of {Module, [Options]}","Введите список вида {Module, [Options]}"}.
{"Enter nickname you want to register","Введите псевдоним, который Вы хотели бы зарегистрировать"}.
{"Enter path to backup file","Введите путь к резервному файлу"}.
{"Enter path to jabberd14 spool dir","Введите путь к директории спула jabberd14"}.
{"Enter path to jabberd14 spool file","Введите путь к файлу из спула jabberd14"}.
{"Enter path to text file","Введите путь к текстовому файлу"}.
{"Enter the text you see","Введите увиденный текст"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","Введите имя пользователя и кодировки, которые будут использоваться при подключении к IRC-серверам. Нажмите 'Далее' для получения дополнительных полей для заполнения. Нажмите 'Завершить' для сохранения настроек."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","Введите имя пользователя, кодировки, порты и пароли, которые будут использоваться при подключении к IRC-серверам"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Ошибка"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","Пример: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","Исключить показ капчи для списка Jabber ID"}.
{"Export all tables as SQL queries to a file:","Экспортировать все таблицы в виде SQL запросов в файл:"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Экспорт данных всех пользователей сервера в файлы формата PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Экспорт пользовательских данных домена в файлы формата PIEFXIS (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","Ошибка обработки JID из вашего запроса на право голоса"}.
{"Family Name","Фамилия"}.
{"February","февраля"}.
{"Fill in fields to search for any matching Jabber User","Заполните форму для поиска пользователя Jabber"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Заполните форму для поиска пользователя Jabber (Если добавить * в конец поля, то происходит поиск подстроки)"}.
{"Friday","Пятница"}.
{"From ~s","От ~s"}.
{"From","От кого"}.
{"Full Name","Полное имя"}.
{"Get Number of Online Users","Получить количество подключённых пользователей"}.
{"Get Number of Registered Users","Получить количество зарегистрированных пользователей"}.
{"Get User Last Login Time","Получить время последнего подключения пользователя"}.
{"Get User Password","Получить пароль пользователя"}.
{"Get User Statistics","Получить статистику по пользователю"}.
{"Grant voice to this person?","Предоставить голос?"}.
{"Groups","Группы"}.
{"Group ","Группа "}.
{"has been banned","запретили входить в комнату"}.
{"has been kicked because of an affiliation change","выгнали из комнаты вследствие смены ранга"}.
{"has been kicked because of a system shutdown","выгнали из комнаты из-за останова системы"}.
{"has been kicked because the room has been changed to members-only","выгнали из комнаты потому что она стала только для членов"}.
{"has been kicked","выгнали из комнаты"}.
{" has set the subject to: "," установил(а) тему: "}.
{"Host","Хост"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Если вы не видите изображение капчи, перейдите по ссылке."}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","Чтобы указать различные порты, пароли, кодировки для разных серверов IRC, заполните список значениями в формате '{\"сервер IRC\", \"кодировка\", порт, \"пароль\"}'. По умолчанию сервис использует кодировку \"~s\", порт ~p, пустой пароль."}.
{"Import Directory","Импорт из директории"}.
{"Import File","Импорт из файла"}.
{"Import user data from jabberd14 spool file:","Импорт пользовательских данных из буферного файла jabberd14:"}.
{"Import User from File at ","Импорт пользователя из файла на "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Импорт пользовательских данных из файла формата PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Импорт пользовательских данных из буферной директории jabberd14:"}.
{"Import Users from Dir at ","Импорт пользователей из директории на "}.
{"Import Users From jabberd14 Spool Files","Импорт пользователей из спула jabberd14"}.
{"Improper message type","Неправильный тип сообщения"}.
{"Incorrect password","Неправильный пароль"}.
{"Invalid affiliation: ~s","Недопустимый ранг: ~s"}.
{"Invalid role: ~s","Недопустимая роль: ~s"}.
{"IP addresses","IP адреса"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","Канал IRC (без символа #)"}.
{"IRC server","Сервер IRC"}.
{"IRC settings","Настройки IRC"}.
{"IRC Transport","IRC Транспорт"}.
{"IRC username","Имя пользователя IRC"}.
{"IRC Username","Имя пользователя IRC"}.
{"is now known as","изменил(а) имя на"}.
{"It is not allowed to send private messages of type \"groupchat\"","Нельзя посылать частные сообщения типа \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Не разрешается посылать частные сообщения прямо в конференцию"}.
{"It is not allowed to send private messages","Запрещено посылать приватные сообщения"}.
{"Jabber Account Registration","Регистрация Jabber-аккаунта"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s недопустимый"}.
{"January","января"}.
{"Join IRC channel","Присоединиться к каналу IRC"}.
{"joins the room","вошёл(а) в комнату"}.
{"Join the IRC channel here.","Присоединяйтесь к каналу IRC"}.
{"Join the IRC channel in this Jabber ID: ~s","Присоединиться к каналу IRC с Jabber ID: ~s"}.
{"July","июля"}.
{"June","июня"}.
{"Last Activity","Последнее подключение"}.
{"Last login","Время последнего подключения"}.
{"Last month","За последний месяц"}.
{"Last year","За последний год"}.
{"leaves the room","вышел(а) из комнаты"}.
{"Listened Ports at ","Прослушиваемые порты на "}.
{"Listened Ports","Прослушиваемые порты"}.
{"List of modules to start","Список запускаемых модулей"}.
{"List of rooms","Список комнат"}.
{"Low level update script","Низкоуровневый сценарий обновления"}.
{"Make participants list public","Сделать список участников видимым всем"}.
{"Make room CAPTCHA protected","Сделать комнату защищённой капчей"}.
{"Make room members-only","Комната только для зарегистрированных участников"}.
{"Make room moderated","Сделать комнату модерируемой"}.
{"Make room password protected","Сделать комнату защищённой паролем"}.
{"Make room persistent","Сделать комнату постоянной"}.
{"Make room public searchable","Сделать комнату видимой всем"}.
{"March","марта"}.
{"Maximum Number of Occupants","Максимальное количество участников"}.
{"Max # of items to persist","Максимальное число сохраняемых публикаций"}.
{"Max payload size in bytes","Максимальный размер полезной нагрузки в байтах"}.
{"May","мая"}.
{"Membership is required to enter this room","В эту конференцию могут входить только её члены"}.
{"Members:","Члены:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Запомните пароль или запишите его на бумаге, которую сохраните в безопасном месте. В Jabber'е нет автоматизированного средства восстановления пароля в том случае, если Вы его забудете."}.
{"Memory","Память"}.
{"Message body","Тело сообщения"}.
{"Middle Name","Отчество"}.
{"Minimum interval between voice requests (in seconds)","Минимальный интервал между запросами на право голоса"}.
{"Moderator privileges required","Требуются права модератора"}.
{"moderators only","только модераторам"}.
{"Modified modules","Изменённые модули"}.
{"Modules at ~p","Модули на ~p"}.
{"Modules","Модули"}.
{"Module","Модуль"}.
{"Monday","Понедельник"}.
{"Multicast","Мультикаст"}.
{"Multi-User Chat","Конференция"}.
{"Name:","Название:"}.
{"Name","Название"}.
{"Never","Никогда"}.
{"New Password:","Новый пароль:"}.
{"Nickname Registration at ","Регистрация псевдонима на "}.
{"Nickname ~s does not exist in the room","Псевдоним ~s в комнате отсутствует"}.
{"Nickname","Псевдоним"}.
{"No body provided for announce message","Тело объявления не должно быть пустым"}.
{"nobody","никто"}.
{"No Data","Нет данных"}.
{"Node ID","ID узла"}.
{"Node not found","Узел не найден"}.
{"Node ~p","Узел ~p"}.
{"Nodes","Узлы"}.
{"No limit","Не ограничено"}.
{"None","Нет"}.
{"No resource provided","Не указан ресурс"}.
{"Not Found","Не Найдено"}.
{"Notify subscribers when items are removed from the node","Уведомлять подписчиков об удалении публикаций из сборника"}.
{"Notify subscribers when the node configuration changes","Уведомлять подписчиков об изменении конфигурации сборника"}.
{"Notify subscribers when the node is deleted","Уведомлять подписчиков об удалении сборника"}.
{"November","ноября"}.
{"Number of occupants","Число присутствующих"}.
{"Number of online users","Количество подключённых пользователей"}.
{"Number of registered users","Количество зарегистрированных пользователей"}.
{"October","октября"}.
{"Offline Messages:","Офлайновые сообщения:"}.
{"Offline Messages","Офлайновые сообщения"}.
{"OK","Продолжить"}.
{"Old Password:","Старый пароль:"}.
{"Online Users:","Подключённые пользователи:"}.
{"Online Users","Подключённые пользователи"}.
{"Online","Подключён"}.
{"Only deliver notifications to available users","Доставлять уведомления только доступным пользователям"}.
{"Only moderators and participants are allowed to change the subject in this room","Только модераторы и участники могут изменять тему в этой комнате"}.
{"Only moderators are allowed to change the subject in this room","Только модераторы могут изменять тему в этой комнате"}.
{"Only moderators can approve voice requests","Только модераторы могут утверждать запросы на право голоса"}.
{"Only occupants are allowed to send messages to the conference","Только присутствующим разрешается посылать сообщения в конференцию"}.
{"Only occupants are allowed to send queries to the conference","Только присутствующим разрешается посылать запросы в конференцию"}.
{"Only service administrators are allowed to send service messages","Только администратор службы может посылать служебные сообщения"}.
{"Options","Параметры"}.
{"Organization Name","Название организации"}.
{"Organization Unit","Отдел организации"}.
{"Outgoing s2s Connections:","Исходящие s2s-серверы:"}.
{"Outgoing s2s Connections","Исходящие s2s-соединения"}.
{"Owner privileges required","Требуются права владельца"}.
{"Packet","Пакет"}.
{"Password ~b","Пароль ~b"}.
{"Password Verification:","Проверка пароля:"}.
{"Password Verification","Проверка пароля"}.
{"Password:","Пароль:"}.
{"Password","Пароль"}.
{"Path to Dir","Путь к директории"}.
{"Path to File","Путь к файлу"}.
{"Pending","Ожидание"}.
{"Period: ","Период"}.
{"Permanent rooms","Постоянные комнаты"}.
{"Persist items to storage","Сохранять публикации в хранилище"}.
{"Ping","Пинг"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Заметьте, что здесь производится резервное копирование только встроенной базы данных Mnesia. Если Вы также используете другое хранилище данных (например с помощью модуля ODBC), то его резервное копирование следует осуществлять отдельно."}.
{"Please, wait for a while before sending new voice request","Пожалуйста, подождите перед тем как подать новый запрос на право голоса"}.
{"Pong","Понг"}.
{"Port ~b","Порт ~b"}.
{"Port","Порт"}.
{"Present real Jabber IDs to","Сделать реальные Jabber ID участников видимыми"}.
{"private, ","приватная, "}.
{"Protocol","Протокол"}.
{"Publish-Subscribe","Публикация-Подписка"}.
{"PubSub subscriber request","Запрос подписчика PubSub"}.
{"Purge all items when the relevant publisher goes offline","Очищать все записи автора публикации когда он отключается"}.
{"Queries to the conference members are not allowed in this room","Запросы к пользователям в этой конференции запрещены"}.
{"RAM and disc copy","ОЗУ и диск"}.
{"RAM copy","ОЗУ"}.
{"Raw","Необработанный формат"}.
{"Really delete message of the day?","Действительно удалить сообщение дня?"}.
{"Recipient is not in the conference room","Адресата нет в конференции"}.
{"Register a Jabber account","Зарегистрировать Jabber-аккаунт"}.
{"Registered nicknames","Зарегистрированные псевдонимы"}.
{"Registered Users:","Зарегистрированные пользователи:"}.
{"Registered Users","Зарегистрированные пользователи"}.
{"Register","Зарегистрировать"}.
{"Registration in mod_irc for ","Регистрация в mod_irc для "}.
{"Remote copy","не хранится локально"}.
{"Remove All Offline Messages","Удалить все офлайновые сообщения"}.
{"Remove User","Удалить пользователя"}.
{"Remove","Удалить"}.
{"Replaced by new connection","Заменено новым соединением"}.
{"Resources","Ресурсы"}.
{"Restart Service","Перезапустить службу"}.
{"Restart","Перезапустить"}.
{"Restore Backup from File at ","Восстановление из резервной копии на "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Восстановить из бинарной резервной копии при следующем запуске (требует меньше памяти):"}.
{"Restore binary backup immediately:","Восстановить из бинарной резервной копии немедленно:"}.
{"Restore plain text backup immediately:","Восстановить из текстовой резервной копии немедленно:"}.
{"Restore","Восстановление из резервной копии"}.
{"Room Configuration","Конфигурация комнаты"}.
{"Room creation is denied by service policy","Cоздавать конференцию запрещено политикой службы"}.
{"Room description","Описание комнаты"}.
{"Room Occupants","Участники комнаты"}.
{"Room title","Название комнаты"}.
{"Roster groups allowed to subscribe","Группы списка контактов, которым разрешена подписка"}.
{"Roster of ","Ростер пользователя "}.
{"Roster size","Размер списка контактов"}.
{"Roster","Ростер"}.
{"RPC Call Error","Ошибка вызова RPC"}.
{"Running Nodes","Работающие узлы"}.
{"~s access rule configuration","Конфигурация правила доступа ~s"}.
{"Saturday","Суббота"}.
{"Script check","Проверка сценария"}.
{"Search Results for ","Результаты поиска в "}.
{"Search users in ","Поиск пользователей в "}.
{"Send announcement to all online users on all hosts","Разослать объявление всем подключённым пользователям на всех виртуальных серверах"}.
{"Send announcement to all online users","Разослать объявление всем подключённым пользователям"}.
{"Send announcement to all users on all hosts","Разослать объявление всем пользователям на всех виртуальных серверах"}.
{"Send announcement to all users","Разослать объявление всем пользователям"}.
{"September","сентября"}.
{"Server ~b","Сервер ~b"}.
{"Server:","Сервер:"}.
{"Set message of the day and send to online users","Установить сообщение дня и разослать его подключённым пользователям"}.
{"Set message of the day on all hosts and send to online users","Установить сообщение дня на всех виртуальных серверах и разослать его подключённым пользователям"}.
{"Shared Roster Groups","Группы общих контактов"}.
{"Show Integral Table","Показать интегральную таблицу"}.
{"Show Ordinary Table","Показать обычную таблицу"}.
{"Shut Down Service","Остановить службу"}.
{"~s invites you to the room ~s","~s приглашает вас в комнату ~s"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Некоторые Jabber-клиенты могут сохранять пароль на Вашем компьютере. Используйте эту функцию только в том случае, если считаете это безопасным."}.
{"Specify the access model","Укажите механизм управления доступом"}.
{"Specify the event message type","Укажите тип сообщения о событии"}.
{"Specify the publisher model","Условия публикации"}.
{"~s's Offline Messages Queue","Oчередь офлайновых сообщений ~s"}.
{"Start Modules at ","Запуск модулей на "}.
{"Start Modules","Запуск модулей"}.
{"Start","Запустить"}.
{"Statistics of ~p","статистика узла ~p"}.
{"Statistics","Статистика"}.
{"Stop Modules at ","Остановка модулей на "}.
{"Stop Modules","Остановка модулей"}.
{"Stopped Nodes","Остановленные узлы"}.
{"Stop","Остановить"}.
{"Storage Type","Тип таблицы"}.
{"Store binary backup:","Сохранить бинарную резервную копию:"}.
{"Store plain text backup:","Сохранить текстовую резервную копию:"}.
{"Subject","Тема"}.
{"Submitted","Отправлено"}.
{"Submit","Отправить"}.
{"Subscriber Address","Адрес подписчика"}.
{"Subscription","Подписка"}.
{"Sunday","Воскресенье"}.
{"That nickname is already in use by another occupant","Этот псевдоним уже занят другим участником"}.
{"That nickname is registered by another person","Этот псевдоним зарегистрирован кем-то другим"}.
{"The CAPTCHA is valid.","Проверка капчи прошла успешно."}.
{"The CAPTCHA verification has failed","Проверка капчи не пройдена"}.
{"The collections with which a node is affiliated","Имя коллекции, в которую входит узел"}.
{"The password is too weak","Слишком слабый пароль"}.
{"the password is","пароль:"}.
{"The password of your Jabber account was successfully changed.","Пароль Вашего Jabber-аккаунта был успешно изменен."}.
{"There was an error changing the password: ","Ошибка при смене пароля:"}.
{"There was an error creating the account: ","Ошибка при создании аккаунта:"}.
{"There was an error deleting the account: ","Ошибка при удалении аккаунта:"}.
{"This IP address is blacklisted in ~s","Этот IP адрес находится в чёрном списке ~s"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Регистр не имеет значения: \"маша\" и \"МАША\" будет считаться одним и тем же именем."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Здесь Вы можете создать Jabber-аккаунт на этом Jabber-сервере. Ваш JID (Jabber-идентификатор) будет в виде: \"пользователь@сервер\". Пожалуйста, внимательно читайте инструкции для правильного заполнения полей."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Здесь Вы можете удалить Jabber-аккаунт с этого сервера."}.
{"Thursday","Четверг"}.
{"Time delay","По истечение"}.
{"Time","Время"}.
{"Too many CAPTCHA requests","Слишком много запросов капчи"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Слишком много (~p) неудачных попыток аутентификации с этого IP-адреса (~s). Адрес будет разблокирован в ~s UTC"}.
{"Too many unacked stanzas","Слишком много неподтверждённых пакетов"}.
{"To ~s","К ~s"}.
{"Total rooms","Все комнаты"}.
{"To","Кому"}.
{"Traffic rate limit is exceeded","Превышен лимит скорости посылки информации"}.
{"Transactions Aborted:","Транзакции отмененные:"}.
{"Transactions Committed:","Транзакции завершенные:"}.
{"Transactions Logged:","Транзакции запротоколированные:"}.
{"Transactions Restarted:","Транзакции перезапущенные:"}.
{"Tuesday","Вторник"}.
{"Unable to generate a CAPTCHA","Не получилось создать капчу"}.
{"Unauthorized","Не авторизован"}.
{"Unregister a Jabber account","Удалить Jabber-аккаунт"}.
{"Unregister","Удалить"}.
{"Update message of the day (don't send)","Обновить сообщение дня (не рассылать)"}.
{"Update message of the day on all hosts (don't send)","Обновить сообщение дня на всех виртуальных серверах (не рассылать)"}.
{"Update plan","План обновления"}.
{"Update ~p","Обновление ~p"}.
{"Update script","Сценарий обновления"}.
{"Update","Обновить"}.
{"Uptime:","Время работы:"}.
{"Use of STARTTLS required","Вы обязаны использовать STARTTLS"}.
{"User JID","JID пользователя"}.
{"User Management","Управление пользователями"}.
{"Username:","Имя пользователя:"}.
{"Users are not allowed to register accounts so quickly","Пользователи не могут регистрировать учётные записи так быстро"}.
{"Users Last Activity","Статистика последнего подключения пользователей"}.
{"Users","Пользователи"}.
{"User ~s","Пользователь ~s"}.
{"User","Пользователь"}.
{"Validate","Утвердить"}.
{"vCard User Search","Поиск пользователей по vCard"}.
{"Virtual Hosts","Виртуальные хосты"}.
{"Visitors are not allowed to change their nicknames in this room","Посетителям запрещено изменять свои псевдонимы в этой комнате"}.
{"Visitors are not allowed to send messages to all occupants","Посетителям не разрешается посылать сообщения всем присутствующим"}.
{"Voice requests are disabled in this conference","Запросы на право голоса отключены в этой конференции"}.
{"Voice request","Запрос на право голоса"}.
{"Wednesday","Среда"}.
{"When to send the last published item","Когда посылать последний опубликованный элемент"}.
{"Whether to allow subscriptions","Разрешить подписку"}.
{"You can later change your password using a Jabber client.","Позже Вы можете изменить пароль через Jabber-клиент."}.
{"You have been banned from this room","Вам запрещено входить в эту конференцию"}.
{"You must fill in field \"Nickname\" in the form","Вы должны заполнить поле \"Псевдоним\" в форме"}.
{"You need a client that supports x:data and CAPTCHA to register","Чтобы зарегистрироваться, требуется x:data-совместимый клиент"}.
{"You need a client that supports x:data to register the nickname","Чтобы зарегистрировать псевдоним, требуется x:data-совместимый клиент"}.
{"You need an x:data capable client to configure mod_irc settings","Чтобы настроить параметры mod_irc, требуется x:data-совместимый клиент"}.
{"You need an x:data capable client to configure room","Чтобы сконфигурировать комнату, требуется x:data-совместимый клиент"}.
{"You need an x:data capable client to search","Чтобы воспользоваться поиском, требуется x:data-совместимый клиент"}.
{"Your active privacy list has denied the routing of this stanza.","Маршрутизация этой строфы запрещена вашим активным списком приватности."}.
{"Your contact offline message queue is full. The message has been discarded.","Очередь недоставленных сообщений Вашего адресата переполнена. Сообщение не было сохранено."}.
{"Your Jabber account was successfully created.","Ваш Jabber-аккаунт был успешно создан."}.
{"Your Jabber account was successfully deleted.","Ваш Jabber-аккаунт был успешно удален."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Ваши сообщения к ~s блокируются. Для снятия блокировки перейдите по ссылке ~s"}.
