%% -*- coding: utf-8 -*-
{" (Add * to the end of field to match substring)"," (Добавьте * в конец поля для поиска подстроки)"}.
{" has set the subject to: "," установил(а) тему: "}.
{"A password is required to enter this room","Чтобы войти в эту конференцию, нужен пароль"}.
{"Accept","Принять"}.
{"Access denied by service policy","Доступ запрещён политикой службы"}.
{"Account doesn't exist","Учётная запись не существует"}.
{"Action on user","Действие над пользователем"}.
{"Add Jabber ID","Добавить Jabber ID"}.
{"Add New","Добавить"}.
{"Add User","Добавить пользователя"}.
{"Administration of ","Администрирование "}.
{"Administration","Администрирование"}.
{"Administrator privileges required","Требуются права администратора"}.
{"All activity","Вся статистика"}.
{"All Users","Все пользователи"}.
{"Allow users to change the subject","Разрешить пользователям изменять тему"}.
{"Allow users to query other users","Разрешить iq-запросы к пользователям"}.
{"Allow users to send invites","Разрешить пользователям посылать приглашения"}.
{"Allow users to send private messages","Разрешить приватные сообщения"}.
{"Allow visitors to change nickname","Разрешить посетителям изменять псевдоним"}.
{"Allow visitors to send private messages to","Разрешить посетителям посылать приватные сообщения"}.
{"Allow visitors to send status text in presence updates","Разрешить посетителям вставлять текcт статуса в сообщения о присутствии"}.
{"Announcements","Объявления"}.
{"April","апреля"}.
{"Attribute 'channel' is required for this request","Атрибут 'channel' является обязательным для этого запроса"}.
{"Attribute 'id' is mandatory for MIX messages","Атрибут 'id' является обязательным для MIX сообщений"}.
{"Attribute 'jid' is not allowed here","Атрибут 'jid' здесь недопустим"}.
{"Attribute 'node' is not allowed here","Атрибут 'node' здесь недопустим"}.
{"August","августа"}.
{"Automatic node creation is not enabled","Автоматическое создание узлов недоступно"}.
{"Backup Management","Управление резервным копированием"}.
{"Backup of ~p","Резервное копирование ~p"}.
{"Backup to File at ","Резервное копирование в файл на "}.
{"Backup","Резервное копирование"}.
{"Bad format","Неправильный формат"}.
{"Birthday","День рождения"}.
{"Both the username and the resource are required","Требуются имя пользователя и ресурс"}.
{"Bytestream already activated","Поток данных уже активирован"}.
{"Cannot remove active list","Невозможно удалить активный список"}.
{"Cannot remove default list","Невозможно удалить список по умолчанию"}.
{"Change Password","Сменить пароль"}.
{"Change User Password","Изменить пароль пользователя"}.
{"Changing password is not allowed","Изменение пароля не разрешено"}.
{"Changing role/affiliation is not allowed","Изменение роли/ранга не разрешено"}.
{"Channel already exists","Канал уже существует"}.
{"Channel does not exist","Канал не существует"}.
{"Channels","Каналы"}.
{"Characters not allowed:","Недопустимые символы:"}.
{"Chatroom configuration modified","Конфигурация комнаты изменилась"}.
{"Chatroom is created","Комната создана"}.
{"Chatroom is destroyed","Комната уничтожена"}.
{"Chatroom is started","Комната запущена"}.
{"Chatroom is stopped","Комната остановлена"}.
{"Chatrooms","Комнаты"}.
{"Choose a username and password to register with this server","Выберите имя пользователя и пароль для регистрации на этом сервере"}.
{"Choose storage type of tables","Выберите тип хранения таблиц"}.
{"Choose whether to approve this entity's subscription.","Решите: предоставить ли подписку этому объекту."}.
{"City","Город"}.
{"Client acknowledged more stanzas than sent by server","Клиент подтвердил больше сообщений чем было отправлено сервером"}.
{"Commands","Команды"}.
{"Conference room does not exist","Конференция не существует"}.
{"Configuration","Конфигурация"}.
{"Connected Resources:","Подключённые ресурсы:"}.
{"Country","Страна"}.
{"CPU Time:","Процессорное время:"}.
{"Database failure","Ошибка базы данных"}.
{"Database Tables at ~p","Таблицы базы данных на ~p"}.
{"Database Tables Configuration at ","Конфигурация таблиц базы данных на "}.
{"Database","База данных"}.
{"December","декабря"}.
{"Default users as participants","Сделать пользователей участниками по умолчанию"}.
{"Delete content","Удалить содержимое"}.
{"Delete message of the day on all hosts","Удалить сообщение дня со всех виртуальных серверов"}.
{"Delete message of the day","Удалить сообщение дня"}.
{"Delete Selected","Удалить выделенные"}.
{"Delete table","Удалить таблицу"}.
{"Delete User","Удалить пользователя"}.
{"Description:","Описание:"}.
{"Disc only copy","только диск"}.
{"Displayed Groups:","Видимые группы:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Не говорите никому свой пароль, даже администраторам сервера."}.
{"Dump Backup to Text File at ","Копирование в текстовый файл на "}.
{"Dump to Text File","Копирование в текстовый файл"}.
{"Duplicated groups are not allowed by RFC6121","Группы с одинаковыми названиями запрещены стандартом RFC6121"}.
{"Edit Properties","Изменить параметры"}.
{"Either approve or decline the voice request.","Подтвердите или отклоните право голоса."}.
{"ejabberd MUC module","ejabberd MUC модуль"}.
{"ejabberd Multicast service","ejabberd Multicast сервис"}.
{"ejabberd Publish-Subscribe module","Модуль ejabberd Публикации-Подписки"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams модуль"}.
{"ejabberd vCard module","ejabberd vCard модуль"}.
{"ejabberd Web Admin","Web-интерфейс администрирования ejabberd"}.
{"ejabberd","ejabberd"}.
{"Elements","Элементы"}.
{"Email","Электронная почта"}.
{"Enable logging","Включить журналирование"}.
{"Enabling push without 'node' attribute is not supported","Включение push-режима без атрибута 'node' не поддерживается"}.
{"End User Session","Завершить сеанс пользователя"}.
{"Enter nickname you want to register","Введите псевдоним, который Вы хотели бы зарегистрировать"}.
{"Enter path to backup file","Введите путь к резервному файлу"}.
{"Enter path to jabberd14 spool dir","Введите путь к директории спула jabberd14"}.
{"Enter path to jabberd14 spool file","Введите путь к файлу из спула jabberd14"}.
{"Enter path to text file","Введите путь к текстовому файлу"}.
{"Enter the text you see","Введите увиденный текст"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Ошибка"}.
{"Export all tables as SQL queries to a file:","Экспортировать все таблицы в виде SQL запросов в файл:"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Экспорт данных всех пользователей сервера в файлы формата PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Экспорт пользовательских данных домена в файлы формата PIEFXIS (XEP-0227):"}.
{"External component failure","Ошибка внешнего сервиса"}.
{"External component timeout","Таймаут внешнего сервиса"}.
{"Failed to activate bytestream","Ошибка при активировании потока данных"}.
{"Failed to extract JID from your voice request approval","Ошибка обработки JID из вашего запроса на право голоса"}.
{"Failed to map delegated namespace to external component","Не получилось найти внешний сервис, делегирующий это пространство имён"}.
{"Failed to parse HTTP response","Ошибка разбора HTTP ответа"}.
{"Family Name","Фамилия"}.
{"February","февраля"}.
{"File larger than ~w bytes","Файл больше ~w байт"}.
{"Fill in the form to search for any matching Jabber User","Заполните форму для поиска пользователя Jabber"}.
{"Friday","Пятница"}.
{"From","От кого"}.
{"Full Name","Полное имя"}.
{"Get Number of Online Users","Получить количество подключённых пользователей"}.
{"Get Number of Registered Users","Получить количество зарегистрированных пользователей"}.
{"Get Pending","Получить отложенные"}.
{"Get User Last Login Time","Получить время последнего подключения пользователя"}.
{"Get User Password","Получить пароль пользователя"}.
{"Get User Statistics","Получить статистику по пользователю"}.
{"Given Name","Имя"}.
{"Group ","Группа "}.
{"Groups","Группы"}.
{"has been banned","запретили входить в комнату"}.
{"has been kicked because of a system shutdown","выгнали из комнаты из-за останова системы"}.
{"has been kicked because of an affiliation change","выгнали из комнаты вследствие смены ранга"}.
{"has been kicked because the room has been changed to members-only","выгнали из комнаты потому что она стала только для членов"}.
{"has been kicked","выгнали из комнаты"}.
{"Host unknown","Неизвестное имя сервера"}.
{"Host","Хост"}.
{"HTTP File Upload","Передача файлов по HTTP"}.
{"Idle connection","Неиспользуемое соединение"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Если вы не видите изображение капчи, перейдите по ссылке."}.
{"Import Directory","Импорт из директории"}.
{"Import File","Импорт из файла"}.
{"Import user data from jabberd14 spool file:","Импорт пользовательских данных из буферного файла jabberd14:"}.
{"Import User from File at ","Импорт пользователя из файла на "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Импорт пользовательских данных из файла формата PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Импорт пользовательских данных из буферной директории jabberd14:"}.
{"Import Users from Dir at ","Импорт пользователей из директории на "}.
{"Import Users From jabberd14 Spool Files","Импорт пользователей из спула jabberd14"}.
{"Improper domain part of 'from' attribute","Неправильная доменная часть атрибута 'from'"}.
{"Improper message type","Неправильный тип сообщения"}.
{"Incoming s2s Connections:","Входящие s2s соединения:"}.
{"Incorrect CAPTCHA submit","Неверный ввод капчи"}.
{"Incorrect data form","Некорректная форма данных"}.
{"Incorrect password","Неправильный пароль"}.
{"Incorrect value of 'action' attribute","Некорректное значение атрибута 'action'"}.
{"Incorrect value of 'action' in data form","Некорректное значение 'action' в форме данных"}.
{"Incorrect value of 'path' in data form","Некорректное значение 'path' в форме данных"}.
{"Insufficient privilege","Недостаточно прав"}.
{"Internal server error","Внутренняя ошибка сервера"}.
{"Invalid 'from' attribute in forwarded message","Некорректный атрибут 'from' в пересланном сообщении"}.
{"Invalid node name","Недопустимое имя узла"}.
{"Invalid 'previd' value","Недопустимое значение 'previd'"}.
{"Invitations are not allowed in this conference","Рассылка приглашений отключена в этой конференции"}.
{"IP addresses","IP адреса"}.
{"is now known as","изменил(а) имя на"}.
{"It is not allowed to send private messages of type \"groupchat\"","Нельзя посылать частные сообщения типа \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Не разрешается посылать частные сообщения прямо в конференцию"}.
{"It is not allowed to send private messages","Запрещено посылать приватные сообщения"}.
{"Jabber Account Registration","Регистрация Jabber-аккаунта"}.
{"Jabber ID","Jabber ID"}.
{"January","января"}.
{"joins the room","вошёл(а) в комнату"}.
{"July","июля"}.
{"June","июня"}.
{"Last Activity","Последнее подключение"}.
{"Last login","Время последнего подключения"}.
{"Last month","За последний месяц"}.
{"Last year","За последний год"}.
{"leaves the room","вышел(а) из комнаты"}.
{"List of rooms","Список комнат"}.
{"Low level update script","Низкоуровневый сценарий обновления"}.
{"Make participants list public","Сделать список участников видимым всем"}.
{"Make room CAPTCHA protected","Сделать комнату защищённой капчей"}.
{"Make room members-only","Комната только для зарегистрированных участников"}.
{"Make room moderated","Сделать комнату модерируемой"}.
{"Make room password protected","Сделать комнату защищённой паролем"}.
{"Make room persistent","Сделать комнату постоянной"}.
{"Make room public searchable","Сделать комнату видимой всем"}.
{"Malformed username","Недопустимое имя пользователя"}.
{"MAM preference modification denied by service policy","Изменение настроек архива сообщений запрещено политикой службы"}.
{"March","марта"}.
{"Maximum Number of Occupants","Максимальное количество участников"}.
{"May","мая"}.
{"Membership is required to enter this room","В эту конференцию могут входить только её члены"}.
{"Members:","Члены:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Запомните пароль или запишите его на бумаге, которую сохраните в безопасном месте. В Jabber'е нет автоматизированного средства восстановления пароля в том случае, если Вы его забудете."}.
{"Memory","Память"}.
{"Message body","Тело сообщения"}.
{"Message not found in forwarded payload","Сообщение не найдено в пересылаемом вложении"}.
{"Messages from strangers are rejected","Сообщения от незнакомцев запрещены"}.
{"Middle Name","Отчество"}.
{"Moderator privileges required","Требуются права модератора"}.
{"Modified modules","Изменённые модули"}.
{"Module failed to handle the query","Ошибка модуля при обработке запроса"}.
{"Monday","Понедельник"}.
{"Multicast","Мультикаст"}.
{"Multiple <item/> elements are not allowed by RFC6121","Множественные элементы <item/> запрещены стандартом RFC6121"}.
{"Multi-User Chat","Конференция"}.
{"Name","Название"}.
{"Name:","Название:"}.
{"Neither 'jid' nor 'nick' attribute found","Не найден атрибут 'jid' или 'nick'"}.
{"Neither 'role' nor 'affiliation' attribute found","Не найден атрибут 'role' или 'affiliation'"}.
{"Never","Никогда"}.
{"New Password:","Новый пароль:"}.
{"Nickname can't be empty","Псевдоним не может быть пустым значением"}.
{"Nickname Registration at ","Регистрация псевдонима на "}.
{"Nickname","Псевдоним"}.
{"No address elements found","Не найден элемент <address/>"}.
{"No addresses element found","Не найден элемент <addresses/>"}.
{"No 'affiliation' attribute found","Не найден атрибут 'affiliation'"}.
{"No available resource found","Нет доступных ресурсов"}.
{"No body provided for announce message","Тело объявления не должно быть пустым"}.
{"No child elements found","Нет дочерних элементов"}.
{"No data form found","Форма данных не найдена"}.
{"No Data","Нет данных"}.
{"No features available","Свойства недоступны"}.
{"No <forwarded/> element found","Не найден элемент <forwarded/>"}.
{"No hook has processed this command","Ни один из хуков не выполнил эту команду"}.
{"No info about last activity found","Не найдено информации о последней активности"}.
{"No 'item' element found","Элемент 'item' не найден"}.
{"No items found in this query","Не найдены элементы в этом запросе"}.
{"No limit","Не ограничено"}.
{"No module is handling this query","Нет модуля который бы обработал этот запрос"}.
{"No node specified","Узел не указан"}.
{"No 'password' found in data form","Не найден 'password' в форме данных"}.
{"No 'password' found in this query","Не найден 'password' в этом запросе"}.
{"No 'path' found in data form","Не найден 'path' в форме данных"}.
{"No pending subscriptions found","Не найдено ожидающих решения подписок"}.
{"No privacy list with this name found","Списка приватности с таким именем не найдено"}.
{"No private data found in this query","Приватные данные не найдены в этом запросе"}.
{"No running node found","Нет работающих узлов"}.
{"No services available","Нет доступных сервисов"}.
{"No statistics found for this item","Не найдено статистики для этого элемента"}.
{"No 'to' attribute found in the invitation","Не найден атрибут 'to' в этом приглашении"}.
{"Node already exists","Узел уже существует"}.
{"Node index not found","Индекс узла не найден"}.
{"Node not found","Узел не найден"}.
{"Node ~p","Узел ~p"}.
{"Nodeprep has failed","Ошибка применения профиля Nodeprep"}.
{"Nodes","Узлы"}.
{"None","Нет"}.
{"Not allowed","Недопустимо"}.
{"Not Found","Не Найдено"}.
{"Not subscribed","Нет подписки"}.
{"November","ноября"}.
{"Number of online users","Количество подключённых пользователей"}.
{"Number of registered users","Количество зарегистрированных пользователей"}.
{"October","октября"}.
{"Offline Messages","Офлайновые сообщения"}.
{"Offline Messages:","Офлайновые сообщения:"}.
{"OK","Продолжить"}.
{"Old Password:","Старый пароль:"}.
{"Online Users","Подключённые пользователи"}.
{"Online Users:","Подключённые пользователи:"}.
{"Online","Подключён"}.
{"Only <enable/> or <disable/> tags are allowed","Допустимы только тэги <enable/> или <disable/>"}.
{"Only <list/> element is allowed in this query","Только элемент <list/> допустим в этом запросе"}.
{"Only members may query archives of this room","Только члены могут запрашивать архивы этой комнаты"}.
{"Only moderators and participants are allowed to change the subject in this room","Только модераторы и участники могут изменять тему в этой комнате"}.
{"Only moderators are allowed to change the subject in this room","Только модераторы могут изменять тему в этой комнате"}.
{"Only moderators can approve voice requests","Только модераторы могут утверждать запросы на право голоса"}.
{"Only occupants are allowed to send messages to the conference","Только присутствующим разрешается посылать сообщения в конференцию"}.
{"Only occupants are allowed to send queries to the conference","Только присутствующим разрешается посылать запросы в конференцию"}.
{"Only service administrators are allowed to send service messages","Только администратор службы может посылать служебные сообщения"}.
{"Organization Name","Название организации"}.
{"Organization Unit","Отдел организации"}.
{"Outgoing s2s Connections:","Исходящие s2s-серверы:"}.
{"Outgoing s2s Connections","Исходящие s2s-соединения"}.
{"Owner privileges required","Требуются права владельца"}.
{"Packet relay is denied by service policy","Пересылка пакетов запрещена политикой службы"}.
{"Packet","Пакет"}.
{"Password Verification","Проверка пароля"}.
{"Password Verification:","Проверка пароля:"}.
{"Password","Пароль"}.
{"Password:","Пароль:"}.
{"Path to Dir","Путь к директории"}.
{"Path to File","Путь к файлу"}.
{"Pending","Ожидание"}.
{"Period: ","Период"}.
{"Ping query is incorrect","Некорректный пинг-запрос"}.
{"Ping","Пинг"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Заметьте, что здесь производится резервное копирование только встроенной базы данных Mnesia. Если Вы также используете другое хранилище данных (например с помощью модуля ODBC), то его резервное копирование следует осуществлять отдельно."}.
{"Please, wait for a while before sending new voice request","Пожалуйста, подождите перед тем как подать новый запрос на право голоса"}.
{"Pong","Понг"}.
{"Possessing 'ask' attribute is not allowed by RFC6121","Включение атрибута 'ask' запрещено стандартом RFC6121"}.
{"Previous session not found","Предыдущая сессия не найдена"}.
{"Previous session PID has been killed","Предыдущая сессия была убита"}.
{"Previous session PID has exited","Процесс предыдущей сессии завершён"}.
{"Previous session PID is dead","Предыдущая сессия мертва"}.
{"Previous session timed out","Предыдущая сессия не отвечает"}.
{"private, ","приватная, "}.
{"Publish-Subscribe","Публикация-Подписка"}.
{"PubSub subscriber request","Запрос подписчика PubSub"}.
{"Push record not found","Push-запись не найдена"}.
{"Queries to the conference members are not allowed in this room","Запросы к пользователям в этой конференции запрещены"}.
{"Query to another users is forbidden","Запрос к другим пользователям запрещён"}.
{"RAM and disc copy","ОЗУ и диск"}.
{"RAM copy","ОЗУ"}.
{"Really delete message of the day?","Действительно удалить сообщение дня?"}.
{"Recipient is not in the conference room","Адресата нет в конференции"}.
{"Register a Jabber account","Зарегистрировать Jabber-аккаунт"}.
{"Registered Users","Зарегистрированные пользователи"}.
{"Registered Users:","Зарегистрированные пользователи:"}.
{"Register","Зарегистрировать"}.
{"Remote copy","не хранится локально"}.
{"Remove All Offline Messages","Удалить все офлайновые сообщения"}.
{"Remove User","Удалить пользователя"}.
{"Remove","Удалить"}.
{"Replaced by new connection","Заменено новым соединением"}.
{"Request has timed out","Истекло время ожидания запроса"}.
{"Resources","Ресурсы"}.
{"Restart Service","Перезапустить службу"}.
{"Restart","Перезапустить"}.
{"Restore Backup from File at ","Восстановление из резервной копии на "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Восстановить из бинарной резервной копии при следующем запуске (требует меньше памяти):"}.
{"Restore binary backup immediately:","Восстановить из бинарной резервной копии немедленно:"}.
{"Restore plain text backup immediately:","Восстановить из текстовой резервной копии немедленно:"}.
{"Restore","Восстановление из резервной копии"}.
{"Room Configuration","Конфигурация комнаты"}.
{"Room creation is denied by service policy","Cоздавать конференцию запрещено политикой службы"}.
{"Room description","Описание комнаты"}.
{"Room Occupants","Участники комнаты"}.
{"Room terminates","Комната остановлена"}.
{"Room title","Название комнаты"}.
{"Roster size","Размер списка контактов"}.
{"Roster","Ростер"}.
{"RPC Call Error","Ошибка вызова RPC"}.
{"Running Nodes","Работающие узлы"}.
{"Saturday","Суббота"}.
{"Script check","Проверка сценария"}.
{"Search Results for ","Результаты поиска в "}.
{"Search users in ","Поиск пользователей в "}.
{"Select All","Выбрать всё"}.
{"Send announcement to all online users on all hosts","Разослать объявление всем подключённым пользователям на всех виртуальных серверах"}.
{"Send announcement to all online users","Разослать объявление всем подключённым пользователям"}.
{"Send announcement to all users on all hosts","Разослать объявление всем пользователям на всех виртуальных серверах"}.
{"Send announcement to all users","Разослать объявление всем пользователям"}.
{"September","сентября"}.
{"Server:","Сервер:"}.
{"Session state copying timed out","Таймаут копирования состояния сессии"}.
{"Set message of the day and send to online users","Установить сообщение дня и разослать его подключённым пользователям"}.
{"Set message of the day on all hosts and send to online users","Установить сообщение дня на всех виртуальных серверах и разослать его подключённым пользователям"}.
{"Shared Roster Groups","Группы общих контактов"}.
{"Show Integral Table","Показать интегральную таблицу"}.
{"Show Ordinary Table","Показать обычную таблицу"}.
{"Shut Down Service","Остановить службу"}.
{"SOCKS5 Bytestreams","Передача файлов через SOCKS5"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Некоторые Jabber-клиенты могут сохранять пароль на Вашем компьютере. Используйте эту функцию только в том случае, если считаете это безопасным."}.
{"Statistics of ~p","статистика узла ~p"}.
{"Statistics","Статистика"}.
{"Stopped Nodes","Остановленные узлы"}.
{"Stop","Остановить"}.
{"Storage Type","Тип таблицы"}.
{"Store binary backup:","Сохранить бинарную резервную копию:"}.
{"Store plain text backup:","Сохранить текстовую резервную копию:"}.
{"Stream management is already enabled","Управление потоком уже активировано"}.
{"Stream management is not enabled","Управление потоком не активировано"}.
{"Subject","Тема"}.
{"Submitted","Отправлено"}.
{"Submit","Отправить"}.
{"Subscriptions are not allowed","Подписки недопустимы"}.
{"Subscription","Подписка"}.
{"Sunday","Воскресенье"}.
{"That nickname is already in use by another occupant","Этот псевдоним уже занят другим участником"}.
{"That nickname is registered by another person","Этот псевдоним зарегистрирован кем-то другим"}.
{"The account already exists","Учётная запись уже существует"}.
{"The account was not deleted","Аккаунт не был удален"}.
{"The CAPTCHA is valid.","Проверка капчи прошла успешно."}.
{"The CAPTCHA verification has failed","Проверка капчи не пройдена"}.
{"The captcha you entered is wrong","Неправильно введённое значение капчи"}.
{"The feature requested is not supported by the conference","Запрашиваемое свойство не поддерживается этой конференцией"}.
{"The password contains unacceptable characters","Пароль содержит недопустимые символы"}.
{"The password is too weak","Слишком слабый пароль"}.
{"the password is","пароль:"}.
{"The password of your Jabber account was successfully changed.","Пароль Вашего Jabber-аккаунта был успешно изменен."}.
{"The password was not changed","Пароль не был изменён"}.
{"The passwords are different","Пароли не совпадают"}.
{"The query is only allowed from local users","Запрос доступен только для локальных пользователей"}.
{"The query must not contain <item/> elements","Запрос не должен содержать элементов <item/>"}.
{"The stanza MUST contain only one <active/> element, one <default/> element, or one <list/> element","Строфа может содержать только один элемент <active/>, один элемент <default/> или один элемент <list/>"}.
{"The username is not valid","Недопустимое имя пользователя"}.
{"There was an error changing the password: ","Ошибка при смене пароля:"}.
{"There was an error creating the account: ","Ошибка при создании аккаунта:"}.
{"There was an error deleting the account: ","Ошибка при удалении аккаунта:"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Регистр не имеет значения: \"маша\" и \"МАША\" будет считаться одним и тем же именем."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Здесь Вы можете создать Jabber-аккаунт на этом Jabber-сервере. Ваш JID (Jabber-идентификатор) будет в виде: \"пользователь@сервер\". Пожалуйста, внимательно читайте инструкции для правильного заполнения полей."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Здесь Вы можете удалить Jabber-аккаунт с этого сервера."}.
{"This room is not anonymous","Эта комната не анонимная"}.
{"Thursday","Четверг"}.
{"Time delay","По истечение"}.
{"Timed out waiting for stream resumption","Истекло время ожидания возобновления потока"}.
{"Time","Время"}.
{"Token TTL","Токен TTL"}.
{"Too many active bytestreams","Слишком много активных потоков данных"}.
{"Too many CAPTCHA requests","Слишком много запросов капчи"}.
{"Too many child elements","Слишком много дочерних элементов"}.
{"Too many <item/> elements","Слишком много элементов <item/>"}.
{"Too many <list/> elements","Слишком много элементов <list/>"}.
{"Too many receiver fields were specified","Указано слишком много получателей"}.
{"Too many unacked stanzas","Слишком много неподтверждённых пакетов"}.
{"Too many users in this conference","Слишком много пользователей в этой конференции"}.
{"Total rooms","Все комнаты"}.
{"To","Кому"}.
{"Traffic rate limit is exceeded","Превышен лимит скорости посылки информации"}.
{"Transactions Aborted:","Транзакции отмененные:"}.
{"Transactions Committed:","Транзакции завершенные:"}.
{"Transactions Logged:","Транзакции запротоколированные:"}.
{"Transactions Restarted:","Транзакции перезапущенные:"}.
{"Tuesday","Вторник"}.
{"Unable to generate a CAPTCHA","Не получилось создать капчу"}.
{"Unable to register route on existing local domain","Нельзя регистрировать маршруты на существующие локальные домены"}.
{"Unauthorized","Не авторизован"}.
{"Unexpected action","Неожиданное действие"}.
{"Unexpected error condition: ~p","Неожиданная ошибка: ~p"}.
{"Unregister a Jabber account","Удалить Jabber-аккаунт"}.
{"Unregister","Удалить"}.
{"Unselect All","Снять всё выделение"}.
{"Unsupported <index/> element","Элемент <index/> не поддерживается"}.
{"Unsupported version","Неподдерживаемая версия"}.
{"Update message of the day (don't send)","Обновить сообщение дня (не рассылать)"}.
{"Update message of the day on all hosts (don't send)","Обновить сообщение дня на всех виртуальных серверах (не рассылать)"}.
{"Update plan","План обновления"}.
{"Update ~p","Обновление ~p"}.
{"Update script","Сценарий обновления"}.
{"Update","Обновить"}.
{"Uptime:","Время работы:"}.
{"User already exists","Пользователь уже существует"}.
{"User (jid)","Пользователь (XMPP адрес)"}.
{"User Management","Управление пользователями"}.
{"User removed","Пользователь удалён"}.
{"User session not found","Сессия пользователя не найдена"}.
{"User session terminated","Сессия пользователя завершена"}.
{"Username:","Имя пользователя:"}.
{"Users are not allowed to register accounts so quickly","Пользователи не могут регистрировать учётные записи так быстро"}.
{"Users Last Activity","Статистика последнего подключения пользователей"}.
{"Users","Пользователи"}.
{"User","Пользователь"}.
{"Validate","Утвердить"}.
{"Value 'get' of 'type' attribute is not allowed","Значение 'get' атрибута 'type' недопустимо"}.
{"Value 'set' of 'type' attribute is not allowed","Значение 'set' атрибута 'type' недопустимо"}.
{"vCard User Search","Поиск пользователей по vCard"}.
{"Virtual Hosting","Виртуальный хостинг"}.
{"Virtual Hosts","Виртуальные хосты"}.
{"Visitors are not allowed to change their nicknames in this room","Посетителям запрещено изменять свои псевдонимы в этой комнате"}.
{"Visitors are not allowed to send messages to all occupants","Посетителям не разрешается посылать сообщения всем присутствующим"}.
{"Voice requests are disabled in this conference","Запросы на право голоса отключены в этой конференции"}.
{"Voice request","Запрос на право голоса"}.
{"Wednesday","Среда"}.
{"Wrong parameters in the web formulary","Недопустимые параметры веб-формы"}.
{"Wrong xmlns","Неправильный xmlns"}.
{"You are being removed from the room because of a system shutdown","Вы покинули комнату из-за останова системы"}.
{"You are not joined to the channel","Вы не присоединены к каналу"}.
{"You can later change your password using a Jabber client.","Позже Вы можете изменить пароль через Jabber-клиент."}.
{"You have been banned from this room","Вам запрещено входить в эту конференцию"}.
{"You have joined too many conferences","Вы присоединены к слишком большому количеству конференций"}.
{"You must fill in field \"Nickname\" in the form","Вы должны заполнить поле \"Псевдоним\" в форме"}.
{"You need a client that supports x:data and CAPTCHA to register","Чтобы зарегистрироваться, требуется x:data-совместимый клиент"}.
{"You need a client that supports x:data to register the nickname","Чтобы зарегистрировать псевдоним, требуется x:data-совместимый клиент"}.
{"You need an x:data capable client to search","Чтобы воспользоваться поиском, требуется x:data-совместимый клиент"}.
{"Your active privacy list has denied the routing of this stanza.","Маршрутизация этой строфы запрещена вашим активным списком приватности."}.
{"Your contact offline message queue is full. The message has been discarded.","Очередь недоставленных сообщений Вашего адресата переполнена. Сообщение не было сохранено."}.
{"Your Jabber account was successfully created.","Ваш Jabber-аккаунт был успешно создан."}.
{"Your Jabber account was successfully deleted.","Ваш Jabber-аккаунт был успешно удален."}.
{"You're not allowed to create nodes","Вам не разрешается создавать узлы"}.
