%% -*- coding: latin-1 -*-
{"Access Configuration","Konfigurácia prístupu"}.
{"Access Control List Configuration","Konfigurácia zoznamu prístupových oprávnení (ACL)"}.
{"Access control lists","Zoznamy prístupových oprávnení (ACL)"}.
{"Access Control Lists","Zoznamy prístupových oprávnení (ACL)"}.
{"Access denied by service policy","Prístup bol zamietnutý nastavením služby"}.
{"Access rules","Prístupové pravidlá"}.
{"Access Rules","Prístupové pravidlá"}.
{"Action on user","Operácia aplikovaná na užívateľa"}.
{"Add Jabber ID","Pridať Jabber ID"}.
{"Add New","Pridať nový"}.
{"Add User","Pridať používateľa"}.
{"Administration","Administrácia"}.
{"Administration of ","Administrácia "}.
{"Administrator privileges required","Sú potrebné práva administrátora"}.
{"A friendly name for the node","Prístupný názov pre uzol"}.
{"All activity","Všetky aktivity"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Dovoliť tomuto Jabber ID odoberať PubSub uzol?"}.
{"Allow users to change the subject","Povoliť užívateľom meniť tému"}.
{"Allow users to query other users","Povoliť užívateľom dotazovať sa informácie o iných užívateľoch"}.
{"Allow users to send invites","Povoliť používateľom posielanie pozvánok"}.
{"Allow users to send private messages","Povoliť užívateľom odosielať súkromné správy"}.
{"Allow visitors to change nickname","Návštevníci môžu meniť prezývky"}.
{"Allow visitors to send private messages to","Povoliť užívateľom odosielať súkromné správy"}.
{"Allow visitors to send status text in presence updates","Návštevníci môžu posielať textové informácie v stavových správach"}.
{"Allow visitors to send voice requests","Povoliť používateľom posielanie pozvánok"}.
{"All Users","Všetci užívatelia"}.
{"Announcements","Oznámenia"}.
{"anyone","všetkým"}.
{"A password is required to enter this room","Pre vstup do miestnosti je potrebné heslo"}.
{"April","Apríl"}.
{"August","August"}.
{"Backup Management","Správa zálohovania"}.
{"Backup to File at ","Záloha do súboru na "}.
{"Backup","Zálohovať"}.
{"Bad format","Zlý formát"}.
{"Birthday","Dátum narodenia"}.
{"CAPTCHA web page","Webová stránka CAPTCHA"}.
{"Change Password","Zmeniť heslo"}.
{"Change User Password","Zmeniť heslo užívateľa"}.
{"Characters not allowed:","Nepovolené znaky:"}.
{"Chatroom configuration modified","Nastavenie diskusnej miestnosti bolo zmenené"}.
{"Chatroom is created","Diskusná miestnosť je vytvorená"}.
{"Chatroom is destroyed","Diskusná miestnosť je zrušená"}.
{"Chatroom is started","Diskusná miestnosť je obnovená"}.
{"Chatroom is stopped","Diskusná miestnosť je pozastavená"}.
{"Chatrooms","Diskusné miestnosti"}.
{"Choose a username and password to register with this server","Zvolte meno užívateľa a heslo pre registráciu na tomto servere"}.
{"Choose modules to stop","Vyberte moduly, ktoré majú byť zastavené"}.
{"Choose storage type of tables","Vyberte typ úložiska pre tabuľky"}.
{"Choose whether to approve this entity's subscription.","Zvolte, či chcete povoliť toto odoberanie"}.
{"City","Mesto"}.
{"Commands","Príkazy"}.
{"Conference room does not exist","Diskusná miestnosť neexistuje"}.
{"Configuration","Konfigurácia"}.
{"Configuration of room ~s","Konfigurácia miestnosti ~s"}.
{"Connected Resources:","Pripojené zdroje:"}.
{"Connections parameters","Parametre spojenia"}.
{"Country","Krajina"}.
{"CPU Time:","Čas procesoru"}.
{"Database","Databáza"}.
{"Database Tables Configuration at ","Konfigurácia databázových tabuliek "}.
{"December","December"}.
{"Default users as participants","Užívatelia sú implicitne členmi"}.
{"Delete message of the day on all hosts","Zmazať správu dňa na všetkých serveroch"}.
{"Delete message of the day","Zmazať správu dňa"}.
{"Delete Selected","Zmazať vybrané"}.
{"Delete User","Vymazať užívateľa"}.
{"Deliver event notifications","Doručiť oznamy o udalosti"}.
{"Deliver payloads with event notifications","Doručiť náklad s upozornením na udalosť"}.
{"Description:","Popis:"}.
{"Disc only copy","Len kópia disku"}.
{"Displayed Groups:","Zobrazené skupiny:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Nevyzrádzajte heslo nikomu, ani administrátorom tohoto Jabber servera."}.
{"Dump Backup to Text File at ","Uložiť zálohu do textového súboru na "}.
{"Dump to Text File","Uložiť do textového súboru"}.
{"Edit Properties","Editovať vlastnosti"}.
{"Either approve or decline the voice request.","Povolte alebo zamietnite žiadosť o Voice."}.
{"ejabberd IRC module","ejabberd IRC modul"}.
{"ejabberd MUC module","ejabberd MUC modul"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe modul"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams modul"}.
{"ejabberd vCard module","ejabberd vCard modul"}.
{"ejabberd Web Admin","ejabberd Web Admin"}.
{"Elements","Prvky"}.
{"Email","E-mail"}.
{"Enable logging","Zapnúť zaznamenávanie histórie"}.
{"Encoding for server ~b","Kódovanie pre server ~b"}.
{"End User Session","Ukončiť reláciu užívateľa"}.
{"Enter list of {Module, [Options]}","Vložte zoznam modulov {Modul, [Parametre]}"}.
{"Enter nickname you want to register","Zadajte prezývku, ktorú chcete registrovať"}.
{"Enter path to backup file","Zadajte cestu k súboru so zálohou"}.
{"Enter path to jabberd14 spool dir","Zadajte cestu k jabberd14 spool adresáru"}.
{"Enter path to jabberd14 spool file","Zadajte cestu k spool súboru jabberd14"}.
{"Enter path to text file","Zadajte cestu k textovému súboru"}.
{"Enter the text you see","Zadajte zobrazený text"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","Vložte meno používateľa a kódovanie, ktoré chcete používať pri pripojení na IRC servery. Kliknutím na tlačítko 'Ďalej' môžete zadať niektoré ďalšie hodnoty. Pomocou 'Ukončiť ' uložíte nastavenia."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","Vložte meno používateľa, kódovanie, porty a heslo ktoré chcete používať pri pripojení na IRC server"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Chyba"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","Príklad: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","Nepoužívať CAPTCHA pre nasledujúce Jabber ID"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Exportovať dáta všetkých uživateľov na serveri do súborov PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Exportovať dáta uživateľov na hostitelovi do súborov PIEFXIS (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","Nepodarilo sa nájsť JID v súhlase o Voice."}.
{"Family Name","Priezvisko"}.
{"February","Február"}.
{"Fill in fields to search for any matching Jabber User","Vyplnte políčka pre vyhľadávanie Jabber užívateľa"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Pre vyhľadanie Jabber používateľa vyplňte formulár (pridajte znak * na koniec, pre vyhľadanie podreťazca)"}.
{"Friday","Piatok"}.
{"From","Od"}.
{"From ~s","Od ~s"}.
{"Full Name","Celé meno: "}.
{"Get Number of Online Users","Zobraziť počet pripojených užívateľov"}.
{"Get Number of Registered Users","Zobraziť počet registrovaných užívateľov"}.
{"Get User Last Login Time","Zobraziť čas posledného prihlásenia"}.
{"Get User Password","Zobraziť heslo užívateľa"}.
{"Get User Statistics","Zobraziť štatistiku užívateľa"}.
{"Grant voice to this person?","Prideltiť Voice tejto osobe?"}.
{"Group ","Skupina "}.
{"Groups","Skupiny"}.
{"has been banned","bol(a) zablokovaný(á)"}.
{"has been kicked because of an affiliation change","bol vyhodený(á) kvôli zmene priradenia"}.
{"has been kicked because of a system shutdown","bol vyhodený(á) kvôli reštartu systému"}.
{"has been kicked because the room has been changed to members-only","bol vyhodený(á), pretože miestnosť bola vyhradená len pre členov"}.
{"has been kicked","bol(a) vyhodený(á) z miestnosti"}.
{" has set the subject to: ","zmenil(a) tému na: "}.
{"Host","Server"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Pokiaľ nevidíte obrázok CAPTCHA, navštívte webovú stránku."}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","Ak chcete zadať iné porty, heslá a kódovania pre IRC servery, vyplnte zoznam s hodnotami vo formáte '{\"irc server\",\"kódovanie\", \"port\", \"heslo\"}'. Predvolenéi hodnoty pre túto službu sú: kódovanie \"~s\", port ~p a žiadne heslo."}.
{"Import Directory","Import adresára"}.
{"Import File","Import súboru"}.
{"Import user data from jabberd14 spool file:","Importovať dáta užívateľov z jabberd14 spool súboru:"}.
{"Import User from File at ","Importovať užívateľa zo súboru na "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importovat dáta užívateľov zo súboru PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importovať dáta užívateľov z jabberd14 spool adresára:"}.
{"Import Users from Dir at ","Importovať užívateľov z adresára na "}.
{"Import Users From jabberd14 Spool Files","Importovať užívateľov z jabberd14 spool súborov"}.
{"Improper message type","Nesprávny typ správy"}.
{"Incorrect password","Nesprávne heslo"}.
{"Invalid affiliation: ~s","Neplatné priradenie: ~s"}.
{"Invalid role: ~s","Neplatná rola: ~s"}.
{"IP addresses","IP adresa"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","IRC kanál (bez počiatočnej #)"}.
{"IRC server","IRC server"}.
{"IRC settings","Nastavania IRC"}.
{"IRC Transport","IRC Transport"}.
{"IRC username","IRC prezývka"}.
{"IRC Username","IRC prezývka"}.
{"is now known as","sa premenoval(a) na"}.
{"It is not allowed to send private messages","Nieje povolené posielať súkromné správy"}.
{"It is not allowed to send private messages of type \"groupchat\"","Nie je dovolené odoslanie súkromnej správy typu \"Skupinová správa\" "}.
{"It is not allowed to send private messages to the conference","Nie je povolené odosielať súkromné správy do konferencie"}.
{"Jabber Account Registration","Registrácia jabber účtu"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s je neplatné"}.
{"January","Január"}.
{"Join IRC channel","Pripojit IRC kanál"}.
{"joins the room","vstúpil(a) do miestnosti"}.
{"Join the IRC channel here.","Propojiť IRC kanál sem."}.
{"Join the IRC channel in this Jabber ID: ~s","Pripojit IRC kanál k tomuto Jabber ID: ~s"}.
{"July","Júl"}.
{"June","Jún"}.
{"Last Activity","Posledná aktivita"}.
{"Last login","Posledné prihlásenie"}.
{"Last month","Posledný mesiac"}.
{"Last year","Posledný rok"}.
{"leaves the room","odišiel(a) z miestnosti"}.
{"Listened Ports at ","Otvorené porty na "}.
{"Listened Ports","Otvorené portov"}.
{"List of modules to start","Zoznam modulov, ktoré majú byť spustené"}.
{"Low level update script","Nízkoúrovňový aktualizačný skript"}.
{"Make participants list public","Nastaviť zoznam zúčastnených ako verejný"}.
{"Make room CAPTCHA protected","Chrániť miestnosť systémom CAPTCHA"}.
{"Make room members-only","Nastaviť miestnosť len pre členov"}.
{"Make room moderated","Nastaviť miestnosť ako moderovanú"}.
{"Make room password protected","Chrániť miestnosť heslom"}.
{"Make room persistent","Nastaviť miestnosť ako trvalú"}.
{"Make room public searchable","Nastaviť miestnosť ako verejne prehľadávateľnú"}.
{"March","Marec"}.
{"Maximum Number of Occupants","Počet účastníkov"}.
{"Max # of items to persist","Maximálny počet položiek, ktoré je možné natrvalo uložiť"}.
{"Max payload size in bytes","Maximálny náklad v bajtoch"}.
{"May","Máj"}.
{"Members:","Členovia:"}.
{"Membership is required to enter this room","Pre vstup do miestnosti je potrebné byť členom"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Zapamätajte si heslo alebo si ho zapíšte na papier. Jabber neposkytuje automatickú funkciu ako zistiť zabudnuté heslo. "}.
{"Memory","Pamäť"}.
{"Message body","Telo správy"}.
{"Middle Name","Prostredné meno: "}.
{"Minimum interval between voice requests (in seconds)","Minimum interval between voice requests (in seconds)"}.
{"Moderator privileges required","Sú potrebné práva moderátora"}.
{"moderators only","moderátorom"}.
{"Modified modules","Modifikované moduly"}.
{"Module","Modul"}.
{"Modules","Moduly"}.
{"Monday","Pondelok"}.
{"Name:","Meno:"}.
{"Name","Meno"}.
{"Never","Nikdy"}.
{"New Password:","Nové heslo:"}.
{"Nickname","Prezývka"}.
{"Nickname Registration at ","Registrácia prezývky na "}.
{"Nickname ~s does not exist in the room","Prezývka ~s v miestnosti neexistuje"}.
{"nobody","nikto"}.
{"No body provided for announce message","Správa neobsahuje text"}.
{"No Data","Žiadne dáta"}.
{"Node ID","ID uzlu"}.
{"Node not found","Uzol nenájdený"}.
{"Nodes","Uzly"}.
{"No limit","Bez limitu"}.
{"None","Nič"}.
{"No resource provided","Nebol poskytnutý žiadny zdroj"}.
{"Not Found","Nebol nájdený"}.
{"Notify subscribers when items are removed from the node","Upozorniť prihlásených používateľov na odstránenie položiek z uzlu"}.
{"Notify subscribers when the node configuration changes","Upozorniť prihlásených používateľov na zmenu nastavenia uzlu"}.
{"Notify subscribers when the node is deleted","Upozorniť prihlásených používateľov na zmazanie uzlu"}.
{"November","November"}.
{"Number of occupants","Počet zúčastnených"}.
{"Number of online users","Počet online užívateľov"}.
{"Number of registered users","Počet registrovaných užívateľov"}.
{"October","Október"}.
{"Offline Messages:","Offline správy"}.
{"Offline Messages","Offline správy"}.
{"OK","OK"}.
{"Old Password:","Staré heslo:"}.
{"Online","Online"}.
{"Online Users:","Online používatelia:"}.
{"Online Users","Online užívatelia"}.
{"Only deliver notifications to available users","Doručovať upozornenia len aktuálne prihláseným používateľom"}.
{"Only moderators and participants are allowed to change the subject in this room","Len moderátori a zúčastnený majú povolené meniť tému tejto miestnosti"}.
{"Only moderators are allowed to change the subject in this room","Len moderátori majú povolené meniť tému miestnosti"}.
{"Only moderators can approve voice requests","Len moderátori môžu schváliť žiadosť o Voice"}.
{"Only occupants are allowed to send messages to the conference","Len členovia majú povolené zasielať správy do konferencie"}.
{"Only occupants are allowed to send queries to the conference","Len členovia majú povolené dotazovať sa o konferencii"}.
{"Only service administrators are allowed to send service messages","Iba správcovia služby majú povolené odosielanie servisných správ"}.
{"Options","Nastavenia"}.
{"Organization Name","Meno organizácie: "}.
{"Organization Unit","Organizačná jednotka: "}.
{"Outgoing s2s Connections:","Odchádzajúce s2s spojenia:"}.
{"Outgoing s2s Connections","Odchádzajúce s2s spojenia"}.
{"Owner privileges required","Sú vyžadované práva vlastníka"}.
{"Packet","Paket"}.
{"Password ~b","Heslo ~b"}.
{"Password:","Heslo:"}.
{"Password","Heslo"}.
{"Password Verification:","Overenie hesla"}.
{"Password Verification","Overenie hesla"}.
{"Path to Dir","Cesta k adresáru"}.
{"Path to File","Cesta k súboru"}.
{"Pending","Čakajúce"}.
{"Period: ","Čas:"}.
{"Persist items to storage","Uložiť položky natrvalo do úložiska"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Prosím, berte na vedomie, že tieto nastavenia zázálohujú iba zabudovnú Mnesia databázu. Ak používate ODBC modul, musíte zálohovať vašu SQL databázu separátne."}.
{"Please, wait for a while before sending new voice request","Prosím počkate, predtým než pošlete novú žiadosť o Voice"}.
{"Pong","Pong"}.
{"Port ~b","Port ~b"}.
{"Port","Port"}.
{"Present real Jabber IDs to","Zobrazovať skutočné Jabber ID"}.
{"private, ","súkromná, "}.
{"Protocol","Protokol"}.
{"Publish-Subscribe","Publish-Subscribe"}.
{"PubSub subscriber request","Žiadosť odberateľa PubSub"}.
{"Purge all items when the relevant publisher goes offline","Odstrániť všetky relevantné položky, keď užívateľ prejde do módu offline"}.
{"Queries to the conference members are not allowed in this room","Dotazovať sa o členoch nie je v tejto miestnosti povolené"}.
{"RAM and disc copy","Kópia RAM a disku"}.
{"RAM copy","Kópia RAM"}.
{"Raw","Surové dáta"}.
{"Really delete message of the day?","Skutočne zmazať správu dňa?"}.
{"Recipient is not in the conference room","Príjemca sa nenachádza v konferenčnej miestnosti"}.
{"Register a Jabber account","Zaregistrovať Jabber účet"}.
{"Registered Users:","Registrovaní používatelia:"}.
{"Registered Users","Registrovaní používatelia"}.
{"Register","Zoznam kontaktov"}.
{"Registration in mod_irc for ","Registrácia do mod_irc na"}.
{"Remote copy","Vzdialená kópia"}.
{"Remove All Offline Messages","Odstrániť všetky offline správy"}.
{"Remove","Odstrániť"}.
{"Remove User","Odstrániť užívateľa"}.
{"Replaced by new connection","Nahradené novým spojením"}.
{"Resources","Zdroje"}.
{"Restart","Reštart"}.
{"Restart Service","Reštartovať službu"}.
{"Restore Backup from File at ","Obnoviť zálohu zo súboru na "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Obnoviť binárnu zálohu pri nasledujúcom reštarte ejabberd (vyžaduje menej pamäte)"}.
{"Restore binary backup immediately:","Okamžite obnoviť binárnu zálohu:"}.
{"Restore","Obnoviť"}.
{"Restore plain text backup immediately:","Okamžite obnoviť zálohu z textového súboru:"}.
{"Room Configuration","Nastavenia miestnosti"}.
{"Room creation is denied by service policy","Vytváranie miestnosti nie je povolené"}.
{"Room description","Popis miestnosti"}.
{"Room Occupants","Ľudí v miestnosti"}.
{"Room title","Názov miestnosti"}.
{"Roster groups allowed to subscribe","Skupiny kontaktov, ktoré môžu odoberať"}.
{"Roster of ","Zoznam kontaktov "}.
{"Roster size","Počet kontaktov v zozname"}.
{"Roster","Zoznam kontaktov"}.
{"RPC Call Error","Chyba RPC volania"}.
{"Running Nodes","Bežiace uzly"}.
{"~s access rule configuration","~s konfigurácia prístupového pravidla"}.
{"Saturday","Sobota"}.
{"Script check","Kontrola skriptu"}.
{"Search Results for ","Hľadať výsledky pre "}.
{"Search users in ","Hľadať užívateľov v "}.
{"Send announcement to all online users","Odoslať zoznam všetkým online používateľom"}.
{"Send announcement to all online users on all hosts","Odoslať oznam všetkým online používateľom na všetkých serveroch"}.
{"Send announcement to all users","Odoslať oznam všetkým používateľom"}.
{"Send announcement to all users on all hosts","Poslať oznámenie všetkým užívateľom na všetkých serveroch"}.
{"September","September"}.
{"Server ~b","Server ~b"}.
{"Set message of the day and send to online users","Nastaviť správu dňa a odoslať ju online používateľom"}.
{"Set message of the day on all hosts and send to online users","Nastaviť správu dňa na všetkých serveroch a poslať ju online užívateľom"}.
{"Shared Roster Groups","Skupiny pre zdieľaný zoznam kontaktov"}.
{"Show Integral Table","Zobraziť kompletnú tabuľku"}.
{"Show Ordinary Table","Zobraziť bežnú tabuľku"}.
{"Shut Down Service","Vypnúť službu"}.
{"~s invites you to the room ~s","~s Vás pozýva do miestnosti ~s"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Niektorí Jabber klenti môžu ukladať heslá v počítači. Používajte túto funkciu len ak veríte, že sú tam v bezpečí.  "}.
{"Specify the access model","Uveďte model prístupu"}.
{"Specify the event message type","Uveďte typ pre správu o udalosti"}.
{"Specify the publisher model","Špecifikovať model publikovania"}.
{"~s's Offline Messages Queue","~s Offline správy"}.
{"Start Modules at ","Spustiť moduly na "}.
{"Start Modules","Spustiť moduly"}.
{"Start","Štart"}.
{"Statistics of ~p","Štatistiky ~p"}.
{"Statistics","Štatistiky"}.
{"Stop Modules at ","Zastaviť moduly na "}.
{"Stop Modules","Zastaviť moduly"}.
{"Stopped Nodes","Zastavené uzly"}.
{"Stop","Zastaviť"}.
{"Storage Type","Typ úložiska"}.
{"Store binary backup:","Uložiť binárnu zálohu:"}.
{"Store plain text backup:","Uložiť zálohu do textového súboru:"}.
{"Subject","Predmet"}.
{"Submit","Odoslať"}.
{"Submitted","Odoslané"}.
{"Subscriber Address","Adresa odberateľa"}.
{"Subscription","Prihlásenie"}.
{"Sunday","Nedeľa"}.
{"That nickname is already in use by another occupant","Prezývka je už používaná iným členom"}.
{"That nickname is registered by another person","Prezývka je už zaregistrovaná inou osobou"}.
{"The CAPTCHA is valid.","Platná CAPTCHA."}.
{"The CAPTCHA verification has failed","Overenie pomocou CAPTCHA zlihalo"}.
{"The collections with which a node is affiliated","Kolekcie asociované s uzlom"}.
{"the password is","heslo je"}.
{"The password is too weak","heslo je"}.
{"The password of your Jabber account was successfully changed.","Heslo k Jabber účtu bolo úspešne zmenené."}.
{"There was an error changing the password: ","Pri zmene hesla nastala chyba: "}.
{"There was an error creating the account: ","Pri vytváraní účtu nastala chyba: "}.
{"There was an error deleting the account: ","Pri rušení účtu nastala chyba:"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Veľké a malé písmená sa nerozlišujú: macbeth je to isté ako MacBeth a Macbeth."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Táto stránka umožňuje refistrovať Jabber účet na tomto serveri. Vaše JID (Jabber IDentifikátor) bude vo formáte: užívateľ@server. Pozorne sledujte inštrukcie, aby ste údaje vypnili správne."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Na tejto stránke si môžete zrušiť Jabber účet registrovaný na tomto serveri."}.
{"Thursday","Štvrtok"}.
{"Time","Čas"}.
{"Time delay","Časový posun"}.
{"Too many CAPTCHA requests","Príliš veľa žiadostí o CAPTCHA"}.
{"To","Pre"}.
{"To ~s","Pre ~s"}.
{"Traffic rate limit is exceeded","Bol prekročený prenosový limit"}.
{"Transactions Aborted:","Transakcie zrušená"}.
{"Transactions Committed:","Transakcie potvrdená"}.
{"Transactions Logged:","Transakcie zaznamenaná"}.
{"Transactions Restarted:","Transakcie reštartovaná"}.
{"Tuesday","Utorok"}.
{"Unable to generate a CAPTCHA","Nepodarilo sa vygenerovat CAPTCHA"}.
{"Unauthorized","Neautorizovaný"}.
{"Unregister a Jabber account","Zrušiť Jabber účet"}.
{"Unregister","Zrušiť účet"}.
{"Update","Aktualizovať"}.
{"Update message of the day (don't send)","Aktualizovať správu dňa (neodosielať)"}.
{"Update message of the day on all hosts (don't send)","Upraviť správu dňa na všetkých serveroch"}.
{"Update plan","Aktualizovať plán"}.
{"Update script","Aktualizované skripty"}.
{"Uptime:","Uptime:"}.
{"Use of STARTTLS required","Je vyžadované použitie STARTTLS "}.
{"User JID","Používateľ "}.
{"User Management","Správa užívateľov"}.
{"Username:","IRC prezývka"}.
{"Users are not allowed to register accounts so quickly","Nieje dovolené vytvárať účty tak rýchlo po sebe"}.
{"Users Last Activity","Posledná aktivita používateľa"}.
{"Users","Používatelia"}.
{"User","Užívateľ"}.
{"Validate","Overiť"}.
{"vCard User Search","Hľadať užívateľov vo vCard"}.
{"Virtual Hosts","Virtuálne servery"}.
{"Visitors are not allowed to change their nicknames in this room","V tejto miestnosti nieje povolené meniť prezývky"}.
{"Visitors are not allowed to send messages to all occupants","Návštevníci nemajú povolené zasielať správy všetkým prihláseným do konferencie"}.
{"Voice requests are disabled in this conference","Žiadosti o Voice nie sú povolené v tejto konferencii"}.
{"Voice request","Žiadosť o Voice"}.
{"Wednesday","Streda"}.
{"When to send the last published item","Kedy odoslať posledne publikovanú položku"}.
{"Whether to allow subscriptions","Povoliť prihlasovanie"}.
{"You can later change your password using a Jabber client.","Neskôr si heslo môžete zmeniť pomocou Jabber klienta."}.
{"You have been banned from this room","Boli ste vylúčený z tejto miestnosti"}.
{"You must fill in field \"Nickname\" in the form","Musíte vyplniť políčko \"Prezývka\" vo formulári"}.
{"You need a client that supports x:data and CAPTCHA to register","Na registráciu prezývky potrebujete klienta podporujúceho z x:data"}.
{"You need a client that supports x:data to register the nickname","Na registráciu prezývky potrebujete klienta podporujúceho z x:data"}.
{"You need an x:data capable client to configure mod_irc settings","Pre konfiguráciu mod_irc potrebujete klienta podporujúceho x:data"}.
{"You need an x:data capable client to configure room","Na konfiguráciu miestnosti potrebujete klienta podporujúceho x:data"}.
{"You need an x:data capable client to search","Na vyhľadávanie potrebujete klienta podporujúceho x:data"}.
{"Your active privacy list has denied the routing of this stanza.","Aktívny list súkromia zbránil v smerovaní tejto stanzy."}.
{"Your contact offline message queue is full. The message has been discarded.","Fronta offline správ tohoto kontaktu je plná. Správa bola zahodená."}.
{"Your Jabber account was successfully created.","Jabber účet bol úspešne vytvorený."}.
{"Your Jabber account was successfully deleted.","Váš Jabber účet bol úspešne odstránený."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Správa určená pre ~s bola zablokovaná. Oblokovať ju môžete na ~s"}.
