%% -*- coding: latin-1 -*-
{"Access Configuration","Åtkomstkonfiguration"}.
{"Access Control List Configuration","Konfiguera ACL"}.
{"Access control lists","ACL"}.
{"Access Control Lists","ACL"}.
{"Access denied by service policy","Åtkomst nekad enligt lokal policy"}.
{"Access rules","Åtkomstregler"}.
{"Access Rules","Åtkomstregler"}.
{"Action on user","Handling mot användare"}.
{"Add Jabber ID","Lägg till Jabber ID"}.
{"Add New","Lägg till ny"}.
{"Add User","Lägg till användare"}.
{"Administration","Administration"}.
{"Administration of ","Administration av "}.
{"Administrator privileges required","Administrationsprivilegier krävs"}.
{"A friendly name for the node","Ett vänligt namn for noden"}.
{"All activity","All aktivitet"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Tillåt denna Jabber ID att prenumerera på denna pubsub node"}.
{"Allow users to change the subject","Tillåt användare att byta ämne"}.
{"Allow users to query other users","Tillåt användare att söka efter andra användare"}.
{"Allow users to send invites","Tillåt användare att skicka inbjudningar"}.
{"Allow users to send private messages","Tillåt användare att skicka privata meddelanden"}.
{"Allow visitors to change nickname","Tillåt gäster att kunna ändra smeknamn"}.
{"Allow visitors to send status text in presence updates","Tillåt gäster att skicka statustext som uppdatering"}.
{"All Users","Alla användare"}.
{"Announcements","Meddelanden"}.
{"anyone","Vemsomhelst"}.
{"April","April"}.
{"August","Augusti"}.
{"Backup Management","Hantera säkerhetskopior"}.
{"Backup","Säkerhetskopiera"}.
{"Backup to File at ","Säkerhetskopiera till fil på "}.
{"Bad format","Dåligt format"}.
{"Birthday","Födelsedag"}.
{"Change Password","Ändra lösenord"}.
{"Change User Password","Andra användarlösenord"}.
{"Chatroom configuration modified","Chattrum konfiguration modifierad"}.
{"Chatrooms","Chattrum"}.
{"Choose a username and password to register with this server","Välj ett användarnamn och lösenord för att registrera mot denna server"}.
{"Choose modules to stop","Välj vilka moduler som skall stoppas"}.
{"Choose storage type of tables","Välj lagringstyp för tabeller"}.
{"Choose whether to approve this entity's subscription.","Välj om du vill godkänna hela denna  prenumertion."}.
{"City","Stad"}.
{"Commands","Kommandon"}.
{"Conference room does not exist","Rummet finns inte"}.
{"Configuration","Konfiguration"}.
{"Configuration of room ~s","Konfiguration för ~s"}.
{"Connected Resources:","Anslutna resurser:"}.
{"Connections parameters","Uppkopplingsparametrar"}.
{"Country","Land"}.
{"CPU Time:","CPU tid"}.
{"Database","Databas"}.
{"Database Tables Configuration at ","Databastabellers konfiguration"}.
{"December","December"}.
{"Default users as participants","Gör om användare till deltagare"}.
{"Delete message of the day on all hosts","Ta bort dagens meddelande på alla värdar"}.
{"Delete message of the day","Ta bort dagens meddelande"}.
{"Delete Selected","Tabort valda"}.
{"Delete User","Ta bort användare"}.
{"Deliver event notifications","Skicka eventnotifikation"}.
{"Deliver payloads with event notifications","Skicka innehåll tillsammans med notifikationer"}.
{"Description:","Beskrivning:"}.
{"Disc only copy","Endast diskkopia"}.
{"Displayed Groups:","Visade grupper:"}.
{"Dump Backup to Text File at ","Dumpa säkerhetskopia till textfil på "}.
{"Dump to Text File","Dumpa till textfil"}.
{"Edit Properties","Redigera egenskaper"}.
{"ejabberd IRC module","ejabberd IRC-modul"}.
{"ejabberd MUC module","ejabberd MUC modul"}.
{"ejabberd Publish-Subscribe module","ejabberd publikprenumerations modul"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestrem modul"}.
{"ejabberd vCard module","ejabberd vCard-modul"}.
{"ejabberd Web Admin","ejabberd Web Admin"}.
{"Elements","Elements"}.
{"Email","Email"}.
{"Enable logging","Möjliggör login"}.
{"Encoding for server ~b","Encoding för server ~b"}.
{"End User Session","Avsluta användarsession"}.
{"Enter list of {Module, [Options]}","Skriv in en lista av {Module, [Options]}"}.
{"Enter nickname you want to register","Skriv in smeknamnet du vill registrera"}.
{"Enter path to backup file","Skriv in sökväg till fil för säkerhetskopia"}.
{"Enter path to jabberd14 spool dir","Skriv in sökväg till spoolkatalog från jabberd14"}.
{"Enter path to jabberd14 spool file","Skriv in sökväg till spoolfil från jabberd14"}.
{"Enter path to text file","Skriv in sökväg till textfil"}.
{"Enter the text you see","Skriv in sökväg till textfil"}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","Skriv in användarnamn och textkodning du vill använda för att ansluta till IRC-servrar"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Fel"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","Exempel: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}]."}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Exportera data av alla användare i servern till en PIEFXIS fil (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Exportera data av användare i en host till PIEFXIS fil (XEP-0227):"}.
{"Family Name","Efternamn"}.
{"February","Februari"}.
{"Fill in fields to search for any matching Jabber User","Fyll i fält för att söka efter jabberanvändare"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Fyll i formuläret för att söka efter en användare (lägg till * på slutet av fältet för att hitta alla som börjar så)"}.
{"Friday","Fredag"}.
{"From","Från"}.
{"From ~s","Från ~s"}.
{"Full Name","Fullständigt namn"}.
{"Get Number of Online Users","Hämta antal inloggade användare"}.
{"Get Number of Registered Users","Hämta antal registrerade användare"}.
{"Get User Last Login Time","Hämta användarens senast inloggade tid"}.
{"Get User Password","Hämta användarlösenord"}.
{"Get User Statistics","Hämta användarstatistik"}.
{"Group ","Grupp "}.
{"Groups","Grupper"}.
{"has been banned","har blivit bannad"}.
{"has been kicked because of an affiliation change","har blivit kickad p.g.a en ändring av tillhörighet"}.
{"has been kicked because of a system shutdown","har blivit kickad p.g.a en systemnerstängning"}.
{"has been kicked because the room has been changed to members-only","har blivit kickad p.g.a att rummet har ändrats till endast användare"}.
{"has been kicked","har blivit kickad"}.
{" has set the subject to: "," har satt ämnet till: "}.
{"Host","Server"}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","Om du vill specifiera textkodning för IRC-servrar, fyll i listan med värden i formatet '{\"irc server\", \"encoding\", port, \"password\"}'. Som standard används \"~s\", port ~p, no password."}.
{"Import Directory","Importera katalog"}.
{"Import File","Importera fil"}.
{"Import user data from jabberd14 spool file:","Importera användare från jabberd14 Spool filer"}.
{"Import User from File at ","Importera användare från fil på "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importera användardata från en PIEFXIS fil (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importera användare från jabberd14 Spool directory:"}.
{"Import Users from Dir at ","Importera användare från katalog på "}.
{"Import Users From jabberd14 Spool Files","Importera användare från jabberd14 Spool filer"}.
{"Improper message type","Felaktig medelandetyp"}.
{"Incorrect password","Fel lösenord"}.
{"Invalid affiliation: ~s","Ogiltlig rang: ~s"}.
{"Invalid role: ~s","Ogiltlig roll: ~s"}.
{"IP addresses","IP adresser"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","IRC kanal (skriv inte första #)"}.
{"IRC server","IRC-användarnamn"}.
{"IRC settings","IRC Inställningar"}.
{"IRC Transport","IRC transport"}.
{"IRC username","IRC-användarnamn"}.
{"IRC Username","IRC-användarnamn"}.
{"is now known as","är känd som"}.
{"It is not allowed to send private messages","Det ar inte tillåtet att skicka privata meddelanden"}.
{"It is not allowed to send private messages of type \"groupchat\"","Det är inte tillåtet att skicka privata medelanden med typen \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Det är inte tillåtet att skicka privata medelanden till den här konferensen"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Otillåtet Jabber ID ~s"}.
{"January","Januari"}.
{"Join IRC channel","Lägg till IRC kanal"}.
{"joins the room","joinar rummet"}.
{"Join the IRC channel here.","Lägg till IRC kanal här."}.
{"Join the IRC channel in this Jabber ID: ~s","Lägg till IRC kanal till detta Jabber ID: ~s"}.
{"July","Juli"}.
{"June","Juni"}.
{"Last Activity","Senast aktivitet"}.
{"Last login","Senaste login"}.
{"Last month","Senaste månaden"}.
{"Last year","Senaste året"}.
{"leaves the room","lämnar rummet"}.
{"Listened Ports at ","Lyssnande portar på "}.
{"Listened Ports","Lyssnarport"}.
{"List of modules to start","Lista av moduler som skall startas"}.
{"Low level update script","Uppdaterade laglevel skript"}.
{"Make participants list public","Gör deltagarlistan publik"}.
{"Make room members-only","Gör om rummet till endast medlemmar"}.
{"Make room moderated","Gör rummet modererat"}.
{"Make room password protected","Gör losenorden i rummet publika"}.
{"Make room persistent","Gör rummet permanent"}.
{"Make room public searchable","Gör rummet publikt sökbart"}.
{"March","Mars"}.
{"Maximum Number of Occupants","Maximalt antal av användare"}.
{"Max # of items to persist","Högsta antal dataposter som sparas"}.
{"Max payload size in bytes","Högsta innehållsstorlek i bytes"}.
{"May","Maj"}.
{"Membership is required to enter this room","Du måste vara medlem för att komma in i det här rummet"}.
{"Members:","Medlemmar:"}.
{"Memory","Minne"}.
{"Message body","Meddelande kropp"}.
{"Middle Name","Mellannamn"}.
{"Moderator privileges required","Moderatorprivilegier krävs"}.
{"moderators only","endast moderatorer"}.
{"Modified modules","Uppdaterade moduler"}.
{"Module","Modul"}.
{"Modules","Moduler"}.
{"Monday","Måndag"}.
{"Name:","Namn:"}.
{"Name","Namn"}.
{"Never","Aldrig"}.
{"Nickname Registration at ","Registrera smeknamn på "}.
{"Nickname ~s does not exist in the room","Smeknamnet ~s existerar inte i det här rummet"}.
{"Nickname","Smeknamn"}.
{"No body provided for announce message","Ingen kropp behövs för dessa meddelanden"}.
{"No Data","Ingen data"}.
{"Node ID","Node ID"}.
{"Node not found","Noden finns inte"}.
{"Nodes","Noder"}.
{"No limit","Ingen gräns"}.
{"None","Inga"}.
{"No resource provided","Ingen resurs angiven"}.
{"Not Found","Noden finns inte"}.
{"Notify subscribers when items are removed from the node","Meddela prenumeranter när dataposter tas bort från noden"}.
{"Notify subscribers when the node configuration changes","Meddela prenumeranter när nodens konfiguration ändras"}.
{"Notify subscribers when the node is deleted","Meddela prenumeranter när noden tas bort"}.
{"November","November"}.
{"Number of occupants","Antal besökare"}.
{"Number of online users","Antal inloggade användare"}.
{"Number of registered users","Antal registrerade användare"}.
{"October","Oktober"}.
{"Offline Messages:","Offline meddelanden:"}.
{"Offline Messages","Offline meddelanden"}.
{"OK","OK"}.
{"Online","Ansluten"}.
{"Online Users","Anslutna användare"}.
{"Online Users:","Inloggade användare"}.
{"Only deliver notifications to available users","Skicka notifikationer bara till uppkopplade användare"}.
{"Only moderators and participants are allowed to change the subject in this room","Endast moderatorer och deltagare har tillåtelse att ändra ämnet i det här rummet"}.
{"Only occupants are allowed to send messages to the conference","Utomstående får inte skicka medelanden till den här konferensen"}.
{"Only occupants are allowed to send queries to the conference","Utomstående får inte skicka iq-queries till den här konferensen"}.
{"Only service administrators are allowed to send service messages","Endast administratörer får skicka tjänstmeddelanden"}.
{"Options","Parametrar"}.
{"Organization Name","Organisationsnamn"}.
{"Organization Unit","Organisationsenhet"}.
{"Outgoing s2s Connections","Utgaende s2s anslutning"}.
{"Outgoing s2s Connections:","Utgående s2s anslutning"}.
{"Owner privileges required","Ägarprivilegier krävs"}.
{"Packet","Paket"}.
{"Password ~b","Lösenord ~b"}.
{"Password:","Lösenord:"}.
{"Password","Lösenord"}.
{"Password Verification","Lösenordsverifikation"}.
{"Path to Dir","Sökväg till katalog"}.
{"Path to File","Sökväg till fil"}.
{"Pending","Ännu inte godkända"}.
{"Period: ","Period: "}.
{"Persist items to storage","Spara dataposter permanent"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Kom ihåg att dessa inställningar endast tar backup pa builtin Mnesias databas. Om du använder ODBC modul så måste du ta backup på SQLs databas enskilt"}.
{"Pong","Pong"}.
{"Port ~b","Port ~b"}.
{"Port","Port"}.
{"Present real Jabber IDs to","Nuvarande äkta Jabber IDs till"}.
{"private, ","privat, "}.
{"Protocol","Protocol"}.
{"Publish-Subscribe","Publikprenumeration"}.
{"PubSub subscriber request","Pubsub prenumerationsforfrågan"}.
{"Queries to the conference members are not allowed in this room","Det är förbjudet att skicka iq-queries till konferensdeltagare"}.
{"RAM and disc copy","RAM- och diskkopia"}.
{"RAM copy","RAM-kopia"}.
{"Raw","Ra"}.
{"Really delete message of the day?","Verkligen ta bort dagens meddelanden?"}.
{"Recipient is not in the conference room","Mottagaren finns inte i rummet"}.
{"Registered Users:","Registrerade användare"}.
{"Registered Users","Registrerade användare"}.
{"Registration in mod_irc for ","mod_irc-registrering för "}.
{"Remote copy","Sparas inte lokalt"}.
{"Remove","Ta bort"}.
{"Remove User","Ta bort användare"}.
{"Replaced by new connection","Ersatt av ny anslutning"}.
{"Resources","Resurser"}.
{"Restart","Omstart"}.
{"Restart Service","Starta om servicen"}.
{"Restore","Återställ"}.
{"Restore Backup from File at ","Återställ säkerhetskopia från fil på "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","återställ den binära backupen efter nästa ejabberd omstart"}.
{"Restore binary backup immediately:","återställ den binära backupen omedelbart"}.
{"Restore plain text backup immediately:","återställ textbackup omedelbart"}.
{"Room Configuration","Rumkonfiguration"}.
{"Room creation is denied by service policy","Skapandet av rum är förbjudet enligt lokal policy"}.
{"Room Occupants","Antal besökare"}.
{"Room title","Rumstitel"}.
{"Roster groups allowed to subscribe","Rostergrupper tillåts att prenumerera"}.
{"Roster","Kontaktlista"}.
{"Roster of ","Kontaktlista för "}.
{"Roster size","Roster storlek"}.
{"RPC Call Error","RPC Uppringningserror"}.
{"Running Nodes","Körande noder"}.
{"~s access rule configuration","Åtkomstregelkonfiguration för ~s"}.
{"Saturday","Lördag"}.
{"Script check","Skript kollat"}.
{"Search Results for ","Sökresultat för"}.
{"Search users in ","Sök efter användare på "}.
{"Send announcement to all online users on all hosts","Sänd meddelanden till alla inloggade användare på alla värdar"}.
{"Send announcement to all online users","Sänd meddelanden till alla inloggade användare"}.
{"Send announcement to all users on all hosts","Sänd meddelanden till alla  användare på alla värdar"}.
{"Send announcement to all users","Sänd meddelanden till alla användare"}.
{"September","September"}.
{"Server ~b","Server ~b"}.
{"Set message of the day and send to online users","Sätt dagens status meddelande och skicka till alla användare"}.
{"Set message of the day on all hosts and send to online users","Sätt dagens status meddelande pa alla värdar och skicka till alla användare"}.
{"Shared Roster Groups","Delade Rostergrupper"}.
{"Show Integral Table","Visa kumulativ tabell"}.
{"Show Ordinary Table","Visa normal tabell"}.
{"Shut Down Service","Stäng ner servicen"}.
{"~s invites you to the room ~s","~s bjöd in dig till rummet ~s"}.
{"Specify the access model","Specificera accessmodellen"}.
{"Specify the publisher model","Ange publiceringsmodell"}.
{"~s's Offline Messages Queue","~s's offline meddelandekö"}.
{"Start Modules at ","Starta moduler på "}.
{"Start Modules","Starta moduler"}.
{"Start","Starta"}.
{"Statistics of ~p","Statistik på ~p"}.
{"Statistics","Statistik"}.
{"Stop Modules at ","Stoppa moduler på "}.
{"Stop Modules","Stanna moduler"}.
{"Stopped Nodes","Stannade noder"}.
{"Stop","Stoppa"}.
{"Storage Type","Lagringstyp"}.
{"Store binary backup:","Lagra den binära backupen"}.
{"Store plain text backup:","Lagra textbackup"}.
{"Subject","Ämne"}.
{"Submit","Skicka"}.
{"Submitted","Skicka in"}.
{"Subscriber Address","Prenumerationsadress"}.
{"Subscription","Prenumeration"}.
{"Sunday","Söndag"}.
{"That nickname is registered by another person","Smeknamnet är reserverat"}.
{"The CAPTCHA is valid.","Din CAPTCHA är godkänd."}.
{"the password is","Lösenordet är"}.
{"Thursday","Torsdag"}.
{"Time delay","Tidsförsening"}.
{"Time","Tid"}.
{"To ~s","Till ~s"}.
{"To","Till"}.
{"Traffic rate limit is exceeded","Trafikgränsen har överstigits"}.
{"Transactions Aborted:","Transaktioner borttagna"}.
{"Transactions Committed:","Transaktioner kommittade"}.
{"Transactions Logged:","Transaktioner loggade "}.
{"Transactions Restarted:","Transaktioner omstartade"}.
{"Tuesday","Tisdag"}.
{"Unauthorized","Ej auktoriserad"}.
{"Update message of the day (don't send)","Uppdatera dagens status meddelande (skicka inte)"}.
{"Update message of the day on all hosts (don't send)","Uppdatera dagens status meddelande på alla värdar (skicka inte)"}.
{"Update plan","Uppdateringsplan"}.
{"Update script","Uppdatera skript"}.
{"Update","Uppdatera"}.
{"Uptime:","Tid upp"}.
{"Use of STARTTLS required","Du måste använda STARTTLS"}.
{"User","Användarnamn"}.
{"User Management","Användarmanagement"}.
{"Users","Användare"}.
{"Users are not allowed to register accounts so quickly","Det är inte tillåtet för användare att skapa konton så fort"}.
{"Users Last Activity","Användarens senaste aktivitet"}.
{"Validate","Validera"}.
{"vCard User Search","vCard användare sök"}.
{"Virtual Hosts","Virtuella servrar"}.
{"Visitors are not allowed to change their nicknames in this room","Det är inte tillåtet for gäster att ändra sina smeknamn i detta rummet"}.
{"Visitors are not allowed to send messages to all occupants","Besökare får inte skicka medelande till alla"}.
{"Wednesday","Onsdag"}.
{"When to send the last published item","När att skicka senast publicerade ämne"}.
{"Whether to allow subscriptions","Tillåta prenumerationer?"}.
{"You have been banned from this room","Du har blivit bannlyst från det här rummet"}.
{"You must fill in field \"Nickname\" in the form","Du måste fylla i fält \"smeknamn\" i formen"}.
{"You need an x:data capable client to configure mod_irc settings","Du behöer en klient som stöjer x:data för att konfigurera mod_irc"}.
{"You need an x:data capable client to configure room","Du behöver en klient som stödjer x:data för att konfiguera detta rum"}.
{"You need an x:data capable client to search","Du behöver en klient som stödjer x:data, för att kunna söka"}.
{"Your contact offline message queue is full. The message has been discarded.","Din kontaktkö for offlinekontakter ar full"}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Dina meddelanden till ~s är blockerade. För att avblockera dem, gå till ~s"}.
