%% -*- coding: utf-8 -*-
{" has set the subject to: "," har satt ämnet till: "}.
{"Access denied by service policy","Åtkomst nekad enligt lokal policy"}.
{"Action on user","Handling mot användare"}.
{"Add Jabber ID","Lägg till Jabber ID"}.
{"Add New","Lägg till ny"}.
{"Add User","Lägg till användare"}.
{"Administration of ","Administration av "}.
{"Administration","Administration"}.
{"Administrator privileges required","Administrationsprivilegier krävs"}.
{"All activity","All aktivitet"}.
{"All Users","Alla användare"}.
{"Allow users to change the subject","Tillåt användare att byta ämne"}.
{"Allow users to query other users","Tillåt användare att söka efter andra användare"}.
{"Allow users to send invites","Tillåt användare att skicka inbjudningar"}.
{"Allow users to send private messages","Tillåt användare att skicka privata meddelanden"}.
{"Allow visitors to change nickname","Tillåt gäster att kunna ändra smeknamn"}.
{"Allow visitors to send status text in presence updates","Tillåt gäster att skicka statustext som uppdatering"}.
{"Announcements","Meddelanden"}.
{"April","April"}.
{"August","Augusti"}.
{"Backup Management","Hantera säkerhetskopior"}.
{"Backup to File at ","Säkerhetskopiera till fil på "}.
{"Backup","Säkerhetskopiera"}.
{"Bad format","Dåligt format"}.
{"Birthday","Födelsedag"}.
{"Change Password","Ändra lösenord"}.
{"Change User Password","Andra användarlösenord"}.
{"Chatroom configuration modified","Chattrum konfiguration modifierad"}.
{"Chatrooms","Chattrum"}.
{"Choose a username and password to register with this server","Välj ett användarnamn och lösenord för att registrera mot denna server"}.
{"Choose storage type of tables","Välj lagringstyp för tabeller"}.
{"Choose whether to approve this entity's subscription.","Välj om du vill godkänna hela denna  prenumertion."}.
{"City","Stad"}.
{"Commands","Kommandon"}.
{"Conference room does not exist","Rummet finns inte"}.
{"Configuration","Konfiguration"}.
{"Connected Resources:","Anslutna resurser:"}.
{"Country","Land"}.
{"CPU Time:","CPU tid"}.
{"Database Tables Configuration at ","Databastabellers konfiguration"}.
{"Database","Databas"}.
{"December","December"}.
{"Default users as participants","Gör om användare till deltagare"}.
{"Delete message of the day on all hosts","Ta bort dagens meddelande på alla värdar"}.
{"Delete message of the day","Ta bort dagens meddelande"}.
{"Delete Selected","Tabort valda"}.
{"Delete User","Ta bort användare"}.
{"Description:","Beskrivning:"}.
{"Disc only copy","Endast diskkopia"}.
{"Displayed Groups:","Visade grupper:"}.
{"Dump Backup to Text File at ","Dumpa säkerhetskopia till textfil på "}.
{"Dump to Text File","Dumpa till textfil"}.
{"Edit Properties","Redigera egenskaper"}.
{"ejabberd MUC module","ejabberd MUC modul"}.
{"ejabberd Publish-Subscribe module","ejabberd publikprenumerations modul"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestrem modul"}.
{"ejabberd vCard module","ejabberd vCard-modul"}.
{"ejabberd Web Admin","ejabberd Web Admin"}.
{"Elements","Elements"}.
{"Email","Email"}.
{"Enable logging","Möjliggör login"}.
{"End User Session","Avsluta användarsession"}.
{"Enter nickname you want to register","Skriv in smeknamnet du vill registrera"}.
{"Enter path to backup file","Skriv in sökväg till fil för säkerhetskopia"}.
{"Enter path to jabberd14 spool dir","Skriv in sökväg till spoolkatalog från jabberd14"}.
{"Enter path to jabberd14 spool file","Skriv in sökväg till spoolfil från jabberd14"}.
{"Enter path to text file","Skriv in sökväg till textfil"}.
{"Enter the text you see","Skriv in sökväg till textfil"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Fel"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Exportera data av alla användare i servern till en PIEFXIS fil (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Exportera data av användare i en host till PIEFXIS fil (XEP-0227):"}.
{"Family Name","Efternamn"}.
{"February","Februari"}.
{"Friday","Fredag"}.
{"From","Från"}.
{"Full Name","Fullständigt namn"}.
{"Get Number of Online Users","Hämta antal inloggade användare"}.
{"Get Number of Registered Users","Hämta antal registrerade användare"}.
{"Get User Last Login Time","Hämta användarens senast inloggade tid"}.
{"Get User Password","Hämta användarlösenord"}.
{"Get User Statistics","Hämta användarstatistik"}.
{"Group ","Grupp "}.
{"Groups","Grupper"}.
{"has been banned","har blivit bannad"}.
{"has been kicked because of a system shutdown","har blivit kickad p.g.a en systemnerstängning"}.
{"has been kicked because of an affiliation change","har blivit kickad p.g.a en ändring av tillhörighet"}.
{"has been kicked because the room has been changed to members-only","har blivit kickad p.g.a att rummet har ändrats till endast användare"}.
{"has been kicked","har blivit kickad"}.
{"Host","Server"}.
{"Import Directory","Importera katalog"}.
{"Import File","Importera fil"}.
{"Import user data from jabberd14 spool file:","Importera användare från jabberd14 Spool filer"}.
{"Import User from File at ","Importera användare från fil på "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importera användardata från en PIEFXIS fil (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importera användare från jabberd14 Spool directory:"}.
{"Import Users from Dir at ","Importera användare från katalog på "}.
{"Import Users From jabberd14 Spool Files","Importera användare från jabberd14 Spool filer"}.
{"Improper message type","Felaktig medelandetyp"}.
{"Incorrect password","Fel lösenord"}.
{"IP addresses","IP adresser"}.
{"is now known as","är känd som"}.
{"It is not allowed to send private messages of type \"groupchat\"","Det är inte tillåtet att skicka privata medelanden med typen \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Det är inte tillåtet att skicka privata medelanden till den här konferensen"}.
{"It is not allowed to send private messages","Det ar inte tillåtet att skicka privata meddelanden"}.
{"Jabber ID","Jabber ID"}.
{"January","Januari"}.
{"joins the room","joinar rummet"}.
{"July","Juli"}.
{"June","Juni"}.
{"Last Activity","Senast aktivitet"}.
{"Last login","Senaste login"}.
{"Last month","Senaste månaden"}.
{"Last year","Senaste året"}.
{"leaves the room","lämnar rummet"}.
{"Low level update script","Uppdaterade laglevel skript"}.
{"Make participants list public","Gör deltagarlistan publik"}.
{"Make room members-only","Gör om rummet till endast medlemmar"}.
{"Make room moderated","Gör rummet modererat"}.
{"Make room password protected","Gör losenorden i rummet publika"}.
{"Make room persistent","Gör rummet permanent"}.
{"Make room public searchable","Gör rummet publikt sökbart"}.
{"March","Mars"}.
{"Maximum Number of Occupants","Maximalt antal av användare"}.
{"May","Maj"}.
{"Membership is required to enter this room","Du måste vara medlem för att komma in i det här rummet"}.
{"Members:","Medlemmar:"}.
{"Memory","Minne"}.
{"Message body","Meddelande kropp"}.
{"Middle Name","Mellannamn"}.
{"Moderator privileges required","Moderatorprivilegier krävs"}.
{"Modified modules","Uppdaterade moduler"}.
{"Monday","Måndag"}.
{"Name","Namn"}.
{"Name:","Namn:"}.
{"Never","Aldrig"}.
{"Nickname Registration at ","Registrera smeknamn på "}.
{"Nickname","Smeknamn"}.
{"No body provided for announce message","Ingen kropp behövs för dessa meddelanden"}.
{"No Data","Ingen data"}.
{"No limit","Ingen gräns"}.
{"Node not found","Noden finns inte"}.
{"Nodes","Noder"}.
{"None","Inga"}.
{"Not Found","Noden finns inte"}.
{"November","November"}.
{"Number of online users","Antal inloggade användare"}.
{"Number of registered users","Antal registrerade användare"}.
{"October","Oktober"}.
{"Offline Messages","Offline meddelanden"}.
{"Offline Messages:","Offline meddelanden:"}.
{"OK","OK"}.
{"Online Users","Anslutna användare"}.
{"Online Users:","Inloggade användare"}.
{"Online","Ansluten"}.
{"Only moderators and participants are allowed to change the subject in this room","Endast moderatorer och deltagare har tillåtelse att ändra ämnet i det här rummet"}.
{"Only occupants are allowed to send messages to the conference","Utomstående får inte skicka medelanden till den här konferensen"}.
{"Only occupants are allowed to send queries to the conference","Utomstående får inte skicka iq-queries till den här konferensen"}.
{"Only service administrators are allowed to send service messages","Endast administratörer får skicka tjänstmeddelanden"}.
{"Organization Name","Organisationsnamn"}.
{"Organization Unit","Organisationsenhet"}.
{"Outgoing s2s Connections","Utgaende s2s anslutning"}.
{"Outgoing s2s Connections:","Utgående s2s anslutning"}.
{"Owner privileges required","Ägarprivilegier krävs"}.
{"Packet","Paket"}.
{"Password Verification","Lösenordsverifikation"}.
{"Password","Lösenord"}.
{"Password:","Lösenord:"}.
{"Path to Dir","Sökväg till katalog"}.
{"Path to File","Sökväg till fil"}.
{"Pending","Ännu inte godkända"}.
{"Period: ","Period: "}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Kom ihåg att dessa inställningar endast tar backup pa builtin Mnesias databas. Om du använder ODBC modul så måste du ta backup på SQLs databas enskilt"}.
{"Pong","Pong"}.
{"private, ","privat, "}.
{"Publish-Subscribe","Publikprenumeration"}.
{"PubSub subscriber request","Pubsub prenumerationsforfrågan"}.
{"Queries to the conference members are not allowed in this room","Det är förbjudet att skicka iq-queries till konferensdeltagare"}.
{"RAM and disc copy","RAM- och diskkopia"}.
{"RAM copy","RAM-kopia"}.
{"Really delete message of the day?","Verkligen ta bort dagens meddelanden?"}.
{"Recipient is not in the conference room","Mottagaren finns inte i rummet"}.
{"Registered Users","Registrerade användare"}.
{"Registered Users:","Registrerade användare"}.
{"Remote copy","Sparas inte lokalt"}.
{"Remove User","Ta bort användare"}.
{"Remove","Ta bort"}.
{"Replaced by new connection","Ersatt av ny anslutning"}.
{"Resources","Resurser"}.
{"Restart Service","Starta om servicen"}.
{"Restart","Omstart"}.
{"Restore Backup from File at ","Återställ säkerhetskopia från fil på "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","återställ den binära backupen efter nästa ejabberd omstart"}.
{"Restore binary backup immediately:","återställ den binära backupen omedelbart"}.
{"Restore plain text backup immediately:","återställ textbackup omedelbart"}.
{"Restore","Återställ"}.
{"Room Configuration","Rumkonfiguration"}.
{"Room creation is denied by service policy","Skapandet av rum är förbjudet enligt lokal policy"}.
{"Room Occupants","Antal besökare"}.
{"Room title","Rumstitel"}.
{"Roster size","Roster storlek"}.
{"Roster","Kontaktlista"}.
{"RPC Call Error","RPC Uppringningserror"}.
{"Running Nodes","Körande noder"}.
{"Saturday","Lördag"}.
{"Script check","Skript kollat"}.
{"Search Results for ","Sökresultat för"}.
{"Search users in ","Sök efter användare på "}.
{"Send announcement to all online users on all hosts","Sänd meddelanden till alla inloggade användare på alla värdar"}.
{"Send announcement to all online users","Sänd meddelanden till alla inloggade användare"}.
{"Send announcement to all users on all hosts","Sänd meddelanden till alla  användare på alla värdar"}.
{"Send announcement to all users","Sänd meddelanden till alla användare"}.
{"September","September"}.
{"Set message of the day and send to online users","Sätt dagens status meddelande och skicka till alla användare"}.
{"Set message of the day on all hosts and send to online users","Sätt dagens status meddelande pa alla värdar och skicka till alla användare"}.
{"Shared Roster Groups","Delade Rostergrupper"}.
{"Show Integral Table","Visa kumulativ tabell"}.
{"Show Ordinary Table","Visa normal tabell"}.
{"Shut Down Service","Stäng ner servicen"}.
{"Statistics of ~p","Statistik på ~p"}.
{"Statistics","Statistik"}.
{"Stopped Nodes","Stannade noder"}.
{"Stop","Stoppa"}.
{"Storage Type","Lagringstyp"}.
{"Store binary backup:","Lagra den binära backupen"}.
{"Store plain text backup:","Lagra textbackup"}.
{"Subject","Ämne"}.
{"Submit","Skicka"}.
{"Submitted","Skicka in"}.
{"Subscription","Prenumeration"}.
{"Sunday","Söndag"}.
{"That nickname is registered by another person","Smeknamnet är reserverat"}.
{"The CAPTCHA is valid.","Din CAPTCHA är godkänd."}.
{"the password is","Lösenordet är"}.
{"This room is not anonymous","Detta rum är inte anonymt"}.
{"Thursday","Torsdag"}.
{"Time delay","Tidsförsening"}.
{"Time","Tid"}.
{"To","Till"}.
{"Traffic rate limit is exceeded","Trafikgränsen har överstigits"}.
{"Transactions Aborted:","Transaktioner borttagna"}.
{"Transactions Committed:","Transaktioner kommittade"}.
{"Transactions Logged:","Transaktioner loggade "}.
{"Transactions Restarted:","Transaktioner omstartade"}.
{"Tuesday","Tisdag"}.
{"Unauthorized","Ej auktoriserad"}.
{"Update message of the day (don't send)","Uppdatera dagens status meddelande (skicka inte)"}.
{"Update message of the day on all hosts (don't send)","Uppdatera dagens status meddelande på alla värdar (skicka inte)"}.
{"Update plan","Uppdateringsplan"}.
{"Update script","Uppdatera skript"}.
{"Update","Uppdatera"}.
{"Uptime:","Tid upp"}.
{"User Management","Användarmanagement"}.
{"User","Användarnamn"}.
{"Users are not allowed to register accounts so quickly","Det är inte tillåtet för användare att skapa konton så fort"}.
{"Users Last Activity","Användarens senaste aktivitet"}.
{"Users","Användare"}.
{"Validate","Validera"}.
{"vCard User Search","vCard användare sök"}.
{"Virtual Hosts","Virtuella servrar"}.
{"Visitors are not allowed to change their nicknames in this room","Det är inte tillåtet for gäster att ändra sina smeknamn i detta rummet"}.
{"Visitors are not allowed to send messages to all occupants","Besökare får inte skicka medelande till alla"}.
{"Wednesday","Onsdag"}.
{"You have been banned from this room","Du har blivit bannlyst från det här rummet"}.
{"You must fill in field \"Nickname\" in the form","Du måste fylla i fält \"smeknamn\" i formen"}.
{"You need an x:data capable client to search","Du behöver en klient som stödjer x:data, för att kunna söka"}.
{"Your contact offline message queue is full. The message has been discarded.","Din kontaktkö for offlinekontakter ar full"}.
