%% -*- coding: latin-1 -*-
{"Access Configuration","การกำหนดค่าการเข้าถึง"}.
{"Access Control List Configuration","การกำหนดค่ารายการควบคุมการเข้าถึง"}.
{"Access control lists","รายการควบคุมการเข้าถึง"}.
{"Access Control Lists","รายการควบคุมการเข้าถึง"}.
{"Access denied by service policy","การเข้าถึงถูกปฏิเสธโดยนโยบายการบริการ"}.
{"Access rules","กฎการเข้าถึง"}.
{"Access Rules","กฎการเข้าถึง"}.
{"Action on user","การดำเนินการกับผู้ใช้"}.
{"Add Jabber ID","เพิ่ม Jabber ID"}.
{"Add New","เพิ่มผู้ใช้ใหม่"}.
{"Add User","เพิ่มผู้ใช้"}.
{"Administration","การดูแล"}.
{"Administration of ","การดูแล "}.
{"Administrator privileges required","ต้องมีสิทธิพิเศษของผู้ดูแลระบบ"}.
{"All activity","กิจกรรมทั้งหมด"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","อนุญาตให้ Jabber ID นี้เข้าร่วมเป็นสมาชิกของโหนด pubsub หรือไม่"}.
{"Allow users to query other users","อนุญาตให้ผู้ใช้ถามคำถามกับผู้ใช้คนอื่นๆ ได้"}.
{"Allow users to send invites","อนุญาตให้ผู้ใช้ส่งคำเชิญถึงกันได้"}.
{"Allow users to send private messages","อนุญาตให้ผู้ใช้ส่งข้อความส่วนตัว"}.
{"All Users","ผู้ใช้ทั้งหมด"}.
{"Announcements","ประกาศ"}.
{"anyone","ทุกคน"}.
{"April","เมษายน"}.
{"August","สิงหาคม"}.
{"Backup","การสำรองข้อมูล "}.
{"Backup Management","การจัดการข้อมูลสำรอง"}.
{"Backup to File at ","สำรองไฟล์ข้อมูลที่"}.
{"Bad format","รูปแบบที่ไม่ถูกต้อง"}.
{"Birthday","วันเกิด"}.
{"Change Password","เปลี่ยนรหัสผ่าน"}.
{"Change User Password","เปลี่ยนรหัสผ่านของผู้ใช้"}.
{"Chatroom configuration modified","มีการปรับเปลี่ยนการกำหนดค่าของห้องสนทนา"}.
{"Chatrooms","ห้องสนทนา"}.
{"Choose a username and password to register with this server","เลือกชื่อผู้ใช้และรหัสผ่านเพื่อลงทะเบียนกับเซิร์ฟเวอร์นี้"}.
{"Choose modules to stop","เลือกโมดูลเพื่อหยุดการทำงาน"}.
{"Choose storage type of tables","เลือกชนิดการจัดเก็บของตาราง"}.
{"Choose whether to approve this entity's subscription.","เลือกว่าจะอนุมัติการสมัครเข้าใช้งานของเอนทิตี้นี้หรือไม่"}.
{"City","เมือง"}.
{"Commands","คำสั่ง"}.
{"Conference room does not exist","ไม่มีห้องประชุม"}.
{"Configuration","การกำหนดค่า"}.
{"Connected Resources:","ทรัพยากรที่เชื่อมต่อ:"}.
{"Country","ประเทศ"}.
{"CPU Time:","เวลาการทำงานของ CPU:"}.
{"Database","ฐานข้อมูล"}.
{"Database Tables Configuration at ","การกำหนดค่าตารางฐานข้อมูลที่"}.
{"December","ธันวาคม"}.
{"Default users as participants","ผู้ใช้เริ่มต้นเป็นผู้เข้าร่วม"}.
{"Delete message of the day","ลบข้อความของวัน"}.
{"Delete message of the day on all hosts","ลบข้อความของวันบนโฮสต์ทั้งหมด"}.
{"Delete Selected","ลบข้อความที่เลือก"}.
{"Delete User","ลบผู้ใช้"}.
{"Deliver event notifications","ส่งการแจ้งเตือนเหตุการณ์"}.
{"Deliver payloads with event notifications","ส่งส่วนของข้อมูล (payload) พร้อมกับการแจ้งเตือนเหตุการณ์"}.
{"Description:","รายละเอียด:"}.
{"Disc only copy","คัดลอกเฉพาะดิสก์"}.
{"Displayed Groups:","กลุ่มที่แสดง:"}.
{"Dump Backup to Text File at ","ถ่ายโอนการสำรองข้อมูลไปยังไฟล์ข้อความที่"}.
{"Dump to Text File","ถ่ายโอนข้อมูลไปยังไฟล์ข้อความ"}.
{"Edit Properties","แก้ไขคุณสมบัติ"}.
{"ejabberd IRC module","ejabberd IRC module"}.
{"ejabberd MUC module","ejabberd MUC module"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe module"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams module"}.
{"ejabberd vCard module","ejabberd vCard module"}.
{"Email","อีเมล"}.
{"Enable logging","เปิดใช้งานการบันทึก"}.
{"End User Session","สิ้นสุดเซสชันของผู้ใช้"}.
{"Enter list of {Module, [Options]}","ป้อนรายการของ {โมดูล, [ตัวเลือก]}"}.
{"Enter nickname you want to register","ป้อนชื่อเล่นที่คุณต้องการลงทะเบียน"}.
{"Enter path to backup file","ป้อนพาธเพื่อสำรองไฟล์ข้อมูล"}.
{"Enter path to jabberd14 spool dir","ป้อนพาธไปยัง jabberd14 spool dir"}.
{"Enter path to jabberd14 spool file","ป้อนพาธไปยังไฟล์เก็บพักข้อมูล jabberd14"}.
{"Enter path to text file","ป้อนพาธของไฟล์ข้อความ"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Family Name","นามสกุล"}.
{"February","กุมภาพันธ์"}.
{"Fill in fields to search for any matching Jabber User","กรอกข้อมูลลงในฟิลด์เพื่อค้นหาผู้ใช้ Jabber ที่ตรงกัน"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","กรอกข้อมูลในแบบฟอร์มเพื่อค้นหาผู้ใช้ Jabber ที่ตรงกัน (ใส่เครื่องหมาย * ที่ท้ายสุดของฟิลด์เพื่อจับคู่กับสตริงย่อย)"}.
{"Friday","วันศุกร์"}.
{"From","จาก"}.
{"From ~s","จาก ~s"}.
{"Full Name","ชื่อเต็ม"}.
{"Get Number of Online Users","แสดงจำนวนผู้ใช้ออนไลน์"}.
{"Get Number of Registered Users","แสดงจำนวนผู้ใช้ที่ลงทะเบียน"}.
{"Get User Last Login Time","แสดงเวลาเข้าสู่ระบบครั้งล่าสุดของผู้ใช้"}.
{"Get User Password","ขอรับรหัสผ่านของผู้ใช้"}.
{"Get User Statistics","แสดงสถิติของผู้ใช้"}.
{"Group ","กลุ่ม"}.
{"Groups","กลุ่ม"}.
{"has been banned","ถูกสั่งห้าม"}.
{"has been kicked","ถูกไล่ออก"}.
{" has set the subject to: "," ตั้งหัวข้อว่า: "}.
{"Host","โฮสต์"}.
{"Import Directory","อิมพอร์ตไดเร็กทอรี"}.
{"Import File","อิมพอร์ตไฟล์"}.
{"Import User from File at ","อิมพอร์ตผู้ใช้จากไฟล์ที่"}.
{"Import Users from Dir at ","อิมพอร์ตผู้ใช้จาก Dir ที่"}.
{"Import Users From jabberd14 Spool Files","อิมพอร์ตผู้ใช้จากไฟล์เก็บพักข้อมูล jabberd14"}.
{"Improper message type","ประเภทข้อความไม่เหมาะสม"}.
{"Incorrect password","รหัสผ่านไม่ถูกต้อง"}.
{"Invalid affiliation: ~s","การเข้าร่วมที่ไม่ถูกต้อง: ~s"}.
{"Invalid role: ~s","บทบาทไม่ถูกต้อง: ~s"}.
{"IP addresses","ที่อยู่ IP"}.
{"IRC Transport","การส่ง IRC"}.
{"IRC Username","ชื่อผู้ใช้ IRC"}.
{"is now known as","ซึ่งรู้จักกันในชื่อ"}.
{"It is not allowed to send private messages of type \"groupchat\"","ไม่อนุญาตให้ส่งข้อความส่วนตัวไปยัง \"กลุ่มสนทนา\""}.
{"It is not allowed to send private messages to the conference","ไม่อนุญาตให้ส่งข้อความส่วนตัวไปยังห้องประชุม"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s ไม่ถูกต้อง"}.
{"January","มกราคม"}.
{"joins the room","เข้าห้องสนทนานี้"}.
{"July","กรกฎาคม"}.
{"June","มิถุนายน"}.
{"Last Activity","กิจกรรมล่าสุด"}.
{"Last login","การเข้าสู่ระบบครั้งล่าสุด"}.
{"Last month","เดือนที่แล้ว"}.
{"Last year","ปีที่แล้ว"}.
{"leaves the room","ออกจากห้อง"}.
{"Listened Ports","พอร์ทฟัง"}.
{"Listened Ports at ","พอร์ทฟังที่"}.
{"List of modules to start","รายการของโมดูลที่จะเริ่มการทำงาน"}.
{"Low level update script","อัพเดตสคริปต์ระดับต่ำ"}.
{"Make participants list public","สร้างรายการผู้เข้าร่วมสำหรับใช้งานโดยบุคคลทั่วไป"}.
{"Make room members-only","สร้างห้องสำหรับสมาชิกเท่านั้น"}.
{"Make room password protected","สร้างห้องที่มีการป้องกันด้วยรหัสผ่าน"}.
{"Make room persistent","สร้างเป็นห้องถาวร"}.
{"Make room public searchable","สร้างเป็นห้องที่บุคคลทั่วไปสามารถค้นหาได้"}.
{"March","มีนาคม"}.
{"Maximum Number of Occupants","จำนวนผู้ครอบครองห้องสูงสุด"}.
{"Max # of items to persist","จำนวนสูงสุดของรายการที่ยืนยัน"}.
{"Max payload size in bytes","ขนาดสูงสุดของส่วนของข้อมูล (payload) มีหน่วยเป็นไบต์"}.
{"May","พฤษภาคม"}.
{"Members:","สมาชิก:"}.
{"Memory","หน่วยความจำ"}.
{"Message body","เนื้อหาของข้อความ"}.
{"Middle Name","ชื่อกลาง"}.
{"Moderator privileges required","ต้องมีสิทธิพิเศษของผู้ดูแลการสนทนา"}.
{"moderators only","สำหรับผู้ดูแลการสนทนาเท่านั้น"}.
{"Module","โมดูล"}.
{"Modules","โมดูล"}.
{"Monday","วันจันทร์"}.
{"Name:","ชื่อ:"}.
{"Name","ชื่อ"}.
{"Never","ไม่เคย"}.
{"Nickname","ชื่อเล่น"}.
{"Nickname Registration at ","การลงทะเบียนชื่อเล่นที่ "}.
{"Nickname ~s does not exist in the room","ไม่มีชื่อเล่น ~s อยู่ในห้องนี้"}.
{"No body provided for announce message","ไม่ได้ป้อนเนื้อหาสำหรับข้อความที่ประกาศ"}.
{"No Data","ไม่มีข้อมูล"}.
{"Node ID","ID โหนด"}.
{"Node not found","ไม่พบโหนด"}.
{"Nodes","โหนด"}.
{"No limit","ไม่จำกัด"}.
{"None","ไม่มี"}.
{"No resource provided","ไม่ได้ระบุข้อมูล"}.
{"Notify subscribers when items are removed from the node","แจ้งเตือนผู้สมัครสมาชิกเมื่อรายการถูกลบออกจากโหนด"}.
{"Notify subscribers when the node configuration changes","แจ้งเตือนผู้สมัครสมาชิกเมื่อการกำหนดค่าโหนดเปลี่ยนแปลง"}.
{"Notify subscribers when the node is deleted","แจ้งเตือนผู้สมัครสมาชิกเมื่อโหนดถูกลบ"}.
{"November","พฤศจิกายน"}.
{"Number of occupants","จำนวนผู้ครอบครองห้อง"}.
{"Number of online users","จำนวนผู้ใช้ออนไลน์"}.
{"Number of registered users","จำนวนผู้ใช้ที่ลงทะเบียน"}.
{"October","ตุลาคม"}.
{"Offline Messages:","ข้อความออฟไลน์:"}.
{"Offline Messages","ข้อความออฟไลน์"}.
{"OK","ตกลง"}.
{"Online","ออนไลน์"}.
{"Online Users:","ผู้ใช้ออนไลน์:"}.
{"Online Users","ผู้ใช้ออนไลน์"}.
{"Only deliver notifications to available users","ส่งการแจ้งเตือนถึงผู้ใช้ที่สามารถติดต่อได้เท่านั้น"}.
{"Only occupants are allowed to send messages to the conference","ผู้ครอบครองห้องเท่านั้นที่ได้รับอนุญาตให้ส่งข้อความไปยังห้องประชุม"}.
{"Only occupants are allowed to send queries to the conference","ผู้ครอบครองห้องเท่านั้นที่ได้รับอนุญาตให้ส่งกระทู้ถามไปยังห้องประชุม"}.
{"Only service administrators are allowed to send service messages","ผู้ดูแลด้านการบริการเท่านั้นที่ได้รับอนุญาตให้ส่งข้อความการบริการ"}.
{"Options","ตัวเลือก"}.
{"Organization Name","ชื่อองค์กร"}.
{"Organization Unit","หน่วยขององค์กร"}.
{"Outgoing s2s Connections:","การเชื่อมต่อ s2s ขาออก:"}.
{"Outgoing s2s Connections","การเชื่อมต่อ s2s ขาออก"}.
{"Owner privileges required","ต้องมีสิทธิพิเศษของเจ้าของ"}.
{"Packet","แพ็กเก็ต"}.
{"Password:","รหัสผ่าน:"}.
{"Password","รหัสผ่าน"}.
{"Password Verification","การตรวจสอบรหัสผ่าน"}.
{"Path to Dir","พาธไปยัง Dir"}.
{"Path to File","พาธของไฟล์ข้อมูล"}.
{"Pending","ค้างอยู่"}.
{"Period: ","ระยะเวลา:"}.
{"Persist items to storage","ยืนยันรายการที่จะจัดเก็บ"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","พอร์ท"}.
{"Present real Jabber IDs to","แสดง Jabber IDs ที่ถูกต้องแก่"}.
{"private, ","ส่วนตัว, "}.
{"Publish-Subscribe","เผยแพร่-สมัครเข้าใช้งาน"}.
{"PubSub subscriber request","คำร้องขอของผู้สมัครเข้าใช้งาน PubSub"}.
{"Queries to the conference members are not allowed in this room","ห้องนี้ไม่อนุญาตให้ส่งกระทู้ถามถึงสมาชิกในห้องประชุม"}.
{"RAM and disc copy","คัดลอก RAM และดิสก์"}.
{"RAM copy","คัดลอก RAM"}.
{"Raw","ข้อมูลดิบ"}.
{"Really delete message of the day?","แน่ใจว่าต้องการลบข้อความของวันหรือไม่"}.
{"Recipient is not in the conference room","ผู้รับไม่ได้อยู่ในห้องประชุม"}.
{"Registered Users:","ผู้ใช้ที่ลงทะเบียน:"}.
{"Registered Users","ผู้ใช้ที่ลงทะเบียน"}.
{"Registration in mod_irc for ","การลงทะเบียนใน mod_irc สำหรับ"}.
{"Remote copy","คัดลอกระยะไกล"}.
{"Remove","ลบ"}.
{"Remove User","ลบผู้ใช้"}.
{"Replaced by new connection","แทนที่ด้วยการเชื่อมต่อใหม่"}.
{"Resources","ทรัพยากร"}.
{"Restart","เริ่มต้นใหม่"}.
{"Restart Service","เริ่มต้นการบริการใหม่อีกครั้ง"}.
{"Restore","การคืนค่า"}.
{"Restore Backup from File at ","คืนค่าการสำรองข้อมูลจากไฟล์ที่"}.
{"Restore binary backup after next ejabberd restart (requires less memory):","คืนค่าข้อมูลสำรองแบบไบนารีหลังจากที่ ejabberd ถัดไปเริ่มการทำงานใหม่ (ใช้หน่วยความจำน้อยลง):"}.
{"Restore binary backup immediately:","คืนค่าข้อมูลสำรองแบบไบนารีโดยทันที:"}.
{"Restore plain text backup immediately:","คืนค่าข้อมูลสำรองที่เป็นข้อความธรรมดาโดยทันที:"}.
{"Room Configuration","การกำหนดค่าห้องสนทนา"}.
{"Room creation is denied by service policy","การสร้างห้องสนทนาถูกปฏิเสธโดยนโยบายการบริการ"}.
{"Room title","ชื่อห้อง"}.
{"Roster","บัญชีรายชื่อ"}.
{"Roster of ","บัญชีรายชื่อของ "}.
{"Roster size","ขนาดของบัญชีรายชื่อ"}.
{"RPC Call Error","ข้อผิดพลาดจากการเรียกใช้ RPC"}.
{"Running Nodes","โหนดที่ทำงาน"}.
{"~s access rule configuration","~s การกำหนดค่ากฎการเข้าถึง"}.
{"Saturday","วันเสาร์"}.
{"Script check","ตรวจสอบคริปต์"}.
{"Search Results for ","ผลการค้นหาสำหรับ "}.
{"Search users in ","ค้นหาผู้ใช้ใน "}.
{"Send announcement to all online users","ส่งประกาศถึงผู้ใช้ออนไลน์ทั้งหมด"}.
{"Send announcement to all online users on all hosts","ส่งประกาศถึงผู้ใช้ออนไลน์ทั้งหมดบนโฮสต์ทั้งหมด"}.
{"Send announcement to all users","ส่งประกาศถึงผู้ใช้ทั้งหมด"}.
{"Send announcement to all users on all hosts","ส่งประกาศถึงผู้ใช้ทั้งหมดบนโฮสต์ทั้งหมด"}.
{"September","กันยายน"}.
{"Set message of the day and send to online users","ตั้งค่าข้อความของวันและส่งถึงผู้ใช้ออนไลน์"}.
{"Set message of the day on all hosts and send to online users","ตั้งค่าข้อความของวันบนโฮสต์ทั้งหมดและส่งถึงผู้ใช้ออนไลน์"}.
{"Shared Roster Groups","กลุ่มบัญชีรายชื่อที่ใช้งานร่วมกัน"}.
{"Show Integral Table","แสดงตารางรวม"}.
{"Show Ordinary Table","แสดงตารางทั่วไป"}.
{"Shut Down Service","ปิดการบริการ"}.
{"~s invites you to the room ~s","~s เชิญคุณเข้าร่วมสนทนาในห้อง ~s"}.
{"Specify the access model","ระบุโมเดลการเข้าถึง"}.
{"Specify the publisher model","ระบุโมเดลผู้เผยแพร่"}.
{"~s's Offline Messages Queue","~s's ลำดับข้อความออฟไลน์"}.
{"Start","เริ่ม"}.
{"Start Modules","เริ่มโมดูล"}.
{"Start Modules at ","เริ่มโมดูลที่"}.
{"Statistics","สถิติ"}.
{"Statistics of ~p","สถิติของ ~p"}.
{"Stop","หยุด"}.
{"Stop Modules","หยุดโมดูล"}.
{"Stop Modules at ","หยุดโมดูลที่"}.
{"Stopped Nodes","โหนดที่หยุด"}.
{"Storage Type","ชนิดที่เก็บข้อมูล"}.
{"Store binary backup:","จัดเก็บข้อมูลสำรองแบบไบนารี:"}.
{"Store plain text backup:","จัดเก็บข้อมูลสำรองที่เป็นข้อความธรรมดา:"}.
{"Subject","หัวเรื่อง"}.
{"Submit","ส่ง"}.
{"Submitted","ส่งแล้ว"}.
{"Subscriber Address","ที่อยู่ของผู้สมัคร"}.
{"Subscription","การสมัครสมาชิก"}.
{"Sunday","วันอาทิตย์"}.
{"the password is","รหัสผ่านคือ"}.
{"Thursday","วันพฤหัสบดี"}.
{"Time","เวลา"}.
{"Time delay","การหน่วงเวลา"}.
{"To","ถึง"}.
{"To ~s","ถึง ~s"}.
{"Traffic rate limit is exceeded","อัตราของปริมาณการเข้าใช้เกินขีดจำกัด"}.
{"Transactions Aborted:","ทรานแซกชันที่ถูกยกเลิก:"}.
{"Transactions Committed:","ทรานแซกชันที่ได้รับมอบหมาย:"}.
{"Transactions Logged:","ทรานแซกชันที่บันทึก:"}.
{"Transactions Restarted:","ทรานแซกชันที่เริ่มทำงานใหม่อีกครั้ง:"}.
{"Tuesday","วันอังคาร"}.
{"Update","อัพเดต"}.
{"Update message of the day (don't send)","อัพเดตข้อความของวัน (ไม่ต้องส่ง)"}.
{"Update message of the day on all hosts (don't send)","อัพเดตข้อความของวันบนโฮสต์ทั้งหมด (ไม่ต้องส่ง) "}.
{"Update plan","แผนการอัพเดต"}.
{"Update script","อัพเดตสคริปต์"}.
{"Uptime:","เวลาการทำงานต่อเนื่อง:"}.
{"Use of STARTTLS required","ต้องใช้ STARTTLS"}.
{"User","ผู้ใช้"}.
{"User Management","การจัดการผู้ใช้"}.
{"Users","ผู้ใช้"}.
{"Users Last Activity","กิจกรรมล่าสุดของผู้ใช้"}.
{"Validate","ตรวจสอบ"}.
{"vCard User Search","ค้นหาผู้ใช้ vCard "}.
{"Virtual Hosts","โฮสต์เสมือน"}.
{"Visitors are not allowed to send messages to all occupants","ผู้เยี่ยมเยือนไม่ได้รับอนุญาตให้ส่งข้อความถึงผู้ครอบครองห้องทั้งหมด"}.
{"Wednesday","วันพุธ"}.
{"When to send the last published item","เวลาที่ส่งรายการที่เผยแพร่ครั้งล่าสุด"}.
{"Whether to allow subscriptions","อนุญาตให้เข้าร่วมเป็นสมาชิกหรือไม่"}.
{"You have been banned from this room","คุณถูกสั่งห้ามไมให้เข้าห้องนี้"}.
{"You must fill in field \"Nickname\" in the form","คุณต้องกรอกฟิลด์ \"Nickname\" ในแบบฟอร์ม"}.
{"You need an x:data capable client to configure mod_irc settings","คุณต้องใช้ไคลเอ็นต์ที่รองรับ x:data เพื่อกำหนดการตั้งค่า mod_irc"}.
{"You need an x:data capable client to configure room","คุณต้องใช้ไคลเอ็นต์ที่รองรับ x:data เพื่อกำหนดค่าห้องสนทนา "}.
{"You need an x:data capable client to search","คุณต้องใช้ไคลเอ็นต์ที่รองรับ x:data เพื่อค้นหา"}.
{"Your contact offline message queue is full. The message has been discarded.","ลำดับข้อความออฟไลน์ของผู้ที่ติดต่อของคุณเต็มแล้ว ข้อความถูกลบทิ้งแล้ว"}.
