%% -*- coding: latin-1 -*-
{"Access Configuration","Erişim Ayarları"}.
{"Access Control List Configuration","Erişim Kontrol Listelerinin Ayarlanması (ACL)"}.
{"Access control lists","Erişim kontrol listeleri (ACL)"}.
{"Access Control Lists","Erişim Kontrol Listeleri (ACL)"}.
{"Access denied by service policy","Servis politikası gereği erişim engellendi"}.
{"Access rules","Erişim kuralları"}.
{"Access Rules","Erişim Kuralları"}.
{"Action on user","Kullanıcıya uygulanacak eylem"}.
{"Add Jabber ID","Jabber ID'si Ekle"}.
{"Add New","Yeni Ekle"}.
{"Add User","Kullanıcı Ekle"}.
{"Administration of ","Yönetim : "}.
{"Administration","Yönetim"}.
{"Administrator privileges required","Yönetim yetkileri gerekli"}.
{"A friendly name for the node","Düğüm için dostane bir isim"}.
{"All activity","Tüm aktivite"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Bu Jabber ID bu pubsub düğümüne üye olmasına izin verilsin mi?"}.
{"Allow users to change the subject","Kullanıcıların konu değiştirmesine izin ver"}.
{"Allow users to query other users","Kullanıcıların diğer kullanıcıları sorgulamalarına izin ver"}.
{"Allow users to send invites","Kullanıcıların davetiye göndermelerine izin ver"}.
{"Allow users to send private messages","Kullanıcıların özel mesaj göndermelerine izin ver"}.
{"Allow visitors to change nickname","Ziyaretçilerin takma isim değiştirmelerine izin ver"}.
{"Allow visitors to send private messages to","Ziyaretçilerin özel mesaj göndermelerine izin ver"}.
{"Allow visitors to send status text in presence updates","Ziyaretçilerin varlık (presence) güncellemelerinde durum metni göndermelerine izin ver"}.
{"Allow visitors to send voice requests","Ziyaretçilerin ses isteğine göndermelerine izin ver"}.
{"All Users","Tüm Kullanıcılar"}.
{"Announcements","Duyurular"}.
{"anyone","herkes"}.
{"A password is required to enter this room","Bu odaya girmek için parola gerekiyor"}.
{"April","Nisan"}.
{"August","Ağustos"}.
{"Backup Management","Yedek Yönetimi"}.
{"Backup to File at ","Dosyaya Yedekle : "}.
{"Backup","Yedekle"}.
{"Bad format","Kötü biçem"}.
{"Birthday","Doğumgünü"}.
{"CAPTCHA web page","CAPTCHA web sayfası"}.
{"Change Password","Parola Değiştir"}.
{"Change User Password","Kullanıcı Parolasını Değiştir"}.
{"Characters not allowed:","İzin verilmeyen karakterler:"}.
{"Chatroom configuration modified","Sohbet odası ayarı değiştirildi"}.
{"Chatroom is created","Sohbet odası oluşturuldu"}.
{"Chatroom is destroyed","Sohbet odası kaldırıldı"}.
{"Chatroom is started","Sohbet odası başlatıldı"}.
{"Chatroom is stopped","Sohbet odası durduruldu"}.
{"Chatrooms","Sohbet Odaları"}.
{"Choose a username and password to register with this server","Bu sunucuya kayıt olmak için bir kullanıcı ismi ve parola seçiniz"}.
{"Choose modules to stop","Durdurulacak modülleri seçiniz"}.
{"Choose storage type of tables","Tabloların veri depolama tipini seçiniz"}.
{"Choose whether to approve this entity's subscription.","Bu varlığın üyeliğini onaylayıp onaylamamayı seçiniz."}.
{"City","İl"}.
{"Commands","Komutlar"}.
{"Conference room does not exist","Konferans odası bulunamadı"}.
{"Configuration","Ayarlar"}.
{"Configuration of room ~s","~s odasının ayarları"}.
{"Connected Resources:","Bağlı Kaynaklar:"}.
{"Connections parameters","Bağlantı parametreleri"}.
{"Country","Ülke"}.
{"CPU Time:","İşlemci Zamanı:"}.
{"Database Tables Configuration at ","Veritabanı Tablo Ayarları : "}.
{"Database","Veritabanı"}.
{"December","Aralık"}.
{"Default users as participants","Kullanıcılar öntanımlı olarak katılımcı olsun"}.
{"Delete message of the day","Günün mesajını sil"}.
{"Delete message of the day on all hosts","Tüm sunuculardaki günün mesajını sil"}.
{"Delete Selected","Seçilenleri Sil"}.
{"Delete User","Kullanıcıyı Sil"}.
{"Deliver event notifications","Olay uyarıları gönderilsin"}.
{"Deliver payloads with event notifications","Yükleri (payload) olay uyarıları ile beraber gönder"}.
{"Description:","Tanım:"}.
{"Disc only copy","Sadece disk kopyala"}.
{"Displayed Groups:","Gösterilen Gruplar:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Parolanızı kimseye söylemeyin, Jabber sunucusunun yöneticilerine bile."}.
{"Dump Backup to Text File at ","Metin Dosyasına Döküm Alarak Yedekle : "}.
{"Dump to Text File","Metin Dosyasına Döküm Al"}.
{"Edit Properties","Özellikleri Düzenle"}.
{"Either approve or decline the voice request.","Ses isteğini kabul edin ya da reddedin"}.
{"ejabberd IRC module","ejabberd IRC modülü"}.
{"ejabberd MUC module","ejabberd MUC modülü"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe modülü"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams modülü"}.
{"ejabberd vCard module","ejabberd vCard modülü"}.
{"ejabberd Web Admin","ejabberd Web Yöneticisi"}.
{"Elements","Elementler"}.
{"Email","E-posta"}.
{"Enable logging","Kayıt tutma özelliğini aç"}.
{"Encoding for server ~b","Sunucu için kodlama ~b"}.
{"End User Session","Kullanıcı Oturumunu Kapat"}.
{"Enter list of {Module, [Options]}","{Module, [Options]} listesi giriniz"}.
{"Enter nickname you want to register","Kaydettirmek istediğiniz takma ismi giriniz"}.
{"Enter path to backup file","Yedek dosyasının yolunu giriniz"}.
{"Enter path to jabberd14 spool dir","jabberd14 spool dosyası için yol giriniz"}.
{"Enter path to jabberd14 spool file","jabberd14 spool dosyası için yol giriniz"}.
{"Enter path to text file","Metin dosyasının yolunu giriniz"}.
{"Enter the text you see","Gördüğünüz metni giriniz"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","IRC sunuculara bağlanmak için kullanmak istediğiniz kullanıcı isimleri ve kodlamaları giriniz.  'İleri' tuşuna basınca karşınıza dolduracak daha fazla alan çıkacak. 'Tamamla' tuşuna basarak ayarları kaydedin."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","IRC sunuculara bağlanmak için kullanmak istediğiniz kullanıcı ismi, kodlamalar, kapılar (portlar) ve parolaları giriniz"}.
{"Erlang Jabber Server","Erlang Jabber Sunucusu"}.
{"Error","Hata"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","Örnek: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"gizli\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}], {\"irc.sometestserver.net\", \"utf-8\"}]"}.
{"Exclude Jabber IDs from CAPTCHA challenge","CAPTCHA doğrulamasını şu Jabber ID'ler için yapma"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Sunucudaki tüm kullanıcıların verisini PIEFXIS dosyalarına (XEP-0227) dışa aktar:"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Bir sunucudaki kullanıcıların verisini PIEFXIS dosyalarına (XEP-0227) dışa aktar:"}.
{"Failed to extract JID from your voice request approval","Ses isteği onayınızdan JID bilginize ulaşılamadı"}.
{"Family Name","Soyisim"}.
{"February","Şubat"}.
{"Fill in fields to search for any matching Jabber User","Eşleşen jabber kullanıcılarını aramak için alanları doldurunuz"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Eşleşen jabber kullanıcılarını aramak için formu doldurunuz (Alt dizgi eşlemek için alanın sonuna * ekleyin)"}.
{"Friday","Cuma"}.
{"From","Kimden"}.
{"From ~s","Kimden ~s"}.
{"Full Name","Tam İsim"}.
{"Get Number of Online Users","Bağlı Kullanıcı Sayısını Al"}.
{"Get Number of Registered Users","Kayıtlı Kullanıcı Sayısını Al"}.
{"Get User Last Login Time","Kullanıcı Son Giriş Zamanınlarını Al"}.
{"Get User Password","Kullanıcı Parolasını Al"}.
{"Get User Statistics","Kullanıcı İstatistiklerini Al"}.
{"Grant voice to this person?","Bu kişiye ses verelim mi?"}.
{"Group ","Group "}.
{"Groups","Gruplar"}.
{"has been banned","odaya girmesi yasaklandı"}.
{"has been kicked because of an affiliation change","ilişki değişikliğinden dolayı atıldı"}.
{"has been kicked because of a system shutdown","sistem kapandığından dolayı atıldı"}.
{"has been kicked because the room has been changed to members-only","oda üyelere-özel hale getirildiğinden dolayı atıldı"}.
{"has been kicked","odadan atıldı"}.
{" has set the subject to: "," konuyu değiştirdi: "}.
{"Host","Sunucu"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Eğer burada CAPTCHA resmini göremiyorsanız, web sayfasını ziyaret edin."}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","IRC sunucuları için farklı kapılar (portlar), parolalar, kodlamalar belirtmek istiyorsanız, '{\"irc sunucusu\", \"kodlama\",\"kapı\",\"parola\"}' biçeminde değerlerle bu listeyi doldurunuz. Öntanımlı olarak bu servis \"~s\" kodlamasını, ~p \"kapısını\", \"boş\" parolasını kullanıyor."}.
{"Import Directory","Dizini İçe Aktar"}.
{"Import File","Dosyayı İçe Aktar"}.
{"Import user data from jabberd14 spool file:","Jabberd 1.4 Spool Dosyalarından Kullanıcıları İçe Aktar:"}.
{"Import User from File at ","Dosyadan Kullanıcıları İçe Aktar : "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Kullanıcıları bir PIEFXIS dosyasından (XEP-0227) içe aktar:"}.
{"Import users data from jabberd14 spool directory:","Jabberd 1.4 Spool Dizininden Kullanıcıları İçe Aktar:"}.
{"Import Users from Dir at ","Dizinden Kullanıcıları İçe Aktar : "}.
{"Import Users From jabberd14 Spool Files","Jabberd 1.4 Spool Dosyalarından Kullanıcıları İçeri Aktar"}.
{"Improper message type","Uygunsuz mesaj tipi"}.
{"Incorrect password","Yanlış parola"}.
{"Invalid affiliation: ~s","Geçersiz ilişki: ~s"}.
{"Invalid role: ~s","Geçersiz rol: ~s"}.
{"IP addresses","IP adresleri"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","IRC kanalı (ilk # işaretini koymayın)"}.
{"IRC server","IRC sunucusu"}.
{"IRC settings","IRC ayarları"}.
{"IRC Transport","IRC Nakli (Transport)"}.
{"IRC username","IRC kullanıcı ismi"}.
{"IRC Username","IRC Kullanıcı İsmi"}.
{"is now known as","isim değiştirdi :"}.
{"It is not allowed to send private messages of type \"groupchat\"","\"groupchat\" tipinde özel mesajlar gönderilmesine izin verilmiyor"}.
{"It is not allowed to send private messages","Özel mesaj gönderilmesine izin verilmiyor"}.
{"It is not allowed to send private messages to the conference","Konferansa özel mesajlar gönderilmesine izin verilmiyor"}.
{"Jabber Account Registration","Jabber Hesap Kaydı"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s geçersiz"}.
{"January","Ocak"}.
{"Join IRC channel","IRC kanalına katıl"}.
{"joins the room","odaya katıldı"}.
{"Join the IRC channel here.","Buradaki IRC kanalına katıl."}.
{"Join the IRC channel in this Jabber ID: ~s","IRC kanalına bu Jabber ID'si ile katıl: ~s"}.
{"July","Temmuz"}.
{"June","Haziran"}.
{"Last Activity","Son Aktivite"}.
{"Last login","Son giriş"}.
{"Last month","Geçen ay"}.
{"Last year","Geçen yıl"}.
{"leaves the room","odadan ayrıldı"}.
{"Listened Ports at ","Dinlenen Kapılar (Portlar) : "}.
{"Listened Ports","Dinlenen Kapılar (Portlar)"}.
{"List of modules to start","Başlatılacak modüllerin listesi"}.
{"Low level update script","Düşük seviye güncelleme betiği"}.
{"Make participants list public","Katılımcı listesini herkese açık hale getir"}.
{"Make room CAPTCHA protected","Odayı insan doğrulaması (captcha) korumalı hale getir"}.
{"Make room members-only","Odayı sadece üyelere açık hale getir"}.
{"Make room moderated","Odayı moderasyonlu hale getir"}.
{"Make room password protected","Odayı parola korumalı hale getir"}.
{"Make room persistent","Odayı kalıcı hale getir"}.
{"Make room public searchable","Odayı herkes tarafından aranabilir hale getir"}.
{"March","Mart"}.
{"Maximum Number of Occupants","Odada En Fazla Bulunabilecek Kişi Sayısı"}.
{"Max # of items to persist","Kalıcı hale getirilecek en fazla öğe sayısı"}.
{"Max payload size in bytes","En fazla yük (payload) boyutu (bayt olarak)"}.
{"May","Mayıs"}.
{"Membership is required to enter this room","Bu odaya girmek için üyelik gerekiyor"}.
{"Members:","Üyeler:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Parolanızı ezberleyin ya da bir kağıda yazarak güvenli bir yerde saklayın. Jabber'da parolanızı unutursanız, otomatik kurtarmak için bir yöntem bulunmuyor."}.
{"Memory","Bellek"}.
{"Message body","Mesajın gövdesi"}.
{"Middle Name","Ortanca İsim"}.
{"Minimum interval between voice requests (in seconds)","Ses istekleri arasında olabilecek en az aralık (saniye olarak)"}.
{"Moderator privileges required","Moderatör yetkileri gerekli"}.
{"moderators only","sadece moderatörler"}.
{"Modified modules","Değişen modüller"}.
{"Module","Modül"}.
{"Modules","Modüller"}.
{"Monday","Pazartesi"}.
{"Name:","İsim:"}.
{"Name","İsim"}.
{"Never","Asla"}.
{"New Password:","Yeni Parola:"}.
{"Nickname Registration at ","Takma İsim Kaydı : "}.
{"Nickname ~s does not exist in the room","~s takma ismi odada yok"}.
{"Nickname","Takma isim"}.
{"nobody","hiç kimse"}.
{"No body provided for announce message","Duyuru mesajının gövdesi yok"}.
{"No Data","Veri Yok"}.
{"Node ID","Düğüm ID"}.
{"Node not found","Düğüm bulunamadı"}.
{"Nodes","Düğümler"}.
{"No limit","Sınırsız"}.
{"None","Hiçbiri"}.
{"No resource provided","Hiç kaynak sağlanmadı"}.
{"Not Found","Bulunamadı"}.
{"Notify subscribers when items are removed from the node","Düğümden öğeler kaldırıldığında üyeleri uyar"}.
{"Notify subscribers when the node configuration changes","Düğüm ayarları değiştiğinde üyeleri uyar"}.
{"Notify subscribers when the node is deleted","Bir düğüm silindiğinde üyeleri uyar"}.
{"November","Kasım"}.
{"Number of occupants","Oda sakini sayısı"}.
{"Number of online users","Bağlı kullanıcı sayısı"}.
{"Number of registered users","Kayıtlı kullanıcı sayısı"}.
{"October","Ekim"}.
{"Offline Messages:","Çevirim-dışı Mesajlar:"}.
{"Offline Messages","Çevirim-dışı Mesajlar"}.
{"OK","Tamam"}.
{"Old Password:","Eski Parola:"}.
{"Online","Bağlı"}.
{"Online Users:","Bağlı Kullanıcılar:"}.
{"Online Users","Bağlı Kullanıcılar"}.
{"Only deliver notifications to available users","Uyarıları sadece durumu uygun kullanıcılara ulaştır"}.
{"Only moderators and participants are allowed to change the subject in this room","Sadece moderatörlerin ve katılımcıların bu odanın konusunu değiştirmesine izin veriliyor"}.
{"Only moderators are allowed to change the subject in this room","Sadece moderatörlerin bu odanın konusunu değiştirmesine izin veriliyor"}.
{"Only moderators can approve voice requests","Yalnız moderatörler ses isteklerini onaylayabilir"}.
{"Only occupants are allowed to send messages to the conference","Sadece oda sakinlerinin konferansa mesaj göndermesine izin veriliyor"}.
{"Only occupants are allowed to send queries to the conference","Sadece oda sakinlerinin konferansa sorgu göndermesine izin veriliyor"}.
{"Only service administrators are allowed to send service messages","Sadece servis yöneticileri servis mesajı gönderebilirler"}.
{"Options","Seçenekler"}.
{"Organization Name","Kurum İsmi"}.
{"Organization Unit","Kurumun İlgili Birimi"}.
{"Outgoing s2s Connections:","Giden s2s Bağlantıları:"}.
{"Outgoing s2s Connections","Giden s2s Bağlantıları"}.
{"Owner privileges required","Sahip yetkileri gerekli"}.
{"Packet","Paket"}.
{"Password ~b","Parola ~b"}.
{"Password:","Parola:"}.
{"Password","Parola"}.
{"Password Verification:","Parola Doğrulaması:"}.
{"Password Verification","Parola Doğrulaması"}.
{"Path to Dir","Dizinin Yolu"}.
{"Path to File","Dosyanın Yolu"}.
{"Pending","Sıra Bekleyen"}.
{"Period: ","Periyot:"}.
{"Persist items to storage","Öğeleri depoda kalıcı hale getir"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Bu seçeneklerin sadece gömülü Mnesia veritabanını yedekleyeceğine dikkat edin. Eğer ODBC modülünü kullanıyorsanız, SQL veritabanınızı da ayrıca yedeklemeniz gerekiyor."}.
{"Please, wait for a while before sending new voice request","Lütfen yeni bir ses isteği göndermeden önce biraz bekleyin"}.
{"Pong","Pong"}.
{"Port ~b","Kapı (Port) ~b"}.
{"Port","Kapı (Port)"}.
{"Present real Jabber IDs to","Gerçek Jabber ID'lerini göster :"}.
{"private, ","özel"}.
{"Protocol","Protokol"}.
{"Publish-Subscribe","Yayınla-Üye Ol"}.
{"PubSub subscriber request","PubSub üye isteği"}.
{"Purge all items when the relevant publisher goes offline","İlgili yayıncı çevirimdışı olunca tüm onunla ilgili olanları sil"}.
{"Queries to the conference members are not allowed in this room","Bu odada konferans üyelerine sorgu yapılmasına izin verilmiyor"}.
{"RAM and disc copy","RAM ve disk kopyala"}.
{"RAM copy","RAM kopyala"}.
{"Raw","Ham"}.
{"Really delete message of the day?","Günün mesajını silmek istediğinize emin misiniz?"}.
{"Recipient is not in the conference room","Alıcı konferans odasında değil"}.
{"Register a Jabber account","Bir Jabber hesabı kaydet"}.
{"Registered Users:","Kayıtlı Kullanıcılar:"}.
{"Registered Users","Kayıtlı Kullanıcılar"}.
{"Register","Kayıt Ol"}.
{"Registration in mod_irc for ","mod_irc'ye kayıt : "}.
{"Remote copy","Uzak kopyala"}.
{"Remove All Offline Messages","Tüm Çevirim-dışı Mesajları Kaldır"}.
{"Remove","Kaldır"}.
{"Remove User","Kullanıcıyı Kaldır"}.
{"Replaced by new connection","Eski bağlantı yenisi ile değiştirildi"}.
{"Resources","Kaynaklar"}.
{"Restart Service","Servisi Tekrar Başlat"}.
{"Restart","Tekrar Başlat"}.
{"Restore Backup from File at ","Dosyadaki Yedekten Geri Al : "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","ejabberd'nin bir sonraki tekrar başlatılışında ikili yedekten geri al (daha az bellek gerektirir)"}.
{"Restore binary backup immediately:","Hemen ikili yedekten geri al:"}.
{"Restore plain text backup immediately:","Hemen düz metin yedekten geri al"}.
{"Restore","Yedekten Geri Al"}.
{"Room Configuration","Oda Ayarları"}.
{"Room creation is denied by service policy","Odanın oluşturulması servis politikası gereği reddedildi"}.
{"Room description","Oda tanımı"}.
{"Room Occupants","Oda Sakini Sayısı"}.
{"Room title","Oda başlığı"}.
{"Roster groups allowed to subscribe","Üye olunmasına izin verilen kontak listesi grupları"}.
{"Roster","Kontak Listesi"}.
{"Roster of ","Kontak Listesi : "}.
{"Roster size","İsim listesi boyutu"}.
{"RPC Call Error","RPC Çağrı Hatası"}.
{"Running Nodes","Çalışan Düğümler"}.
{"~s access rule configuration","~s erişim kuralları ayarları"}.
{"Saturday","Cumartesi"}.
{"Script check","Betik kontrolü"}.
{"Search Results for ","Arama sonuçları : "}.
{"Search users in ","Kullanıcılarda arama yap : "}.
{"Send announcement to all online users","Duyuruyu tüm bağlı kullanıcılara yolla"}.
{"Send announcement to all online users on all hosts","Duyuruyu tüm sunuculardaki tüm bağlı kullanıcılara yolla"}.
{"Send announcement to all users","Duyuruyu tüm kullanıcılara yolla"}.
{"Send announcement to all users on all hosts","Tüm sunuculardaki tüm kullanıcılara duyuru yolla"}.
{"September","Eylül"}.
{"Server ~b","Sunucu ~b"}.
{"Server:","Sunucu:"}.
{"Set message of the day and send to online users","Günün mesajını belirle"}.
{"Set message of the day on all hosts and send to online users","Tüm sunucularda günün mesajını belirle ve bağlı tüm kullanıcılara gönder"}.
{"Shared Roster Groups","Paylaşımlı Kontak Listesi Grupları"}.
{"Show Integral Table","Önemli Tabloyu Göster"}.
{"Show Ordinary Table","Sıradan Tabloyu Göster"}.
{"Shut Down Service","Servisi Kapat"}.
{"~s invites you to the room ~s","~s sizi ~s odasına davet ediyor"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Bazı Jabber istemcileri parolanızı bilgisayarınızda saklayabilir. Bu özelliği ancak bilgisayarın güvenli olduğuna güveniyorsanız kullanın."}.
{"Specify the access model","Erişim modelini belirtiniz"}.
{"Specify the event message type","Olay mesaj tipini belirtiniz"}.
{"Specify the publisher model","Yayıncı modelini belirtiniz"}.
{"~s's Offline Messages Queue","~s Kullanıcısının Mesaj Kuyruğu"}.
{"Start","Başlat"}.
{"Start Modules at ","Modülleri Başlat : "}.
{"Start Modules","Modülleri Başlat"}.
{"Statistics","İstatistikler"}.
{"Statistics of ~p","~p istatistikleri"}.
{"Stop","Durdur"}.
{"Stop Modules at ","Modülleri Durdur : "}.
{"Stop Modules","Modülleri Durdur"}.
{"Stopped Nodes","Durdurulmuş Düğümler"}.
{"Storage Type","Depolama Tipi"}.
{"Store binary backup:","İkili yedeği sakla:"}.
{"Store plain text backup:","Düz metin yedeği sakla:"}.
{"Subject","Konu"}.
{"Submit","Gönder"}.
{"Submitted","Gönderilenler"}.
{"Subscriber Address","Üye Olanın Adresi"}.
{"Subscription","Üyelik"}.
{"Sunday","Pazar"}.
{"That nickname is already in use by another occupant","Takma isim odanın başka bir sakini tarafından halihazırda kullanımda"}.
{"That nickname is registered by another person","O takma isim başka biri tarafından kaydettirilmiş"}.
{"The CAPTCHA is valid.","İnsan doğrulaması (captcha) geçerli."}.
{"The CAPTCHA verification has failed","CAPTCHA doğrulaması başarısız oldu"}.
{"The collections with which a node is affiliated","Bir düğüm ile bağlantılı koleksiyonlar"}.
{"the password is","parola :"}.
{"The password is too weak","Parola çok zayıf"}.
{"The password of your Jabber account was successfully changed.","Jabber hesabınızın parolası başarıyla değiştirildi."}.
{"There was an error changing the password: ","Parolanın değiştirilmesi sırasında bir hata oluştu:"}.
{"There was an error creating the account: ","Hesap oluşturulurken bir hata oluştu:"}.
{"There was an error deleting the account: ","Hesabın silinmesi sırasında bir hata oluştu:"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Burada büyük küçük harfi yapılmaz: macbeth ile MacBeth ve Macbeth aynıdır."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Bu sayfa bu Jabber sunucusunda bir Jabber hesabı oluşturulmasına olanak tanıyor. Sizin JID'iniz (Jabber Tanımlayıcısı) şu biçemde olacaktır: kullanici_adi@sunucu. Lütfen alanları doğru doldurabilmek için yönergeleri dikkatle okuyunuz."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Bu sayfa bu Jabber sunucusundan bir Jabber hesabının kaydını silmeye olanak tanıyor."}.
{"Thursday","Perşembe"}.
{"Time delay","Zaman gecikmesi"}.
{"Time","Zaman"}.
{"To","Kime"}.
{"Too many CAPTCHA requests","Çok fazla CAPTCHA isteği"}.
{"To ~s","Kime ~s"}.
{"Traffic rate limit is exceeded","Trafik oran sınırı aşıldı"}.
{"Transactions Aborted:","İptal Edilen Hareketler (Transactions):"}.
{"Transactions Committed:","Tamamlanan Hareketler (Transactions Committed):"}.
{"Transactions Logged:","Kaydı Tutulan Hareketler (Transactions):"}.
{"Transactions Restarted:","Tekrar Başlatılan Hareketler (Transactions):"}.
{"Tuesday","Salı"}.
{"Unable to generate a CAPTCHA","İnsan doğrulaması (CAPTCHA) oluşturulamadı"}.
{"Unauthorized","Yetkisiz"}.
{"Unregister a Jabber account","Bir Jabber hesabı kaydı sil"}.
{"Unregister","Kaydı Sil"}.
{"Update","GÜncelle"}.
{"Update message of the day (don't send)","Günün mesajını güncelle (gönderme)"}.
{"Update message of the day on all hosts (don't send)","Tüm sunuculardaki günün mesajını güncelle (gönderme)"}.
{"Update plan","Planı güncelle"}.
{"Update script","Betiği Güncelle"}.
{"Uptime:","Hizmet Süresi:"}.
{"Use of STARTTLS required","STARTTLS kullanımı gereklidir"}.
{"User JID","Kullanıcı JID"}.
{"User","Kullanıcı"}.
{"User Management","Kullanıcı Yönetimi"}.
{"Username:","Kullanıcı adı:"}.
{"Users are not allowed to register accounts so quickly","Kullanıcıların bu kadar hızlı hesap açmalarına izin verilmiyor"}.
{"Users","Kullanıcılar"}.
{"Users Last Activity","Kullanıcıların Son Aktiviteleri"}.
{"Validate","Geçerli"}.
{"vCard User Search","vCard Kullanıcı Araması"}.
{"Virtual Hosts","Sanal Sunucuları"}.
{"Visitors are not allowed to change their nicknames in this room","Bu odada ziyaretçilerin takma isimlerini değiştirmesine izin verilmiyor"}.
{"Visitors are not allowed to send messages to all occupants","Ziyaretçilerin odadaki tüm sakinlere mesaj göndermesine izin verilmiyor"}.
{"Voice requests are disabled in this conference","Bu konferansta ses istekleri etkisizleştirilmiş durumda."}.
{"Voice request","Ses isteği"}.
{"Wednesday","Çarşamba"}.
{"When to send the last published item","Son yayınlanan öğe ne zaman gönderilsin"}.
{"Whether to allow subscriptions","Üyeliklere izin verilsin mi"}.
{"You can later change your password using a Jabber client.","Parolanızı daha sonra bir Jabber istemci kullanarak değiştirebilirsiniz."}.
{"You have been banned from this room","Bu odaya girmeniz yasaklandı"}.
{"You must fill in field \"Nickname\" in the form","Formda \"Takma isim\" alanını doldurmanız gerekiyor"}.
{"You need a client that supports x:data and CAPTCHA to register","Takma isminizi kaydettirmek için x:data ve CAPTCHA destekleyen bir istemciye gereksinimiz var"}.
{"You need a client that supports x:data to register the nickname","Takma isminizi kaydettirmek için x:data destekleyen bir istemciye gereksinimiz var"}.
{"You need an x:data capable client to configure mod_irc settings","mod_irc ayarlarını düzenlemek için x:data becerisine sahip bir istemciye gereksinimiz var"}.
{"You need an x:data capable client to configure room","Odayı ayarlamak için x:data becerisine sahip bir istemciye gereksinimiz var"}.
{"You need an x:data capable client to search","Arama yapabilmek için x:data becerisine sahip bir istemciye gereksinimiz var"}.
{"Your active privacy list has denied the routing of this stanza.","Etkin mahremiyet listeniz bu bölümün yönlendirilmesini engelledi."}.
{"Your contact offline message queue is full. The message has been discarded.","Çevirim-dışı mesaj kuyruğunuz dolu. Mesajını dikkate alınmadı."}.
{"Your Jabber account was successfully created.","Jabber hesabınız başarıyla oluşturuldu."}.
{"Your Jabber account was successfully deleted.","Jabber hesabınız başarıyla silindi."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","~s kullanıcısına mesajlarınız engelleniyor. Durumu düzeltmek için ~s adresini ziyaret ediniz."}.
