%% -*- coding: latin-1 -*-
{"Access Configuration","Cấu Hình Truy Cập"}.
{"Access Control List Configuration","Cấu Hình Danh Sách Kiểm Soát Truy Cập"}.
{"Access control lists","Danh sách kiểm soát truy cập"}.
{"Access Control Lists","Danh Sách Kiểm Soát Truy Cập"}.
{"Access denied by service policy","Sự truy cập bị chặn theo chính sách phục vụ"}.
{"Access rules","Quy tắc Truy Cập"}.
{"Access Rules","Quy Tắc Truy Cập"}.
{"Action on user","Hành động đối với người sử dụng"}.
{"Add Jabber ID","Thêm Jabber ID"}.
{"Add New","Thêm Mới"}.
{"Add User","Thêm Người Sử Dụng"}.
{"Administration of ","Quản trị về "}.
{"Administration","Quản trị"}.
{"Administrator privileges required","Yêu cầu đặc quyền của nhà quản trị"}.
{"All activity","Tất cả hoạt động"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Cho phép Jabber ID đăng ký nút môđun xuất bản đăng ký này không?"}.
{"Allow users to query other users","Cho phép người sử dụng hỏi người sử dụng khác"}.
{"Allow users to send invites","Cho phép người sử dụng gửi lời mời"}.
{"Allow users to send private messages","Cho phép người sử dụng gửi thư riêng"}.
{"All Users","Tất Cả Người Sử Dụng"}.
{"Announcements","Thông báo"}.
{"anyone","bất kỳ ai"}.
{"April","Tháng Tư"}.
{"August","Tháng Tám"}.
{"Backup Management","Quản lý Sao Lưu Dự Phòng"}.
{"Backup","Sao lưu dự phòng"}.
{"Backup to File at ","Sao lưu dự phòng ra Tập Tin tại"}.
{"Bad format","Định dạng hỏng"}.
{"Birthday","Ngày sinh"}.
{"Change Password","Thay Đổi Mật Khẩu"}.
{"Change User Password","Thay Đổi Mật Khẩu Người Sử Dụng"}.
{"Chatroom configuration modified","Cấu hình phòng trò chuyện được chỉnh sửa"}.
{"Chatrooms","Phòng trò chuyện"}.
{"Choose a username and password to register with this server","Chọn một tên truy cập và mật khẩu để đăng ký với máy chủ này"}.
{"Choose modules to stop","Chọn môđun để dừng"}.
{"Choose storage type of tables","Chọn loại bảng lưu trữ"}.
{"Choose whether to approve this entity's subscription.","Chọn có nên chấp nhận sự đăng ký của đối tượng này không"}.
{"City","Thành phố"}.
{"Commands","Lệnh"}.
{"Conference room does not exist","Phòng họp không tồn tại"}.
{"Configuration","Cấu hình"}.
{"Connected Resources:","Tài Nguyên Được Kết Nối:"}.
{"Country","Quốc gia"}.
{"CPU Time:","Thời Gian CPU:"}.
{"Database","Cơ sở dữ liệu"}.
{"Database Tables Configuration at ","Cấu Hình Bảng Cơ Sở Dữ Liệu tại"}.
{"December","Tháng Mười Hai"}.
{"Default users as participants","Người sử dụng mặc định là người tham dự"}.
{"Delete message of the day on all hosts","Xóa thư trong ngày trên tất cả các máy chủ"}.
{"Delete message of the day","Xóa thư trong ngày"}.
{"Delete Selected","Tùy chọn Xóa được Chọn"}.
{"Delete User","Xóa Người Sử Dụng"}.
{"Deliver event notifications","Đưa ra các thông báo sự kiện"}.
{"Deliver payloads with event notifications","Đưa ra thông tin dung lượng với các thông báo sự kiện"}.
{"Description:","Miêu tả:"}.
{"Disc only copy","Chỉ sao chép vào đĩa"}.
{"Displayed Groups:","Nhóm được hiển thị:"}.
{"Dump Backup to Text File at ","Kết Xuất Sao Lưu ra Tập Tin Văn Bản tại"}.
{"Dump to Text File","Kết xuất ra Tập Tin Văn Bản"}.
{"Edit Properties","Chỉnh Sửa Thuộc Tính"}.
{"ejabberd IRC module","Môdun ejabberd IRC Bản quyền"}.
{"ejabberd MUC module","Môdun ejabberd MUC Bản quyền"}.
{"ejabberd Publish-Subscribe module","Môdun ejabberd Xuất Bản-Đăng Ký Bản quyền"}.
{"ejabberd SOCKS5 Bytestreams module","Môdun SOCKS5 Bytestreams Bản quyền"}.
{"ejabberd vCard module","Môdun ejabberd vCard Bản quyền"}.
{"Email","Email"}.
{"Enable logging","Cho phép ghi nhật ký"}.
{"End User Session","Kết Thúc Phiên Giao Dịch Người Sử Dụng"}.
{"Enter list of {Module, [Options]}","Nhập danh sách {Môđun, [Các Tùy Chọn]}"}.
{"Enter nickname you want to register","Nhập bí danh bạn muốn đăng ký"}.
{"Enter path to backup file","Nhập đường dẫn đến tập tin sao lưu dự phòng"}.
{"Enter path to jabberd14 spool dir","Nhập đường dẫn đến thư mục spool jabberd14"}.
{"Enter path to jabberd14 spool file","Nhập đường dẫn đến tập tin spool jabberd14"}.
{"Enter path to text file","Nhập đường dẫn đến tập tin văn bản"}.
{"Erlang Jabber Server","Erlang Jabber Server Bản quyền"}.
{"Family Name","Họ"}.
{"February","Tháng Hai"}.
{"Fill in fields to search for any matching Jabber User","Điền vào các ô để tìm kiếm bất kỳ các thông tin nào khớp với Người sử dụng Jabber"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Điền vào mẫu này để tìm kiếm bất kỳ thông tin nào khớp với Người sử dụng Jabber (Thêm dấu * vào cuối ô để thông tin khớp với chuỗi bên trong)"}.
{"Friday","Thứ Sáu"}.
{"From ~s","Nhận từ ~s"}.
{"From","Từ"}.
{"Full Name","Tên Đầy Đủ"}.
{"Get Number of Online Users","Nhận Số Người Sử Dụng Trực Tuyến"}.
{"Get Number of Registered Users","Nhận Số Người Sử Dụng Đã Đăng Ký"}.
{"Get User Last Login Time","Nhận Thời Gian Đăng Nhập Cuối Cùng Của Người Sử Dụng"}.
{"Get User Password","Nhận Mật Khẩu Người Sử Dụng"}.
{"Get User Statistics","Nhận Thông Tin Thống Kê Người Sử Dụng"}.
{"Group ","Nhóm "}.
{"Groups","Nhóm"}.
{"has been banned","đã bị cấm"}.
{"has been kicked","đã bị đẩy ra khỏi"}.
{" has set the subject to: "," đã đặt chủ đề thành: "}.
{"Host","Máy chủ"}.
{"Import Directory","Nhập Thư Mục"}.
{"Import File","Nhập Tập Tin"}.
{"Import User from File at ","Nhập Người Sử Dụng từ Tập Tin tại"}.
{"Import Users from Dir at ","Nhập Người Sử Dụng từ Thư Mục tại"}.
{"Import Users From jabberd14 Spool Files","Nhập Người Sử Dụng Từ Các Tập Tin Spool jabberd14"}.
{"Improper message type","Loại thư không phù hợp"}.
{"Incorrect password","Mật khẩu sai"}.
{"Invalid affiliation: ~s","Tư cách không hợp lệ: ~s"}.
{"Invalid role: ~s","Vai trò không hợp lệ: ~s"}.
{"IP addresses","Địa chỉ IP"}.
{"IRC Transport","Truyền tải IRC"}.
{"IRC Username","Tên truy cập IRC"}.
{"is now known as","bây giờ được biết như"}.
{"It is not allowed to send private messages of type \"groupchat\"","Không được phép gửi những thư riêng loại \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Không được phép gửi những thư riêng đến phòng họp"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s không hợp lệ"}.
{"January","Tháng Một"}.
{"joins the room","tham gia phòng này"}.
{"July","Tháng Bảy"}.
{"June","Tháng Sáu"}.
{"Last Activity","Hoạt Động Cuối Cùng"}.
{"Last login","Đăng nhập lần cuối"}.
{"Last month","Tháng trước"}.
{"Last year","Năm trước"}.
{"leaves the room","rời khỏi phòng này"}.
{"Listened Ports at ","Cổng Liên Lạc tại"}.
{"Listened Ports","Cổng Kết Nối"}.
{"List of modules to start","Danh sách các môđun khởi động"}.
{"Low level update script","Lệnh cập nhật mức độ thấp"}.
{"Make participants list public","Tạo danh sách người tham dự công khai"}.
{"Make room members-only","Tạo phòng chỉ cho phép tư cách thành viên tham gia"}.
{"Make room password protected","Tạo phòng được bảo vệ bằng mật khẩu"}.
{"Make room persistent","Tạo phòng bền vững"}.
{"Make room public searchable","Tạo phòng có thể tìm kiếm công khai"}.
{"March","Tháng Ba"}.
{"Maximum Number of Occupants","Số Lượng Người Tham Dự Tối Đa"}.
{"Max # of items to persist","Số mục tối đa để lưu trữ"}.
{"Max payload size in bytes","Kích thước dung lượng byte tối đa"}.
{"May","Tháng Năm"}.
{"Members:","Thành viên:"}.
{"Memory","Bộ Nhớ"}.
{"Message body","Thân thư"}.
{"Middle Name","Họ Đệm"}.
{"Moderator privileges required","Yêu cầu đặc quyền của nhà điều phối"}.
{"moderators only","nhà điều phối duy nhất"}.
{"Module","Môđun"}.
{"Modules","Môđun"}.
{"Monday","Thứ Hai"}.
{"Name:","Tên:"}.
{"Name","Tên"}.
{"Never","Không bao giờ"}.
{"Nickname","Bí danh"}.
{"Nickname Registration at ","Đăng Ký Bí Danh tại"}.
{"Nickname ~s does not exist in the room","Bí danh ~s không tồn tại trong phòng này"}.
{"No body provided for announce message","Không có nội dung trong thư thông báo"}.
{"No Data","Không Dữ Liệu"}.
{"Node ID","ID Nút"}.
{"Node not found","Nút không tìm thấy"}.
{"Nodes","Nút"}.
{"No limit","Không giới hạn"}.
{"None","Không có"}.
{"No resource provided","Không có nguồn lực cung cấp"}.
{"Notify subscribers when items are removed from the node","Thông báo cho người đăng ký khi nào các mục chọn bị gỡ bỏ khỏi nút"}.
{"Notify subscribers when the node configuration changes","Thông báo cho người đăng ký khi nào cấu hình nút thay đổi"}.
{"Notify subscribers when the node is deleted","Thông báo cho người đăng ký khi nào nút bị xóa bỏ"}.
{"November","Tháng Mười Một"}.
{"Number of occupants","Số người tham dự"}.
{"Number of online users","Số người sử dụng trực tuyến"}.
{"Number of registered users","Số người sử dụng đã đăng ký"}.
{"October","Tháng Mười"}.
{"Offline Messages:","Thư Ngoại Tuyến:"}.
{"Offline Messages","Thư Ngoại Tuyến"}.
{"OK","OK"}.
{"Online","Trực tuyến"}.
{"Online Users:","Người Sử Dụng Trực Tuyến:"}.
{"Online Users","Người Sử Dụng Trực Tuyến"}.
{"Only deliver notifications to available users","Chỉ gửi thông báo đến những người sử dụng hiện có"}.
{"Only occupants are allowed to send messages to the conference","Chỉ có những đối tượng tham gia mới được phép gửi thư đến phòng họp"}.
{"Only occupants are allowed to send queries to the conference","Chỉ có những đối tượng tham gia mới được phép gửi yêu cầu đến phòng họp"}.
{"Only service administrators are allowed to send service messages","Chỉ có người quản trị dịch vụ mới được phép gửi những thư dịch vụ"}.
{"Options","Tùy chọn"}.
{"Organization Name","Tên Tổ Chức"}.
{"Organization Unit","Bộ Phận"}.
{"Outgoing s2s Connections:","Kết Nối Bên Ngoài s2s:"}.
{"Outgoing s2s Connections","Kết Nối Bên Ngoài s2s"}.
{"Owner privileges required","Yêu cầu đặc quyền của người sở hữu"}.
{"Packet","Gói thông tin"}.
{"Password:","Mật Khẩu:"}.
{"Password","Mật Khẩu"}.
{"Password Verification","Kiểm Tra Mật Khẩu"}.
{"Path to Dir","Đường Dẫn đến Thư Mục"}.
{"Path to File","Đường dẫn đến Tập Tin"}.
{"Pending","Chờ"}.
{"Period: ","Giai đoạn: "}.
{"Persist items to storage","Những mục cần để lưu trữ"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","Cổng"}.
{"Present real Jabber IDs to","Jabber ID thực tế hiện hành đến"}.
{"private, ","riêng,"}.
{"Publish-Subscribe","Xuất Bản-Đăng Ký"}.
{"PubSub subscriber request","Yêu cầu người đăng ký môđun Xuất Bản Đăng Ký"}.
{"Queries to the conference members are not allowed in this room","Không được phép gửi các yêu cầu gửi đến các thành viên trong phòng họp này"}.
{"RAM and disc copy","Sao chép vào RAM và đĩa"}.
{"RAM copy","Sao chép vào RAM"}.
{"Raw","Thô"}.
{"Really delete message of the day?","Có thực sự xóa thư trong ngày này không?"}.
{"Recipient is not in the conference room","Người nhận không có trong phòng họp"}.
{"Registered Users:","Người Sử Dụng Đã Đăng Ký:"}.
{"Registered Users","Người Sử Dụng Đã Đăng Ký"}.
{"Registration in mod_irc for ","Đăng ký trong mod_irc cho "}.
{"Remote copy","Sao chép từ xa"}.
{"Remove","Gỡ bỏ"}.
{"Remove User","Gỡ Bỏ Người Sử Dụng"}.
{"Replaced by new connection","Được thay thế bởi kết nối mới"}.
{"Resources","Nguồn tài nguyên"}.
{"Restart","Khởi động lại"}.
{"Restart Service","Khởi Động Lại Dịch Vụ"}.
{"Restore Backup from File at ","Phục hồi Sao Lưu từ Tập Tin tại "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Khôi phục bản sao lưu dự phòng dạng nhị phân sau lần khởi động ejabberd kế tiếp (yêu cầu ít bộ nhớ hơn):"}.
{"Restore binary backup immediately:","Khôi phục bản sao lưu dự phòng dạng nhị phận ngay lập tức:"}.
{"Restore","Khôi phục"}.
{"Restore plain text backup immediately:","Khôi phục bản sao lưu dự phòng thuần văn bản ngay lập tức:"}.
{"Room Configuration","Cấu Hình Phòng"}.
{"Room creation is denied by service policy","Việc tạo phòng bị ngăn lại theo chính sách dịch vụ"}.
{"Room title","Tên phòng"}.
{"Roster","Bảng phân công"}.
{"Roster of ","Bảng phân công của "}.
{"Roster size","Kích thước bảng phân công"}.
{"RPC Call Error","Lỗi Gọi RPC"}.
{"Running Nodes","Nút Hoạt Động"}.
{"~s access rule configuration","~s cấu hình quy tắc truy cập"}.
{"Saturday","Thứ Bảy"}.
{"Script check","Lệnh kiểm tra"}.
{"Search Results for ","Kết Quả Tìm Kiếm cho "}.
{"Search users in ","Tìm kiếm người sử dụng trong"}.
{"Send announcement to all online users","Gửi thông báo đến tất cả người sử dụng trực tuyến"}.
{"Send announcement to all online users on all hosts","Gửi thông báo đến tất cả người sử dụng trực tuyến trên tất cả các máy chủ"}.
{"Send announcement to all users","Gửi thông báo đến tất cả người sử dụng"}.
{"Send announcement to all users on all hosts","Gửi thông báo đến tất cả người sử dụng trên tất cả các máy chủ"}.
{"September","Tháng Chín"}.
{"Set message of the day and send to online users","Tạo lập thư trong ngày và gửi đến những người sử dụng trực tuyến"}.
{"Set message of the day on all hosts and send to online users","Tạo lập thư trong ngày trên tất cả các máy chủ và gửi đến những người sử dụng trực tuyến"}.
{"Shared Roster Groups","Nhóm Phân Công Chia Sẻ"}.
{"Show Integral Table","Hiển Thị Bảng Đầy Đủ"}.
{"Show Ordinary Table","Hiển Thị Bảng Thường"}.
{"Shut Down Service","Tắt Dịch Vụ"}.
{"~s invites you to the room ~s","~s mời bạn vào phòng ~s"}.
{"Specify the access model","Xác định mô hình truy cập"}.
{"Specify the publisher model","Xác định mô hình nhà xuất bản"}.
{"~s's Offline Messages Queue","~s's Danh Sách Chờ Thư Ngoại Tuyến"}.
{"Start","Khởi động"}.
{"Start Modules at ","Môđun Khởi Động tại "}.
{"Start Modules","Môđun Khởi Động"}.
{"Statistics of ~p","Thống kê về ~p"}.
{"Statistics","Số liệu thống kê"}.
{"Stop","Dừng"}.
{"Stop Modules at ","Môđun Dừng tại"}.
{"Stop Modules","Môđun Dừng"}.
{"Stopped Nodes","Nút Dừng"}.
{"Storage Type","Loại Lưu Trữ"}.
{"Store binary backup:","Lưu dữ liệu sao lưu dạng nhị phân:"}.
{"Store plain text backup:","Khôi phục bản sao lưu dự phòng thuần văn bản"}.
{"Subject","Tiêu đề"}.
{"Submit","Gửi"}.
{"Submitted","Đã gửi"}.
{"Subscriber Address","Địa Chỉ Người Đăng Ký"}.
{"Subscription","Đăng ký"}.
{"Sunday","Chủ Nhật"}.
{"the password is","mật khẩu là"}.
{"Thursday","Thứ Năm"}.
{"Time delay","Thời gian trì hoãn"}.
{"Time","Thời Gian"}.
{"To","Đến"}.
{"To ~s","Gửi đến ~s"}.
{"Traffic rate limit is exceeded","Quá giới hạn tỷ lệ lưu lượng truyền tải"}.
{"Transactions Aborted:","Giao Dịch Hủy Bỏ:"}.
{"Transactions Committed:","Giao Dịch Được Cam Kết:"}.
{"Transactions Logged:","Giao Dịch Được Ghi Nhận:"}.
{"Transactions Restarted:","Giao Dịch Khởi Động Lại:"}.
{"Tuesday","Thứ Ba"}.
{"Update","Cập Nhật"}.
{"Update message of the day (don't send)","Cập nhật thư trong ngày (không gửi)"}.
{"Update message of the day on all hosts (don't send)","Cập nhật thư trong ngày trên tất cả các máy chủ (không gửi)"}.
{"Update plan","Kế hoạch cập nhật"}.
{"Update script","Cập nhận lệnh"}.
{"Uptime:","Thời gian tải lên:"}.
{"Use of STARTTLS required","Yêu cầu sử dụng STARTTLS"}.
{"User Management","Quản Lý Người Sử Dụng"}.
{"User","Người sử dụng"}.
{"Users Last Activity","Hoạt Động Cuối Cùng Của Người Sử Dụng"}.
{"Users","Người sử dụng"}.
{"Validate","Xác nhận hợp lệ"}.
{"vCard User Search","Tìm Kiếm Người Sử Dụng vCard"}.
{"Virtual Hosts","Máy Chủ Ảo"}.
{"Visitors are not allowed to send messages to all occupants","Người ghé thăm không được phép gửi thư đến tất cả các người tham dự"}.
{"Wednesday","Thứ Tư"}.
{"When to send the last published item","Khi cần gửi mục được xuất bản cuối cùng"}.
{"Whether to allow subscriptions","Xác định nên cho phép đăng ký không"}.
{"You have been banned from this room","Bạn bị cấm tham gia phòng này"}.
{"You must fill in field \"Nickname\" in the form","Bạn phải điền thông tin vào ô \"Nickname\" trong biểu mẫu này"}.
{"You need an x:data capable client to configure mod_irc settings","Bạn cần có một trình ứng dụng khách hỗ trợ định dạng dữ liệu x: để xác định các thiết lập mod_irc"}.
{"You need an x:data capable client to configure room","Bạn cần có một trình ứng dụng khách hỗ trợ định dạng dữ liệu x: để xác định cấu hình phòng họp"}.
{"You need an x:data capable client to search","Bạn cần có một trình ứng dụng khách hỗ trợ định dạng dữ liệu x: để tìm kiếm"}.
{"Your contact offline message queue is full. The message has been discarded.","Danh sách chờ thư liên lạc ngoại tuyến của bạn đã đầy. Thư này đã bị loại bỏ."}.
