%% -*- coding: latin-1 -*-
{"Accept","Accepter"}.
{"Access Configuration","Apontiaedje des accès"}.
{"Access Control List Configuration","Apontiaedje des droets (ACL)"}.
{"Access control lists","Droets (ACL)"}.
{"Access Control Lists","Droets (ACL)"}.
{"Access denied by service policy","L' accès a stî rfuzé pal politike do siervice"}.
{"Access rules","Rîles d' accès"}.
{"Access Rules","Rîles d' accès"}.
{"Action on user","Accion so l' uzeu"}.
{"Add Jabber ID","Radjouter èn ID Jabber"}.
{"Add New","Radjouter"}.
{"Add User","Radjouter èn uzeu"}.
{"Administration","Manaedjaedje"}.
{"Administration of ","Manaedjaedje di "}.
{"Administrator privileges required","I fåt des priviledjes di manaedjeu"}.
{"A friendly name for the node","On no uzeu-ahessåve pol nuk"}.
{"All activity","Dispoy todi"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Permete ki ci Jabber ID ci si poye abouner a ç' nuk eplaidaedje-abounmint ci?"}.
{"Allow users to change the subject","Les uzeus polèt candjî l' tite"}.
{"Allow users to query other users","Les uzeus polèt cweri ls ôtes uzeus"}.
{"Allow users to send invites","Les uzeus polèt evoyî priyaedjes"}.
{"Allow users to send private messages","Les uzeus polèt evoyî des messaedjes privés"}.
{"Allow visitors to change nickname","Permete ki les viziteus candjexhe leus metous nos"}.
{"Allow visitors to send private messages to","Les uzeus polèt evoyî des messaedjes privés"}.
{"Allow visitors to send status text in presence updates","Permete ki les viziteus evoyexhe des tecse d' estat dins leus messaedjes di prezince"}.
{"Allow visitors to send voice requests","Les uzeus polèt evoyî des dmandes di vwès"}.
{"All Users","Tos les uzeus"}.
{"Announcements","Anonces"}.
{"anyone","tot l' minme kî"}.
{"A password is required to enter this room","I fåt dner on scret po poleur intrer dins cisse såle ci"}.
{"April","avri"}.
{"August","awousse"}.
{"Backup","Copeye di såvrité"}.
{"Backup Management","Manaedjaedje des copeyes di såvrité"}.
{"Backup of ~p","Copeye di såvrité po ~p"}.
{"Backup to File at ","Fé ene copeye di såvrité dins on fitchî so "}.
{"Bad format","Mwais fôrmat"}.
{"Birthday","Date d' askepiaedje"}.
{"CAPTCHA web page","Pådje web CAPTCHA"}.
{"Change Password","Candjî l' sicret"}.
{"Change User Password","Candjî l' sicret d' l' uzeu"}.
{"Characters not allowed:","Caracteres nén permetous:"}.
{"Chatroom configuration modified","L' apontiaedje del såle di berdelaedje a candjî"}.
{"Chatroom is created","Li såle di berdelaedje est ahivêye"}.
{"Chatroom is destroyed","Li såle di berdelaedje est distrûte"}.
{"Chatroom is started","Li såle di berdelaedje est enondêye"}.
{"Chatroom is stopped","Li såle di berdelaedje est ahotêye"}.
{"Chatrooms","Såles di berdelaedje"}.
{"Choose a username and password to register with this server","Tchoezixhoz on no d' uzeu eyet on scret po vs edjîstrer so ç' sierveu ci"}.
{"Choose modules to stop","Tchoezixhoz les modules a-z arester"}.
{"Choose storage type of tables","Tchoezi l' sôre di wårdaedje po les tåves"}.
{"Choose whether to approve this entity's subscription.","Tchoezi s' i fåt aprover ou nén l' abounmint di ciste intité."}.
{"City","Veye"}.
{"Commands","Comandes"}.
{"Conference room does not exist","Li såle di conferince n' egzistêye nén"}.
{"Configuration","Apontiaedjes"}.
{"Configuration of room ~s","Apontiaedje del såle ~s"}.
{"Connected Resources:","Raloyî avou les rsoûces:"}.
{"Connections parameters","Parametes des raloyaedjes"}.
{"Country","Payis"}.
{"CPU Time:","Tins CPU:"}.
{"Database","Båze di dnêyes"}.
{"Database Tables at ~p","Tåves del båze di dnêyes so ~p"}.
{"Database Tables Configuration at ","Apontiaedje des tåves del båze di dnêyes so "}.
{"December","decimbe"}.
{"Default users as participants","Les uzeus sont des pårticipants come prémetowe dujhance"}.
{"Delete message of the day","Disfacer l' messaedje do djoû"}.
{"Delete message of the day on all hosts","Disfacer l' messaedje do djoû so tos les lodjoes"}.
{"Delete Selected","Disfacer les elemints tchoezis"}.
{"Delete User","Disfacer èn uzeu"}.
{"Deliver event notifications","Evoyî des notifiaedjes d' evenmints"}.
{"Deliver payloads with event notifications","Evoyî l' contnou avou les notifiaedjes d' evenmints"}.
{"Description:","Discrijhaedje:"}.
{"Disc only copy","Copeye seulmint sol deure plake"}.
{"Displayed Groups:","Groupes håynés:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","Ni dnez vosse sicret a nolu, nén ddja ås manaedjeus do sierveu Jabber."}.
{"Dump Backup to Text File at ","Copeye di såvritè viè on fitchî tecse so "}.
{"Dump to Text File","Schaper en on fitchî tecse"}.
{"Edit Properties","Candjî les prôpietés"}.
{"Either approve or decline the voice request.","Aprover oudonbén rifuzer li dmande di vwès."}.
{"ejabberd IRC module","Module IRC po ejabberd"}.
{"ejabberd MUC module","Module MUC (såles di berdelaedje) po ejabberd"}.
{"ejabberd Multicast service","siervice multicast d' ejabberd"}.
{"ejabberd Publish-Subscribe module","Module d' eplaidaedje-abounmint po ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","Module SOCKS5 Bytestreams po ejabberd"}.
{"ejabberd vCard module","Module vCard ejabberd"}.
{"ejabberd Web Admin","Manaedjeu waibe ejabberd"}.
{"Elements","Elemints"}.
{"Email","Emile"}.
{"Empty Rooms","Såles vudes"}.
{"Enable logging","Mete en alaedje li djournå"}.
{"Enable message archiving","Mete en alaedje l' årtchivaedje des messaedjes"}.
{"Encoding for server ~b","Ecôdaedje pol sierveu ~b"}.
{"End User Session","Fini l' session d' l' uzeu"}.
{"Enter list of {Module, [Options]}","Dinez ene djivêye del cogne {Module, [Tchuzes]}"}.
{"Enter nickname you want to register","Dinez l' metou no ki vos vloz edjîstrer"}.
{"Enter path to backup file","Dinez l' tchimin viè l' fitchî copeye di såvrité"}.
{"Enter path to jabberd14 spool dir","Dinez l' tchimin viè l' ridant di spool jabberd14"}.
{"Enter path to jabberd14 spool file","Dinez l' tchimin viè l' fitchî di spool jabberd14"}.
{"Enter path to text file","Dinez l' tchimin viè l' fitchî tecse"}.
{"Enter the text you see","Tapez l' tecse ki vos voeyoz"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","Dinez les nos d' uzeu et ls ecôdaedjes ki vos vloz eployî po vs raloyî åzès sierveus IRC  Clitchîz so «Shuvant» po-z aveur di pus di tchamps a rimpli.  Clitchîz so «Fini» po schaper les apontiaedjes."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","Dinez l' no d' uzeu, les ecôdaedjes, les pôrts et les screts ki vos vloz eployî po vs raloyî åzès sierveus IRC"}.
{"Erlang Jabber Server","Sierveu Jabber Erlang"}.
{"Error","Aroke"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","Egzimpe: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","Esclure les IDs Jabber des kesses CAPTCHA"}.
{"Export all tables as SQL queries to a file:","Espoirter totes les tåves, come des cmandes SQL, viè on fitchî"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Espoirter les dnêyes di tos les uzeus do sierveu viè des fitchîs PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Espoirter les dnêyes di tos les uzeus do sierveu viè des fitchîs PIEFXIS (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","Nén moyén di rsaetchî on JID foû d' l' aprovaedje di vosse dimande di vwès"}.
{"Family Name","No d' famile"}.
{"February","fevrî"}.
{"Fill in fields to search for any matching Jabber User","Rimplixhoz les tchamps po cweri èn uzeu Jabber"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Rimplixhoz les tchamps do formulaire po cweri èn uzeu Jabber (radjouter «*» al fén do tchamp po cweri tot l' minme kéne fén d' tchinne"}.
{"Friday","vénrdi"}.
{"From","Di"}.
{"From ~s","Dispoy ~s"}.
{"Full Name","No etir"}.
{"Get Number of Online Users","Riçure li nombe d' uzeus raloyîs"}.
{"Get Number of Registered Users","Riçure li nombe d' uzeus edjîstrés"}.
{"Get User Last Login Time","Riçure li date/eure do dierin elodjaedje di l' uzeu"}.
{"Get User Password","Riçure sicret d' l' uzeu"}.
{"Get User Statistics","Riçure les statistikes di l' uzeu"}.
{"Grant voice to this person?","Permete li vwès po cisse djin ci?"}.
{"Group ","Groupe "}.
{"Groups","Groupes"}.
{"has been banned","a stî bani"}.
{"has been kicked","a stî pité evoye"}.
{"has been kicked because of an affiliation change","a stî pité evoye cåze d' on candjmint d' afiyaedje"}.
{"has been kicked because of a system shutdown","a stî pité evoye cåze d' èn arestaedje do sistinme"}.
{"has been kicked because the room has been changed to members-only","a stî pité evoye cåze ki l' såle a stî ristrindowe åzès mimbes seulmint"}.
{" has set the subject to: "," a candjî l' tite a: "}.
{"Host","Sierveu"}.
{"If you don't see the CAPTCHA image here, visit the web page.","Si vos n' voeyoz nole imådje CAPTCHA chal, vizitez l' pådje waibe."}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","Si vos vloz dner des pôrts, sicrets ou ecôdaedjes diferins po les sierveus IRC, rimplixhoz cisse djivêye ci avou des valixhances del cogne «{\"sierveu irc\", \"ecôdaedje\", pôrt, \"sicret\"}». Les prémetowès valixhances do siervice sont «~s» po l' ecôdaedje, «~p» pol pôrt, et on vude sicret."}.
{"Import Directory","Sititchî d' on ridant"}.
{"Import File","Sititchî d' on fitchî"}.
{"Import user data from jabberd14 spool file:","Sititchî des dnêyes uzeus foû d' on fitchî spoûle jabberd14:"}.
{"Import User from File at ","Sititchî uzeu d' on fitchî so "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Sititchî des dnêyes uzeus foû d' on fitchî PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Sititchî des dnêyes uzeus foû d' on ridant spoûle jabberd14:"}.
{"Import Users from Dir at ","Sitichî des uzeus d' on ridant so "}.
{"Import Users From jabberd14 Spool Files","Sititchî des uzeus Jabberd 1.4"}.
{"Improper message type","Sôre di messaedje nén valide"}.
{"Incoming s2s Connections:","Raloyaedjes s2s en intrêye:"}.
{"Incorrect password","Sicret nén corek"}.
{"Invalid affiliation: ~s","Afiyaedje nén valide: ~s"}.
{"Invalid role: ~s","Role nén valide: ~s"}.
{"IP addresses","Adresses IP"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","Canå IRC (èn nén mete li prumî #)"}.
{"IRC server","Sierveu IRC"}.
{"IRC settings","Apontiaedjes IRC"}.
{"IRC Transport","Transpoirt IRC"}.
{"IRC username","No d' uzeu IRC"}.
{"IRC Username","No d' uzeu IRC"}.
{"is now known as","est asteure kinoxhou come"}.
{"It is not allowed to send error messages to the room. The participant (~s) has sent an error message (~s) and got kicked from the room","On n' pout nén evoyî des messaedjes d' aroke sol såle. Li pårticipan (~s) a-st evoyî on messaedje d' aroke (~s) ey a stî tapé foû."}.
{"It is not allowed to send private messages","Ci n' est nén permetou d' evoyî des messaedjes privés"}.
{"It is not allowed to send private messages of type \"groupchat\"","C' est nén possibe d' evoyî des messaedjes privés del sôre «groupchat»"}.
{"It is not allowed to send private messages to the conference","On n' pout nén evoyî des messaedjes privés dins cisse conferince ci"}.
{"Jabber Account Registration","Edjîstraedje di conte Jabber"}.
{"Jabber ID","ID Jabber"}.
{"Jabber ID ~s is invalid","Li Jabber ID ~s n' est nén valide"}.
{"January","djanvî"}.
{"Join IRC channel","Radjonde canå IRC"}.
{"joins the room","arive sol såle"}.
{"Join the IRC channel here.","Radjonde li canå IRC droci."}.
{"Join the IRC channel in this Jabber ID: ~s","Radjonde li canå IRC e cist ID Jabber: ~s"}.
{"July","djulete"}.
{"June","djun"}.
{"Last Activity","Dierinne activité"}.
{"Last login","Dierin elodjaedje"}.
{"Last month","Dierin moes"}.
{"Last year","Dierinne anêye"}.
{"leaves the room","cwite li såle"}.
{"Listened Ports at ","Pôrts drovous so "}.
{"Listened Ports","Pôrts drovous"}.
{"List of modules to start","Djivêye di modules a-z enonder"}.
{"List of rooms","Djivêye des såles"}.
{"Low level update script","Sicripe di metaedje a djoû d' bas livea"}.
{"Make participants list public","Rinde publike li djivêye des pårticipants"}.
{"Make room CAPTCHA protected","Rinde li såle di berdelaedje protedjeye pa CAPTCHA"}.
{"Make room members-only","Rinde li såle di berdelaedje ristrindowe ås mimbes seulmint"}.
{"Make room moderated","Rinde li såle di berdelaedje moderêye"}.
{"Make room password protected","Rinde li såle di berdelaedje protedjeye pa scret"}.
{"Make room persistent","Rinde li såle permaninte"}.
{"Make room public searchable","Rinde li såle di berdelaedje cweråve publicmint"}.
{"March","måss"}.
{"Maximum Number of Occupants","Nombe macsimom di prezints"}.
{"Max # of items to persist","Nombe macsimoms di cayets permanints"}.
{"Max payload size in bytes","Contnou macsimom en octets"}.
{"May","may"}.
{"Membership is required to enter this room","I fåt esse mimbe po poleur intrer dins cisse såle ci"}.
{"Members:","Mimbes:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","Rimimbrez vosse sicret, ou scrijhoz l' so on papî ki vos wådroz en ene place bén a hoûte, ca avou Jabber i n' a pont moyén di rapexhî vosse sicret si vos l' rovyîz."}.
{"Memory","Memwere"}.
{"Message body","Coir do messaedje"}.
{"Middle Name","No do mitan"}.
{"Minimum interval between voice requests (in seconds)","Tins minimom etur deus dmandes di vwès (e segondes)"}.
{"Moderator","Moderateu"}.
{"Moderator privileges required","I fåt des priviledjes di moderateu"}.
{"moderators only","les moderateus seulmint"}.
{"Modified modules","Modules di candjîs"}.
{"Module","Module"}.
{"Modules at ~p","Modules so ~p"}.
{"Modules","Modules"}.
{"Monday","londi"}.
{"Multicast","Multicast"}.
{"Multi-User Chat","Berdelaedje a sacwants"}.
{"Name","No"}.
{"Name:","Pitit no:"}.
{"Never","Måy"}.
{"New Password:","Novea scret:"}.
{"Nickname","Metou no"}.
{"Nickname Registration at ","Edjîstraedje di metou no amon "}.
{"Nickname ~s does not exist in the room","Li metou no ~s n' egzistêye nén dins l' såle"}.
{"nobody","nolu"}.
{"No body provided for announce message","I n' a nou coir do messaedje po ciste anonce la"}.
{"No Data","Nole dinêye disponibe"}.
{"Node ID","ID d' nuk"}.
{"Node not found","Nuk nén trové"}.
{"Node ~p","Nuk ~p"}.
{"Nodes","Nuks"}.
{"No limit","Pont d' limite"}.
{"None","Nole"}.
{"No resource provided","Nole rissoûce di dnêye"}.
{"Not Found","Nén trové"}.
{"Notify subscribers when items are removed from the node","Notifyî åzès abounés cwand des cayets sont oisté foû do nuk"}.
{"Notify subscribers when the node configuration changes","Notifyî åzès abounés cwand l' apontiaedje do nuk candje"}.
{"Notify subscribers when the node is deleted","Notifyî åzès abounés cwand l' nuk est disfacé"}.
{"November","nôvimbe"}.
{"Number of occupants","Nombe di prezints"}.
{"Number of online users","Nombe d' uzeus raloyîs"}.
{"Number of registered users","Nombe d' uzeus edjîstrés"}.
{"October","octôbe"}.
{"Offline Messages:","Messaedjes ki ratindèt:"}.
{"Offline Messages","Messaedjes ki ratindèt"}.
{"OK","'l est bon"}.
{"Old Password:","Vî scret:"}.
{"Online","Raloyî"}.
{"Online Users:","Uzeus raloyîs:"}.
{"Online Users","Uzeus raloyîs"}.
{"Only deliver notifications to available users","Seulmint evoyî des notifiaedje åzès uzeus disponibes"}.
{"Only members may query archives of this room","Seulmint les mimbes polèt cweri les årtchives dins cisse såle ci"}.
{"Only moderators and participants are allowed to change the subject in this room","Seulmint les moderateus et les pårticipants polèt candjî l' sudjet dins cisse såle ci"}.
{"Only moderators are allowed to change the subject in this room","Seulmint les moderateus polèt candjî l' sudjet dins cisse såle ci"}.
{"Only moderators can approve voice requests","Seulmint les moderateus polèt aprover des dmandes di vwès"}.
{"Only occupants are allowed to send messages to the conference","Seulmint les prezints polèt evoyî des messaedjes al conferince"}.
{"Only occupants are allowed to send queries to the conference","Seulmint les prezints polèt evoyî des cweraedjes sol conferince"}.
{"Only service administrators are allowed to send service messages","Seulmint les manaedjeus d' siervices polèt evoyî des messaedjes di siervice"}.
{"Options","Tchuzes"}.
{"Organization Name","No d' l' organizåcion"}.
{"Organization Unit","Unité d' l' organizåcion"}.
{"Outgoing s2s Connections:","Raloyaedjes s2s e rexhowe:"}.
{"Outgoing s2s Connections","Raloyaedjes s2s e rexhowe"}.
{"Owner privileges required","I fåt des priviledjes di prôpietaire"}.
{"Packet","Paket"}.
{"Participant","Pårticipant"}.
{"Password ~b","Sicret ~b"}.
{"Password:","Sicret:"}.
{"Password","Sicret"}.
{"Password Verification:","Acertinaedje do scret:"}.
{"Password Verification","Acertinaedje do scret"}.
{"Path to Dir","Tchimin viè l' ridant"}.
{"Path to File","Tchimin viè l' fitchî"}.
{"Pending","Ratindant"}.
{"Period: ","Termene:"}.
{"Permanent rooms","Såles tofer la"}.
{"Persist items to storage","Cayets permanints a wårder"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Notez ki ces tchuzes la vont seulmint fé ene copeye di såvrité del båze di dnêyes Mnesia costrûte å dvins do programe. Si vos eployîz ene difoûtrinne båze di dnêyes avou l' module ODBC, vos dvoz fé ene copeye di såvrité del båze SQL da vosse sepårumint."}.
{"Please specify file name.","Dinez l' no do fitchî."}.
{"Please specify file size.","Dinez l' grandeu do fitchî."}.
{"Please, wait for a while before sending new voice request","Ratindez ene miete s' i vs plait divant d' rivoyî ene nouve dimande di vwès"}.
{"Pong","Pong"}.
{"Port ~b","Pôrt ~b"}.
{"Port","Pôrt"}.
{"Present real Jabber IDs to","Mostrer les vraiys Jabber IDs a"}.
{"private, ","privé, "}.
{"Protocol","Protocole"}.
{"Publish-Subscribe","Eplaidaedje-abounmint"}.
{"PubSub subscriber request","Dimande d' eplaidaedje-abounmint d' èn abouné"}.
{"Purge all items when the relevant publisher goes offline","Purdjî tos les cayets cwand l' eplaideu aloyî va foû raloyaedje"}.
{"Queries to the conference members are not allowed in this room","Les cweraedjes des mimbes del conferince ni sont nén permetous dins cisse såle ci"}.
{"RAM and disc copy","Copeye e memwere (RAM) et sol deure plake"}.
{"RAM copy","Copeye e memwere (RAM)"}.
{"Raw","Dinêyes brutes"}.
{"Really delete message of the day?","Voloz vs vormint disfacer l' messaedje do djoû?"}.
{"Recipient is not in the conference room","Li riçuveu n' est nén dins l' såle di conferince"}.
{"Register a Jabber account","Edjîstrer on conte Jabber"}.
{"Register","Edjîstrer"}.
{"Registered nicknames","Metous nos edjistrés"}.
{"Registered Users:","Uzeus edjistrés:"}.
{"Registered Users","Uzeus edjistrés"}.
{"Registration in mod_irc for ","Edjîstraedje dins mod_irc po "}.
{"Remote copy","Copeye å lon"}.
{"Remove All Offline Messages","Oister tos les messaedjes ki ratindèt"}.
{"Remove","Oister"}.
{"Remove User","Disfacer l' uzeu"}.
{"Replaced by new connection","Replaecî pa on novea raloyaedje"}.
{"Resources","Rissoûces"}.
{"Restart","Renonder"}.
{"Restart Service","Renonder siervice"}.
{"Restore Backup from File at ","Rapexhî dispoy li fitchî copeye di såvrité so "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Rapexhî l' copeye di såvrité binaire après l' renondaedje ki vént d' ejabberd (çoula prind moens d' memwere del fé insi):"}.
{"Restore binary backup immediately:","Rapexhî do côp foû d' ene copeye di såvrité binaire:"}.
{"Restore plain text backup immediately:","Rapexhî do côp foû d' ene copeye di såvrité tecse:"}.
{"Restore","Rapexhî"}.
{"Roles for which Presence is Broadcasted","Roles ki leu prezince est difuzêye"}.
{"Room Configuration","Apontiaedje del såle"}.
{"Room creation is denied by service policy","L' ahivaedje del såle est rfuzé pal politike do siervice"}.
{"Room description","Discrijhaedje del såle"}.
{"Room Occupants","Prezints el såle"}.
{"Room title","Tite del såle"}.
{"Roster","Djivêye des soçons"}.
{"Roster groups allowed to subscribe","Pårtaedjîs groupes di soçons k' on s' î pout abouner"}.
{"Roster of ","Djivêye des soçons da "}.
{"Roster size","Grandeu del djivêye des soçons"}.
{"RPC Call Error","Aroke di houcaedje RPC"}.
{"Running Nodes","Nuks en alaedje"}.
{"~s access rule configuration","Apontiaedje des rîles d' accès a ~s"}.
{"Saturday","semdi"}.
{"Script check","Acertinaedje do scripe"}.
{"Search Results for ","Rizultats do cweraedje po "}.
{"Search users in ","Cweri des uzeus dins "}.
{"Send announcement to all online users","Evoyî l' anonce a tos les uzeus raloyîs"}.
{"Send announcement to all online users on all hosts","Evoyî l' anonce a tos les uzeus raloyîs so tos les lodjoes"}.
{"Send announcement to all users","Evoyî l' anonce a tos les uzeus"}.
{"Send announcement to all users on all hosts","Evoyî l' anonce a tos les uzeus so tos les lodjoes"}.
{"September","setimbe"}.
{"Server ~b","Sierveu ~b"}.
{"Server:","Sierveu:"}.
{"Server","Sierveu"}.
{"Set message of the day and send to online users","Defini l' messaedje do djoû et l' evoyî åzès uzeus raloyîs"}.
{"Set message of the day on all hosts and send to online users","Defini l' messaedje do djoû so tos les lodjoes et l' evoyî åzès uzeus raloyîs"}.
{"Shared Roster Groups","Pårtaedjîs groupes ezès djivêyes di soçons"}.
{"Show Integral Table","Mostrer totå"}.
{"Show Ordinary Table","Mostrer crexhince"}.
{"Shut Down Service","Arester siervice"}.
{"~s invites you to the room ~s","~s vos preye sol såle ~s"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","Des cliyints Jabber k' i gn a polèt wårder vosse sicret sol copiutrece, mins vos n' duvrîz fé çoula ki sol copiutrece da vosse, po des råjhons di såvrité."}.
{"Specify the access model","Sipecifyî l' modele d' accès"}.
{"Specify the event message type","Sipecifyî l' sôre do messaedje d' evenmint"}.
{"Specify the publisher model","Dinez l' modele d' eplaideu"}.
{"~s's Offline Messages Queue","messaedjes ki ratindèt el cawêye po ~s"}.
{"Start","Enonder"}.
{"Start Modules at ","Renonder les modules so "}.
{"Start Modules","Enonder des modules"}.
{"Statistics of ~p","Sitatistikes di ~p"}.
{"Statistics","Sitatistikes"}.
{"Stop","Arester"}.
{"Stop Modules","Arester des modules"}.
{"Stop Modules at ","Arester les modules so "}.
{"Stopped Nodes","Nuks essoctés"}.
{"Storage Type","Sôre di wårdaedje"}.
{"Store binary backup:","Copeye di såvrité binaire:"}.
{"Store plain text backup:","Copeye di såvrité tecse:"}.
{"Subject","Sudjet"}.
{"Submit","Evoyî"}.
{"Submitted","Candjmints evoyîs"}.
{"Subscriber Address","Adresse di l' abouné"}.
{"Subscription","Abounmimnt"}.
{"Sunday","dimegne"}.
{"That nickname is already in use by another occupant","Li metou no est ddja eployî pa ene ôte sakî sol såle"}.
{"That nickname is registered by another person","Li metou no est ddja edjîstré pa ene ôte sakî"}.
{"The CAPTCHA is valid.","Li CAPTCHA est valide."}.
{"The CAPTCHA verification has failed","Li verifiaedje CAPTCHA a fwait berwete"}.
{"The collections with which a node is affiliated","Les ramexhnêyes k' on nuk est afiyî avou"}.
{"the password is","li scret est"}.
{"The password is too weak","li scret est trop flåw"}.
{"The password of your Jabber account was successfully changed.","Li scret do conte Jabber da vosse a stî candjî comifåt."}.
{"There was an error changing the password: ","Åk n' a nén stî tot candjant l' sicret: "}.
{"There was an error creating the account: ","Åk n' a nén stî tot ahivant l' conte: "}.
{"There was an error deleting the account: ","Åk n' a nén stî tot disfaçant l' conte: "}.
{"This IP address is blacklisted in ~s","Ciste adresse IP est so ene noere djivêye e ~s"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","Pont d' diferince etur les grandes et ptitès letes: «macbeth» est l' minme ki «MacBeth» ou co «Macbeth»"}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Cisse pådje permete d' ahiver on conte Jabber so ç' sierveu Jabber ci. Li JID (IDintifieu Jabber) da vosse serè del cogne: noduzeu@sierveu. Lijhoz atintivmint les instruccions po bén rimpli les tchamps."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Cisse pådje permete di disdjîstrer on conte Jabber so ç' sierveu ci."}.
{"Thursday","djudi"}.
{"Time","Date"}.
{"Time delay","Tårdjaedje"}.
{"Too many CAPTCHA requests","Pår trop di dmandes CAPTCHA"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","I gn a-st avou pår trop (~p) d' otintifiaedjes k' ont fwait berwete vinant di ciste adresse IP la (~s). L' adresse serè disblokêye a ~s UTC"}.
{"Too many unacked stanzas","Pår trop di messaedjes sins acertinaedje di rçuvaedje"}.
{"To","Po"}.
{"To ~s","Viè ~s"}.
{"Total rooms","Totå di såles"}.
{"Traffic rate limit is exceeded","Li limite pol volume di trafik a stî passêye"}.
{"Transactions Aborted:","Transaccions arestêyes:"}.
{"Transactions Committed:","Transaccions evoyeyes:"}.
{"Transactions Logged:","Transaccions wårdêyes e djournå:"}.
{"Transactions Restarted:","Transaccions renondêyes:"}.
{"Tuesday","mårdi"}.
{"Unable to generate a CAPTCHA","Nén moyén di djenerer on CAPTCHA"}.
{"Unauthorized","Nén otorijhî"}.
{"Unregister a Jabber account","Disdjîstrer on conte Jabber"}.
{"Unregister","Disdjîstrer"}.
{"Update message of the day (don't send)","Mete a djoû l' messaedje do djoû (nén l' evoyî)"}.
{"Update message of the day on all hosts (don't send)","Mete a djoû l' messaedje do djoû so tos les lodjoes (nén l' evoyî)"}.
{"Update","Mete a djoû"}.
{"Update plan","Plan d' metaedje a djoû"}.
{"Update ~p","Metaedje a djoû di ~p"}.
{"Update script","Sicripe di metaedje a djoû"}.
{"Uptime:","Tins dispoy l' enondaedje:"}.
{"Use of STARTTLS required","L' eployaedje di STARTTL est oblidjî"}.
{"User JID","JID d' l' uzeu"}.
{"User Management","Manaedjaedje des uzeus"}.
{"Username:","No d' uzeu:"}.
{"Users are not allowed to register accounts so quickly","Les noveas uzeus n' si polèt nén edjîstrer si raddimint"}.
{"Users Last Activity","Dierinne activité des uzeus"}.
{"User ~s","Uzeu ~s"}.
{"Users","Uzeus"}.
{"User","Uzeu"}.
{"Validate","Valider"}.
{"vCard User Search","Calpin des uzeus"}.
{"Virtual Hosts","Forveyous sierveus"}.
{"Visitors are not allowed to change their nicknames in this room","Les viziteus èn polèt nén candjî leus metous no po ç' såle ci"}.
{"Visitors are not allowed to send messages to all occupants","Les viziteus n' polèt nén evoyî des messaedjes a tos les prezints"}.
{"Visitor","Viziteu"}.
{"Voice request","Dimande di vwès"}.
{"Voice requests are disabled in this conference","Les dmandes di vwès sont dismetowes e cisse conferince ci"}.
{"Wednesday","mierkidi"}.
{"When to send the last published item","Cwand evoyî l' dierin cayet eplaidî"}.
{"Whether to allow subscriptions","Si on permete les abounmints"}.
{"You can later change your password using a Jabber client.","Vos ploz candjî vosse sicret pus tård avou on cliyint Jabber."}.
{"You have been banned from this room","Vos avoz stî bani di cisse såle ci"}.
{"You must fill in field \"Nickname\" in the form","Vos dvoz rimpli l' tchamp «Metou no» dins l' formiulaire"}.
{"You need a client that supports x:data and CAPTCHA to register","Vos avoz mezåjhe d' on cliyint ki sopoite x:data eyet CAPTCHA po vs edjîstrer"}.
{"You need a client that supports x:data to register the nickname","Vos avoz mezåjhe d' on cliyint ki sopoite x:data po-z edjîstrer l' metou no"}.
{"You need an x:data capable client to configure mod_irc settings","Vos avoz mezåjhe d' on cliyint ki sopoite x:data po candjî ls apontiaedjes di mod_irc"}.
{"You need an x:data capable client to configure room","I vs fåt on cliyint ki sopoite x:data por vos poleur apontyî l' såle"}.
{"You need an x:data capable client to search","Vos avoz mezåjhe d' on cliyint ki sopoite x:data po fé on cweraedje"}.
{"Your active privacy list has denied the routing of this stanza.","Vosse djivêye di privaceye active a rfuzé l' evoyaedje di ç' messaedje ci."}.
{"Your contact offline message queue is full. The message has been discarded.","Li cawêye di messaedjes e môde disraloyî di vosse soçon est plinne. Li messaedje a stî tapé å diale."}.
{"Your Jabber account was successfully created.","Li conte Jabber da vosse a stî ahivé comifåt."}.
{"Your Jabber account was successfully deleted.","Li conte Jabber da vosse a stî disfacé comifåt."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Vos messaedjes po ~s sont blokés. Po les disbloker, alez vey ~s"}.
