%% -*- coding: latin-1 -*-
{"Access Configuration","Apontiaedje des accès"}.
{"Access Control List Configuration","Apontiaedje des droets (ACL)"}.
{"Access control lists","Droets (ACL)"}.
{"Access Control Lists","Droets (ACL)"}.
{"Access denied by service policy","L' accès a stî rfuzé pal politike do siervice"}.
{"Access rules","Rîles d' accès"}.
{"Access Rules","Rîles d' accès"}.
{"Action on user","Accion so l' uzeu"}.
{"Add Jabber ID","Radjouter èn ID Jabber"}.
{"Add New","Radjouter"}.
{"Add User","Radjouter èn uzeu"}.
{"Administration","Manaedjaedje"}.
{"Administration of ","Manaedjaedje di "}.
{"Administrator privileges required","I fåt des priviledjes di manaedjeu"}.
{"A friendly name for the node","On no uzeu-ahessåve pol nuk"}.
{"All activity","Dispoy todi"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Permete ki ci Jabber ID ci si poye abouner a ç' nuk eplaidaedje-abounmint ci?"}.
{"Allow users to query other users","Les uzeus polèt cweri ls ôtes uzeus"}.
{"Allow users to send invites","Les uzeus polèt evoyî priyaedjes"}.
{"Allow users to send private messages","Les uzeus polèt evoyî des messaedjes privés"}.
{"Allow visitors to change nickname","Permete ki les viziteus candjexhe leus metous nos"}.
{"Allow visitors to send status text in presence updates","Permete ki les viziteus evoyexhe des tecse d' estat dins leus messaedjes di prezince"}.
{"All Users","Tos les uzeus"}.
{"Announcements","Anonces"}.
{"anyone","tot l' minme kî"}.
{"April","avri"}.
{"August","awousse"}.
{"Backup","Copeye di såvrité"}.
{"Backup Management","Manaedjaedje des copeyes di såvrité"}.
{"Backup to File at ","Fé ene copeye di såvrité dins on fitchî so "}.
{"Bad format","Mwais fôrmat"}.
{"Birthday","Date d' askepiaedje"}.
{"Change Password","Candjî l' sicret"}.
{"Change User Password","Candjî l' sicret d' l' uzeu"}.
{"Chatroom configuration modified","L' apontiaedje del såle di berdelaedje a candjî"}.
{"Chatrooms","Såles di berdelaedje"}.
{"Choose a username and password to register with this server","Tchoezixhoz on no d' uzeu eyet on scret po vs edjîstrer so ç' sierveu ci"}.
{"Choose modules to stop","Tchoezixhoz les modules a-z arester"}.
{"Choose storage type of tables","Tchoezi l' sôre di wårdaedje po les tåves"}.
{"Choose whether to approve this entity's subscription.","Tchoezi s' i fåt aprover ou nén l' abounmint di ciste intité."}.
{"City","Veye"}.
{"Commands","Comandes"}.
{"Conference room does not exist","Li såle di conferince n' egzistêye nén"}.
{"Configuration","Apontiaedjes"}.
{"Connected Resources:","Raloyî avou les rsoûces:"}.
{"Country","Payis"}.
{"CPU Time:","Tins CPU:"}.
{"Database","Båze di dnêyes"}.
{"Database Tables Configuration at ","Apontiaedje des tåves del båze di dnêyes so "}.
{"December","decimbe"}.
{"Default users as participants","Les uzeus sont des pårticipants come prémetowe dujhance"}.
{"Delete message of the day","Disfacer l' messaedje do djoû"}.
{"Delete message of the day on all hosts","Disfacer l' messaedje do djoû so tos les lodjoes"}.
{"Delete Selected","Disfacer les elemints tchoezis"}.
{"Delete User","Disfacer èn uzeu"}.
{"Deliver event notifications","Evoyî des notifiaedjes d' evenmints"}.
{"Deliver payloads with event notifications","Evoyî l' contnou avou les notifiaedjes d' evenmints"}.
{"Description:","Discrijhaedje:"}.
{"Disc only copy","Copeye seulmint sol deure plake"}.
{"Displayed Groups:","Groupes håynés:"}.
{"Dump Backup to Text File at ","Copeye di såvritè viè on fitchî tecse so "}.
{"Dump to Text File","Schaper en on fitchî tecse"}.
{"Edit Properties","Candjî les prôpietés"}.
{"ejabberd IRC module","Module IRC po ejabberd"}.
{"ejabberd MUC module","Module MUC (såles di berdelaedje) po ejabberd"}.
{"ejabberd Publish-Subscribe module","Module d' eplaidaedje-abounmint po ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","Module SOCKS5 Bytestreams po ejabberd"}.
{"ejabberd vCard module","Module vCard ejabberd"}.
{"ejabberd Web Admin","Manaedjeu waibe ejabberd"}.
{"Email","Emile"}.
{"Enable logging","Mete en alaedje li djournå"}.
{"End User Session","Fini l' session d' l' uzeu"}.
{"Enter list of {Module, [Options]}","Dinez ene djivêye del cogne {Module, [Tchuzes]}"}.
{"Enter nickname you want to register","Dinez l' metou no ki vos vloz edjîstrer"}.
{"Enter path to backup file","Dinez l' tchimin viè l' fitchî copeye di såvrité"}.
{"Enter path to jabberd14 spool dir","Dinez l' tchimin viè l' ridant di spool jabberd14"}.
{"Enter path to jabberd14 spool file","Dinez l' tchimin viè l' fitchî di spool jabberd14"}.
{"Enter path to text file","Dinez l' tchimin viè l' fitchî tecse"}.
{"Erlang Jabber Server","Sierveu Jabber Erlang"}.
{"Family Name","No d' famile"}.
{"February","fevrî"}.
{"Fill in fields to search for any matching Jabber User","Rimplixhoz les tchamps po cweri èn uzeu Jabber"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Rimplixhoz les tchamps do formulaire po cweri èn uzeu Jabber (radjouter «*» al fén do tchamp po cweri tot l' minme kéne fén d' tchinne"}.
{"Friday","vénrdi"}.
{"From","Di"}.
{"From ~s","Dispoy ~s"}.
{"Full Name","No etir"}.
{"Get Number of Online Users","Riçure li nombe d' uzeus raloyîs"}.
{"Get Number of Registered Users","Riçure li nombe d' uzeus edjîstrés"}.
{"Get User Last Login Time","Riçure li date/eure do dierin elodjaedje di l' uzeu"}.
{"Get User Password","Riçure sicret d' l' uzeu"}.
{"Get User Statistics","Riçure les statistikes di l' uzeu"}.
{"Group ","Groupe "}.
{"Groups","Groupes"}.
{"has been banned","a stî bani"}.
{"has been kicked","a stî pité evoye"}.
{"has been kicked because of an affiliation change","a stî pité evoye cåze d' on candjmint d' afiyaedje"}.
{"has been kicked because of a system shutdown","a stî pité evoye cåze d' èn arestaedje do sistinme"}.
{"has been kicked because the room has been changed to members-only","a stî pité evoye cåze ki l' såle a stî ristrindowe åzès mimbes seulmint"}.
{" has set the subject to: "," a candjî l' tite a: "}.
{"Host","Sierveu"}.
{"Import Directory","Sititchî d' on ridant"}.
{"Import File","Sititchî d' on fitchî"}.
{"Import User from File at ","Sititchî uzeu d' on fitchî so "}.
{"Import Users from Dir at ","Sitichî des uzeus d' on ridant so "}.
{"Import Users From jabberd14 Spool Files","Sititchî des uzeus Jabberd 1.4"}.
{"Improper message type","Sôre di messaedje nén valide"}.
{"Incorrect password","Sicret nén corek"}.
{"Invalid affiliation: ~s","Afiyaedje nén valide: ~s"}.
{"Invalid role: ~s","Role nén valide: ~s"}.
{"IP addresses","Adresses IP"}.
{"IRC Transport","Transpoirt IRC"}.
{"IRC Username","No d' uzeu IRC"}.
{"is now known as","est asteure kinoxhou come"}.
{"It is not allowed to send private messages","Ci n' est nén permetou d' evoyî des messaedjes privés"}.
{"It is not allowed to send private messages of type \"groupchat\"","C' est nén possibe d' evoyî des messaedjes privés del sôre «groupchat»"}.
{"It is not allowed to send private messages to the conference","On n' pout nén evoyî des messaedjes privés dins cisse conferince ci"}.
{"Jabber ID","ID Jabber"}.
{"Jabber ID ~s is invalid","Li Jabber ID ~s n' est nén valide"}.
{"January","djanvî"}.
{"joins the room","arive sol såle"}.
{"July","djulete"}.
{"June","djun"}.
{"Last Activity","Dierinne activité"}.
{"Last login","Dierin elodjaedje"}.
{"Last month","Dierin moes"}.
{"Last year","Dierinne anêye"}.
{"leaves the room","cwite li såle"}.
{"Listened Ports at ","Pôrts drovous so "}.
{"Listened Ports","Pôrts drovous"}.
{"List of modules to start","Djivêye di modules a-z enonder"}.
{"Low level update script","Sicripe di metaedje a djoû d' bas livea"}.
{"Make participants list public","Rinde publike li djivêye des pårticipants"}.
{"Make room members-only","Rinde li såle di berdelaedje ristrindowe ås mimbes seulmint"}.
{"Make room moderated","Rinde li såle di berdelaedje moderêye"}.
{"Make room password protected","Rinde li såle di berdelaedje protedjeye pa scret"}.
{"Make room persistent","Rinde li såle permaninte"}.
{"Make room public searchable","Rinde li såle di berdelaedje cweråve publicmint"}.
{"March","måss"}.
{"Maximum Number of Occupants","Nombe macsimom di prezints"}.
{"Max # of items to persist","Nombe macsimoms di cayets permanints"}.
{"Max payload size in bytes","Contnou macsimom en octets"}.
{"May","may"}.
{"Members:","Mimbes:"}.
{"Memory","Memwere"}.
{"Message body","Coir do messaedje"}.
{"Middle Name","No do mitan"}.
{"Moderator privileges required","I fåt des priviledjes di moderateu"}.
{"moderators only","les moderateus seulmint"}.
{"Module","Module"}.
{"Modules","Modules"}.
{"Monday","londi"}.
{"Name","No"}.
{"Name:","Pitit no:"}.
{"Never","Måy"}.
{"Nickname","Metou no"}.
{"Nickname Registration at ","Edjîstraedje di metou no amon "}.
{"Nickname ~s does not exist in the room","Li metou no ~s n' egzistêye nén dins l' såle"}.
{"No body provided for announce message","I n' a nou coir do messaedje po ciste anonce la"}.
{"No Data","Nole dinêye disponibe"}.
{"Node ID","ID d' nuk"}.
{"Node not found","Nuk nén trové"}.
{"Nodes","Nuks"}.
{"No limit","Pont d' limite"}.
{"None","Nole"}.
{"No resource provided","Nole rissoûce di dnêye"}.
{"Notify subscribers when items are removed from the node","Notifyî åzès abounés cwand des cayets sont oisté foû do nuk"}.
{"Notify subscribers when the node configuration changes","Notifyî åzès abounés cwand l' apontiaedje do nuk candje"}.
{"Notify subscribers when the node is deleted","Notifyî åzès abounés cwand l' nuk est disfacé"}.
{"November","nôvimbe"}.
{"Number of occupants","Nombe di prezints"}.
{"Number of online users","Nombe d' uzeus raloyîs"}.
{"Number of registered users","Nombe d' uzeus edjîstrés"}.
{"October","octôbe"}.
{"Offline Messages:","Messaedjes ki ratindèt:"}.
{"Offline Messages","Messaedjes ki ratindèt"}.
{"OK","'l est bon"}.
{"Online","Raloyî"}.
{"Online Users:","Uzeus raloyîs:"}.
{"Online Users","Uzeus raloyîs"}.
{"Only deliver notifications to available users","Seulmint evoyî des notifiaedje åzès uzeus disponibes"}.
{"Only occupants are allowed to send messages to the conference","Seulmint les prezints polèt evoyî des messaedjes al conferince"}.
{"Only occupants are allowed to send queries to the conference","Seulmint les prezints polèt evoyî des cweraedjes sol conferince"}.
{"Only service administrators are allowed to send service messages","Seulmint les manaedjeus d' siervices polèt evoyî des messaedjes di siervice"}.
{"Options","Tchuzes"}.
{"Organization Name","No d' l' organizåcion"}.
{"Organization Unit","Unité d' l' organizåcion"}.
{"Outgoing s2s Connections:","Raloyaedjes s2s e rexhowe:"}.
{"Outgoing s2s Connections","Raloyaedjes s2s e rexhowe"}.
{"Owner privileges required","I fåt des priviledjes di prôpietaire"}.
{"Packet","Paket"}.
{"Password:","Sicret:"}.
{"Password","Sicret"}.
{"Password Verification","Acertinaedje do scret"}.
{"Path to Dir","Tchimin viè l' ridant"}.
{"Path to File","Tchimin viè l' fitchî"}.
{"Pending","Ratindant"}.
{"Period: ","Termene:"}.
{"Persist items to storage","Cayets permanints a wårder"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","Pôrt"}.
{"Present real Jabber IDs to","Mostrer les vraiys Jabber IDs a"}.
{"private, ","privé, "}.
{"Publish-Subscribe","Eplaidaedje-abounmint"}.
{"PubSub subscriber request","Dimande d' eplaidaedje-abounmint d' èn abouné"}.
{"Queries to the conference members are not allowed in this room","Les cweraedjes des mimbes del conferince ni sont nén permetous dins cisse såle ci"}.
{"RAM and disc copy","Copeye e memwere (RAM) et sol deure plake"}.
{"RAM copy","Copeye e memwere (RAM)"}.
{"Raw","Dinêyes brutes"}.
{"Really delete message of the day?","Voloz vs vormint disfacer l' messaedje do djoû?"}.
{"Recipient is not in the conference room","Li riçuveu n' est nén dins l' såle di conferince"}.
{"Registered Users:","Uzeus edjistrés:"}.
{"Registered Users","Uzeus edjistrés"}.
{"Registration in mod_irc for ","Edjîstraedje dins mod_irc po "}.
{"Remote copy","Copeye å lon"}.
{"Remove","Oister"}.
{"Remove User","Disfacer l' uzeu"}.
{"Replaced by new connection","Replaecî pa on novea raloyaedje"}.
{"Resources","Rissoûces"}.
{"Restart","Renonder"}.
{"Restart Service","Renonder siervice"}.
{"Restore Backup from File at ","Rapexhî dispoy li fitchî copeye di såvrité so "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Rapexhî l' copeye di såvrité binaire après l' renondaedje ki vént d' ejabberd (çoula prind moens d' memwere del fé insi):"}.
{"Restore binary backup immediately:","Rapexhî do côp foû d' ene copeye di såvrité binaire:"}.
{"Restore plain text backup immediately:","Rapexhî do côp foû d' ene copeye di såvrité tecse:"}.
{"Restore","Rapexhî"}.
{"Room Configuration","Apontiaedje del såle"}.
{"Room creation is denied by service policy","L' ahivaedje del såle est rfuzé pal politike do siervice"}.
{"Room title","Tite del såle"}.
{"Roster","Djivêye des soçons"}.
{"Roster groups allowed to subscribe","Pårtaedjîs groupes di soçons k' on s' î pout abouner"}.
{"Roster of ","Djivêye des soçons da "}.
{"Roster size","Grandeu del djivêye des soçons"}.
{"RPC Call Error","Aroke di houcaedje RPC"}.
{"Running Nodes","Nuks en alaedje"}.
{"~s access rule configuration","Apontiaedje des rîles d' accès a ~s"}.
{"Saturday","semdi"}.
{"Script check","Acertinaedje do scripe"}.
{"Search Results for ","Rizultats do cweraedje po "}.
{"Search users in ","Cweri des uzeus dins "}.
{"Send announcement to all online users","Evoyî l' anonce a tos les uzeus raloyîs"}.
{"Send announcement to all online users on all hosts","Evoyî l' anonce a tos les uzeus raloyîs so tos les lodjoes"}.
{"Send announcement to all users","Evoyî l' anonce a tos les uzeus"}.
{"Send announcement to all users on all hosts","Evoyî l' anonce a tos les uzeus so tos les lodjoes"}.
{"September","setimbe"}.
{"Set message of the day and send to online users","Defini l' messaedje do djoû et l' evoyî åzès uzeus raloyîs"}.
{"Set message of the day on all hosts and send to online users","Defini l' messaedje do djoû so tos les lodjoes et l' evoyî åzès uzeus raloyîs"}.
{"Shared Roster Groups","Pårtaedjîs groupes ezès djivêyes di soçons"}.
{"Show Integral Table","Mostrer totå"}.
{"Show Ordinary Table","Mostrer crexhince"}.
{"Shut Down Service","Arester siervice"}.
{"~s invites you to the room ~s","~s vos preye sol såle ~s"}.
{"Specify the access model","Sipecifyî l' modele d' accès"}.
{"Specify the publisher model","Dinez l' modele d' eplaideu"}.
{"~s's Offline Messages Queue","messaedjes ki ratindèt el cawêye po ~s"}.
{"Start","Enonder"}.
{"Start Modules at ","Renonder les modules so "}.
{"Start Modules","Enonder des modules"}.
{"Statistics of ~p","Sitatistikes di ~p"}.
{"Statistics","Sitatistikes"}.
{"Stop","Arester"}.
{"Stop Modules","Arester des modules"}.
{"Stop Modules at ","Arester les modules so "}.
{"Stopped Nodes","Nuks essoctés"}.
{"Storage Type","Sôre di wårdaedje"}.
{"Store binary backup:","Copeye di såvrité binaire:"}.
{"Store plain text backup:","Copeye di såvrité tecse:"}.
{"Subject","Sudjet"}.
{"Submit","Evoyî"}.
{"Submitted","Candjmints evoyîs"}.
{"Subscriber Address","Adresse di l' abouné"}.
{"Subscription","Abounmimnt"}.
{"Sunday","dimegne"}.
{"the password is","li scret est"}.
{"Thursday","djudi"}.
{"Time","Date"}.
{"Time delay","Tårdjaedje"}.
{"To","Po"}.
{"To ~s","Viè ~s"}.
{"Traffic rate limit is exceeded","Li limite pol volume di trafik a stî passêye"}.
{"Transactions Aborted:","Transaccions arestêyes:"}.
{"Transactions Committed:","Transaccions evoyeyes:"}.
{"Transactions Logged:","Transaccions wårdêyes e djournå:"}.
{"Transactions Restarted:","Transaccions renondêyes:"}.
{"Tuesday","mårdi"}.
{"Update message of the day (don't send)","Mete a djoû l' messaedje do djoû (nén l' evoyî)"}.
{"Update message of the day on all hosts (don't send)","Mete a djoû l' messaedje do djoû so tos les lodjoes (nén l' evoyî)"}.
{"Update","Mete a djoû"}.
{"Update plan","Plan d' metaedje a djoû"}.
{"Update script","Sicripe di metaedje a djoû"}.
{"Uptime:","Tins dispoy l' enondaedje:"}.
{"Use of STARTTLS required","L' eployaedje di STARTTL est oblidjî"}.
{"User Management","Manaedjaedje des uzeus"}.
{"Users Last Activity","Dierinne activité des uzeus"}.
{"Users","Uzeus"}.
{"User","Uzeu"}.
{"Validate","Valider"}.
{"vCard User Search","Calpin des uzeus"}.
{"Virtual Hosts","Forveyous sierveus"}.
{"Visitors are not allowed to change their nicknames in this room","Les viziteus èn polèt nén candjî leus metous no po ç' såle ci"}.
{"Visitors are not allowed to send messages to all occupants","Les viziteus n' polèt nén evoyî des messaedjes a tos les prezints"}.
{"Wednesday","mierkidi"}.
{"When to send the last published item","Cwand evoyî l' dierin cayet eplaidî"}.
{"Whether to allow subscriptions","Si on permete les abounmints"}.
{"You have been banned from this room","Vos avoz stî bani di cisse såle ci"}.
{"You must fill in field \"Nickname\" in the form","Vos dvoz rimpli l' tchamp «Metou no» dins l' formiulaire"}.
{"You need an x:data capable client to configure mod_irc settings","Vos avoz mezåjhe d' on cliyint ki sopoite x:data po candjî ls apontiaedjes di mod_irc"}.
{"You need an x:data capable client to configure room","I vs fåt on cliyint ki sopoite x:data por vos poleur apontyî l' såle"}.
{"You need an x:data capable client to search","Vos avoz mezåjhe d' on cliyint ki sopoite x:data po fé on cweraedje"}.
{"Your contact offline message queue is full. The message has been discarded.","Li cawêye di messaedjes e môde disraloyî di vosse soçon est plinne. Li messaedje a stî tapé å diale."}.
