%% -*- coding: latin-1 -*-
{"Accept","接受"}.
{"Access Configuration","访问配置"}.
{"Access Control List Configuration","访问控制列表(ACL)配置"}.
{"Access control lists","访问控制列表(ACL)"}.
{"Access Control Lists","访问控制列表(ACL)"}.
{"Access denied by service policy","访问被服务策略拒绝"}.
{"Access rules","访问规则"}.
{"Access Rules","访问规则"}.
{"Action on user","对用户的动作"}.
{"Add Jabber ID","添加Jabber ID"}.
{"Add New","添加新用户"}.
{"Add User","添加用户"}.
{"Administration of ","管理"}.
{"Administration","管理"}.
{"Administrator privileges required","需要管理员权限"}.
{"A friendly name for the node","该节点的友好名称"}.
{"All activity","所有活动"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","允许该Jabber ID订阅该pubsub节点?"}.
{"Allow users to change the subject","允许用户更改主题"}.
{"Allow users to query other users","允许用户查询其它用户"}.
{"Allow users to send invites","允许用户发送邀请"}.
{"Allow users to send private messages","允许用户发送私聊消息"}.
{"Allow visitors to change nickname","允许用户更改昵称"}.
{"Allow visitors to send private messages to","允许访客发送私聊消息至"}.
{"Allow visitors to send status text in presence updates","更新在线状态时允许用户发送状态文本"}.
{"Allow visitors to send voice requests","允许访客发送声音请求"}.
{"All Users","所有用户"}.
{"Announcements","通知"}.
{"anyone","任何人"}.
{"A password is required to enter this room","进入此房间需要密码"}.
{"April","四月"}.
{"August","八月"}.
{"Backup Management","备份管理"}.
{"Backup of ~p","~p的备份"}.
{"Backup to File at ","备份文件位于"}.
{"Backup","备份"}.
{"Bad format","格式错误"}.
{"Birthday","出生日期"}.
{"CAPTCHA web page","验证码网页"}.
{"Change Password","更改密码"}.
{"Change User Password","更改用户密码"}.
{"Characters not allowed:","禁用字符:"}.
{"Chatroom configuration modified","聊天室配置已修改"}.
{"Chatroom is created","聊天室已被创建"}.
{"Chatroom is destroyed","聊天室已被销毁"}.
{"Chatroom is started","聊天室已被启动"}.
{"Chatroom is stopped","聊天室已被停用"}.
{"Chatrooms","聊天室"}.
{"Choose a username and password to register with this server","请选择在此服务器上注册所需的用户名和密码"}.
{"Choose modules to stop","请选择要停止的模块"}.
{"Choose storage type of tables","请选择表格的存储类型"}.
{"Choose whether to approve this entity's subscription.","选择是否允许该实体的订阅"}.
{"City","城市"}.
{"Commands","命令"}.
{"Conference room does not exist","会议室不存在"}.
{"Configuration of room ~s","房间~s的配置 "}.
{"Configuration","配置"}.
{"Connected Resources:","已连接资源:"}.
{"Connections parameters","连接参数"}.
{"Country","国家"}.
{"CPU Time:","CPU时间："}.
{"Database Tables at ~p","位于~p的数据库表"}.
{"Database Tables Configuration at ","数据库表格配置位于"}.
{"Database","数据库"}.
{"December","十二月"}.
{"Default users as participants","用户默认被视为参与人"}.
{"Delete message of the day on all hosts","删除所有主机上的每日消息"}.
{"Delete message of the day","删除每日消息"}.
{"Delete Selected","删除已选内容"}.
{"Delete User","删除用户"}.
{"Deliver event notifications","传递事件通知"}.
{"Deliver payloads with event notifications","用事件通告传输有效负载"}.
{"Description:","描述:"}.
{"Disc only copy","仅磁盘复制"}.
{"Displayed Groups:","已显示的组:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","不要将密码告诉任何人, 就算是Jabber服务器的管理员也不可以."}.
{"Dump Backup to Text File at ","转储备份到文本文件于"}.
{"Dump to Text File","转储到文本文件"}.
{"Edit Properties","编辑属性"}.
{"Either approve or decline the voice request.","接受或拒绝声音请求"}.
{"ejabberd IRC module","ejabberd IRC 模块"}.
{"ejabberd MUC module","ejabberd MUC 模块"}.
{"ejabberd Multicast service","ejabberd多重映射服务"}.
{"ejabberd Publish-Subscribe module","ejabberd 发行-订阅模块"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 字节流模块"}.
{"ejabberd vCard module","ejabberd vCard模块"}.
{"ejabberd Web Admin","ejabberd网页管理"}.
{"Elements","元素"}.
{"Email","电子邮件"}.
{"Empty Rooms","空房间"}.
{"Enable logging","启用服务器端聊天记录"}.
{"Enable message archiving","启用消息归档"}.
{"Encoding for server ~b","服务器~b的编码"}.
{"End User Session","结束用户会话"}.
{"Enter list of {Module, [Options]}","请输入{模块, [选项]}列表"}.
{"Enter nickname you want to register","请输入您想要注册的昵称"}.
{"Enter path to backup file","请输入备份文件的路径"}.
{"Enter path to jabberd14 spool dir","请输入jabberd14 spool目录的路径"}.
{"Enter path to jabberd14 spool file","请输入 jabberd14 spool 文件的路径"}.
{"Enter path to text file","请输入文本文件的路径"}.
{"Enter the text you see","请输入您所看到的文本"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","请输入您想使用的用来连接到 IRC 服务器的用户名和编码. 按 '下一步' 获取更多待填字段. 按 '完成' 保存设置."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","请输入您想使用的用来连接到IRC服务器的用户名, 编码, 端口和密码."}.
{"Erlang Jabber Server","Erlang Jabber服务器"}.
{"Error","错误"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","例如: [{\"irc.lucky.net\", \"koi8-r\"}, 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","从验证码挑战中排除Jabber ID"}.
{"Export all tables as SQL queries to a file:","将所有表以SQL查询语句导出到文件:"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","将服务器上所有用户的数据导出到 PIEFXIS 文件 (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","将某主机的用户数据导出到 PIEFXIS 文件 (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","无法从你的声音请求确认信息中提取JID"}.
{"Family Name","姓氏"}.
{"February","二月"}.
{"Fill in fields to search for any matching Jabber User","填充字段以搜索任何匹配的Jabber用户"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","填充表单以搜索任何匹配的Jabber用户(在字段末添加*来匹配子串)"}.
{"Friday","星期五"}.
{"From ~s","来自~s"}.
{"From","从"}.
{"Full Name","全名"}.
{"Get Number of Online Users","获取在线用户数"}.
{"Get Number of Registered Users","获取注册用户数"}.
{"Get User Last Login Time","获取用户上次登陆时间"}.
{"Get User Password","获取用户密码"}.
{"Get User Statistics","获取用户统计"}.
{"Grant voice to this person?","为此人授权声音?"}.
{"Groups","组"}.
{"Group ","组"}.
{"has been banned","已被禁止"}.
{"has been kicked because of an affiliation change","因联属关系改变而被踢出"}.
{"has been kicked because of a system shutdown","因系统关机而被踢出"}.
{"has been kicked because the room has been changed to members-only","因该房间改为只对会员开放而被踢出"}.
{"has been kicked","已被踢出"}.
{" has set the subject to: ","已将标题设置为: "}.
{"Host","主机"}.
{"If you don't see the CAPTCHA image here, visit the web page.","如果您在这里没有看到验证码图片, 请访问网页."}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","如果您想为 IRC 服务器指定不同的端口, 密码, 编码, 请用 '{\"irc 服务器\", \"编码\", 端口, \"密码\"}' 格式的值填充此表单. 默认情况下此服务使用\"~s\"编码, ~p 端口, 密码为空."}.
{"Import Directory","导入目录"}.
{"Import File","导入文件"}.
{"Import user data from jabberd14 spool file:","从 jabberd14 Spool 文件导入用户数据:"}.
{"Import User from File at ","导入用户的文件位于"}.
{"Import users data from a PIEFXIS file (XEP-0227):","从 PIEFXIS 文件 (XEP-0227) 导入用户数据:"}.
{"Import users data from jabberd14 spool directory:","从jabberd14 Spool目录导入用户数据:"}.
{"Import Users from Dir at ","导入用户的目录位于"}.
{"Import Users From jabberd14 Spool Files","从 jabberd14 Spool 文件导入用户"}.
{"Improper message type","不恰当的消息类型"}.
{"Incoming s2s Connections:","入站 s2s 连接:"}.
{"Incorrect password","密码不正确"}.
{"Invalid affiliation: ~s","无效加入: ~s"}.
{"Invalid role: ~s","无效角色: ~s"}.
{"IP addresses","IP地址"}.
{"IP","IP"}.
{"IRC channel (don't put the first #)","IRC频道 (不要输入第一个#号)"}.
{"IRC server","IRC服务器"}.
{"IRC settings","IRC设置"}.
{"IRC Transport","IRC传输"}.
{"IRC username","IRC用户名"}.
{"IRC Username","IRC用户名"}.
{"is now known as","现在称呼为"}.
{"It is not allowed to send error messages to the room. The participant (~s) has sent an error message (~s) and got kicked from the room","不允许将错误消息发送到该房间. 参与者(~s)已发送过一条消息(~s)并已被踢出房间"}.
{"It is not allowed to send private messages of type \"groupchat\"","\"群组聊天\"类型不允许发送私聊消息"}.
{"It is not allowed to send private messages to the conference","不允许向会议发送私聊消息"}.
{"It is not allowed to send private messages","不可以发送私聊消息"}.
{"Jabber Account Registration","Jabber帐户注册"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s 无效"}.
{"January","一月"}.
{"Join IRC channel","加入IRC频道"}.
{"joins the room","加入房间"}.
{"Join the IRC channel here.","在这里加入IRC频道."}.
{"Join the IRC channel in this Jabber ID: ~s","用此Jabber ID ~s加入IRC频道"}.
{"July","七月"}.
{"June","六月"}.
{"Last Activity","上次活动"}.
{"Last login","上次登陆"}.
{"Last month","上个月"}.
{"Last year","上一年"}.
{"leaves the room","离开房间"}.
{"Listened Ports at ","监听的端口位于"}.
{"Listened Ports","被监听的端口"}.
{"List of modules to start","要启动的模块列表"}.
{"List of rooms","房间列表"}.
{"Low level update script","低级别更新脚本"}.
{"Make participants list public","公开参与人列表"}.
{"Make room CAPTCHA protected","保护房间验证码"}.
{"Make room members-only","设置房间只接收会员"}.
{"Make room moderated","设置房间只接收主持人"}.
{"Make room password protected","进入此房间需要密码"}.
{"Make room persistent","永久保存该房间"}.
{"Make room public searchable","使房间可被公开搜索"}.
{"March","三月"}.
{"Maximum Number of Occupants","允许的与会人最大数"}.
{"Max # of items to persist","允许持久化的最大内容条目数"}.
{"Max payload size in bytes","最大有效负载字节数"}.
{"May","五月"}.
{"Membership is required to enter this room","进入此房间需要会员身份"}.
{"Members:","会员:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","记住你的密码, 或将其记到纸上并放于安全位置. 如果你忘记了密码, Jabber也没有自动恢复密码的方式."}.
{"Memory","内存"}.
{"Message body","消息主体"}.
{"Middle Name","中间名"}.
{"Minimum interval between voice requests (in seconds)","声音请求的最小间隔(以秒为单位)"}.
{"Moderator privileges required","需要主持人权限"}.
{"moderators only","仅主持人"}.
{"Moderator","主持人"}.
{"Modified modules","被修改模块"}.
{"Modules at ~p","位于~p的模块"}.
{"Modules","模块"}.
{"Module","模块"}.
{"Monday","星期一"}.
{"Multicast","多重映射"}.
{"Multi-User Chat","多用户聊天"}.
{"Name:","姓名:"}.
{"Name","姓名"}.
{"Never","从未"}.
{"New Password:","新密码:"}.
{"Nickname Registration at ","昵称注册于"}.
{"Nickname ~s does not exist in the room","昵称~s不在该房间"}.
{"Nickname","昵称"}.
{"No body provided for announce message","通知消息无正文内容"}.
{"nobody","没有人"}.
{"No Data","没有数据"}.
{"Node ID","节点ID"}.
{"Node not found","没有找到节点"}.
{"Node ~p","节点~p"}.
{"Nodes","节点"}.
{"No limit","不限"}.
{"None","无"}.
{"No resource provided","无资源提供"}.
{"Not Found","没有找到"}.
{"Notify subscribers when items are removed from the node","当从节点删除内容条目时通知订阅人"}.
{"Notify subscribers when the node configuration changes","当节点设置改变时通知订阅人"}.
{"Notify subscribers when the node is deleted","当节点被删除时通知订阅人"}.
{"November","十一月"}.
{"Number of occupants","驻留人数"}.
{"Number of online users","在线用户数"}.
{"Number of registered users","注册用户数"}.
{"October","十月"}.
{"Offline Messages:","离线消息:"}.
{"Offline Messages","离线消息"}.
{"OK","确定"}.
{"Old Password:","旧密码: "}.
{"Online Users:","在线用户:"}.
{"Online Users","在线用户"}.
{"Online","在线"}.
{"Only deliver notifications to available users","仅将通知发送给可发送的用户"}.
{"Only members may query archives of this room","只有会员可以查询本房间的存档"}.
{"Only moderators and participants are allowed to change the subject in this room","只有主持人和参与人可以在此房间里更改主题"}.
{"Only moderators are allowed to change the subject in this room","只有主持人可以在此房间里更改主题"}.
{"Only moderators can approve voice requests","仅主持人能确认声音请求"}.
{"Only occupants are allowed to send messages to the conference","只有与会人可以向大会发送消息"}.
{"Only occupants are allowed to send queries to the conference","只有与会人可以向大会发出查询请求"}.
{"Only service administrators are allowed to send service messages","只有服务管理员可以发送服务消息"}.
{"Options","选项"}.
{"Organization Name","组织名称"}.
{"Organization Unit","组织单位"}.
{"Outgoing s2s Connections:","出站 s2s 连接:"}.
{"Outgoing s2s Connections","出站 s2s 连接"}.
{"Owner privileges required","需要持有人权限"}.
{"Packet","数据包"}.
{"Participant","参与人"}.
{"Password ~b","~b的密码"}.
{"Password Verification:","密码确认:"}.
{"Password Verification","确认密码"}.
{"Password:","密码:"}.
{"Password","密码"}.
{"Path to Dir","目录的路径"}.
{"Path to File","文件路径"}.
{"Pending","挂起"}.
{"Period: ","持续时间: "}.
{"Permanent rooms","永久房间"}.
{"Persist items to storage","持久化内容条目"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","注意：这些选项仅将备份内置的 Mnesia 数据库. 如果您正在使用 ODBC 模块, 您还需要分别备份您的数据库."}.
{"Please specify file name.","请指定文件名称."}.
{"Please specify file size.","请指定文件大小."}.
{"Please, wait for a while before sending new voice request","请稍后再发送新的声音请求"}.
{"Pong","Pong"}.
{"Port ~b","~b的端口"}.
{"Port","端口"}.
{"Present real Jabber IDs to","将真实Jabber ID显示给"}.
{"private, ","保密, "}.
{"Protocol","协议"}.
{"Publish-Subscribe","发行-订阅"}.
{"PubSub subscriber request","PubSub订阅人请求"}.
{"Purge all items when the relevant publisher goes offline","相关发布人离线后清除所有选项"}.
{"Queries to the conference members are not allowed in this room","本房间不可以查询会议成员信息"}.
{"RAM and disc copy","内存与磁盘复制"}.
{"RAM copy","内存(RAM)复制"}.
{"Raw","原始格式"}.
{"Really delete message of the day?","确实要删除每日消息吗?"}.
{"Recipient is not in the conference room","接收人不在会议室"}.
{"Register a Jabber account","注册Jabber帐户"}.
{"Registered nicknames","注册的昵称"}.
{"Registered Users:","注册用户:"}.
{"Registered Users","注册用户"}.
{"Register","注册"}.
{"Registration in mod_irc for ","mod_irc 中的注册是为 "}.
{"Remote copy","远程复制"}.
{"Remove All Offline Messages","移除所有离线消息"}.
{"Remove User","删除用户"}.
{"Remove","移除"}.
{"Replaced by new connection","被新的连接替换"}.
{"Resources","资源"}.
{"Restart Service","重启服务"}.
{"Restart","重启"}.
{"Restore Backup from File at ","要恢复的备份文件位于"}.
{"Restore binary backup after next ejabberd restart (requires less memory):","在下次 ejabberd 重启后恢复二进制备份(需要的内存更少):"}.
{"Restore binary backup immediately:","立即恢复二进制备份:"}.
{"Restore plain text backup immediately:","立即恢复普通文本备份:"}.
{"Restore","恢复"}.
{"Roles for which Presence is Broadcasted","广播存在性的角色"}.
{"Room Configuration","房间配置"}.
{"Room creation is denied by service policy","创建房间被服务策略拒绝"}.
{"Room description","房间描述"}.
{"Room Occupants","房间人数"}.
{"Room title","房间标题"}.
{"Roster groups allowed to subscribe","允许订阅的花名册组"}.
{"Roster of ","花名册属于"}.
{"Roster size","花名册大小"}.
{"Roster","花名册"}.
{"RPC Call Error","RPC 调用错误"}.
{"Running Nodes","运行中的节点"}.
{"~s access rule configuration","~s访问规则配置"}.
{"Saturday","星期六"}.
{"Script check","脚本检查"}.
{"Search Results for ","搜索结果属于关键词 "}.
{"Search users in ","搜索用户于"}.
{"Send announcement to all online users on all hosts","发送通知给所有主机的在线用户"}.
{"Send announcement to all online users","发送通知给所有在线用户"}.
{"Send announcement to all users on all hosts","发送通知给所有主机上的所有用户"}.
{"Send announcement to all users","发送通知给所有用户"}.
{"September","九月"}.
{"Server ~b","服务器~b"}.
{"Server:","服务器:"}.
{"Server","服务器"}.
{"Set message of the day and send to online users","设定每日消息并发送给所有在线用户"}.
{"Set message of the day on all hosts and send to online users","设置所有主机上的每日消息并发送给在线用户"}.
{"Shared Roster Groups","共享的花名册组群"}.
{"Show Integral Table","显示完整列表"}.
{"Show Ordinary Table","显示普通列表"}.
{"Shut Down Service","关闭服务"}.
{"~s invites you to the room ~s","~s邀请你到房间~s"}.
{"Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.","某些 Jabber 客户端可以在你的计算机里存储密码. 请仅在你确认你的计算机安全的情况下使用该功能."}.
{"Specify the access model","指定访问范例"}.
{"Specify the event message type","指定事件消息类型"}.
{"Specify the publisher model","指定发布人范例"}.
{"~s's Offline Messages Queue","~s的离线消息队列"}.
{"Start Modules at ","要启动的模块位于 "}.
{"Start Modules","启动模块"}.
{"Start","开始"}.
{"Statistics of ~p","~p的统计"}.
{"Statistics","统计"}.
{"Stop Modules at ","要停止的模块位于 "}.
{"Stop Modules","停止模块"}.
{"Stopped Nodes","已经停止的节点"}.
{"Stop","停止"}.
{"Storage Type","存储类型"}.
{"Store binary backup:","存储为二进制备份:"}.
{"Store plain text backup:","存储为普通文本备份:"}.
{"Subject","标题"}.
{"Submitted","已提交"}.
{"Submit","提交"}.
{"Subscriber Address","订阅人地址"}.
{"Subscription","订阅"}.
{"Sunday","星期天"}.
{"That nickname is already in use by another occupant","该昵称已被另一用户使用"}.
{"That nickname is registered by another person","该昵称已被另一个人注册了"}.
{"The CAPTCHA is valid.","验证码有效."}.
{"The CAPTCHA verification has failed","验证码检查失败"}.
{"The collections with which a node is affiliated","加入结点的集合"}.
{"The password is too weak","密码强度太弱"}.
{"the password is","密码是"}.
{"The password of your Jabber account was successfully changed.","你的Jabber帐户密码已成功更新."}.
{"There was an error changing the password: ","修改密码出错: "}.
{"There was an error creating the account: ","帐户创建出错: "}.
{"There was an error deleting the account: ","帐户删除失败: "}.
{"This IP address is blacklisted in ~s","此IP地址在~s中已被列入黑名单"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","此处不区分大小写: macbeth 与 MacBeth 和 Macbeth 是一样的."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","本页面允许在此服务器上创建Jabber帐户. 你的JID (Jabber ID) 的形式如下: 用户名@服务器. 请仔细阅读说明并正确填写相应字段."}.
{"This page allows to unregister a Jabber account in this Jabber server.","此页面允许在此Jabber服务器上注销Jabber帐户"}.
{"Thursday","星期四"}.
{"Time delay","时间延迟"}.
{"Time","时间"}.
{"Too many CAPTCHA requests","验证码请求太多"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","来自IP地址(~p)的(~s)失败认证太多. 该地址将在UTC时间~s被禁用."}.
{"Too many unacked stanzas","未被确认的节太多"}.
{"To ~s","发送给~s"}.
{"Total rooms","所有房间"}.
{"To","到"}.
{"Traffic rate limit is exceeded","已经超过传输率限制"}.
{"Transactions Aborted:","取消的事务:"}.
{"Transactions Committed:","提交的事务:"}.
{"Transactions Logged:","记入日志的事务:"}.
{"Transactions Restarted:","重启的事务:"}.
{"Tuesday","星期二"}.
{"Unable to generate a CAPTCHA","无法生成验证码"}.
{"Unauthorized","未认证的"}.
{"Unregister a Jabber account","注销Jabber帐户"}.
{"Unregister","取消注册"}.
{"Update message of the day (don't send)","更新每日消息(不发送)"}.
{"Update message of the day on all hosts (don't send)","更新所有主机上的每日消息(不发送)"}.
{"Update plan","更新计划"}.
{"Update ~p","更新~p"}.
{"Update script","更新脚本"}.
{"Update","更新"}.
{"Uptime:","正常运行时间:"}.
{"Use of STARTTLS required","要求使用 STARTTLS"}.
{"User JID","用户JID"}.
{"User Management","用户管理"}.
{"Username:","用户名:"}.
{"Users are not allowed to register accounts so quickly","不允许用户太频繁地注册帐户"}.
{"Users Last Activity","用户上次活动"}.
{"Users","用户"}.
{"User ~s","用户~s"}.
{"User","用户"}.
{"Validate","确认"}.
{"vCard User Search","vCard用户搜索"}.
{"Virtual Hosts","虚拟主机"}.
{"Visitors are not allowed to change their nicknames in this room","此房间不允许用户更改昵称"}.
{"Visitors are not allowed to send messages to all occupants","不允许访客给所有占有者发送消息"}.
{"Visitor","访客"}.
{"Voice requests are disabled in this conference","该会议的声音请求以被禁用"}.
{"Voice request","声音请求"}.
{"Wednesday","星期三"}.
{"When to send the last published item","何时发送最新发布的内容条目"}.
{"Whether to allow subscriptions","是否允许订阅"}.
{"You can later change your password using a Jabber client.","你可以稍后用Jabber客户端修改你的密码."}.
{"You have been banned from this room","您已被禁止进入该房间"}.
{"You must fill in field \"Nickname\" in the form","您必须填充表单中\"昵称\"项"}.
{"You need a client that supports x:data and CAPTCHA to register","您需要一个支持 x:data 和验证码的客户端进行注册"}.
{"You need a client that supports x:data to register the nickname","您需要一个支持 x:data 的客户端来注册昵称"}.
{"You need an x:data capable client to configure mod_irc settings","您需要一个兼容 x:data 的客户端来配置mod_irc设置"}.
{"You need an x:data capable client to configure room","您需要一个兼容 x:data 的客户端来配置房间"}.
{"You need an x:data capable client to search","您需要一个兼容 x:data 的客户端来搜索"}.
{"Your active privacy list has denied the routing of this stanza.","你的活跃私聊列表拒绝了在此房间进行路由分发."}.
{"Your contact offline message queue is full. The message has been discarded.","您的联系人离线消息队列已满. 消息已被丢弃"}.
{"Your Jabber account was successfully created.","你的Jabber帐户已成功创建."}.
{"Your Jabber account was successfully deleted.","你的 Jabber 帐户已成功删除."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","您发送给~s的消息已被阻止. 要解除阻止, 请访问 ~s"}.
