% $Id$
% Language: Catalan (català)
% Author: Vicent Alberola Canet

% jlib.hrl
{"No resource provided", "Recurs no disponible"}.

% mod_configure.erl
{"Restart Service", "Reiniciar el Servei"}.
{"Shut Down Service", "Apager el Servei"}.
{"Delete User", "Eliminar Usuari"}.
{"End User Session", "Finalitzar Sesió d'Usuari"}.
{"Get User Password", "Obtenir Password d'usuari"}.
{"Change User Password", "Canviar Password d'Usuari"}.
{"Get User Last Login Time", "Obtenir la última connexió d'Usuari"}.
{"Get User Statistics", "Obtenir Estadístiques d'Usuari"}.
{"Get Number of Registered Users", "Obtenir Número d'Usuaris Registrats"}.
{"Get Number of Online Users", "Obtenir Número d'Usuaris Connectats"}.
{"User Management", "Gestió d'Usuaris"}.
{"Time delay", "Temps de retràs"}.
{"Password Verification", "Verificació del Password"}.
{"Number of registered users", "Número d'Usuaris Registrats"}.
{"Number of online users", "Número d'usuaris connectats"}.
{"Last login", "Últim login"}.
{"Roster size", "Tamany de la llista"}.
{"IP addresses", "Adreça IP"}.
{"Resources", "Recursos"}.
{"Choose storage type of tables", "Selecciona el tipus d'almacenament de les taules"}.
{"RAM copy", "Còpia en RAM"}.
{"RAM and disc copy", "Còpia en RAM i disc"}.
{"Disc only copy", "Còpia sols en disc"}.
{"Remote copy", "Còpia remota"}.
{"Stop Modules at ", "Detindre mòduls en "}.
{"Choose modules to stop", "Selecciona mòduls a detindre"}.
{"Start Modules at ", "Iniciar mòduls en "}.
{"Enter list of {Module, [Options]}", "Introdueix llista de {mòdul, [opcions]}"}.
{"List of modules to start", "Llista de mòduls a iniciar"}.
{"Backup to File at ", "Desar còpia de seguretat a fitxer en "}.
{"Enter path to backup file", "Introdueix ruta al fitxer de còpia de seguretat"}.
{"Path to File", "Ruta al fitxer"}.
{"Restore Backup from File at ", "Restaura còpia de seguretat des del fitxer en "}.
{"Dump Backup to Text File at ", "Exporta còpia de seguretat a fitxer de text en "}.
{"Enter path to text file", "Introdueix ruta al fitxer de text"}.
{"Import User from File at ", "Importa usuari des de fitxer en "}.
{"Enter path to jabberd1.4 spool file", "Introdueix ruta al fitxer jabberd1.4 spool"}.
{"Import Users from Dir at ", "Importar usuaris des del directori en "}.
{"Enter path to jabberd1.4 spool dir", "Introdueix la ruta al directori de jabberd1.4 spools"}.
{"Path to Dir", "Ruta al directori"}.
{"Access Control List Configuration", "Configuració de la Llista de Control d'Accés"}.
{"Access control lists", "Llistes de Control de Accés"}.
{"Access Configuration", "Configuració d'accesos"}.
{"Access rules", "Regles d'accés"}.
{"Administration of ", "Administració de "}.
{"Action on user", "Acció en l'usuari"}.
{"Edit Properties", "Editar propietats"}.
{"Remove User", "Eliminar usuari"}.
{"Database", "Base de dades"}.
{"Outgoing s2s Connections", "Connexions s2s d'eixida"}.
{"Import Users From jabberd 1.4 Spool Files", "Importar usuaris de jabberd 1.4"}.
{"Database Tables Configuration at ", "Configuració de la base de dades en "}.

% mod_disco.erl
{"Configuration", "Configuració"}.
{"Online Users", "Usuaris conectats"}.
{"All Users", "Tots els usuaris"}.
{"To ~s", "A ~s"}.
{"From ~s", "De ~s"}.
{"Running Nodes", "Nodes funcionant"}.
{"Stopped Nodes", "Nodes parats"}.
{"Access Control Lists", "Llista de Control d'Accés"}.
{"Access Rules", "Regles d'Accés"}.
{"Modules", "Mòduls"}.
{"Start Modules", "Iniciar mòduls"}.
{"Stop Modules", "Parar mòduls"}.
{"Backup Management", "Gestió de còpia de seguretat"}.
{"Backup", "Guardar còpia de seguretat"}.
{"Restore", "Restaurar"}.
{"Dump to Text File", "Exportar a fitxer de text"}.
{"Import File", "Importar fitxer"}.
{"Import Directory", "Importar directori"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Tria nom d'usuari i password per a registrar-te en aquest servidor"}.

% mod_vcard.erl
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Emplena el formulari per a buscar usuaris Jabber. Afegix * al final d'un camp per a buscar subcadenes."}.
{"You need an x:data capable client to search", "Necesites un client amb suport x:data per a poder buscar"}.
{"Search users in ", "Cerca usuaris en "}.

{"User",              "Usuari"}.
{"Full Name", 	      "Nom complet"}.
{"Name", 	      "Nom"}.
{"Middle Name",       "Segon nom"}.
{"Family Name",       "Cognom"}.
{"Nickname", 	      "Nickname"}.
{"Birthday", 	      "Aniversari"}.
{"Country", 	      "Pais"}.
{"City", 	      "Ciutat"}.
{"Organization Name", "Nom de la organizació"}.
{"Organization Unit", "Unitat de la organizació"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd Publish-Subscribe module", "Mòdul ejannerd Publicar-Subscriure"}.
{"PubSub subscriber request", "Petició de PubSub subscriure"}.
{"Choose whether to approve this entity's subscription.", "Tria si aprova aquesta entitat de subscripció"}.
{"Node ID", "ID del Node"}.
{"Subscriber Address", "Adreça del Subscriptor"}.
{"Allow this JID to subscribe to this pubsub node?", "Deixar que aquesta JID es puga subscriure a aquest node pubsub"}.
{"Deliver event notifications", "Entrega de notificacions d'events"}.
{"Specify the access model", "Especificar el model d'accés"}.
{"Roster groups that may subscribe (if access model is roster)", "Llista de grups que cal subscriures (si el model d'accés és per llista)"}.
{"When to send the last published item", "Quan s'ha enviat l'última publicació"}.
{"Deliver payloads with event notifications", "Enviar payloads junt a les notificacions d'events"}.
{"Notify subscribers when the node configuration changes", "Notificar subscriptors quan canvia la configuració del node"}.
{"Notify subscribers when the node is deleted", "Notificar subscriptors quan el node és eliminat"}.
{"Notify subscribers when items are removed from the node", "Notificar subscriptors quan els elements són eliminats del node"}.
{"Persist items to storage", "Persistir elements al guardar"}.
{"Max # of items to persist", "Màxim # d'elements que persistixen"}.
{"Whether to allow subscriptions", "Permetre subscripcions"}.
{"Specify the publisher model", "Especificar el model del publicant"}.
{"Max payload size in bytes", "Màxim tamany del payload en bytes"}.
{"Only deliver notifications to available users", "Sols enviar notificacions als usuaris disponibles"}.
{"Publish-Subscribe", "Publicar-subscriure't"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "Necessites un client amb suport x:data per a poder registrar el Nickname"}.
{"Nickname Registration at ", "Registre del Nickname en "}.
{"Enter nickname you want to register", "Introdueix el nickname que vols registrar"}.
{"Only service administrators are allowed to send service messages", "Sols els administradors del servei tenen permís per a enviar missatges de servei"}.
{"Conference room does not exist", "La sala de conferències no existeix"}.
{"Access denied by service policy", "Accés denegat per la política del servei"}.
{"Specified nickname is already registered", "El Nickname especificat ja està registrat, busca-te'n un altre"}.
{"Room creation is denied by service policy", "Se t'ha denegat el crear la sala per política del servei"}.
{"Chatrooms", "Sales de xat"}.
{"You must fill in field \"Nickname\" in the form", "Deus d'omplir el camp \"Nickname\" al formulari"}.
{"ejabberd MUC module", "mòdul ejabberd MUC"}.

% mod_muc/mod_muc_room.erl
{"Traffic rate limit is exceeded", "El llímit de tràfic ha sigut sobrepassat"}.
{"Maximum Number of Occupants", "Número màxim d'ocupants"}.
{"No limit", "Sense Llímit"}.
{"~s invites you to the room ~s", "~s et convida a la sala ~s"}.
{"the password is", "el password és"}.
{" has set the subject to: ", " ha posat l'assumpte: "}.
{"You need an x:data capable client to configure room", "Necessites un client amb suport x:data per a configurar la sala"}.
{"Configuration for ", "Configuració per a "}.
{"Room title", "Títol de la sala"}.
{"Password", "Password"}.
{"Only moderators and participants are allowed to change subject in this room", "Sols els moderadors i participants poden canviar l'assumpte d'aquesta sala"}.
{"Only moderators are allowed to change subject in this room", "Sols els moderadors poden canviar l'assumpte d'aquesta sala"}.
{"Visitors are not allowed to send messages to all occupants", "Els visitants no poden enviar missatges a tots els ocupants"}.
{"Only occupants are allowed to send messages to the conference", "Sols els ocupants poden enviar missatges a la sala"}.
{"It is not allowed to send private messages to the conference", "No està permés l'enviament de missatges privats a la sala"}.
{"Improper message type", "Tipus de missatge incorrecte"}.
{"Nickname is already in use by another occupant", "El Nickname està siguent utilitzat per una altra persona"}.
{"Nickname is registered by another person", "El Nickname ja està registrat per una altra persona"}.
{"It is not allowed to send private messages of type \"groupchat\"", "No està permés enviar missatges del tipus \"groupchat\""}.
{"Recipient is not in the conference room", "El receptor no està en la sala de conferència"}.
{"Only occupants are allowed to send queries to the conference", "Sols els ocupants poden enviar solicituts a la sala"}.
{"Queries to the conference members are not allowed in this room", " En aquesta sala no es permeten solicituts als membres de la sala"}.
{"You have been banned from this room", "Has sigut bloquejat en aquesta sala"}.
{"Membership required to enter this room", "Necessites ser membre d'aquesta sala per a poder entrar"}.
{"Password required to enter this room", "Es necessita password per a entrar en aquesta sala"}.
{"Incorrect password", "Password incorrecte"}.
{"Administrator privileges required", "Es necessita tenir privilegis d'administrador"}.
{"Moderator privileges required", "Es necessita tenir privilegis de moderador"}.
{"JID ~s is invalid", "El JID ~s no és vàlid"}.
{"Nickname ~s does not exist in the room", "El Nickname ~s no existeix a la sala"}.
{"Invalid affiliation: ~s", "Afiliació invàlida: ~s"}.
{"Invalid role: ~s", "Rol invàlid: ~s"}.
{"Owner privileges required", "Es requerixen privilegis de propietari de la sala"}.
{"private, ", "privat"}.
{"This room is not anonymous", "Aquesta sala no és anònima"}.
{"Make room persistent", "Crear una sala persistent"}.
{"Make room public searchable", "Crear una sala pública"}.
{"Make participants list public", "Crear una llista de participants pública"}.
{"Make room password protected", "Crear una sala amb password"}.
{"Present real JIDs to", "Presentar JID's reals a"}.
{"moderators only", "sols moderadors"}.
{"anyone", "qualsevol"}.
{"Make room members-only", "Crear una sala de \"soles membres\""}.
{"Default users as participants", "Els usuaris per defecte són els participants"}.
{"Allow users to change subject", "Permetre que els usuaris canvien el tema"}.
{"Allow users to send private messages", "Permetre que els usuaris envien missatges privats"}.
{"Allow users to query other users", "Permetre que els usuaris fagen peticions a altres usuaris"}.
{"Allow users to send invites", "Permetre que els usuaris envien invitacions"}.
{"Enable logging", "Habilitar el registre de la conversa"}.
{"Number of occupants", "Número d'ocupants"}.

% mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "Has sigut expulsat a causa d'un canvi d'afiliació"}.
{"has been kicked because the room has been changed to members-only", "Has sigut expulsat perquè la sala ha canviat a sols membres"}.
{"has been kicked because of a system shutdown", "Has sigut expulsat perquè el sistema s'ha apagat"}.
{"Chatroom configuration modified", "Configuració de la sala de xat modificada"}.
{"joins the room", "Entrar a la sala"}.
{"leaves the room", "Deixar la sala"}.
{"has been kicked", "Has sigut expulsat"}.
{"has been banned", "Has sigut banejat"}.
{"is now known as", "ara es conegut com"}.
{"Monday", "Dilluns"}.
{"Tuesday", "Dimarts"}.
{"Wednesday", "Dimecres"}.
{"Thursday", "Dijous"}.
{"Friday", "Divendres"}.
{"Saturday", "Dissabte"}.
{"Sunday", "Diumenge"}.
{"January", "Gener"}.
{"February", "Febrer"}.
{"March", "Març"}.
{"April", "Abril"}.
{"May", "Maig"}.
{"June", "Juny"}.
{"July", "Juliol"}.
{"August", "Agost"}.
{"September", "Setembre"}.
{"October", "Octubre"}.
{"November", "Novembre"}.
{"December", "Decembre"}.
{"Room Configuration", "Configuració de la sala"}.

% mod_irc/mod_irc.erl
{"You need an x:data capable client to configure mod_irc settings", "Necessites un client amb suport x:data per a configurar les opcions de mod_irc"}.
{"Registration in mod_irc for ", "Registre en mod_irc per a"}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Introdueix el nom d'usuari i les codificacions de caràcters per a utilitzar als servidors de IRC"}.
{"IRC Username", "Nom d'usuari al IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Si vols especificar codificacions de caràcters distints per a cada servidor IRC emplena aquesta llista amb els valors amb el format '{\"servidor irc\", \"codificació\"}'.  Aquest servei utilitza per defecte la codificació \"~s\"."}.
{"Encodings", "Codificacions"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Exemple: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"IRC Transport", "Transport a IRC"}.
{"ejabberd IRC module", "mòdul ejabberd IRC"}.

% web/ejabberd_web_admin.erl
{"Users", "Usuaris"}.
{"Nodes", "Nodes"}.
{"Statistics", "Estadístiques"}.
{"Delete Selected", "Eliminar els seleccionats"}.
{"Submit", "Enviar"}.
{"~s access rule configuration", "Configuració de les Regles d'Accés ~s"}.
{"Node not found", "Node no trobat"}.
{"Add New", "Afegir nou"}.
{"Change Password", "Canviar password"}.
{"Connected Resources:", "Recursos connectats:"}.
{"Password:", "Password:"}.
{"None", "Cap"}.
{"Node ", "Node "}.
{"Restart", "Reiniciar"}.
{"Stop", "Detindre"}.
{"Name", "Nom"}.
{"Storage Type", "Tipus d'emmagatzematge"}.
{"Size", "Tamany"}.
{"Memory", "Memòria"}.
{"OK", "Acceptar"}.
{"Listened Ports at ", "Ports a la escolta en "}.
{"Port", "Port"}.
{"Module", "Mòdul"}.
{"Options", "Opcions"}.
{"Update", "Actualitzar"}.
{"Delete", "Eliminar"}.
{"Add User", "Afegir usuari"}.
{"Last Activity", "Última activitat"}.
{"Never", "Mai"}.
{"Time", "Data"}.
{"From", "De"}.
{"To", "Per a"}.
{"Packet", "Paquet"}.
{"Roster", "Llista de contactes"}.
{"Nickname", "Nickname"}.
{"Subscription", "Subscripció"}.
{"Pending", "Pendent"}.
{"Groups", "Grups"}.
{"Remove", "Borrar"}.
{"User ", "Usuari "}.
{"Roster of ", "Llista de contactes de "}.
{"Online", "Connectat"}.
{"Validate", "Validar"}.
{"Name:", "Nom:"}.
{"Description:", "Descripció:"}.
{"Members:", "Membre:"}.
{"Displayed Groups:", "Mostrar grups:"}.
{"Group ", "Grup "}.
{"Period: ", "Període: "}.
{"Last month", "Últim mes"}.
{"Last year", "Últim any"}.
{"All activity", "Tota l'activitat"}.
{"Show Ordinary Table", "Mostrar Taula Ordinaria"}.
{"Show Integral Table", "Mostrar Taula Integral"}.
{"Modules at ", "Mòduls en "}.
{"Start", "Iniciar"}.
{"Virtual Hosts", "Hosts Virtuals"}.
{"ejabberd virtual hosts", "Hosts virtuals del ejabberd"}.
{"Host", "Host"}.
{"ejabberd Web Interface", "Interficie Web del ejabberd"}.
{"Administration", "Administració"}.
{"(Raw)", "(en format text)"}.
{"Submitted", "Enviat"}.
{"Bad format", "Format erroni"}.
{"Raw", "en format text"}.
{"Users Last Activity", "Última activitat d'usuari"}.
{"Registered Users", "Usuaris registrats"}.
{"Offline Messages", "Missatges offline"}.
{"Registered Users:", "Usuaris registrats:"}.
{"Online Users:", "Usuaris en línia:"}.
{"Outgoing s2s Connections:", "Connexions d'eixida s2s"}.
{"Outgoing s2s Servers:", "Servidors d'eixida de s2s"}.
{"Offline Messages:", "Missatges fora de línia:"}.
{"~s's Offline Messages Queue", "~s's cua de missatges offline"}.
{"Add Jabber ID", "Afegir Jabber ID"}.
{"No Data", "No hi ha dades"}.
{"Listened Ports", "Ports a l'escolta"}.
{"RPC Call Error", "Error de cridada RPC"}.
{"Database Tables at ", "Taules de la base de dades en "}.
{"Backup of ", "Còpia de seguretat de "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Recordar que estes opcions sols fan còpia de seguretat de la base de dades Mnesia. Si estàs utilitzant el mòdul d'ODBC també deus de fer una còpia de seguretat de la base de dades de SQL a part."}.
{"Store binary backup:", "Guardar una còpia de seguretat binària:"}.
{"Restore binary backup immediately:", "Restaurar una còpia de seguretat binària ara mateix."}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Restaurar una còpia de seguretat binària després de reiniciar el ejabberd (requereix menys memòria:"}.
{"Store plain text backup:", "Guardar una còpia de seguretat en format de text pla:"}.
{"Restore plain text backup immediately:", "Restaurar una còpia de seguretat en format de text pla ara mateix:"}.
{"Statistics of ~p", "Estadístiques de ~p"}.
{"CPU Time:", "Temps de CPU"}.
{"Transactions Commited:", "Transaccions Realitzades:"}.
{"Transactions Aborted:", "Transaccions Avortades"}.
{"Transactions Restarted:", "Transaccions reiniciades"}.
{"Transactions Logged:", "Transaccions registrades"}.
{"Update ", "Actualitzar"}.
{"Update plan", "Pla d'actualització"}.
{"Updated modules", "Mòduls actualitzats"}.
{"Update script", "Script d'actualització"}.
{"Low level update script", "Script d'actualització de baix nivell"}.
{"Script check", "Comprovar script"}.
{"Shared Roster Groups", "Grups de contactes compartits"}.
{"Uptime:", "Temps en marxa"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "És obligatori utilitzar STARTTLS"}.
{"Replaced by new connection", "Reemplaçat per una nova connexió"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Emplena camps per a buscar usuaris Jabber que concorden"}.

% mod_vcard_odbc.erl
{"Erlang Jabber Server", "Servidor Erlang Jabber"}.
{"Email", "Email"}.
{"vCard User Search", "Recerca de vCard d'usuari"}.
{"ejabberd vCard module", "Mòdul ejabberd vCard"}.
{"Search Results for ", "Resultat de la búsqueda"}.
{"Jabber ID", "ID Jabber"}.

% mod_adhoc.erl
{"Commands", "Comandaments"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Send announcement to all users on all hosts", "Enviar anunci a tots els usuaris de tots els hosts"}.
{"Set message of the day on all hosts and send to online users", "Escriure missatge del dia en tots els hosts i envia als usuaris connectats"}.
{"Update message of the day on all hosts (don't send)", "Actualitza el missatge del dia en tots els hosts (no enviar)"}.
{"Delete message of the day on all hosts", "Elimina el missatge del dis de tots els hosts"}.
{"Really delete message of the day?", "Segur que vols eliminar el missatge del dia?"}.
{"Subject", "Assumpte"}.
{"Message body", "Missatge"}.
{"No body provided for announce message", "No hi ha proveedor per al missatge anunci"}.
{"Announcements", "Anuncis"}.
{"Send announcement to all users", "Enviar anunci a tots els usuaris"}.
{"Send announcement to all online users", "Enviar anunci a tots els usuaris connectats"}.
{"Send announcement to all online users on all hosts", "Enviar anunci a tots els usuaris connectats a tots els hosts"}.
{"Set message of the day and send to online users", "Configurar el missatge del dia i enviar a tots els usuaris"}.
{"Update message of the day (don't send)", "Actualitzar el missatge del dia (no enviar)"}.
{"Delete message of the day", "Eliminar el missatge del dia"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "mòdul ejabberd SOCKS5 Bytestreams"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "La cua de missatges offline és plena. El missatge ha sigut descartat"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
