% $Id$
% Czech translation
% Authors: Milos Svasek [DuxforD] from openheads.net
 

% jlib.hrl
{"No resource provided", "Nebyl poskytnutý žádny zdroj"}.

% mod_configure.erl
{"Choose storage type of tables", "Vyberte typ úložiště pro tabulky"}.
{"RAM copy", "Kopie RAM"}.
{"RAM and disc copy", "Kopie RAM a disku"}.
{"Disc only copy", "Jen kopie disku"}.
{"Remote copy", "Vzdálená kopie"}.
{"Stop Modules at ", "Zastavit moduly na "}.
{"Choose modules to stop", "Vyberte moduly, které mají být zastavené"}.
{"Start Modules at ", "Spustit moduly na "}.
{"Enter list of {Module, [Options]}", "Vložte seznam modulů {Modul, [Parametre]}"}.
{"List of modules to start", "Seznam modulů, které mají být spuštěné"}.
{"Backup to File at ", "Záloha do souboru na "}.
{"Enter path to backup file", "Zadajte cestu k souboru se zálohou"}.
{"Path to File", "Cesta k souboru"}.
{"Restore Backup from File at ", "Obnovit zálohu ze souboru na "}.
{"Dump Backup to Text File at ", "Uložit zálohu do textového souboru na "}.
{"Enter path to text file", "Zadajte cestu k textovému souboru"}.
{"Import User from File at ", "Importovat uživatele ze souboru na "}.
{"Enter path to jabberd1.4 spool file", "Zadejte cestu k spool souboru jabberd1.4"}.
{"Import Users from Dir at ", "Importovat uživatele z adresáře na "}.
{"Enter path to jabberd1.4 spool dir", "Zadejte cestu k jabberd1.4 spool adresáři"}.
{"Path to Dir", "Cesta k adresáři"}.
{"Hostname Configuration", "Konfigurace jména serveru"}.
{"Choose host name", "Vyberte jméno serveru"}.
{"Host name", "Jméno serveru"}.
{"Access Control List Configuration", "Konfigurace seznamu přístupových práv (ACL)"}.
{"Access control lists", "Seznamy přístupových práv (ACL)"}.
{"Access Configuration", "Konfigurace přístupů"}.
{"Access rules", "Pravidla přístupů"}.
{"Remove Users", "Odstranit uživatele"}.
{"Choose users to remove", "Vybrat uživatele, kteří budou odstraněni"}.
{"Administration of ", "Administrace "}.
{"Action on user", "Akce aplikovaná na uživatele"}.
{"Edit Properties", "Upravit vlastnosti"}.
{"Remove User", "Odstranit uživatele"}.

% mod_disco.erl
{"Configuration", "Konfigurace"}.
{"Online Users", "Online uživatelé"}.
{"All Users", "Všichni uživatelé"}.
{"To ~s", "Pre ~s"}.
{"From ~s", "Od  ~s"}.
{"Running Nodes", "Bežící uzly"}.
{"Stopped Nodes", "Zastavené uzly"}.
{"Host Name", "Jméno serveru"}.
{"Access Control Lists", "Seznamy přístupových práv (ACL)"}.
{"Access Rules", "Pravidla přístupů"}.
{"Remove Users", "Odstranit uživatele"}.
{"Modules", "Moduly"}.
{"Start Modules", "Spustit moduly"}.
{"Stop Modules", "Zastavit moduly"}.
{"Backup Management", "Správa zálohování"}.
{"Backup", "Zálohovat"}.
{"Restore", "Obnovit"}.
{"Dump to Text File", "Uložit do textového souboru"}.
{"Import File", "Import souboru"}.
{"Import Directory", "Import adresáře"}.

% mod_register.erl
{"Choose a username and password to register with this server",
 "Zadejte jméno uživatele a heslo pro registraci na tomto serveru"}.

% mod_vcard.erl
{"You need an x:data capable client to search",
 "K vyhledávání potřebujete klienta podporujícího x:data"}.
{"Search users in ", "Hledat uživatele v "}.
{"Fill in fields to search for any matching Jabber User",
 "Vyplňte políčka pro vyhledávání Jabber uživatele"}.

{"User",              "Uživatel: "}.
{"Full Name", 	      "Celé jméno: "}.
{"Name", 	      "Jméno: "}.
{"Middle Name",       "Prostřední jméno: "}.
{"Family Name",       "Příjmení: "}.
{"Nickname", 	      "Přezdívka: "}.
{"Birthday", 	      "Datum narození: "}.
{"Country", 	      "Země: "}.
{"City", 	      "Město: "}.
{"Organization Name", "Název firmy: "}.
{"Organization Unit", "Oddělení: "}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname",
 "K registraci přezdívky potřebujete klienta podporujícího z x:data"}.
{"Nickname Registration at ", "Registrace prezdívky na "}.
{"Enter nickname you want to register", "Zadajte prezdívku, kterou chete zaregistrovat"}.
{"Only service administrators are allowed to send service messages",
 "Pouze správci služby mají povolené odesílání servisních zpráv"}.
{"Conference room does not exist", "Konferenční místnost neexistuje"}.
{"Access denied by service policy", "Přístup byl zamítnutý nastavením služby"}.
{"Specified nickname is already registered", "Zadaná prezdívka je již registrována"}.

% mod_muc/mod_muc_room.erl
{" has set the subject to: ", "změnil(a) téma na: "}.
{"You need an x:data capable client to configure room",
 "Ke konfiguraci místnosti potřebujete klienta podporujícího z x:data"}.
{"Configuration for ", "Konfigurace pre "}.
{"Room title", "Název místnosti"}.
{"Password", "Heslo"}.
{"Only moderators and participants are allowed to change subject in this room",
 "Jen moderátoři a účastníci mají povoleno měnit téma této místnosti"}.
{"Only moderators are allowed to change subject in this room",
 "Jen moderátoři mají povoleno měnit téma místnosti"}.
{"Visitors are not allowed to send messages to all occupants",
 "Návštevníci nemají povoleno zsílat zprávy všem přihlášeným do konference"}.
{"Only occupants are allowed to send messages to the conference",
 "Jen členové mají povolené zasílat správy do konference"}.
{"It is not allowed to send normal messages to the conference",
 "Není povoleno odesílat normální zprávy do konference"}.
{"It is not allowed to send private messages to the conference",
 "Není povoleno odesílat soukromé zprávy do konference"}.
{"Improper message type", "Nesprávný typ zprávy"}.
{"Nickname is already in use by another occupant", "Prezdívka je již používána jiným členem"}.
{"Nickname is registered by another person", "Prezdívka je registrována jinou osobou"}.
{"It is not allowed to send private messages of type \"groupchat\"",
 "Není dovoleno odeslání soukromé zprávy typu \"Skupinová zpráva\" "}.
{"Recipient is not in the conference room", "Příjemce se nenachází v konferenční místnosti"}.
{"Only occupants are allowed to send queries to the conference",
 "Jen členové mohou odesílat požadavky (query) do konference"}.
{"Queries to the conference members are not allowed in this room",
 "Požadavky (queries) na členy konference nejsou v této místnosti povolené"}.
{"You have been banned from this room", "Byl jste vyloučen z této místnosti"}.
{"Membership required to enter this room", "Pro vstup do místnosti musíte být členem"}.
{"Password required to enter this room", "Pro vstup do místnosti musíte zadat heslo"}.
{"Incorrect password", "Nesprávne heslo"}.
{"Administrator privileges required", "Jsou potřebná práva administrátora"}.
{"Moderator privileges required", "Jsou potřebná práva moderátora"}.
{"JID ~s is invalid", "JID ~s je neplatné"}.
{"Nickname ~s does not exist in the room", "Prezdívka ~s v místnosti neexistuje"}.
{"Invalid affiliation: ~s", "Neplatné přiřazení: ~s"}.
{"Invalid role: ~s", "Neplatná role: ~s"}.
{"Owner privileges required", "Jsou vyžadována práva vlastníka"}.
{"private, ", "soukromá, "}.
{"Present real JIDs to", "Zjisti skutečné JIDy pro"}.
{"moderators only", "pouze pro moderátory"}.
{"anyone", "každý"}.

% mod_irc/mod_irc.erl
{"You need an x:data capable client to configure mod_irc settings",
 "Pro konfiguraci mod_irc potřebujete klienta podporujícího x:data"}.
{"Registration in mod_irc for ", "Registrace do mod_irc na "}.
{"Enter username and encodings you wish to use for connecting to IRC servers",
 "Vložte jméno uživatele a kódování, které chcete používat při připojení na IRC server"}.
{"IRC Username", "IRC prezdívka"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].",
 "Příklad: [{\"irc.freenode.net\",\"utf-8\"}, {\irc.freenode.net\", \"iso8859-2\"}]."}.
{"Encodings", "Kódování"}.

% web/ejabberd_web_admin.erl
{"Users", "Uživatelé"}.
{"Nodes", "Uzly"}.
{"Statistics", "Statistiky"}.
{"Submitted", "Odeslané"}.
{"CPU Time:", "Čas procesoru"}.
{"Delete Selected", "Smazat vybrané"}.
{"Submit", "Odeslat"}.
{"~s access rule configuration", "~s konfigurace pravidla přístupu"}.
{"Node not found", "Uzel nenalezen"}.
{"Add New", "Přidat nový"}.
{"Change Password", "Změnit heslo"}.
{"Connected Resources:", "Připojené zdroje:"}.
{"Password:", "Heslo:"}.
{"None", "Nic"}.
{"Node ", "Uzel "}.
{"Restart", "Restart"}.
{"Stop", "Stop"}.
{"Name", "Jméno"}.
{"Storage Type", "Typ úložiště"}.
{"Size", "Velikost"}.
{"Memory", "Paměť"}.
{"OK", "OK"}.
{"Listened Ports at ", "Otevřené porty na "}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Nastavení"}.
{"Update", "Aktualizovat"}.
{"Delete", "Smazat"}.
{"Add User", "Přidat uživatele"}.
{"Last Activity", "Poslední aktivita"}.
{"Never", "Nikdy"}.
{"Time", "Čas"}.
{"From", "Od"}.
{"To", "Pro"}.
{"Packet", "Paket"}.
{"Roster", "Seznam kontaktů"}.
{"Nickname", "Prezdívka"}.
{"Subscription", "Přihlášení"}.
{"Pending", "Čekající"}.
{"Groups", "Skupiny"}.
{"Remove", "Odstranit"}.
{"User ", "Uživatel "}.
{"Roster of ", "Seznam kontaktů "}.
{"Shared Roster", "Sdílený seznam kontaktů"}.
{"Online", "Online"}.
{"Validate", "Ověřit"}.
{"Name:", "Jméno:"}.
{"Description:", "Popis:"}.
{"Members:", "Členové:"}.
{"Displayed Groups:", "Zobrazené skupiny:"}.
{"Group ", "Skupina "}.
{"Period: ", "Čas:"}.
{"Last month", "Poslední měsíc"}.
{"Last year", "Poslední rok"}.
{"All activity", "Všechny aktivity"}.
{"Show Ordinary Table", "Zobrazit bežnou tabulku"}.
{"Show Integral Table", "Zobrazit kompletní tabulku"}.
{"Start", "Start"}.
{"Modules at ", "Moduly na "}.
{"Virtual Hosts", "Virtuální servery"}.
{"ejabberd virtual hosts", "Ejabberd virtuální servery"}.
{"Host", "Server"}.
{"ejabberd Web Interface", "Ejabberd Web rozhraní"}.

% mod_vcard_odbc.erl
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", 
 "Pro vyhledání Jabber uživatele vyplňte formulář (přidejte znak * na konec, pro vyhledání podřetězce)"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Je vyžadováno STARTTLS."}.
{"Replaced by new connection", "Nahrazeno novým spojením"}.

% mod_pubsub/mod_pubsub.erl
{[], " "}.
{"Node Creator", "Majitel uzlu"}.
{"Deliver payloads with event notifications", "Doručovat náklad s upozorněním na událost"}.
{"Notify subscribers when the node configuration changes", "Upozornit členy na změnu nastavení uzlu"}.
{"Notify subscribers when the node is deleted", "Upozornit členy na smazaní uzlu"}.
{"Notify subscribers when items are removed from the node", "Upozornit členy na odstranění položek z uzlu"}.
{"Persist items to storage", "Uložit položky natrvalo do úložiště"}.
{"Max # of items to persist", "Maximální počet položek, které je možné natrvalo uložit"}.
{"Whether to allow subscriptions", "Povolit přihlašování"}.
{"Specify the subscriber model", "Specifikovat přihlašovací model"}.
{"Specify the publisher model", "Specifikovat model pro publikování"}.
{"Max payload size in bytes", "Maximální náklad v bajtech"}.
{"Send items to new subscribers", "Odeslat položky novým uživatelům"}.
{"Only deliver notifications to available users", "Doručovat upozornení jen aktuálně přihlášeným uživatelům"}.
{"Specify the current subscription approver", "Zadat současného schvalovatele přihlášení "}.

% mod_irc/mod_irc.erl
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", 
 "Pokud chcete zadat jiné kódování pro IRC servery, vyplňte seznam s hodnotami ve formátě '{\"irc server\",\"encoding\"}'. Předvolené kódování pro tuto službu je \"~s\"."}.

% mod_muc/mod_muc.erl
{"Room creation is denied by service policy", "Vytváranie miestnosti nie je povolené"}.

% /usr/home/src/ejabberd/ejabberd/src/mod_vcard_odbc.erl
{"Erlang Jabber Server\nCopyright (c) 2002-2006 Alexey Shchepin", 
 "Erlang Jabber Server\nCopyright (c) 2002-2006 Alexey Shchepin"}.
{"Email", "E-mail"}.
{"ejabberd vCard module\nCopyright (c) 2003-2006 Alexey Shchepin",
 "Ejabberd vCard modul\nCopyright (c) 2003-2006 Alexey Shchepin"}.
{"Search Results for ", "Hledat výsledky pro "}.
{"Jabber ID", "Jabber ID"}.

% /usr/home/src/ejabberd/ejabberd/src/mod_adhoc.erl
{"Commands", "Příkazy"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% /usr/home/src/ejabberd/ejabberd/src/ejabberd_c2s.erl
{"Replaced by new connection", "Nahrazeno novým spojením"}.

% /usr/home/src/ejabberd/ejabberd/src/mod_announce.erl
{"Really delete message of the day?", "Skutečně smazat správu dne?"}.
{"Subject", "Předmět"}.
{"Message body", "Tělo zprávy"}.
{"No body provided for announce message", "Zpráva neobsahuje text"}.
{"Announcements", "Oznámení"}.
{"Send announcement to all users", "Odeslat seznam všech uživatelů"}.
{"Send announcement to all online users", "Odeslat seznam všech online uživatelů"}.
{"Send announcement to all online users on all hosts", "Odeslat seznam všech online uživatelů na všech serverech"}.
{"Set message of the day and send to online users", "Nastavit zprávu dne a odeslat jí online uživatelům"}.
{"Update message of the day (don't send)", "Aktualizovat zprávu dne (neodesíelat)"}.
{"Delete message of the day", "Smazat zprávu dne"}.

% /usr/home/src/ejabberd/ejabberd/src/mod_configure.erl
{"Database", "Databáze"}.
{"Outgoing s2s Connections", "Odchozí s2s spojení"}.
{"Import Users From jabberd 1.4 Spool Files", "Importovat uživatelů z jabber 1.4 spool souborů"}.
{"Database Tables Configuration at ", "Konfigurace databázových tabulek "}.

% /usr/home/src/ejabberd/ejabberd/src/mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module\nCopyright (c) 2003-2006 Alexey Shchepin", 
 "ejabberd pub/sub modul\nCopyright (c) 2003-2006 Alexey Shchepin"}.

% /usr/home/src/ejabberd/ejabberd/src/web/ejabberd_web_admin.erl
{"ejabberd Web Interface", "Ejabberd Web rozhraní"}.
{"Administration", "Administrace"}.
{"ejabberd (c) 2002-2006 Alexey Shchepin, 2004-2006 Process One", 
 "Ejabberd (c) 2002-2006 Alexey Shchepin, 2004-2006 Process One"}.
{"(Raw)", "(Zdroj)"}.
{"Bad format", "Nesprávný formát"}.
{"Raw", "Zdroj"}.
{"Users Last Activity", "Poslední aktivita uživatele"}.
{"Registered Users", "Registrovaní uživatelé"}.
{"Offline Messages", "Offline zprávy"}.
{"Registered Users:", "Registrovaní živatelé:"}.
{"Authenticated Users:", "Ověření uživatelé:"}.
{"Online Users:", "Online uživatelé:"}.
{"Outgoing s2s Connections:", "Odchozí s2s spojení:"}.
{"Outgoing s2s Servers:", "Odchozí s2s servery:"}.
{"Offline Messages:", "Offline zprávy"}.
{"~s's Offline Messages Queue", "~s Offline zpráv"}.
{"Add Jabber ID", "Přidat JID"}.
{"No Data", "Žádná data"}.
{"Listened Ports", "Otevřené porty"}.
{"RPC Call Error", "Chyba RPC volání"}.
{"Database Tables at ", "Databázové tabulky na "}.
{"Backup of ", "Záloha na "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", 
 "Podotýkáme, že tato nastavení budou zálohované do zabudované databáze Mnesia. Pokud používáte ODBC modul, musíte zálohovat vaší SQL databázi separátně."}.
{"Store binary backup:", "Uložit binární zálohu:"}.
{"Restore binary backup immediately:", "Okamžitě obnovit binární zálohu:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", 
 "Obnovit binární zálohu při následujícím restartu Ejabberd (vyžaduje méně paměti)"}.
{"Store plain text backup:", "Uložit zálohu do textového souboru:"}.
{"Restore plain text backup immediately:", "Okamžitě obnovit zálohu z textového souboru:"}.
{"Statistics of ~p", "Statistiky ~p"}.
{"Uptime:", "Čas běhu"}.
{"Transactions Commited:", "Transakce potvrzena"}.
{"Transactions Aborted:", "Transakce zrušena"}.
{"Transactions Restarted:", "Transakce restartována"}.
{"Transactions Logged:", "Transakce zaznamenána"}.
{"Update ", "Aktualizovat "}.
{"Update plan", "Aktualizovat plán"}.
{"Updated modules", "Aktualizované moduly"}.
{"Update script", "Aktualizované skripty"}.
{"Low level update script", "Nízkoúrovňový aktualizační skript"}.
{"Script check", "Kontrola skriptu"}.
{"Not Found", "Nenalezeno"}.
{"Shared Roster Groups", "Skupiny pro zdílený seznam kontaktů"}.

% /usr/home/src/ejabberd/ejabberd/src/mod_irc/mod_irc.erl
{"ejabberd IRC module\nCopyright (c) 2003-2006 Alexey Shchepin", "Ejabberd IRC modul\nCopyright (c) 2003-2006 Alexey Shchepin"}.

% /usr/home/src/ejabberd/ejabberd/src/mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Nastavení diskuzní místnosti bylo změněno"}.
{"joins the room", "vstoupil(a) do místnosti"}.
{"leaves the room", "opustil(a) místnost"}.
{"has been kicked", "byl(a) vyhozen(á) z místnosti"}.
{"has been banned", "byl(a) zablokován(a)"}.
{"is now known as", "se přejmenoval(a) na"}.
{"Monday", "Pondělí"}.
{"Tuesday", "Úterý"}.
{"Wednesday", "Středa"}.
{"Thursday", "Čtvrtek"}.
{"Friday", "Pátek"}.
{"Saturday", "Sobota"}.
{"Sunday", "Neděle"}.
{"January", "Leden"}.
{"February", "Únor"}.
{"March", "Březen"}.
{"April", "Duben"}.
{"May", "Květen"}.
{"June", "Červen"}.
{"July", "Červenec"}.
{"August", "Srpen"}.
{"September", "Září"}.
{"October", "říjen"}.
{"November", "Listopad"}.
{"December", "Prosinec"}.
{"Room Configuration", "Nastavení místnosti"}.

% /usr/home/src/ejabberd/ejabberd/src/mod_muc/mod_muc.erl
{"You must fill in field \"Nickname\" in the form", 
 "Musíte vyplnit políčko \"Prezdívka\" ve formuláři"}.
{"ejabberd MUC module\nCopyright (c) 2003-2006 Alexey Shchepin", 
 "Ejabberd MUC modul\nCopyright (c) 2003-2006 Alexey Shchepin"}.

% /usr/home/src/ejabberd/ejabberd/src/mod_muc/mod_muc_room.erl
{"This room is not anonymous", "Tato místnost není anonymní"}.
{"Make room persistent", "Nastavit místnost jako stálou"}.
{"Make room public searchable", "Nastavit místnost jako veřejně prohldávatelnou"}.
{"Make participants list public", "Nastavit seznam účastníků jako veřejný"}.
{"Make room password protected", "Chránit místnost heslem"}.
{"Make room members-only", "Nastavit místnost jen pro členy"}.
{"Make room moderated", "Nastavit místnost jako moderovanou"}.
{"Default users as participants", "Uživatelé jsou implicitně členy"}.
{"Allow users to change subject", "Povolit uživatelům měnit téma této místnosti"}.
{"Allow users to send private messages", "Povolit uživatelům odesíelat soukromé zprávy"}.
{"Allow users to query other users", "Povolit uživatelům odesíela požadavky (query) ostatním uživatelům"}.
{"Allow users to send invites", "povolit uživatelům posíelání pozvánek"}.
{"Enable logging", "Zapnout ukládání historie"}.
{"Description", "Popis"}.
{"Number of occupants", "Počet účastníků"}.

% Local Variables:
% mode: erlang
% End:
