% $Id$
% Language: Czech (čeština)
% Author: Lukáš Polívka [spike411] xmpp:spike411@jabber.cz
% Author: Milos Svasek [DuxforD] from openheads.net

% jlib.hrl
{"No resource provided", "Nebyl poskytnut žádný zdroj"}.

% mod_configure.erl
{"Choose storage type of tables", "Vyberte typ úložiště pro tabulky"}.
{"RAM copy", "Kopie RAM"}.
{"RAM and disc copy", "Kopie RAM a disku"}.
{"Disc only copy", "Jen kopie disku"}.
{"Remote copy", "Vzdálená kopie"}.
{"Stop Modules at ", "Zastavit moduly na "}.
{"Choose modules to stop", "Vyberte moduly, které mají být zastaveny"}.
{"Start Modules at ", "Spustit moduly na "}.
{"Enter list of {Module, [Options]}", "Vložte seznam modulů {Modul, [Parametry]}"}.
{"List of modules to start", "Seznam modulů, které mají být spuštěné"}.
{"Backup to File at ", "Záloha do souboru na "}.
{"Enter path to backup file", "Zadajte cestu k souboru se zálohou"}.
{"Path to File", "Cesta k souboru"}.
{"Restore Backup from File at ", "Obnovit zálohu ze souboru na "}.
{"Dump Backup to Text File at ", "Uložit zálohu do textového souboru na "}.
{"Enter path to text file", "Zadajte cestu k textovému souboru"}.
{"Import User from File at ", "Importovat uživatele ze souboru na "}.
{"Enter path to jabberd1.4 spool file", "Zadejte cestu k spool souboru jabberd1.4"}.
{"Import Users from Dir at ", "Importovat uživatele z adresáře na "}.
{"Enter path to jabberd1.4 spool dir", "Zadejte cestu k jabberd1.4 spool adresáři"}.
{"Path to Dir", "Cesta k adresáři"}.
{"Access Control List Configuration", "Konfigurace seznamu přístupových práv (ACL)"}.
{"Access control lists", "Seznamy přístupových práv (ACL)"}.
{"Access Configuration", "Konfigurace přístupů"}.
{"Access rules", "Pravidla přístupů"}.
{"Administration of ", "Administrace "}.
{"Action on user", "Akce aplikovaná na uživatele"}.
{"Edit Properties", "Upravit vlastnosti"}.
{"Remove User", "Odstranit uživatele"}.
{"Restart Service", "Restartovat službu"}.
{"Shut Down Service", "Vypnout službu"}.
{"Delete User", "Smazat uživatele"}.
{"End User Session", "Ukončit sezení uživatele"}.
{"Get User Password", "Získat heslo uživatele"}.
{"Change User Password", "Změnit heslo uživatele"}.
{"Get User Last Login Time", "Získat čas podleního přihlášení uživatele"}.
{"Get User Statistics", "Získat statistiky uživatele"}.
{"Get Number of Registered Users", "Získat počet registrovaných uživatelů"}.
{"Get Number of Online Users", "Získat počet online uživatelů"}.
{"User Management", "Správa uživatelů"}.
{"Time delay", "Časový posun"}.
{"Password Verification", "Ověření hesla"}.
{"Number of registered users", "Počet registrovaných uživatelů"}.
{"Number of online users", "Počet online uživatelů"}.
{"Last login", "Poslední přihlášení"}.
{"Roster size", "Velikost seznamu kontaktů"}.
{"IP addresses", "IP adresy"}.
{"Resources", "Zdroje"}.

% mod_disco.erl
{"Configuration", "Konfigurace"}.
{"Online Users", "Online uživatelé"}.
{"All Users", "Všichni uživatelé"}.
{"To ~s", "Pro ~s"}.
{"From ~s", "Od  ~s"}.
{"Running Nodes", "Běžící uzly"}.
{"Stopped Nodes", "Zastavené uzly"}.
{"Access Control Lists", "Seznamy přístupových práv (ACL)"}.
{"Access Rules", "Pravidla přístupů"}.
{"Modules", "Moduly"}.
{"Start Modules", "Spustit moduly"}.
{"Stop Modules", "Zastavit moduly"}.
{"Backup Management", "Správa zálohování"}.
{"Backup", "Zálohovat"}.
{"Restore", "Obnovit"}.
{"Dump to Text File", "Uložit do textového souboru"}.
{"Import File", "Import souboru"}.
{"Import Directory", "Import adresáře"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Zadejte jméno uživatele a heslo pro registraci na tomto serveru"}.

% mod_vcard.erl
{"You need an x:data capable client to search", "K vyhledávání potřebujete klienta podporujícího x:data"}.
{"Search users in ", "Hledat uživatele v "}.
{"Fill in fields to search for any matching Jabber User", "Vyplňte políčka pro vyhledání uživatele Jabberu"}.

{"User",              "Uživatel: "}.
{"Full Name", 	      "Celé jméno: "}.
{"Name", 	      "Jméno: "}.
{"Middle Name",       "Druhé jméno: "}.
{"Family Name",       "Příjmení: "}.
{"Nickname", 	      "Přezdívka: "}.
{"Birthday", 	      "Datum narození: "}.
{"Country", 	      "Země: "}.
{"City", 	      "Město: "}.
{"Organization Name", "Název firmy: "}.
{"Organization Unit", "Oddělení: "}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "K registraci přezdívky potřebujete klienta podporujícího x:data"}.
{"Nickname Registration at ", "Registrace prezdívky na "}.
{"Enter nickname you want to register", "Zadejte přezdívku, kterou chcete zaregistrovat"}.
{"Only service administrators are allowed to send service messages", "Pouze správci služby mají povolené odesílání servisních zpráv"}.
{"Conference room does not exist", "Konferenční místnost neexistuje"}.
{"Access denied by service policy", "Přístup byl zamítnut nastavením služby"}.
{"Specified nickname is already registered", "Zadaná přezdívka je již zaregistrována"}.

% mod_muc/mod_muc_room.erl
{"Make room moderated", "Nastavit místnost jako moderovanou"}.
{" has set the subject to: ", " změnil(a) téma na: "}.
{"You need an x:data capable client to configure room", "Ke konfiguraci místnosti potřebujete klienta podporujícího x:data"}.
{"Configuration for ", "Konfigurace pro "}.
{"Room title", "Název místnosti"}.
{"Password", "Heslo"}.
{"Only moderators and participants are allowed to change subject in this room", "Jen moderátoři a účastníci mají povoleno měnit téma této místnosti"}.
{"Only moderators are allowed to change subject in this room", "Jen moderátoři mají povoleno měnit téma místnosti"}.
{"Visitors are not allowed to send messages to all occupants", "Návštevníci nemají povoleno zasílat zprávy všem přihlášeným do konference"}.
{"Only occupants are allowed to send messages to the conference", "Jen členové mají povolené zasílat správy do konference"}.
{"It is not allowed to send private messages to the conference", "Není povoleno odesílat soukromé zprávy do konference"}.
{"Improper message type", "Nesprávný typ zprávy"}.
{"Nickname is already in use by another occupant", "Přezdívka je již používána jiným členem"}.
{"Nickname is registered by another person", "Přezdívka je zaregistrována jinou osobou"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Není dovoleno odeslání soukromé zprávy typu \"skupinová zpráva\" "}.
{"Recipient is not in the conference room", "Příjemce se nenachází v konferenční místnosti"}.
{"Only occupants are allowed to send queries to the conference", "Jen členové mohou odesílat požadavky (query) do konference"}.
{"Queries to the conference members are not allowed in this room", "Požadavky (queries) na členy konference nejsou v této místnosti povolené"}.
{"You have been banned from this room", "Byl jste vyloučen z této místnosti"}.
{"Membership required to enter this room", "Pro vstup do místnosti musíte být členem"}.
{"Password required to enter this room", "Pro vstup do místnosti musíte zadat heslo"}.
{"Incorrect password", "Nesprávné heslo"}.
{"Administrator privileges required", "Jsou potřebná práva administrátora"}.
{"Moderator privileges required", "Jsou potřebná práva moderátora"}.
{"JID ~s is invalid", "JID ~s je neplatné"}.
{"Nickname ~s does not exist in the room", "Přezdívka ~s v místnosti neexistuje"}.
{"Invalid affiliation: ~s", "Neplatné přiřazení: ~s"}.
{"Invalid role: ~s", "Neplatná role: ~s"}.
{"Owner privileges required", "Jsou vyžadována práva vlastníka"}.
{"private, ", "soukromá, "}.
{"Present real JIDs to", "Odhalovat skutečná Jabber ID"}.
{"moderators only", "moderátorům"}.
{"anyone", "každému"}.
{"Traffic rate limit is exceeded", "Byl překročen limit"}.
{"Maximum Number of Occupants", "Počet účastníků"}.
{"No limit", "Bez limitu"}.
{"~s invites you to the room ~s", "~s vás zve do místnosti ~s"}.
{"the password is", "heslo je"}.

% mod_irc/mod_irc.erl
{"You need an x:data capable client to configure mod_irc settings", "Pro konfiguraci mod_irc potřebujete klienta podporujícího x:data"}.
{"Registration in mod_irc for ", "Registrace do mod_irc na "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Vložte jméno uživatele a kódování, které chcete používat při připojení na IRC server"}.
{"IRC Username", "IRC přezdívka"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Příklad: [{\"irc.freenode.net\",\"utf-8\"}, {\irc.freenode.net\", \"iso8859-2\"}]."}.
{"Encodings", "Kódování"}.
{"IRC Transport", "IRC transport"}.

% web/ejabberd_web_admin.erl
{"Users", "Uživatelé"}.
{"Nodes", "Uzly"}.
{"Statistics", "Statistiky"}.
{"Submitted", "Odeslané"}.
{"CPU Time:", "Čas procesoru"}.
{"Delete Selected", "Smazat vybrané"}.
{"Submit", "Odeslat"}.
{"~s access rule configuration", "~s konfigurace pravidla přístupu"}.
{"Node not found", "Uzel nenalezen"}.
{"Add New", "Přidat nový"}.
{"Change Password", "Změnit heslo"}.
{"Connected Resources:", "Připojené zdroje:"}.
{"Password:", "Heslo:"}.
{"None", "Nic"}.
{"Node ", "Uzel "}.
{"Restart", "Restart"}.
{"Stop", "Stop"}.
{"Name", "Jméno"}.
{"Storage Type", "Typ úložiště"}.
{"Size", "Velikost"}.
{"Memory", "Paměť"}.
{"OK", "OK"}.
{"Listened Ports at ", "Otevřené porty na "}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Nastavení"}.
{"Update", "Aktualizovat"}.
{"Delete", "Smazat"}.
{"Add User", "Přidat uživatele"}.
{"Last Activity", "Poslední aktivita"}.
{"Never", "Nikdy"}.
{"Time", "Čas"}.
{"From", "Od"}.
{"To", "Pro"}.
{"Packet", "Paket"}.
{"Roster", "Seznam kontaktů"}.
{"Nickname", "Prezdívka"}.
{"Subscription", "Přihlášení"}.
{"Pending", "Čekající"}.
{"Groups", "Skupiny"}.
{"Remove", "Odstranit"}.
{"User ", "Uživatel "}.
{"Roster of ", "Seznam kontaktů "}.
{"Online", "Online"}.
{"Validate", "Ověřit"}.
{"Name:", "Jméno:"}.
{"Description:", "Popis:"}.
{"Members:", "Členové:"}.
{"Displayed Groups:", "Zobrazené skupiny:"}.
{"Group ", "Skupina "}.
{"Period: ", "Čas:"}.
{"Last month", "Poslední měsíc"}.
{"Last year", "Poslední rok"}.
{"All activity", "Všechny aktivity"}.
{"Show Ordinary Table", "Zobrazit běžnou tabulku"}.
{"Show Integral Table", "Zobrazit kompletní tabulku"}.
{"Start", "Start"}.
{"Modules at ", "Moduly na "}.
{"Virtual Hosts", "Virtuální hostitelé"}.
{"ejabberd virtual hosts", "Virtuální hostitelé ejabberd"}.
{"Host", "Hostitel"}.
{"ejabberd Web Interface", "Webové rozhraní ejabberd"}.

% mod_vcard_odbc.erl
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Pro vyhledání uživatele Jabberu vyplňte formulář (přidejte znak * na konec, pro vyhledání podřetězce)"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Je vyžadováno STARTTLS."}.
{"Replaced by new connection", "Nahrazeno novým spojením"}.

% mod_pubsub/mod_pubsub.erl
{"Deliver payloads with event notifications", "Doručovat náklad s upozorněním na událost"}.
{"Notify subscribers when the node configuration changes", "Upozornit odběratele na změnu nastavení uzlu"}.
{"Notify subscribers when the node is deleted", "Upozornit odběratele na smazání uzlu"}.
{"Notify subscribers when items are removed from the node", "Upozornit odběratele na odstranění položek z uzlu"}.
{"Persist items to storage", "Uložit položky natrvalo do úložiště"}.
{"Max # of items to persist", "Maximální počet položek, které je možné natrvalo uložit"}.
{"Whether to allow subscriptions", "Povolit odebírání"}.
{"Specify the publisher model", "Specifikovat model pro publikování"}.
{"Max payload size in bytes", "Maximální náklad v bajtech"}.
{"Only deliver notifications to available users", "Doručovat upozornění jen právě přihlášeným uživatelům"}.
{"Publish-Subscribe", "Publish-Subscribe"}.
{"ejabberd Publish-Subscribe module", "ejabberd Publish-Subscribe modul"}.
{"PubSub subscriber request", "Žádost odběratele PubSub"}.
{"Choose whether to approve this entity's subscription.", "Zvolte, zda chcete schválit odebírání touto entitou"}.
{"Node ID", "ID uzlu"}.
{"Subscriber Address", "Adresa odběratele"}.
{"Allow this JID to subscribe to this pubsub node?", "Povolit tomuto JID odebírat tento pubsub uzel?"}.
{"Deliver event notifications", "Doručovat upozornění na události"}.
{"Specify the access model", "Uveďte přístupový model"}.
{"Roster groups that may subscribe (if access model is roster)", "Skupiny kontaktů, které mohou odebírat (pokud je přístupový model seznam kontaktů)"}.
{"When to send the last published item", "Kdy odeslat poslední publikovanou položku"}.

% mod_irc/mod_irc.erl
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Pokud chcete zadat jiné kódování pro IRC servery, vyplňte seznam s hodnotami ve formátu '{\"irc server\",\"encoding\"}'. Předvolené kódování pro tuto službu je \"~s\"."}.

% mod_muc/mod_muc.erl
{"Room creation is denied by service policy", "Pravidla služby nepovolují vytvořit místnost"}.

% mod_vcard_odbc.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"Email", "E-mail"}.
{"ejabberd vCard module", "ejabberd vCard modul"}.
{"Search Results for ", "Výsledky hledání pro "}.
{"Jabber ID", "Jabber ID"}.

% mod_adhoc.erl
{"Commands", "Příkazy"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% ejabberd_c2s.erl
{"Replaced by new connection", "Nahrazeno novým spojením"}.

% mod_announce.erl
{"Really delete message of the day?", "Skutečně smazat zprávu dne?"}.
{"Subject", "Předmět"}.
{"Message body", "Tělo zprávy"}.
{"No body provided for announce message", "Zpráva neobsahuje text"}.
{"Announcements", "Oznámení"}.
{"Send announcement to all users", "Odeslat oznámení všem uživatelům"}.
{"Send announcement to all online users", "Odeslat oznámení všem online uživatelům"}.
{"Send announcement to all online users on all hosts", "Odeslat oznámení všem online uživatelům na všech hostitelích"}.
{"Set message of the day and send to online users", "Nastavit zprávu dne a odeslat ji online uživatelům"}.
{"Update message of the day (don't send)", "Aktualizovat zprávu dne (neodesílat)"}.
{"Delete message of the day", "Smazat zprávu dne"}.
{"Send announcement to all users on all hosts", "Odeslat oznámení všem uživatelům na všech hostitelích"}.
{"Set message of the day on all hosts and send to online users", "Nastavit zprávu dne a odeslat ji online uživatelům"}.
{"Update message of the day on all hosts (don't send)", "Aktualizovat zprávu dne pro všechny hostitele (neodesílat)"}.
{"Delete message of the day on all hosts", "Smazat zprávu dne na všech hostitelích"}.

% mod_configure.erl
{"Database", "Databáze"}.
{"Outgoing s2s Connections", "Odchozí s2s spojení"}.
{"Import Users From jabberd 1.4 Spool Files", "Importovat uživatele z jabberd 1.4 spool souborů"}.
{"Database Tables Configuration at ", "Konfigurace databázových tabulek "}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Interface", "Ejabberd Web rozhraní"}.
{"Administration", "Administrace"}.
{"(Raw)", "(Zdroj)"}.
{"Bad format", "Nesprávný formát"}.
{"Raw", "Zdroj"}.
{"Users Last Activity", "Poslední aktivita uživatele"}.
{"Registered Users", "Registrovaní uživatelé"}.
{"Offline Messages", "Offline zprávy"}.
{"Registered Users:", "Registrovaní živatelé:"}.
{"Online Users:", "Online uživatelé:"}.
{"Outgoing s2s Connections:", "Odchozí s2s spojení:"}.
{"Outgoing s2s Servers:", "Odchozí s2s servery:"}.
{"Offline Messages:", "Offline zprávy"}.
{"~s's Offline Messages Queue", "Fronta offline zpráv uživatele ~s"}.
{"Add Jabber ID", "Přidat JID"}.
{"No Data", "Žádná data"}.
{"Listened Ports", "Otevřené porty"}.
{"RPC Call Error", "Chyba RPC volání"}.
{"Database Tables at ", "Databázové tabulky na "}.
{"Backup of ", "Záloha na "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Podotýkáme, že tato nastavení budou zálohována do zabudované databáze Mnesia. Pokud používáte ODBC modul, musíte zálohovat svoji SQL databázi samostatně."}.
{"Store binary backup:", "Uložit binární zálohu:"}.
{"Restore binary backup immediately:", "Okamžitě obnovit binární zálohu:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Obnovit binární zálohu při následujícím restartu ejabberd (vyžaduje méně paměti)"}.
{"Store plain text backup:", "Uložit zálohu do textového souboru:"}.
{"Restore plain text backup immediately:", "Okamžitě obnovit zálohu z textového souboru:"}.
{"Statistics of ~p", "Statistiky ~p"}.
{"Uptime:", "Čas běhu"}.
{"Transactions Commited:", "Transakce potvrzena"}.
{"Transactions Aborted:", "Transakce zrušena"}.
{"Transactions Restarted:", "Transakce restartována"}.
{"Transactions Logged:", "Transakce zaznamenána"}.
{"Update ", "Aktualizovat "}.
{"Update plan", "Aktualizovat plán"}.
{"Updated modules", "Aktualizované moduly"}.
{"Update script", "Aktualizované skripty"}.
{"Low level update script", "Nízkoúrovňový aktualizační skript"}.
{"Script check", "Kontrola skriptu"}.
{"Shared Roster Groups", "Skupiny pro sdílený seznam kontaktů"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "Ejabberd IRC modul"}.

% mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "byl(a) vyhozen(a) kvůli změně přiřazení"}.
{"has been kicked because the room has been changed to members-only", "byl(a) vyhozen(a), protože mísnost je nyní pouze pro členy"}.
{"has been kicked because of a system shutdown", "byl(a) vyhozen(a), protože dojde k vypnutí systému"}.
{"Chatroom configuration modified", "Nastavení diskuzní místnosti bylo změněno"}.
{"joins the room", "vstoupil(a) do místnosti"}.
{"leaves the room", "opustil(a) místnost"}.
{"has been kicked", "byl(a) vyhozen(a) z místnosti"}.
{"has been banned", "byl(a) zablokován(a)"}.
{"is now known as", "se přejmenoval(a) na"}.
{"Monday", "Pondělí"}.
{"Tuesday", "Úterý"}.
{"Wednesday", "Středa"}.
{"Thursday", "Čtvrtek"}.
{"Friday", "Pátek"}.
{"Saturday", "Sobota"}.
{"Sunday", "Neděle"}.
{"January", ". ledna"}.
{"February", ". února"}.
{"March", ". března"}.
{"April", ". dubna"}.
{"May", ". května"}.
{"June", ". června"}.
{"July", ". července"}.
{"August", ". srpna"}.
{"September", ". září"}.
{"October", ". října"}.
{"November", ". listopadu"}.
{"December", ". prosince"}.
{"Room Configuration", "Nastavení místnosti"}.

% mod_muc/mod_muc.erl
{"You must fill in field \"Nickname\" in the form", "Musíte vyplnit políčko \"Přezdívka\" ve formuláři"}.
{"ejabberd MUC module", "Ejabberd MUC modul"}.
{"Chatrooms", "Konference"}.

% mod_muc/mod_muc_room.erl
{"This room is not anonymous", "Tato místnost není anonymní"}.
{"Make room persistent", "Nastavit místnost jako stálou"}.
{"Make room public searchable", "Nastavit místnost jako veřejnou"}.
{"Make participants list public", "Nastavit seznam účastníků jako veřejný"}.
{"Make room password protected", "Chránit místnost heslem"}.
{"Make room members-only", "Nastavit místnost jen pro členy"}.
{"Default users as participants", "Uživatelé jsou implicitně členy"}.
{"Allow users to change subject", "Povolit uživatelům měnit téma místnosti"}.
{"Allow users to send private messages", "Povolit uživatelům odesílat soukromé zprávy"}.
{"Allow users to query other users", "Povolit uživatelům odesílat požadavky (query) ostatním uživatelům"}.
{"Allow users to send invites", "Povolit uživatelům posílání pozvánek"}.
{"Enable logging", "Zaznamenávat konverzace"}.
{"Number of occupants", "Počet účastníků"}.

% mod_vcard_odbc.erl
{"vCard User Search", "Hledání uživatelů podle vizitek"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Fronta offline zpráv pro váš kontakt je plná. Zpráva byla zahozena."}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams modul"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
