% $Id$

% jlib.hrl
{"No resource provided", "Keine Ressource zur Verfügung"}.

% mod_configure.erl
{"Choose storage type of tables", "Wähle Speichertyp der Tabellen"}.
{"RAM copy", "Kopie im RAM"}.
{"RAM and disc copy", "Kopie im RAM und auf der Festplatte"}.
{"Disc only copy", "Kopie nur auf Festplatte"}.
{"Remote copy", "Fernkopie"}.
{"Stop Modules at ", "Stop Module bei "}.
{"Choose modules to stop", "Wähle zu stoppende Module"}.
{"Start Modules at ", "Start Module bei "}.
{"Enter list of {Module, [Options]}", "Geben Sie die Liste der Module ein {Module, [Optionen]}"}.
{"List of modules to start", "Liste der zu startenden Module"}.
{"Backup to File at ", "Datensicherung bei "}.
{"Enter path to backup file", "Geben Sie den Pfad zur Datensicherung ein"}.
{"Path to File", "Pfad zur Datei"}.
{"Restore Backup from File at ", "Datenwiederherstellung von Datei "}.
{"Dump Backup to Text File at ", "Ausgabe der Sicherung in diese Textdatei "}.
{"Enter path to text file", "Geben Sie den Pfad zur Textdatei ein"}.
{"Import User from File at ", "Benutzer aus dieser Datei importieren "}.
{"Enter path to jabberd1.4 spool file", "Geben Sie den Pfad zur jabberd1.4 spool Datei ein"}.
{"Import Users from Dir at ", "Benutzer vom Verzeichnis importieren "}.
{"Enter path to jabberd1.4 spool dir", "Geben Sie den Pfad zum jabberd1.4 spool Verzeichnis ein"}.
{"Path to Dir", "Pfad zum Verzeichnis"}.
{"Hostname Configuration", "Konfiguration des Hostnamens"}.
{"Choose host name", "Wählen Sie den Hostnamen"}.
{"Host name", "Hostname"}.
{"Access Control List Configuration", "Access Control List(ACL) Konfiguration"}.
{"Access control lists", "Access Control Listen"}.
{"Access Configuration", "Zugangskonfiguration"}.
{"Access rules", "Zugangsregeln"}.
{"Remove Users", "Benutzer löschen"}.
{"Choose users to remove", "Wählen Sie die zu löschenden Benutzer"}.
{"Administration of ", "Administration der "}.
{"Action on user", "Aktion auf Benutzer"}.
{"Edit Properties", "Einstellungen ändern"}.
{"Remove User", "Benutzer löschen"}.

% mod_disco.erl
{"Configuration", "Konfiguration"}.
{"Online Users", "Online Benutzer"}.
{"All Users", "Alle Benutzer"}.
{"To ~s", "An ~s"}.
{"From ~s", "Von  ~s"}.
{"Running Nodes", "Aktive Knoten"}.
{"Stopped Nodes", "Inaktive Knoten"}.
{"Host Name", "Hostname"}.
{"Access Control Lists", "Zugangskontrolllisten"}.
{"Access Rules", "Zugangsregeln"}.
{"Remove Users", "Benutzer löschen"}.
{"Modules", "Module"}.
{"Start Modules", "Module starten"}.
{"Stop Modules", "Module stoppen"}.
{"Backup Management", "Datensicherungsmanagement"}.
{"Backup", "Sicherung"}.
{"Restore", "Wiederherstellung"}.
{"Dump to Text File", "Ausgabe in Textdatei"}.
{"Import File", "Datei importieren"}.
{"Import Directory", "Verzeichnis importieren"}.

% mod_register.erl
{"Choose a username and password to register with this server",
 "Wählen Sie zum Registrieren einen Benutzernamen und ein Passwort"}.

% mod_vcard.erl
{"ejabberd vCard module\nCopyright (c) 2003-2006 Alexey Shchepin", "ejabberd vCard module\nCopyright (c) 2003-2006 Alexey Shchepin"}.
{"You need an x:data capable client to search",
 "Sie brauchen einen x:data kompatiblen Client um suchen zu können"}.
{"Search users in ", "Benutzer suchen in "}.
{"Fill in fields to search for any matching Jabber User",
 "Felder ausfüllen, um nach passenden Jabber Benutzern zu suchen"}.

{"User",              "Benutzer"}.
{"Full Name", 	      "Ganzer Name"}.
{"Name", 	      "Vorname"}.
{"Middle Name",       "Mittelname"}.
{"Family Name",       "Nachname"}.
{"Nickname", 	      "Spitzname"}.
{"Birthday", 	      "Geburtsdatum"}.
{"Country", 	      "Land"}.
{"City", 	      "Stadt"}.
{"Organization Name", "Firmenname"}.
{"Organization Unit", "Abteilung"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module\nCopyright (c) 2003-2006 Alexey Shchepin", "ejabberd pub/sub module\nCopyright (c) 2003-2006 Alexey Shchepin"}.
{[], " "}.
{"Node Creator", "Knoten Erschaffer"}.
{"Deliver payloads with event notifications", "Nutzlast mit Benachrichtigungen versenden"}.
{"Notify subscribers when the node configuration changes", "Benutzer benachrichtigen, wenn die Knotenkonfiguration sich ändert"}.
{"Notify subscribers when the node is deleted", "Benutzer benachrichtigen, wenn der Knoten gelöscht wird"}.
{"Notify subscribers when items are removed from the node", "Benutzer benachrichtigen, wenn Einträge vom Knoten entfernt werden"}.
{"Persist items to storage", "Einträge dauerhaft speichern"}.
{"Max # of items to persist", "Maximale Anzahl dauerhaft zu speichernder Einträge"}.
{"Whether to allow subscriptions", "Ob Abonnements erlaubt sind"}.
{"Specify the subscriber model", "Geben Sie das Abonnementsmodell an"}.
{"Specify the publisher model", "Geben Sie das Publikationsmodell an"}.
{"Max payload size in bytes", "Maximale Nutzlastgröße in Bytes"}.
{"Send items to new subscribers", "Einträge an neue Abonnenten schicken"}.
{"Only deliver notifications to available users", "Benachrichtigungen nur an User schicken, die verfügbar sind"}.
{"Specify the current subscription approver", "Geben Sie an, wer die Abonnements bestätigt"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname",
 "Sie brauchen einen für x:data geeigneten Client, um sich mit dem Spitznamen zu registrieren"}.
{"Nickname Registration at ", "Registrieren des Spitznamens "}.
{"Enter nickname you want to register", "Geben Sie den zu registrierenden Spitznamen ein"}.
{"ejabberd MUC module\nCopyright (c) 2003-2006 Alexey Shchepin", "ejabberd MUC module\nCopyright (c) 2003-2006 Alexey Shchepin"}.
{"Only service administrators are allowed to send service messages",
 "Nur Service Administratoren sind berechtigt, Servicenachrichten zu senden"}.
{"Conference room does not exist", "Konferenzraum existiert nicht"}.
{"Access denied by service policy", "Zutritt verweigert von der Service Policy"}.
{"You must fill in field \"Nickname\" in the form", "Sie müssen etwas ins Feld \"Nickname\" eintragen"}.
{"Specified nickname is already registered", "Der angegebene Name ist bereits vergeben"}.
{"Room creation is denied by service policy", "Anlegen des Raumes aufgrund von Servereinstellungen verweigert"}.

% mod_muc/mod_muc_room.erl
{" has set the subject to: ", " hat das Thema geändert zu "}.
{"You need an x:data capable client to configure room",
 "Sie brauchen einen für x:data geeigneten Client um den Raum zu konfigurieren"}.
{"Configuration for ", "Konfiguration für "}.
{"Room title", "Raumname"}.
{"Password", "Passwort"}.
{"Only moderators and participants are allowed to change subject in this room",
 "Nur Moderatoren und Teilnehmer dürfen das Thema in diesem Raum ändern"}.
{"Only moderators are allowed to change subject in this room",
 "Nur Moderatoren dürfen das Thema in diesem Raum ändern"}.
{"Visitors are not allowed to send messages to all occupants",
 "Besucher dürfen nicht an alle im Raum Nachrichten verschicken"}.
{"Only occupants are allowed to send messages to the conference",
 "Nur Leute im Raum dürfen Nachrichten an die Konferenz schicken"}.
{"It is not allowed to send normal messages to the conference",
 "Es ist nicht erlaubt normale Nachrichten an die Konferenz zu schicken"}.
{"It is not allowed to send private messages to the conference",
 "Es ist nicht erlaubt private Nachrichten an die Konferenz zu schicken"}.
{"Improper message type", "Unzulässiger Nachrichtentyp"}.
{"Nickname is already in use by another occupant", "Spitzname wird schon von jemand anderem genutzt"}.
{"Nickname is registered by another person", "Spitzname wurde schon von jemand anderem registriert"}.
{"It is not allowed to send private messages of type \"groupchat\"",
 "Es ist nicht erlaubt private Nachrichten des Typs \"Gruppenchat\" zu senden"}.
{"Recipient is not in the conference room", "Der Empfänger ist nicht im Konferenzraum"}.
{"Only occupants are allowed to send queries to the conference",
 "Nur Teilnehmer sind berechtig Anfragen an die Konferenz zu senden"}.
{"Queries to the conference members are not allowed in this room",
 "Anfragen an die Konferenzmitglieder sind in diesem Raum nicht erlaubt"}.
{"You have been banned from this room", "Sie wurden aus diesem Raum verbannt"}.
{"Membership required to enter this room", "Um diesen Raum zu betreten müssen sie ein Mitglied sein"}.
{"Password required to enter this room", "Sie brauchen ein Passwort um diesen Raum zu betreten"}.
{"Incorrect password", "Falsches Passwort"}.
{"Administrator privileges required", "Administratorenrechte benötigt"}.
{"Moderator privileges required", "Moderatorrechte benötigt"}.
{"JID ~s is invalid", "JID ~s ist ungültig"}.
{"Nickname ~s does not exist in the room", "Spitzname ~s funktioniert im Raum nicht"}.
{"Invalid affiliation: ~s", "Ungültige Option: ~s"}.
{"Invalid role: ~s", "Ungültige Funktion: ~s"}.
{"Owner privileges required", "Besitzerrechte benötigt"}.
{"private, ", "privat"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module\nCopyright (c) 2003-2006 Alexey Shchepin", "ejabberd IRC module\nCopyright (c) 2003-2006 Alexey Shchepin"}.
{"You need an x:data capable client to configure mod_irc settings",
 "Sie brauchen einen x:data kompatiblen Client um die mod_irc Einstellungen zu konfigurieren"}.
{"Registration in mod_irc for ", "Registrierung in mod_irc für "}.
{"Enter username and encodings you wish to use for connecting to IRC servers",
 "Geben Sie Benutzernamen und Verschlüsselung für die Verbindung zum IRC Server an"}.
{"IRC Username", "IRC Benutzername"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].",
 "Beispiel: [{\"irc.lucky.net\",\"koi8-r\"}, {\vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Verschlüsselungen"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Wenn Sie verschiedene Verschlüsselungen für IRC Server angeben, schreiben Sie diese im Format '{\"irc server\", \"encoding\"}'. Standardmäßig benutzt der Dienst die  \"~s\" Verschlüsselung"}.

% web/ejabberd_web_admin.erl
{"Users", "Benutzer"}.
{"Nodes", "Knoten(nodes)"}.
{"Statistics", "Statistik"}.
{"Delete Selected", "Lösche Markiertes"}.
{"Submit", "Bestätigen"}.
{"~s access rule configuration", "~s Zurtrittsregel Konfiguration"}.
{"Node not found", "Knoten nicht gefunden"}.
{"Add New", "Neuen hinzufügen"}.
{"Change Password", "Passwort ändern"}.
{"Connected Resources:", "Verbundene Resourcen"}.
{"Password:", "Passwort:"}.
{"None", "Keine"}.
{"Node ", "Knoten "}.
{"Restart", "Neustart"}.
{"Stop", "Stop"}.
{"Name", "Name"}.
{"Storage Type", "Speichertyp"}.
{"Size", "Größe"}.
{"Memory", "Speicher"}.
{"OK", "OK"}.
{"Listened Ports at ", "Überwachte Ports "}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Optionen"}.
{"Update", "Aktualisieren"}.
{"Delete", "Löschen"}.
{"Add User", "Benutzer hinzufügen"}.
{"Last Activity", "Letzte Aktion"}.
{"Never", "Nie"}.
{"Time", "Uhrzeit"}.
{"From", "Von"}.
{"To", "Zu"}.
{"Packet", "Paket"}.
{"Roster", "Liste"}.
{"Nickname", "Spitzname"}.
{"Subscription", "Subskription"}.
{"Pending", "schwebend"}.
{"Groups", "Gruppe"}.
{"Remove", "Entfernen"}.
{"User ", "Benutzer "}.
{"Roster of ", "Liste von "}.
{"Virtual Hosts", "Virtuelle Hosts"}.
{"ejabberd (c) 2002-2006 Alexey Shchepin, 2004-2006 Process One", "ejabberd (c) 2002-2006 Alexey Shchepin, 2004-2006 Process One"}.
{"Shared Roster", "Gemeinsame Kontaktliste"}.
{"ejabberd virtual hosts", "ejabberd virtuelle Hosts"}.
{"Period: ", "Zeitraum"}.
{"Last month", "Letzter Monat"}.
{"Last year", "Letztes Jahr"}.
{"All activity", "Alle Aktivitäten"}.
{"Show Ordinary Table", "Normale Tabelle anzeigen"}.
{"Show Integral Table", "Vollständige Tabelle anzeigen"}.
{"Host", "Host"}.
{"Online", "Online"}.
{"Validate", "Validieren"}.
{"Modules at ", "Module auf "}.
{"Start", "Anfang"}.
{"Name:", "Name"}.
{"Description:", "Beschreibung:"}.
{"Members:", "Mitglieder:"}.
{"Displayed Groups:", "Angezeigte Gruppen:"}.
{"Group ", "Gruppe "}.
{"ejabberd Web Interface", "ejabberd Web Interface"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Verwendung von STARTTLS erforderlich"}.
{"Replaced by new connection", "Durch neue Verbindung ersetzt"}.

% mod_vcard_odbc.erl
{"Erlang Jabber Server\nCopyright (c) 2002-2006 Alexey Shchepin", "Erlang Jabber Server\nCopyright (c) 2002-2006 Alexey Shchepin"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Füllen Sie die Felder aus, um nach passenden Jabber benutzern zu suchen (beenden Sie ein Feld mit *, um auch nach Teilzeichenketten zu suchen)"}.
{"Email", "E-Mail"}.
{"Search Results for ", "Suchergebnisse für"}.
{"Jabber ID", "Jabber ID"}.

% mod_adhoc.erl
{"Commands", "Befehle"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Really delete message of the day?", "Wirklich die Nachricht des Tages löschen ?"}.
{"Subject", "Betreff"}.
{"Message body", "Nachrichtentext"}.
{"No body provided for announce message", "Keinen Text für die Ankündigung angegeben"}.
{"Announcements", "Ankündigungen"}.
{"Send announcement to all users", "Sende Ankündigung an alle Benutzer"}.
{"Send announcement to all online users", "Sende Ankündigung an alle online Benutzer"}.
{"Send announcement to all online users on all hosts", "Sende Ankündigung an alle online Benutzer auf allen Hosts"}.
{"Set message of the day and send to online users", "Setze Nachricht des Tages und sende sie an alle online Benutzer"}.
{"Update message of the day (don't send)", "Aktualisiere Nachricht des Tages (nicht senden)"}.
{"Delete message of the day", "Lösche Nachricht des Tages"}.

% mod_configure.erl
{"Database", "Datenbank"}.
{"Outgoing s2s Connections", "Ausgehende s2s Verbindungen"}.
{"Import Users From jabberd 1.4 Spool Files", "Importiere Benutzer von jabberd 1.4 Spool Dateien"}.
{"Database Tables Configuration at ", "Datenbank Tabellen Konfiguration bei "}.

% web/ejabberd_web_admin.erl
{"Administration", "Verwaltung"}.
{"(Raw)", "(Roh)"}.
{"Submitted", "Bestätigt"}.
{"Bad format", "Ungültiges Format"}.
{"Raw", "Roh"}.
{"Users Last Activity", "Letzte Benutzeraktivität"}.
{"Registered Users", "Registrierte Benutzer"}.
{"Offline Messages", "Offline Nachrichten"}.
{"Registered Users:", "Registrierte Benutzer:"}.
{"Authenticated Users:", "Überprüfte Benutzer:"}.
{"Online Users:", "Online Benutzer:"}.
{"Outgoing s2s Connections:", "Ausgehende s2s Verbindungen:"}.
{"Outgoing s2s Servers:", "Ausgehende s2s Server:"}.
{"Offline Messages:", "Offline Nachrichten:"}.
{"~s's Offline Messages Queue", "~s's Offline Nachrichten Warteschlange"}.
{"Add Jabber ID", "Jabber ID hinzufügen"}.
{"No Data", "Keine Daten"}.
{"Listened Ports", "Überwachte Ports"}.
{"RPC Call Error", "RPC Abruf-Fehler"}.
{"Database Tables at ", "Datenbank Tabellen bei "}.
{"Backup of ", "Sicherung von "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Beachten sie, daß diese Optionen nur die eingebaute Mnesia Datenbank sichert. Wenn sie das ODBC Modul verwenden, müssen sie die SQL Datenbank manuell sichern."}.
{"Store binary backup:", "Speichere binäres Sicherung:"}.
{"Restore binary backup immediately:", "Stelle binäre Sicherung sofort wiederher:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Stelle binäre Sicherung beim nächsten ejabberd Neustart wiederher (benötigt weniger Speicher):"}.
{"Store plain text backup:", "Speichere plaintext Sicherung:"}.
{"Restore plain text backup immediately:", "Stelle plaintext Sicherung sofort wiederher:"}.
{"Statistics of ~p", "Statistiken von ~p"}.
{"Uptime:", "Betriebszeit:"}.
{"CPU Time:", "CPU Zeit:"}.
{"Transactions Commited:", "Vorgänge durchgeführt:"}.
{"Transactions Aborted:", "Vorgänge abgebrochen:"}.
{"Transactions Restarted:", "Vorgänge neu gestartet:"}.
{"Transactions Logged:", "Vorgänge protokolliert:"}.
{"Update ", "Aktualisierung"}.
{"Update plan", "Aktualisierungsplan"}.
{"Updated modules", "Aktualisierte Module"}.
{"Update script", "Aktualisierungsscript"}.
{"Low level update script", "Low level Aktualisierungsscript"}.
{"Script check", "Script Überprüfung"}.
{"Not Found", "Nicht gefunden"}.
{"Shared Roster Groups", "Gruppen der gemeinsamen Kontaktliste"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Chatraum Konfiguration verändert"}.
{"joins the room", "kommt in den Raum"}.
{"leaves the room", "verlässt den Raum"}.
{"has been kicked", "wurde gekickt"}.
{"has been banned", "wurde gebannt"}.
{"is now known as", "ist nun bekannt als"}.
{"Monday", "Montag"}.
{"Tuesday", "Dienstag"}.
{"Wednesday", "Mittwoch"}.
{"Thursday", "Donnerstag"}.
{"Friday", "Freitag"}.
{"Saturday", "Samstag"}.
{"Sunday", "Sonntag"}.
{"January", "Jänner"}.
{"February", "Feber"}.
{"March", "März"}.
{"April", "April"}.
{"May", "Mai"}.
{"June", "Juni"}.
{"July", "Juli"}.
{"August", "August"}.
{"September", "September"}.
{"October", "Oktober"}.
{"November", "November"}.
{"December", "Dezember"}.
{"Room Configuration", "Raum Konfiguration"}.

% mod_muc/mod_muc_room.erl
{"This room is not anonymous", "Dieser Raum ist nicht anonym"}.
{"Make room persistent", "Raum persistent machen"}.
{"Make room public searchable", "Raum öffentlich durchsuchbar machen"}.
{"Make participants list public", "Teilnehmerliste öffentlich machen"}.
{"Make room password protected", "Raum passwortgeschützt machen"}.
{"Make room members-only", "Raum members-only machen"}.
{"Make room moderated", "Raum modieriert machen"}.
{"Default users as participants", "Standartbenutzer als Teilnehmer"}.
{"Allow users to change subject", "Erlaube Benutzern Thema zu ändern"}.
{"Allow users to send private messages", "Erlaube Benutzern private Nachrichten zu senden"}.
{"Allow users to query other users", "Erlaube Benutzern andere Benutzer zu sehen(query)"}.
{"Allow users to send invites", "Erlaube Benutzern Einladungen zu senden"}.
{"Enable logging", "Log-Funktion aktivieren"}.
{"Description", "Beschreibung"}.
{"Number of occupants", "Anzahl der Teilnehmer"}.
{"Make real JIDs discovered for", "Echte Jabber IDs anzeigen für"}.
{"moderators only", "nur Moderatoren"}.
{"anyone", "jeden"}.

% Local Variables:
% mode: erlang
% End:
