% $Id$

% jlib.hrl
{"No resource provided", "Keine Ressource zur Verfügung"}.

% mod_configure.erl
{"Choose storage type of tables", "Wähle Speichertyp der Tabellen"}.
{"RAM copy", "Kopie im RAM"}.
{"RAM and disc copy", "Kopie im RAM und auf der Festplatte"}.
{"Disc only copy", "Kopie nur auf Festplatte"}.
{"Remote copy", "Fernkopie"}.
{"Stop Modules at ", "Stop Module bei "}.
{"Choose modules to stop", "Wähle zu stoppende Module"}.
{"Start Modules at ", "Start Module bei "}.
{"Enter list of {Module, [Options]}", "Geben Sie die Liste der Module ein {Module, [Optionen]}"}.
{"List of modules to start", "Liste der zu startenden Module"}.
{"Backup to File at ", "Datensicherung bei "}.
{"Enter path to backup file", "Geben Sie den Pfad zur Datensicherung ein"}.
{"Path to File", "Pfad zur Datei"}.
{"Restore Backup from File at ", "Datenwiederherstellung von Datei "}.
{"Dump Backup to Text File at ", "Ausgabe der Sicherung in diese Textdatei "}.
{"Enter path to text file", "Geben Sie den Pfad zur Textdatei ein"}.
{"Import User from File at ", "Benutzer aus dieser Datei importieren "}.
{"Enter path to jabberd1.4 spool file", "Geben Sie den Pfad zur jabberd1.4 spool Datei ein"}.
{"Import Users from Dir at ", "Benutzer vom Verzeichnis importieren "}.
{"Enter path to jabberd1.4 spool dir", "Geben Sie den Pfad zum jabberd1.4 spool Verzeichnis ein"}.
{"Path to Dir", "Pfad zum Verzeichnis"}.
{"Hostname Configuration", "Konfiguration des Hostnamens"}.
{"Choose host name", "Wählen Sie den Hostnamen"}.
{"Host name", "Hostname"}.
{"Access Control List Configuration", "Access Control List(ACL) Konfiguration"}.
{"Access control lists", "Access Control Listen"}.
{"Access Configuration", "Zugangskonfiguration"}.
{"Access rules", "Zugangsregeln"}.
{"Remove Users", "Benutzer löschen"}.
{"Choose users to remove", "Wählen Sie die zu löschenden Benutzer"}.
{"Administration of ", "Administration der "}.
{"Action on user", "Aktion auf Benutzer"}.
{"Edit Properties", "Einstellungen ändern"}.
{"Remove User", "Benutzer löschen"}.
{"DB Tables Configuration at ", "DB Tabellenkonfiguration auf "}.

% mod_disco.erl
{"Configuration", "Konfiguration"}.
{"Online Users", "Online Benutzer"}.
{"All Users", "Alle Benutzer"}.
{"Outgoing S2S connections", "Rausgehende S2S Verbindungen"}.
{"To ~s", "An ~s"}.
{"From ~s", "Vom  ~s"}.
{"Running Nodes", "Aktive Knoten"}.
{"Stopped Nodes", "Inaktive Knoten"}.
{"Host Name", "Hostname"}.
{"Access Control Lists", "Zugangskontrolllisten"}.
{"Access Rules", "Zugangsregeln"}.
{"Remove Users", "Benutzer löschen"}.
{"DB", "DB"}.
{"Modules", "Module"}.
{"Start Modules", "Module starten"}.
{"Stop Modules", "Module stoppen"}.
{"Backup Management", "Datensicherungsmanagement"}.
{"Import users from jabberd1.4 spool files", "Benutzer von jabberd1.4 spool Dateien importieren"}.
{"Backup", "Sicherung"}.
{"Restore", "Wiederherstellung"}.
{"Dump to Text File", "Ausgabe in Textdatei"}.
{"Import File", "Datei importieren"}.
{"Import Directory", "Verzeichnis importieren"}.

% mod_register.erl
{"Choose a username and password to register with this server",
 "Wählen Sie zum Registrieren einen Benutzernamen und ein Passwort"}.

% mod_vcard.erl
{"ejabberd vCard module\nCopyright (c) 2003-2005 Alexey Shchepin", "ejabberd vCard module\nCopyright (c) 2003-2005 Alexey Shchepin"}.
{"You need an x:data capable client to search",
 "Sie brauchen einen x:data kompatiblen Client um zu suchen"}.
{"Search users in ", "Benutzer suchen in "}.
{"Fill in fields to search for any matching Jabber User",
 "Felder ausfüllen, um nach passenden Jabber Benutzern zu suchen"}.
{"Results of search in ", "Ergebnisse der Suche in "}.

{"User",              "User"}.
{"Full Name", 	      "Ganzer Name"}.
{"Name", 	      "Vorname"}.
{"Middle Name",       "Mittelname"}.
{"Family Name",       "Nachname"}.
{"Nickname", 	      "Spitzname"}.
{"Birthday", 	      "Geburtsdatum"}.
{"Country", 	      "Land"}.
{"City", 	      "Stadt"}.
{"email", 	      "E-Mail"}.
{"Organization Name", "Firmenname"}.
{"Organization Unit", "Organisationseinheit"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module\nCopyright (c) 2003-2005 Alexey Shchepin", "ejabberd pub/sub module\nCopyright (c) 2003-2005 Alexey Shchepin"}.
{[], " "}.
{"Node Creator", "Knoten Erschaffer"}.
{"Deliver payloads with event notifications", "Nutzlast mit Benachrichtigungen versenden"}.
{"Notify subscribers when the node configuration changes", "Benutzer benachrichtigen, wenn die Knotenkonfiguration sich ändert"}.
{"Notify subscribers when the node is deleted", "Benutzer benachrichtigen, wenn der Knoten gelöscht wird"}.
{"Notify subscribers when items are removed from the node", "Benutzer benachrichtigen, wenn Einträge vom Knoten entfernt werden"}.
{"Persist items to storage", "Einträge dauerhaft speichern"}.
{"Max # of items to persist", "Maximale Anzahl dauerhaft zu speichernder Einträge"}.
{"Whether to allow subscriptions", "Ob Abonnements erlaubt sind"}.
{"Specify the subscriber model", "Geben Sie das Abonnementsmodell an"}.
{"Specify the publisher model", "Geben Sie das Publikationsmodell an"}.
{"Max payload size in bytes", "Maximale Nutzlastgröße in Bytes"}.
{"Send items to new subscribers", "Einträge an neue Abonnenten schicken"}.
{"Only deliver notifications to available users", "Benachrichtigungen nur an User schicken, die verfügbar sind"}.
{"Specify the current subscription approver", "Geben Sie an, wer die Abonnements bestätigt"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname",
 "Sie brauchen einen für x:data geeigneten Client, um sich mit dem Spitznamen zu registrieren"}.
{"Nickname Registration at ", "Registrieren des Spitznamens "}.
{"Enter nickname you want to register", "Geben Sie den zu registrierenden Spitznamen ein"}.
{"ejabberd MUC module\nCopyright (c) 2003-2005 Alexey Shchepin", "ejabberd MUC module\nCopyright (c) 2003-2005 Alexey Shchepin"}.
{"Only service administrators are allowed to send service messages",
 "Nur Service Administratoren sind berechtigt, Servicenachrichten zu lesen"}.
{"Conference room does not exist", "Konferenzraum existiert nicht"}.
{"Access denied by service policy", "Zutritt verweigert von der Service Policy"}.
{"You must fill in field \"nick\" in the form", "Sie müssen etwas ins Feld \"nick\" eintragen"}.
{"Specified nickname is already registered", "Der angegebene Name ist bereits vergeben"}.
{"Room creation is denied by service policy", "Anlegen des Raumes aufgrund von Servereinstellungen verweigert"}.

% mod_muc/mod_muc_room.erl
{" has set the subject to: ", " hat das Thema geändert zu "}.
{"You need an x:data capable client to configure room",
 "Sie brauchen einen für x:data geeigneten Client um den Raum zu konfigurieren"}.
{"Configuration for ", "Konfiguration für "}.
{"Room title", "Raumname"}.
{"Allow users to change subject?", "Benutzer dürfen das Thema ändern?"}.
{"Allow users to query other users?",
 "Benutzer dürfen andere Benutzer anfragen(query)?"}.
{"Allow users to send private messages?",
 "Benutzer dürfen private Nachrichten verschicken?"}.
{"Make room public searchable?", "Den Raum öffentlich dursuchbar machen?"}.
{"Make participants list public?", "Die Teilnehmerliste öffentlich machen?"}.
{"Make room persistent?", "Den Raum persistent machen?"}.
{"Make room moderated?", "Den Raum moderiert machen?"}.
{"Default users as members?",
 "Standardbenutzer als Mitglieder ansehen?"}.
{"Make room members only?",
 "Den Raum nur für Mitglieder zugänglich machen?"}.
{"Allow users to send invites?",
 "Benutzer dürfen Einladungen senden?"}.
{"Make room password protected?", "Den Raum passwort geschützt machen?"}.
{"Password", "Passwort"}.
{"Make room anonymous?", "Den Raum anonym machen?"}.
{"Enable logging?", "Nachrichten loggen?"}.
{"Only moderators and participants are allowed to change subject in this room",
 "Nur Moderatoren und Teilnehmer dürfen das Thema in diesem Raum ändern"}.
{"Only moderators are allowed to change subject in this room",
 "Nur Moderatoren dürfen das Thema in diesem Raum ändern"}.
{"Visitors are not allowed to send messages to all occupants",
 "Besucher dürfen nicht an alle im Raum Nachrichten verschicken"}.
{"Only occupants are allowed to send messages to the conference",
 "Nur Leute im Raum dürfen Nachrichten an die Konferenz schicken"}.
{"It is not allowed to send normal messages to the conference",
 "Es ist nicht erlaubt normale Nachrichten an die Konferenz zu schicken"}.
{"It is not allowed to send private messages to the conference",
 "Es ist nicht erlaubt private Nachrichten an die Konferenz zu schicken"}.
{"Improper message type", "Unzulässiger Nachrichtentyp"}.
{"Nickname is already in use by another occupant", "Spitzname wird schon von jemand anderem genutzt"}.
{"Nickname is registered by another person", "Spitzname wurde schon von jemand anderem registriert"}.
{"It is not allowed to send private messages of type \"groupchat\"",
 "Es ist nicht erlaubt private Nachrichten des Typs \"Gruppenchat\" zu senden"}.
{"Recipient is not in the conference room", "Der Empfänger ist nicht im Konferenzraum"}.
{"Only occupants are allowed to send queries to the conference",
 "Nur Teilnehmer sind berechtig Anfragen an die Konferenz zu senden"}.
{"Queries to the conference members are not allowed in this room",
 "Anfragen an die Konferenzmitglieder sind in diesem Raum nicht erlaubt"}.
{"You have been banned from this room", "Sie wurden aus diesem Raum verbannt"}.
{"Membership required to enter this room", "Um diesen Raum zu betreten müssen sie ein Mitglied sein"}.
{"Password required to enter this room", "Sie brauchen ein Passwort um diesen Raum zu betreten"}.
{"Incorrect password", "Falsches Passwort"}.
{"Administrator privileges required", "Administratorenrechte benötigt"}.
{"Moderator privileges required", "Moderatorrechte benötigt"}.
{"JID ~s is invalid", "JID ~s ist ungültig"}.
{"Nickname ~s does not exist in the room", "Spitzname ~s funktioniert im Raum nicht"}.
{"Invalid affiliation: ~s", "Ungültige Option: ~s"}.
{"Invalid role: ~s", "Ungültige Funktion: ~s"}.
{"Owner privileges required", "Besitzerrechte benötigt"}.
{"private, ", "privat"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module\nCopyright (c) 2003-2005 Alexey Shchepin", "ejabberd IRC module\nCopyright (c) 2003-2005 Alexey Shchepin"}.
{"You need an x:data capable client to configure mod_irc settings",
 "Sie brauchen einen x:data kompatiblen Client um die mod_irc Einstellungen zu konfigurieren"}.
{"Registration in mod_irc for ", "Registrierung in mod_irc für "}.
{"Enter username and encodings you wish to use for connecting to IRC servers",
 "Geben Sie Benutzernamen und Verschlüsselung für die Verbindung zum IRC Server an"}.
{"IRC Username", "IRC Benutzername"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].",
 "Beispiel: [{\"irc.lucky.net\",\"koi8-r\"}, {\vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Verschlüsselungen"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Wenn Sie verschiedene Verschlüsselungen für IRC Server angeben, schreiben Sie diese im Format '{\"irc server\", \"encoding\"}'. Standardmäßig benutzt der Dienst die  \"~s\" Verschlüsselung"}.

% web/ejabberd_web_admin.erl
{"ejabberd administration", "Ejabberd Administration"}.
{"Users", "Benutzer"}.
{"Nodes", "Knoten(nodes)"}.
{"Statistics", "Statistik"}.
{"submitted", "bestätigt"}.
{"bad format", "ungültiges Format"}.
{"ejabberd access control lists configuration", "Ejabberd access control lists Konfiguration"}.
{"Delete Selected", "Lösche Markiertes"}.
{"Submit", "Bestätigen"}.
{"ejabberd access rules configuration", "Ejabberd Zutrittsregeln Konfiguration"}.
{"~s access rule configuration", "~s Zurtrittsregel Konfiguration"}.
{"ejabberd users", "Ejabberd Benutzer"}.
{"ejabberd stats", "Ejabberd Statistik"}.
{"Node not found", "Knoten nicht gefunden"}.
{"Add New", "Neuen hinzufügen"}.
{"Registered users", "Registrierte Benutzer"}.
{"Online users", "Online Benutzer"}.
{"Outgoing S2S servers", "Rausgehende S2S Server"}.
{"Change Password", "Passwort ändern"}.
{"Connected Resources:", "Verbundene Resourcen"}.
{"Password:", "Passwort:"}.
{"None", "Keine"}.
{"Node ", "Knoten "}.
{"DB Management", "DB Management"}.
{"Listened Ports Management", "Ports Management"}.
{"Restart", "Neustart"}.
{"Stop", "Stop"}.
{"RPC call error", "RPC-Aufruf Fehler"}.
{"DB Tables at ", "DB Tabellen bei "}.
{"Name", "Name"}.
{"Storage Type", "Speichertyp"}.
{"Size", "Größe"}.
{"Memory", "Speicher"}.
{"Backup Management at ", "Backup Management bei "}.
{"Store a backup in a file", "Die Sicherung in eine Datei legen "}.
{"OK", "OK"}.
{"Restore a backup from a file", "Die Sicherung aus einer Datei wiederherstellen"}.
{"Install a database fallback from a file", "Eine Sicherungsdatenbank aus einer Datei installieren"}.
{"Dump a database in a text file", "Ausgabe der Datenbank in eine Textdatei"}.
{"Restore a database from a text file", "Datenbank aus einer Textdatei wiederherstellen"}.
{"Listened Ports at ", "Listened Ports at "}.
{"~p statistics", "~p Statistiken"}.
{"Uptime", "Betriebszeit"}.
{"CPU Time", "CPU Zeit"}.
{"Transactions commited", "abgeschlossene Vorgänge"}.
{"Transactions aborted", "abgebrochene Vorgänge"}.
{"Transactions restarted", "neugestartete Vorgänge"}.
{"Transactions logged", "geloggte Vorgänge"}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Optionen"}.
{"Update", "Aktualisieren"}.
{"Delete", "Löschen"}.
{"Add User", "Benutzer hinzufügen"}.
{"Offline messages", "Offline Nachrichten"}.
{"Last Activity", "Letzte Aktion"}.
{"Never", "Nie"}.
{"~s offline messages queue", "~s offline Nachrichtenschlange"}.
{"Time", "Uhrzeit"}.
{"From", "Von"}.
{"To", "Zu"}.
{"Packet", "Paket"}.
{"Offline messages:", "Offline Nachrichten"}.
{"Roster", "Liste"}.
{"Nickname", "Spitzname"}.
{"Subscription", "Subskription"}.
{"Pending", "schwebend"}.
{"Groups", "Gruppe"}.
{"Remove", "Entfernen"}.
{"Add JID", "JID hinzufügen"}.
{"User ", "Benutzer "}.
{"Roster of ", "Liste von "}.
{"Virtual Hosts", "Virtuelle Hosts"}.
{"ejabberd (c) 2002-2005 Alexey Shchepin, 2004-2005 Process One", "ejabberd (c) 2002-2005 Alexey Shchepin, 2004-2005 Process One"}.
{"Shared Roster", "Gemeinsame Kontaktliste"}.
{"(raw)", "(roh)"}.
{"raw", "roh"}.
{"ejabberd virtual hosts", "ejabberd virtuelle Hosts"}.
{"Users last activity", "Letzte Aktivität des Benutzers"}.
{"Period: ", "Zeitraum"}.
{"Last month", "Letzter Monat"}.
{"Last year", "Letztes Jahr"}.
{"All activity", "Alle Aktivitäten"}.
{"Show Ordinary Table", "Normale Tabelle anzeigen"}.
{"Show Integral Table", "Vollständige Tabelle anzeigen"}.
{"Host", "Host"}.
{"Online", "Online"}.
{"Authenticated users", "Angemeldete Benutzer"}.
{"Validate", "Validieren"}.
{"No data", "Keine Daten"}.
{"Modules Management", "Modulverwaltung"}.
{"Modules at ", "Module auf "}.
{"Not found", "Nicht gefunden"}.
{"Start", "Anfang"}.
{"Shared roster groups", "Gruppen der gemeinsamen Kontaktliste"}.
{"Name:", "Name"}.
{"Description:", "Beschreibung:"}.
{"Members:", "Mitglieder:"}.
{"Displayed Groups:", "Angezeigte Gruppen:"}.
{"Group ", "Gruppe "}.
{"ejabberd Web Interface", "ejabberd Web Interface"}.

% mod_vcard_ldap.erl
{"Given Name", "Vorname"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Verwendung von STARTTLS erforderlich"}.
{"Replaced by new connection", "Durch neue Verbindung ersetzt"}.

% mod_vcard_odbc.erl
{"Erlang Jabber Server\nCopyright (c) 2002-2005 Alexey Shchepin", "Erlang Jabber Server\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Füllen Sie die Felder aus, um nach passenden Jabber benutzern zu suchen (beenden Sie ein Feld mit *, um auch nach Teilzeichenketten zu suchen)"}.
{"JID", "JID"}.

% Local Variables:
% mode: erlang
% End:
