% $Id$
% Language: Esperanto
% Author: Andreas van Cranenburgh

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Uzo de STARTTLS bezonata"}.
{"Replaced by new connection", "Anstataŭigita je nova konekto"}.

% jlib.hrl
{"No resource provided", "Neniu risurco donita"}.

% mod_configure.erl
{"Database", "Datumbazo"}.
{"Restart Service", "Restartu Servon"}.
{"Shut Down Service", "Haltigu Servon"}.
{"Delete User", "Forigu Uzanton"}.
{"End User Session", "Haltigu Uzant-seancon"}.
{"Get User Password", "Montru pasvorton de uzanto"}.
{"Change User Password", "Ŝanĝu pasvorton de uzanto"}.
{"Get User Last Login Time", "Montru tempon de lasta ensaluto"}.
{"Get User Statistics", "Montru statistikojn de uzanto"}.
{"Get Number of Registered Users", "Montru nombron de registritaj uzantoj"}.
{"Get Number of Online Users", "Montru nombron de konektataj uzantoj"}.
{"User Management", "Uzanto-administrado"}.
{"Outgoing s2s Connections", "Elirantaj s-al-s-konektoj"}.
{"Import Users From jabberd 1.4 Spool Files", "Importu uzantojn de jabberd1.4-uzantdosieroj"}.
{"Database Tables Configuration at ", "Agordo de datumbaz-tabeloj je "}.
{"Time delay", "Prokrasto"}.
{"Password Verification", "Pasvortkontrolo"}.
{"Number of registered users", "Nombro de registritaj uzantoj"}.
{"Number of online users", "Nombro de konektataj uzantoj"}.
{"Last login", "Lasta ensaluto"}.
{"Roster size", "Kontaktlist-grando"}.
{"IP addresses", "IP-adresoj"}.
{"Resources", "Risurcoj"}.
{"Choose storage type of tables", "Elektu konserv-tipon de tabeloj"}.
{"RAM copy", "RAM-kopio"}.
{"RAM and disc copy", "RAM- kaj disk-kopio"}.
{"Disc only copy", "Nur disk-kopio"}.
{"Remote copy", "Fora kopio"}.
{"Stop Modules at ", "Haltigu modulojn je "}.
{"Choose modules to stop", "Elektu modulojn por fini"}.
{"Start Modules at ", "Startu modulojn je "}.
{"Enter list of {Module, [Options]}", "Enmetu liston de {Modulo, [Elektebloj]}"}.
{"List of modules to start", "Listo de moduloj por starti"}.
{"Backup to File at ", "Faru sekurkopion je "}.
{"Enter path to backup file", "Enmetu vojon por sekurkopio"}.
{"Path to File", "Voje de dosiero"}.
{"Restore Backup from File at ", "Restaŭrigu de dosiero el "}.
{"Dump Backup to Text File at ", "Skribu sekurkopion en plata teksto al "}.
{"Enter path to text file", "Enmetu vojon al plata teksto"}.
{"Import User from File at ", "Importu uzanton de dosiero el "}.
{"Enter path to jabberd1.4 spool file", "Enmetu vojon al jabberd1.4-uzantdosiero"}.
{"Import Users from Dir at ", "Importu uzantojn de dosierujo ĉe "}.
{"Enter path to jabberd1.4 spool dir", "Enmetu vojon al jabberd1.4-uzantdosierujo"}.
{"Path to Dir", "Vojo al dosierujo"}.
{"Access Control List Configuration", "Agordo de atingokontrolo"}.
{"Access control lists", "Atingokontrol-listoj"}.
{"Access Configuration", "Agordo de atingo"}.
{"Access rules", "Atingo-reguloj"}.
{"Administration of ", "Mastrumado de "}.
{"Action on user", "Ago je uzanto"}.
{"Edit Properties", "Redaktu atributojn"}.
{"Remove User", "Forigu uzanton"}.

% mod_disco.erl
{"Configuration", "Agordo"}.
{"Online Users", "Konektataj Uzantoj"}.
{"All Users", "Ĉiuj Uzantoj"}.
{"To ~s", "Al ~s"}.
{"From ~s", "De ~s"}.
{"Running Nodes", "Funkciantaj Nodoj"}.
{"Stopped Nodes", "Neaktivaj Nodoj"}.
{"Access Control Lists", "Atingokontrol-listoj"}.
{"Access Rules", "Atingo-reguloj"}.
{"Modules", "Moduloj"}.
{"Start Modules", "Startu Modulojn"}.
{"Stop Modules", "Haltigu Modulojn"}.
{"Backup Management", "Mastrumado de sekurkopioj"}.
{"Backup", "Faru Sekurkopion"}.
{"Restore", "Restaŭru"}.
{"Dump to Text File", "Skribu en plata tekst-dosiero"}.
{"Import File", "Importu dosieron"}.
{"Import Directory", "Importu dosierujo"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Elektu uzantnomon kaj pasvorton por registri je ĉi tiu servilo"}.

% mod_vcard.erl
{"Erlang Jabber Server", "Erlang-a Jabber-Servilo"}.
{"ejabberd vCard module", "ejabberd vCard-modulo"}.
{"You need an x:data capable client to search", "Vi bezonas klienton kun x:data-funkcio por serĉado"}.
{"Search users in ", "Serĉu uzantojn en "}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Kompletigu la formon por serĉi rekonata Jabber-uzanto (Aldonu * je la fino de la kampo por rekoni subĉenon"}.
{"User",              "Uzanto"}.
{"Full Name", 	      "Plena Nomo"}.
{"Name", 	            "Nomo"}.
{"Middle Name",       "Meza Nomo"}.
{"Family Name",       "Lasta Nomo"}.
{"Nickname", 	      "Kaŝnomo"}.
{"Birthday", 	      "Naskiĝtago"}.
{"Country", 	      "Lando"}.
{"City", 	      "Urbo"}.
{"Organization Name", "Organiz-nomo"}.
{"Organization Unit", "Organiz-parto"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Kompletigu la formon por serĉi rekonata Jabber-uzanto"}.

% mod_vcard_odbc.erl
{"Email", "Retpoŝto"}.
{"vCard User Search", "Serĉado de vizitkartoj"}.
{"Search Results for ", "Serĉ-rezultoj de "}.
{"Jabber ID", "Jabber ID"}.

% mod_pubsub/mod_pubsub.erl
{"Publish-Subscribe", "Public-Abonado"}.
{"ejabberd Publish-Subscribe module", "ejabberd Public-Abonada modulo"}.
{"PubSub subscriber request", "PubAbo abonpeto"}.
{"Choose whether to approve this entity's subscription.", "Elektu ĉu permesi la abonon de ĉi tiu ento"}.
{"Node ID", "Nodo ID"}.
{"Subscriber Address", "Abonanta adreso"}.
{"Allow this JID to subscribe to this pubsub node?", "Ĉu permesi ĉi tiun JID aboni al la jena PubAbo-nodo"}.
{"Deliver event notifications", "Liveru event-sciigojn"}.
{"Specify the access model", "Specifu atingo-modelon"}.
{"Roster groups that may subscribe (if access model is roster)", "Kontaktlist-grupoj kiu rajtas aboni (se atingo-modelo estas kontaktlista)"}.
{"When to send the last published item", "Kiam sendi la laste publicitan eron"}.
{"Deliver payloads with event notifications", "Liveru aĵojn de event-sciigoj"}.
{"Notify subscribers when the node configuration changes", "Sciigu abonantoj kiam la agordo de la nodo ŝanĝas"}.
{"Notify subscribers when the node is deleted", "Sciigu abonantoj kiam la nodo estas forigita"}.
{"Notify subscribers when items are removed from the node", "Sciigu abonantoj kiam eroj estas forigita de la nodo"}.
{"Persist items to storage", "Savu erojn en konservado"}.
{"Max # of items to persist", "Maksimuma kiomo de eroj en konservado"}.
{"Whether to allow subscriptions", "Ĉu permesi aboni"}.
{"Specify the publisher model", "Enmetu publikadan modelon"}.
{"Max payload size in bytes", "Maksimuma aĵo-grando je bajtoj"}.
{"Only deliver notifications to available users", "Nur liveru sciigojn al konektataj uzantoj"}.

% mod_muc/mod_muc.erl
{"Chatrooms", "Babilejoj"}.
{"You must fill in field \"Nickname\" in the form", "Vi devas kompletigi la \"Kaŝnomo\" kampon"}.
{"You need an x:data capable client to register nickname", "Vi bezonas klienton kun x:data-funkcio por registri kaŝnomon"}.
{"Nickname Registration at ", "Kaŝnomo-registrado je "}.
{"Enter nickname you want to register", "Enmetu kaŝnomon kiun vi volas registri"}.
{"ejabberd MUC module", "ejabberd MUC-modulo"}.
{"Only service administrators are allowed to send service messages", "Nur servo-administrantoj rajtas sendi serv-mesaĝojn"}.
{"Room creation is denied by service policy", "Ĉi tiu serv-politiko ne permesas babilejo-kreadon"}.
{"Conference room does not exist", "Babilejo ne ekzistas"}.
{"Access denied by service policy", "Atingo rifuzita de serv-politiko"}.
{"You must fill in field \"nick\" in the form", "Vi devas enmeti kampon \"kaŝnomo\""}.
{"Specified nickname is already registered", "Donita kaŝnomo jam estas registrita"}.

% mod_muc/mod_muc_room.erl
{"Traffic rate limit is exceeded", "Trafikrapida limigo superita"}.
{"This room is not anonymous", "Ĉi tiu babilejo ne estas anonima"}.
{"Make room persistent", "Farigu babilejon daŭra"}.
{"Make room public searchable", "Farigu babilejon publike trovebla"}.
{"Make participants list public", "Farigu partoprento-liston publika"}.
{"Make room password protected", "Farigu babilejon protektata per pasvorto"}.
{"Maximum Number of Occupants", "Limigo de nombro de partoprenantoj"}.
{"No limit", "Neniu limigo"}.
{"Present real JIDs to", "Montru verajn JID-ojn al"}. % "jo-idojn" ..
{"moderators only", "moderantoj sole"}.
{"anyone", "iu ajn"}.
{"Make room members-only", "Farigu babilejon sole por membroj"}.
{"Default users as participants", "Kutime farigu uzantojn kiel partpoprenantoj"}.
{"Allow users to change subject", "Permesu uzantojn ŝanĝi la temon"}.
{"Allow users to send private messages", "Permesu uzantojn sendi privatajn mesaĝojn"}.
{"Allow users to query other users", "Permesu uzantojn informpeti aliajn uzantojn"}. %FIXME: two objects in one sentence?
{"Allow users to send invites", "Permesu uzantojn sendi invitojn"}.
{"Enable logging", "Ŝaltu protokoladon"}.
{"Number of occupants", "Nombro de ĉeestantoj"}.
{"~s invites you to the room ~s", "~s invitas vin al la babilejo ~s"}.
{"the password is", "la pasvorto estas"}.
{" has set the subject to: ", " ŝanĝis la temon al: "}.
{"You need an x:data capable client to configure room", "Vi bezonas klienton kun x:data-funkcio por agordi la babilejon"}.
{"Configuration for ", "Agordo de "}.
{"Room title", "Babilejo-nomo"}.
{"Password", "Pasvorto"}.
{"Only moderators and participants are allowed to change subject in this room", "Nur moderigantoj kaj partoprenantoj rajtas ŝanĝi la temon en ĉi tiu babilejo"}.
{"Only moderators are allowed to change subject in this room", "Nur moderigantoj rajtas ŝanĝi la temon en ĉi tiu babilejo"}.
{"Visitors are not allowed to send messages to all occupants", "Vizitantoj ne rajtas sendi mesaĝojn al ĉiuj partoprenantoj"}.
{"Only occupants are allowed to send messages to the conference", "Nur partoprenantoj rajtas sendi mesaĝojn al la babilejo"}.
{"It is not allowed to send private messages to the conference", "Nur partoprenantoj rajtas sendi privatajn mesaĝojn al la babilejo"}.
{"Improper message type", "Malĝusta mesaĝo-tipo"}.
{"Nickname is already in use by another occupant", "Kaŝnomo estas jam uzata de alia partoprenanto"}.
{"Nickname is registered by another person", "Kaŝnomo estas registrita de alia persono"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Malpermesas sendi mesaĝojn de tipo \"groupchat\""}.
{"Recipient is not in the conference room", "Ricevanto ne ĉeestas en la babilejo "}.
{"Only occupants are allowed to send queries to the conference", "Nur partoprenantoj rajtas sendi informmendojn al la babilejoj"}.
{"Queries to the conference members are not allowed in this room", "Malpermesas informmendoj al partoprenantoj en ĉi tiu babilejo"}.
{"You have been banned from this room", "Vi estas malpermesata en ĉi tiu babilejo"}.
{"Membership required to enter this room", "Membreco estas bezonata por eniri ĉi tiun babilejon"}.
{"Password required to enter this room", "Pasvorto estas bezonata por eniri ĉi tiun babilejon"}.
{"Incorrect password", "Nekorekta pasvorto"}.
{"Administrator privileges required", "Administrantaj rajtoj bezonata"}.
{"Moderator privileges required", "Moderantaj rajtoj bezonata"}.
{"JID ~s is invalid", "JID ~s estas nevalida"}.
{"Nickname ~s does not exist in the room", "Kaŝnomo ~s ne ekzistas en la babilejo"}.
{"Invalid affiliation: ~s", "Nevalida aparteneco: ~s"}.
{"Invalid role: ~s", "Nevalida rolo: ~s"}.
{"Owner privileges required", "Mastraj rajtoj bezonata"}.
{"private, ", "privata, "}.

% mod_irc/mod_irc.erl
{"IRC Transport", "IRC-transportilo"}.
{"ejabberd IRC module", "ejabberd IRC-modulo"}.
{"You need an x:data capable client to configure mod_irc settings", "Vi bezonas klienton kun x:data-funkcio por agordi mod_irc"}.
{"Registration in mod_irc for ", "Registraĵo en mod_irc de "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Enmetu uzantnomon kaj enkodigoj kiujn vi volas uzi por konektoj al IRC-serviloj"}.
{"IRC Username", "IRC-kaŝnomo"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Se vi volas specifi diversajn enkodigojn por IRC-serviloj, kompletigu la jenan liston kun la formo '{\"irc-servilo\", \"enkodigo\"}'. Se ne specifita, ĉi tiu servilo uzas la enkodigo \"~s\""}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Ekzemplo: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Enkodigoj"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "ejabberd Teksaĵa Administro"}.
{"Administration", "Administro"}.
{"(Raw)", "(Kruda)"}.
{"Raw", "Kruda"}.
{"Users Last Activity", "Lasta aktiveco de uzanto"}.
{"Registered Users", "Registritaj uzantoj"}.
{"Offline Messages", "Liverontaj mesaĝoj"}.
{"Registered Users:", "Registritaj uzantoj:"}.
{"Online Users:", "Konektataj uzantoj:"}.
{"Outgoing s2s Connections:", "Elirantaj s-al-s-konektoj:"}.
{"Outgoing s2s Servers:", "Elirantaj s-al-s-serviloj"}.
{"No Data", "Neniu datumo"}.
{"Listened Ports", "Atentataj pordoj"}.
{"RPC Call Error", "Eraro de RPC-alvoko"}.
{"Database Tables at ", "Datumbaz-tabeloj je "}.
{"Backup of ", "Sekurkopio de "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Rimarku ke ĉi tiuj elektebloj nur sekurkopias la propran Mnesia-datumbazon. Se vi uzas la ODBC-modulon, vi ankaŭ devas sekurkopii tiujn SQL-datumbazoj aparte."}.
{"Store binary backup:", "Konservu duuman sekurkopion:"}.
{"Restore binary backup immediately:", "Restaŭrigu duuman sekurkopion tuj:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Restaŭrigu duuman sekurkopion post sekvonta ejabberd-restarto"}.
{"Store plain text backup:", "Skribu sekurkopion en plata tekstdosiero"}.
{"Restore plain text backup immediately:", "Restaŭrigu sekurkopion el plata tekstdosiero tuj"}.
{"Statistics of ~p", "Statistikoj de ~p"}.
{"Uptime:", "Daŭro de funkciado"}.
{"CPU Time:", "CPU-tempo"}.
{"Transactions Commited:", "Transakcioj enmetitaj"}.
{"Transactions Aborted:", "Transakcioj nuligitaj"}.
{"Transactions Restarted:", "Transakcioj restartitaj"}.
{"Transactions Logged:", "Transakcioj protokolitaj"}.
{"Update ", "Ĝisdatigu "}.
{"Update plan", "Ĝisdatigo-plano"}.
{"Updated modules", "Ĝisdatigitaj moduloj"}.
{"Update script", "Ĝisdatigo-skripto"}.
{"Low level update script", "Bazanivela ĝisdatigo-skripto"}.
{"Script check", "Skript-kontrolo"}.
{"Users", "Uzantoj"}.
{"Nodes", "Nodoj"}.
{"Statistics", "Statistikoj"}.
{"Delete Selected", "Forigu elektata(j)n"}.
{"Submit", "Sendu"}.
{"~s access rule configuration", "Agordo de atingo-reguloj de ~s"}.
{"Node not found", "Nodo ne trovita"}.
{"Add New", "Aldonu novan"}.
{"Change Password", "Ŝanĝu pasvorton"}.
{"Connected Resources:", "Konektataj risurcoj:"}.
{"Password:", "Pasvorto:"}.
{"None", "Nenio"}.
{"Node ", "Nodo "}.
{"Restart", "Restartu"}.
{"Stop", "Haltigu"}.
{"Name", "Nomo"}.
{"Storage Type", "Konserv-tipo"}.
{"Size", "Grando"}.
{"Memory", "Memoro"}.
{"OK", "Bone"}.
{"Listened Ports at ", "Atentataj pordoj je "}.
{"Port", "Pordo"}.
{"Module", "Modulo"}.
{"Options", "Elektebloj"}.
{"Update", "Ĝisdatigu"}.
{"Delete", "Forigu"}.
{"Add User", "Aldonu Uzanton"}.
{"Last Activity", "Lasta aktiveco"}.
{"Never", "Neniam"}.
{"Time", "Tempo"}.
{"From", "De"}.
{"To", "Ĝis"}.
{"Packet", "Pakaĵo"}.
{"Roster", "Kontaktlisto"}.
{"Nickname", "Kaŝnomo"}.
{"Subscription", "Abono"}.
{"Pending", "Atendanta"}.
{"Groups", "Grupoj"}.
{"Remove", "Forigu"}.
{"User ", "Uzanto "}.
{"Roster of ", "Kontaktlisto de "}.
{"Online", "Konektata"}.
{"Validate", "Validigu"}.
{"Name:", "Nomo:"}.
{"Description:", "Priskribo:"}.
{"Members:", "Membroj:"}.
{"Displayed Groups:", "Montrataj grupoj:"}.
{"Group ", "Grupo "}.
{"Virtual Hosts", "Virtual-gastigoj"}.  %ĉu eble pli bone "ŝajn-gastigoj"?
{"ejabberd virtual hosts", "ejabberd virtual-gastigoj"}.
{"Period: ", "Periodo: "}.
{"Last month", "Lasta monato"}.
{"Last year", "Lasta jaro"}.
{"All activity", "Ĉiu aktiveco"}.
{"Show Ordinary Table", "Montru ordinaran tabelon"}.
{"Show Integral Table", "Montru integran tabelon"}.
{"Host", "Gastigo"}.
{"Modules at ", "Moduloj je "}.
{"Start", "Startu"}.

% mod_roster.erl
{"Submitted", "Sendita"}.
{"Bad format", "Malĝusta formo"}.
{"Add Jabber ID", "Aldonu Jabber ID"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Mesaĝo-atendovico de la senkonekta kontakto estas plena. La mesaĝo estas forĵetita"}.
{"~s's Offline Messages Queue", "Mesaĝo-atendovico de ~s"}. %FIXME: "message queue" is not really offline, neither are the messages..
{"Offline Messages:", "Liverontaj mesaĝoj"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bajtfluo modulo"}.

% mod_shared_roster.erl
{"Shared Roster Groups", "Komuna Kontaktlist-grupo"}.

% mod_announce.erl
{"Really delete message of the day?", "Ĉu vere forigi mesaĝon de la tago?"}.
{"Subject", "Temo"}.
{"Message body", "Teksto de mesaĝo"}.
{"No body provided for announce message", "Neniu teksto donita por anonc-mesaĝo"}.
{"Announcements", "Anoncoj"}.
{"Send announcement to all users", "Sendu anoncon al ĉiu uzanto"}.
{"Send announcement to all users on all hosts", "Sendu anoncon al ĉiu uzanto de ĉiu gastigo"}.
{"Send announcement to all online users", "Sendu anoncon al ĉiu konektata uzanto"}.
{"Send announcement to all online users on all hosts", "Sendu anoncon al ĉiu konektata uzanto de ĉiu gastigo"}.
{"Set message of the day and send to online users", "Enmetu mesaĝon de la tago kaj sendu al konektataj uzantoj"}.
{"Set message of the day on all hosts and send to online users", "Enmetu mesaĝon de la tago je ĉiu gastigo kaj sendu al konektataj uzantoj"}.
{"Update message of the day (don't send)", "Ŝanĝu mesaĝon de la tago (ne sendu)"}.
{"Update message of the day on all hosts (don't send)", "Ŝanĝu mesaĝon de la tago je ĉiu gastigo (ne sendu)"}.
{"Delete message of the day", "Forigu mesaĝo de la tago"}.
{"Delete message of the day on all hosts", "Forigu mesaĝo de la tago je ĉiu gastigo"}.

% mod_adhoc.erl
{"Commands", "Ordonoj"}.
{"Ping", "Sondaĵo"}. %FIXME: perhaps there's a corresponding sound in Esperanto?
{"Pong", "Resondaĵo"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Agordo de babilejo ŝanĝita"}.
{"joins the room", "eniras la babilejo"}.
{"leaves the room", "eliras la babilejo"}.
{"has been banned", "estas forbarita"}.
{"has been kicked", "estas forpelita"}.
{"has been kicked because of an affiliation change", "estas forpelita pro aparteneca ŝanĝo"}.
{"has been kicked because the room has been changed to members-only", "estas forpelita ĉar la babilejo fariĝis sole por membroj"}.
{"has been kicked because of a system shutdown", "estas forpelita pro sistem-haltigo"}.
{"is now known as", "nun nomiĝas"}.
{"Monday", "Lundo"}.
{"Tuesday", "Mardo"}.
{"Wednesday", "Merkredo"}.
{"Thursday", "Ĵaŭdo"}.
{"Friday", "Vendredo"}.
{"Saturday", "Sabato"}.
{"Sunday", "Dimanĉo"}.
{"January", "Januaro"}.
{"February", "Februaro"}.
{"March", "Marĉo"}.
{"April", "Aprilo"}.
{"May", "Majo"}.
{"June", "Junio"}.
{"July", "Julio"}.
{"August", "Aŭgusto"}.
{"September", "Septembro"}.
{"October", "Oktobro"}.
{"November", "Novembro"}.
{"December", "Decembro"}.
{"Room Configuration", "Babilejo-agordo"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
