% $Id$

% Ejabberd - Spanish - badlop AT jabberes.org

% jlib.hrl
{"No resource provided", "No se ha proporcionado recurso"}.

% mod_configure.erl
{"DB Tables Configuration at ", "Configuración de tablas de la BD en "}.
{"Choose storage type of tables", "Selecciona tipo de almacenamiento de las tablas"}.
{"RAM copy", "Copia en RAM"}.
{"RAM and disc copy", "Copia en RAM y disco"}.
{"Disc only copy", "Copia en disco solamente"}.
{"Remote copy", "Copia remota"}.
{"Stop Modules at ", "Detener módulos en "}.
{"Choose modules to stop", "Selecciona módulos a detener"}.
{"Start Modules at ", "Iniciar módulos en "}.
{"Enter list of {Module, [Options]}", "Introduce lista de {módulo, [opciones]}"}.
{"List of modules to start", "Lista de módulos a iniciar"}.
{"Backup to File at ", "Guardar copia de seguridad en fichero en "}.
{"Enter path to backup file", "Introduce ruta al fichero de copia de seguridad"}.
{"Path to File", "Ruta al fichero"}.
{"Restore Backup from File at ", "Restaura copia de seguridad desde el fichero en "}.
{"Dump Backup to Text File at ", "Exporta copia de seguridad a fichero de texto en "}.
{"Enter path to text file", "Introduce ruta al fichero de texto"}.
{"Import User from File at ", "Importa usuario desde fichero en "}.
{"Enter path to jabberd1.4 spool file", "Introduce ruta al fichero jabberd1.4 spool"}.
{"Import Users from Dir at ", "Importar usuarios desde el directorio en "}.
{"Enter path to jabberd1.4 spool dir", "Introduce la ruta al directorio de jabberd1.4 spools"}.
{"Path to Dir", "Ruta al directorio"}.
{"Hostname Configuration", "Configuración del nombre de máquina"}.
{"Choose host name", "Indica el nombre de la máquina"}.
{"Host name", "Nombre de la máquina"}.
{"Access Control List Configuration", "Configuración de la Lista de Control de Acceso"}.
{"Access control lists", "Listas de Control de Acceso"}.
{"Access Configuration", "Configuración de accesos"}.
{"Access rules", "Reglas de acceso"}.
{"Remove Users", "Eliminar usuarios"}.
{"Choose users to remove", "Selecciona usuarios a eliminar"}.
{"Administration of ", "Administración de "}.
{"Action on user", "Acción en el usuario"}.
{"Edit Properties", "Editar propiedades"}.
{"Remove User", "Eliminar usuario"}.

% mod_disco.erl
{"Configuration", "Configuración"}.
{"Online Users", "Usuarios conectados"}.
{"All Users", "Todos los usuarios"}.
{"Outgoing S2S connections", "Conexiones S2S de salida"}.
{"To ~s", "A ~s"}.
{"From ~s", "De ~s"}.
{"Running Nodes", "Nodos funcionando"}.
{"Stopped Nodes", "Nodos detenidos"}.
{"Host Name", "Nombre de la máquina"}.
{"Access Control Lists", "Listas de Control de Acceso"}.
{"Access Rules", "Reglas de Acceso"}.
{"Remove Users", "Eliminar usuarios"}.
{"DB", "BD"}.
{"Modules", "Módulos"}.
{"Start Modules", "Iniciar módulos"}.
{"Stop Modules", "Detener módulos"}.
{"Backup Management", "Gestión de copia de seguridad"}.
{"Import users from jabberd1.4 spool files", "Importar usuarios desde ficheros jabberd1.4 spool"}.
{"Backup", "Guardar copia de seguridad"}.
{"Restore", "Restaurar"}.
{"Dump to Text File", "Exportar a fichero de texto"}.
{"Import File", "Importar fichero"}.
{"Import Directory", "Importar directorio"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Escoge un nombre de usuario y contraseña para registrarte en este servidor"}.

% mod_vcard.erl
{"Erlang Jabber Server\nCopyright (c) 2002-2005 Alexey Shchepin", "Servidor Jabber en Erlang\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Rellena el formulario para buscar usuarios Jabber. Añade * al final de un campo para buscar subcadenas."}.
{"ejabberd vCard module\nCopyright (c) 2003-2005 Alexey Shchepin", "Módulo vCard para ejabberd\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"You need an x:data capable client to search", "Necesitas un cliente con soporte de x:data para poder buscar"}.
{"Search users in ", "Buscar usuarios en "}.
{"Results of search in ", "Resultados de la búsqueda en "}.

{"User",              "Usuario"}.
{"Full Name", 	      "Nombre completo"}.
{"Name", 	      "Nombre"}.
{"Middle Name",       "Segundo nombre"}.
{"Family Name",       "Apellido"}.
{"Nickname", 	      "Apodo"}.
{"Birthday", 	      "Cumpleaños"}.
{"Country", 	      "País"}.
{"City", 	      "Ciudad"}.
{"email", 	      "correo-e"}.
{"Organization Name", "Nombre de la organización"}.
{"Organization Unit", "Unidad de la organización"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module\nCopyright (c) 2003-2005 Alexey Shchepin", "Módulo Pub/Sub para ejabberd\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"Node Creator", "Creador del nodo"}.
{[], " "}.
{"Deliver payloads with event notifications", "Enviar payloads junto con las notificaciones de eventos"}.
{"Notify subscribers when the node configuration changes", "Notificar subscriptores cuando cambia la configuración del nodo"}.
{"Notify subscribers when the node is deleted", "Notificar subscriptores cuando el nodo se borra"}.
{"Notify subscribers when items are removed from the node", "Notificar subscriptores cuando los elementos se borran del nodo"}.
{"Persist items to storage", "Persistir elementos al almacenar"}.
{"Max # of items to persist", "Máximo # de elementos que persisten"}.
{"Whether to allow subscriptions", "Permitir subscripciones"}.
{"Specify the subscriber model", "Especificar el modelo del subscriptor"}.
{"Specify the publisher model", "Especificar el modelo del publicante"}.
{"Max payload size in bytes", "Máximo tamaño del payload en bytes"}.
{"Send items to new subscribers", "Enviar elementos a los nuevos subscriptores"}.
{"Only deliver notifications to available users", "Solo enviar notificaciones a los usuarios disponibles"}.
{"Specify the current subscription approver", "Especificar el aprobador de subscripción actual"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "Necesitas un cliente con soporte de x:data para poder registrar el apodo"}.
{"Nickname Registration at ", "Registro del apodo en "}.
{"Enter nickname you want to register", "Introduce el apodo que quieras registrar"}.
{"Only service administrators are allowed to send service messages", "Solo los administradores del servicio tienen permiso para enviar mensajes de servicio"}.
{"Conference room does not exist", "La sala de conferencias no existe"}.
{"Access denied by service policy", "Acceso denegado por la política del servicio"}.
{"You must fill in field \"nick\" in the form", "Debes rellenar el campo \"apodo\" en el formulario"}.
{"Specified nickname is already registered", "El apodo especificado ya está registrado, tendrás que buscar otro"}.
{"Room creation is denied by service policy", "Se te ha denegado crear la sala por política del servicio"}.
{"ejabberd MUC module\nCopyright (c) 2003-2005 Alexey Shchepin", "Módulo de MUC para ejabbed\nCopyright (c) 2002-2005 Alexey Shchepin"}.

% mod_muc/mod_muc_room.erl
{" has set the subject to: ", " ha puesto el asunto: "}.
{"You need an x:data capable client to configure room", "Necesitas un cliente con soporte de x:data para configurar la sala"}.
{"Configuration for ", "Configuración para "}.
{"Room title", "Título de la sala"}.
{"Allow users to change subject?", "Permitir a los usuarios cambiar el asunto"}.
{"Allow users to query other users?", "Permitir a los usuarios consultar a otros usuarios"}.
{"Allow users to send private messages?", "Permitir a los usuarios enviar mensajes privados"}.
{"Make room public searchable?", "Hacer la sala públicamente visible"}.
{"Make participants list public?", "Hacer pública la lista de participantes"}.
{"Make room persistent?", "Hacer la sala permanente"}.
{"Make room moderated?", "Hacer la sala moderada"}.
{"Default users as members?", "Los usuarios son miembros por defecto"}.
{"Make room members only?", "Hacer la sala sólo para miembros"}.
{"Allow users to send invites?", "Permitir a los usuarios enviar invitaciones"}.
{"Make room password protected?", "Proteger la sala con contraseña"}.
{"Password", "Contraseña"}.
{"Make room anonymous?", "Hacer anónima la sala"}.
{"Enable logging?", "Guardar históricos"}.
{"Only moderators and participants are allowed to change subject in this room", "Solo los moderadores y participantes pueden cambiar el asunto de esta sala"}.
{"Only moderators are allowed to change subject in this room", "Solo los moderadores pueden cambiar el asunto de esta sala"}.
{"Visitors are not allowed to send messages to all occupants", "Los visitantes no pueden enviar mensajes a todos los ocupantes"}.
{"Only occupants are allowed to send messages to the conference", "Solo los ocupantes pueden enviar mensajes a la sala"}.
{"It is not allowed to send normal messages to the conference", "Impedir el envio de mensajes normales a la sala"}.
{"It is not allowed to send private messages to the conference", "Impedir el envio de mensajes privados a la sala"}.
{"Improper message type", "Tipo de mensaje incorrecto"}.
{"Nickname is already in use by another occupant", "El apodo ya está siendo usado por otro ocupante"}.
{"Nickname is registered by another person", "El apodo ya está registrado por otra persona"}.
{"It is not allowed to send private messages of type \"groupchat\"", "No está permitido enviar mensajes privados del tipo \"groupchat\""}.
{"Recipient is not in the conference room", "El receptor no está en la sala de conferencia"}.
{"Only occupants are allowed to send queries to the conference", "Solo los ocupantes pueden enviar solicitudes a la sala"}.
{"Queries to the conference members are not allowed in this room", "En esta sala no se permiten solicitudes a los miembros de la sala"}.
{"You have been banned from this room", "Has sido bloqueado en esta sala"}.
{"Membership required to enter this room", "Necesitas ser miembro de esta sala para poder entrar"}.
{"Password required to enter this room", "Se necesita contraseña para entrar en esta sala"}.
{"Incorrect password", "Contraseña incorrecta"}.
{"Administrator privileges required", "Se necesita privilegios de administrador"}.
{"Moderator privileges required", "Se necesita privilegios de moderador"}.
{"JID ~s is invalid", "El JID ~s no es válido"}.
{"Nickname ~s does not exist in the room", "El apodo ~s no existe en la sala"}.
{"Invalid affiliation: ~s", "Afiliación no válida: ~s"}.
{"Invalid role: ~s", "Rol no válido: ~s"}.
{"Owner privileges required", "Se requieren privilegios de propietario de la sala"}.
{"private, ", "privado"}.

% mod_irc/mod_irc.erl
{"You need an x:data capable client to configure mod_irc settings", "Necesitas un cliente con soporte de x:data para configurar las opciones de mod_irc"}.
{"Registration in mod_irc for ", "Registro en mod_irc para"}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Introduce el nombre de usuario y codificaciones de carácteres que quieras usar al conectar en los servidores de IRC"}.
{"IRC Username", "Nombre de usuario en IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Si quieres especificar codificaciones de carácteres distintos para cada servidor IRC rellena esta lista con valores en el formato '{\"servidor irc\", \"codificación\"}'.  Este servicio usa por defecto la codificación \"~s\"."}.
{"Encodings", "Codificaciones"}.
{"ejabberd IRC module\nCopyright (c) 2003-2005 Alexey Shchepin", "Módulo de IRC para ejabberd\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Ejemplo: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.

% web/ejabberd_web_admin.erl
{"ejabberd administration", "Administración de ejabberd"}.
{"Users", "Usuarios"}.
{"Nodes", "Nodos"}.
{"Statistics", "Estadísticas"}.
{"(raw)", "(crudo)"}.
{"submitted", "enviado"}.
{"bad format", "mal formato"}.
{"raw", "crudo"}.
{"ejabberd access control lists configuration", "Configuración de las Listas de Control de Acceso de ejabberd"}.
{"Delete Selected", "Eliminar los seleccionados"}.
{"Submit", "Enviar"}.
{"ejabberd access rules configuration", "Configuración de las Reglas de Acceso de ejabberd"}.
{"~s access rule configuration", "Configuración de las Regla de Acceso ~s"}.
{"ejabberd users", "Usuarios de ejabberd"}.
{"ejabberd stats", "Estadísticas de ejabberd"}.
{"Node not found", "Nodo no encontrado"}.
{"Add New", "Añadir nuevo"}.
{"Registered users", "Usuarios registrados"}.
{"Online users", "Usuarios conectados"}.
{"Outgoing S2S servers", "Servidores conectados"}.
{"Change Password", "Cambiar contraseña"}.
{"Connected Resources:", "Recursos conectados:"}.
{"Password:", "Contraseña:"}.
{"None", "Ninguno"}.
{"Node ", "Nodo "}.
{"DB Management", "Gestión de la BD"}.
{"Listened Ports Management", "Gestión de los puertos de escucha"}.
{"Restart", "Reiniciar"}.
{"Stop", "Detener"}.
{"RPC call error", "Error en la llamada RPC"}.
{"DB Tables at ", "Tablas de la BD en "}.
{"Name", "Nombre"}.
{"Storage Type", "Tipo de almacenamiento"}.
{"Size", "Tamaño"}.
{"Memory", "Memoria"}.
{"Backup Management at ", "Gestión de copia de seguridad en "}.
{"Store a backup in a file", "Almacenar una copia de seguridad en fichero"}.
{"OK", "Aceptar"}.
{"Restore a backup from a file", "Recuperar una copia de seguridad de un fichero"}.
{"Install a database fallback from a file", "Instalar una recuperación de BD desde un fichero"}.
{"Dump a database in a text file", "Exportar una Base de Datos a un fichero de texto"}.
{"Restore a database from a text file", "Restaurar una Base de Datos desde un fichero de texto"}.
{"Listened Ports at ", "Puertos de escucha en "}.
{"~p statistics", "Estadísticas de ~p"}.
{"Uptime", "Tiempo de funcionamiento"}.
{"CPU Time", "Tiempo de procesador consumido"}.
{"Transactions commited", "Transacciones realizadas"}.
{"Transactions aborted", "Transacciones abortadas"}.
{"Transactions restarted", "Transacciones reiniciadas"}.
{"Transactions logged", "Transacciones almacenadas"}.
{"Port", "Puerto"}.
{"Module", "Módulo"}.
{"Options", "Opciones"}.
{"Update", "Actualizar"}.
{"Delete", "Eliminar"}.
{"Add User", "Añadir usuario"}.
{"Offline messages", "Mensajes diferidos"}.
{"Last Activity", "Última actividad"}.
{"Never", "Nunca"}.
{"~s offline messages queue", "~s cola de mensajes diferidos"}.
{"Time", "Fecha"}.
{"From", "De"}.
{"To", "Para"}.
{"Packet", "Paquete"}.
{"Offline messages:", "Mensajes diferidos:"}.
{"Roster", "Lista de contactos"}.
{"Nickname", "Apodo"}.
{"Subscription", "Subscripción"}.
{"Pending", "Pendiente"}.
{"Groups", "Grupos"}.
{"Remove", "Borrar"}.
{"Add JID", "Añadir JID"}.
{"User ", "Usuario "}.
{"Roster of ", "Lista de contactos de "}.
{"ejabberd (c) 2002-2005 Alexey Shchepin, 2004-2005 Process One", "ejabberd (c) 2002-2005 Alexey Shchepin, 2004-2005 Process One"}.
{"Shared Roster", "Grupos Compartidos"}.
{"Online", "Conectado"}.
{"JID", "JID"}.
{"Validate", "Validar"}.
{"Not found", "No encontrado"}.
{"Shared roster groups", "Grupos Compartidos"}.
{"Name:", "Nombre:"}.
{"Description:", "Descripción:"}.
{"Members:", "Miembros:"}.
{"Displayed Groups:", "Mostrar grupos:"}.
{"Group ", "Grupo "}.
{"Users last activity", "Última actividad de los usuarios"}.
{"Period: ", "Periodo: "}.
{"Last month", "Último mes"}.
{"Last year", "Último año"}.
{"All activity", "Toda la actividad"}.
{"Show Ordinary Table", "Mostrar Tabla Ordinaria"}.
{"Show Integral Table", "Mostrar Tabla Integral"}.
{"Authenticated users", "Usuarios autenticados"}.
{"No data", "No hay datos"}.
{"Modules Management", "Gestión de módulos"}.
{"Modules at ", "Módulos en "}.
{"Start", "Iniciar"}.
{"Virtual Hosts", "Hosts Virtuales"}.
{"ejabberd virtual hosts", "Hosts virtuales de ejabberd"}.
{"Host", "Host"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Es obligatorio usar STARTTLS"}.

% mod_vcard_ldap.erl
{"Given Name", "Nombre dado"}.
{"JID", "JID"}.
{"Fill in fields to search for any matching Jabber User", "Rellena campos para buscar usuarios Jabber que concuerden"}.

% Local Variables:
% mode: erlang
% End:
