% $Id$
% Language: Spanish (castellano)
% Author: Badlop

% jlib.hrl
{"No resource provided", "No se ha proporcionado recurso"}.

% mod_configure.erl
{"Choose storage type of tables", "Selecciona tipo de almacenamiento de las tablas"}.
{"RAM copy", "Copia en RAM"}.
{"RAM and disc copy", "Copia en RAM y disco"}.
{"Disc only copy", "Copia en disco solamente"}.
{"Remote copy", "Copia remota"}.
{"Stop Modules at ", "Detener módulos en "}.
{"Choose modules to stop", "Selecciona módulos a detener"}.
{"Start Modules at ", "Iniciar módulos en "}.
{"Enter list of {Module, [Options]}", "Introduce lista de {módulo, [opciones]}"}.
{"List of modules to start", "Lista de módulos a iniciar"}.
{"Backup to File at ", "Guardar copia de seguridad en fichero en "}.
{"Enter path to backup file", "Introduce ruta al fichero de copia de seguridad"}.
{"Path to File", "Ruta al fichero"}.
{"Restore Backup from File at ", "Restaura copia de seguridad desde el fichero en "}.
{"Dump Backup to Text File at ", "Exporta copia de seguridad a fichero de texto en "}.
{"Enter path to text file", "Introduce ruta al fichero de texto"}.
{"Import User from File at ", "Importa usuario desde fichero en "}.
{"Enter path to jabberd1.4 spool file", "Introduce ruta al fichero jabberd1.4 spool"}.
{"Import Users from Dir at ", "Importar usuarios desde el directorio en "}.
{"Enter path to jabberd1.4 spool dir", "Introduce la ruta al directorio de jabberd1.4 spools"}.
{"Path to Dir", "Ruta al directorio"}.
{"Access Control List Configuration", "Configuración de la Lista de Control de Acceso"}.
{"Access control lists", "Listas de Control de Acceso"}.
{"Access Configuration", "Configuración de accesos"}.
{"Access rules", "Reglas de acceso"}.
{"Administration of ", "Administración de "}.
{"Action on user", "Acción en el usuario"}.
{"Edit Properties", "Editar propiedades"}.
{"Remove User", "Eliminar usuario"}.
{"Database", "Base de datos"}.
{"Outgoing s2s Connections", "Conexiones S2S salientes"}.
{"Import Users From jabberd 1.4 Spool Files", "Importar usuarios de ficheros spool de jabberd-1.4"}.
{"Database Tables Configuration at ", "Configuración de tablas de la base de datos en "}.
{"Restart Service", "Reiniciar el servicio"}.
{"Shut Down Service", "Detener el servicio"}.
{"Delete User", "Borrar usuario"}.
{"End User Session", "Cerrar sesión de usuario"}.
{"Get User Password", "Ver contraseña de usuario"}.
{"Change User Password", "Cambiar contraseña de usuario"}.
{"Get User Last Login Time", "Ver fecha de la última conexión de usuario"}.
{"Get User Statistics", "Ver estadísticas de usuario"}.
{"Get Number of Registered Users", "Ver número de usuarios registrados"}.
{"Get Number of Online Users", "Ver número de usuarios conectados"}.
{"User Management", "Administración de usuarios"}.
{"Time delay", "Retraso temporal"}.
{"Password Verification", "Verificación de la contraseña"}.
{"Number of registered users", "Número de usuarios registrados"}.
{"Number of online users", "Número de usuarios conectados"}.
{"Last login", "Última conexión"}.
{"Roster size", "Tamaño de la lista de contactos"}.
{"IP addresses", "Direcciones IP"}.
{"Resources", "Recursos"}.

% mod_disco.erl
{"Configuration", "Configuración"}.
{"Online Users", "Usuarios conectados"}.
{"All Users", "Todos los usuarios"}.
{"To ~s", "A ~s"}.
{"From ~s", "De ~s"}.
{"Running Nodes", "Nodos funcionando"}.
{"Stopped Nodes", "Nodos detenidos"}.
{"Access Control Lists", "Listas de Control de Acceso"}.
{"Access Rules", "Reglas de Acceso"}.
{"Modules", "Módulos"}.
{"Start Modules", "Iniciar módulos"}.
{"Stop Modules", "Detener módulos"}.
{"Backup", "Guardar copia de seguridad"}.
{"Restore", "Restaurar"}.
{"Dump to Text File", "Exportar a fichero de texto"}.
{"Import File", "Importar fichero"}.
{"Import Directory", "Importar directorio"}.

% mod_register.erl
{"Users are not allowed to register accounts so fast", "Los usuarios no tienen permitido crear cuentas con tanta rapidez"}.
{"Choose a username and password to register with this server", "Escoge un nombre de usuario y contraseña para registrarte en este servidor"}.

% mod_vcard.erl
{"Erlang Jabber Server", "Servidor Jabber en Erlang"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Rellena el formulario para buscar usuarios Jabber. Añade * al final de un campo para buscar subcadenas."}.
{"ejabberd vCard module", "Módulo vCard para ejabberd"}.
{"You need an x:data capable client to search", "Necesitas un cliente con soporte de x:data para poder buscar"}.
{"Search users in ", "Buscar usuarios en "}.

% mod_vcard_odbc.erl
{"Email", "correo"}.
{"Search Results for ", "Buscar resultados por "}.
{"Jabber ID", "Jabber ID"}.
{"vCard User Search", "Buscar vCard de usuario"}.
{"User",              "Usuario"}.
{"Full Name", 	      "Nombre completo"}.
{"Name", 	      "Nombre"}.
{"Middle Name",       "Segundo nombre"}.
{"Family Name",       "Apellido"}.
{"Nickname", 	      "Apodo"}.
{"Birthday", 	      "Cumpleaños"}.
{"Country", 	      "País"}.
{"City", 	      "Ciudad"}.
{"Organization Name", "Nombre de la organización"}.
{"Organization Unit", "Unidad de la organización"}.

% mod_pubsub/mod_pubsub.erl
{"A friendly name for the node", "Un nombre sencillo para el nodo"}.
{"Roster groups allowed to subscribe", "Grupos de contactos que pueden suscribirse"}.
{"Deliver payloads with event notifications", "Enviar contenidos junto con las notificaciones de eventos"}.
{"Notify subscribers when the node configuration changes", "Notificar subscriptores cuando cambia la configuración del nodo"}.
{"Notify subscribers when the node is deleted", "Notificar subscriptores cuando el nodo se borra"}.
{"Notify subscribers when items are removed from the node", "Notificar subscriptores cuando los elementos se borran del nodo"}.
{"Persist items to storage", "Persistir elementos al almacenar"}.
{"Max # of items to persist", "Máximo # de elementos que persisten"}.
{"Whether to allow subscriptions", "Permitir subscripciones"}.
{"Specify the publisher model", "Especificar el modelo del publicante"}.
{"Max payload size in bytes", "Máximo tamaño del contenido en bytes"}.
{"Only deliver notifications to available users", "Solo enviar notificaciones a los usuarios disponibles"}.
{"Publish-Subscribe", "Servicio de Publicar-Subscribir"}.
{"ejabberd Publish-Subscribe module", "Módulo de Publicar-Subscribir de ejabberd"}.
{"PubSub subscriber request", "Petición de subscriptor de PubSub"}.
{"Choose whether to approve this entity's subscription.", "Decidir si aprobar la subscripción de esta entidad."}.
{"Node ID", "Nodo ID"}.
{"Subscriber Address", "Dirección del subscriptor"}.
{"Allow this JID to subscribe to this pubsub node?", "¿Deseas permitir a este JabberID que se subscriba a este nodo PubSub?"}.
{"Deliver event notifications", "Entregar notificaciones de eventos"}.
{"Specify the access model", "Especifica el modelo de acceso"}.
{"When to send the last published item", "Cuando enviar el último elemento publicado"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "Necesitas un cliente con soporte de x:data para poder registrar el apodo"}.
{"Nickname Registration at ", "Registro del apodo en "}.
{"Enter nickname you want to register", "Introduce el apodo que quieras registrar"}.
{"Only service administrators are allowed to send service messages", "Solo los administradores del servicio tienen permiso para enviar mensajes de servicio"}.
{"Conference room does not exist", "La sala de conferencias no existe"}.
{"Access denied by service policy", "Acceso denegado por la política del servicio"}.
{"You must fill in field \"Nickname\" in the form", "Debes rellenar el campo \"Apodo\" en el formulario"}.
{"Specified nickname is already registered", "El apodo especificado ya está registrado, tendrás que buscar otro"}.
{"Room creation is denied by service policy", "Se te ha denegado crear la sala por política del servicio"}.
{"ejabberd MUC module", "Módulo de MUC para ejabbed"}.
{"Chatrooms", "Salas de charla"}.

% mod_muc/mod_muc_room.erl
{"It is not allowed to send private messages", "No está permitido enviar mensajes privados"}.
{"Visitors are not allowed to change their nicknames in this room", "Los visitantes no tienen permitido cambiar sus apodos en esta sala"}.
{"Allow visitors to send status text in presence updates", "Permitir a los visitantes enviar texto de estado en las actualizaciones de presencia"}.
{"Allow visitors to change nickname", "Permitir a los visitantes cambiarse el apodo"}.
{"This participant is kicked from the room because he sent an error message to another participant", "Este participante ha sido expulsado de la sala porque envió un mensaje de error a otro participante"}.
{"This participant is kicked from the room because he sent an error message", "Este participante ha sido expulsado de la sala porque envió un mensaje de error"}.
{"This participant is kicked from the room because he sent an error presence", "Este participante ha sido expulsado de la sala porque envió una presencia de error"}.
{"Make room moderated", "Sala moderada"}.
{" has set the subject to: ", " ha puesto el asunto: "}.
{"You need an x:data capable client to configure room", "Necesitas un cliente con soporte de x:data para configurar la sala"}.
{"Configuration for ", "Configuración para "}.
{"Room title", "Título de la sala"}.
{"Allow users to change subject", "Permitir a los usuarios cambiar el asunto"}.
{"Allow users to query other users", "Permitir a los usuarios consultar a otros usuarios"}.
{"Allow users to send private messages", "Permitir a los usuarios enviar mensajes privados"}.
{"Make room public searchable", "Sala públicamente visible"}.
{"Make participants list public", "La lista de participantes es pública"}.
{"Make room persistent", "Sala permanente"}.
{"Default users as participants", "Los usuarios son participantes por defecto"}.
{"Make room members-only", "Sala sólo para miembros"}.
{"Allow users to send invites", "Permitir a los usuarios enviar invitaciones"}.
{"Make room password protected", "Proteger la sala con contraseña"}.
{"Password", "Contraseña"}.
{"This room is not anonymous", "Sala no anónima"}.
{"Enable logging", "Guardar históricos"}.
{"Only moderators and participants are allowed to change subject in this room", "Solo los moderadores y participantes pueden cambiar el asunto de esta sala"}.
{"Only moderators are allowed to change subject in this room", "Solo los moderadores pueden cambiar el asunto de esta sala"}.
{"Visitors are not allowed to send messages to all occupants", "Los visitantes no pueden enviar mensajes a todos los ocupantes"}.
{"Only occupants are allowed to send messages to the conference", "Solo los ocupantes pueden enviar mensajes a la sala"}.
{"It is not allowed to send private messages to the conference", "Impedir el envio de mensajes privados a la sala"}.
{"Improper message type", "Tipo de mensaje incorrecto"}.
{"Nickname is already in use by another occupant", "El apodo ya está siendo usado por otro ocupante"}.
{"Nickname is registered by another person", "El apodo ya está registrado por otra persona"}.
{"It is not allowed to send private messages of type \"groupchat\"", "No está permitido enviar mensajes privados del tipo \"groupchat\""}.
{"Recipient is not in the conference room", "El receptor no está en la sala de conferencia"}.
{"Only occupants are allowed to send queries to the conference", "Solo los ocupantes pueden enviar solicitudes a la sala"}.
{"Queries to the conference members are not allowed in this room", "En esta sala no se permiten solicitudes a los miembros de la sala"}.
{"You have been banned from this room", "Has sido bloqueado en esta sala"}.
{"Membership required to enter this room", "Necesitas ser miembro de esta sala para poder entrar"}.
{"Password required to enter this room", "Se necesita contraseña para entrar en esta sala"}.
{"Incorrect password", "Contraseña incorrecta"}.
{"Administrator privileges required", "Se necesita privilegios de administrador"}.
{"Moderator privileges required", "Se necesita privilegios de moderador"}.
{"JID ~s is invalid", "El JID ~s no es válido"}.
{"Nickname ~s does not exist in the room", "El apodo ~s no existe en la sala"}.
{"Invalid affiliation: ~s", "Afiliación no válida: ~s"}.
{"Invalid role: ~s", "Rol no válido: ~s"}.
{"Owner privileges required", "Se requieren privilegios de propietario de la sala"}.
{"private, ", "privado"}.
{"Number of occupants", "Número de ocupantes"}.
{"Present real JIDs to", "Los JID reales pueden verlos"}.
{"moderators only", "solo moderadores"}.
{"anyone", "cualquiera"}.
{"Traffic rate limit is exceeded", "Se ha exedido el límite de tráfico"}.
{"Maximum Number of Occupants", "Número máximo de ocupantes"}.
{"No limit", "Sin límite"}.
{"~s invites you to the room ~s", "~s te invita a la sala ~s"}.
{"the password is", "la contraseña es"}.

% mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "ha sido expulsado por un cambio de su afiliación"}.
{"has been kicked because the room has been changed to members-only", "ha sido expulsado porque la sala es ahora solo para miembros"}.
{"has been kicked because of a system shutdown", "ha sido expulsado porque el sistema se va a detener"}.
{"Chatroom configuration modified", "Configuración de la sala modificada"}.
{"joins the room", "entra en la sala"}.
{"leaves the room", "sale de la sala"}.
{"has been kicked", "ha sido expulsado"}.
{"has been banned", "ha sido bloqueado"}.
{"is now known as", "se cambia el nombre a"}.
{"Monday", "lunes"}.
{"Tuesday", "martes"}.
{"Wednesday", "miércoles"}.
{"Thursday", "jueves"}.
{"Friday", "viernes"}.
{"Saturday", "sábado"}.
{"Sunday", "domingo"}.
{"January", "enero"}.
{"February", "febrero"}.
{"March", "marzo"}.
{"April", "abril"}.
{"May", "mayo"}.
{"June", "junio"}.
{"July", "julio"}.
{"August", "agosto"}.
{"September", "septiembre"}.
{"October", "octubre"}.
{"November", "noviembre"}.
{"December", "diciembre"}.
{"Room Configuration", "Configuración de la sala"}.

% mod_irc/mod_irc.erl
{"You need an x:data capable client to configure mod_irc settings", "Necesitas un cliente con soporte de x:data para configurar las opciones de mod_irc"}.
{"Registration in mod_irc for ", "Registro en mod_irc para"}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Introduce el nombre de usuario y codificaciones de carácteres que quieras usar al conectar en los servidores de IRC"}.
{"IRC Username", "Nombre de usuario en IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Si quieres especificar codificaciones de carácteres distintos para cada servidor IRC rellena esta lista con valores en el formato '{\"servidor irc\", \"codificación\"}'.  Este servicio usa por defecto la codificación \"~s\"."}.
{"Encodings", "Codificaciones"}.
{"ejabberd IRC module", "Módulo de IRC para ejabberd"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Ejemplo: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"IRC Transport", "Transporte de IRC"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "ejabberd Web Admin"}.
{"Users", "Usuarios"}.
{"Nodes", "Nodos"}.
{"Statistics", "Estadísticas"}.
{"Delete Selected", "Eliminar los seleccionados"}.
{"Submit", "Enviar"}.
{"~s access rule configuration", "Configuración de las Regla de Acceso ~s"}.
{"Node not found", "Nodo no encontrado"}.
{"Add New", "Añadir nuevo"}.
{"Change Password", "Cambiar contraseña"}.
{"Connected Resources:", "Recursos conectados:"}.
{"Password:", "Contraseña:"}.
{"None", "Ninguno"}.
{"Node ", "Nodo "}.
{"Restart", "Reiniciar"}.
{"Stop", "Detener"}.
{"Name", "Nombre"}.
{"Storage Type", "Tipo de almacenamiento"}.
{"Size", "Tamaño"}.
{"Memory", "Memoria"}.
{"Backup Management", "Gestión de copia de seguridad"}.
{"OK", "Aceptar"}.
{"Listened Ports at ", "Puertos de escucha en "}.
{"Port", "Puerto"}.
{"Module", "Módulo"}.
{"Options", "Opciones"}.
{"Update", "Actualizar"}.
{"Delete", "Eliminar"}.
{"Add User", "Añadir usuario"}.
{"Last Activity", "Última actividad"}.
{"Never", "Nunca"}.
{"Time", "Fecha"}.
{"From", "De"}.
{"To", "Para"}.
{"Packet", "Paquete"}.
{"Roster", "Lista de contactos"}.
{"Nickname", "Apodo"}.
{"Subscription", "Subscripción"}.
{"Pending", "Pendiente"}.
{"Groups", "Grupos"}.
{"Remove", "Borrar"}.
{"User ", "Usuario "}.
{"Roster of ", "Lista de contactos de "}.
{"Online", "Conectado"}.
{"Validate", "Validar"}.
{"Name:", "Nombre:"}.
{"Description:", "Descripción:"}.
{"Members:", "Miembros:"}.
{"Displayed Groups:", "Mostrar grupos:"}.
{"Group ", "Grupo "}.
{"Period: ", "Periodo: "}.
{"Last month", "Último mes"}.
{"Last year", "Último año"}.
{"All activity", "Toda la actividad"}.
{"Show Ordinary Table", "Mostrar Tabla Ordinaria"}.
{"Show Integral Table", "Mostrar Tabla Integral"}.
{"Modules at ", "Módulos en "}.
{"Start", "Iniciar"}.
{"Virtual Hosts", "Dominios"}.
{"ejabberd virtual hosts", "Dominios de ejabberd"}.
{"Host", "Dominio"}.
{"Restore plain text backup immediately:", "Restaurar copias de seguridad de texto plano inmediatamente:"}.
{"Statistics of ~p", "Estadísticas de ~p"}.
{"Uptime:", "Tiempo desde el inicio:"}.
{"CPU Time:", "Tiempo consumido de CPU:"}.
{"Transactions Commited:", "Transacciones finalizadas:"}.
{"Transactions Aborted:", "Transacciones abortadas:"}.
{"Transactions Restarted:", "Transacciones reiniciadas:"}.
{"Transactions Logged:", "Transacciones registradas:"}.
{"Update ", "Actualizar "}.
{"Update plan", "Plan de actualización"}.
{"Updated modules", "Módulos actualizados"}.
{"Update script", "Script de actualización"}.
{"Low level update script", "Script de actualización a bajo nivel"}.
{"Script check", "Comprobación de script"}.
{"Shared Roster Groups", "Grupos Compartidos"}.
{"Administration", "Administración"}.
{"(Raw)", "(crudo)"}.
{"Submitted", "Enviado"}.
{"Bad format", "Mal formato"}.
{"Raw", "Crudo"}.
{"Users Last Activity", "Última actividad de los usuarios"}.
{"Registered Users", "Usuarios registrados"}.
{"Offline Messages", "Mensajes diferidos"}.
{"Registered Users:", "Usuarios registrados:"}.
{"Online Users:", "Usuarios conectados:"}.
{"Outgoing s2s Connections:", "Conexiones S2S salientes:"}.
{"Outgoing s2s Servers:", "Servidores S2S salientes:"}.
{"Offline Messages:", "Mensajes diferidos:"}.
{"~s's Offline Messages Queue", "Cola de mensajes diferidos de ~s"}.
{"Add Jabber ID", "Añadir Jabber ID"}.
{"No Data", "Sin datos"}.
{"Listened Ports", "Puertos de escucha"}.
{"RPC Call Error", "Error en la llamada RPC"}.
{"Database Tables at ", "Tablas de la base de datos en "}.
{"Backup of ", "Copia de seguridad de "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Ten en cuenta que estas opciones solo harán copia de seguridad de la base de datos Mnesia embebida. Si estás usando ODBC tendrás que hacer también copia de seguridad de tu base de datos SQL."}.
{"Store binary backup:", "Guardar copia de seguridad binaria:"}.
{"Restore binary backup immediately:", "Restaurar inmediatamente copia de seguridad binaria:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Restaurar copia de seguridad binaria en el siguiente reinicio de ejabberd (requiere menos memoria que si instantánea):"}.
{"Store plain text backup:", "Guardar copia de seguridad en texto plano:"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Es obligatorio usar STARTTLS"}.
{"Replaced by new connection", "Reemplazado por una nueva conexión"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Rellena campos para buscar usuarios Jabber que concuerden"}.

% mod_adhoc.erl
{"Commands", "Comandos"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Really delete message of the day?", "¿Está seguro de quere borrar el mensaje del dia?"}.
{"Subject", "Asunto"}.
{"Message body", "Cuerpo del mensaje"}.
{"No body provided for announce message", "No se ha proporcionado cuerpo de mensaje para el anuncio"}.
{"Announcements", "Anuncios"}.
{"Send announcement to all users", "Enviar anuncio a todos los usuarios"}.
{"Send announcement to all online users", "Enviar anuncio a todos los usuarios conectados"}.
{"Send announcement to all online users on all hosts", "Enviar anuncio a todos los usuarios conectados en todos los dominios"}.
{"Set message of the day and send to online users", "Poner mensaje del dia y enviar a todos los usuarios conectados"}.
{"Update message of the day (don't send)", "Actualizar mensaje del dia, pero no enviarlo"}.
{"Delete message of the day", "Borrar mensaje del dia"}.
{"Send announcement to all users on all hosts", "Enviar anuncio a todos los usuarios en todos los dominios"}.
{"Set message of the day on all hosts and send to online users", "Poner mensaje del día en todos los dominios y enviar a los usuarios conectados"}.
{"Update message of the day on all hosts (don't send)", "Actualizar el mensaje del día en todos los dominos (pero no enviarlo)"}.
{"Delete message of the day on all hosts", "Borrar el mensaje del día en todos los dominios"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "Módulo SOCKS5 Bytestreams para ejabberd"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Tu cola de mensajes diferidos de contactos está llena. El mensaje se ha descartado."}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
