{"Access Configuration","Configuration d'accès"}.
{"Access Control List Configuration","Configuration des droits (ACL)"}.
{"Access control lists","Droits (ACL)"}.
{"Access Control Lists","Droits (ACL)"}.
{"Access denied by service policy","L'accès au service est refusé"}.
{"Access rules","Règles d'accès"}.
{"Access Rules","Règles d'accès"}.
{"Action on user","Action sur l'utilisateur"}.
{"Add Jabber ID","Ajouter un Jabber ID"}.
{"Add New","Ajouter"}.
{"Add User","Ajouter un utilisateur"}.
{"Administration","Administration"}.
{"Administration of ","Administration de "}.
{"Administrator privileges required","Les droits d'administrateur sont nécessaires"}.
{"A friendly name for the node","Un nom convivial pour le noeud"}.
{"All activity","Toute activité"}.
{"Allow this JID to subscribe to this pubsub node?","Autoriser ce JID à s'abonner à ce noeud pubsub"}.
{"Allow users to change subject","Autoriser les utilisateurs à changer le sujet"}.
{"Allow users to query other users","Permettre aux utilisateurs d'envoyer des requêtes aux autres utilisateurs"}.
{"Allow users to send invites","Permettre aux utilisateurs d'envoyer des invitations"}.
{"Allow users to send private messages","Autoriser les utilisateurs à envoyer des messages privés"}.
{"Allow visitors to change nickname","Autoriser les visiteurs à changer de pseudo"}.
{"Allow visitors to send status text in presence updates","Autoriser les visiteurs à envoyer un message d'état avec leur présence"}.
{"All Users","Tous les utilisateurs"}.
{"Announcements","Annonces"}.
{"anyone","tout le monde"}.
{"April","Avril"}.
{"August","Août"}.
{"Backup Management","Gestion des sauvegardes"}.
{"Backup of ","Sauvegarde de "}.
{"Backup","Sauvegarde"}.
{"Backup to File at ","Sauvegarde sur fichier sur "}.
{"Bad format","Mauvais format"}.
{"Birthday","Date d'anniversaire"}.
{"Change Password","Modifier le mot de passe"}.
{"Change User Password","Changer le mot de passe de l'utilisateur"}.
{"Chatroom configuration modified","Configuration du salon modifiée"}.
{"Chatrooms","Salons de discussion"}.
{"Choose a username and password to register with this server","Choisissez un nom d'utilisateur et un mot de passe pour s'enregistrer sur ce serveur"}.
{"Choose modules to stop","Sélectionnez les modules à arrêter"}.
{"Choose storage type of tables","Choisissez un type de stockage pour les tables"}.
{"Choose whether to approve this entity's subscription.","Accepter cet abonnement ?"}.
{"City","Ville"}.
{"Commands","Commandes"}.
{"Conference room does not exist","La salle de conférence n'existe pas"}.
{"Configuration","Configuration"}.
{"Configuration for ","Configuration pour "}.
{"Connected Resources:","Ressources connectées:"}.
{"Country","Pays"}.
{"CPU Time:","Temps CPU:"}.
{"Database","Base de données"}.
{"Database Tables at ","Tables de base de données sur "}.
{"Database Tables Configuration at ","Configuration des tables de base de données sur "}.
{"December","Décembre"}.
{"Default users as participants","Les utilisateurs sont par défaut participant"}.
{"Delete message of the day on all hosts","Supprimer le message du jour sur tous les domaines"}.
{"Delete message of the day","Supprimer le message du jour"}.
{"Delete Selected","Suppression des éléments sélectionnés"}.
{"Delete","Supprimer"}.
{"Delete User","Supprimer l'utilisateur"}.
{"Deliver event notifications","Envoyer les notifications d'événement"}.
{"Deliver payloads with event notifications","Inclure le contenu du message avec la notification"}.
{"Description:","Description:"}.
{"Disc only copy","Copie sur disque uniquement"}.
{"Displayed Groups:","Groupes affichés:"}.
{"Dump Backup to Text File at ","Enregistrer la sauvegarde dans un fichier texte sur "}.
{"Dump to Text File","Sauvegarder dans un fichier texte"}.
{"Edit Properties","Modifier les propriétés"}.
{"ejabberd IRC module","Module IRC ejabberd"}.
{"ejabberd MUC module","Module MUC ejabberd"}.
{"ejabberd Publish-Subscribe module","Module Publish-Subscribe d'ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams module"}.
{"ejabberd vCard module","Module vCard ejabberd"}.
{"ejabberd virtual hosts","Serveurs virtuels d'ejabberd"}.
{"ejabberd Web Admin","Console Web d'administration de ejabberd"}.
{"Email","Email"}.
{"Enable logging","Activer l'archivage"}.
{"Encodings","Encodages"}.
{"End User Session","Terminer la session de l'utilisateur"}.
{"Enter list of {Module, [Options]}","Entrez une liste de {Module, [Options]}"}.
{"Enter nickname you want to register","Entrez le pseudo que vous souhaitez enregistrer"}.
{"Enter path to backup file","Entrez le chemin vers le fichier de sauvegarde"}.
{"Enter path to jabberd1.4 spool dir","Entrez le chemin vers le répertoire de spool jabberd1.4"}.
{"Enter path to jabberd1.4 spool file","Entrez le chemin vers le fichier spool jabberd1.4"}.
{"Enter path to text file","Entrez le chemin vers le fichier texte"}.
{"Enter username and encodings you wish to use for connecting to IRC servers","Entrez le nom d'utilisateur et les encodages que vous souhaitez utiliser pour vous connecter aux serveurs IRC"}.
{"Erlang Jabber Server","Serveur Jabber Erlang"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].","Exemple: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Family Name","Nom de famille"}.
{"February","Février"}.
{"Fill in fields to search for any matching Jabber User","Remplissez les champs pour rechercher un utilisateur Jabber"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Remplissez le formulaire pour recherche un utilisateur Jabber (Ajouter * à la fin du champ pour chercher n'importe quelle fin de chaîne"}.
{"Friday","Vendredi"}.
{"From","De"}.
{"From ~s","De ~s"}.
{"Full Name","Nom complet"}.
{"Get Number of Online Users","Récupérer le nombre d'utilisateurs en ligne"}.
{"Get Number of Registered Users","Récupérer le nombre d'utilisateurs enregistrés"}.
{"Get User Last Login Time","Récupérer la dernière date de connexion de l'utilisateur"}.
{"Get User Password","Récupérer le mot de passe de l'utilisateur"}.
{"Get User Statistics","Récupérer les statistiques de l'utilisateur"}.
{"Group ","Groupe "}.
{"Groups","Groupes"}.
{"has been banned","a été banni"}.
{"has been kicked","a été expulsé"}.
{"has been kicked because of an affiliation change","a été éjecté à cause d'un changement d'autorisation"}.
{"has been kicked because of a system shutdown","a été éjecté en raison de l'arrêt du système"}.
{"has been kicked because the room has been changed to members-only","a été éjecté car la salle est désormais réservée aux membres"}.
{" has set the subject to: "," a changé le sujet pour: "}.
{"Host","Serveur"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","Si vous voulez préciser différents encodages pour les serveurs IRC, remplissez cette liste avec des valeurs dans le format '{\"serveur irc\", \"encodage\"}'. Par défaut ce service utilise l'encodage \"~s\"."}.
{"Import Directory","Importer une répertoire"}.
{"Import File","Importer un fichier"}.
{"Import User from File at ","Importer un utilisateur depuis le fichier sur "}.
{"Import Users from Dir at ","Importer des utilisateurs depuis le répertoire sur "}.
{"Import Users From jabberd 1.4 Spool Files","Importer des utilisateurs depuis un fichier spool Jabberd 1.4"}.
{"Improper message type","Mauvais type de message"}.
{"Incorrect password","Mot de passe incorrect"}.
{"Invalid affiliation: ~s","Affiliation invalide: ~s"}.
{"Invalid role: ~s","Role invalide: ~s"}.
{"IP addresses","Adresses IP"}.
{"IRC Transport","Passerelle IRC"}.
{"IRC Username","Nom d'utilisateur IRC"}.
{"is now known as","est maintenant connu comme"}.
{"It is not allowed to send private messages","L'envoi de messages privés n'est pas autorisé"}.
{"It is not allowed to send private messages of type \"groupchat\"","Il n'est pas permis d'envoyer des messages privés de type \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Il n'est pas permis d'envoyer des messages \"normaux\" à la conférence"}.
{"Jabber ID","Jabber ID"}.
{"January","Janvier"}.
{"JID ~s is invalid","Le JID ~s n'est pas valide"}.
{"joins the room","rejoint le salon"}.
{"July","Juillet"}.
{"June","Juin"}.
{"Last Activity","Dernière Activité"}.
{"Last login","Dernière connexion"}.
{"Last month","Dernier mois"}.
{"Last year","Dernière année"}.
{"leaves the room","quitte le salon"}.
{"Listened Ports at ","Ports ouverts sur "}.
{"Listened Ports","Ports ouverts"}.
{"List of modules to start","Liste des modules à démarrer"}.
{"Low level update script","Script de mise à jour de bas-niveau"}.
{"Make participants list public","Rendre la liste des participants publique"}.
{"Make room members-only","Réserver le salon aux membres uniquement"}.
{"Make room moderated","Rendre le salon modéré"}.
{"Make room password protected","Protéger le salon par mot de passe"}.
{"Make room persistent","Rendre le salon persistant"}.
{"Make room public searchable","Rendre le salon public"}.
{"March","Mars"}.
{"Maximum Number of Occupants","Nombre maximum d'occupants"}.
{"Max # of items to persist","Nombre maximum d'éléments à stocker"}.
{"Max payload size in bytes","Taille maximum pour le contenu du message en octet"}.
{"May","Mai"}.
{"Membership required to enter this room","Vous devez être membre pour accèder à ce salon"}.
{"Members:","Membres:"}.
{"Memory","Mémoire"}.
{"Message body","Corps du message"}.
{"Middle Name","Autre nom"}.
{"Moderator privileges required","Les droits de modérateur sont nécessaires"}.
{"moderators only","modérateurs seulement"}.
{"Module","Module"}.
{"Modules at ","Modules sur "}.
{"Modules","Modules"}.
{"Monday","Lundi"}.
{"Name:","Nom:"}.
{"Name","Nom"}.
{"Never","Jamais"}.
{"Nickname is already in use by another occupant","Le pseudo est déjà utilisé par un autre occupant"}.
{"Nickname is registered by another person","Le pseudo est enregistré par une autre personne"}.
{"Nickname","Pseudo"}.
{"Nickname Registration at ","Enregistrement d'un pseudo sur "}.
{"Nickname ~s does not exist in the room","Le pseudo ~s n'existe pas dans ce salon"}.
{"No body provided for announce message","Pas de corps de message pour l'annonce"}.
{"No Data","Aucune information disponible"}.
{"Node ID","Identifiant du noeud"}.
{"Node ","Noeud "}.
{"Node not found","Noeud non trouvé"}.
{"Nodes","Noeuds"}.
{"No limit","Pas de limite"}.
{"None","Aucun"}.
{"No resource provided","Aucune ressource fournie"}.
{"Notify subscribers when items are removed from the node","Avertir les abonnés lorsque des éléments sont supprimés sur le noeud"}.
{"Notify subscribers when the node configuration changes","Avertir les abonnés lorsque la configuration du noeud change"}.
{"Notify subscribers when the node is deleted","Avertir les abonnés lorsque le noeud est supprimé"}.
{"November","Novembre"}.
{"Number of occupants","Nombre d'occupants"}.
{"Number of online users","Nombre d'utilisateurs en ligne"}.
{"Number of registered users","Nombre d'utilisateurs enregistrés"}.
{"October","Octobre"}.
{"Offline Messages:","Messages en attente:"}.
{"Offline Messages","Messages en attente"}.
{"OK","OK"}.
{"Online","En ligne"}.
{"Online Users:","Utilisateurs connectés:"}.
{"Online Users","Utilisateurs en ligne"}.
{"Only deliver notifications to available users","Envoyer les notifications uniquement aux utilisateurs disponibles"}.
{"Only moderators and participants are allowed to change subject in this room","Seuls les modérateurs et les participants peuvent changer le sujet dans ce salon"}.
{"Only moderators are allowed to change subject in this room","Seuls les modérateurs peuvent changer le sujet dans ce salon"}.
{"Only occupants are allowed to send messages to the conference","Seuls les occupants peuvent envoyer des messages à la conférence"}.
{"Only occupants are allowed to send queries to the conference","Seuls les occupants sont autorisés à envoyer des requêtes à la conférence"}.
{"Only service administrators are allowed to send service messages","Seuls les administrateurs du service sont autoriser à envoyer des messages de service"}.
{"Options","Options"}.
{"Organization Name","Nom de l'organisation"}.
{"Organization Unit","Unité de l'organisation"}.
{"Outgoing s2s Connections:","Connexions s2s sortantes:"}.
{"Outgoing s2s Connections","Connexions s2s sortantes"}.
{"Outgoing s2s Servers:","Serveurs s2s sortants"}.
{"Owner privileges required","Les droits de propriétaire sont nécessaires"}.
{"Packet","Paquet"}.
{"Password:","Mot de passe:"}.
{"Password","Mot de passe"}.
{"Password required to enter this room","Un mot de passe est nécessaire pour accèder à ce salon"}.
{"Password Verification","Vérification du mot de passe"}.
{"Path to Dir","Chemin vers le répertoire"}.
{"Path to File","Chemin vers le fichier"}.
{"Pending","En suspend"}.
{"Period: ","Période:"}.
{"Persist items to storage","Stockage persistant des éléments"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","Port"}.
{"Present real JIDs to","Rendre le JID réel visible pour"}.
{"private, ","privé"}.
{"Publish-Subscribe","Publication-Abonnement"}.
{"PubSub subscriber request","Demande d'abonnement PubSub"}.
{"Queries to the conference members are not allowed in this room","Les requêtes sur les membres de la conférence ne sont pas autorisé dans ce salon"}.
{"RAM and disc copy","Copie en mémoire vive (RAM) et sur disque"}.
{"RAM copy","Copie en mémoire vive (RAM)"}.
{"(Raw)","(Brut)"}.
{"Raw","Brut"}.
{"Really delete message of the day?","Confirmer la suppression du message du jour ?"}.
{"Recipient is not in the conference room","Le destinataire n'est pas dans la conférence"}.
{"Registered Users:","Utilisateurs enregistrés:"}.
{"Registered Users","Utilisateurs enregistrés"}.
{"Registration in mod_irc for ","Enregistrement du mod_irc pour "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Ces options sauvegardent uniquement la base de données interne Mnesia. Si vous utilisez le module ODBC vous devez sauvegarde votre base SQL séparément."}.
{"Remote copy","Copie distante"}.
{"Remove","Enlever"}.
{"Remove User","Supprimer l'utilisateur"}.
{"Replaced by new connection","Remplacé par une nouvelle connexion"}.
{"Resources","Ressources"}.
{"Restart","Redémarrer"}.
{"Restart Service","Redémarrer le service"}.
{"Restore Backup from File at ","Restaurer la sauvegarde depuis le fichier sur "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Restauration de la sauvegarde binaire après redémarrage (nécessite moins de mémoire):"}.
{"Restore binary backup immediately:","Restauration immédiate d'une sauvegarde binaire:"}.
{"Restore plain text backup immediately:","Restauration immédiate d'une sauvegarde texte:"}.
{"Restore","Restauration"}.
{"Room Configuration","Configuration du salon"}.
{"Room creation is denied by service policy","La création de salons est interdite par le service"}.
{"Room title","Titre du salon"}.
{"Roster groups allowed to subscribe","Groupes de liste de contact autorisés à s'abonner"}.
{"Roster","Liste de contacts"}.
{"Roster of ","Liste de contact de "}.
{"Roster size","Taille de la liste de contacts"}.
{"RPC Call Error","Erreur d'appel RPC"}.
{"Running Nodes","Noeuds actifs"}.
{"~s access rule configuration","Configuration des règles d'accès ~s"}.
{"Saturday","Samedi"}.
{"Script check","Validation du script"}.
{"Search Results for ","Résultats de recherche pour "}.
{"Search users in ","Rechercher des utilisateurs "}.
{"Send announcement to all online users","Envoyer l'annonce à tous les utilisateurs en ligne"}.
{"Send announcement to all online users on all hosts","Envoyer l'annonce à tous les utilisateurs en ligne sur tous les serveurs"}.
{"Send announcement to all users","Envoyer l'annonce à tous les utilisateurs"}.
{"Send announcement to all users on all hosts","Envoyer une annonce à tous les utilisateurs de tous les domaines"}.
{"September","Septembre"}.
{"Set message of the day and send to online users","Définir le message du jour et l'envoyer aux utilisateurs en ligne"}.
{"Set message of the day on all hosts and send to online users","Définir le message du jour pour tous domaines et l'envoyer aux utilisateurs en ligne"}.
{"Shared Roster Groups","Groupes de liste de contacts partagée"}.
{"Show Integral Table","Montrer la table intégralement"}.
{"Show Ordinary Table","Montrer la table ordinaire"}.
{"Shut Down Service","Arrêter le service"}.
{"~s invites you to the room ~s","~s vous a invité dans la salle de discussion ~s"}.
{"Size","Taille"}.
{"Specified nickname is already registered","Le pseudo demandé est déjà enregistré"}.
{"Specify the access model","Définir le modèle d'accès"}.
{"Specify the publisher model","Définir le modèle de publication"}.
{"~s's Offline Messages Queue","~s messages en file d'attente"}.
{"Start","Démarrer"}.
{"Start Modules at ","Démarrer les modules sur "}.
{"Start Modules","Modules de démarrage"}.
{"Statistics of ~p","Statistiques de ~p"}.
{"Statistics","Statistiques"}.
{"Stop","Arrêter"}.
{"Stop Modules at ","Arrêter les modules sur "}.
{"Stop Modules","Modules d'arrêt"}.
{"Stopped Nodes","Noeuds arrêtés"}.
{"Storage Type","Type de stockage"}.
{"Store binary backup:","Sauvegarde binaire:"}.
{"Store plain text backup:","Sauvegarde texte:"}.
{"Subject","Sujet"}.
{"Submit","Soumettre"}.
{"Submitted","Soumis"}.
{"Subscriber Address","Adresse de l'abonné"}.
{"Subscription","Abonnement"}.
{"Sunday","Dimanche"}.
{"the password is","le mot de passe est"}.
{"This participant is kicked from the room because he sent an error message","Ce participant est expulsé du salon pour avoir envoyé un message erroné"}.
{"This participant is kicked from the room because he sent an error message to another participant","Ce participant est expulsé du salon pour avoir envoyé un message erroné à un autre participant"}.
{"This participant is kicked from the room because he sent an error presence","Ce participant est expulsé du salon pour avoir envoyé une présence erroné"}.
{"This room is not anonymous","Ce salon n'est pas anonyme"}.
{"Thursday","Jeudi"}.
{"Time delay","Délais"}.
{"Time","Heure"}.
{"To","A"}.
{"To ~s","A ~s"}.
{"Traffic rate limit is exceeded","La limite de trafic a été dépassée"}.
{"Transactions Aborted:","Transactions annulées:"}.
{"Transactions Commited:","Transactions commitées:"}.
{"Transactions Logged:","Transactions journalisées:"}.
{"Transactions Restarted:","Transactions redémarrées:"}.
{"Tuesday","Mardi"}.
{"Updated modules","Modules mis à jours"}.
{"Update message of the day (don't send)","Mise à jour du message du jour (pas d'envoi)"}.
{"Update message of the day on all hosts (don't send)","Mettre à jour le message du jour sur tous les domaines (ne pas envoyer)"}.
{"Update","Mettre à jour"}.
{"Update ","Mise à jour "}.
{"Update plan","Plan de mise à jour"}.
{"Update script","Script de mise à jour"}.
{"Uptime:","Temps depuis le démarrage:"}.
{"Use of STARTTLS required","L'utilisation de STARTTLS est impérative"}.
{"User Management","Gestion des utilisateurs"}.
{"Users are not allowed to register accounts so fast","Les utilisateurs ne sont pas autorisés à enregistrer des comptes si rapidement"}.
{"Users Last Activity","Dernière activité des utilisateurs"}.
{"Users","Utilisateurs"}.
{"User ","Utilisateur "}.
{"User","Utilisateur"}.
{"Validate","Valider"}.
{"vCard User Search","Recherche dans l'annnuaire"}.
{"Virtual Hosts","Serveurs virtuels"}.
{"Visitors are not allowed to change their nicknames in this room","Les visiteurs ne sont pas autorisés à changer de pseudo dans ce salon"}.
{"Visitors are not allowed to send messages to all occupants","Les visiteurs ne sont pas autorisés à envoyer des messages à tout les occupants"}.
{"Wednesday","Mercredi"}.
{"When to send the last published item","A quel moment envoyer le dernier élément publié"}.
{"Whether to allow subscriptions","Autoriser l'abonnement ?"}.
{"You have been banned from this room","Vous avez été exclus de ce salon"}.
{"You must fill in field \"Nickname\" in the form","Vous devez préciser le champ \"pseudo\" dans le formulaire"}.
{"You need an x:data capable client to configure mod_irc settings","Vous avez besoin d'un client supportant x:data pour configurer le module IRC"}.
{"You need an x:data capable client to configure room","Vous avez besoin d'un client supportant x:data pour configurer le salon"}.
{"You need an x:data capable client to register nickname","Vous avez besoin d'un client supportant x:data pour enregistrer un pseudo"}.
{"You need an x:data capable client to search","Vous avez besoin d'un client supportant x:data pour faire une recherche"}.
{"Your contact offline message queue is full. The message has been discarded.","La file d'attente de message de votre contact est pleine. Votre message a été détruit."}.
