% $Id: gl.msg 641 2007-09-26 10:48:05Z mremond $
% Language: Galician (galego)
% Author: Carlos E. Lopez - suso AT jabber-hispano.org

% jlib.hrl
{"No resource provided", "Non se proporcionou recurso"}.

% mod_configure.erl
{"Choose storage type of tables", "Selecciona tipo de almacenamento das táboas"}.
{"RAM copy", "Copia en RAM"}.
{"RAM and disc copy", "Copia en RAM e disco"}.
{"Disc only copy", "Copia en disco soamente"}.
{"Remote copy", "Copia remota"}.
{"Stop Modules at ", "Deter módulos en "}.
{"Choose modules to stop", "Selecciona módulos a deter"}.
{"Start Modules at ", "Iniciar módulos en "}.
{"Enter list of {Module, [Options]}", "Introduce lista de {módulo, [opcións]}"}.
{"List of modules to start", "Lista de módulos a iniciar"}.
{"Backup to File at ", "Gardar copia de seguridade en ficheiro en "}.
{"Enter path to backup file", "Introduce ruta ao ficheiro de copia de seguridade"}.
{"Path to File", "Ruta ao ficheiro"}.
{"Restore Backup from File at ", "Restaura copia de seguridade desde o ficheiro en "}.
{"Dump Backup to Text File at ", "Exporta copia de seguridade a ficheiro de texto en "}.
{"Enter path to text file", "Introduce ruta ao ficheiro de texto"}.
{"Import User from File at ", "Importa usuario desde ficheiro en "}.
{"Enter path to jabberd1.4 spool file", "Introduce ruta ao ficheiro jabberd1.4 spool"}.
{"Import Users from Dir at ", "Importar usuarios desde o directorio en "}.
{"Enter path to jabberd1.4 spool dir", "Introduce a ruta ao directorio de jabberd1.4 spools"}.
{"Path to Dir", "Ruta ao directorio"}.
{"Hostname Configuration", "Configuración do nome de máquina"}.
{"Choose host name", "Indica o nome da máquina"}.
{"Host name", "Nome da máquina"}.
{"Access Control List Configuration", "Configuración da Lista de Control de Acceso"}.
{"Access control lists", "Listas de Control de Acceso"}.
{"Access Configuration", "Configuración de accesos"}.
{"Access rules", "Regras de acceso"}.
{"Remove Users", "Eliminar usuarios"}.
{"Choose users to remove", "Selecciona usuarios a eliminar"}.
{"Administration of ", "Administración de "}.
{"Action on user", "Acción no usuario"}.
{"Edit Properties", "Editar propiedades"}.
{"Remove User", "Eliminar usuario"}.
{"Database", "Base de datos"}.
{"Outgoing s2s Connections", "Conexións S2S saíntes"}.
{"Import Users From jabberd 1.4 Spool Files", "Importar usuarios de ficheiros spool de jabberd-1.4"}.
{"Database Tables Configuration at ", "Configuración de táboas da base de datos en "}.

% mod_disco.erl
{"Configuration", "Configuración"}.
{"Online Users", "Usuarios conectados"}.
{"All Users", "Todos os usuarios"}.
{"To ~s", "A ~s"}.
{"From ~s", "De ~s"}.
{"Running Nodes", "Nodos funcionando"}.
{"Stopped Nodes", "Nodos detidos"}.
{"Host Name", "Nome da máquina"}.
{"Access Control Lists", "Listas de Control de Acceso"}.
{"Access Rules", "Regras de Acceso"}.
{"Remove Users", "Eliminar usuarios"}.
{"Modules", "Módulos"}.
{"Start Modules", "Iniciar módulos"}.
{"Stop Modules", "Detener módulos"}.
{"Backup", "Gardar copia de seguridade"}.
{"Restore", "Restaurar"}.
{"Dump to Text File", "Exportar a ficheiro de texto"}.
{"Import File", "Importar ficheiro"}.
{"Import Directory", "Importar directorio"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Escolle un nome de usuario e contraseña para rexistrarche neste servidor"}.

% mod_vcard.erl
{"Erlang Jabber Server\nCopyright (c) 2002-2007 Alexey Shchepin", "Servidor Jabber en Erlang\nCopyright (c) 2002-2007 Alexey Shchepin"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Enche o formulario para buscar usuarios Jabber. Engade * ao final dun campo para buscar subcadenas."}.
{"ejabberd vCard module\nCopyright (c) 2003-2007 Alexey Shchepin", "Módulo vCard para ejabberd\nCopyright (c) 2002-2007 Alexey Shchepin"}.
{"You need an x:data capable client to search", "Necesitas un cliente con soporte de x:data para poder buscar"}.
{"Search users in ", "Buscar usuarios en "}.

% mod_vcard_odbc.erl
{"Email", "Email"}.
{"Search Results for ", "Buscar resultados por "}.
{"Jabber ID", "Jabber ID"}.
{"User",              "Usuario"}.
{"Full Name", 	      "Nome completo"}.
{"Name", 	      "Nome"}.
{"Middle Name",       "Segundo nome"}.
{"Family Name",       "Apelido"}.
{"Nickname", 	      "Alcume"}.
{"Birthday", 	      "Aniversario"}.
{"Country", 	      "País"}.
{"City", 	      "Cidade"}.
{"Organization Name", "Nome da organización"}.
{"Organization Unit", "Unidade da organización"}.
{"vCard User Search", "Procura de usuario en vCard"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module\nCopyright (c) 2003-2007 Alexey Shchepin", "Módulo Pub/Sub para ejabberd\nCopyright (c) 2002-2007 Alexey Shchepin"}.
{"Node Creator", "Creador do nodo"}.
{"Deliver payloads with event notifications", "Enviar payloads xunto coas notificacións de eventos"}.
{"Notify subscribers when the node configuration changes", "Notificar subscriptores cando cambia a configuración do nodo"}.
{"Notify subscribers when the node is deleted", "Notificar subscriptores cando o nodo bórrase"}.
{"Notify subscribers when items are removed from the node", "Notificar subscriptores cando os elementos bórranse do nodo"}.
{"Persist items to storage", "Persistir elementos ao almacenar"}.
{"Max # of items to persist", "Máximo # de elementos que persisten"}.
{"Whether to allow subscriptions", "Permitir subscripciones"}.
{"Specify the subscriber model", "Especificar o modelo do subscriptor"}.
{"Specify the publisher model", "Especificar o modelo do publicante"}.
{"Max payload size in bytes", "Máximo tamaño do payload en bytes"}.
{"Send items to new subscribers", "Enviar elementos aos novos subscriptores"}.
{"Only deliver notifications to available users", "Só enviar notificacións aos usuarios dispoñibles"}.
{"Specify the current subscription approver", "Especificar o aprobador de subscripción actual"}.
{"Publish-Subscribe", "Subscripción-publica"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "Necesitas un cliente con soporte de x:data para poder rexistrar o alcume"}.
{"Nickname Registration at ", "Rexistro do alcume en "}.
{"Enter nickname you want to register", "Introduce o alcume que queiras rexistrar"}.
{"Only service administrators are allowed to send service messages", "Só os administradores do servizo teñen permiso para enviar mensaxes de servizo"}.
{"Conference room does not exist", "A sala de conferencias non existe"}.
{"Access denied by service policy", "Acceso denegado pola política do servizo"}.
{"You must fill in field \"Nickname\" in the form", "Debes encher o campo \"Alcumo\" no formulario"}.
{"Specified nickname is already registered", "O alcume especificado xa está rexistrado, terás que buscar outro"}.
{"Room creation is denied by service policy", "Denegar crear a sala por política do servizo"}.
{"ejabberd MUC module\nCopyright (c) 2003-2007 Alexey Shchepin", "Módulo de MUC para ejabbed\nCopyright (c) 2002-2007 Alexey Shchepin"}.
{"Chatrooms", "Salas de charla"}.

% mod_muc/mod_muc_room.erl
{" has set the subject to: ", " puxo o asunto: "}.
{"You need an x:data capable client to configure room", "Necesitas un cliente con soporte de x:data para configurar a sala"}.
{"Configuration for ", "Configuración para "}.
{"Room title", "Título da sala"}.
{"Allow users to change subject", "Permitir aos usuarios cambiar o asunto"}.
{"Allow users to query other users", "Permitir aos usuarios consultar a outros usuarios"}.
{"Allow users to send private messages", "Permitir aos usuarios enviar mensaxes privadas"}.
{"Make room public searchable", "Sala publicamente visible"}.
{"Make participants list public", "A lista de participantes é pública"}.
{"Make room persistent", "Sala permanente"}.
{"Make room moderated", "Sala moderada"}.
{"Default users as participants", "Os usuarios son participantes por defecto"}.
{"Make room members-only", "Sala só para membros"}.
{"Allow users to send invites", "Permitir aos usuarios enviar invitacións"}.
{"Make room password protected", "Protexer a sala con contraseña"}.
{"Password", "Contraseña"}.
{"This room is not anonymous", "Sala non anónima"}.
{"Enable logging", "Gardar históricos"}.
{"Only moderators and participants are allowed to change subject in this room", "Só os moderadores e participantes poden cambiar o asunto desta sala"}.
{"Only moderators are allowed to change subject in this room", "Só os moderadores poden cambiar o asunto desta sala"}.
{"Visitors are not allowed to send messages to all occupants", "Os visitantes non poden enviar mensaxes a todos os ocupantes"}.
{"Only occupants are allowed to send messages to the conference", "Só os ocupantes poden enviar mensaxes á sala"}.
{"It is not allowed to send private messages to the conference", "Impedir o envio de mensaxes privadas á sala"}.
{"Improper message type", "Tipo de mensaxe incorrecta"}.
{"Nickname is already in use by another occupant", "O alcume xa está sendo usado por outro ocupante"}.
{"Nickname is registered by another person", "O alcume xa está rexistrado por outra persoa"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Non está permitido enviar mensaxes privadas do tipo \"groupchat\""}.
{"Recipient is not in the conference room", "O receptor non está na sala de conferencia"}.
{"Only occupants are allowed to send queries to the conference", "Só os ocupantes poden enviar solicitudes á sala"}.
{"Queries to the conference members are not allowed in this room", "Nesta sala non se permiten solicitudes aos membros da sala"}.
{"You have been banned from this room", "fuches bloqueado nesta sala"}.
{"Membership required to enter this room", "Necesitas ser membro desta sala para poder entrar"}.
{"Password required to enter this room", "Necesítase contraseña para entrar nesta sala"}.
{"Incorrect password", "Contraseña incorrecta"}.
{"Administrator privileges required", "Necesítase privilexios de administrador"}.
{"Moderator privileges required", "Necesítase privilexios de moderador"}.
{"JID ~s is invalid", "O JID ~s non é válido"}.
{"Nickname ~s does not exist in the room", "O alcume ~s non existe na sala"}.
{"Invalid affiliation: ~s", "Afiliación non válida: ~s"}.
{"Invalid role: ~s", "Rol non válido: ~s"}.
{"Owner privileges required", "Requírense privilexios de propietario da sala"}.
{"private, ", "privado"}.
{"Description", "Descripción"}.
{"Number of occupants", "Número de ocupantes"}.
{"Present real JIDs to", "Os JID reais poden velos"}.
{"moderators only", "só moderadores"}.
{"anyone", "calquera"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Configuración de la sala modificada"}.
{"joins the room", "entra en la sala"}.
{"leaves the room", "sale de la sala"}.
{"has been kicked", "ha sido expulsado"}.
{"has been banned", "ha sido bloqueado"}.
{"is now known as", "cámbiase o nome a"}.
{"Monday", "Luns"}.
{"Tuesday", "Martes"}.
{"Wednesday", "Mércores"}.
{"Thursday", "Xoves"}.
{"Friday", "Venres"}.
{"Saturday", "Sábado"}.
{"Sunday", "Domingo"}.
{"January", "Xaneiro"}.
{"February", "Febreiro"}.
{"March", "Marzo"}.
{"April", "Abril"}.
{"May", "Maio"}.
{"June", "Xuño"}.
{"July", "Xullo"}.
{"August", "Agosto"}.
{"September", "Setembro"}.
{"October", "Outubro"}.
{"November", "Novembro"}.
{"December", "Decembro"}.
{"Room Configuration", "Configuración da sala"}.

% mod_irc/mod_irc.erl
{"You need an x:data capable client to configure mod_irc settings", "Necesitas un cliente con soporte de x:data para configurar as opcións de mod_irc"}.
{"Registration in mod_irc for ", "Rexistro en mod_irc para"}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Introduce o nome de usuario e codificaciones de carácteres que queiras usar ao conectar nos servidores de IRC"}.
{"IRC Username", "Nome de usuario en IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Se queres especificar codificaciones de carácteres distintos para cada servidor IRC rechea esta lista con valores no formato '{\"servidor irc\", \"codificación\"}'. Este servizo usa por defecto a codificación \"~s\"."}.
{"Encodings", "Codificaciones"}.
{"ejabberd IRC module\nCopyright (c) 2003-2007 Alexey Shchepin", "Módulo de IRC para ejabberd\nCopyright (c) 2002-2007 Alexey Shchepin"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Ejemplo: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"IRC Transport", "Transporte IRC"}.

% web/ejabberd_web_admin.erl
{"Users", "Usuarios"}.
{"Nodes", "Nodos"}.
{"Statistics", "Estatísticas"}.
{"Delete Selected", "Eliminar os seleccionados"}.
{"Submit", "Enviar"}.
{"~s access rule configuration", "Configuración das Regra de Acceso ~s"}.
{"Node not found", "Nodo non atopado"}.
{"Add New", "Engadir novo"}.
{"Change Password", "Cambiar contraseña"}.
{"Connected Resources:", "Recursos conectados:"}.
{"Password:", "Contraseña:"}.
{"None", "Ningún"}.
{"Node ", "Nodo "}.
{"Restart", "Reiniciar"}.
{"Stop", "Deter"}.
{"Name", "Nome"}.
{"Storage Type", "Tipo de almacenamiento"}.
{"Size", "Tamaño"}.
{"Memory", "Memoria"}.
{"Backup Management", "Xestión de copia de seguridade"}.
{"OK", "Aceptar"}.
{"Listened Ports at ", "Portos de escoita en "}.
{"Port", "Porto"}.
{"Module", "Módulo"}.
{"Options", "Opcións"}.
{"Update", "Actualizar"}.
{"Delete", "Eliminar"}.
{"Add User", "Engadir usuario"}.
{"Last Activity", "Última actividade"}.
{"Never", "Nunca"}.
{"Time", "Data"}.
{"From", "De"}.
{"To", "Para"}.
{"Packet", "Paquete"}.
{"Roster", "Lista de contactos"}.
{"Nickname", "Alcume"}.
{"Subscription", "Subscripción"}.
{"Pending", "Pendente"}.
{"Groups", "Grupos"}.
{"Remove", "Borrar"}.
{"User ", "Usuario "}.
{"Roster of ", "Lista de contactos de "}.
{"ejabberd (c) 2002-2007 Alexey Shchepin, 2004-2007 Process One", "ejabberd (c) 2002-2007 Alexey Shchepin, 2004-2007 Process One"}.
{"Shared Roster", "Grupos Compartidos"}.
{"Online", "Conectado"}.
{"Validate", "Validar"}.
{"Name:", "Nome:"}.
{"Description:", "Descrición:"}.
{"Members:", "Membros:"}.
{"Displayed Groups:", "Mostrar grupos:"}.
{"Group ", "Grupo "}.
{"Period: ", "Periodo: "}.
{"Last month", "Último mes"}.
{"Last year", "Último ano"}.
{"All activity", "Toda a actividade"}.
{"Show Ordinary Table", "Mostrar Táboa Ordinaria"}.
{"Show Integral Table", "Mostrar Táboa Integral"}.
{"Modules at ", "Módulos en "}.
{"Start", "Iniciar"}.
{"Virtual Hosts", "Hosts Virtuais"}.
{"ejabberd virtual hosts", "Hosts virtuais de ejabberd"}.
{"Host", "Host"}.
{"ejabberd Web Interface", "Interfaz Web de ejabberd"}.
{"Restore plain text backup immediately:", "Restaurar copias de seguridade de texto plano inmediatamente:"}.
{"Statistics of ~p", "Estatísticas de ~p"}.
{"Uptime:", "Tempo desde o inicio:"}.
{"CPU Time:", "Tempo consumido de CPU:"}.
{"Transactions Commited:", "Transaccións finalizadas:"}.
{"Transactions Aborted:", "Transaccións abortadas:"}.
{"Transactions Restarted:", "Transaccións reiniciadas:"}.
{"Transactions Logged:", "Transaccións rexistradas:"}.
{"Update ", "Actualizar"}.
{"Update plan", "Plan de actualización"}.
{"Updated modules", "Módulos actualizados"}.
{"Update script", "Script de actualización"}.
{"Low level update script", "Script de actualización a baixo nivel"}.
{"Script check", "Comprobación de script"}.
{"Not Found", "Non atopado"}.
{"Shared Roster Groups", "Grupos Compartidos"}.
{"Administration", "Administración"}.
{"(Raw)", "(Cru)"}.
{"Submitted", "Enviado"}.
{"Bad format", "Mal formato"}.
{"Raw", "Cru"}.
{"Users Last Activity", "Última actividade dos usuarios"}.
{"Registered Users", "Usuarios rexistrados"}.
{"Offline Messages", "Mensaxes diferidas"}.
{"Registered Users:", "Usuarios rexistrados:"}.
{"Authenticated Users:", "Usuarios autenticados:"}.
{"Online Users:", "Usuarios conectados:"}.
{"Outgoing s2s Connections:", "Conexións S2S saíntes:"}.
{"Outgoing s2s Servers:", "Servidores S2S saíntes:"}.
{"Offline Messages:", "Mensaxes diferidas:"}.
{"~s's Offline Messages Queue", "Cola de mensaxes diferidas de ~s"}.
{"Add Jabber ID", "Engadir ID Jabber"}.
{"No Data", "Sen datos"}.
{"Listened Ports", "Portos de escoita"}.
{"RPC Call Error", "Erro na chamada RPC"}.
{"Database Tables at ", "Táboas da base de datos en "}.
{"Backup of ", "Copia de seguridade de "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Ten en conta que estas opcións só farán copia de seguridade da base de datos Mnesia embebida. Se estás usando ODBC terás que facer tamén copia de seguridade da túa base de datos SQL."}.
{"Store binary backup:", "Gardar copia de seguridade binaria:"}.
{"Restore binary backup immediately:", "Restaurar inmediatamente copia de seguridade binaria:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Restaurar copia de seguridade binaria no seguinte reinicio de ejabberd (require menos memoria que se instantánea):"}.
{"Store plain text backup:", "Gardar copia de seguridade en texto plano:"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "É obrigatorio usar STARTTLS"}.
{"Replaced by new connection", "Substituído por unha nova conexión"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Rechea campos para buscar usuarios Jabber que concuerden"}.

% mod_adhoc.erl
{"Commands", "Comandos"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Really delete message of the day?", "Está seguro de quere borrar a mensaxe do dia?"}.
{"Subject", "Asunto"}.
{"Message body", "Corpo da mensaxe"}.
{"No body provided for announce message", "Non se proporcionou corpo de mensaxe para o anuncio"}.
{"Announcements", "Anuncios"}.
{"Send announcement to all users", "Enviar anuncio a todos os usuarios"}.
{"Send announcement to all online users", "Enviar anuncio a todos los usuarios conectados"}.
{"Send announcement to all online users on all hosts", "Enviar anuncio a todos os usuarios conectados en todos os dominios"}.
{"Set message of the day and send to online users", "Pór mensaxe do dia e enviar a todos os usuarios conectados"}.
{"Update message of the day (don't send)", "Actualizar mensaxe do dia, pero non envialo"}.
{"Delete message of the day", "Borrar mensaxe do dia"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module\nCopyright (c) 2003-2007 Alexey Shchepin", "ejabberd SOCKS5 Bytestreams module\nCopyright (c) 2003-2007 Alexey Shchepin"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
