{"Access Configuration","Configuración de accesos"}.
{"Access Control List Configuration","Configuración da Lista de Control de Acceso"}.
{"Access control lists","Listas de Control de Acceso"}.
{"Access Control Lists","Listas de Control de Acceso"}.
{"Access denied by service policy","Acceso denegado pola política do servizo"}.
{"Access rules","Regras de acceso"}.
{"Access Rules","Regras de Acceso"}.
{"Action on user","Acción no usuario"}.
{"Add Jabber ID","Engadir ID Jabber"}.
{"Add New","Engadir novo"}.
{"Add User","Engadir usuario"}.
{"Administration","Administración"}.
{"Administration of ","Administración de "}.
{"Administrator privileges required","Necesítase privilexios de administrador"}.
{"All activity","Toda a actividade"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Desexas permitir a este JabberID que se subscriba a este nodo PubSub?"}.
{"Allow users to change subject","Permitir aos usuarios cambiar o asunto"}.
{"Allow users to query other users","Permitir aos usuarios consultar a outros usuarios"}.
{"Allow users to send invites","Permitir aos usuarios enviar invitacións"}.
{"Allow users to send private messages","Permitir aos usuarios enviar mensaxes privadas"}.
{"All Users","Todos os usuarios"}.
{"Announcements","Anuncios"}.
{"anyone","calquera"}.
{"April","Abril"}.
{"August","Agosto"}.
{"Backup","Gardar copia de seguridade"}.
{"Backup Management","Xestión de copia de seguridade"}.
{"Backup of ","Copia de seguridade de "}.
{"Backup to File at ","Gardar copia de seguridade en ficheiro en "}.
{"Bad format","Mal formato"}.
{"Birthday","Aniversario"}.
{"Change Password","Cambiar contraseña"}.
{"Change User Password","Cambiar contraseña de usuario"}.
{"Chatroom configuration modified","Configuración de la sala modificada"}.
{"Chatrooms","Salas de charla"}.
{"Choose a username and password to register with this server","Escolle un nome de usuario e contraseña para rexistrarche neste servidor"}.
{"Choose modules to stop","Selecciona módulos a deter"}.
{"Choose storage type of tables","Selecciona tipo de almacenamento das táboas"}.
{"Choose whether to approve this entity's subscription.","Decidir se aprobar a subscripción desta entidade."}.
{"City","Cidade"}.
{"Commands","Comandos"}.
{"Conference room does not exist","A sala de conferencias non existe"}.
{"Configuration","Configuración"}.
{"Configuration for ","Configuración para "}.
{"Connected Resources:","Recursos conectados:"}.
{"Country","País"}.
{"CPU Time:","Tempo consumido de CPU:"}.
{"Database","Base de datos"}.
{"Database Tables at ","Táboas da base de datos en "}.
{"Database Tables Configuration at ","Configuración de táboas da base de datos en "}.
{"December","Decembro"}.
{"Default users as participants","Os usuarios son participantes por defecto"}.
{"Delete","Eliminar"}.
{"Delete message of the day","Borrar mensaxe do dia"}.
{"Delete message of the day on all hosts","Borrar a mensaxe do día en todos os dominios"}.
{"Delete Selected","Eliminar os seleccionados"}.
{"Delete User","Borrar usuario"}.
{"Deliver event notifications","Entregar notificacións de eventos"}.
{"Deliver payloads with event notifications","Enviar payloads xunto coas notificacións de eventos"}.
{"Description:","Descrición:"}.
{"Disc only copy","Copia en disco soamente"}.
{"Displayed Groups:","Mostrar grupos:"}.
{"Dump Backup to Text File at ","Exporta copia de seguridade a ficheiro de texto en "}.
{"Dump to Text File","Exportar a ficheiro de texto"}.
{"Edit Properties","Editar propiedades"}.
{"ejabberd IRC module","Módulo de IRC para ejabberd"}.
{"ejabberd MUC module","Módulo de MUC para ejabberd"}.
{"ejabberd Publish-Subscribe module","Módulo de Publicar-Subscribir de ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams module"}.
{"ejabberd vCard module","Módulo vCard para ejabberd"}.
{"ejabberd virtual hosts","Hosts virtuais de ejabberd"}.
{"ejabberd Web Admin","Ejabberd Administrador Web"}.
{"Email","Email"}.
{"Enable logging","Gardar históricos"}.
{"Encodings","Codificaciones"}.
{"End User Session","Pechar sesión de usuario"}.
{"Enter list of {Module, [Options]}","Introduce lista de {módulo, [opcións]}"}.
{"Enter nickname you want to register","Introduce o alcume que queiras rexistrar"}.
{"Enter path to backup file","Introduce ruta ao ficheiro de copia de seguridade"}.
{"Enter path to jabberd14 spool dir","Introduce a ruta ao directorio de jabberd14 spools"}.
{"Enter path to jabberd14 spool file","Introduce ruta ao ficheiro jabberd14 spool"}.
{"Enter path to text file","Introduce ruta ao ficheiro de texto"}.
{"Enter username and encodings you wish to use for connecting to IRC servers","Introduce o nome de usuario e codificaciones de carácteres que queiras usar ao conectar nos servidores de IRC"}.
{"Erlang Jabber Server","Servidor Jabber en Erlang"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].","Ejemplo: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Family Name","Apelido"}.
{"February","Febreiro"}.
{"Fill in fields to search for any matching Jabber User","Rechea campos para buscar usuarios Jabber que concuerden"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Enche o formulario para buscar usuarios Jabber. Engade * ao final dun campo para buscar subcadenas."}.
{"Friday","Venres"}.
{"From","De"}.
{"From ~s","De ~s"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Ver número de usuarios conectados"}.
{"Get Number of Registered Users","Ver número de usuarios rexistrados"}.
{"Get User Last Login Time","Ver data da última conexión de usuario"}.
{"Get User Password","Ver contraseña de usuario"}.
{"Get User Statistics","Ver estatísticas de usuario"}.
{"Group ","Grupo "}.
{"Groups","Grupos"}.
{"has been banned","ha sido bloqueado"}.
{"has been kicked because of an affiliation change","foi expulsado debido a un cambio de afiliación"}.
{"has been kicked because of a system shutdown","foi expulsado por mor dun sistema de peche"}.
{"has been kicked because the room has been changed to members-only","foi expulsado, porque a sala cambiouse a só-membros"}.
{"has been kicked","ha sido expulsado"}.
{" has set the subject to: "," puxo o asunto: "}.
{"Host","Host"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","Se queres especificar codificaciones de carácteres distintos para cada servidor IRC rechea esta lista con valores no formato '{\"servidor irc\", \"codificación\"}'. Este servizo usa por defecto a codificación \"~s\"."}.
{"Import Directory","Importar directorio"}.
{"Import File","Importar ficheiro"}.
{"Import User from File at ","Importa usuario desde ficheiro en "}.
{"Import Users from Dir at ","Importar usuarios desde o directorio en "}.
{"Import Users From jabberd14 Spool Files","Importar usuarios de ficheiros spool de jabberd-1.4"}.
{"Improper message type","Tipo de mensaxe incorrecta"}.
{"Incorrect password","Contraseña incorrecta"}.
{"Invalid affiliation: ~s","Afiliación non válida: ~s"}.
{"Invalid role: ~s","Rol non válido: ~s"}.
{"IP addresses","Direccións IP"}.
{"IRC Transport","Transporte IRC"}.
{"IRC Username","Nome de usuario en IRC"}.
{"is now known as","cámbiase o nome a"}.
{"It is not allowed to send private messages of type \"groupchat\"","Non está permitido enviar mensaxes privadas do tipo \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Impedir o envio de mensaxes privadas á sala"}.
{"Jabber ID","Jabber ID"}.
{"January","Xaneiro"}.
{"Jabber ID ~s is invalid","O JID ~s non é válido"}.
{"joins the room","entra en la sala"}.
{"July","Xullo"}.
{"June","Xuño"}.
{"Last Activity","Última actividade"}.
{"Last login","Última conexión"}.
{"Last month","Último mes"}.
{"Last year","Último ano"}.
{"leaves the room","sale de la sala"}.
{"Listened Ports at ","Portos de escoita en "}.
{"Listened Ports","Portos de escoita"}.
{"List of modules to start","Lista de módulos a iniciar"}.
{"Low level update script","Script de actualización a baixo nivel"}.
{"Make participants list public","A lista de participantes é pública"}.
{"Make room members-only","Sala só para membros"}.
{"Make room moderated","Facer Sala moderada"}.
{"Make room password protected","Protexer a sala con contraseña"}.
{"Make room persistent","Sala permanente"}.
{"Make room public searchable","Sala publicamente visible"}.
{"March","Marzo"}.
{"Maximum Number of Occupants","Número máximo de ocupantes"}.
{"Max # of items to persist","Máximo # de elementos que persisten"}.
{"Max payload size in bytes","Máximo tamaño do payload en bytes"}.
{"May","Maio"}.
{"Membership required to enter this room","Necesitas ser membro desta sala para poder entrar"}.
{"Members:","Membros:"}.
{"Memory","Memoria"}.
{"Message body","Corpo da mensaxe"}.
{"Middle Name","Segundo nome"}.
{"Moderator privileges required","Necesítase privilexios de moderador"}.
{"moderators only","só moderadores"}.
{"Module","Módulo"}.
{"Modules at ","Módulos en "}.
{"Modules","Módulos"}.
{"Monday","Luns"}.
{"Name:","Nome:"}.
{"Name","Nome"}.
{"Never","Nunca"}.
{"Nickname","Alcume"}.
{"Nickname is already in use by another occupant","O alcume xa está sendo usado por outro ocupante"}.
{"Nickname is registered by another person","O alcume xa está rexistrado por outra persoa"}.
{"Nickname Registration at ","Rexistro do alcume en "}.
{"Nickname ~s does not exist in the room","O alcume ~s non existe na sala"}.
{"No body provided for announce message","Non se proporcionou corpo de mensaxe para o anuncio"}.
{"No Data","Sen datos"}.
{"Node ID","Nodo IDE"}.
{"Node ","Nodo "}.
{"Node not found","Nodo non atopado"}.
{"Nodes","Nodos"}.
{"No limit","Sen límite"}.
{"None","Ningún"}.
{"No resource provided","Non se proporcionou recurso"}.
{"Notify subscribers when items are removed from the node","Notificar subscriptores cando os elementos bórranse do nodo"}.
{"Notify subscribers when the node configuration changes","Notificar subscriptores cando cambia a configuración do nodo"}.
{"Notify subscribers when the node is deleted","Notificar subscriptores cando o nodo bórrase"}.
{"November","Novembro"}.
{"Number of occupants","Número de ocupantes"}.
{"Number of online users","Número de usuarios conectados"}.
{"Number of registered users","Número de usuarios rexistrados"}.
{"October","Outubro"}.
{"Offline Messages:","Mensaxes diferidas:"}.
{"Offline Messages","Mensaxes diferidas"}.
{"OK","Aceptar"}.
{"Online","Conectado"}.
{"Online Users:","Usuarios conectados:"}.
{"Online Users","Usuarios conectados"}.
{"Only deliver notifications to available users","Só enviar notificacións aos usuarios dispoñibles"}.
{"Only moderators and participants are allowed to change subject in this room","Só os moderadores e participantes poden cambiar o asunto desta sala"}.
{"Only moderators are allowed to change subject in this room","Só os moderadores poden cambiar o asunto desta sala"}.
{"Only occupants are allowed to send messages to the conference","Só os ocupantes poden enviar mensaxes á sala"}.
{"Only occupants are allowed to send queries to the conference","Só os ocupantes poden enviar solicitudes á sala"}.
{"Only service administrators are allowed to send service messages","Só os administradores do servizo teñen permiso para enviar mensaxes de servizo"}.
{"Options","Opcións"}.
{"Organization Name","Nome da organización"}.
{"Organization Unit","Unidade da organización"}.
{"Outgoing s2s Connections:","Conexións S2S saíntes:"}.
{"Outgoing s2s Connections","Conexións S2S saíntes"}.
{"Outgoing s2s Servers:","Servidores S2S saíntes:"}.
{"Owner privileges required","Requírense privilexios de propietario da sala"}.
{"Packet","Paquete"}.
{"Password:","Contraseña:"}.
{"Password","Contraseña"}.
{"Password required to enter this room","Necesítase contraseña para entrar nesta sala"}.
{"Password Verification","Verificación da contraseña"}.
{"Path to Dir","Ruta ao directorio"}.
{"Path to File","Ruta ao ficheiro"}.
{"Pending","Pendente"}.
{"Period: ","Periodo: "}.
{"Persist items to storage","Persistir elementos ao almacenar"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","Porto"}.
{"Present real Jabber IDs to","Os JID reais poden velos"}.
{"private, ","privado"}.
{"Publish-Subscribe","Publicar-Subscribir"}.
{"PubSub subscriber request","Petición de subscriptor de PubSub"}.
{"Queries to the conference members are not allowed in this room","Nesta sala non se permiten solicitudes aos membros da sala"}.
{"RAM and disc copy","Copia en RAM e disco"}.
{"RAM copy","Copia en RAM"}.
{"(Raw)","(Cru)"}.
{"Raw","Cru"}.
{"Really delete message of the day?","Está seguro de quere borrar a mensaxe do dia?"}.
{"Recipient is not in the conference room","O receptor non está na sala de conferencia"}.
{"Registered Users:","Usuarios rexistrados:"}.
{"Registered Users","Usuarios rexistrados"}.
{"Registration in mod_irc for ","Rexistro en mod_irc para"}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Ten en conta que estas opcións só farán copia de seguridade da base de datos Mnesia embebida. Se estás usando ODBC terás que facer tamén copia de seguridade da túa base de datos SQL."}.
{"Remote copy","Copia remota"}.
{"Remove","Borrar"}.
{"Remove User","Eliminar usuario"}.
{"Replaced by new connection","Substituído por unha nova conexión"}.
{"Resources","Recursos"}.
{"Restart","Reiniciar"}.
{"Restart Service","Reiniciar o servizo"}.
{"Restore Backup from File at ","Restaura copia de seguridade desde o ficheiro en "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Restaurar copia de seguridade binaria no seguinte reinicio de ejabberd (require menos memoria que se instantánea):"}.
{"Restore binary backup immediately:","Restaurar inmediatamente copia de seguridade binaria:"}.
{"Restore plain text backup immediately:","Restaurar copias de seguridade de texto plano inmediatamente:"}.
{"Restore","Restaurar"}.
{"Room Configuration","Configuración da Sala"}.
{"Room creation is denied by service policy","Denegar crear a sala por política do servizo"}.
{"Room title","Título da sala"}.
{"Roster groups allowed to subscribe","Lista de grupos autorizados a subscribir"}.
{"Roster","Lista de contactos"}.
{"Roster of ","Lista de contactos de "}.
{"Roster size","Tamaño da lista de contactos"}.
{"RPC Call Error","Erro na chamada RPC"}.
{"Running Nodes","Nodos funcionando"}.
{"~s access rule configuration","Configuración das Regra de Acceso ~s"}.
{"Saturday","Sábado"}.
{"Script check","Comprobación de script"}.
{"Search Results for ","Buscar resultados por "}.
{"Search users in ","Buscar usuarios en "}.
{"Send announcement to all online users","Enviar anuncio a todos los usuarios conectados"}.
{"Send announcement to all online users on all hosts","Enviar anuncio a todos os usuarios conectados en todos os dominios"}.
{"Send announcement to all users","Enviar anuncio a todos os usuarios"}.
{"Send announcement to all users on all hosts","Enviar anuncio a todos os usuarios en todos os dominios"}.
{"September","Setembro"}.
{"Set message of the day and send to online users","Pór mensaxe do dia e enviar a todos os usuarios conectados"}.
{"Set message of the day on all hosts and send to online users","Pór mensaxe do día en todos os dominios e enviar aos usuarios conectados"}.
{"Shared Roster Groups","Grupos Compartidos"}.
{"Show Integral Table","Mostrar Táboa Integral"}.
{"Show Ordinary Table","Mostrar Táboa Ordinaria"}.
{"Shut Down Service","Deter o servizo"}.
{"~s invites you to the room ~s","~s invítache á sala ~s"}.
{"Size","Tamaño"}.
{"Specified nickname is already registered","O alcume especificado xa está rexistrado, terás que buscar outro"}.
{"Specify the access model","Especifica o modelo de acceso"}.
{"Specify the publisher model","Especificar o modelo do publicante"}.
{"~s's Offline Messages Queue","Cola de mensaxes diferidas de ~s"}.
{"Start","Iniciar"}.
{"Start Modules at ","Iniciar módulos en "}.
{"Start Modules","Iniciar módulos"}.
{"Statistics","Estatísticas"}.
{"Statistics of ~p","Estatísticas de ~p"}.
{"Stop","Deter"}.
{"Stop Modules at ","Deter módulos en "}.
{"Stop Modules","Detener módulos"}.
{"Stopped Nodes","Nodos detidos"}.
{"Storage Type","Tipo de almacenamiento"}.
{"Store binary backup:","Gardar copia de seguridade binaria:"}.
{"Store plain text backup:","Gardar copia de seguridade en texto plano:"}.
{"Subject","Asunto"}.
{"Submit","Enviar"}.
{"Submitted","Enviado"}.
{"Subscriber Address","Dirección do subscriptor"}.
{"Subscription","Subscripción"}.
{"Sunday","Domingo"}.
{"the password is","a contraseña é"}.
{"This participant is kicked from the room because he sent an error message","Este participante é expulsado da sala, xa que enviou unha mensaxe de erro"}.
{"This participant is kicked from the room because he sent an error message to another participant","Este participante é expulsado da sala, porque el enviou unha mensaxe de erro a outro participante"}.
{"This participant is kicked from the room because he sent an error presence","Este participante é expulsado da sala, porque el enviou un erro de presenza"}.
{"This room is not anonymous","Sala non anónima"}.
{"Thursday","Xoves"}.
{"Time","Data"}.
{"Time delay","Atraso temporal"}.
{"To","Para"}.
{"To ~s","A ~s"}.
{"Traffic rate limit is exceeded","Hase exedido o límite de tráfico"}.
{"Transactions Aborted:","Transaccións abortadas:"}.
{"Transactions Committed:","Transaccións finalizadas:"}.
{"Transactions Logged:","Transaccións rexistradas:"}.
{"Transactions Restarted:","Transaccións reiniciadas:"}.
{"Tuesday","Martes"}.
{"Update ","Actualizar"}.
{"Update","Actualizar"}.
{"Updated modules","Módulos actualizados"}.
{"Update message of the day (don't send)","Actualizar mensaxe do dia, pero non envialo"}.
{"Update message of the day on all hosts (don't send)","Actualizar a mensaxe do día en todos os dominos (pero non envialo)"}.
{"Update plan","Plan de actualización"}.
{"Update script","Script de actualización"}.
{"Uptime:","Tempo desde o inicio:"}.
{"Use of STARTTLS required","É obrigatorio usar STARTTLS"}.
{"User Management","Administración de usuarios"}.
{"Users Last Activity","Última actividade dos usuarios"}.
{"Users","Usuarios"}.
{"User ","Usuario "}.
{"User","Usuario"}.
{"Validate","Validar"}.
{"vCard User Search","Procura de usuario en vCard"}.
{"Virtual Hosts","Hosts Virtuais"}.
{"Visitors are not allowed to send messages to all occupants","Os visitantes non poden enviar mensaxes a todos os ocupantes"}.
{"Wednesday","Mércores"}.
{"When to send the last published item","Cando enviar o último elemento publicado"}.
{"Whether to allow subscriptions","Permitir subscripciones"}.
{"You have been banned from this room","fuches bloqueado nesta sala"}.
{"You must fill in field \"Nickname\" in the form","Debes encher o campo \"Alcumo\" no formulario"}.
{"You need an x:data capable client to configure mod_irc settings","Necesitas un cliente con soporte de x:data para configurar as opcións de mod_irc"}.
{"You need an x:data capable client to configure room","Necesitas un cliente con soporte de x:data para configurar a sala"}.
{"You need an x:data capable client to register nickname","Necesitas un cliente con soporte de x:data para poder rexistrar o alcume"}.
{"You need an x:data capable client to search","Necesitas un cliente con soporte de x:data para poder buscar"}.
{"Your contact offline message queue is full. The message has been discarded.","A túa cola de mensaxes diferidas de contactos está chea. A mensaxe descartouse."}.
