% $Id$
% Language: Italian (italiano)
% Author: Smart2128
% Author: Luca Brivio

% jlib.hrl
{"No resource provided", "Nessuna risorsa fornita"}.

% mod_configure.erl
{"Restart Service", "Riavviare il servizio"}.
{"Shut Down Service", "Terminare il servizio"}.
{"Delete User", "Eliminare l'utente"}.
{"End User Session", "Terminare la sessione dell'utente"}.
{"Get User Password", "Ottenere la password dell'utente"}.
{"Change User Password", "Cambiare la password dell'utente"}.
{"Get User Last Login Time", "Ottenere la data di ultimo accesso dell'utente"}.
{"Get User Statistics", "Ottenere le statistiche dell'utente"}.
{"Get Number of Registered Users", "Ottenere il numero di utenti registrati"}.
{"Get Number of Online Users", "Ottenere il numero di utenti online"}.
{"User Management", "Gestione degli utenti"}.
{"Time delay", "Ritardo"}.
{"Password Verification", "Verifica della password"}.
{"Number of registered users", "Numero di utenti registrati"}.
{"Number of online users", "Numero di utenti online"}.
{"Last login", "Ultimo accesso"}.
{"Roster size", "Dimensione della lista dei contatti"}.
{"IP addresses", "Indirizzi IP"}.
{"Resources", "Risorse"}.
{"Choose storage type of tables", "Selezionare una modalità di conservazione delle tabelle"}.
{"RAM copy", "Copia in memoria (RAM)"}.
{"RAM and disc copy", "Copia in memoria (RAM) e su disco"}.
{"Disc only copy", "Copia su disco soltanto"}.
{"Remote copy", "Copia remota"}.
{"Stop Modules at ", "Arrestare moduli su "}.
{"Choose modules to stop", "Selezionare i moduli da arrestare"}.
{"Start Modules at ", "Avviare moduli su "}.
{"Enter list of {Module, [Options]}", "Immettere un elenco di {Modulo, [Opzioni]}"}.
{"List of modules to start", "Elenco dei moduli da avviare"}.
{"Backup to File at ", "Salvataggio sul file "}.
{"Enter path to backup file", "Immettere il percorso del file di salvataggio"}.
{"Path to File", "Percorso del file"}.
{"Restore Backup from File at ", "Recuperare il salvataggio dal file "}.
{"Dump Backup to Text File at ", "Trascrivere il salvataggio sul file di testo "}.
{"Enter path to text file", "Immettere il percorso del file di testo"}.
{"Import User from File at ", "Importare un utente dal file "}.
{"Enter path to jabberd1.4 spool file", "Immettere il percorso del file di spool di jabberd1.4"}.
{"Import Users from Dir at ", "Importare utenti dalla directory "}.
{"Enter path to jabberd1.4 spool dir", "Immettere il percorso della directory di spool di jabberd1.4"}.
{"Path to Dir", "Percorso della directory"}.
{"Access Control List Configuration", "Configurazione dei diritti di accesso (ACL)"}.
{"Access control lists", "Diritti di accesso (ACL)"}.
{"Access Configuration", "Configurazione dell'accesso"}.
{"Access rules", "Regole di accesso"}.
{"Administration of ", "Amministrazione di "}.
{"Action on user", "Azione sull'utente"}.
{"Edit Properties", "Modificare le proprietà"}.
{"Remove User", "Eliminare l'utente"}.
{"Database", "Database"}.
{"Outgoing s2s Connections", "Connessioni s2s in uscita"}.
{"Import Users From jabberd 1.4 Spool Files", "Importare utenti da file di spool di jabberd 1.4"}.
{"Database Tables Configuration at ", "Configurazione delle tabelle del database su "}.

% src/ejabberd_c2s.erl
{"Use of STARTTLS required", "Utilizzo di STARTTLS obbligatorio"}.
{"Replaced by new connection", "Sostituito da una nuova connessione"}.

% mod_disco.erl
{"Configuration", "Configurazione"}.
{"Online Users", "Utenti online"}.
{"All Users", "Tutti gli utenti"}.
{"To ~s", "A ~s"}.
{"From ~s", "Da ~s"}.
{"Running Nodes", "Nodi attivi"}.
{"Stopped Nodes", "Nodi arrestati"}.
{"Access Control Lists", "Diritti di accesso (ACL)"}.
{"Access Rules", "Regole di accesso"}.
{"Modules", "Moduli"}.
{"Start Modules", "Avviare moduli"}.
{"Stop Modules", "Arrestare moduli"}.
{"Backup Management", "Gestione dei salvataggi"}.
{"Backup", "Salvare"}.
{"Restore", "Recuperare"}.
{"Dump to Text File", "Trascrivere su file di testo"}.
{"Import File", "Importare un file"}.
{"Import Directory", "Importare una directory"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Scegliere un nome utente e una password per la registrazione con questo server"}.

% src/mod_vcard_ldap.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"ejabberd vCard module", "Modulo vCard per ejabberd"}.
{"Email", "E-mail"}.
{"Search Results for ", "Risultati della ricerca per "}.
{"Jabber ID", "Jabber ID (JID)"}.

% mod_vcard.erl
{"You need an x:data capable client to search", "Per effettuare ricerche è necessario un client che supporti x:data"}.
{"Search users in ", "Cercare utenti in "}.
{"Fill in fields to search for any matching Jabber User", "Riempire i campi per la ricerca di utenti Jabber corrispondenti ai criteri"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Riempire il modulo per la ricerca di utenti Jabber corrispondenti ai criteri (Aggiungere * alla fine del campo per la ricerca di una sottostringa"}.
{"User",              "Utente"}.
{"Full Name", 	      "Nome completo"}.
{"Name", 	      "Nome"}.
{"Middle Name",       "Altro nome"}.
{"Family Name",       "Cognome"}.
{"Nickname", 	      "Nickname"}.
{"Birthday", 	      "Compleanno"}.
{"Country", 	      "Paese"}.
{"City", 	      "Città"}.
{"Organization Name", "Nome dell'organizzazione"}.
{"Organization Unit", "Unità dell'organizzazione"}.

% mod_adhoc.erl
{"Commands", "Comandi"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Send announcement to all users on all hosts", "Inviare l'annuncio a tutti gli utenti su tutti gli host"}.
{"Set message of the day on all hosts and send to online users", "Impostare il messaggio del giorno (MOTD) su tutti gli host e inviarlo agli utenti online"}.
{"Update message of the day on all hosts (don't send)", "Aggiornare il messaggio del giorno (MOTD) su tutti gli host (non inviarlo)"}.
{"Delete message of the day on all hosts", "Eliminare il messaggio del giorno (MOTD) su tutti gli host"}.
{"Really delete message of the day?", "Si conferma l'eliminazione del messaggio del giorno (MOTD)?"}.
{"Subject", "Oggetto"}.
{"Message body", "Corpo del messaggio"}.
{"No body provided for announce message", "Nessun corpo fornito per il messaggio di annuncio"}.
{"Announcements", "Annunci"}.
{"Send announcement to all users", "Inviare l'annuncio a tutti gli utenti"}.
{"Send announcement to all online users", "Inviare l'annuncio a tutti gli utenti online"}.
{"Send announcement to all online users on all hosts", "Inviare l'annuncio a tutti gli utenti online su tutti gli host"}.
{"Set message of the day and send to online users", "Impostare il messaggio del giorno (MOTD) ed inviarlo agli utenti online"}.
{"Update message of the day (don't send)", "Aggiornare il messaggio del giorno (MOTD) (non inviarlo)"}.
{"Delete message of the day", "Eliminare il messaggio del giorno (MOTD)"}.

% mod_pubsub/mod_pubsub.erl
{"Roster groups allowed to subscribe", "Gruppi roster abilitati alla registrazione"}.
{"Publish-Subscribe", "Pubblicazione-Iscrizione"}.
{"ejabberd Publish-Subscribe module", "Modulo Pubblicazione/Iscrizione (PubSub) per ejabberd"}.
{"PubSub subscriber request", "Richiesta di iscrizione per PubSub"}.
{"Choose whether to approve this entity's subscription.", "Scegliere se approvare l'iscrizione per questa entità"}.
{"Node ID", "ID del nodo"}.
{"Subscriber Address", "Indirizzo dell'iscritta/o"}.
{"Allow this JID to subscribe to this pubsub node?", "Consentire a questo JID l'iscrizione a questo nodo pubsub?"}.
{"Deliver event notifications", "Inviare notifiche degli eventi"}.
{"Specify the access model", "Specificare il modello di accesso"}.
{"When to send the last published item", "Quando inviare l'ultimo elemento pubblicato"}.
{"Deliver payloads with event notifications", "Inviare il contenuto del messaggio con la notifica dell'evento"}.
{"Notify subscribers when the node configuration changes", "Notificare gli iscritti quando la configurazione del nodo cambia"}.
{"Notify subscribers when the node is deleted", "Notificare gli iscritti quando il nodo è cancellato"}.
{"Notify subscribers when items are removed from the node", "Notificare gli iscritti quando sono eliminati degli elementi dal nodo"}.
{"Persist items to storage", "Conservazione persistente degli elementi"}.
{"Max # of items to persist", "Numero massimo di elementi da conservare persistentemente"}.
{"Whether to allow subscriptions", "Consentire iscrizioni?"}.
{"Specify the publisher model", "Definire il modello di pubblicazione"}.
{"Max payload size in bytes", "Dimensione massima del contenuto del messaggio in byte"}.
{"Only deliver notifications to available users", "Inviare le notifiche solamente agli utenti disponibili"}.

% mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "è stato espulso a causa di un cambiamento di appartenenza"}.
{"has been kicked because the room has been changed to members-only", "è stato espulso per la limitazione della stanza ai soli membri"}.
{"has been kicked because of a system shutdown", "è stato espulso a causa dello spegnimento del sistema"}.
{"Chatroom configuration modified", "Configurazione della stanza modificata"}.
{"joins the room", "entra nella stanza"}.
{"leaves the room", "esce dalla stanza"}.
{"has been kicked", "è stata/o espulsa/o"}.
{"has been banned", "è stata/o bandita/o"}.
{"is now known as", "è ora conosciuta/o come"}.
{"Monday", "Lunedì"}.
{"Tuesday", "Martedì"}.
{"Wednesday", "Mercoledì"}.
{"Thursday", "Giovedì"}.
{"Friday", "Venerdì"}.
{"Saturday", "Sabato"}.
{"Sunday", "Domenica"}.
{"January", "Gennaio"}.
{"February", "Febbraio"}.
{"March", "Marzo"}.
{"April", "Aprile"}.
{"May", "Maggio"}.
{"June", "Giugno"}.
{"July", "Luglio"}.
{"August", "Agosto"}.
{"September", "Settembre"}.
{"October", "Ottobre"}.
{"November", "Novembre"}.
{"December", "Dicembre"}.
{"Room Configuration", "Configurazione della stanza"}.

% mod_muc/mod_muc.erl
{"Chatrooms", "Stanze"}.
{"You need an x:data capable client to register nickname", "Per registrare un nickname è necessario un client che supporti x:data"}.
{"Nickname Registration at ", "Registrazione di un nickname su "}.
{"Enter nickname you want to register", "Immettere il nickname che si vuole registrare"}.
{"ejabberd MUC module", "Modulo MUC per ejabberd"}.
{"Only service administrators are allowed to send service messages", "L'invio di messaggi di servizio è consentito solamente agli amministratori del servizio"}.
{"Room creation is denied by service policy", "La creazione di stanze è impedita dalle politiche del servizio"}.
{"Conference room does not exist", "La stanza per conferenze non esiste"}.
{"Access denied by service policy", "Accesso impedito dalle politiche del servizio"}.
{"Specified nickname is already registered", "Il nickname specificato è già registrato"}.
{"You must fill in field \"Nickname\" in the form", "Si deve riempire il campo \"Nickname\" nel modulo"}.

% mod_muc/mod_muc_room.erl
{"This participant is kicked from the room because he sent an error message", "Partecipante espulso dalla stanza perché ha inviato un messaggio non valido"}.
{"This participant is kicked from the room because he sent an error message to another participant", "Partecipante espulso dalla stanza perché ha inviato un messaggio non valido a un altro partecipante"}.
{"This participant is kicked from the room because he sent an error presence", "Partecipante espulso dalla stanza perché ha inviato una presenza non valido"}.
{"Traffic rate limit is exceeded", "Limite di traffico superato"}.
{"Maximum Number of Occupants", "Numero massimo di occupanti"}.
{"No limit", "Nessun limite"}.
{"~s invites you to the room ~s", "~s ti invita nella stanza ~s"}.
{"the password is", "la password è"}.
{" has set the subject to: ", " ha modificato l'oggetto in: "}.
{"You need an x:data capable client to configure room", "Per la configurazione della stanza è necessario un client che supporti x:data"}.
{"Configuration for ", "Configurazione per "}.
{"Room title", "Titolo della stanza"}.
{"Password", "Password"}.
{"Only moderators and participants are allowed to change subject in this room", "La modifica dell'oggetto di questa stanza è consentita soltanto ai moderatori e ai partecipanti"}.
{"Only moderators are allowed to change subject in this room", "La modifica dell'oggetto di questa stanza è consentita soltanto ai moderatori"}.
{"Visitors are not allowed to send messages to all occupants", "Non è consentito ai visitatori l'invio di messaggi a tutti i presenti"}.
{"Only occupants are allowed to send messages to the conference", "L'invio di messaggi alla conferenza è consentito soltanto ai presenti"}.
{"It is not allowed to send private messages to the conference", "Non è consentito l'invio di messaggi privati alla conferenza"}.
{"Improper message type", "Tipo di messaggio non corretto"}.
{"Nickname is already in use by another occupant", "Il nickname è già in uso all'interno della conferenza"}.
{"Nickname is registered by another person", "Il nickname è registrato da un'altra persona"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Non è consentito l'invio di messaggi privati di tipo \"groupchat\""}.
{"Recipient is not in the conference room", "Il destinatario non è nella stanza per conferenze"}.
{"Only occupants are allowed to send queries to the conference", "L'invio di query alla conferenza è consentito ai soli presenti"}.
{"Queries to the conference members are not allowed in this room", "In questa stanza non sono consentite query ai membri della conferenza"}.
{"You have been banned from this room", "Sei stata/o bandita/o da questa stanza"}.
{"Membership required to enter this room", "Per entrare in questa stanza è necessario essere membro"}.
{"Password required to enter this room", "Per entrare in questa stanza è prevista una password"}.
{"Incorrect password", "Password non esatta"}.
{"Administrator privileges required", "Necessari i privilegi di amministratore"}.
{"Moderator privileges required", "Necessari i privilegi di moderatore"}.
{"JID ~s is invalid", "Il JID ~s non è valido"}.
{"Nickname ~s does not exist in the room", "Il nickname ~s non esiste nella stanza"}.
{"Invalid affiliation: ~s", "Affiliazione non valida: ~s"}.
{"Invalid role: ~s", "Ruolo non valido: ~s"}.
{"Owner privileges required", "Necessari i privilegi di proprietario"}.
{"private, ", "privato, "}.
{"This room is not anonymous", "Questa stanza non è anonima"}.
{"Make room persistent", "Rendere la stanza persistente"}.
{"Make room public searchable", "Rendere la sala visibile al pubblico"}.
{"Make participants list public", "Rendere pubblica la lista dei partecipanti"}.
{"Make room password protected", "Rendere la stanza protetta da password"}.
{"Make room members-only", "Rendere la stanza riservata ai membri"}.
{"Make room moderated", "Rendere la stanza moderata"}.
{"Default users as participants", "Definire per default gli utenti come partecipanti"}.
{"Allow users to change subject", "Consentire agli utenti di cambiare l'oggetto"}.
{"Allow users to send private messages", "Consentire agli utenti l'invio di messaggi privati"}.
{"Allow users to query other users", "Consentire agli utenti query verso altri utenti"}.
{"Allow users to send invites", "Consentire agli utenti l'invio di inviti"}.
{"Enable logging", "Abilitare i log"}.
{"Number of occupants", "Numero di presenti"}.
{"Present real JIDs to", "Rendere visibile il JID reale a"}.
{"moderators only", "moderatori soltanto"}.
{"anyone", "tutti"}.

% mod_irc/mod_irc.erl
{"IRC Transport", "Transport IRC"}.
{"ejabberd IRC module", "Modulo IRC per ejabberd"}.
{"You need an x:data capable client to configure mod_irc settings", "Per la configurazione del modulo IRC è necessario un client che supporti x:data"}.
{"Registration in mod_irc for ", "Registrazione in mod_irc per "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Immettere il nome utente e le codifiche che si desidera utilizzare per la connessione ai server IRC"}.
{"IRC Username", "Nome utente IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Se si vogliono specificare differenti codifiche per i server IRC, si riempa questo elenco con valori nel formato '{\"server IRC\", \"codifica\"}'. Per default questo servizio utilizza la codifica \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Esempio: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Codifiche"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "Amministrazione web ejabberd"}.
{"Administration", "Amministrazione"}.
{"Users", "Utenti"}.
{"Nodes", "Nodi"}.
{"Statistics", "Statistiche"}.
{"(Raw)", "(Grezzo)"}.
{"Submitted", "Inviato"}.
{"Bad format", "Formato non valido"}.
{"Raw", "Grezzo"}.
{"Delete Selected", "Eliminare gli elementi selezionati"}.
{"Submit", "Inviare"}.
{"~s access rule configuration", "Configurazione delle regole di accesso per ~s"}.
{"Node not found", "Nodo non trovato"}.
{"Add New", "Aggiungere nuovo"}.
{"Registered Users", "Utenti registrati"}.
{"Registered Users:", "Utenti registrati:"}.
{"Change Password", "Modificare la password"}.
{"Connected Resources:", "Risorse connesse:"}.
{"Password:", "Password:"}.
{"None", "Nessuno"}.
{"Node ", "Nodo "}.
{"Listened Ports", "Porte in ascolto"}.
{"Restart", "Riavviare"}.
{"Stop", "Arrestare"}.
{"RPC Call Error", "Errore di chiamata RPC"}.
{"Name", "Nome"}.
{"Storage Type", "Tipo di conservazione"}.
{"Size", "Dimensione"}.
{"Memory", "Memoria"}.
{"OK", "OK"}.
{"Listened Ports at ", "Porte in ascolto su "}.
{"Uptime:", "Tempo dall'avvio:"}.
{"CPU Time:", "Tempo CPU:"}.
{"Transactions Commited:", "Transazioni avvenute:"}.
{"Transactions Aborted:", "Transazioni abortite:"}.
{"Transactions Restarted:", "Transazioni riavviate:"}.
{"Transactions Logged:", "Transazioni con log:"}.
{"Port", "Porta"}.
{"Module", "Modulo"}.
{"Options", "Opzioni"}.
{"Update", "Aggiornare"}.
{"Delete", "Eliminare"}.
{"Add User", "Aggiungere un utente"}.
{"Offline Messages", "Messaggi offline"}.
{"Users Last Activity", "Ultima attività degli utenti"}.
{"Never", "Mai"}.
{"~s's Offline Messages Queue", "Coda di ~s messaggi offline"}.
{"Time", "Ora"}.
{"From", "Da"}.
{"To", "A"}.
{"Packet", "Pacchetto"}.
{"Offline Messages:", "Messaggi offline:"}.
{"Roster", "Lista dei contatti"}.
{"Nickname", "Nickname"}.
{"Subscription", "Iscrizione"}.
{"Pending", "Pendente"}.
{"Groups", "Gruppi"}.
{"Remove", "Eliminare"}.
{"Add Jabber ID", "Aggiungere un Jabber ID (JID)"}.
{"User ", "Utente "}.
{"Roster of ", "Lista dei contatti di "}.
{"Online", "Online"}.
{"Validate", "Validare"}.
{"Name:", "Nome:"}.
{"Description:", "Descrizione:"}.
{"Members:", "Membri:"}.
{"Displayed Groups:", "Gruppi visualizzati:"}.
{"Group ", "Gruppo "}.
{"Period: ", "Periodo:"}.
{"Last month", "Ultimo mese"}.
{"Last year", "Ultimo anno"}.
{"All activity", "Tutta l'attività"}.
{"Show Ordinary Table", "Mostrare la tabella normale"}.
{"Show Integral Table", "Mostrare la tabella integrale"}.
{"Modules at ", "Moduli su "}.
{"Start", "Avviare"}.
{"Virtual Hosts", "Host virtuali"}.
{"ejabberd virtual hosts", "Host virtuali di ejabberd"}.
{"Host", "Host"}.
{"No Data", "Nessuna informazione"}.
{"Online Users:", "Utenti connessi:"}.
{"Outgoing s2s Connections:", "Connessioni s2s in uscita:"}.
{"Outgoing s2s Servers:", "Server s2s in uscita"}.
{"Database Tables at ", "Tabelle del database su "}.
{"Backup of ", "Salvataggio di "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "N.B.: Queste opzioni comportano il salvataggio solamente del database interno Mnesia. Se si sta utilizzando il modulo ODBC, è necessario salvare il proprio database SQL separatamente."}.
{"Store binary backup:", "Conservare un salvataggio binario:"}.
{"Restore binary backup immediately:", "Recuperare un salvataggio binario adesso:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Recuperare un salvataggio binario dopo il prossimo riavvio di ejabberd (necessita di meno memoria):"}.
{"Store plain text backup:", "Conservare un salvataggio come semplice testo:"}.
{"Restore plain text backup immediately:", "Recuperare un salvataggio come semplice testo adesso:"}.
{"Statistics of ~p", "Statistiche di ~p"}.
{"Update ", "Aggiornare "}.
{"Update plan", "Piano di aggiornamento"}.
{"Updated modules", "Moduli aggiornati"}.
{"Update script", "Script di aggiornamento"}.
{"Low level update script", "Script di aggiornamento di basso livello"}.
{"Script check", "Verifica dello script"}.
{"Shared Roster Groups", "Gruppi di liste di contatti comuni"}.
{"Last Activity", "Ultima attività"}.

% mod_vcard_odbc.erl
{"vCard User Search", "Ricerca di utenti per vCard"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "La coda dei messaggi offline del contatto è piena. Il messaggio è stato scartato"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "Modulo SOCKS5 Bytestreams per ejabberd"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
