{"Access Configuration","Configurazione dell'accesso"}.
{"Access Control List Configuration","Configurazione dei diritti di accesso (ACL)"}.
{"Access control lists","Diritti di accesso (ACL)"}.
{"Access Control Lists","Diritti di accesso (ACL)"}.
{"Access denied by service policy","Accesso impedito dalle politiche del servizio"}.
{"Access rules","Regole di accesso"}.
{"Access Rules","Regole di accesso"}.
{"Action on user","Azione sull'utente"}.
{"Add Jabber ID","Aggiungere un Jabber ID (Jabber ID)"}.
{"Add New","Aggiungere nuovo"}.
{"Add User","Aggiungere un utente"}.
{"Administration","Amministrazione"}.
{"Administration of ","Amministrazione di "}.
{"Administrator privileges required","Necessari i privilegi di amministratore"}.
{"A friendly name for the node","Un nome comodo per il nodo"}.
{"All activity","Tutta l'attività"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Consentire a questo JID l'iscrizione a questo nodo pubsub?"}.
{"Allow users to change subject","Consentire agli utenti di cambiare l'oggetto"}.
{"Allow users to query other users","Consentire agli utenti query verso altri utenti"}.
{"Allow users to send invites","Consentire agli utenti l'invio di inviti"}.
{"Allow users to send private messages","Consentire agli utenti l'invio di messaggi privati"}.
{"Allow visitors to change nickname","Consentire ai visitatori di cambiare il nickname"}.
{"Allow visitors to send status text in presence updates","Consentire ai visitatori l'invio di testo sullo stato in aggiornamenti sulla presenza"}.
{"All Users","Tutti gli utenti"}.
{"Announcements","Annunci"}.
{"anyone","tutti"}.
{"April","Aprile"}.
{"August","Agosto"}.
{"Backup Management","Gestione dei salvataggi"}.
{"Backup of ","Salvataggio di "}.
{"Backup","Salvare"}.
{"Backup to File at ","Salvataggio sul file "}.
{"Bad format","Formato non valido"}.
{"Birthday","Compleanno"}.
{"Change Password","Modificare la password"}.
{"Change User Password","Cambiare la password dell'utente"}.
{"Chatroom configuration modified","Configurazione della stanza modificata"}.
{"Chatrooms","Stanze"}.
{"Choose a username and password to register with this server","Scegliere un nome utente e una password per la registrazione con questo server"}.
{"Choose modules to stop","Selezionare i moduli da arrestare"}.
{"Choose storage type of tables","Selezionare una modalità di conservazione delle tabelle"}.
{"Choose whether to approve this entity's subscription.","Scegliere se approvare l'iscrizione per questa entità"}.
{"City","Città"}.
{"Commands","Comandi"}.
{"Conference room does not exist","La stanza per conferenze non esiste"}.
{"Configuration","Configurazione"}.
{"Configuration for ","Configurazione per "}.
{"Connected Resources:","Risorse connesse:"}.
{"Country","Paese"}.
{"CPU Time:","Tempo CPU:"}.
{"Database","Database"}.
{"Database Tables at ","Tabelle del database su "}.
{"Database Tables Configuration at ","Configurazione delle tabelle del database su "}.
{"December","Dicembre"}.
{"Default users as participants","Definire per default gli utenti come partecipanti"}.
{"Delete","Eliminare"}.
{"Delete message of the day","Eliminare il messaggio del giorno (MOTD)"}.
{"Delete message of the day on all hosts","Eliminare il messaggio del giorno (MOTD) su tutti gli host"}.
{"Delete Selected","Eliminare gli elementi selezionati"}.
{"Delete User","Eliminare l'utente"}.
{"Deliver event notifications","Inviare notifiche degli eventi"}.
{"Deliver payloads with event notifications","Inviare il contenuto del messaggio con la notifica dell'evento"}.
{"Description:","Descrizione:"}.
{"Disc only copy","Copia su disco soltanto"}.
{"Displayed Groups:","Gruppi visualizzati:"}.
{"Dump Backup to Text File at ","Trascrivere il salvataggio sul file di testo "}.
{"Dump to Text File","Trascrivere su file di testo"}.
{"Edit Properties","Modificare le proprietà"}.
{"ejabberd IRC module","Modulo IRC per ejabberd"}.
{"ejabberd MUC module","Modulo MUC per ejabberd"}.
{"ejabberd Publish-Subscribe module","Modulo Pubblicazione/Iscrizione (PubSub) per ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","Modulo SOCKS5 Bytestreams per ejabberd"}.
{"ejabberd vCard module","Modulo vCard per ejabberd"}.
{"ejabberd virtual hosts","Host virtuali di ejabberd"}.
{"ejabberd Web Admin","Amministrazione web ejabberd"}.
{"Email","E-mail"}.
{"Enable logging","Abilitare i log"}.
{"Encodings","Codifiche"}.
{"End User Session","Terminare la sessione dell'utente"}.
{"Enter list of {Module, [Options]}","Immettere un elenco di {Modulo, [Opzioni]}"}.
{"Enter nickname you want to register","Immettere il nickname che si vuole registrare"}.
{"Enter path to backup file","Immettere il percorso del file di salvataggio"}.
{"Enter path to jabberd14 spool dir","Immettere il percorso della directory di spool di jabberd14"}.
{"Enter path to jabberd14 spool file","Immettere il percorso del file di spool di jabberd14"}.
{"Enter path to text file","Immettere il percorso del file di testo"}.
{"Enter username and encodings you wish to use for connecting to IRC servers","Immettere il nome utente e le codifiche che si desidera utilizzare per la connessione ai server IRC"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].","Esempio: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Family Name","Cognome"}.
{"February","Febbraio"}.
{"Fill in fields to search for any matching Jabber User","Riempire i campi per la ricerca di utenti Jabber corrispondenti ai criteri"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Riempire il modulo per la ricerca di utenti Jabber corrispondenti ai criteri (Aggiungere * alla fine del campo per la ricerca di una sottostringa"}.
{"Friday","Venerdì"}.
{"From","Da"}.
{"From ~s","Da ~s"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Ottenere il numero di utenti online"}.
{"Get Number of Registered Users","Ottenere il numero di utenti registrati"}.
{"Get User Last Login Time","Ottenere la data di ultimo accesso dell'utente"}.
{"Get User Password","Ottenere la password dell'utente"}.
{"Get User Statistics","Ottenere le statistiche dell'utente"}.
{"Group ","Gruppo "}.
{"Groups","Gruppi"}.
{"has been banned","è stata/o bandita/o"}.
{"has been kicked because of an affiliation change","è stato espulso a causa di un cambiamento di appartenenza"}.
{"has been kicked because of a system shutdown","è stato espulso a causa dello spegnimento del sistema"}.
{"has been kicked because the room has been changed to members-only","è stato espulso per la limitazione della stanza ai soli membri"}.
{"has been kicked","è stata/o espulsa/o"}.
{" has set the subject to: "," ha modificato l'oggetto in: "}.
{"Host","Host"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","Se si vogliono specificare differenti codifiche per i server IRC, si riempa questo elenco con valori nel formato '{\"server IRC\", \"codifica\"}'. Per default questo servizio utilizza la codifica \"~s\"."}.
{"Import Directory","Importare una directory"}.
{"Import File","Importare un file"}.
{"Import User from File at ","Importare un utente dal file "}.
{"Import Users from Dir at ","Importare utenti dalla directory "}.
{"Import Users From jabberd14 Spool Files","Importare utenti da file di spool di jabberd14"}.
{"Improper message type","Tipo di messaggio non corretto"}.
{"Incorrect password","Password non esatta"}.
{"Invalid affiliation: ~s","Affiliazione non valida: ~s"}.
{"Invalid role: ~s","Ruolo non valido: ~s"}.
{"IP addresses","Indirizzi IP"}.
{"IRC Transport","Transport IRC"}.
{"IRC Username","Nome utente IRC"}.
{"is now known as","è ora conosciuta/o come"}.
{"It is not allowed to send private messages","Non è consentito l'invio di messaggi privati"}.
{"It is not allowed to send private messages of type \"groupchat\"","Non è consentito l'invio di messaggi privati di tipo \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Non è consentito l'invio di messaggi privati alla conferenza"}.
{"Jabber ID","Jabber ID (Jabber ID)"}.
{"January","Gennaio"}.
{"Jabber ID ~s is invalid","Il JID ~s non è valido"}.
{"joins the room","entra nella stanza"}.
{"July","Luglio"}.
{"June","Giugno"}.
{"Last Activity","Ultima attività"}.
{"Last login","Ultimo accesso"}.
{"Last month","Ultimo mese"}.
{"Last year","Ultimo anno"}.
{"leaves the room","esce dalla stanza"}.
{"Listened Ports at ","Porte in ascolto su "}.
{"Listened Ports","Porte in ascolto"}.
{"List of modules to start","Elenco dei moduli da avviare"}.
{"Low level update script","Script di aggiornamento di basso livello"}.
{"Make participants list public","Rendere pubblica la lista dei partecipanti"}.
{"Make room members-only","Rendere la stanza riservata ai membri"}.
{"Make room moderated","Rendere la stanza moderata"}.
{"Make room password protected","Rendere la stanza protetta da password"}.
{"Make room persistent","Rendere la stanza persistente"}.
{"Make room public searchable","Rendere la sala visibile al pubblico"}.
{"March","Marzo"}.
{"Maximum Number of Occupants","Numero massimo di occupanti"}.
{"Max # of items to persist","Numero massimo di elementi da conservare persistentemente"}.
{"Max payload size in bytes","Dimensione massima del contenuto del messaggio in byte"}.
{"May","Maggio"}.
{"Membership required to enter this room","Per entrare in questa stanza è necessario essere membro"}.
{"Members:","Membri:"}.
{"Memory","Memoria"}.
{"Message body","Corpo del messaggio"}.
{"Middle Name","Altro nome"}.
{"Moderator privileges required","Necessari i privilegi di moderatore"}.
{"moderators only","moderatori soltanto"}.
{"Module","Modulo"}.
{"Modules at ","Moduli su "}.
{"Modules","Moduli"}.
{"Monday","Lunedì"}.
{"Name:","Nome:"}.
{"Name","Nome"}.
{"Never","Mai"}.
{"Nickname is already in use by another occupant","Il nickname è già in uso all'interno della conferenza"}.
{"Nickname is registered by another person","Il nickname è registrato da un'altra persona"}.
{"Nickname","Nickname"}.
{"Nickname Registration at ","Registrazione di un nickname su "}.
{"Nickname ~s does not exist in the room","Il nickname ~s non esiste nella stanza"}.
{"No body provided for announce message","Nessun corpo fornito per il messaggio di annuncio"}.
{"No Data","Nessuna informazione"}.
{"Node ID","ID del nodo"}.
{"Node ","Nodo "}.
{"Node not found","Nodo non trovato"}.
{"Nodes","Nodi"}.
{"No limit","Nessun limite"}.
{"None","Nessuno"}.
{"No resource provided","Nessuna risorsa fornita"}.
{"Notify subscribers when items are removed from the node","Notificare gli iscritti quando sono eliminati degli elementi dal nodo"}.
{"Notify subscribers when the node configuration changes","Notificare gli iscritti quando la configurazione del nodo cambia"}.
{"Notify subscribers when the node is deleted","Notificare gli iscritti quando il nodo è cancellato"}.
{"November","Novembre"}.
{"Number of occupants","Numero di presenti"}.
{"Number of online users","Numero di utenti online"}.
{"Number of registered users","Numero di utenti registrati"}.
{"October","Ottobre"}.
{"Offline Messages:","Messaggi offline:"}.
{"Offline Messages","Messaggi offline"}.
{"OK","OK"}.
{"Online","Online"}.
{"Online Users:","Utenti connessi:"}.
{"Online Users","Utenti online"}.
{"Only deliver notifications to available users","Inviare le notifiche solamente agli utenti disponibili"}.
{"Only moderators and participants are allowed to change subject in this room","La modifica dell'oggetto di questa stanza è consentita soltanto ai moderatori e ai partecipanti"}.
{"Only moderators are allowed to change subject in this room","La modifica dell'oggetto di questa stanza è consentita soltanto ai moderatori"}.
{"Only occupants are allowed to send messages to the conference","L'invio di messaggi alla conferenza è consentito soltanto ai presenti"}.
{"Only occupants are allowed to send queries to the conference","L'invio di query alla conferenza è consentito ai soli presenti"}.
{"Only service administrators are allowed to send service messages","L'invio di messaggi di servizio è consentito solamente agli amministratori del servizio"}.
{"Options","Opzioni"}.
{"Organization Name","Nome dell'organizzazione"}.
{"Organization Unit","Unità dell'organizzazione"}.
{"Outgoing s2s Connections:","Connessioni s2s in uscita:"}.
{"Outgoing s2s Connections","Connessioni s2s in uscita"}.
{"Outgoing s2s Servers:","Server s2s in uscita"}.
{"Owner privileges required","Necessari i privilegi di proprietario"}.
{"Packet","Pacchetto"}.
{"Password:","Password:"}.
{"Password","Password"}.
{"Password required to enter this room","Per entrare in questa stanza è prevista una password"}.
{"Password Verification","Verifica della password"}.
{"Path to Dir","Percorso della directory"}.
{"Path to File","Percorso del file"}.
{"Pending","Pendente"}.
{"Period: ","Periodo:"}.
{"Persist items to storage","Conservazione persistente degli elementi"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","Porta"}.
{"Present real Jabber IDs to","Rendere visibile il JID reale a"}.
{"private, ","privato, "}.
{"Publish-Subscribe","Pubblicazione-Iscrizione"}.
{"PubSub subscriber request","Richiesta di iscrizione per PubSub"}.
{"Queries to the conference members are not allowed in this room","In questa stanza non sono consentite query ai membri della conferenza"}.
{"RAM and disc copy","Copia in memoria (RAM) e su disco"}.
{"RAM copy","Copia in memoria (RAM)"}.
{"(Raw)","(Grezzo)"}.
{"Raw","Grezzo"}.
{"Really delete message of the day?","Si conferma l'eliminazione del messaggio del giorno (MOTD)?"}.
{"Recipient is not in the conference room","Il destinatario non è nella stanza per conferenze"}.
{"Registered Users:","Utenti registrati:"}.
{"Registered Users","Utenti registrati"}.
{"Registration in mod_irc for ","Registrazione in mod_irc per "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","N.B.: Queste opzioni comportano il salvataggio solamente del database interno Mnesia. Se si sta utilizzando il modulo ODBC, è necessario salvare il proprio database SQL separatamente."}.
{"Remote copy","Copia remota"}.
{"Remove","Eliminare"}.
{"Remove User","Eliminare l'utente"}.
{"Replaced by new connection","Sostituito da una nuova connessione"}.
{"Resources","Risorse"}.
{"Restart","Riavviare"}.
{"Restart Service","Riavviare il servizio"}.
{"Restore Backup from File at ","Recuperare il salvataggio dal file "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Recuperare un salvataggio binario dopo il prossimo riavvio di ejabberd (necessita di meno memoria):"}.
{"Restore binary backup immediately:","Recuperare un salvataggio binario adesso:"}.
{"Restore plain text backup immediately:","Recuperare un salvataggio come semplice testo adesso:"}.
{"Restore","Recuperare"}.
{"Room Configuration","Configurazione della stanza"}.
{"Room creation is denied by service policy","La creazione di stanze è impedita dalle politiche del servizio"}.
{"Room title","Titolo della stanza"}.
{"Roster groups allowed to subscribe","Gruppi roster abilitati alla registrazione"}.
{"Roster","Lista dei contatti"}.
{"Roster of ","Lista dei contatti di "}.
{"Roster size","Dimensione della lista dei contatti"}.
{"RPC Call Error","Errore di chiamata RPC"}.
{"Running Nodes","Nodi attivi"}.
{"~s access rule configuration","Configurazione delle regole di accesso per ~s"}.
{"Saturday","Sabato"}.
{"Script check","Verifica dello script"}.
{"Search Results for ","Risultati della ricerca per "}.
{"Search users in ","Cercare utenti in "}.
{"Send announcement to all online users","Inviare l'annuncio a tutti gli utenti online"}.
{"Send announcement to all online users on all hosts","Inviare l'annuncio a tutti gli utenti online su tutti gli host"}.
{"Send announcement to all users","Inviare l'annuncio a tutti gli utenti"}.
{"Send announcement to all users on all hosts","Inviare l'annuncio a tutti gli utenti su tutti gli host"}.
{"September","Settembre"}.
{"Set message of the day and send to online users","Impostare il messaggio del giorno (MOTD) ed inviarlo agli utenti online"}.
{"Set message of the day on all hosts and send to online users","Impostare il messaggio del giorno (MOTD) su tutti gli host e inviarlo agli utenti online"}.
{"Shared Roster Groups","Gruppi di liste di contatti comuni"}.
{"Show Integral Table","Mostrare la tabella integrale"}.
{"Show Ordinary Table","Mostrare la tabella normale"}.
{"Shut Down Service","Terminare il servizio"}.
{"~s invites you to the room ~s","~s ti invita nella stanza ~s"}.
{"Size","Dimensione"}.
{"Specified nickname is already registered","Il nickname specificato è già registrato"}.
{"Specify the access model","Specificare il modello di accesso"}.
{"Specify the publisher model","Definire il modello di pubblicazione"}.
{"~s's Offline Messages Queue","Coda di ~s messaggi offline"}.
{"Start","Avviare"}.
{"Start Modules at ","Avviare moduli su "}.
{"Start Modules","Avviare moduli"}.
{"Statistics of ~p","Statistiche di ~p"}.
{"Statistics","Statistiche"}.
{"Stop","Arrestare"}.
{"Stop Modules","Arrestare moduli"}.
{"Stop Modules at ","Arrestare moduli su "}.
{"Stopped Nodes","Nodi arrestati"}.
{"Storage Type","Tipo di conservazione"}.
{"Store binary backup:","Conservare un salvataggio binario:"}.
{"Store plain text backup:","Conservare un salvataggio come semplice testo:"}.
{"Subject","Oggetto"}.
{"Submit","Inviare"}.
{"Submitted","Inviato"}.
{"Subscriber Address","Indirizzo dell'iscritta/o"}.
{"Subscription","Iscrizione"}.
{"Sunday","Domenica"}.
{"the password is","la password è"}.
{"This participant is kicked from the room because he sent an error message","Partecipante espulso dalla stanza perché ha inviato un messaggio non valido"}.
{"This participant is kicked from the room because he sent an error message to another participant","Partecipante espulso dalla stanza perché ha inviato un messaggio non valido a un altro partecipante"}.
{"This participant is kicked from the room because he sent an error presence","Partecipante espulso dalla stanza perché ha inviato una presenza non valido"}.
{"This room is not anonymous","Questa stanza non è anonima"}.
{"Thursday","Giovedì"}.
{"Time delay","Ritardo"}.
{"Time","Ora"}.
{"To","A"}.
{"To ~s","A ~s"}.
{"Traffic rate limit is exceeded","Limite di traffico superato"}.
{"Transactions Aborted:","Transazioni abortite:"}.
{"Transactions Committed:","Transazioni avvenute:"}.
{"Transactions Logged:","Transazioni con log:"}.
{"Transactions Restarted:","Transazioni riavviate:"}.
{"Tuesday","Martedì"}.
{"Update ","Aggiornare "}.
{"Update","Aggiornare"}.
{"Updated modules","Moduli aggiornati"}.
{"Update message of the day (don't send)","Aggiornare il messaggio del giorno (MOTD) (non inviarlo)"}.
{"Update message of the day on all hosts (don't send)","Aggiornare il messaggio del giorno (MOTD) su tutti gli host (non inviarlo)"}.
{"Update plan","Piano di aggiornamento"}.
{"Update script","Script di aggiornamento"}.
{"Uptime:","Tempo dall'avvio:"}.
{"Use of STARTTLS required","Utilizzo di STARTTLS obbligatorio"}.
{"User Management","Gestione degli utenti"}.
{"Users are not allowed to register accounts so fast","Non è consentito agli utenti registrare account così rapidamente"}.
{"Users Last Activity","Ultima attività degli utenti"}.
{"Users","Utenti"}.
{"User ","Utente "}.
{"User","Utente"}.
{"Validate","Validare"}.
{"vCard User Search","Ricerca di utenti per vCard"}.
{"Virtual Hosts","Host virtuali"}.
{"Visitors are not allowed to change their nicknames in this room","Non è consentito ai visitatori cambiare il nickname in questa stanza"}.
{"Visitors are not allowed to send messages to all occupants","Non è consentito ai visitatori l'invio di messaggi a tutti i presenti"}.
{"Wednesday","Mercoledì"}.
{"When to send the last published item","Quando inviare l'ultimo elemento pubblicato"}.
{"Whether to allow subscriptions","Consentire iscrizioni?"}.
{"You have been banned from this room","Sei stata/o bandita/o da questa stanza"}.
{"You must fill in field \"Nickname\" in the form","Si deve riempire il campo \"Nickname\" nel modulo"}.
{"You need an x:data capable client to configure mod_irc settings","Per la configurazione del modulo IRC è necessario un client che supporti x:data"}.
{"You need an x:data capable client to configure room","Per la configurazione della stanza è necessario un client che supporti x:data"}.
{"You need an x:data capable client to register nickname","Per registrare un nickname è necessario un client che supporti x:data"}.
{"You need an x:data capable client to search","Per effettuare ricerche è necessario un client che supporti x:data"}.
{"Your contact offline message queue is full. The message has been discarded.","La coda dei messaggi offline del contatto è piena. Il messaggio è stato scartato"}.
