{"Access Configuration","アクセス設定"}.
{"Access Control List Configuration","アクセスコントロールリスト設定"}.
{"Access control lists","アクセスコントロールリスト"}.
{"Access Control Lists","アクセスコントロールリスト"}.
{"Access denied by service policy","サービスポリシーによってアクセスが禁止されました"}.
{"Access rules","アクセスルール"}.
{"Access Rules","アクセスルール"}.
{"Action on user","ユーザー操作"}.
{"Add Jabber ID","Jabber ID の追加"}.
{"Add New","新規追加"}.
{"Add User","ユーザーを追加"}.
{"Administration of ","管理: "}.
{"Administration","管理"}.
{"Administrator privileges required","管理者権限が必要です"}.
{"A friendly name for the node","ノードの為のフレンドリネーム"}.
{"All activity","全て"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","この JID をこの pubsubノードへ購読することを許可しますか？"}.
{"Allow users to change subject","ユーザーによる件名の変更を許可する"}.
{"Allow users to query other users","ユーザーによる他のユーザーへの問い合わせを許可する"}.
{"Allow users to send invites","ユーザーによる招待を許可する"}.
{"Allow users to send private messages","ユーザーによるプライベートメッセージの送信を許可する"}.
{"Allow visitors to change nickname","ビジターがニックネームを変更する事を許可します"}.
{"Allow visitors to send status text in presence updates","ビジターがプレゼンス更新のステータス文を送信する事を許可する"}.
{"All Users","全ユーザー"}.
{"Announcements","アナウンス"}.
{"anyone","誰でも"}.
{"April","4月"}.
{"August","8月"}.
{"Backup","バックアップ"}.
{"Backup Management","バックアップ管理"}.
{"Backup of ","バックアップ: "}.
{"Backup to File at ","ファイルにバックアップ"}.
{"Bad format","不正なフォーマット"}.
{"Birthday","誕生日"}.
{"Change Password","パスワードの変更"}.
{"Change User Password","パスワードを変更"}.
{"Chatroom configuration modified","チャットルームの設定を変更しました"}.
{"Chatrooms","チャットルーム"}.
{"Choose a username and password to register with this server","サーバーに登録するユーザー名とパスワードを選択して下さい"}.
{"Choose modules to stop","停止するモジュールの選択"}.
{"Choose storage type of tables","テーブルのストレージタイプの選択"}.
{"Choose whether to approve this entity's subscription.","このエントリを承認するかどうかを選択して下さい"}.
{"City","都道府県"}.
{"Commands","コマンド"}.
{"Conference room does not exist","カンファレンスルームは存在しません"}.
{"Configuration for ","設定: "}.
{"Configuration","設定"}.
{"Connected Resources:","接続リソース:"}.
{"Country","国"}.
{"CPU Time:","CPU時間:"}.
{"Database","データーベース"}.
{"Database Tables at ","データーベーステーブル: "}.
{"Database Tables Configuration at ","データーベーステーブル設定 "}.
{"December","12月"}.
{"Default users as participants","デフォルトのユーザーは参加者にする"}.
{"Delete message of the day on all hosts","全ホストのお知らせメッセージを削除する"}.
{"Delete message of the day","お知らせメッセージを削除する"}.
{"Delete Selected","選択した項目を削除"}.
{"Delete User","ユーザを削除"}.
{"Delete","削除"}.
{"Deliver event notifications","イベント通知を配送します"}.
{"Deliver payloads with event notifications","イベント通知と同時にペイロードを配送します"}.
{"Description:","詳細:"}.
{"Disc only copy","ディスクだけのコピー"}.
{"Displayed Groups:","表示グループ"}.
{"Dump Backup to Text File at ","テキストファイルにバックアップ"}.
{"Dump to Text File","テキストファイルに出力"}.
{"Edit Properties","プロパティの編集"}.
{"ejabberd IRC module","ejabberd IRC module"}.
{"ejabberd MUC module","ejabberd MUC module"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe module"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams module"}.
{"ejabberd vCard module","ejabberd vCard module"}.
{"ejabberd virtual hosts","ejabberd ヴァーチャルホスト"}.
{"ejabberd Web Admin","ejabberd Web 管理"}.
{"Email","メールアドレス"}.
{"Enable logging","ロギングを有効にする"}.
{"Encodings","エンコーディング"}.
{"End User Session","エンドユーザーセッション"}.
{"Enter list of {Module, [Options]}","{モジュール, [オプション]}のリストを入力して下さい"}.
{"Enter nickname you want to register","登録するニックネームを入力して下さい"}.
{"Enter path to backup file","バックアップファイルのパスを入力して下さい"}.
{"Enter path to jabberd14 spool dir","jabberd14 spool ディレクトリのパスを入力して下さい"}.
{"Enter path to jabberd14 spool file","jabberd14 spool ファイルのパスを入力して下さい"}.
{"Enter path to text file","テキストファイルのパスを入力して下さい"}.
{"Enter username and encodings you wish to use for connecting to IRC servers","IRCサーバーに接続先する為のユーザー名と文字エンコーディングを入力して下さい"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].","例: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Family Name","姓"}.
{"February","2月"}.
{"Fill in fields to search for any matching Jabber User","項目を埋めて Jabber User を検索して下さい"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","フォームを埋めて Jabber User を検索して下さい(* を使用すると部分文字列にマッチします)"}.
{"Friday","金曜日"}.
{"From ~s","差出人 ~s"}.
{"From","差出人"}.
{"Full Name","氏名"}.
{"Get Number of Online Users","登録ユーザーを取得"}.
{"Get Number of Registered Users","登録ユーザー数を取得"}.
{"Get User Last Login Time","最終ログイン時間の取得"}.
{"Get User Password","パスワードを取得"}.
{"Get User Statistics","ユーザー統計の取得"}.
{"Group ","グループ"}.
{"Groups","グループ"}.
{"has been banned","はバンされました"}.
{"has been kicked","はキックされました"}.
{"has been kicked because of an affiliation change","は提携が変更されたためキックされました"}.
{"has been kicked because of a system shutdown","はシステムシャットダウンのためキックされました"}.
{"has been kicked because the room has been changed to members-only","はチャットルームのメンバー制限によりキックされました"}.
{" has set the subject to: "," は件名を設定しました: "}.
{"Host","ホスト"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","別の文字エンコーディングを使用したい場合、'{\"irc server\", \"encoding\"}' という形式のリストを入力して下さい。デフォルトで \"~s\" を使用します"}.
{"Import Directory","ディレクトリインポート"}.
{"Import File","ファイルかインポート"}.
{"Import User from File at ","ファイルからユーザーをインポート"}.
{"Import Users from Dir at ","ディレクトリからユーザーをインポート"}.
{"Import Users From jabberd14 Spool Files","jabberd14 Spool ファイルからユーザーをインポート"}.
{"Improper message type","誤ったメッセージタイプです"}.
{"Incorrect password","パスワードが違います"}.
{"Invalid affiliation: ~s","無効な提携です: ~s"}.
{"Invalid role: ~s","無効なロールです: ~s"}.
{"IP addresses","IPアドレス"}.
{"IRC Transport","IRC トランスポート"}.
{"IRC Username","IRCユーザー名"}.
{"is now known as","は名前を変更しました: "}.
{"It is not allowed to send private messages of type \"groupchat\"","種別が\"groupchat\" であるプライベートメッセージは許可されていません"}.
{"It is not allowed to send private messages to the conference","カンファレンスルームにプライベートメッセージを送信することは出来ません"}.
{"It is not allowed to send private messages","プライベートメッセージを送信することは許可されませんでした"}.
{"Jabber ID","Jabber ID"}.
{"January","1月"}.
{"Jabber ID ~s is invalid","JID ~s は無効です"}.
{"joins the room","チャットルームに参加"}.
{"July","7月"}.
{"June","6月"}.
{"Last Activity","活動履歴"}.
{"Last login","最終ログイン"}.
{"Last month","先月"}.
{"Last year","去年"}.
{"leaves the room","チャットルームから退出"}.
{"Listened Ports at ","Listen ポート: "}.
{"Listened Ports","Listenポート"}.
{"List of modules to start","起動モジュールの一覧"}.
{"Low level update script","低レベル更新スクリプト"}.
{"Make participants list public","参加者一覧を公開します"}.
{"Make room members-only","チャットルームをメンバーのみに制限する"}.
{"Make room moderated","チャットルームをモデレートする"}.
{"Make room password protected","チャットルームにパスワードを設定します"}.
{"Make room persistent","チャットルームを永続化します"}.
{"Make room public searchable","チャットルームを検索可能にします"}.
{"March","3月"}.
{"Maximum Number of Occupants","最大移住者数"}.
{"Max # of items to persist","アイテムの最大保存数 #"}.
{"Max payload size in bytes","最大ぺイロードサイズ(byte)"}.
{"May","5月"}.
{"Members:","メンバー:"}.
{"Membership required to enter this room","チャットルームに入るにはメンバーでなければなりません"}.
{"Memory","メモリ"}.
{"Message body","本文"}.
{"Middle Name","ミドルネーム"}.
{"Moderator privileges required","モデレーター権限が必要です"}.
{"moderators only","モデレーターのみ"}.
{"Module","モジュール"}.
{"Modules","モジュール"}.
{"Modules at ","モジュール: "}.
{"Monday","月曜日"}.
{"Name","名"}.
{"Name:","名前: "}.
{"Never","無し"}.
{"Nickname","ニックネーム"}.
{"Nickname is already in use by another occupant","ニックネームは既に他の移住者によって使用されています"}.
{"Nickname is registered by another person","ニックネームは他の人によって登録されています"}.
{"Nickname Registration at ","ニックネーム登録: "}.
{"Nickname ~s does not exist in the room","ニックネーム ~s はこのチャットルームに居ません"}.
{"No body provided for announce message","アナウンスメッセージはありませんでした"}.
{"No Data","データ無し"}.
{"Node ","ノード"}.
{"Node ID","ノードID"}.
{"Node not found","ノードが見つかりません"}.
{"Nodes","ノード"}.
{"No limit","制限無し"}.
{"None","無し"}.
{"No resource provided","リソースが提供されませんでした"}.
{"Notify subscribers when items are removed from the node","アイテムがノードから消された時に購読者へ通知します"}.
{"Notify subscribers when the node configuration changes","ノード設定に変更があった時に購読者へ通知します"}.
{"Notify subscribers when the node is deleted","ノードが削除された時に購読者へ通知します"}.
{"November","11月"}.
{"Number of occupants","居住者の数"}.
{"Number of online users","オンラインユーザー数"}.
{"Number of registered users","登録ユーザー数"}.
{"October","10月"}.
{"Offline Messages:","オフラインメッセージ"}.
{"Offline Messages","オフラインメッセージ"}.
{"OK","OK"}.
{"Online","オンライン"}.
{"Online Users:","オンラインユーザー:"}.
{"Online Users","オンラインユーザー"}.
{"Only deliver notifications to available users","有効なユーザーにのみ告知を送信する"}.
{"Only moderators and participants are allowed to change subject in this room","モデレーターと参加者のみがチャットルームの件名を変更出来ます"}.
{"Only moderators are allowed to change subject in this room","モデレーターのみがチャットルームの件名を変更出来ます"}.
{"Only occupants are allowed to send messages to the conference","移住者のみがカンファレンスに"}.
{"Only occupants are allowed to send queries to the conference","移住者のみがカンファレンスにクエリーを送信出来ます"}.
{"Only service administrators are allowed to send service messages","カービス管理者のみがサービスメッセージを送信出来ます"}.
{"Options","オプション"}.
{"Organization Name","会社名"}.
{"Organization Unit","部署名"}.
{"Outgoing s2s Connections:","外向き s2s コネクション:"}.
{"Outgoing s2s Connections","外向き s2s コネクション"}.
{"Outgoing s2s Servers:","外向き s2s サービス:"}.
{"Owner privileges required","オーナー権限が必要です"}.
{"Packet","パケット"}.
{"Password:","パスワード"}.
{"Password","パスワード"}.
{"Password required to enter this room","チャットルームに入るにはパスワードが必要です"}.
{"Password Verification","パスワード(確認)"}.
{"Path to Dir","ディレクトリのパス"}.
{"Path to File","ファイルパス"}.
{"Pending","保留"}.
{"Period: ","期間: "}.
{"Persist items to storage","アイテムをストレージに保存する"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","ポート"}.
{"Present real Jabber IDs to","本当の JID を公開する"}.
{"private, ","プライベート"}.
{"Publish-Subscribe","Publish-Subscribe"}.
{"PubSub subscriber request","PubSub 購読リクエスト"}.
{"Queries to the conference members are not allowed in this room","このチャットルームではカンファレンスメンバーへのクエリーは禁止されています"}.
{"RAM and disc copy","RAM, ディスクコピー"}.
{"RAM copy","RAMコピー"}.
{"(Raw)","(Raw)"}.
{"Raw","Raw"}.
{"Really delete message of the day?","本当にお知らせメッセージを削除しますか？"}.
{"Recipient is not in the conference room","受信者がカンファレンスルームに居ません"}.
{"Registered Users:","登録ユーザー:"}.
{"Registered Users","登録ユーザー"}.
{"Registration in mod_irc for ","mod_irc での登録: "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","これらのオプションは組み込みの Mnesiaデーターベースをバックアップのみを行うことに注意して下さい。もしも ODBCモジュールを使用している場合は SQLデーターベースのバックアップを別に行う必要があります。"}.
{"Remote copy","リモートコピー"}.
{"Remove User","ユーザーの削除"}.
{"Remove","削除"}.
{"Replaced by new connection","新しいコネクションによって置き換えられました"}.
{"Resources","リソース"}.
{"Restart Service","サービスを再起動"}.
{"Restart","再起動"}.
{"Restore","リストア"}.
{"Restore Backup from File at ","ファイルからバックアップをリストア"}.
{"Restore binary backup after next ejabberd restart (requires less memory):","ejabberd の再起動時にバイナリバックアップからリストア"}.
{"Restore binary backup immediately:","直ちにバイナリバックアップからリストア"}.
{"Restore plain text backup immediately:","直ちにプレーンテキストバックアップからリストア"}.
{"Room Configuration","チャットルーム設定"}.
{"Room creation is denied by service policy","サービスポリシーにっよってチャットルームの作成が禁止されています"}.
{"Room title","チャットルームタイトル"}.
{"Roster groups allowed to subscribe","名簿グループは購読を許可しました"}.
{"Roster of ","名簿: "}.
{"Roster size","名簿サイズ"}.
{"Roster","名簿"}.
{"RPC Call Error","RPC 呼び出しエラー"}.
{"Running Nodes","起動ノード"}.
{"~s access rule configuration","~s アクセスルール設定"}.
{"Saturday","土曜日"}.
{"Script check","スクリプトチェック"}.
{"Search Results for ","検索結果: "}.
{"Search users in ","ユーザーの検索: "}.
{"Send announcement to all online users on all hosts","全ホストのオンラインユーザへアナウンスを送信"}.
{"Send announcement to all online users","アナウンスを全てのオンラインユーザーに送信"}.
{"Send announcement to all users on all hosts","アナウンスを全ホストのユーザーに送信"}.
{"Send announcement to all users","アナウンスを全てのユーザーに送信"}.
{"September","9月"}.
{"Set message of the day and send to online users","お知らせメッセージを設定し、オンラインユーザーに送信する"}.
{"Set message of the day on all hosts and send to online users","全ホストのお知らせメッセージを設定し、オンラインユーザーに送信する"}.
{"Shared Roster Groups","共有名簿グループ"}.
{"Show Integral Table","Integralテーブルを表示"}.
{"Show Ordinary Table","Ordinaryテーブルを表示"}.
{"Shut Down Service","サービスを停止"}.
{"~s invites you to the room ~s","~s はあなたをチャットルーム ~s に招待しています"}.
{"Size","サイズ"}.
{"Specified nickname is already registered","指定されたニックネームは既に登録されています"}.
{"Specify the access model","アクセスモデルを設定する"}.
{"Specify the publisher model","公開モデルを指定する"}.
{"~s's Offline Messages Queue","~s's オフラインメッセージキュー"}.
{"Start Modules at ","モジュールの開始"}.
{"Start Modules","モジュールの起動"}.
{"Start","開始"}.
{"Statistics of ~p","~p の統計"}.
{"Statistics","統計"}.
{"Stop Modules at ","モジュールの停止 "}.
{"Stop Modules","モジュールの停止"}.
{"Stopped Nodes","停止ノード"}.
{"Stop","停止"}.
{"Storage Type","ストレージタイプ"}.
{"Store binary backup:","バイナリバックアップの保存"}.
{"Store plain text backup:","プレーンテキストバックアップの保存"}.
{"Subject","件名"}.
{"Submitted","送信完了"}.
{"Submit","送信"}.
{"Subscriber Address","購読アドレス"}.
{"Subscription","認可"}.
{"Sunday","日曜日"}.
{"the password is","パスワードは"}.
{"This participant is kicked from the room because he sent an error message to another participant","他の参加者にエラーメッセージを送信したため、この参加者はキックされました"}.
{"This participant is kicked from the room because he sent an error message","エラーメッセージを送信したため、この参加者はキックされました"}.
{"This participant is kicked from the room because he sent an error presence","エラープレゼンスを送信したため、この参加者はキックされました"}.
{"This room is not anonymous","このチャットルームは非匿名です"}.
{"Thursday","木曜日"}.
{"Time delay","遅延時間"}.
{"Time","時間"}.
{"To ~s","宛先 ~s"}.
{"To","宛先"}.
{"Traffic rate limit is exceeded","トラフィックレートの制限を超えました"}.
{"Transactions Aborted:","トランザクションの失敗:"}.
{"Transactions Committed:","トランザクションのコミット:"}.
{"Transactions Logged:","トランザクションのログ: "}.
{"Transactions Restarted:","トランザクションの再起動:"}.
{"Tuesday","火曜日"}.
{"Updated modules","モジュールを更新しました"}.
{"Update message of the day (don't send)","お知らせメッセージを更新する(送信しない)"}.
{"Update message of the day on all hosts (don't send)","全ホストのお知らせメッセージを更新する"}.
{"Update plan","更新計画"}.
{"Update script","スクリプトの更新"}.
{"Update ","更新 "}.
{"Update","更新"}.
{"Uptime:","起動時間"}.
{"Use of STARTTLS required","STARTTLS を使用"}.
{"User ","ユーザー "}.
{"User","ユーザー"}.
{"User Management","ユーザー管理"}.
{"Users","ユーザー"}.
{"Users are not allowed to register accounts so fast","早すぎるユーザーアカウント登録は許可されませんでした"}.
{"Users Last Activity","ユーザーの活動履歴"}.
{"Validate","検証"}.
{"vCard User Search","vCard ユーザー検索"}.
{"Virtual Hosts","ヴァーチャルホスト"}.
{"Visitors are not allowed to change their nicknames in this room","ビジターはこのチャットルームでニックネームを変更することは許可されていません"}.
{"Visitors are not allowed to send messages to all occupants","ビジターが移住者ににメッセージを送ることは許可されていません"}.
{"Wednesday","水曜日"}.
{"When to send the last published item","最後の公開アイテムを送信するタイミングで"}.
{"Whether to allow subscriptions","購読を許可するかどうか"}.
{"You have been banned from this room","あなたはチャットルームからバンされています"}.
{"You must fill in field \"Nickname\" in the form","フォームの\"ニックネーム\"フィールドを入力する必要があります"}.
{"You need an x:data capable client to configure mod_irc settings","mod_irc の設定にはクライアントが x:data をサポートする必要があります"}.
{"You need an x:data capable client to configure room","チャットルームを設定するにはにはクライアントが x:data をサポートする必要があります"}.
{"You need an x:data capable client to register nickname","ニックネームを登録するにはクライアントが x:data をサポートする必要があります"}.
{"You need an x:data capable client to search","検索を行うためにはクライアントが x:data をサポートする必要があります"}.
{"Your contact offline message queue is full. The message has been discarded.","宛先のオフラインメッセージキューが一杯です。このメッセージは破棄されます。"}.
