% $Id$
% Language: Japanese (日本語)
% Author: Tsukasa Hamano

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "宛先のオフラインメッセージキューが一杯です。このメッセージは破棄されます。"}.
{"~s's Offline Messages Queue", "~s's オフラインメッセージキュー"}.
{"Submitted", "送信完了"}.
{"Packet", "パケット"}.
{"Delete Selected", "選択した項目を削除"}.
{"Offline Messages:", "オフラインメッセージ"}.

% mod_vcard_ldap.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"You need an x:data capable client to search", "検索を行うためにはクライアントが x:data をサポートする必要があります"}.
{"Search users in ", "ユーザーの検索: "}.
{"Fill in fields to search for any matching Jabber User", "項目を埋めて Jabber User を検索して下さい"}.
{"vCard User Search", "vCard ユーザー検索"}.
{"ejabberd vCard module", "ejabberd vCard module"}.
{"Search Results for ", "検索結果: "}.
{"Jabber ID", "Jabber ID"}.

% mod_vcard.erl
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "フォームを埋めて Jabber User を検索して下さい(* を使用すると部分文字列にマッチします)"}.
{"User", "ユーザー"}.
{"Full Name", "氏名"}.
{"Name", "名"}.
{"Middle Name", "ミドルネーム"}.
{"Family Name", "姓"}.
{"Nickname", "ニックネーム"}.
{"Birthday", "誕生日"}.
{"Country", "国"}.
{"City", "都道府県"}.
{"Email", "メールアドレス"}.
{"Organization Name", "会社名"}.
{"Organization Unit", "部署名"}.

% mod_configure.erl
{"Action on user", "ユーザー操作"}.
{"Configuration", "設定"}.
{"Database", "データーベース"}.
{"Start Modules", "モジュールの起動"}.
{"Stop Modules", "モジュールの停止"}.
{"Backup", "バックアップ"}.
{"Restore", "リストア"}.
{"Dump to Text File", "テキストファイルに出力"}.
{"Import File", "ファイルかインポート"}.
{"Import Directory", "ディレクトリインポート"}.
{"Restart Service", "サービスを再起動"}.
{"Shut Down Service", "サービスを停止"}.
{"Add User", "ユーザーを追加"}.
{"Delete User", "ユーザを削除"}.
{"End User Session", "エンドユーザーセッション"}.
{"Get User Password", "パスワードを取得"}.
{"Change User Password", "パスワードを変更"}.
{"Get User Last Login Time", "最終ログイン時間の取得"}.
{"Get User Statistics", "ユーザー統計の取得"}.
{"Get Number of Registered Users", "登録ユーザー数を取得"}.
{"Get Number of Online Users", "登録ユーザーを取得"}.
{"Access Control Lists", "アクセスコントロールリスト"}.
{"Access Rules", "アクセスルール"}.
{"User Management", "ユーザー管理"}.
{"Online Users", "オンラインユーザー"}.
{"All Users", "全ユーザー"}.
{"Outgoing s2s Connections", "外向き s2s コネクション"}.
{"Running Nodes", "起動ノード"}.
{"Stopped Nodes", "停止ノード"}.
{"Modules", "モジュール"}.
{"Backup Management", "バックアップ管理"}.
{"Import Users From jabberd 1.4 Spool Files", "jabberd 1.4 Spool ファイルからユーザーをインポート"}.
{"To ~s", "宛先 ~s"}.
{"From ~s", "差出人 ~s"}.
{"Database Tables Configuration at ", "データーベーステーブル設定 "}.
{"Choose storage type of tables", "テーブルのストレージタイプの選択"}.
{"RAM copy", "RAMコピー"}.
{"RAM and disc copy", "RAM, ディスクコピー"}.
{"Disc only copy", "ディスクだけのコピー"}.
{"Remote copy", "リモートコピー"}.
{"Stop Modules at ", "モジュールの停止 "}.
{"Choose modules to stop", "停止するモジュールの選択"}.
{"Start Modules at ", "モジュールの開始"}.
{"Enter list of {Module, [Options]}", "{モジュール, [オプション]}のリストを入力して下さい"}.
{"List of modules to start", "起動モジュールの一覧"}.
{"Backup to File at ", "ファイルにバックアップ"}.
{"Enter path to backup file", "バックアップファイルのパスを入力して下さい"}.
{"Path to File", "ファイルパス"}.
{"Restore Backup from File at ", "ファイルからバックアップをリストア"}.
{"Dump Backup to Text File at ", "テキストファイルにバックアップ"}.
{"Enter path to text file", "テキストファイルのパスを入力して下さい"}.
{"Import User from File at ", "ファイルからユーザーをインポート"}.
{"Enter path to jabberd1.4 spool file", "jabberd1.4 spool ファイルのパスを入力して下さい"}.
{"Import Users from Dir at ", "ディレクトリからユーザーをインポート"}.
{"Enter path to jabberd1.4 spool dir", "jabberd1.4 spool ディレクトリのパスを入力して下さい"}.
{"Path to Dir", "ディレクトリのパス"}.
{"Time delay", "遅延時間"}.
{"Send announcement to all online users on all hosts", "全ホストのオンラインユーザへアナウンスを送信"}.
{"Subject", "件名"}.
{"Message body", "本文"}.
{"Access Control List Configuration", "アクセスコントロールリスト設定"}.
{"Access control lists", "アクセスコントロールリスト"}.
{"Access Configuration", "アクセス設定"}.
{"Access rules", "アクセスルール"}.
{"Password", "パスワード"}.
{"Password Verification", "パスワード(確認)"}.
{"Number of registered users", "登録ユーザー数"}.
{"Number of online users", "オンラインユーザー数"}.
{"Never", "無し"}.
{"Online", "オンライン"}.
{"Last login", "最終ログイン"}.
{"Roster size", "名簿サイズ"}.
{"IP addresses", "IPアドレス"}.
{"Resources", "リソース"}.
{"Administration of ", "管理: "}.
{"Edit Properties", "プロパティの編集"}.
{"Remove User", "ユーザーの削除"}.

% mod_roster_odbc.erl
{"None", "無し"}.
{"Subscription", "認可"}.
{"Pending", "保留"}.
{"Groups", "グループ"}.
{"Validate", "検証"}.
{"Remove", "削除"}.
{"Roster of ", "名簿: "}.
{"Bad format", "不正なフォーマット"}.
{"Add Jabber ID", "Jabber ID の追加"}.
{"Roster", "名簿"}.

% mod_offline.erl
{"Time", "時間"}.
{"From", "差出人"}.
{"To", "宛先"}.

% mod_register.erl
{"Users are not allowed to register accounts so fast", "早すぎるユーザーアカウント登録は許可されませんでした"}.
{"Choose a username and password to register with this server", "サーバーに登録するユーザー名とパスワードを選択して下さい"}.

% ejabberd_c2s.erl
{"Replaced by new connection", "新しいコネクションによって置き換えられました"}.
{"Use of STARTTLS required", "STARTTLS を使用"}.
{"No resource provided", "リソースが提供されませんでした"}.

% mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "は提携が変更されたためキックされました"}.
{"has been kicked because the room has been changed to members-only", "はチャットルームのメンバー制限によりキックされました"}.
{"has been kicked because of a system shutdown", "はシステムシャットダウンのためキックされました"}.
{"Chatroom configuration modified", "チャットルームの設定を変更しました"}.
{"joins the room", "チャットルームに参加"}.
{"leaves the room", "チャットルームから退出"}.
{"has been kicked", "はキックされました"}.
{"has been banned", "はバンされました"}.
{" has set the subject to: ", " は件名を設定しました: "}.
{"Monday", "月曜日"}.
{"Tuesday", "火曜日"}.
{"Wednesday", "水曜日"}.
{"Thursday", "木曜日"}.
{"Friday", "金曜日"}.
{"Saturday", "土曜日"}.
{"Sunday", "日曜日"}.
{"January", "1月"}.
{"February", "2月"}.
{"March", "3月"}.
{"April", "4月"}.
{"May", "5月"}.
{"June", "6月"}.
{"July", "7月"}.
{"August", "8月"}.
{"September", "9月"}.
{"October", "10月"}.
{"November", "11月"}.
{"December", "12月"}.
{"Room Configuration", "チャットルーム設定"}.
{"Room title", "チャットルームタイトル"}.
{"is now known as", "は名前を変更しました: "}.

% mod_muc/mod_muc.erl
{"Access denied by service policy", "サービスポリシーによってアクセスが禁止されました"}.
{"Only service administrators are allowed to send service messages", "カービス管理者のみがサービスメッセージを送信出来ます"}.
{"Room creation is denied by service policy", "サービスポリシーにっよってチャットルームの作成が禁止されています"}.
{"Conference room does not exist", "カンファレンスルームは存在しません"}.
{"Chatrooms", "チャットルーム"}.
{"You need an x:data capable client to register nickname", "ニックネームを登録するにはクライアントが x:data をサポートする必要があります"}.
{"Nickname Registration at ", "ニックネーム登録: "}.
{"Enter nickname you want to register", "登録するニックネームを入力して下さい"}.
{"Specified nickname is already registered", "指定されたニックネームは既に登録されています"}.
{"You must fill in field \"Nickname\" in the form", "フォームの\"ニックネーム\"フィールドを入力する必要があります"}.
{"ejabberd MUC module", "ejabberd MUC module"}.

% mod_muc/mod_muc_room.erl
{"This participant is kicked from the room because he sent an error message", "エラーメッセージを送信したため、この参加者はキックされました"}.
{"This participant is kicked from the room because he sent an error message to another participant", "他の参加者にエラーメッセージを送信したため、この参加者はキックされました"}.
{"It is not allowed to send private messages", "プライベートメッセージを送信することは許可されませんでした"}.
{"This participant is kicked from the room because he sent an error presence", "エラープレゼンスを送信したため、この参加者はキックされました"}.
{"Visitors are not allowed to change their nicknames in this room", "ビジターはこのチャットルームでニックネームを変更することは許可されていません"}.
{"Make room moderated", "チャットルームをモデレートする"}.
{"Allow visitors to send status text in presence updates", "ビジターがプレゼンス更新のステータス文を送信する事を許可する"}.
{"Allow visitors to change nickname", "ビジターがニックネームを変更する事を許可します"}.
{"It is not allowed to send private messages of type \"groupchat\"", "種別が\"groupchat\" であるプライベートメッセージは許可されていません"}.
{"Invalid affiliation: ~s", "無効な提携です: ~s"}.
{"Invalid role: ~s", "無効なロールです: ~s"}.
{"Owner privileges required", "オーナー権限が必要です"}.
{"Configuration for ", "設定: "}.
{"Make room persistent", "チャットルームを永続化します"}.
{"Make room public searchable", "チャットルームを検索可能にします"}.
{"Make participants list public", "参加者一覧を公開します"}.
{"Make room password protected", "チャットルームにパスワードを設定します"}.
{"Maximum Number of Occupants", "最大移住者数"}.
{"No limit", "制限無し"}.
{"Present real JIDs to", "本当の JID を公開する"}.
{"moderators only", "モデレーターのみ"}.
{"anyone", "誰でも"}.
{"Make room members-only", "チャットルームをメンバーのみに制限する"}.
{"Default users as participants", "デフォルトのユーザーは参加者にする"}.
{"Allow users to change subject", "ユーザーによる件名の変更を許可する"}.
{"Allow users to send private messages", "ユーザーによるプライベートメッセージの送信を許可する"}.
{"Allow users to query other users", "ユーザーによる他のユーザーへの問い合わせを許可する"}.
{"Allow users to send invites", "ユーザーによる招待を許可する"}.
{"Enable logging", "ロギングを有効にする"}.
{"Number of occupants", "居住者の数"}.
{"~s invites you to the room ~s", "~s はあなたをチャットルーム ~s に招待しています"}.
{"the password is", "パスワードは"}.
{"Traffic rate limit is exceeded", "トラフィックレートの制限を超えました"}.
{"It is not allowed to send private messages to the conference", "カンファレンスルームにプライベートメッセージを送信することは出来ません"}.
{"Improper message type", "誤ったメッセージタイプです"}.
{"Only occupants are allowed to send messages to the conference", "移住者のみがカンファレンスに"}.
{"Recipient is not in the conference room", "受信者がカンファレンスルームに居ません"}.
{"Only occupants are allowed to send queries to the conference", "移住者のみがカンファレンスにクエリーを送信出来ます"}.
{"Queries to the conference members are not allowed in this room", "このチャットルームではカンファレンスメンバーへのクエリーは禁止されています"}.
{"private, ", "プライベート"}.
{"Only moderators and participants are allowed to change subject in this room", "モデレーターと参加者のみがチャットルームの件名を変更出来ます"}.
{"Only moderators are allowed to change subject in this room", "モデレーターのみがチャットルームの件名を変更出来ます"}.
{"Visitors are not allowed to send messages to all occupants", "ビジターが移住者ににメッセージを送ることは許可されていません"}.
{"Nickname is already in use by another occupant", "ニックネームは既に他の移住者によって使用されています"}.
{"Nickname is registered by another person", "ニックネームは他の人によって登録されています"}.
{"You have been banned from this room", "あなたはチャットルームからバンされています"}.
{"Membership required to enter this room", "チャットルームに入るにはメンバーでなければなりません"}.
{"This room is not anonymous", "このチャットルームは非匿名です"}.
{"Password required to enter this room", "チャットルームに入るにはパスワードが必要です"}.
{"Incorrect password", "パスワードが違います"}.
{"Administrator privileges required", "管理者権限が必要です"}.
{"Moderator privileges required", "モデレーター権限が必要です"}.
{"JID ~s is invalid", "JID ~s は無効です"}.
{"Nickname ~s does not exist in the room", "ニックネーム ~s はこのチャットルームに居ません"}.
{"You need an x:data capable client to configure room", "チャットルームを設定するにはにはクライアントが x:data をサポートする必要があります"}.

% mod_irc/mod_irc.erl
{"Registration in mod_irc for ", "mod_irc での登録: "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "IRCサーバーに接続先する為のユーザー名と文字エンコーディングを入力して下さい"}.
{"IRC Username", "IRCユーザー名"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "別の文字エンコーディングを使用したい場合、'{\"irc server\", \"encoding\"}' という形式のリストを入力して下さい。デフォルトで \"~s\" を使用します"}.
{"IRC Transport", "IRC トランスポート"}.
{"ejabberd IRC module", "ejabberd IRC module"}.
{"You need an x:data capable client to configure mod_irc settings", "mod_irc の設定にはクライアントが x:data をサポートする必要があります"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "例: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "エンコーディング"}.

% mod_adhoc.erl
{"Commands", "コマンド"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Really delete message of the day?", "本当にお知らせメッセージを削除しますか？"}.
{"No body provided for announce message", "アナウンスメッセージはありませんでした"}.
{"Announcements", "アナウンス"}.
{"Set message of the day and send to online users", "お知らせメッセージを設定し、オンラインユーザーに送信する"}.
{"Set message of the day on all hosts and send to online users", "全ホストのお知らせメッセージを設定し、オンラインユーザーに送信する"}.
{"Update message of the day (don't send)", "お知らせメッセージを更新する(送信しない)"}.
{"Update message of the day on all hosts (don't send)", "全ホストのお知らせメッセージを更新する"}.
{"Delete message of the day", "お知らせメッセージを削除する"}.
{"Delete message of the day on all hosts", "全ホストのお知らせメッセージを削除する"}.
{"Send announcement to all users", "アナウンスを全てのユーザーに送信"}.
{"Send announcement to all users on all hosts", "アナウンスを全ホストのユーザーに送信"}.
{"Send announcement to all online users", "アナウンスを全てのオンラインユーザーに送信"}.

% mod_shared_roster.erl
{"Add New", "新規追加"}.
{"Shared Roster Groups", "共有名簿グループ"}.
{"Name:", "名前: "}.
{"Description:", "詳細:"}.
{"Members:", "メンバー:"}.
{"Displayed Groups:", "表示グループ"}.
{"Group ", "グループ"}.
{"Submit", "送信"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams module"}.

% mod_pubsub/mod_pubsub.erl
{"A friendly name for the node", "ノードの為のフレンドリネーム"}.
{"Roster groups allowed to subscribe", "名簿グループは購読を許可しました"}.
{"Publish-Subscribe", "Publish-Subscribe"}.
{"ejabberd Publish-Subscribe module", "ejabberd Publish-Subscribe module"}.
{"PubSub subscriber request", "PubSub 購読リクエスト"}.
{"Choose whether to approve this entity's subscription.", "このエントリを承認するかどうかを選択して下さい"}.
{"Node ID", "ノードID"}.
{"Subscriber Address", "購読アドレス"}.
{"Allow this JID to subscribe to this pubsub node?", "この JID をこの pubsubノードへ購読することを許可しますか？"}.
{"Deliver payloads with event notifications", "イベント通知と同時にペイロードを配送します"}.
{"Deliver event notifications", "イベント通知を配送します"}.
{"Notify subscribers when the node configuration changes", "ノード設定に変更があった時に購読者へ通知します"}.
{"Notify subscribers when the node is deleted", "ノードが削除された時に購読者へ通知します"}.
{"Notify subscribers when items are removed from the node", "アイテムがノードから消された時に購読者へ通知します"}.
{"Persist items to storage", "アイテムをストレージに保存する"}.
{"Max # of items to persist", "アイテムの最大保存数 #"}.
{"Whether to allow subscriptions", "購読を許可するかどうか"}.
{"Specify the access model", "アクセスモデルを設定する"}.
{"Specify the publisher model", "公開モデルを指定する"}.
{"Max payload size in bytes", "最大ぺイロードサイズ(byte)"}.
{"When to send the last published item", "最後の公開アイテムを送信するタイミングで"}.
{"Only deliver notifications to available users", "有効なユーザーにのみ告知を送信する"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "ejabberd Web 管理"}.
{"All activity", "全て"}.
{"Show Ordinary Table", "Ordinaryテーブルを表示"}.
{"Show Integral Table", "Integralテーブルを表示"}.
{"Administration", "管理"}.
{"Virtual Hosts", "ヴァーチャルホスト"}.
{"Nodes", "ノード"}.
{"Statistics", "統計"}.
{"Users", "ユーザー"}.
{"Last Activity", "活動履歴"}.
{"(Raw)", "(Raw)"}.
{"Raw", "Raw"}.
{"~s access rule configuration", "~s アクセスルール設定"}.
{"ejabberd virtual hosts", "ejabberd ヴァーチャルホスト"}.
{"Users Last Activity", "ユーザーの活動履歴"}.
{"Period: ", "期間: "}.
{"Last month", "先月"}.
{"Last year", "去年"}.
{"Node not found", "ノードが見つかりません"}.
{"Host", "ホスト"}.
{"Registered Users", "登録ユーザー"}.
{"Offline Messages", "オフラインメッセージ"}.
{"Registered Users:", "登録ユーザー:"}.
{"Online Users:", "オンラインユーザー:"}.
{"Outgoing s2s Connections:", "外向き s2s コネクション:"}.
{"Outgoing s2s Servers:", "外向き s2s サービス:"}.
{"Change Password", "パスワードの変更"}.
{"User ", "ユーザー "}.
{"Connected Resources:", "接続リソース:"}.
{"Password:", "パスワード"}.
{"No Data", "データ無し"}.
{"Node ", "ノード"}.
{"Listened Ports", "Listenポート"}.
{"Update", "更新"}.
{"Restart", "再起動"}.
{"Stop", "停止"}.
{"RPC Call Error", "RPC 呼び出しエラー"}.
{"Database Tables at ", "データーベーステーブル: "}.
{"Storage Type", "ストレージタイプ"}.
{"Size", "サイズ"}.
{"Memory", "メモリ"}.
{"Backup of ", "バックアップ: "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "これらのオプションは組み込みの Mnesiaデーターベースをバックアップのみを行うことに注意して下さい。もしも ODBCモジュールを使用している場合は SQLデーターベースのバックアップを別に行う必要があります。"}.
{"Store binary backup:", "バイナリバックアップの保存"}.
{"OK", "OK"}.
{"Restore binary backup immediately:", "直ちにバイナリバックアップからリストア"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "ejabberd の再起動時にバイナリバックアップからリストア"}.
{"Store plain text backup:", "プレーンテキストバックアップの保存"}.
{"Restore plain text backup immediately:", "直ちにプレーンテキストバックアップからリストア"}.
{"Listened Ports at ", "Listen ポート: "}.
{"Modules at ", "モジュール: "}.
{"Statistics of ~p", "~p の統計"}.
{"Uptime:", "起動時間"}.
{"CPU Time:", "CPU時間:"}.
{"Transactions Commited:", "トランザクションのコミット:"}.
{"Transactions Aborted:", "トランザクションの失敗:"}.
{"Transactions Restarted:", "トランザクションの再起動:"}.
{"Transactions Logged:", "トランザクションのログ: "}.
{"Update ", "更新 "}.
{"Update plan", "更新計画"}.
{"Updated modules", "モジュールを更新しました"}.
{"Update script", "スクリプトの更新"}.
{"Low level update script", "低レベル更新スクリプト"}.
{"Script check", "スクリプトチェック"}.
{"Port", "ポート"}.
{"Module", "モジュール"}.
{"Options", "オプション"}.
{"Delete", "削除"}.
{"Start", "開始"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
