% $Id$

% mod_configure.erl
{"DB Tables Configuration at ", "Databasetabellenconfiguratie op "}.
{"Choose storage type of tables", "Kies opslagmethode voor tabellen"}.
{"RAM copy", "Kopieer naar RAM"}.
{"RAM and disc copy", "RAM- en schijfkopie"}.
{"Disc only copy", "Enkel schijfkopie"}.
{"Remote copy", "Afstandskopie"}.
{"Stop Modules at ", "Stop modules op "}.
{"Choose modules to stop", "Selecteer de modules die u wilt stoppen"}.
{"Start Modules at ", "Start modules op "}.
{"Enter list of {Module, [Options]}", "Voer lijst met op te starten modules in in volgende vorm: {Module, [Opties]}"}.
{"List of modules to start", "Lijst met op te starten modules"}.
{"Backup to File at ", "Maak een backup naar een bestand op "}.
{"Enter path to backup file", "Voer pad naar backupbestand in"}.
{"Path to File", "Pad naar bestand"}.
{"Restore Backup from File at ", "Herstel backup vanaf bestand op "}.
{"Dump Backup to Text File at ", "Dump backup naar tekstbestand op "}.
{"Enter path to text file", "Voer pad naar tekstbestand in"}.
{"Import User from File at ", "Importeer gebruiker via bestand op "}.
{"Enter path to jabberd1.4 spool file", "Voer pad van jabberd1.4-spool-bestand in"}.
{"Import Users from Dir at ", "Importeer gebruikers vanaf directory op "}.
{"Enter path to jabberd1.4 spool dir", "Voer pad naar jabberd1.4-spool-directory in"}.
{"Path to Dir", "Pad naar directory"}.
{"Hostname Configuration", "Hostnaam configuratie"}.
{"Choose host name", "Kies hostnaam"}.
{"Host name", "Hostnaam"}.
{"Access Control List Configuration", "Access Control List Configuratie"}.
{"Access control lists", "Access control lists"}.
{"Access Configuration", "Toegangsconfiguratie"}.
{"Access rules", "Access rules"}.
{"Remove Users", "Verwijder gebruikers"}.
{"Choose users to remove", "Selecteer de gebruikers die u wilt verwijderen"}.
{"Administration of ", "Beheer van "}.
{"Action on user", "Actie op gebruiker"}.
{"Edit Properties", "Bewerk eigenschappen"}.
{"Remove User", "Verwijder gebruiker"}.

% mod_disco.erl
{"Configuration", "Configuratie"}.
{"Online Users", "Online gebruikers"}.
{"All Users", "Alle gebruikers"}.
{"Outgoing S2S connections", "Uitgaande S2S connecties"}.
{"To ~s", "Naar ~s"}.
{"From ~s", "Van ~s"}.
{"Running Nodes", "Draaiende nodes"}.
{"Stopped Nodes", "Gestopte nodes"}.
{"Host Name", "Hostnaam"}.
{"Access Control Lists", "Access Control Lists"}.
{"Access Rules", "Access Rules"}.
{"Remove Users", "Verwijder gebruikers"}.
{"DB", "Database"}.
{"Modules", "Modules"}.
{"Start Modules", "Start modules"}.
{"Stop Modules", "Stop modules"}.
{"Backup Management", "Backupbeheer"}.
{"Import users from jabberd1.4 spool files", "Importeer jabberd1.4 gebruikers via spool-bestanden"}.
{"Backup", "Backup"}.
{"Restore", "Herstel backup"}.
{"Dump to Text File", "Dump naar tekstbestand"}.
{"Import File", "Importeer bestand"}.
{"Import Directory", "Importeer directory"}.

% mod_register.erl
{"Choose a username and password to register with this server",
 "Kies een gebruikersnaam en een wachtwoord om u te registreren op deze server"}.

% mod_vcard.erl
{"Erlang Jabber Server\nCopyright (c) 2002-2004 Alexey Shchepin",
 "Erlang Jabber Server\nCopyright (c) 2002-2004 Alexey Shchepin"}.
{"ejabberd vCard module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd vCard module\nCopyright (c) 2003-2004 Alexey Shchepin"}.
{"You need an x:data capable client to search",
 "U hebt een x:data compatibele client nodig om te kunnen zoeken"}.
{"Search users in ", "Zoek gebruikers in "}.
{"Fill in fields to search for any matching Jabber User",
 "Vul de velden in om te zoeken naar Jabbergebruikers op deze server"}.
{"Results of search in ", "Zoekresultaten van "}.

{"User",              "Gebruiker"}.
{"Full Name", 	      "Volledige naam"}.
{"Name", 	      "Voornaam"}.
{"Middle Name",       "Tussennaam"}.
{"Family Name",       "Achternaam"}.
{"Nickname", 	      "Bijnaam"}.
{"Birthday", 	      "Geboortedatum"}.
{"Country", 	      "Land"}.
{"City", 	      "Plaats"}.
{"email", 	      "E-mail"}.
{"Organization Name", "Organisatie"}.
{"Organization Unit", "Afdeling"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd pub/sub module\nCopyright (c) 2003-2004 Alexey Shchepin"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname",
 "U hebt een x:data compatibele client nodig om een bijnaam te kunnen registreren"}.
{"Nickname Registration at ", "Registratie van bijnaam op "}.
{"Enter nickname you want to register", "Voer de bijnaam in die u wilt registreren"}.
{"ejabberd MUC module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd MUC module\nCopyright (c) 2003-2004 Alexey Shchepin"}.
{"Only service administrators are allowed to send service messages",
 "Alleen service-beheerders hebben de toelating om service-berichten te versturen"}.
{"Room creation is not allowed by service policy",
 "Een kamer creëren is niet toegestaan door de service policy"}.
{"Conference room does not exist", "Conferentiekamer bestaat niet"}.
{"Access denied by service policy", "Toegang geweigerd door service policy"}.
{"You must fill in field \"nick\" in the form",
 "U moet het veld \"nick\" invullen in het formulier"}.
{"Specified nickname is already registered", "De gekozen bijnaam is al geregistreerd"}.

% mod_muc/mod_muc_room.erl
{" has set the subject to: ", " heeft het onderwerp ingesteld op: "}.
{"You need an x:data-capable client to configure room",
 "U hebt een x:data compatibele client nodig om een kamer te kunnen configureren"}.
{"Configuration for ", "Configuratie voor "}.
{"Room title", "Kamernaam"}.
{"Allow users to change subject?", "Gebruikers toestaan het onderwerp te wijzigen"}.
{"Allow users to query other users?",
 "Gebruikers toestaan om andere gebruikers te query-en"}.
{"Allow users to send private messages?",
 "Gebruikers toestaan om privéberichten te versturen"}.
{"Make room public searchable?", "Kamer doorzoekbaar maken"}.
{"Make participants list public?", "Deelnemerslijst publiek maken"}.
{"Make room persistent?", "Kamer blijvend maken"}.
{"Make room moderated?", "Kamer moderated maken"}.
{"Default users as members?",
 "Gebruikers standaard als leden instellen"}.
{"Make room members only?",
 "Kamer enkel toegankelijk maken voor leden"}.
{"Allow users to send invites?",
 "Gebruikers toestaan om uitnodigingen te sturen"}.
{"Make room password protected?", "Kamer beveiligen met een wachtwoord"}.
{"Password", "Wachtwoord"}.
{"Make room anonymous?", "Kamer anoniem maken"}.
{"Enable logging?", "Logs inschakelen"}.
{"Only moderators and participants are allowed to change subject in this room",
 "Alleen moderators en deelnemers hebben de toelating om het onderwerp in deze kamer te wijzigen"}.
{"Only moderators are allowed to change subject in this room",
 "Alleen moderators hebben de toelating om het onderwerp in deze kamer te wijzigen"}.
{"Visitors are not allowed to send messages to all occupants",
 "Bezoekers hebben geen toelating om berichten te sturen naar alle aanwezigen"}.
{"Only occupants are allowed to send messages to the conference",
 "Alleen aanwezigen zijn toegelaten om berichten naar de conferentie te sturen"}.
{"It is not allowed to send normal messages to the conference",
 "Het is niet toegelaten om normale berichten naar de kamer te sturen"}.
{"It is not allowed to send private messages to the conference",
 "Het is niet toegelaten om privéberichten naar de kamer te sturen"}.
{"Improper message type", "Onjuist berichttype"}.
{"Nickname is already in use by another occupant", "Bijnaam is al in gebruik door een andere aanwezige"}.
{"Nickname is registered by another person", "Bijnaam is al geregistreerd door iemand anders"}.
{"It is not allowed to send private messages of type \"groupchat\"",
 "Het is niet toegelaten om privéberichten van het type \"groupchat\" te versturen"}.
{"Recipient is not in the conference room", "Ontvanger is niet in conferentiekamer"}.
{"Only occupants are allowed to send queries to the conference",
 "Alleen aanwezeigen zijn toegelaten om verzoeken te zenden naar de conferentie"}.
{"Queries to the conference members are not allowed in this room",
 "Verzoeken aan de conferentieleden zijn niet toegelaten in deze kamer"}.
{"You have been banned from this room", "U bent verbannen uit deze kamer"}.
{"Membership required to enter this room", "Lidmaatschap vereist om deze kamer te kunnen betreden"}.
{"Password required to enter this room", "Wachtwoord vereist om deze kamer te kunnen betreden"}.
{"Incorrect password", "Foutief wachtwoord"}.
{"Administrator privileges required", "Beheerdersprivileges vereist"}.
{"Moderator privileges required", "Moderatorprivileges vereist"}.
{"JID ~s is invalid", "JID ~s is ongeldig"}.
{"Nickname ~s does not exist in the room", "Bijnaam ~s bestaat niet in de kamer"}.
{"Invalid affiliation: ~s", "Ongeldige aansluiting: ~s"}.
{"Invalid role: ~s", "Ongeldige rol: ~s"}.
{"Owner privileges required", "Eigenaarsprivileges vereist"}.
{"private, ", "privé, "}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd IRC module\nCopyright (c) 2003-2004 Alexey Shchepin"}.
{"You need an x:data capable client to configure mod_irc settings",
 "U hebt een x:data-compatibele client nodig om de instellingen van mod_irc te configureren"}.
{"Registration in mod_irc for ", "Registratie in mod_irc voor "}.
{"Enter username and encodings you wish to use for connecting to IRC servers",
 "Voer de gebruikersnaam en coderingen in die u wilt gebruiken voor de verbindingen met IRC servers"}.
{"IRC Username", "IRC gebruikersnaam"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Indien u verschillende coderingen wilt specificeren voor IRC servers, dan moet u in deze lijst waaren in het formaat: '{\"irc server\", \"encoding\"}'. Standaard gebruikt deze service codering \"~s\" invullen."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Voorbeeld: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Coderingen"}.

% web/ejabberd_web_admin.erl
{"Users", "Gebruikers"}.
{"Nodes", "Nodes"}.
{"Statistics", "Statistieken"}.
{"", ""}.
{"", ""}.

% Local Variables:
% mode: erlang
% End:
