% $Id$
% Language: Dutch (nederlands)
% Author: Andreas from Unstable.nl
% Author: Sander Devrieze

% mod_vcard_ldap.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"You need an x:data capable client to search", "U hebt een client nodig die x:data ondersteunt om te zoeken"}.
{"Search users in ", "Gebruikers zoeken in "}.
{"Fill in fields to search for any matching Jabber User", "Vul de velden in om te zoeken naar Jabber-gebruikers op deze server"}.
{"User", "Gebruiker"}.
{"Full Name", "Volledige naam"}.
{"Middle Name", "Tussennaam"}.
{"Family Name", "Achternaam"}.
{"Nickname", "Bijnaam"}.
{"Birthday", "Geboortedatum"}.
{"Country", "Land"}.
{"City", "Plaats"}.
{"Email", "E-mail"}.
{"Organization Name", "Organisatie"}.
{"Organization Unit", "Afdeling"}.
{"ejabberd vCard module", "ejabberd's vCard-module"}.
{"Search Results for ", "Zoekresultaten voor "}.
{"Jabber ID", "Jabber ID"}.

% mod_vcard.erl
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Gebruik de velden om te zoeken (Voeg achteraan het teken * toe om te zoeken naar alles wat met het eerste deel begint.)."}.
{"Name", "Naam"}.
% Probably needs to be "Given Name"

% mod_configure.erl
{"Configuration", "Instellingen"}.
{"Database", "Database"}.
{"Start Modules", "Modules starten"}.
{"Stop Modules", "Modules stoppen"}.
{"Backup", "Backup"}.
{"Restore", "Binaire backup direct herstellen"}.
{"Dump to Text File", "Backup naar een tekstbestand schrijven"}.
{"Import File", "Bestand importeren"}.
{"Import Directory", "Directory importeren"}.
{"Access Control Lists", "Access control lists"}.
{"Access Rules", "Access rules"}.
{"Online Users", "Online gebruikers"}.
{"All Users", "Alle gebruikers"}.
{"Outgoing s2s Connections", "Uitgaande s2s-verbindingen"}.
{"Running Nodes", "Draaiende nodes"}.
{"Stopped Nodes", "Gestopte nodes"}.
{"Modules", "Modules"}.
{"Backup Management", "Backup"}.
{"Import Users From jabberd 1.4 Spool Files", "Importeer gebruikers via spool-bestanden van jabberd 1.4"}.
{"To ~s", "Naar ~s"}.
{"From ~s", "Van ~s"}.
{"Database Tables Configuration at ", "Instellingen van databasetabellen op "}.
{"Choose storage type of tables", "Opslagmethode voor tabellen kiezen"}.
{"RAM copy", "RAM"}.
{"RAM and disc copy", "RAM en harde schijf"}.
{"Disc only copy", "Harde schijf"}.
{"Remote copy", "Op andere nodes in de cluster"}.
{"Stop Modules at ", "Modules stoppen op "}.
{"Choose modules to stop", "Selecteer de modules die u wilt stoppen"}.
{"Start Modules at ", "Modules starten op "}.
{"Enter list of {Module, [Options]}", "Voer lijst met op te starten modules als volgt in: {Module, [Opties]}"}.
{"List of modules to start", "Lijst met op te starten modules"}.
{"Backup to File at ", "Binaire backup maken op "}.
{"Enter path to backup file", "Voer pad naar backupbestand in"}.
{"Path to File", "Pad naar bestand"}.
{"Restore Backup from File at ", "Binaire backup direct herstellen op "}.
{"Dump Backup to Text File at ", "Backup naar een tekstbestand schrijven op "}.
{"Enter path to text file", "Voer pad naar backupbestand in"}.
{"Import User from File at ", "Importeer gebruiker via bestand op "}.
{"Enter path to jabberd1.4 spool file", "Voer pad naar jabberd 1.4-spool-bestand in"}.
{"Import Users from Dir at ", "Gebruikers importeren vanaf directory op "}.
{"Enter path to jabberd1.4 spool dir", "Voer pad naar jabberd 1.4-spool-directory in"}.
{"Path to Dir", "Pad naar directory"}.
{"Access Control List Configuration", "Instellingen van access control lists"}.
{"Access control lists", "Access control lists"}.
{"Access Configuration", "Toegangsinstellingen"}.
{"Access rules", "Access rules"}.
{"Administration of ", "Beheer van "}.
{"Action on user", "Actie op gebruiker"}.
{"Edit Properties", "Eigenschappen bewerken"}.
{"Remove User", "Gebruiker verwijderen"}.
{"Password", "Wachtwoord"}.
{"Restart Service", "Herstart Service"}.
{"Shut Down Service", "Stop Service"}.
{"Delete User", "Verwijder Gebruiker"}.
{"End User Session", "Verwijder Gebruikers-sessie"}.
{"Get User Password", "Gebruikerswachtwoord Opvragen"}.
{"Change User Password", "Verander Gebruikerswachtwoord"}.
{"Get User Last Login Time", "Tijd van Laatste Aanmelding Opvragen"}.
{"Get User Statistics", "Gebruikers-statistieken Opvragen"}.
{"Get Number of Registered Users", "Aantal Geregistreerde Gebruikers Opvragen"}.
{"Get Number of Online Users", "Aantal Aanwezige Gebruikers Opvragen"}.
{"User Management", "Gebruikersbeheer"}.
{"Time delay", "Vertraging"}.
{"Password Verification", "Wachtwoord Bevestiging"}.
{"Number of registered users", "Aantal Geregistreerde Gebruikers"}.
{"Number of online users", "Aantal Aanwezige Gebruikers"}.
{"Last login", "Laatste Aanmelding"}.
{"Roster size", "Contactlijst Groote"}.
{"IP addresses", "IP-adres"}.
{"Resources", "Bronnen"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Kies een gebruikersnaam en een wachtwoord om u te registreren op deze server"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Gebruik van STARTTLS is vereist"}.
{"No resource provided", "Geen bron opgegeven"}.
{"Replaced by new connection", "Vervangen door een nieuwe verbinding"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "De instellingen van de chatruimte werden veranderd"}.
{"joins the room", "betrad de chatruimte"}.
{"leaves the room", "verliet de chatruimte"}.
{"has been kicked", "werd gekicked"}.
{"has been banned", "werd verbannen"}.
{"is now known as", "heet nu"}.
{" has set the subject to: ", " veranderde het onderwerp in: "}.
{"Monday", "maandag"}.
{"Tuesday", "dinsdag"}.
{"Wednesday", "woensdag"}.
{"Thursday", "donderdag"}.
{"Friday", "vrijdag"}.
{"Saturday", "zaterdag"}.
{"Sunday", "zondag"}.
{"January", "januari"}.
{"February", "februari"}.
{"March", "maart"}.
{"April", "april"}.
{"May", "mei"}.
{"June", "juni"}.
{"July", "juli"}.
{"August", "augustus"}.
{"September", "september"}.
{"October", "oktober"}.
{"November", "november"}.
{"December", "december"}.
{"Room Configuration", "Instellingen van de chatruimte"}.
{"Room title", "Naam van de chatruimte"}.

% mod_muc/mod_muc.erl
{"Access denied by service policy", "De toegang werd geweigerd door het beleid van deze dienst"}.
{"Only service administrators are allowed to send service messages", "Alleen beheerders van deze dienst mogen mededelingen verzenden naar alle chatruimtes"}.
{"Room creation is denied by service policy", "De aanmaak van de chatruimte is verhinderd door de instellingen van deze server"}.
{"Conference room does not exist", "De chatruimte bestaat niet"}.
{"You need an x:data capable client to register nickname", "U hebt een client nodig die x:data ondersteunt om een bijnaam te registreren"}.
{"Nickname Registration at ", "Registratie van een bijnaam op "}.
{"Enter nickname you want to register", "Voer de bijnaam in die u wilt registreren"}.
{"Specified nickname is already registered", "De gekozen bijnaam is al geregistreerd"}.
{"You must fill in field \"Nickname\" in the form", "U moet het veld \"bijnaam\" invullen"}.
{"ejabberd MUC module", "ejabberd's MUC module"}.
{"Chatrooms", "Groepsgesprekken"}.

% mod_muc/mod_muc_room.erl
{"Make room moderated", "Chatruimte gemodereerd maken"}.
{"Only moderators and participants are allowed to change subject in this room", "Alleen moderators en deelnemers mogen het onderwerp van deze chatruimte veranderen"}.
{"Only moderators are allowed to change subject in this room", "Alleen moderators mogen het onderwerp van deze chatruimte veranderen"}.
{"Visitors are not allowed to send messages to all occupants", "Bezoekers mogen geen berichten verzenden naar alle aanwezigen"}.
{"It is not allowed to send private messages to the conference", "Er mogen geen privéberichten naar de chatruimte worden verzonden"}.
{"Improper message type", "Onjuist berichttype"}.
{"Only occupants are allowed to send messages to the conference", "Alleen aanwezigen mogen berichten naar de chatruimte verzenden"}.
{"Nickname is already in use by another occupant", "Deze bijnaam is al in gebruik door een andere aanwezige"}.
{"Nickname is registered by another person", "Deze bijnaam is al geregistreerd door iemand anders"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Er mogen geen privéberichten van het type \"groupchat\" worden verzonden"}.
{"Recipient is not in the conference room", "De ontvanger is niet in de chatruimte"}.
{"Only occupants are allowed to send queries to the conference", "Alleen aanwezigen mogen verzoeken verzenden naar de chatruimte"}.
{"Queries to the conference members are not allowed in this room", "Er mogen geen verzoeken verzenden worden naar deelnemers in deze chatruimte"}.
{"private, ", "privé, "}.
{"You have been banned from this room", "U werd verbannen uit deze chatruimte"}.
{"Membership required to enter this room", "U moet lid zijn om deze chatruimte te kunnen betreden"}.
{"This room is not anonymous", "Deze chatruimte is niet anoniem"}.
{"Password required to enter this room", "U hebt een wachtwoord nodig om deze chatruimte te kunnen betreden"}.
{"Incorrect password", "Foutief wachtwoord"}.
{"Administrator privileges required", "U hebt beheerdersprivileges nodig"}.
{"Moderator privileges required", "U hebt moderatorprivileges nodig"}.
{"JID ~s is invalid", "De Jabber ID ~s is ongeldig"}.
{"Nickname ~s does not exist in the room", "De bijnaam ~s bestaat niet in deze chatruimte"}.
{"Invalid affiliation: ~s", "Ongeldige affiliatie: ~s"}.
{"Invalid role: ~s", "Ongeldige rol: ~s"}.
{"Owner privileges required", "U hebt eigenaarsprivileges nodig"}.
{"Configuration for ", "Instellingen van "}.
{"Make room persistent", "Chatruimte blijvend maken"}.
{"Make room public searchable", "Chatruimte doorzoekbaar maken"}.
{"Make participants list public", "Deelnemerslijst publiek maken"}.
{"Make room password protected", "Chatruimte beveiligen met een wachtwoord"}.
{"Make room members-only", "Chatruimte enkel toegankelijk maken voor leden"}.
{"Default users as participants", "Gebruikers standaard instellen als deelnemers"}.
{"Allow users to change subject", "Gebruikers mogen het onderwerp veranderen"}.
{"Allow users to send private messages", "Gebruikers mogen privéberichten verzenden"}.
{"Allow users to query other users", "Gebruikers mogen naar andere gebruikers verzoeken verzenden"}.
{"Allow users to send invites", "Gebruikers mogen uitnodigingen verzenden"}.
{"Enable logging", "Logs aanzetten"}.
{"You need an x:data capable client to configure room", "U hebt een client nodig die x:data ondersteunt om deze chatruimte in te stellen"}.
{"Number of occupants", "Aantal aanwezigen"}.
{"Present real JIDs to", "Jabber ID's kunnen achterhaald worden door"}.
{"moderators only", "moderators"}.
{"anyone", "iedereen"}.
{"Traffic rate limit is exceeded", "Dataverkeerslimiet overschreden"}.
{"Maximum Number of Occupants", "Maximum aantal aanwezigen"}.
{"No limit", "Geen limiet"}.
{"~s invites you to the room ~s", "~s nodigt je uit voor het groepsgesprek ~s"}.
{"the password is", "het wachtwoord is"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "ejabberd's IRC-module"}.
{"You need an x:data capable client to configure mod_irc settings", "U hebt een client nodig die x:data ondersteunt om dit IRC-transport in te stellen"}.
{"Registration in mod_irc for ", "Registratie van "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Voer de gebruikersnaam en de coderingen in die u wilt gebruiken voor verbindingen met IRC-servers"}.
{"IRC Username", "Gebruikersnaam voor IRC:"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Als u verschillende coderingen wilt opgeven voor elke IRC-server, ga dan voor elke server te werk op als volgt: '{\"IRC-server\", \"codering\"}'. Standaard gebruikt dit IRC-transport de codering \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Voorbeeld: [{\"irc.example.org\", \"koi8-r\"}, {\"vendetta.example.net\", \"iso8859-1\"}]."}.
{"Encodings", "Coderingen:"}.
{"IRC Transport", "IRC Transport"}.

% mod_adhoc.erl
{"Commands", "Commando's"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Really delete message of the day?", "Wilt u het bericht van de dag verwijderen?"}.
{"Subject", "Onderwerp"}.
{"Message body", "Bericht"}.
{"No body provided for announce message", "De mededeling bevat geen bericht"}.
{"Announcements", "Mededelingen"}.
{"Send announcement to all users", "Mededeling verzenden naar alle gebruikers"}.
{"Send announcement to all online users", "Mededeling verzenden naar alle online gebruikers"}.
{"Send announcement to all online users on all hosts", "Mededeling verzenden naar alle online gebruikers op alle virtuele hosts"}.
{"Set message of the day and send to online users", "Bericht van de dag instellen en verzenden naar online gebruikers"}.
{"Update message of the day (don't send)", "Bericht van de dag bijwerken (niet verzenden)"}.
{"Delete message of the day", "Bericht van de dag verwijderen"}.
{"Send announcement to all users on all hosts", "Stuur aankondiging aan alle gebruikers op alle hosts"}.
{"Set message of the day on all hosts and send to online users", "Stel bericht-van-de-dag in op alle hosts en stuur naar aanwezige gebruikers"}.
{"Update message of the day on all hosts (don't send)", "Verander bericht-van-de-dag op alle hosts (niet versturen)"}.
{"Delete message of the day on all hosts", "Verwijder bericht-van-de-dag op alle hosts"}.

% mod_pubsub/mod_pubsub.erl
{"Deliver payloads with event notifications", "Berichten bezorgen samen met gebeurtenisnotificaties"}.
{"Notify subscribers when the node configuration changes", "Abonnees informeren wanneer de instellingen van de node veranderen"}.
{"Notify subscribers when the node is deleted", "Abonnees informeren wanneer de node verwijderd word"}.
{"Notify subscribers when items are removed from the node", "Abonnees informeren wanneer items verwijderd worden uit de node"}.
{"Persist items to storage", "Items in het geheugen bewaren"}.
{"Max # of items to persist", "Maximum aantal in het geheugen te bewaren items"}.
{"Whether to allow subscriptions", "Abonnementsaanvraag toestaan"}.
{"Specify the publisher model", "Publicatietype opgeven"}.
{"Max payload size in bytes", "Maximumgrootte van bericht in bytes"}.
{"Only deliver notifications to available users", "Notificaties alleen verzenden naar online gebruikers"}.
{"Publish-Subscribe", "Publish-Subscribe"}.
{"ejabberd Publish-Subscribe module", "ejabberd Publish-Subscribe module"}.
{"PubSub subscriber request", "PubSub abonnee verzoek"}.
{"Choose whether to approve this entity's subscription.", "Beslis of dit verzoek tot abonneren zal worden goedgekeurd"}.
{"Node ID", "Node ID"}.
{"Subscriber Address", "Abonnee Adres"}.
{"Allow this JID to subscribe to this pubsub node?", "Deze gebruiker toestaan te abonneren op deze pubsub node?"}.
{"Deliver event notifications", "Gebeurtenisbevestigingen Sturen"}.
{"Specify the access model", "Geef toegangsmodel"}.
{"Roster groups that may subscribe (if access model is roster)", "Contactlijst groepen die kunnen abonneren (als contactlijst het toegangsmodel is)"}.
{"When to send the last published item", "Wanneer het laatst gepubliceerde item verzonden moet worden"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Interface", "ejabberd's webinterface"}.
{"Administration", "Beheer"}.
{"Virtual Hosts", "Virtuele hosts"}.
{"Nodes", "Nodes"}.
{"Statistics", "Statistieken"}.
{"ejabberd (c) 2002-2008 Alexey Shchepin, 2004-2008 Process One", "ejabberd (c) 2002-2008 Alexey Shchepin, 2004-2008 Process One"}.
{"Users", "Gebruikers"}.
{"Last Activity", "Laatste activiteit"}.
{"(Raw)", "(Ruw)"}.
{"Submitted", "Verzonden"}.
{"Bad format", "Slecht formaat"}.
{"Submit", "Verzenden"}.
{"Raw", "Ruw"}.
{"Delete Selected", "Geselecteerde verwijderen"}.
{"~s access rule configuration", "Access rules op ~s"}.
{"ejabberd virtual hosts", "Virtuele hosts"}.
{"Users Last Activity", "Laatste activiteit van gebruikers"}.
{"Period: ", "Periode: "}.
{"Last month", "Afgelopen maand"}.
{"Last year", "Afgelopen jaar"}.
{"All activity", "Alle activiteit"}.
{"Show Ordinary Table", "Deel van tabel laten zien"}.
{"Show Integral Table", "Volledige tabel laten zien"}.
{"Node not found", "Node niet gevonden"}.
{"Add New", "Toevoegen"}.
{"Host", "Host"}.
{"Registered Users", "Geregistreerde gebruikers"}.
{"Add User", "Gebruiker toevoegen"}.
{"Offline Messages", "Offline berichten"}.
{"Never", "Nooit"}.
{"Online", "Online"}.
{"Registered Users:", "Geregistreerde gebruikers:"}.
{"Online Users:", "Online gebruikers:"}.
{"Outgoing s2s Connections:", "Uitgaande s2s-verbindingen:"}.
{"Outgoing s2s Servers:", "Uitgaande s2s-verbindingen:"}.
{"None", "Geen"}.
{"Change Password", "Wachtwoord wijzigen"}.
{"User ", "Gebruiker "}.
{"Connected Resources:", "Verbonden bronnen:"}.
{"Password:", "Wachtwoord:"}.
{"Offline Messages:", "Offline berichten:"}.
{"Roster", "Roster"}.
{"~s's Offline Messages Queue", "offline berichten van ~s"}.
{"Time", "Tijd"}.
{"From", "Van"}.
{"To", "Aan"}.
{"Packet", "Pakket"}.
{"Subscription", "Inschrijving"}.
{"Pending", "Bezig"}.
{"Groups", "Groepen"}.
{"Validate", "Bevestigen"}.
{"Remove", "Verwijderen"}.
{"Roster of ", "Roster van "}.
{"Add Jabber ID", "Jabber ID toevoegen"}.
{"No Data", "Geen gegevens"}.
{"Node ", "Node "}.
{"Listened Ports", "Openstaande poorten"}.
{"Update", "Bijwerken"}.
{"Restart", "Herstarten"}.
{"Stop", "Stoppen"}.
{"RPC Call Error", "RPC-oproepfout"}.
{"Database Tables at ", "Databasetabellen van "}.
{"Storage Type", "Opslagmethode"}.
{"Size", "Grootte"}.
{"Memory", "Geheugen"}.
{"Backup of ", "Backup maken van "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Merk op dat volgende opties enkel backups maken van de ingebouwde database Mnesia. Als u (een) andere database(s) gebruikt dan moet u daarvan (een) afzonderlijke backup(s) maken."}.
{"Store binary backup:", "Binaire backup maken:"}.
{"OK", "OK"}.
{"Restore binary backup immediately:", "Binaire backup direct herstellen:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Binaire backup herstellen na herstart van ejabberd (vereist minder geheugen):"}.
{"Store plain text backup:", "Backup naar een tekstbestand schrijven:"}.
{"Restore plain text backup immediately:", "Backup in een tekstbestand direct herstellen:"}.
{"Listened Ports at ", "Openstaande poorten op "}.
{"Modules at ", "Modules op "}.
{"Statistics of ~p", "Statistieken van ~p"}.
{"Uptime:", "Uptime:"}.
{"CPU Time:", "Processortijd:"}.
{"Transactions Commited:", "Bevestigde transacties:"}.
{"Transactions Aborted:", "Afgebroken transacties:"}.
{"Transactions Restarted:", "Herstarte transacties:"}.
{"Transactions Logged:", "Gelogde transacties:"}.
{"Update ", "Opwaarderen van "}.
{"Update plan", "Plan voor de opwaardering"}.
{"Updated modules", "Modules opwaarderen"}.
{"Update script", "Script voor de opwaardering"}.
{"Low level update script", "Lowlevel script voor de opwaardering"}.
{"Script check", "Controle van script"}.
{"Port", "Poort"}.
{"Module", "Module"}.
{"Options", "Opties"}.
{"Delete", "Verwijderen"}.
{"Start", "Starten"}.
{"Shared Roster Groups", "Gedeelde rostergroepen"}.
{"Name:", "Naam:"}.
{"Description:", "Beschrijving:"}.
{"Members:", "Groepsleden:"}.
{"Displayed Groups:", "Weergegeven groepen:"}.
{"Group ", "Groep "}.

% mod_vcard_odbc.erl
{"vCard User Search", "Gebruikers zoeken"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Te veel offline berichten voor dit contactpersoon. Het bericht is niet opgeslagen."}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams module"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
