% $Id$
% Language: Norwegian (bokmål)
% Author: Stian B. Barmen

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Bruk av STARTTLS kreves"}.
{"Replaced by new connection", "Erstattet av en ny tilkobling"}.

% jlib.hrl
{"No resource provided", "Ingen ressurs angitt"}.

% mod_configure.erl
{"Database", "Database"}.
{"Restart Service", "Start Tjeneste på Nytt"}.
{"Shut Down Service", "Avslutt Tjeneste"}.
{"Delete User", "Slett Bruker"}.
{"End User Session", "Avslutt Bruker Sesjon"}.
{"Get User Password", "Hent Brukers Passord"}.
{"Change User Password", "Endre Brukers Passord"}.
{"Get User Last Login Time", "Vis Brukers Siste Påloggings Tidspunkt"}.
{"Get User Statistics", "Vis Bruker Statistikk"}.
{"Get Number of Registered Users", "Vis Antall Registrerte Brukere"}.
{"Get Number of Online Users", "Vis Antall Tilkoblede Brukere"}.
{"User Management", "Bruker Behandling"}.
{"Outgoing s2s Connections", "Utgående s2s Koblinger"}.
{"Import Users From jabberd 1.4 Spool Files", "Importer Brukere Fra jabberd 1.4 Spoolfiler"}.
{"Database Tables Configuration at ", "Database Tabell Konfigurasjon på "}.
{"Time delay", "Tids forsinkelse"}.
{"Password Verification", "Passord Bekreftelse"}.
{"Number of registered users", "Antall registrerte brukere"}.
{"Number of online users", "Antall tilkoblede brukere"}.
{"Last login", "Siste pålogging"}.
{"Roster size", "Kontaktliste størrelse"}.
{"IP addresses", "IP adresser"}.
{"Resources", "Ressurser"}.
{"Choose storage type of tables", "Velg lagringstype for tabeller"}.
{"RAM copy", "RAM kopi"}.
{"RAM and disc copy", "RAM og diskkopi"}.
{"Disc only copy", "Kun diskkopi"}.
{"Remote copy", "Lagres ikke lokalt"}.
{"Stop Modules at ", "Stopp Moduler på "}.
{"Choose modules to stop", "Velg hvilke moduler som skal stoppes"}.
{"Start Modules at ", "Start Moduler på "}.
{"Enter list of {Module, [Options]}", "Skriv inn en liste av {Module, [Options]}"}.
{"List of modules to start", "Liste over moduler som skal startes"}.
{"Backup to File at ", "Sikkerhetskopiere til Fil på "}.
{"Enter path to backup file", "Skriv inn sti til sikkerhetskopi filen"}.
{"Path to File", "Sti til Fil"}.
{"Restore Backup from File at ", "Gjenopprett fra Sikkerhetsopifil på "}.
{"Dump Backup to Text File at ", "Dump Sikkerhetskopi til Tekstfil på "}.
{"Enter path to text file", "Skriv inn sti til tekstfil"}.
{"Import User from File at ", "Importer Bruker fra Fil på "}.
{"Enter path to jabberd1.4 spool file", "Skriv inn sti til jabberd1.4 spoolfil"}.
{"Import Users from Dir at ", "Importer Brukere fra Katalog på "}.
{"Enter path to jabberd1.4 spool dir", "Skriv inn sti til jabberd1.4 spoolkatalog"}.
{"Path to Dir", "Sti til Katalog"}.
{"Access Control List Configuration", "Konfigurasjon for Tilgangskontroll lister"}.
{"Access control lists", "Tilgangskontroll lister"}.
{"Access Configuration", "Tilgangskonfigurasjon"}.
{"Access rules", "Tilgangsregler"}.
{"Administration of ", "Administrasjon av "}.
{"Action on user", "Handling på bruker"}.
{"Edit Properties", "Redigere Egenskaper"}.
{"Remove User", "Fjern Bruker"}.

% mod_disco.erl
{"Configuration", "Konfigurasjon"}.
{"Online Users", "Tilkoblede Brukere"}.
{"All Users", "Alle Brukere"}.
{"To ~s", "Til ~s"}.
{"From ~s", "Fra ~s"}.
{"Running Nodes", "Kjørende Noder"}.
{"Stopped Nodes", "Stoppede Noder"}.
{"Access Control Lists", "Tilgangskontrollister"}.
{"Access Rules", "Tilgangsregler"}.
{"Modules", "Moduler"}.
{"Start Modules", "Start Moduler"}.
{"Stop Modules", "Stop Moduler"}.
{"Backup Management", "Håndtere Sikkerehetskopiering"}.
{"Backup", "Sikkerhetskopier"}.
{"Restore", "Gjenopprett"}.
{"Dump to Text File", "Dump til Tekstfil"}.
{"Import File", "Importer File"}.
{"Import Directory", "Importer Katalog"}.

% mod_register.erl
{"Users are not allowed to register accounts so fast", "Brukere får ikke lov til å registrere kontoer så fort"}.
{"Choose a username and password to register with this server", "Velg et brukernavn og passord for å registrere på denne serveren"}.

% mod_vcard.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"ejabberd vCard module", "ejabberd vCard modul"}.
{"You need an x:data capable client to search", "Du tregner en klient som støtter x:data for å kunne søke"}.
{"Search users in ", "Søk etter brukere i "}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Fyll inn skjemaet for å søke etter Jabber bruker (Legg til * på slutten av feltet for å treffe alle som starter slik)"}.
{"User",              "Bruker"}.
{"Full Name", 	      "Fullstendig Navn"}.
{"Name", 	            "Fornavn"}.
{"Middle Name",       "Mellomnavn"}.
{"Family Name",       "Etternavn"}.
{"Nickname", 	      "Kallenavn"}.
{"Birthday", 	      "Fødselsdag"}.
{"Country", 	      "Land"}.
{"City", 	      "By"}.
{"Organization Name", "Organisasjonsnavn"}.
{"Organization Unit", "Organisasjonsenhet"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Fyll inn felt for å søke etter Jabber brukere"}.

% mod_vcard_odbc.erl
{"Email", "Epost"}.
{"vCard User Search", "vCard Bruker Søk"}.
{"Search Results for ", "Søke Resultater for "}.
{"Jabber ID", "Jabber ID"}.

% mod_pubsub/mod_pubsub.erl
{"A friendly name for the node", "Et vennlig navn for noden"}.
{"Roster groups allowed to subscribe", "Kontaktliste grupper som tillates å abonnere"}.
{"Publish-Subscribe", "Publish-Subscribe"}.
{"ejabberd Publish-Subscribe module", "ejabberd Publish-Subscribe modul"}.
{"PubSub subscriber request", "PubSub abonements forespørsel"}.
{"Choose whether to approve this entity's subscription.", "Velg om du vil godkjenne denne eksistensens abonement"}.
{"Node ID", "Node ID"}.
{"Subscriber Address", "Abonnements Adresse"}.
{"Allow this JID to subscribe to this pubsub node?", "Tillat denne JID å abonnere på denne pubsub noden?"}.
{"Deliver event notifications", "Lever begivenhets kunngjøringer"}.
{"Specify the access model", "Spesifiser aksess modellen"}.
{"When to send the last published item", "Når skal siste publiserte artikkel sendes"}.
{"Deliver payloads with event notifications", "Send innhold sammen med kunngjøringer"}.
{"Notify subscribers when the node configuration changes", "Informer abonnenter når node konfigurasjonen endres"}.
{"Notify subscribers when the node is deleted", "Informer abonnenter når noden slettes"}.
{"Notify subscribers when items are removed from the node", "Informer abonnenter når elementer fjernes fra noden"}.
{"Persist items to storage", "Vedvarende elementer til lagring"}.
{"Max # of items to persist", "Høyeste # elementer som skal lagres"}.
{"Whether to allow subscriptions", "Om man skal tillate abonnenter"}.
{"Specify the publisher model", "Angi publiserings modell"}.
{"Max payload size in bytes", "Største innholdsstørrelse i byte"}.
{"Only deliver notifications to available users", "Send kunngjøringer bare til tilgjengelige brukere"}.

% mod_muc/mod_muc.erl
{"Chatrooms", "Samtalerom"}.
{"You must fill in field \"Nickname\" in the form", "Du må fylle inn feltet \"Nickname\" i skjemaet"}.
{"You need an x:data capable client to register nickname", "Du trenger en klient som søtter x:data for å registrere kallenavn"}.
{"Nickname Registration at ", "Registrer Kallenavn på "}.
{"Enter nickname you want to register", "Skriv inn kallenavnet du ønsker å registrere"}.
{"ejabberd MUC module", "ejabberd MUC modul"}.
{"Only service administrators are allowed to send service messages", "Bare tjeneste administratorer er tilatt å sende tjeneste meldinger"}.
{"Room creation is denied by service policy", "Oppretting av rom nektes av en tjenste regel"}.
{"Conference room does not exist", "Konferanserommet finnes ikke"}.
{"Access denied by service policy", "Tilgang nektes på grunn av en tjeneste regel"}.
{"You must fill in field \"nick\" in the form", "Du må fylle inn feltet \"nick\" i skjemaet"}.
{"Specified nickname is already registered", "Dette kallenavnet er allerede registrert"}.

% mod_muc/mod_muc_room.erl
{"It is not allowed to send private messages", "Det er ikke tillatt å sende private meldinger"}.
{"Visitors are not allowed to change their nicknames in this room", "Besøkende får ikke lov å endre kallenavn i dette rommet"}.
{"Allow visitors to send status text in presence updates", "Tillat besøkende å sende status tekst i tilgjengelighets oppdateringer"}.
{"Allow visitors to change nickname", "Tillat besøkende å endre kallenavn"}.
{"This participant is kicked from the room because he sent an error message", "Denne deltakeren er kastet ut av rommet fordi han sendte en feilmelding"}.
{"This participant is kicked from the room because he sent an error message to another participant", "Denne deltakeren er kastet ut av rommet fordi han sendte en feilmelding til en annen deltaker"}.
{"This participant is kicked from the room because he sent an error presence", "Denne deltakeren er kastet ut av rommet fordi han sendte feil tilstederværelse"}.
{"Make room moderated", "Gjør rommet redaktørstyrt"}.
{"Traffic rate limit is exceeded", "Trafikkmengde grense overskredet"}.
{"This room is not anonymous", "Dette rommet er ikke anonymt"}.
{"Make room persistent", "Gjør rommet permanent"}.
{"Make room public searchable", "Gjør rommet offentlig søkbart"}.
{"Make participants list public", "Gjør deltakerlisten offentlig"}.
{"Make room password protected", "Passordbeskytt rommet"}.
{"Maximum Number of Occupants", "Maksimum Antall Deltakere"}.
{"No limit", "Ingen grense"}.
{"Present real JIDs to", "Presenter ekte JIDer til"}.
{"moderators only", "kun for redaktører"}.
{"anyone", "hvem som helst"}.
{"Make room members-only", "Gjør rommet tilgjengelig kun for medlemmer"}.
{"Default users as participants", "Standard brukere som deltakere"}.
{"Allow users to change subject", "Tillat brukere å endre emne"}.
{"Allow users to send private messages", "Tillat brukere å sende private meldinger"}.
{"Allow users to query other users", "Tillat brukere å sende forespørsel til andre brukere"}.
{"Allow users to send invites", "Tillat brukere å sende invitasjoner"}.
{"Enable logging", "Slå på logging"}.
{"Number of occupants", "Antall deltakere"}.
{"~s invites you to the room ~s", "~s inviterer deg til rommet ~s"}.
{"the password is", "passordet er"}.
{" has set the subject to: ", " har satt emnet til: "}.
{"You need an x:data capable client to configure room", "Du trenger en klient som støtter x:data for å konfigurere rommet"}.
{"Configuration for ", "Konfigurasjon for "}.
{"Room title", "Romtittel"}.
{"Password", "Passord"}.
{"Only moderators and participants are allowed to change subject in this room", "Bare redaktører og deltakere kan endre emnet i dette rommet"}.
{"Only moderators are allowed to change subject in this room", "Bare redaktører kan endre emnet i dette rommet"}.
{"Visitors are not allowed to send messages to all occupants", "Besøkende får ikke sende meldinger til alle deltakere"}.
{"Only occupants are allowed to send messages to the conference", "Bare deltakere får sende normale meldinger til konferansen"}.
{"It is not allowed to send private messages to the conference", "Det er ikke tillatt å sende private meldinger til konferansen"}.
{"Improper message type", "Feilaktig meldingstype"}.
{"Nickname is already in use by another occupant", "Kallenavnet er allerede i bruk av en annen bruker"}.
{"Nickname is registered by another person", "Kallenavnet er reservert av en annen person"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Det er ikke tillatt å sende private meldinger med typen \"groupchat\""}.
{"Recipient is not in the conference room", "Mottakeren er ikke i konferanserommet"}.
{"Only occupants are allowed to send queries to the conference", "Bare deltakere er tillatt å sende forespørsler til konferansen"}.
{"Queries to the conference members are not allowed in this room", "Det er ikke tillatt å sende forespørsler til deltakerene i dette rommet"}.
{"You have been banned from this room", "Du har blitt bannlyst i dette rommet."}.
{"Membership required to enter this room", "Du må være medlem for å gå inn i dette rommet"}.
{"Password required to enter this room", "Passord kreves for å komme inn i dette rommet"}.
{"Incorrect password", "Feil passord"}.
{"Administrator privileges required", "Administratorprivilegier kreves"}.
{"Moderator privileges required", "Redaktørprivilegier kreves"}.
{"JID ~s is invalid", "Ugyldig JID ~s"}.
{"Nickname ~s does not exist in the room", "Kallenavn ~s eksisterer ikke i dette rommet"}.
{"Invalid affiliation: ~s", "Ugyldig rang: ~s"}.
{"Invalid role: ~s", "Ugyldig rolle: ~s"}.
{"Owner privileges required", "Eierprivilegier kreves"}.
{"private, ", "privat, "}.

% mod_irc/mod_irc.erl
{"IRC Transport", "IRC Transport"}.
{"ejabberd IRC module", "ejabberd IRC modul"}.
{"You need an x:data capable client to configure mod_irc settings", "Du trenger en klient som støtter x:data for å konfigurere mod_irc instillinger"}.
{"Registration in mod_irc for ", "Registrering i mod_irc for "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Skriv inn brukernavn og tekstkoding du ønsker å bruke for å koble til IRC tjenere"}.
{"IRC Username", "IRC Brukernavn"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","Om du ønsker å spesifisere tekstkoding for IRC tjenere, fyller du ut en liste med verdier i formatet '{\"irc server\", \"encoding\"}'. Denne tjenesten bruker \"~s\" som standard."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Eksempel: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Tekstkodinger"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "ejabberd Web Admin"}.
{"Administration", "Administrasjon"}.
{"(Raw)", "(Rå)"}.
{"Raw", "Rå"}.
{"Users Last Activity", "Brukers Siste Aktivitet"}.
{"Registered Users", "Registrerte Brukere"}.
{"Offline Messages", "Frakoblede Meldinger"}.
{"Registered Users:", "Registrerte Brukere:"}.
{"Online Users:", "Tilkoblede Brukere:"}.
{"Outgoing s2s Connections:", "Utgående s2s Koblinger"}.
{"Outgoing s2s Servers:", "Utgående s2s Tjenere"}.
{"No Data", "Ingen Data"}.
{"Listened Ports", "Lyttende Porter"}.
{"RPC Call Error", "RPC Kall Feil"}.
{"Database Tables at ", "Database Tabeller på "}.
{"Backup of ", "Sikkerhetskopi av "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Merk at disse valgene vil bare sikkerhetskopiere den innebygde Mnesia databasen. Dersom du bruker ODBC modulen må du også ta backup av din SQL database."}.
{"Store binary backup:", "Lagre binær sikkerhetskopi:"}.
{"Restore binary backup immediately:", "Gjenopprette binær backup umiddelbart:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Gjenopprette binær backup etter neste ejabberd omstart (krever mindre minne):"}.
{"Store plain text backup:", "Lagre rentekst sikkerhetskopi:"}.
{"Restore plain text backup immediately:", "Gjenopprette rentekst sikkerhetskopi umiddelbart:"}.
{"Statistics of ~p", "Statistikk for ~p"}.
{"Uptime:", "Oppetid:"}.
{"CPU Time:", "CPU Tid:"}.
{"Transactions Commited:", "Sendte Transaksjoner:"}.
{"Transactions Aborted:", "Avbrutte Transasksjoner:"}.
{"Transactions Restarted:", "Omstartede Transasksjoner:"}.
{"Transactions Logged:", "Loggede Transasksjoner:"}.
{"Update ", "Oppdater "}.
{"Update plan", "Oppdaterings plan"}.
{"Updated modules", "Oppdater moduler"}.
{"Update script", "Oppdaterings skript"}.
{"Low level update script", "Lavnivå oppdaterings skript"}.
{"Script check", "Skript sjekk"}.
{"Users", "Brukere"}.
{"Nodes", "Noder"}.
{"Statistics", "Statistikk"}.
{"Delete Selected", "Slett valgte"}.
{"Submit", "Send"}.
{"~s access rule configuration", "tilgangsregel konfigurasjon for ~s"}.
{"Node not found", "Noden finnes ikke"}.
{"Add New", "Legg til ny"}.
{"Change Password", "Endre Passord"}.
{"Connected Resources:", "Tilkoblede Ressurser:"}.
{"Password:", "Passord:"}.
{"None", "Ingen"}.
{"Node ", "Node "}.
{"Restart", "Starte på nytt"}.
{"Stop", "Stoppe"}.
{"Name", "Navn"}.
{"Storage Type", "Lagringstype"}.
{"Size", "Størrelse"}.
{"Memory", "Minne"}.
{"OK", "OK"}.
{"Listened Ports at ", "Lyttende Porter på "}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Alternativer"}.
{"Update", "Oppdatere"}.
{"Delete", "Slett"}.
{"Add User", "Legg til Bruker"}.
{"Last Activity", "Siste Aktivitet"}.
{"Never", "Aldri"}.
{"Time", "Tid"}.
{"From", "Fra"}.
{"To", "Til"}.
{"Packet", "Pakke"}.
{"Roster", "Kontaktliste"}.
{"Nickname", "Kallenavn"}.
{"Subscription", "Abonnement"}.
{"Pending", "Ventende"}.
{"Groups", "Grupper"}.
{"Remove", "Fjern"}.
{"User ", "Bruker "}.
{"Roster of ", "Kontaktliste for "}.
{"Online", "Tilkoblet"}.
{"Validate", "Bekrefte gyldighet"}.
{"Name:", "Navn:"}.
{"Description:", "Beskrivelse:"}.
{"Members:", "Medlemmer:"}.
{"Displayed Groups:", "Viste grupper:"}.
{"Group ", "Gruppe "}.
{"Virtual Hosts", "Virtuelle Maskiner"}.
{"ejabberd virtual hosts", "virtuella ejabberd maskiner"}.
{"Period: ", "Periode: "}.
{"Last month", "Siste måned"}.
{"Last year", "Siste året"}.
{"All activity", "All aktivitet"}.
{"Show Ordinary Table", "Vis Ordinær Tabell"}.
{"Show Integral Table", "Vis Integral Tabell"}.
{"Host", "Maskin"}.
{"Modules at ", "Moduler på "}.
{"Start", "Start"}.

% mod_roster.erl
{"Submitted", "Innsendt"}.
{"Bad format", "Feil format"}.
{"Add Jabber ID", "Legg til Jabber ID"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Kontaktens frakoblede meldingskø er full. Meldingen har blitt kassert."}.
{"~s's Offline Messages Queue", "~ss kø for Frakoblede Meldinger"}.
{"Offline Messages:", "Frakoblede Meldinger:"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams modul"}.

% mod_shared_roster.erl
{"Shared Roster Groups", "Delte Kontaktgrupper"}.

% mod_announce.erl
{"Really delete message of the day?", "Virkelig slette melding for dagen?"}.
{"Subject", "Tittel"}.
{"Message body", "Meldingskropp"}.
{"No body provided for announce message", "Ingen meldingskropp gitt for kunngjørings melding"}.
{"Announcements", "Kunngjøringer"}.
{"Send announcement to all users", "Send kunngjøring til alle brukere"}.
{"Send announcement to all users on all hosts", "Send kunngjøring til alle brukere på alle maskiner"}.
{"Send announcement to all online users", "Send kunngjøring alle tilkoblede brukere"}.
{"Send announcement to all online users on all hosts", "Send kunngjøring til alle tilkoblede brukere på alle maskiner"}.
{"Set message of the day and send to online users", "Angi melding for dagen og send til tilkoblede brukere"}.
{"Set message of the day on all hosts and send to online users", "Angi melding for dagen på alle maskiner og send til tilkoblede brukere"}.
{"Update message of the day (don't send)", "Oppdater melding for dagen (ikke send)"}.
{"Update message of the day on all hosts (don't send)", "Oppdater melding for dagen på alle maskiner (ikke send)"}.
{"Delete message of the day", "Slett melding for dagen"}.
{"Delete message of the day on all hosts", "Slett melding for dagen på alle maskiner"}.

% mod_adhoc.erl
{"Commands", "Kommandoer"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Samtalerommets konfigurasjon er endret"}.
{"joins the room", "kommer inn i rommet"}.
{"leaves the room", "forlater rommet"}.
{"has been banned", "har blitt bannlyst"}.
{"has been kicked", "har blitt kastet ut"}.
{"has been kicked because of an affiliation change", "har blitt kastet ut på grunn av en tilknytnings endring"}.
{"has been kicked because the room has been changed to members-only", "har blitt kastet ut på grunn av at rommet er endret til kun-for-medlemmer"}.
{"has been kicked because of a system shutdown", "har blitt kastet ut på grunn av at systemet avslutter"}.
{"is now known as", "er nå kjent som"}.
{"Monday", "mandag"}.
{"Tuesday", "tirsdag"}.
{"Wednesday", "onsdag"}.
{"Thursday", "torsdag"}.
{"Friday", "fredag"}.
{"Saturday", "lørdag"}.
{"Sunday", "søndag"}.
{"January", "januar"}.
{"February", "februar"}.
{"March", "mars"}.
{"April", "april"}.
{"May", "mai"}.
{"June", "juni"}.
{"July", "juli"}.
{"August", "august"}.
{"September", "september"}.
{"October", "oktober"}.
{"November", "november"}.
{"December", "desember"}.
{"Room Configuration", "Rom Konfigurasjon"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
