{"Access Configuration","Tilgangskonfigurasjon"}.
{"Access Control List Configuration","Konfigurasjon for Tilgangskontroll lister"}.
{"Access Control Lists","Tilgangskontrollister"}.
{"Access control lists","Tilgangskontroll lister"}.
{"Access denied by service policy","Tilgang nektes på grunn av en tjeneste regel"}.
{"Access rules","Tilgangsregler"}.
{"Access Rules","Tilgangsregler"}.
{"Action on user","Handling på bruker"}.
{"Add Jabber ID","Legg til Jabber ID"}.
{"Add New","Legg til ny"}.
{"Add User","Legg til Bruker"}.
{"Administration","Administrasjon"}.
{"Administration of ","Administrasjon av "}.
{"Administrator privileges required","Administratorprivilegier kreves"}.
{"A friendly name for the node","Et vennlig navn for noden"}.
{"All activity","All aktivitet"}.
{"Allow this JID to subscribe to this pubsub node?","Tillat denne JID å abonnere på denne pubsub noden?"}.
{"Allow users to change subject","Tillat brukere å endre emne"}.
{"Allow users to query other users","Tillat brukere å sende forespørsel til andre brukere"}.
{"Allow users to send invites","Tillat brukere å sende invitasjoner"}.
{"Allow users to send private messages","Tillat brukere å sende private meldinger"}.
{"Allow visitors to change nickname","Tillat besøkende å endre kallenavn"}.
{"Allow visitors to send status text in presence updates","Tillat besøkende å sende status tekst i tilgjengelighets oppdateringer"}.
{"All Users","Alle Brukere"}.
{"Announcements","Kunngjøringer"}.
{"anyone","hvem som helst"}.
{"April","april"}.
{"August","august"}.
{"Backup Management","Håndtere Sikkerehetskopiering"}.
{"Backup of ","Sikkerhetskopi av "}.
{"Backup","Sikkerhetskopier"}.
{"Backup to File at ","Sikkerhetskopiere til Fil på "}.
{"Bad format","Feil format"}.
{"Birthday","Fødselsdag"}.
{"Change Password","Endre Passord"}.
{"Change User Password","Endre Brukers Passord"}.
{"Chatroom configuration modified","Samtalerommets konfigurasjon er endret"}.
{"Chatrooms","Samtalerom"}.
{"Choose a username and password to register with this server","Velg et brukernavn og passord for å registrere på denne serveren"}.
{"Choose modules to stop","Velg hvilke moduler som skal stoppes"}.
{"Choose storage type of tables","Velg lagringstype for tabeller"}.
{"Choose whether to approve this entity's subscription.","Velg om du vil godkjenne denne eksistensens abonement"}.
{"City","By"}.
{"Commands","Kommandoer"}.
{"Conference room does not exist","Konferanserommet finnes ikke"}.
{"Configuration for ","Konfigurasjon for "}.
{"Configuration","Konfigurasjon"}.
{"Connected Resources:","Tilkoblede Ressurser:"}.
{"Country","Land"}.
{"CPU Time:","CPU Tid:"}.
{"Database","Database"}.
{"Database Tables at ","Database Tabeller på "}.
{"Database Tables Configuration at ","Database Tabell Konfigurasjon på "}.
{"December","desember"}.
{"Default users as participants","Standard brukere som deltakere"}.
{"Delete message of the day on all hosts","Slett melding for dagen på alle maskiner"}.
{"Delete message of the day","Slett melding for dagen"}.
{"Delete Selected","Slett valgte"}.
{"Delete","Slett"}.
{"Delete User","Slett Bruker"}.
{"Deliver event notifications","Lever begivenhets kunngjøringer"}.
{"Deliver payloads with event notifications","Send innhold sammen med kunngjøringer"}.
{"Description:","Beskrivelse:"}.
{"Disc only copy","Kun diskkopi"}.
{"Displayed Groups:","Viste grupper:"}.
{"Dump Backup to Text File at ","Dump Sikkerhetskopi til Tekstfil på "}.
{"Dump to Text File","Dump til Tekstfil"}.
{"Edit Properties","Redigere Egenskaper"}.
{"ejabberd IRC module","ejabberd IRC modul"}.
{"ejabberd MUC module","ejabberd MUC modul"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe modul"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams modul"}.
{"ejabberd vCard module","ejabberd vCard modul"}.
{"ejabberd virtual hosts","virtuella ejabberd maskiner"}.
{"ejabberd Web Admin","ejabberd Web Admin"}.
{"Email","Epost"}.
{"Enable logging","Slå på logging"}.
{"Encodings","Tekstkodinger"}.
{"End User Session","Avslutt Bruker Sesjon"}.
{"Enter list of {Module, [Options]}","Skriv inn en liste av {Module, [Options]}"}.
{"Enter nickname you want to register","Skriv inn kallenavnet du ønsker å registrere"}.
{"Enter path to backup file","Skriv inn sti til sikkerhetskopi filen"}.
{"Enter path to jabberd1.4 spool dir","Skriv inn sti til jabberd1.4 spoolkatalog"}.
{"Enter path to jabberd1.4 spool file","Skriv inn sti til jabberd1.4 spoolfil"}.
{"Enter path to text file","Skriv inn sti til tekstfil"}.
{"Enter username and encodings you wish to use for connecting to IRC servers","Skriv inn brukernavn og tekstkoding du ønsker å bruke for å koble til IRC tjenere"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].","Eksempel: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Family Name","Etternavn"}.
{"February","februar"}.
{"Fill in fields to search for any matching Jabber User","Fyll inn felt for å søke etter Jabber brukere"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Fyll inn skjemaet for å søke etter Jabber bruker (Legg til * på slutten av feltet for å treffe alle som starter slik)"}.
{"Friday","fredag"}.
{"From","Fra"}.
{"From ~s","Fra ~s"}.
{"Full Name","Fullstendig Navn"}.
{"Get Number of Online Users","Vis Antall Tilkoblede Brukere"}.
{"Get Number of Registered Users","Vis Antall Registrerte Brukere"}.
{"Get User Last Login Time","Vis Brukers Siste Påloggings Tidspunkt"}.
{"Get User Password","Hent Brukers Passord"}.
{"Get User Statistics","Vis Bruker Statistikk"}.
{"Group ","Gruppe "}.
{"Groups","Grupper"}.
{"has been banned","har blitt bannlyst"}.
{"has been kicked because of an affiliation change","har blitt kastet ut på grunn av en tilknytnings endring"}.
{"has been kicked because of a system shutdown","har blitt kastet ut på grunn av at systemet avslutter"}.
{"has been kicked because the room has been changed to members-only","har blitt kastet ut på grunn av at rommet er endret til kun-for-medlemmer"}.
{"has been kicked","har blitt kastet ut"}.
{" has set the subject to: "," har satt emnet til: "}.
{"Host","Maskin"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","Om du ønsker å spesifisere tekstkoding for IRC tjenere, fyller du ut en liste med verdier i formatet '{\"irc server\", \"encoding\"}'. Denne tjenesten bruker \"~s\" som standard."}.
{"Import Directory","Importer Katalog"}.
{"Import File","Importer File"}.
{"Import User from File at ","Importer Bruker fra Fil på "}.
{"Import Users from Dir at ","Importer Brukere fra Katalog på "}.
{"Import Users From jabberd 1.4 Spool Files","Importer Brukere Fra jabberd 1.4 Spoolfiler"}.
{"Improper message type","Feilaktig meldingstype"}.
{"Incorrect password","Feil passord"}.
{"Invalid affiliation: ~s","Ugyldig rang: ~s"}.
{"Invalid role: ~s","Ugyldig rolle: ~s"}.
{"IP addresses","IP adresser"}.
{"IRC Transport","IRC Transport"}.
{"IRC Username","IRC Brukernavn"}.
{"is now known as","er nå kjent som"}.
{"It is not allowed to send private messages","Det er ikke tillatt å sende private meldinger"}.
{"It is not allowed to send private messages of type \"groupchat\"","Det er ikke tillatt å sende private meldinger med typen \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Det er ikke tillatt å sende private meldinger til konferansen"}.
{"Jabber ID","Jabber ID"}.
{"January","januar"}.
{"JID ~s is invalid","Ugyldig JID ~s"}.
{"joins the room","kommer inn i rommet"}.
{"July","juli"}.
{"June","juni"}.
{"Last Activity","Siste Aktivitet"}.
{"Last login","Siste pålogging"}.
{"Last month","Siste måned"}.
{"Last year","Siste året"}.
{"leaves the room","forlater rommet"}.
{"Listened Ports at ","Lyttende Porter på "}.
{"Listened Ports","Lyttende Porter"}.
{"List of modules to start","Liste over moduler som skal startes"}.
{"Low level update script","Lavnivå oppdaterings skript"}.
{"Make participants list public","Gjør deltakerlisten offentlig"}.
{"Make room members-only","Gjør rommet tilgjengelig kun for medlemmer"}.
{"Make room moderated","Gjør rommet redaktørstyrt"}.
{"Make room password protected","Passordbeskytt rommet"}.
{"Make room persistent","Gjør rommet permanent"}.
{"Make room public searchable","Gjør rommet offentlig søkbart"}.
{"March","mars"}.
{"Maximum Number of Occupants","Maksimum Antall Deltakere"}.
{"Max # of items to persist","Høyeste # elementer som skal lagres"}.
{"Max payload size in bytes","Største innholdsstørrelse i byte"}.
{"May","mai"}.
{"Membership required to enter this room","Du må være medlem for å gå inn i dette rommet"}.
{"Members:","Medlemmer:"}.
{"Memory","Minne"}.
{"Message body","Meldingskropp"}.
{"Middle Name","Mellomnavn"}.
{"Moderator privileges required","Redaktørprivilegier kreves"}.
{"moderators only","kun for redaktører"}.
{"Module","Modul"}.
{"Modules at ","Moduler på "}.
{"Modules","Moduler"}.
{"Monday","mandag"}.
{"Name:","Navn:"}.
{"Name","Navn"}.
{"Never","Aldri"}.
{"Nickname is already in use by another occupant","Kallenavnet er allerede i bruk av en annen bruker"}.
{"Nickname is registered by another person","Kallenavnet er reservert av en annen person"}.
{"Nickname","Kallenavn"}.
{"Nickname Registration at ","Registrer Kallenavn på "}.
{"Nickname ~s does not exist in the room","Kallenavn ~s eksisterer ikke i dette rommet"}.
{"No body provided for announce message","Ingen meldingskropp gitt for kunngjørings melding"}.
{"No Data","Ingen Data"}.
{"Node ID","Node ID"}.
{"Node ","Node "}.
{"Node not found","Noden finnes ikke"}.
{"Nodes","Noder"}.
{"No limit","Ingen grense"}.
{"None","Ingen"}.
{"No resource provided","Ingen ressurs angitt"}.
{"Notify subscribers when items are removed from the node","Informer abonnenter når elementer fjernes fra noden"}.
{"Notify subscribers when the node configuration changes","Informer abonnenter når node konfigurasjonen endres"}.
{"Notify subscribers when the node is deleted","Informer abonnenter når noden slettes"}.
{"November","november"}.
{"Number of occupants","Antall deltakere"}.
{"Number of online users","Antall tilkoblede brukere"}.
{"Number of registered users","Antall registrerte brukere"}.
{"October","oktober"}.
{"Offline Messages:","Frakoblede Meldinger:"}.
{"Offline Messages","Frakoblede Meldinger"}.
{"OK","OK"}.
{"Online","Tilkoblet"}.
{"Online Users:","Tilkoblede Brukere:"}.
{"Online Users","Tilkoblede Brukere"}.
{"Only deliver notifications to available users","Send kunngjøringer bare til tilgjengelige brukere"}.
{"Only moderators and participants are allowed to change subject in this room","Bare redaktører og deltakere kan endre emnet i dette rommet"}.
{"Only moderators are allowed to change subject in this room","Bare redaktører kan endre emnet i dette rommet"}.
{"Only occupants are allowed to send messages to the conference","Bare deltakere får sende normale meldinger til konferansen"}.
{"Only occupants are allowed to send queries to the conference","Bare deltakere er tillatt å sende forespørsler til konferansen"}.
{"Only service administrators are allowed to send service messages","Bare tjeneste administratorer er tilatt å sende tjeneste meldinger"}.
{"Options","Alternativer"}.
{"Organization Name","Organisasjonsnavn"}.
{"Organization Unit","Organisasjonsenhet"}.
{"Outgoing s2s Connections:","Utgående s2s Koblinger"}.
{"Outgoing s2s Connections","Utgående s2s Koblinger"}.
{"Outgoing s2s Servers:","Utgående s2s Tjenere"}.
{"Owner privileges required","Eierprivilegier kreves"}.
{"Packet","Pakke"}.
{"Password:","Passord:"}.
{"Password","Passord"}.
{"Password required to enter this room","Passord kreves for å komme inn i dette rommet"}.
{"Password Verification","Passord Bekreftelse"}.
{"Path to Dir","Sti til Katalog"}.
{"Path to File","Sti til Fil"}.
{"Pending","Ventende"}.
{"Period: ","Periode: "}.
{"Persist items to storage","Vedvarende elementer til lagring"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","Port"}.
{"Present real JIDs to","Presenter ekte JIDer til"}.
{"private, ","privat, "}.
{"Publish-Subscribe","Publish-Subscribe"}.
{"PubSub subscriber request","PubSub abonements forespørsel"}.
{"Queries to the conference members are not allowed in this room","Det er ikke tillatt å sende forespørsler til deltakerene i dette rommet"}.
{"RAM and disc copy","RAM og diskkopi"}.
{"RAM copy","RAM kopi"}.
{"(Raw)","(Rå)"}.
{"Raw","Rå"}.
{"Really delete message of the day?","Virkelig slette melding for dagen?"}.
{"Recipient is not in the conference room","Mottakeren er ikke i konferanserommet"}.
{"Registered Users:","Registrerte Brukere:"}.
{"Registered Users","Registrerte Brukere"}.
{"Registration in mod_irc for ","Registrering i mod_irc for "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Merk at disse valgene vil bare sikkerhetskopiere den innebygde Mnesia databasen. Dersom du bruker ODBC modulen må du også ta backup av din SQL database."}.
{"Remote copy","Lagres ikke lokalt"}.
{"Remove","Fjern"}.
{"Remove User","Fjern Bruker"}.
{"Replaced by new connection","Erstattet av en ny tilkobling"}.
{"Resources","Ressurser"}.
{"Restart Service","Start Tjeneste på Nytt"}.
{"Restart","Starte på nytt"}.
{"Restore Backup from File at ","Gjenopprett fra Sikkerhetsopifil på "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Gjenopprette binær backup etter neste ejabberd omstart (krever mindre minne):"}.
{"Restore binary backup immediately:","Gjenopprette binær backup umiddelbart:"}.
{"Restore","Gjenopprett"}.
{"Restore plain text backup immediately:","Gjenopprette rentekst sikkerhetskopi umiddelbart:"}.
{"Room Configuration","Rom Konfigurasjon"}.
{"Room creation is denied by service policy","Oppretting av rom nektes av en tjenste regel"}.
{"Room title","Romtittel"}.
{"Roster groups allowed to subscribe","Kontaktliste grupper som tillates å abonnere"}.
{"Roster","Kontaktliste"}.
{"Roster of ","Kontaktliste for "}.
{"Roster size","Kontaktliste størrelse"}.
{"RPC Call Error","RPC Kall Feil"}.
{"Running Nodes","Kjørende Noder"}.
{"~s access rule configuration","tilgangsregel konfigurasjon for ~s"}.
{"Saturday","lørdag"}.
{"Script check","Skript sjekk"}.
{"Search Results for ","Søke Resultater for "}.
{"Search users in ","Søk etter brukere i "}.
{"Send announcement to all online users on all hosts","Send kunngjøring til alle tilkoblede brukere på alle maskiner"}.
{"Send announcement to all online users","Send kunngjøring alle tilkoblede brukere"}.
{"Send announcement to all users on all hosts","Send kunngjøring til alle brukere på alle maskiner"}.
{"Send announcement to all users","Send kunngjøring til alle brukere"}.
{"September","september"}.
{"Set message of the day and send to online users","Angi melding for dagen og send til tilkoblede brukere"}.
{"Set message of the day on all hosts and send to online users","Angi melding for dagen på alle maskiner og send til tilkoblede brukere"}.
{"Shared Roster Groups","Delte Kontaktgrupper"}.
{"Show Integral Table","Vis Integral Tabell"}.
{"Show Ordinary Table","Vis Ordinær Tabell"}.
{"Shut Down Service","Avslutt Tjeneste"}.
{"~s invites you to the room ~s","~s inviterer deg til rommet ~s"}.
{"Size","Størrelse"}.
{"Specified nickname is already registered","Dette kallenavnet er allerede registrert"}.
{"Specify the access model","Spesifiser aksess modellen"}.
{"Specify the publisher model","Angi publiserings modell"}.
{"~s's Offline Messages Queue","~ss kø for Frakoblede Meldinger"}.
{"Start Modules at ","Start Moduler på "}.
{"Start Modules","Start Moduler"}.
{"Start","Start"}.
{"Statistics of ~p","Statistikk for ~p"}.
{"Statistics","Statistikk"}.
{"Stop Modules at ","Stopp Moduler på "}.
{"Stop Modules","Stop Moduler"}.
{"Stopped Nodes","Stoppede Noder"}.
{"Stop","Stoppe"}.
{"Storage Type","Lagringstype"}.
{"Store binary backup:","Lagre binær sikkerhetskopi:"}.
{"Store plain text backup:","Lagre rentekst sikkerhetskopi:"}.
{"Subject","Tittel"}.
{"Submit","Send"}.
{"Submitted","Innsendt"}.
{"Subscriber Address","Abonnements Adresse"}.
{"Subscription","Abonnement"}.
{"Sunday","søndag"}.
{"the password is","passordet er"}.
{"This participant is kicked from the room because he sent an error message","Denne deltakeren er kastet ut av rommet fordi han sendte en feilmelding"}.
{"This participant is kicked from the room because he sent an error message to another participant","Denne deltakeren er kastet ut av rommet fordi han sendte en feilmelding til en annen deltaker"}.
{"This participant is kicked from the room because he sent an error presence","Denne deltakeren er kastet ut av rommet fordi han sendte feil tilstederværelse"}.
{"This room is not anonymous","Dette rommet er ikke anonymt"}.
{"Thursday","torsdag"}.
{"Time delay","Tids forsinkelse"}.
{"Time","Tid"}.
{"To ~s","Til ~s"}.
{"To","Til"}.
{"Traffic rate limit is exceeded","Trafikkmengde grense overskredet"}.
{"Transactions Aborted:","Avbrutte Transasksjoner:"}.
{"Transactions Commited:","Sendte Transaksjoner:"}.
{"Transactions Logged:","Loggede Transasksjoner:"}.
{"Transactions Restarted:","Omstartede Transasksjoner:"}.
{"Tuesday","tirsdag"}.
{"Updated modules","Oppdater moduler"}.
{"Update message of the day (don't send)","Oppdater melding for dagen (ikke send)"}.
{"Update message of the day on all hosts (don't send)","Oppdater melding for dagen på alle maskiner (ikke send)"}.
{"Update ","Oppdater "}.
{"Update","Oppdatere"}.
{"Update plan","Oppdaterings plan"}.
{"Update script","Oppdaterings skript"}.
{"Uptime:","Oppetid:"}.
{"Use of STARTTLS required","Bruk av STARTTLS kreves"}.
{"User ","Bruker "}.
{"User","Bruker"}.
{"User Management","Bruker Behandling"}.
{"Users are not allowed to register accounts so fast","Brukere får ikke lov til å registrere kontoer så fort"}.
{"Users","Brukere"}.
{"Users Last Activity","Brukers Siste Aktivitet"}.
{"Validate","Bekrefte gyldighet"}.
{"vCard User Search","vCard Bruker Søk"}.
{"Virtual Hosts","Virtuelle Maskiner"}.
{"Visitors are not allowed to change their nicknames in this room","Besøkende får ikke lov å endre kallenavn i dette rommet"}.
{"Visitors are not allowed to send messages to all occupants","Besøkende får ikke sende meldinger til alle deltakere"}.
{"Wednesday","onsdag"}.
{"When to send the last published item","Når skal siste publiserte artikkel sendes"}.
{"Whether to allow subscriptions","Om man skal tillate abonnenter"}.
{"You have been banned from this room","Du har blitt bannlyst i dette rommet."}.
{"You must fill in field \"Nickname\" in the form","Du må fylle inn feltet \"Nickname\" i skjemaet"}.
{"You need an x:data capable client to configure mod_irc settings","Du trenger en klient som støtter x:data for å konfigurere mod_irc instillinger"}.
{"You need an x:data capable client to configure room","Du trenger en klient som støtter x:data for å konfigurere rommet"}.
{"You need an x:data capable client to register nickname","Du trenger en klient som søtter x:data for å registrere kallenavn"}.
{"You need an x:data capable client to search","Du tregner en klient som støtter x:data for å kunne søke"}.
{"Your contact offline message queue is full. The message has been discarded.","Kontaktens frakoblede meldingskø er full. Meldingen har blitt kassert."}.
