% $Id$
% Language: Polish (polski)
% Author: Andrzej Smyk
% Author: Mateusz Gajewski
% Author: Zbyszek Zolkiewski

% jlib.hrl
{"No resource provided", "Brak dostarczonych zasobów"}.

% mod_configure.erl
{"Restart Service", "Restart serwisu"}.
{"Shut Down Service", "Wyłączenie serwisu"}.
{"Delete User", "Usuń użytkownika"}.
{"End User Session", "Zakończ sesję uzytkownika"}.
{"Get User Password", "Pobierz hasło użytkownika"}.
{"Change User Password", "Zmień hasło użytkownika"}.
{"Get User Last Login Time", "Pokaż czas ostatniego zalogowania uzytkownika"}.
{"Get User Statistics", "Pobierz statystyki użytkownika"}.
{"Get Number of Registered Users", "Pokaż liczbę zarejestrowanych użytkowników"}.
{"Get Number of Online Users", "Pokaż ilość użytkowników online"}.
{"User Management", "Zarządzanie użytkownikami"}.
{"Time delay", "Opóźnienie czasu"}.
{"Password Verification", "Weryfikacja hasła"}.
{"Number of registered users", "Ilość zarejestrowanych użytkowników"}.
{"Number of online users", "Ilość użytkowników online"}.
{"Last login", "Ostatnie logowanie"}.
{"Roster size", "Rozmiar rostera"}.
{"IP addresses", "Adresy IP"}.
{"Resources", "Zasoby"}.
{"Choose storage type of tables", "Wybierz typ przechowalni tablic"}.
{"RAM copy", "Kopia RAM"}.
{"RAM and disc copy", "Kopia ramu i dysku"}.
{"Disc only copy", "Kopia samego dysku"}.
{"Remote copy", "Zdalna kopia"}.
{"Stop Modules at ", "Zatrzymaj moduł o "}.
{"Choose modules to stop", "Wybierz moduły do zatrzymania"}.
{"Start Modules at ", "Uruchom moduł o "}.
{"Enter list of {Module, [Options]}", "Wprowadź listę {Moduł, [Opcje]}"}.
{"List of modules to start", "Lista modułów do uruchomienia"}.
{"Backup to File at ", "Stwórz kopię do pliku na "}.
{"Enter path to backup file", "Wprowadź scieżkę do pliku kopii zapasowej"}.
{"Path to File", "Scieżka do pliku"}.
{"Restore Backup from File at ", "Przywróć kopię zapasową z pliku na "}.
{"Dump Backup to Text File at ", "Zrzuć kopię zapasową do pliku tekstowego na "}.
{"Enter path to text file", "Wprowadź scieżkę do pliku tekstowego"}.
{"Import User from File at ", "Importuj użytkownika z pliku na "}.
{"Enter path to jabberd1.4 spool file", "Wprowadź ścieżkę do pliku spool dla serwera jabberd1.4"}.
{"Import Users from Dir at ", "Importuj użytkowników z katalogu na "}.
{"Enter path to jabberd1.4 spool dir", "Wprowadź ścieżkę do katalogu spool serwera jabberd1.4"}.
{"Path to Dir", "Ścieżka do katalogu"}.
{"Hostname Configuration", "Konfiguracja hosta"}.
{"Choose host name", "Wybierz nazwę hosta"}.
{"Host name", "Nazwa hosta"}.
{"Access Control List Configuration", "Konfiguracja listy dostępowej"}.
{"Access control lists", "Lista dostępu"}.
{"Access Configuration", "Konfiguracja dostępu"}.
{"Access rules", "Zasady dostępu"}.
{"Remove Users", "Usuń użytkowników"}.
{"Choose users to remove", "Wybierz użytkowników do usunięcia"}.
{"Administration of ", "Administracja "}.
{"Action on user", "Akcja dla użytkownika"}.
{"Edit Properties", "Edytuj właściwości"}.
{"Remove User", "Usuń użytkownika"}.

% mod_disco.erl
{"Configuration", "Konfiguracja"}.
{"Online Users", "Użytkownicy zalogowani"}.
{"All Users", "Wszyscy użytkownicy"}.
{"To ~s", "Do ~s"}.
{"From ~s", "Z  ~s"}.
{"Running Nodes", "Uruchomione gałęzie"}.
{"Stopped Nodes", "Zatrzymane gałęzie"}.
{"Host Name", "Nazwa hosta"}.
{"Access Control Lists", "Lista dostępowa"}.
{"Access Rules", "Zasady dostępu"}.
{"Remove Users", "Usuń użytkowników"}.
{"Modules", "Moduły"}.
{"Start Modules", "Uruchom moduły"}.
{"Stop Modules", "Zatrzymaj moduły"}.
{"Backup Management", "Zarządzanie kopiami zapasowymi"}.
{"Backup", "Tworzenie kopii"}.
{"Restore", "Odtwarzanie kopii"}.
{"Dump to Text File", "Zrzucanie do pliku tekstowego"}.
{"Import File", "Importuj plik"}.
{"Import Directory", "Importuj katalog"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Wybierz nazwę użytkownika i hasło aby zarejestrować się na tym serwerze"}.

% mod_vcard.erl
{"You need an x:data capable client to search", "Potrzebujesz klienta kompatybilnego z x:data aby wyszukiwać"}.
{"Search users in ", "Wyszukaj użytkowników w "}.
{"Fill in fields to search for any matching Jabber User", "Wypełnij pola aby znaleźdź pasujących użytkowników Jabbera"}.
{"User",              "Użytkownik: "}.
{"Full Name", 	      "Pełna nazwa: "}.
{"Name", 	      "Imię: "}.
{"Middle Name",       "Nazwisko: "}.
{"Family Name",       "Nazwisko rodowe: "}.
{"Nickname", 	      "Nick: "}.
{"Birthday", 	      "Data urodzenia: "}.
{"Country", 	      "Państwo: "}.
{"City", 	      "Miasto: "}.
{"Organization Name", "Nazwa organizacji: "}.
{"Organization Unit", "Dział: "}.

% mod_muc/mod_muc.erl
{"Chatrooms", "Pokoje rozmów"}.
{"ejabberd MUC module", "Moduł MUC"}.
{"You need an x:data capable client to register nickname", "Potrzebujesz klienta kompatybilnego z x:data aby zarejestrować nick"}.
{"Nickname Registration at ", "Rejestracja nicka na "}.
{"Enter nickname you want to register", "Wprowadz nicka którego chcesz zarejestrować"}.
{"Only service administrators are allowed to send service messages", "Jedynie administrator może wysyłać wiadomości serwisowe"}.
{"Conference room does not exist", "Pokój konferencyjny nie istnieje"}.
{"Access denied by service policy", "Dostęp zabroniony przez zabezpieczenia serwera"}.
{"Specified nickname is already registered", "Podany nick jest już zarejestrowany"}.

% mod_muc/mod_muc_room.erl
{"Make room moderated", "Moderuj pokój"}.
{"Traffic rate limit is exceeded", "Limit transferu przekroczony"}.
{"Maximum Number of Occupants", "Maksymalna liczba uczestników"}.
{"No limit", "Bez limitu"}.
{"~s invites you to the room ~s", "~ zaprasza Cię do pokoju ~s"}.
{"the password is", "hasło to"}.
{" has set the subject to: ", "zmieł(a) temat na: "}.
{"You need an x:data capable client to configure room", "Potrzebujesz klienta kompatybilnego z x:data aby skonfigurować pokój"}.
{"Configuration for ", "Konfiguracja dla "}.
{"Room title", "Tytuł pokoju"}.
{"Password", "Hasło"}.
{"Only moderators and participants are allowed to change subject in this room", "Tylko moderatorzy i wlasciciele mogą zmienić temat tego pokoju"}.
{"Only moderators are allowed to change subject in this room", "Tylko moderatorzy mogą zmienić temat tego pokoju"}.
{"Visitors are not allowed to send messages to all occupants", "Odwiedzający nie mogą wysyłać wiadomości do wszystkich obecnych"}.
{"Only occupants are allowed to send messages to the conference", "Tylko obecni mogą wysyłać wiadomości na konferencje"}.
{"It is not allowed to send normal messages to the conference", "Nie można wysyłać normalnych wiadomości na konferencje"}.
{"It is not allowed to send private messages to the conference", "Nie wolno wysyłac prywatnych wiadomości na konferencje"}.
{"Improper message type", "Nieprawidłowy typ wiadomości"}.
{"Nickname is already in use by another occupant", "Nick jest używany przez innego użytkownika"}.
{"Nickname is registered by another person", "Nick jest już zarejestrowany przez inną osobę"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Nie mozna wysyłac prywatnych wiadomości typu \"Groupchat\" "}.
{"Recipient is not in the conference room", "Odbiorca nie jest obecny w pokoju"}.
{"Only occupants are allowed to send queries to the conference", "Tylko użytkownicy mogą wysyłać zapytania do pokoju konferencyjnego"}.
{"Queries to the conference members are not allowed in this room", "Zapytania do członków konferencji nie są dozwolone w tym pokoju"}.
{"You have been banned from this room", "Zostałeś zabanowany w tym pokoju"}.
{"Membership required to enter this room", "Aby wejść do pokoju wymagane jest jego członkostwo"}.
{"Password required to enter this room", "Aby wejść do pokoju wymagane jest hasło"}.
{"Incorrect password", "Nieprawidłowe hasło"}.
{"Administrator privileges required", "Wymagane prawa administratora"}.
{"Moderator privileges required", "Wymagane prawa moderatora"}.
{"JID ~s is invalid", "JID ~s jest niepoprawny"}.
{"Nickname ~s does not exist in the room", "Nick ~s nie istnieje w tym pokoju"}.
{"Invalid affiliation: ~s", "Nieprawidłowe powiązanie: ~s"}.
{"Invalid role: ~s", "Nieprawidłowa rola: ~s"}.
{"Owner privileges required", "Wymagane uprawnienia właściciela	"}.
{"private, ", "prywatny, "}.
{"Present real JIDs to", "Kto może widzieć prawdziwe JID-y?"}.
{"moderators only", "tylko moderatorzy"}.
{"anyone", "wszyscy"}.


% mod_irc/mod_irc.erl
{"IRC Transport", "Transport IRC"}.
{"ejabberd IRC module", "Moduł IRC"}.
{"You need an x:data capable client to configure mod_irc settings", "Potrzebujesz klienta kompatybilnego z x:data aby skonfigurować mod_irc"}.
{"Registration in mod_irc for ", "Rejestracja w mod_irc dla "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Wprowadź nazwę użytkownika i kodowanie których chcesz używać do łączenia z serwerami IRC"}.
{"IRC Username", "Nazwa użytkownika"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Przykład: [{\"wroclaw.irc.pl\",\"utf-8\"}, {\"warszawa.irc.pl\", \"iso8859-2\"}]."}.
{"Encodings", "Kodowania"}.

% web/ejabberd_web_admin.erl
{"Low level update script", "Skrypt update-u niskiego poziomu"}.
{"Users", "Użytkownicy"}.
{"Nodes", "Gałęzie"}.
{"Statistics", "Statystyki"}.
{"Delete Selected", "Usuń zaznaczone"}.
{"Submit", "Wprowadź"}.
{"~s access rule configuration", "~s konfiguracja zasad dostępu"}.
{"Node not found", "Gałąź nie znaleziona"}.
{"Add New", "Dodaj nowe"}.
{"Change Password", "Zmień hasło"}.
{"Connected Resources:", "Zasoby podłączone"}.
{"Password:", "Hasło:"}.
{"None", "Brak"}.
{"Node ", "Gałąź "}.
{"Restart", "Restart"}.
{"Stop", "Stop"}.
{"Name", "Nazwa"}.
{"Storage Type", "Typ bazy"}.
{"Size", "Wielkość"}.
{"Memory", "Pamięć"}.
{"OK", "OK"}.
{"Listened Ports at ", "Porty nasłuchujące "}.
{"Port", "Port"}.
{"Module", "Moduł"}.
{"Options", "Opcje"}.
{"Update", "Aktualizacja"}.
{"Delete", "Usuń"}.
{"Add User", "Dodaj użytkownika"}.
{"Last Activity", "Ostatnia aktywność"}.
{"Never", "Nigdy"}.
{"Time", "Czas"}.
{"From", "Od"}.
{"To", "Do"}.
{"Packet", "Pakiet "}.
{"Roster", "Roster "}.
{"Nickname", "Nick "}.
{"Subscription", "Subskrypcja "}.
{"Pending", "Oczekiwanie "}.
{"Groups", "Grupy "}.
{"Remove", "Usuń "}.
{"User ", "Użytkownik "}.
{"Roster of ", "Roster "}.
{"Shared Roster", "Roster współdzielony"}.
{"Online", "Dostępny"}.
{"Validate", "Zatwierdź"}.
{"Name:", "Nazwa:"}.
{"Description:", "Opis:"}.
{"Members:", "Członkowie:"}.
{"Displayed Groups:", "Wyświetlane grupy:"}.
{"Group ", "Grupa "}.
{"Period: ", "Przedział czasu "}.
{"Last month", "Ostatni miesiąc"}.
{"Last year", "Ostatni rok"}.
{"All activity", "Cała aktywność"}.
{"Show Ordinary Table", "Pokaż zwykłą tabelę"}.
{"Show Integral Table", "Pokaż tabelę całkowitą"}.
{"Start", "Start"}.
{"Modules at ", "Moduły na "}.
{"Virtual Hosts", "Wirtualne hosty"}.
{"ejabberd virtual hosts", "wirtualne hosty ejabberda"}.
{"Host", "Host"}.

% mod_vcard_odbc.erl
{"Email", "Email"}.
{"vCard User Search", "Wyszukiwanie vCard użytkowników"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Wypełnij formularz aby wyszukać pasujących użytkowników Jabbera (dodaj * na koniec pola aby dopasować)"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Wymagane użycie STARTTLS"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd Publish-Subscribe module", "Moduł Publish-Subscribe"}.
{"PubSub subscriber request", "Rządzanie subskrybenta PubSub"}.
{"Choose whether to approve this entity's subscription.", "Wybierz, czy akceptować subskrypcję tej jednostki"}.
{"Node ID", "ID noda"}.
{"Subscriber Address", "Adres subskrybenta"}.
{"Allow this JID to subscribe to this pubsub node?", "Pozwól temu JID na zapisanie się do tego noda pubsub"}.
{"Deliver event notifications", "Dostarczaj powiadomienia o zdarzeniach"}.
{"Specify the access model", "Oznacz model dostępu"}.
{"Roster groups that may subscribe (if access model is roster)", "Grupy rostera jakie mogą subskrybować (jeśli model dostępu to roster"}.
{"When to send the last published item", "Kiedy wysłać ostatnio opublikowaną rzecz"}.
{"Node Creator", "Tworzenie gałęzi"}.
{"Deliver payloads with event notifications", "Dołącz zawartość publikowanego przedmiotu podczas wysyłania powiadomienia o publikacji"}.
{"Notify subscribers when the node configuration changes", "Informuj subskrybentów gdy konfiguracja gałęzi się zmieni"}.
{"Notify subscribers when the node is deleted", "Informuj subskrybentów gdy gałąż zostanie wykasowana"}.
{"Notify subscribers when items are removed from the node", "Informuj subskrybentów kiedy zostaną z gałęzi usunięte jakieś elementy"}.
{"Persist items to storage", "Przechowuj przedmioty pub/sub w pamięci"}.
{"Max # of items to persist", "Maksymalna ilość przechowywanych przedmiotów"}.
{"Whether to allow subscriptions", "Czy pozwolić na subskrypcje"}.
{"Specify the subscriber model", "Oznacz model subskrybenta"}.
{"Specify the publisher model", "Oznacz model publikującego"}.
{"Max payload size in bytes", "Maksymalna wielkość powiadomienia w bajtach"}.
{"Send items to new subscribers", "Wysyłaj rzeczy do nowych subskrybentów"}.
{"Only deliver notifications to available users", "Dostarczaj notyfikacje tylko do osiągalnych użytkowników"}.
{"Specify the current subscription approver", "Wyznacz aprobującego obecne subskrypcje "}.

% mod_irc/mod_irc.erl
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Jeśli chcesz ustawić inne kodowanie dla serwerów IRC, wypełnij tą listę wartościami w formacie '{\"irc server\",\"encoding\"}'. Jako domyślne ten serwis używa kodowania \"~s\"."}.

% mod_muc/mod_muc.erl
{"Room creation is denied by service policy", "Tworzenie pokoju jest zabronione przez polisę"}.

% mod_vcard_odbc.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"ejabberd vCard module", "Erlang Jabber Server"}.
{"Search Results for ", "Wyniki wyszukiwania dla "}.
{"Jabber ID", "Jabber ID"}.

% mod_adhoc.erl
{"Commands", "Polecenia"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% ejabberd_c2s.erl
{"Replaced by new connection", "Podmienione przez nowe połączenie"}.

% mod_announce.erl
{"Send announcement to all users on all hosts", "Wyślij powiadomienie do wszystkich użytkowników na wszystkich hostach"}.
{"Set message of the day on all hosts and send to online users", "Ustaw wiadomość dnia dla wszystkich hostów i wyślij do uzytkowników online"}.
{"Update message of the day on all hosts (don't send)", "Odśwież wiadomośc dnia na wszystkich hostach (nie wysyłaj)"}.
{"Delete message of the day on all hosts", "Usuń wiadomość dnia ze wszystkich hostów"}.
{"Really delete message of the day?", "Na pewno usunąć wiadomość dnia?"}.
{"Subject", "Temat"}.
{"Message body", "Treść wiadomości"}.
{"No body provided for announce message", "Nikt nie jest uprawniony do rozsyłania oznajmień"}.
{"Announcements", "Oznajmienia"}.
{"Send announcement to all users", "Wyślij oznajmienie do wszystkich użytkowników"}.
{"Send announcement to all online users", "Wyślij oznajmienie do wszystkich użytkowników online"}.
{"Send announcement to all online users on all hosts", "Wyślij oznajmienie do wszystkich użytkowników online na wszystkich hostach"}.
{"Set message of the day and send to online users", "Wyślij wiadomość dnia do wszystkich użytkowników online"}.
{"Update message of the day (don't send)", "Zmień wiadomość dnia (nie wysyłaj)"}.
{"Delete message of the day", "Usuń wiadomość dnia"}.

% mod_configure.erl
{"Database", "Baza"}.
{"Outgoing s2s Connections", "Wychodzące połączenia s2s"}.
{"Import Users From jabberd 1.4 Spool Files", "Importuj użytkowników z plików spool serwera jabber 1.4"}.
{"Database Tables Configuration at ", "Konfiguracja tabel bazy na "}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Interface", "Interfejs WWW serwera ejabberd"}.
{"Administration", "Administracja"}.
{"Submitted", "Wprowadzone"}.
{"Bad format", "Zły format"}.
{"Users Last Activity", "Ostatnia aktywność użytkowników"}.
{"Registered Users", "Użytkownicy zarejestrowani"}.
{"Offline Messages", "Wiadomości offline"}.
{"Registered Users:", "Użytkownicy zarejestrowani:"}.
{"Authenticated Users:", "Użytkownicy autoryzowani:"}.
{"Online Users:", "Użytkownicy online:"}.
{"Outgoing s2s Connections:", "Wychodzące połączenia s2s:"}.
{"Outgoing s2s Servers:", "Serwery zewnętrzne s2s:"}.
{"Offline Messages:", "Wiadomości offline"}.
{"~s's Offline Messages Queue", "~s skolejkowanych wiadomości offline"}.
{"Add Jabber ID", "Dodaj JID"}.
{"No Data", "Brak danych"}.
{"Listened Ports", "Porty nasłuchujące"}.
{"RPC Call Error", "Błąd odwołania RPC"}.
{"Database Tables at ", "Tabele bazy na "}.
{"Backup of ", "Kopia zapasowa "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Te opcje backupują jedynie bazę Mnesia. Jeśli używasz modułu ODBC - musisz wykonać kopię SQL oddzielnie"}.
{"Store binary backup:", "Zachowaj kopię binarną:"}.
{"Restore binary backup immediately:", "Natychmiast odtwórz kopię binarną:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Odtwórz kopię binarną podczas następnego restaru ejabberd-a (wymaga mniej pamięci)"}.
{"Store plain text backup:", "Zachowaj kopię w czystym tekście"}.
{"Restore plain text backup immediately:", "Odtwórz kopię z czystego tekstu"}.
{"Statistics of ~p", "Statystyki ~p"}.
{"Uptime:", "Uptime"}.
{"CPU Time:", "Czas CPU"}.
{"Transactions Commited:", "Transakcje zakończone"}.
{"Transactions Aborted:", "Transakcje anulowane"}.
{"Transactions Restarted:", "Transakcje uruchomione ponownie"}.
{"Transactions Logged:", "Transakcje logowane"}.
{"Update ", "Uaktualnij"}.
{"Update plan", "Uaktualnij plan"}.
{"Updated modules", "Uaktualnione moduły"}.
{"Update script", "Uaktualnij skrypt"}.
{"Script check", "Sprawdź skrypt"}.
{"Not Found", "Nie znaleziono"}.
{"Shared Roster Groups", "Grupy współdzielone"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Konfiguracja pokoju zmodyfikowana"}.
{"joins the room", "dołączył(a) się do pokoju"}.
{"leaves the room", "opóścił(a) pokój"}.
{"has been kicked", "został(a) kopnięty(a)"}.
{"has been banned", "został(a) zabanowany(a)"}.
{"is now known as", "jest teraz znany(a) jako"}.
{"Monday", "Poniedziałek"}.
{"Tuesday", "Wtorek"}.
{"Wednesday", "Środa"}.
{"Thursday", "Czwartek"}.
{"Friday", "Piątek"}.
{"Saturday", "Sobota"}.
{"Sunday", "Niedziela"}.
{"January", "Styczeń"}.
{"February", "Luty"}.
{"March", "Marzec"}.
{"April", "Kwiecień"}.
{"May", "Maj"}.
{"June", "Czerwiec"}.
{"July", "Lipiec"}.
{"August", "Sierpień"}.
{"September", "Wrzesień"}.
{"October", "Październik"}.
{"November", "Listopad"}.
{"December", "Grudzień"}.
{"Room Configuration", "Konfiguracja pokoju"}.

% mod_muc/mod_muc.erl
{"You must fill in field \"Nickname\" in the form", "Musisz wypełnić pole NICKNAME w formularzu"}.

% mod_muc/mod_muc_room.erl
{"This room is not anonymous", "Pokój nie jest nieznany"}.
{"Make room persistent", "Utwórz pokój na stałe"}.
{"Make room public searchable", "Pozwól wyszukiwać pokój"}.
{"Make participants list public", "Upublicznij listę uczestników"}.
{"Make room password protected", "Zabezpiecz pokój hasłem"}.
{"Make room members-only", "Utwórz pokój tylko dla uczestnikóww"}.
{"Make room moderated", "Moderuj pokój"}.
{"Default users as participants", "Domyślni użytkownicy jako uczestnicy"}.
{"Allow users to change subject", "Pozwól użytkownikom zmienić tytuł pokoju"}.
{"Allow users to send private messages", "Pozwól użytkownikom wysyłać prywatne wiadomości"}.
{"Allow users to query other users", "Pozwól użytkownikom pobierać informacje o innych użytkownikach"}.
{"Allow users to send invites", "Pozwól użytkownikom wysyłać zaproszenia"}.
{"Enable logging", "Włącz logowanie"}.
{"Description", "Opis"}.
{"Number of occupants", "Liczba uczestników"}.

% mod_vcard_ldap.erl
{"Jabber ID", "Jabber ID"}.

% mod_presence.erl
{"You need an x:data capable client to register presence", "Potrzebujesz klinta kompatybilnego z x:data aby zarejestrować widoczność "}.
{"Presence registration at ", "Rejestracja widoczności na "}.
{"What presence features do you want to register?", "Jakie usługi widoczności chcesz zarejestrować?"}.
{"Specified presence is already registered", "Określona widoczność już jest zarejestrowana"}.
{"You must fill in field \"Xml\" in the form", "Musisz wypełnić w formularzu pole \"XML\""}.
{"You must fill in field \"Icon\" in the form", "Musisz wypełnić w formularzu pole \"Icon\""}.
{"Raw XML export", "Eksport XML do raw"}.
{"Allow icon export", "Pozwól na eksport ikon"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "Mudł SOCKS5 Bytestreams"}.

% mod_offline.erl
{"Your contact offline message queue is full. The message has been discarded.", "Twoja kolejka wiadomoci offline jest pełna. Wiadomoć została odrzucona."}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
