{"Access Configuration","Konfiguracja dostępu"}.
{"Access Control List Configuration","Konfiguracja listy dostępowej"}.
{"Access control lists","Lista dostępowa"}.
{"Access Control Lists","Lista dostępowa"}.
{"Access rules","Reguły dostępu"}.
{"Access Rules","Zasady dostępu"}.
{"Action on user","Wykonaj na użytkowniku"}.
{"Add Jabber ID","Dodaj Jabber ID"}.
{"Add New","Dodaj nowe"}.
{"Add User","Dodaj użytkownika"}.
{"Administration","Administracja"}.
{"Administration of ","Zarządzanie "}.
{"Administrator privileges required","Wymagane uprawnienia administratora"}.
{"A friendly name for the node","Przyjazna nazwa węzła"}.
{"All activity","Cała aktywność"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Pozwól temu Jabber ID na zapisanie się do tego węzła PubSub"}.
{"Allow users to change the subject","Pozwól użytkownikom zmieniać temat"}.
{"Allow users to query other users","Pozwól użytkownikom pobierać informacje o innych użytkownikach"}.
{"Allow users to send invites","Pozwól użytkownikom wysyłać zaproszenia"}.
{"Allow users to send private messages","Pozwól użytkownikom wysyłać prywatne wiadomości"}.
{"Allow visitors to change nickname","Pozwól uczestnikom na zmianę nicka"}.
{"Allow visitors to send status text in presence updates","Pozwól uczestnikom na wysyłanie statusów opisowych"}.
{"All Users","Wszyscy użytkownicy"}.
{"Announcements","Powiadomienia"}.
{"anyone","wszystkich"}.
{"A password is required to enter this room","Aby wejść do pokoju wymagane jest hasło"}.
{"April","Kwiecień"}.
{"August","Sierpień"}.
{"Backup Management","Zarządzanie kopiami zapasowymi"}.
{"Backup of ","Kopia zapasowa "}.
{"Backup to File at ","Zapisz kopię w pliku na "}.
{"Backup","Wykonaj kopie"}.
{"Bad format","Błędny format"}.
{"Birthday","Data urodzenia"}.
{"Change Password","Zmień hasło"}.
{"Change User Password","Zmień hasło użytkownika"}.
{"Choose a username and password to register with this server","Wybierz nazwę użytkownika i hasło aby zarejestrować się na tym serwerze"}.
{"Choose modules to stop","Wybierz moduły do zatrzymania"}.
{"Choose storage type of tables","Wybierz typ bazy dla tablel"}.
{"Choose whether to approve this entity's subscription.","Wybierz, czy akceptować subskrypcję tej jednostki"}.
{"City","Miasto"}.
{"Commands","Polecenia"}.
{"Configuration","Konfiguracja"}.
{"Configuration of room ~s","Konfiguracja pokoju ~s"}.
{"Connected Resources:","Zasoby zalogowane:"}.
{"Country","Państwo"}.
{"CPU Time:","Czas CPU:"}.
{"Database","Baza danych"}.
{"Database Tables at ","Tabele bazy na "}.
{"Database Tables Configuration at ","Konfiguracja tabel bazy na "}.
{"December","Grudzień"}.
{"Default users as participants","Domyślni użytkownicy jako uczestnicy"}.
{"Delete message of the day on all hosts","Usuń wiadomość dnia ze wszystkich hostów"}.
{"Delete message of the day","Usuń wiadomość dnia"}.
{"Delete Selected","Usuń zaznaczone"}.
{"Delete User","Usuń użytkownika"}.
{"Delete","Usuń"}.
{"Deliver event notifications","Dostarczaj powiadomienia o zdarzeniach"}.
{"Deliver payloads with event notifications","Dostarczaj zawartość publikacji wraz z powiadomieniami o zdarzeniach"}.
{"Description:","Opis:"}.
{"Disc only copy","Kopia tylko na dysku"}.
{"Dump Backup to Text File at ","Zapisz kopię zapasową w pliku tekstowym na "}.
{"Dump to Text File","Wykonaj kopie do pliku tekstowego"}.
{"Edit Properties","Edytuj właściwości"}.
{"ejabberd MUC module","Moduł MUC"}.
{"ejabberd Publish-Subscribe module","Moduł Publish-Subscribe"}.
{"ejabberd SOCKS5 Bytestreams module","Moduł SOCKS5 Bytestreams"}.
{"ejabberd vCard module","Moduł vCard ejabberd"}.
{"ejabberd Web Admin","ejabberd: Panel Administracyjny"}.
{"Elements","Elementy"}.
{"Email","Email"}.
{"Enable logging","Włącz logowanie"}.
{"End User Session","Zakończ sesję uzytkownika"}.
{"Enter list of {Module, [Options]}","Wprowadź listę {Moduł, [Opcje]}"}.
{"Enter nickname you want to register","Wprowadz nazwę użytkownika którego chcesz zarejestrować"}.
{"Enter path to backup file","Wprowadź scieżkę do pliku kopii zapasowej"}.
{"Enter path to jabberd14 spool dir","Wprowadź ścieżkę do roboczego katalogu serwera jabberd14"}.
{"Enter path to jabberd14 spool file","Wprowadź ścieżkę do roboczego pliku serwera jabberd14"}.
{"Enter path to text file","Wprowadź scieżkę do pliku tekstowego"}.
{"Enter the text you see","Przepisz tekst z obrazka"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Błąd"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Eksportuj dane wszystkich użytkowników serwera do plików w formacie PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Eksportuj dane użytkowników z hosta do plików w formacie PIEFXIS (XEP-0227):"}.
{"Family Name","Nazwisko"}.
{"February","Luty"}.
{"Fill in fields to search for any matching Jabber User","Wypełnij pola aby znaleźć pasujących użytkowników Jabbera"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Wypełnij formularz aby wyszukać użytkowników Jabbera (dodaj * na koniec zapytania aby wyszukać po fragmencie)"}.
{"Friday","Piątek"}.
{"From","Od"}.
{"From ~s","Od ~s"}.
{"Full Name","Pełna nazwa"}.
{"Get Number of Online Users","Pokaż liczbę zalogowanych użytkowników"}.
{"Get Number of Registered Users","Pokaż liczbę zarejestrowanych użytkowników"}.
{"Get User Last Login Time","Pokaż czas ostatniego zalogowania uzytkownika"}.
{"Get User Password","Pobierz hasło użytkownika"}.
{"Get User Statistics","Pobierz statystyki użytkownika"}.
{"Group ","Grupa "}.
{"Groups","Grupy"}.
{"has been banned","został wykluczony"}.
{"has been kicked because of an affiliation change","został wyrzucony z powodu zmiany przynależności"}.
{"has been kicked because of a system shutdown","został wyrzucony z powodu wyłączenia systemu"}.
{"has been kicked because the room has been changed to members-only","został wyrzucony z powodu zmiany pokoju na \"Tylko dla Członków\""}.
{"has been kicked","został wyrzucony"}.
{" has set the subject to: "," zmienił temat na: "}.
{"Host","Host"}.
{"Import Directory","Importuj katalog"}.
{"Import File","Importuj plik"}.
{"Import user data from jabberd14 spool file:","Importuj dane użytkownika z pliku roboczego serwera jabberd14:"}.
{"Import User from File at ","Importuj użytkownika z pliku na "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importuj dane użytkowników z pliku w formacie PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importuj użytkowników z katalogu roboczego serwera jabberd14"}.
{"Import Users from Dir at ","Importuj użytkowników z katalogu na "}.
{"Import Users From jabberd14 Spool Files","Importuj użytkowników z plików roboczych serwera jabberd14"}.
{"Improper message type","Nieprawidłowy typ wiadomości"}.
{"Incorrect password","Nieprawidłowe hasło"}.
{"Invalid affiliation: ~s","Nieprawidłowa przynależność: ~s"}.
{"Invalid role: ~s","Nieprawidłowa rola: ~s"}.
{"IP addresses","Adresy IP"}.
{"IP","IP"}.
{"is now known as","jest teraz znany jako"}.
{"It is not allowed to send private messages of type \"groupchat\"","Nie można wysyłać prywatnych wiadomości typu \"groupchat\""}.
{"It is not allowed to send private messages","Wysyłanie prywatnych wiadomości jest zabronione"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s jest niepoprawny"}.
{"January","Styczeń"}.
{"joins the room","dołącza do pokoju"}.
{"July","Lipiec"}.
{"June","Czerwiec"}.
{"Last Activity","Ostatnia aktywność"}.
{"Last login","Ostatnie logowanie"}.
{"Last month","Miniony miesiąc"}.
{"Last year","Miniony rok"}.
{"leaves the room","opuszcza pokój"}.
{"Listened Ports at ","Porty nasłuchujące na "}.
{"Listened Ports","Porty nasłuchujące"}.
{"List of modules to start","Lista modułów do uruchomienia"}.
{"Low level update script","Skrypt aktualizacji niskiego poziomu"}.
{"Make participants list public","Upublicznij listę uczestników"}.
{"Make room captcha protected","Pokój zabezpieczony captchą"}.
{"Make room members-only","Pokój tylko dla członków"}.
{"Make room moderated","Pokój moderowany"}.
{"Make room password protected","Pokój zabezpieczony hasłem"}.
{"Make room persistent","Utwórz pokój na stałe"}.
{"Make room public searchable","Pozwól wyszukiwać pokój"}.
{"March","Marzec"}.
{"Maximum Number of Occupants","Maksymalna liczba uczestników"}.
{"Max # of items to persist","Maksymalna liczba przechowywanych przedmiotów"}.
{"Max payload size in bytes","Maksymalna wielkość powiadomienia w bajtach"}.
{"May","Maj"}.
{"Members:","Członkowie:"}.
{"Membership is required to enter this room","Musisz być na liście członków tego pokoju aby do niego wejść"}.
{"Memory","Pamięć"}.
{"Message body","Treść wiadomości"}.
{"Middle Name","Drugie imię"}.
{"Moderator privileges required","Wymagane uprawnienia moderatora"}.
{"moderators only","tylko moderatorzy"}.
{"Modified modules","Zmodyfikowane moduły"}.
{"Module","Moduł"}.
{"Modules at ","Moduły na "}.
{"Modules","Moduły"}.
{"Monday","Poniedziałek"}.
{"Name","Imię"}.
{"Name:","Nazwa:"}.
{"Never","Nigdy"}.
{"Nickname","Nazwa użytkownika"}.
{"Nickname Registration at ","Rejestracja nazwy użytkownika na "}.
{"Nickname ~s does not exist in the room","Nie ma nicka ~s w tym pokoju"}.
{"No Data","Brak danych"}.
{"Node ID","ID węzła"}.
{"Node not found","Węzeł nie został znaleziony"}.
{"Nodes","Węzły"}.
{"Node ","Węzeł "}.
{"No limit","Bez limitu"}.
{"None","Brak"}.
{"Not Found","Nie znaleziono"}.
{"Notify subscribers when items are removed from the node","Informuj subskrybentów o usunięciu elementów węzła"}.
{"Notify subscribers when the node configuration changes","Informuj subskrybentów o zmianach konfiguracji węzła"}.
{"Notify subscribers when the node is deleted","Informuj subskrybentów o usunięciu węzła"}.
{"November","Listopad"}.
{"Number of occupants","Liczba uczestników"}.
{"Number of online users","Liczba zalogowanych użytkowników"}.
{"Number of registered users","Liczba zarejestrowanych użytkowników"}.
{"October","Październik"}.
{"Offline Messages:","Wiadomości offline:"}.
{"Offline Messages","Wiadomości offline"}.
{"OK","OK"}.
{"Online","Dostępny"}.
{"Online Users:","Użytkownicy zalogowani:"}.
{"Online Users","Użytkownicy zalogowani"}.
{"Only deliver notifications to available users","Dostarczaj powiadomienia tylko dostępnym użytkownikom"}.
{"Only moderators and participants are allowed to change the subject in this room","Tylko moderatorzy i uczestnicy mogą zmienić temat tego pokoju"}.
{"Only moderators are allowed to change the subject in this room","Tylko moderatorzy mogą zmienić temat tego pokoju"}.
{"Options","Opcje"}.
{"Organization Name","Nazwa organizacji"}.
{"Organization Unit","Dział"}.
{"Outgoing s2s Connections:","Wychodzące połączenia s2s:"}.
{"Outgoing s2s Connections","Wychodzące połączenia s2s"}.
{"Outgoing s2s Servers:","Serwery zewnętrzne s2s:"}.
{"Owner privileges required","Wymagane uprawnienia właściciela"}.
{"Packet","Pakiet"}.
{"Password:","Hasło:"}.
{"Password","Hasło"}.
{"Password Verification","Weryfikacja hasła"}.
{"Path to Dir","Ścieżka do katalogu"}.
{"Path to File","Scieżka do pliku"}.
{"Pending","Oczekuje"}.
{"Period: ","Przedział czasu: "}.
{"Persist items to storage","Przechowuj na stałe dane PubSub"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Te opcje kopii zapasowych dotyczą tylko wbudowanej bazy danych typu Mnesia. Jeśli korzystasz z modułu ODBC, musisz wykonać kopie bazy we własnym zakresie."}.
{"Pong","Pong"}.
{"Port","Port"}.
{"Present real Jabber IDs to","Prawdziwe Jabber ID widoczne dla"}.
{"private, ","prywatny, "}.
{"Protocol","Protokół"}.
{"Publish-Subscribe","PubSub"}.
{"PubSub subscriber request","Żądanie subskrybcji PubSub"}.
{"Purge all items when the relevant publisher goes offline","Usuń wszystkie elementy w momencie kiedy publikujący rozłączy się"}.
{"RAM and disc copy","Kopia na dysku i w pamięci RAM"}.
{"RAM copy","Kopia w pamięci RAM"}.
{"Raw","Żródło"}.
{"Really delete message of the day?","Na pewno usunąć wiadomość dnia?"}.
{"Registered Users:","Użytkownicy zarejestrowani:"}.
{"Registered Users","Użytkownicy zarejestrowani"}.
{"Remote copy","Kopia zdalna"}.
{"Remove All Offline Messages","Usuń wszystkie wiadomości typu 'Offline'"}.
{"Remove User","Usuń użytkownika"}.
{"Remove","Usuń"}.
{"Resources","Zasoby"}.
{"Restart Service","Restart usługi"}.
{"Restart","Uruchom ponownie"}.
{"Restore Backup from File at ","Odtwórz bazę danych z kopii zapasowej na "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Odtwórz kopię binarną podczas następnego uruchomienia ejabberd (wymaga mniej zasobów):"}.
{"Restore binary backup immediately:","Natychmiast odtwórz kopię binarną:"}.
{"Restore plain text backup immediately:","Natychmiast odtwórz kopię z postaci tekstowej:"}.
{"Restore","Przywróć z kopii"}.
{"Room Configuration","Konfiguracja pokoju"}.
{"Room description","Opis pokoju"}.
{"Room Occupants","Lista uczestników"}.
{"Room title","Tytuł pokoju"}.
{"Roster groups allowed to subscribe","Grupy kontaktów uprawnione do subskrypcji"}.
{"Roster","Lista kontaktów"}.
{"Roster of ","Lista kontaktów "}.
{"Roster size","Rozmiar listy kontaktów"}.
{"RPC Call Error","Błąd żądania RPC"}.
{"Running Nodes","Uruchomione węzły"}.
{"~s access rule configuration","~s konfiguracja zasad dostępu"}.
{"Saturday","Sobota"}.
{"Script check","Sprawdź skrypt"}.
{"Search Results for ","Wyniki wyszukiwania dla "}.
{"Search users in ","Wyszukaj użytkowników w "}.
{"Send announcement to all online users on all hosts","Wyślij powiadomienie do wszystkich zalogowanych użytkowników na wszystkich hostach"}.
{"Send announcement to all online users","Wyślij powiadomienie do wszystkich zalogowanych użytkowników"}.
{"Send announcement to all users on all hosts","Wyślij powiadomienie do wszystkich użytkowników na wszystkich hostach"}.
{"Send announcement to all users","Wyślij powiadomienie do wszystkich użytkowników"}.
{"September","Wrzesień"}.
{"Set message of the day and send to online users","Wyślij wiadomość dnia do wszystkich zalogowanych użytkowników"}.
{"Set message of the day on all hosts and send to online users","Ustaw wiadomość dnia dla wszystkich hostów i wyślij do zalogowanych uzytkowników"}.
{"Shared Roster Groups","Wspólne grupy kontaktów"}.
{"Show Integral Table","Pokaż tabelę całkowitą"}.
{"Show Ordinary Table","Pokaż zwykłą tabelę"}.
{"Shut Down Service","Wyłącz usługę"}.
{"~s invites you to the room ~s","~s zaprasza Cię do pokoju ~s"}.
{"Specify the access model","Określ model dostępu"}.
{"Specify the event message type","Określ typ wiadomości"}.
{"Specify the publisher model","Określ model publikującego"}.
{"~s's Offline Messages Queue","Kolejka wiadomości offline użytkownika ~s"}.
{"Start Modules at ","Uruchom moduły na "}.
{"Start Modules","Uruchom moduły"}.
{"Start","Uruchom"}.
{"Statistics of ~p","Statystyki ~p"}.
{"Statistics","Statystyki"}.
{"Stop Modules at ","Zatrzymaj moduły na "}.
{"Stop Modules","Zatrzymaj moduły"}.
{"Stopped Nodes","Zatrzymane węzły"}.
{"Stop","Zatrzymaj"}.
{"Storage Type","Typ bazy"}.
{"Store binary backup:","Zachowaj kopię binarną:"}.
{"Store plain text backup:","Zachowaj kopię w postaci tekstowej:"}.
{"Subject","Temat"}.
{"Submitted","Wprowadzone"}.
{"Submit","Wyślij"}.
{"Subscriber Address","Adres subskrybenta"}.
{"Subscription","Subskrypcja"}.
{"Sunday","Niedziela"}.
{"That nickname is already in use by another occupant","Ta nazwa użytkownika jest używana przez kogoś innego"}.
{"That nickname is registered by another person","Ta nazwa użytkownika jest już zarejestrowana przez inną osobę"}.
{"The captcha is valid.","Captcha jest poprawna."}.
{"The collections with which a node is affiliated","Grupy, do których należy węzeł"}.
{"the password is","hasło to:"}.
{"This participant is kicked from the room because he sent an error message","Ten uczestnik został wyrzucony z pokoju ponieważ wysłał komunikat błędu"}.
{"This participant is kicked from the room because he sent an error message to another participant","Ten uczestnik został wyrzucony z pokoju ponieważ wysłał komunikat błędu do innego uczestnika"}.
{"This participant is kicked from the room because he sent an error presence","Ten uczestnik został wyrzucony z pokoju ponieważ jego informacja o statusie zawierała błędy"}.
{"This room is not anonymous","Ten pokój nie jest anonimowy"}.
{"Thursday","Czwartek"}.
{"Time","Czas"}.
{"Time delay","Opóźnienie"}.
{"To","Do"}.
{"To ~s","Do ~s"}.
{"Traffic rate limit is exceeded","Limit transferu przekroczony"}.
{"Transactions Aborted:","Transakcje anulowane:"}.
{"Transactions Committed:","Transakcje zakończone:"}.
{"Transactions Logged:","Transakcje zalogowane:"}.
{"Transactions Restarted:","Transakcje uruchomione ponownie:"}.
{"Tuesday","Wtorek"}.
{"Unable to generate a captcha","Nie można wygenerować captcha"}.
{"Unauthorized","Nie autoryzowano"}.
{"Update","Aktualizuj"}.
{"Update message of the day (don't send)","Aktualizuj wiadomość dnia (bez wysyłania)"}.
{"Update message of the day on all hosts (don't send)","Aktualizuj wiadomość dnia na wszystkich hostach (bez wysyłania)"}.
{"Update plan","Plan aktualizacji"}.
{"Update script","Skrypt aktualizacji"}.
{"Update ","Uaktualnij "}.
{"Uptime:","Czas pracy:"}.
{"User Management","Zarządzanie użytkownikami"}.
{"Users Last Activity","Ostatnia aktywność użytkowników"}.
{"Users","Użytkownicy"}.
{"User ","Użytkownik "}.
{"User","Użytkownik"}.
{"Validate","Potwierdź"}.
{"vCard User Search","Wyszukiwanie vCard użytkowników"}.
{"Virtual Hosts","Wirtualne Hosty"}.
{"Visitors are not allowed to change their nicknames in this room","Uczestnicy tego pokoju nie mogą zmieniać swoich nicków"}.
{"Visitors are not allowed to send messages to all occupants","Odwiedzający nie mogą wysyłać wiadomości do wszystkich obecnych"}.
{"Wednesday","Środa"}.
{"When to send the last published item","Kiedy wysłać ostatnio opublikowaną rzecz"}.
{"Whether to allow subscriptions","Czy pozwolić na subskrypcje"}.
{"You have been banned from this room","Zostałeś wykluczony z tego pokoju"}.
{"You must fill in field \"Nickname\" in the form","Musisz wypełnić pole \"Nazwa użytkownika\" w formularzu"}.
{"You need an x:data capable client to configure room","Potrzebujesz klienta obsługującego x:data aby skonfigurować pokój"}.
{"You need an x:data capable client to register nickname","Potrzebujesz klienta obsługującego x:data aby zarejestrować nick"}.
{"You need an x:data capable client to search","Potrzebujesz klienta obsługującego x:data aby wyszukiwać"}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Twoje wiadomości do ~s są blokowane. Aby je odblokować, odwiedź ~s"}.
