% $Id$
% Brazilian Portuguese translation
% Author: Victor Hugo dos Santos



% jlib.hrl
{"No resource provided", "Recurso não foi fornecido"}.


% mod_configure.erl
{"Access Configuration", "Configuração de Acesso"}.
{"Access Control List Configuration", "Configuração da Lista de Controle de Acesso"}.
{"Access control lists", "Listas de Controle de Acesso"}.
{"Access rules", "Regras de acesso"}.
{"Action on user", "Ação no usuário"}.
{"Administration of ", "Administração de "}.
{"Backup to File at ", "Salvar cópia de segurança para arquivo em "}.
{"Choose modules to stop", "Selecione módulos a parar"}.
{"Choose storage type of tables", "Selecione o tipo de armazenamento das tabelas"}.
{"Choose users to remove", "Selecione usuários para remoção"}.
{"Disc only copy", "Copia em disco somente"}.
{"Dump Backup to Text File at ", "Exporta cópia de segurança para arquivo de texto em "}.
{"Edit Properties", "Editar propriedades"}.
{"Enter list of {Module, [Options]}", "Introduza lista de {módulo, [opções]}"}.
{"Enter path to backup file", "Introduza o caminho do arquivo de cópia de segurança"}.
{"Enter path to jabberd1.4 spool dir", "Introduza o caminho para o diretório de spools do jabberd1.4"}.
{"Enter path to jabberd1.4 spool file", "Introduza o caminho para o arquivo de spool do jabberd1.4"}.
{"Enter path to text file", "Introduza caminho para o arquivo de texto"}.
{"Import User from File at ", "Importar usuário a partir do arquivo em "}.
{"Import Users from Dir at ", "Importar usuários a partir do diretório em "}.
{"Path to Dir", "Caminho para o diretório"}.
{"Path to File", "Caminho do arquivo"}.
{"RAM and disc copy", "Copia em RAM y disco"}.
{"RAM copy", "Copia em RAM"}.
{"Remote copy", "Copia remota"}.
{"Remove User", "Remover usuário"}.
{"Remove Users", "Remover usuários"}.
{"Restore Backup from File at ", "Restaura cópia de segurança a partir do arquivo em "}.
{"Start Modules at ", "Iniciar módulos em "}.
{"Nome Modules at ", "Parar módulos em "}.


% mod_disco.erl
{"Access Control Lists", "Listas de Controle de Acesso"}.
{"Access Rules", "Regras de Aceso"}.
{"All Users", "Todos os usuários"}.
{"Backup", "Salvar cópia de segurança"}.
{"Backup Management", "Gestão de copia de segurança"}.
{"Configuration", "Configuração"}.
{"DB", "BD"}.
{"Dump to Text File", "Exportar para arquivo de texto"}.
{"From ~s", "De ~s"}.
{"Máquina Name", "Nome da máquina"}.
{"Import Directory", "Importar diretório"}.
{"Import File", "Importar arquivo"}.
{"Import users from jabberd1.4 spool files", "Importar usuários a partir de arquivos da spool do jabberd1.4"}.
{"Modules", "Módulos"}.
{"Online Users", "Usuários conectados"}.
{"Outgoing S2S connections", "Conexões S2S de saída"}. 
{"Remove Users", "Remover usuários"}.
{"Restore", "Restaurar"}.
{"Running Nodes", "Nos em execução"}.
{"Start Modules", "Iniciar módulos"}.
{"Stop Modules", "Parar módulos"}.
{"Stopped Nodes", "Nos parados"}.
{"To ~s", "Para ~s"}.


% mod_register.erl
{"Choose a username and password to register with this server", "Escolha um nome de usuário e senha para registrar-se neste servidor"}.


% mod_vcard.erl
{"Birthday","Aniversário"}.
{"City", "Cidade"}.
{"Country","País"}.
{"ejabberd vCard module\nCopyright (c) 2003-2005 Alexey Shchepin", "Módulo vCard para ejabberd\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"email", "e-mail"}.
{"Erlang Jabber Server\nCopyright (c) 2002-2005 Alexey Shchepin", "Servidor Jabber em Erlang\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"Family Name", "Nome de família"}.
{"Fill in fields to search for any matching Jabber User", "Preencha os campos para procurar usuários Jabber coincidentes"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Preencha o formulário para buscar usuários Jabber. Agrega * ao final de um campo para buscar sub-palavras."}.
{"Full Name", "Nome completo"}.
{"Middle Name", "Apelido"}.
{"Name", "Nome"}.
{"Nickname", "Nick"}.
{"Organization Name", "Nome da organização"}.
{"Organization Unit", "Unidade da organização"}.
{"Results of search in ", "Resultados da busca em "}.
{"Search users in ", "Procurar usuários em "}.
{"User", "Usuário"}.
{"You need an x:data capable client to search", "Necessitas um cliente com suporte de x:data para poder buscar"}.
% mod_pubsub/mod_pubsub.erl


{[], " "}.
{"Deliver payloads with event notifications", "Enviar payloads junto com as notificações de eventos"}.
{"ejabberd pub/sub module\nCopyright (c) 2003-2005 Alexey Shchepin", "Módulo Pub/Sub para ejabberd\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"Max # of items to persist", "Máximo # de elementos que persistem"}.
{"Max payload size in bytes", "Máximo tamanho do payload em bytes"}.
{"Node Creator", "Criador do nodo"}.
{"Notify subscribers when items are removed from the node", "Notificar subscritores quando os elementos se eliminem do nodo"}.
{"Notify subscribers when the node configuration changes", "Notificar subscritores quando cambia la configuração do nodo"}.
{"Notify subscribers when the node is deleted", "Notificar subscritores quando o nodo se elimine"}.
{"Only deliver notifications to available users", "Solo enviar notificações aos usuários disponíveis"}.
{"Persist items to storage", "Persistir elementos ao armazenar"}.
{"Send items to new subscribers", "Enviar elementos aos  novos subscritores"}.
{"Specify the current subscription approver", "Especificar o aprobador da subscrição atual"}.
{"Specify the publisher model", "Especificar o modelo do publicante"}.
{"Specify the subscriber model", "Especificar o modelo de subscrição"}.
{"Whether to allow subscriptions", "Permitir subscrições"}.

% mod_muc/mod_muc.erl
{"Allow users to change subject?", "Permitir aos usuários mudar o tópico?"}.
{"Allow users to query other users?", "Permitir aos usuários consultar outros usuários?"}.
{"Allow users to send invites?", "Permitir que os usuários enviem convites?"}.
{"Allow users to send private messages?", "Permitir que os usuários enviem mensagens privadas?"}.
{"Default users as members?", "Os usuários padrão são membros?"}.
{"Enable logging?", "Salvar históricos?"}.
{"Access denied by service policy", "Aceso denegado por la política do serviço"}.
{"Conference room does not exist", "La sala de conferencias não existe"}.
{"ejabberd MUC module\nCopyright (c) 2003-2005 Alexey Shchepin", "Módulo de MUC para ejabbed\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"Enter nickname you want to register", "Introduza o apelido que quer registrar"}.
{"Incorrect password", "Senha incorreta"}.
{"Make room anonymous?", "Tornar a sala anônima?"}.
{"Make room password protected?", "Proteger a sala com senha?"}.
{"Nickname is already in use by another occupant", "O apelido já está em uso por outro ocupante"}.
{"Nickname is registered by another person", "O apelido já está registrado por outra pessoa"}.
{"Nickname Registration at ", "Registro do apelido em "}.
{"Nickname ~s does not exist in the room", "Apelido ~s não existe na sala"}.
{"Password required to enter this room", "É necessária a senha para poder entrar nesta sala"}.
{"Password", "Senha"}.
{"Room creation is denied by service policy", "Se te a denegado criar la sala por política do serviço"}.
{"Specified nickname is already registered", "O apelido especificado já está registrado"}.
{"You must fill in field \"nick\" in the form", "Deve preencher o campo \"apelido\" no formulário"}.
{"You need an x:data capable client to register nickname", "Necessitas um cliente com suporte de x:data para poder registrar o nick"}.

% mod_muc/mod_muc_room.erl
{"Administrator privileges required", "Se necessita privilégios de administrador"}.
{"Allow users to change subject?", "Permitir aos usuários cambiar o assunto"}.
{"Allow users to query other users?", "Permitir aos usuários consultar a outros usuários"}.
{"Allow users to send invites?", "Permitir aos usuários enviar convides"}.
{"Allow users to send private messages?", "Permitir aos usuários enviar mensagens privados"}.
{"Configuration for ", "Configuração para "}.
{"Default users as members?", "Os usuários são membros por defeito"}.
{"Enable logging?", "Guardar históricos"}.
{" has set the subject to: ", " a posto o assunto: "}.
{"Improper message type", "Tipo de mensagem incorreto"}.
{"Incorrect password", "Senha incorreta"}.
{"Invalid affiliation: ~s", "Afiliação não válida: ~s"}.
{"Invalid role: ~s", "Rol não válido: ~s"}.
{"It is not allowed to send normal messages to the conference", "Impedir o envio de mensagens normais a la sala"}.
{"It is not allowed to send private messages of type \"groupchat\"", "No está permitido enviar mensagens privados do tipo \"groupchat\""}.
{"It is not allowed to send private messages to the conference", "Impedir o envio de mensagens privados a la sala"}.
{"JID ~s is invalid", "O JID ~s não es válido"}.
{"Make participants list public?", "Fazer pública la lista de participantes"}.
{"Make room anonymous?", "Fazer anônima la sala"}.
{"Make room members only?", "Fazer la sala solo para membros"}.
{"Make room moderated?", "Fazer la sala moderada"}.
{"Make room password protected?", "Proteger la sala com senha"}.
{"Make room persistent?", "Fazer la sala permanente"}.
{"Make room public searchable?", "Fazer a sala publicamente visível"}.
{"Membership required to enter this room", "Necessitas ser membro de esta sala para poder entrar"}.
{"Moderator privileges required", "Se necessita privilégios de moderador"}.
{"Nickname is already in use by another occupant", "O nick já está sendo usado por outro ocupante"}.
{"Nickname is registered by another person", "O nick já está registrado por outra pessoa"}.
{"Nickname ~s does not exist in the room", "O nick ~s não existe em la sala"}.
{"Only moderators and participants are allowed to change subject in this room", "Solo os moderadores y participantes podem cambiar o assunto de esta sala"}.
{"Only moderators are allowed to change subject in this room", "Solo os moderadores podem cambiar o assunto de esta sala"}.
{"Only occupants are allowed to send messages to the conference", "Solo os ocupantes podem enviar mensagens a la sala"}.
{"Only occupants are allowed to send queries to the conference", "Solo os ocupantes podem enviar consultas a la sala"}.
{"Owner privileges required", "Se requere privilégios de proprietário da sala"}.
{"Password", "Senha"}.
{"Password required to enter this room", "Se necessita senha para entrar em esta sala"}.
{"private, ", "privado"}.
{"Queries to the conference members are not allowed in this room", "Nesta sala não se permite consultas aos membros da sala"}.
{"Recipient is not in the conference room", "O receptor não está em la sala de conferencia"}.
{"Room title", "Título da sala"}.
{"Visitors are not allowed to send messages to all occupants", "Os visitantes não podem enviar mensagens a todos os ocupantes"}.
{"You have been banned from this room", "As sido bloqueado em esta sala"}.
{"You need an x:data capable client to configure room", "Necessitas um cliente com suporte de x:data para configurar la sala"}.


% mod_irc/mod_irc.erl
{"ejabberd IRC module\nCopyright (c) 2003-2005 Alexey Shchepin", "Módulo de IRC para ejabberd\nCopyright (c) 2002-2005 Alexey Shchepin"}.
{"Encodings", "Codificação"}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Introduza o nome de usuário e codificações de caracteres que quer usar ao conectar-se aos servidores de IRC"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Exemplo: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Se deseja especificar codificações de caracteres diferentes para cada servidor IRC preencha esta lista com valores no formato '{\"servidor irc\", \"codificação\"}'.  Este serviço usa por padrão a codificação \"~s\"."}.
{"IRC Username", "Nome de usuário no IRC"}.
{"Registration in mod_irc for ", "Registro em mod_irc para"}.
{"You need an x:data capable client to configure mod_irc settings", "Necessitas um cliente com suporte de x:data para configurar las opções de mod_irc"}.


% web/ejabberd_web_admin.erl
{"Add JID", "Adicionar JID"}.
{"Add New", "Adicionar novo"}.
{"Add User", "Adicionar usuário"}.
{"All activity", "Toda la atividade"}.
{"Authentificated users", "Usuários autenticados"}.
{"Backup Management at ", "Gestão de copia de segurança em "}.
{"bad format", "mal formato"}.
{"Change Password", "Mudar senha"}.
{"Connected Resources:", "Recursos conectados:"}.
{"CPU Time", "Tempo de processador consumido"}.
{"DB Management", "Gestão do BD"}.
{"DB Tables at ", "Tabelas do BD em "}.
{"Delete", "Eliminar"}.
{"Delete Selected", "Remover os selecionados"}.
{"Dump a database in a text file", "Exportar uma Base de Dados para um arquivo de texto"}.
{"ejabberd access control lists configuration", "Configuração das Listas de Controle de Acesso do ejabberd"}.
{"ejabberd access rules configuration", "Configuração de las Regras de Aceso de ejabberd"}.
{"ejabberd administration", "Administração de ejabberd"}.
{"ejabberd (c) 2002-2005 Alexey Shchepin, 2004-2005 Process One", "ejabberd (c) 2002-2005 Alexey Shchepin, 2004-2005 Process One"}.
{"ejabberd stats", "Estatísticas de ejabberd"}.
{"ejabberd users", "Usuários do ejabberd"}.
{"ejabberd virtual hosts", "Maquinas virtuais de ejabberd"}.
{"From", "De"}.
{"Group ", "Grupo "}.
{"Groups", "Grupos"}.
{"Host", "Máquina"}.
{"Install a database fallback from a file", "Instalar uma recuperação de BD a partir de um arquivo"}.
{"JID", "JID"}.
{"Last Activity", "Última atividade"}.
{"Last month", "Último mês"}.
{"Last year", "Último ano"}.
{"Listened Ports at ", "Portas de escuta em "}.
{"Listened Ports Management", "Gestão dos portas de escuta"}.
{"Members:", "Miembros:"}.
{"Memory", "Memória"}.
{"Module", "Módulo"}.
{"Modules at ", "Módulos em "}.
{"Modules Management", "Gestão de módulos"}.
{"Name:", "Nome:"}.
{"Name", "Nome"}.
{"Never", "Nunca"}.
{"Nickname", "Apelido"}.
{"Online", "Conectado"}.
{"Online users", "Usuários conectados"}.
{"Options", "Opções"}.
{"Outgoing S2S servers", "Servidores conectados"}.
{"Packet", "Pacote"}.
{"Password:", "Senha:"}.
{"Pending", "Pendente"}.
{"Period: ", "Período: "}.
{"Port", "Porta"}.
{"~p statistics", "Estatísticas de ~p"}.
{"(raw)", "(cru)"}.
{"raw", "cru"}.
{"Registered users", "Usuários registrados"}.
{"Remove", "Borrar"}.
{"Restart", "Reiniciar"}.
{"Restore a backup from a file", "Recuperar uma cópia de segurança a partir do arquivo"}.
{"Restore a database from a text file", "Restaurar uma Base de Dados a partir de um arquivo de texto"}.
{"Roster", "Lista de contatos"}.
{"Roster of ", "Lista de contatos de "}.
{"RPC call error", "Erro em la chamada RPC"}.
{"~s access rule configuration", "Configuração da Regra de Acesso ~s"}.
{"Shared roster groups", "Grupos compartilhado"}.
{"Shared Roster", "Lista de contatos compartilhada"}.
{"Show Integral Table", "Mostrar Tabela Integral"}.
{"Show Ordinary Table", "Mostrar Tabela Ordinária"}.
{"Size", "Tamanho"}.
{"~s offline messages queue", "~s cola de mensagens diferidos"}.
{"Start", "Iniciar"}.
{"Statistics", "Estatísticas"}.
{"Stop", "Parar"}.
{"Storage Type", "Tipo de armazenamento"}.
{"Store a backup in a file", "Armazenar uma cópia de segurança no arquivo"}.
{"Submit", "Enviar"}.
{"submitted", "enviado"}.
{"Subscription", "Subscrição"}.
{"Time", "Fecha"}.
{"To", "Para"}.
{"Transactions aborted", "Transações abortadas"}.
{"Transactions commited", "Transações realizadas"}.
{"Transactions logged", "Transações armazenadas"}.
{"Transactions restarted", "Transações reiniciadas"}.
{"Update", "Atualizar"}.
{"Uptime", "Tempo de funcionamento"}.
{"Users last activity", "Última atividades dos usuários"}.
{"Users", "Usuários"}.
{"User ", "Usuário"}.
{"Validate", "Validar"}.
{"Virtual Hosts", "Maquinas Virtuais"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "É obrigatório usar STARTTLS"}.


% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Preencha campos para buscar usuários Jabber que concordem"}.
{"Given Name", "Nome dado"}.
{"JID", "JID"}.


% Local Variables:
% mode: erlang
% End:
