{"Access Configuration","Configuração de Acesso"}.
{"Access Control List Configuration","Configuração da Lista de Controle de Acesso"}.
{"Access control lists","Listas de Controle de Acesso"}.
{"Access Control Lists","Listas de Controle de Acesso"}.
{"Access denied by service policy","Aceso denegado por la política do serviço"}.
{"Access Rules","Regras de Aceso"}.
{"Access rules","Regras de acesso"}.
{"Action on user","Ação no usuário"}.
{"Add Jabber ID","Adicionar ID jabber"}.
{"Add New","Adicionar novo"}.
{"Add User","Adicionar usuário"}.
{"Administration","Administração"}.
{"Administration of ","Administração de "}.
{"Administrator privileges required","Se necessita privilégios de administrador"}.
{"A friendly name for the node","Um nome familiar para o nó"}.
{"All activity","Toda la atividade"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Autorizar este JID para a inscrição neste tópico pubsub ?"}.
{"Allow users to change subject","Permitir a usuários modificar o assunto"}.
{"Allow users to query other users","Permitir a usuários pesquisar informações sobre os demais"}.
{"Allow users to send invites","Permitir a usuários envio de convites"}.
{"Allow users to send private messages","Permitir a usuários enviarem mensagens privadas"}.
{"Allow visitors to change nickname","Permitir mudança de apelido aos visitantes"}.
{"Allow visitors to send status text in presence updates","Permitir atualizações de status aos visitantes"}.
{"All Users","Todos os usuários"}.
{"Announcements","Anúncios"}.
{"anyone","qualquer um"}.
{"April","Abril"}.
{"August","Agosto"}.
{"Backup Management","Gestão de copia de segurança"}.
{"Backup of ","Backup de"}.
{"Backup","Salvar cópia de segurança"}.
{"Backup to File at ","Salvar cópia de segurança para arquivo em "}.
{"Bad format","Formato incorreto"}.
{"Birthday","Aniversário"}.
{"Change Password","Mudar senha"}.
{"Change User Password","Alterar Senha do Usuário"}.
{"Chatroom configuration modified","Configuração da sala de bate-papo modificada"}.
{"Chatrooms","Salas de Chat"}.
{"Choose a username and password to register with this server","Escolha um nome de usuário e senha para registrar-se neste servidor"}.
{"Choose modules to stop","Selecione módulos a parar"}.
{"Choose storage type of tables","Selecione o tipo de armazenamento das tabelas"}.
{"Choose whether to approve this entity's subscription.","Aprovar esta assinatura."}.
{"City","Cidade"}.
{"Commands","Comandos"}.
{"Conference room does not exist","La sala de conferencias não existe"}.
{"Configuration","Configuração"}.
{"Configuration for ","Configuração para "}.
{"Connected Resources:","Recursos conectados:"}.
{"Country","País"}.
{"CPU Time:","Tempo de CPU"}.
{"Database","Base de dados"}.
{"Database Tables at ","Tabelas de base de dados em"}.
{"Database Tables Configuration at ","Configuração de Tabelas de Base de dados em "}.
{"December","Dezembro"}.
{"Default users as participants","Usuários padrões como participantes"}.
{"Delete","Eliminar"}.
{"Delete message of the day","Apagar mensagem do dia"}.
{"Delete message of the day on all hosts","Apagar a mensagem do dia em todos os hosts"}.
{"Delete Selected","Remover os selecionados"}.
{"Delete User","Deletar Usuário"}.
{"Deliver event notifications","Entregar as notificações de evento"}.
{"Deliver payloads with event notifications","Enviar payloads junto com as notificações de eventos"}.
{"Description:","Descrição:"}.
{"Disc only copy","Copia em disco somente"}.
{"Displayed Groups:","Grupos Indicados"}.
{"Dump Backup to Text File at ","Exporta cópia de segurança para arquivo de texto em "}.
{"Dump to Text File","Exportar para arquivo de texto"}.
{"Edit Properties","Editar propriedades"}.
{"ejabberd IRC module","Módulo de IRC para ejabberd"}.
{"ejabberd MUC module","Módulo de MUC para ejabberd"}.
{"ejabberd Publish-Subscribe module","Módulo para Publicar Tópicos do ejabberd"}.
{"ejabberd SOCKS5 Bytestreams module","Modulo ejabberd SOCKS5 Bytestreams"}.
{"ejabberd vCard module","Módulo vCard para ejabberd"}.
{"ejabberd virtual hosts","Maquinas virtuais de ejabberd"}.
{"ejabberd Web Admin","ejabberd Web Admin"}.
{"Email","e-mail"}.
{"Enable logging","Permitir criação de logs"}.
{"Encodings","Codificação"}.
{"End User Session","Terminar Sessão do Usuário"}.
{"Enter list of {Module, [Options]}","Introduza lista de {módulo, [opções]}"}.
{"Enter nickname you want to register","Introduza o apelido que quer registrar"}.
{"Enter path to backup file","Introduza o caminho do arquivo de cópia de segurança"}.
{"Enter path to jabberd14 spool dir","Introduza o caminho para o diretório de spools do jabberd14"}.
{"Enter path to jabberd14 spool file","Introduza o caminho para o arquivo de spool do jabberd14"}.
{"Enter path to text file","Introduza caminho para o arquivo de texto"}.
{"Enter username and encodings you wish to use for connecting to IRC servers","Introduza o nome de usuário e codificações de caracteres que quer usar ao conectar-se aos servidores de IRC"}.
{"Erlang Jabber Server","Servidor Jabber em Erlang"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].","Exemplo: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Family Name","Nome de família"}.
{"February","Fevereiro"}.
{"Fill in fields to search for any matching Jabber User","Preencha campos para buscar usuários Jabber que concordem"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Preencha o formulário para buscar usuários Jabber. Agrega * ao final de um campo para buscar sub-palavras."}.
{"Friday","Sexta"}.
{"From","De"}.
{"From ~s","De ~s"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Obter Número de Usuários Online"}.
{"Get Number of Registered Users","Obter Número de Usuários Registrados"}.
{"Get User Last Login Time","Obter a Data do Último Login"}.
{"Get User Password","Obter Senha do Usuário"}.
{"Get User Statistics","Obter Estatísticas do Usuário"}.
{"Group ","Grupo "}.
{"Groups","Grupos"}.
{"has been banned","foi banido"}.
{"has been kicked because of an affiliation change","foi desconectado porque por afiliação inválida"}.
{"has been kicked because of a system shutdown","foi desconectado porque o sistema foi desligado"}.
{"has been kicked because the room has been changed to members-only","foi desconectado porque a política da sala mudou, só membros são permitidos"}.
{"has been kicked","foi removido"}.
{" has set the subject to: "," a posto o assunto: "}.
{"Host","Máquina"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","Se deseja especificar codificações de caracteres diferentes para cada servidor IRC preencha esta lista com valores no formato '{\"servidor irc\", \"codificação\"}'.  Este serviço usa por padrão a codificação \"~s\"."}.
{"Import Directory","Importar diretório"}.
{"Import File","Importar arquivo"}.
{"Import User from File at ","Importar usuário a partir do arquivo em "}.
{"Import Users from Dir at ","Importar usuários a partir do diretório em "}.
{"Import Users From jabberd14 Spool Files","Importar usuários de arquivos jabberd14"}.
{"Improper message type","Tipo de mensagem incorreto"}.
{"Incorrect password","Senha incorreta"}.
{"Invalid affiliation: ~s","Afiliação não válida: ~s"}.
{"Invalid role: ~s","Rol não válido: ~s"}.
{"IP addresses","Endereços IP"}.
{"IRC Transport","IRC Transport"}.
{"IRC Username","Nome de usuário no IRC"}.
{"is now known as","é agora conhecido como"}.
{"It is not allowed to send private messages","Não é permitido enviar mensagens privadas"}.
{"It is not allowed to send private messages of type \"groupchat\"","No está permitido enviar mensagens privados do tipo \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Impedir o envio de mensagens privados a la sala"}.
{"Jabber ID","ID Jabber"}.
{"January","Janeiro"}.
{"Jabber ID ~s is invalid","O JID ~s não es válido"}.
{"joins the room","Entrar na sala"}.
{"July","Julho"}.
{"June","Junho"}.
{"Last Activity","Última atividade"}.
{"Last login","Último login"}.
{"Last month","Último mês"}.
{"Last year","Último ano"}.
{"leaves the room","Sair da sala"}.
{"Listened Ports at ","Portas de escuta em "}.
{"Listened Ports","Portas escutadas"}.
{"List of modules to start","Listas de módulos para inicializar"}.
{"Low level update script","Script de atualização low level"}.
{"Make participants list public","Tornar pública a lista de participantes"}.
{"Make room members-only","Tornar sala apenas para membros"}.
{"Make room moderated","Tornar a sala moderada"}.
{"Make room password protected","Tornar protegida a senha da sala"}.
{"Make room persistent","Tornar sala persistente"}.
{"Make room public searchable","Tornar sala pública possível de ser encontrada"}.
{"March","Março"}.
{"Maximum Number of Occupants","Número máximo de participantes"}.
{"Max # of items to persist","Máximo # de elementos que persistem"}.
{"Max payload size in bytes","Máximo tamanho do payload em bytes"}.
{"May","Maio"}.
{"Membership required to enter this room","Necessitas ser membro de esta sala para poder entrar"}.
{"Members:","Miembros:"}.
{"Memory","Memória"}.
{"Message body","Corpo da mensagem"}.
{"Middle Name","Apelido"}.
{"Moderator privileges required","Se necessita privilégios de moderador"}.
{"moderators only","apenas moderadores"}.
{"Module","Módulo"}.
{"Modules at ","Módulos em "}.
{"Modules","Módulos"}.
{"Monday","Segunda"}.
{"Name:","Nome:"}.
{"Name","Nome"}.
{"Never","Nunca"}.
{"Nickname","Apelido"}.
{"Nickname is already in use by another occupant","O nick já está sendo usado por outro ocupante"}.
{"Nickname is registered by another person","O nick já está registrado por outra pessoa"}.
{"Nickname Registration at ","Registro do apelido em "}.
{"Nickname ~s does not exist in the room","O nick ~s não existe em la sala"}.
{"No body provided for announce message","Nenhum corpo de texto fornecido para anunciar mensagem"}.
{"No Data","Nenhum dado"}.
{"Node ID","ID do Tópico"}.
{"Node ","Nó"}.
{"Node not found","Nó não encontrado"}.
{"Nodes","Nós"}.
{"No limit","Ilimitado"}.
{"None","Nenhum"}.
{"No resource provided","Recurso não foi fornecido"}.
{"Notify subscribers when items are removed from the node","Notificar subscritores quando os elementos se eliminem do nodo"}.
{"Notify subscribers when the node configuration changes","Notificar subscritores quando cambia la configuração do nodo"}.
{"Notify subscribers when the node is deleted","Notificar subscritores quando o nodo se elimine"}.
{"November","Novembro"}.
{"Number of occupants","Número de participantes"}.
{"Number of online users","Número de usuários online"}.
{"Number of registered users","Número de usuários registrados"}.
{"October","Outubro"}.
{"Offline Messages:","Mensagens offline"}.
{"Offline Messages","Mensagens offline"}.
{"OK","OK"}.
{"Online","Conectado"}.
{"Online Users","Usuários conectados"}.
{"Online Users:","Usuários online"}.
{"Only deliver notifications to available users","Solo enviar notificações aos usuários disponíveis"}.
{"Only moderators and participants are allowed to change subject in this room","Solo os moderadores y participantes podem cambiar o assunto de esta sala"}.
{"Only moderators are allowed to change subject in this room","Solo os moderadores podem cambiar o assunto de esta sala"}.
{"Only occupants are allowed to send messages to the conference","Solo os ocupantes podem enviar mensagens a la sala"}.
{"Only occupants are allowed to send queries to the conference","Solo os ocupantes podem enviar consultas a la sala"}.
{"Only service administrators are allowed to send service messages","Apenas administradores possuem permissão para enviar mensagens de serviço"}.
{"Options","Opções"}.
{"Organization Name","Nome da organização"}.
{"Organization Unit","Unidade da organização"}.
{"Outgoing s2s Connections","Conexões que partam de s2s"}.
{"Outgoing s2s Connections:","Conexões que partem de s2s"}.
{"Outgoing s2s Servers:","Servidores que partem de s2s"}.
{"Owner privileges required","Se requere privilégios de proprietário da sala"}.
{"Packet","Pacote"}.
{"Password required to enter this room","Se necessita senha para entrar em esta sala"}.
{"Password:","Senha:"}.
{"Password","Senha"}.
{"Password Verification","Verificação de Senha"}.
{"Path to Dir","Caminho para o diretório"}.
{"Path to File","Caminho do arquivo"}.
{"Pending","Pendente"}.
{"Period: ","Período: "}.
{"Persist items to storage","Persistir elementos ao armazenar"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","Porta"}.
{"Present real Jabber IDs to","Tornar o JID real visível por"}.
{"private, ","privado"}.
{"Publish-Subscribe","Publicação de Tópico"}.
{"PubSub subscriber request","PubSub requisição de assinante"}.
{"Queries to the conference members are not allowed in this room","Nesta sala não se permite consultas aos membros da sala"}.
{"RAM and disc copy","Copia em RAM y disco"}.
{"RAM copy","Copia em RAM"}.
{"(Raw)","(Intocado)"}.
{"Raw","Intocado"}.
{"Really delete message of the day?","Deletar realmente a mensagem do dia?"}.
{"Recipient is not in the conference room","O receptor não está em la sala de conferencia"}.
{"Registered Users:","Usuários registrados"}.
{"Registered Users","Usuários Registrados"}.
{"Registration in mod_irc for ","Registro em mod_irc para"}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Observe que tais opções farão backup apenas da base de dados Mnesia. Caso você esteja utilizando o modulo ODBC, você precisará fazer backup de sua base de dados SQL separadamente."}.
{"Remote copy","Copia remota"}.
{"Remove","Borrar"}.
{"Remove User","Remover usuário"}.
{"Replaced by new connection","Substituído por nova conexão"}.
{"Resources","Recursos"}.
{"Restart","Reiniciar"}.
{"Restart Service","Reiniciar Serviço"}.
{"Restore Backup from File at ","Restaura cópia de segurança a partir do arquivo em "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Restaurar backup binário após próximo reinicialização do ejabberd (requer menos memória):"}.
{"Restore binary backup immediately:","Restaurar backup binário imediatamente"}.
{"Restore plain text backup immediately:","Restaurar backup plain text imediatamente:"}.
{"Restore","Restaurar"}.
{"Room Configuration","Configuração de salas"}.
{"Room creation is denied by service policy","Se te a denegado criar la sala por política do serviço"}.
{"Room title","Título da sala"}.
{"Roster groups allowed to subscribe","Listar grupos autorizados"}.
{"Roster","Lista de contatos"}.
{"Roster of ","Lista de contatos de "}.
{"Roster size","Tamanho da Lista"}.
{"RPC Call Error","Erro de chamada RPC"}.
{"Running Nodes","Nos em execução"}.
{"~s access rule configuration","Configuração da Regra de Acesso ~s"}.
{"Saturday","Sábado"}.
{"Script check","Verificação de Script"}.
{"Search Results for ","Resultados de pesquisa para"}.
{"Search users in ","Procurar usuários em "}.
{"Send announcement to all online users","Enviar anúncio a todos os usuárions online"}.
{"Send announcement to all online users on all hosts","Enviar anúncio a todos usuários online em todas as máquinas"}.
{"Send announcement to all users","Enviar anúncio a todos os usuários"}.
{"Send announcement to all users on all hosts","Enviar aviso para todos os usuários em todos os hosts"}.
{"September","Setembro"}.
{"Set message of the day and send to online users","Definir mensagem do dia e enviar a todos usuários online"}.
{"Set message of the day on all hosts and send to online users","Definir mensagem do dia em todos os hosts e enviar para os usuários online"}.
{"Shared Roster Groups","Grupos Shared Roster"}.
{"Show Integral Table","Mostrar Tabela Integral"}.
{"Show Ordinary Table","Mostrar Tabela Ordinária"}.
{"Shut Down Service","Parar Serviço"}.
{"~s invites you to the room ~s","~s convidou você para a sala ~s"}.
{"Size","Tamanho"}.
{"Specified nickname is already registered","O apelido especificado já está registrado"}.
{"Specify the access model","Especificar os modelos de acesso"}.
{"Specify the publisher model","Especificar o modelo do publicante"}.
{"~s's Offline Messages Queue","~s's Fila de Mensagens Offline"}.
{"Start","Iniciar"}.
{"Start Modules at ","Iniciar módulos em "}.
{"Start Modules","Iniciar módulos"}.
{"Statistics","Estatísticas"}.
{"Statistics of ~p","Estatísticas de ~p"}.
{"Stop Modules at ","Parar módulos em "}.
{"Stop Modules","Parar módulos"}.
{"Stop","Parar"}.
{"Stopped Nodes","Nos parados"}.
{"Storage Type","Tipo de armazenamento"}.
{"Store binary backup:","Armazenar backup binário:"}.
{"Store plain text backup:","Armazenar backup plain text"}.
{"Subject","Assunto"}.
{"Submit","Enviar"}.
{"Submitted","Submetido"}.
{"Subscriber Address","Enderço dos Assinantes"}.
{"Subscription","Subscrição"}.
{"Sunday","Domingo"}.
{"the password is","a senha é"}.
{"This participant is kicked from the room because he sent an error message","Este participante foi desconectado da sala de chat por ter enviado uma mensagem de erro."}.
{"This participant is kicked from the room because he sent an error message to another participant","Este participante foi desconectado da sala de chat por ter enviado uma mensagem de erro para outro usuário."}.
{"This participant is kicked from the room because he sent an error presence","Este participante foi desconectado da sala de chat por ter enviado uma notificação errônea de presença."}.
{"This room is not anonymous","Essa sala não é anônima"}.
{"Thursday","Quinta"}.
{"Time delay","Intervalo de Tempo"}.
{"Time","Fecha"}.
{"To","Para"}.
{"To ~s","Para ~s"}.
{"Traffic rate limit is exceeded","Limite de banda excedido"}.
{"Transactions Aborted:","Transações abortadas:"}.
{"Transactions Committed:","Transações:"}.
{"Transactions Logged:","Transações de log:"}.
{"Transactions Restarted:","Transações restauradas:"}.
{"Tuesday","Terça"}.
{"Update ","Atualizar"}.
{"Update","Atualizar"}.
{"Updated modules","Módulos atualizados"}.
{"Update message of the day (don't send)","Atualizar mensagem do dia (não enviar)"}.
{"Update message of the day on all hosts (don't send)","Atualizar a mensagem do dia em todos os host (não enviar)"}.
{"Update plan","Plano de Atualização"}.
{"Update script","Script de atualização"}.
{"Uptime:","Uptime:"}.
{"Use of STARTTLS required","É obrigatório usar STARTTLS"}.
{"User Management","Gerenciamento de Usuários"}.
{"Users are not allowed to register accounts so fast","Usuários ainda não podem registrar novas contas"}.
{"Users Last Activity","Ultimas atividades dos usuários"}.
{"Users","Usuários"}.
{"User ","Usuário"}.
{"User","Usuário"}.
{"Validate","Validar"}.
{"vCard User Search","Busca de Usuário vCard"}.
{"Virtual Hosts","Maquinas Virtuais"}.
{"Visitors are not allowed to change their nicknames in this room","Nesta sala, os visitantes não pode mudar seus apelidos"}.
{"Visitors are not allowed to send messages to all occupants","Os visitantes não podem enviar mensagens a todos os ocupantes"}.
{"Wednesday","Quarta"}.
{"When to send the last published item","Quando enviar o último tópico publicado"}.
{"Whether to allow subscriptions","Permitir subscrições"}.
{"You have been banned from this room","As sido bloqueado em esta sala"}.
{"You must fill in field \"Nickname\" in the form","Você deve completar o campo \"Apelido\" no formulário"}.
{"You need an x:data capable client to configure mod_irc settings","Necessitas um cliente com suporte de x:data para configurar las opções de mod_irc"}.
{"You need an x:data capable client to configure room","Necessitas um cliente com suporte de x:data para configurar la sala"}.
{"You need an x:data capable client to register nickname","Necessitas um cliente com suporte de x:data para poder registrar o nick"}.
{"You need an x:data capable client to search","Necessitas um cliente com suporte de x:data para poder buscar"}.
{"Your contact offline message queue is full. The message has been discarded.","Sua fila de mensagens offline esta cheia. Sua mensagem foi descartada"}.
