% $Id$

% Brazilian Portuguese translation
% Author: Felipe Brito Vasconcellos
% Only strings that differ from pt.msg are included

% mod_configure.erl
{"Choose storage type of tables", "Selecione o tipo de armazenamento das tabelas"}.
{"Backup to File at ", "Salvar cópia de segurança para arquivo em "}.
{"Enter path to backup file", "Introduza o caminho do arquivo de cópia de segurança"}.
{"Path to File", "Caminho do arquivo"}.
{"Restore Backup from File at ", "Restaura cópia de segurança a partir do arquivo em "}.
{"Dump Backup to Text File at ", "Exporta cópia de segurança para arquivo de texto em "}.
{"Enter path to text file", "Introduza caminho para o arquivo de texto"}.
{"Import User from File at ", "Importar usuário a partir do arquivo em "}.
{"Enter path to jabberd1.4 spool file", "Introduza o caminho para o arquivo de spool do jabberd1.4"}.
{"Import Users from Dir at ", "Importar usuários a partir do diretório em "}.
{"Enter path to jabberd1.4 spool dir", "Introduza o caminho para o diretório de spools do jabberd1.4"}.
{"Path to Dir", "Caminho para o diretório"}.
{"Access Control List Configuration", "Configuração da Lista de Controle de Acesso"}.
{"Access control lists", "Listas de Controle de Acesso"}.
{"Remove Users", "Remover usuários"}.
{"Choose users to remove", "Selecione usuários para remoção"}.
{"Action on user", "Ação no usuário"}.
{"Remove User", "Remover usuário"}.

% mod_disco.erl
{"Online Users", "Usuários conectados"}.
{"All Users", "Todos os usuários"}.
{"To ~s", "Para ~s"}.
{"Running Nodes", "Nodos em execução"}.
{"Access Control Lists", "Listas de Controle de Acesso"}.
{"Remove Users", "Remover usuários"}.
{"Import users from jabberd1.4 spool files", "Importar usuários a partir de arquivos da spool do jabberd1.4"}.
{"Backup", "Salvar cópia de segurança"}.
{"Dump to Text File", "Exportar para arquivo de texto"}.
{"Import File", "Importar arquivo"}.
{"Import Directory", "Importar diretório"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Escolha um nome de usuário e senha para se registar neste servidor"}.

% mod_vcard.erl
{"Search users in ", "Procurar usuários em "}.
{"Fill in fields to search for any matching Jabber User", "Preencha os campos para procurar usuários Jabber coincidentes"}.
{"User",              "Usuário"}.
{"Family Name",       "Nome de família"}.
{"Nickname", 	      "Apelido"}.

% mod_muc/mod_muc.erl
{"Nickname Registration at ", "Registo do apelido em "}.
{"Enter nickname you want to register", "Introduza o apelido que quer registar"}.
{"You must fill in field \"nick\" in the form", "Deve preencher o campo \"apelido\" no formulário"}.
{"Specified nickname is already registered", "O apelido especificado já está registado"}.
{"Allow users to change subject?", "Permitir aos usuários mudar o tópico?"}.
{"Allow users to query other users?", "Permitir aos usuários consultar outros usuários?"}.
{"Allow users to send private messages?", "Permitir que os usuários enviem mensagens privadas?"}.
{"Default users as members?", "Os usuários padrão são membros?"}.
{"Allow users to send invites?", "Permitir que os usuários enviem convites?"}.
{"Make room password protected?", "Proteger a sala com senha?"}.
{"Password", "Senha"}.
{"Make room anonymous?", "Tornar a sala anônima?"}.
{"Enable logging?", "Salvar históricos?"}.
{"Nickname is already in use by another occupant", "O apelido já está em uso por outro ocupante"}.
{"Nickname is registered by another person", "O apelido já está registado por outra pessoa"}.
{"Password required to enter this room", "É necessária a senha para poder entrar nesta sala"}.
{"Incorrect password", "Senha incorrecta"}.
{"Nickname ~s does not exist in the room", "Apelido ~s não existe na sala"}.

% mod_irc/mod_irc.erl
{"Enter username and encodings you wish to use for connecting to IRC servers", "Introduza o nome de usuário e codificações de caracteres que quer usar ao conectar-se aos servidores de IRC"}.
{"IRC Username", "Nome de usuário no IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Se deseja especificar codificações de caracteres diferentes para cada servidor IRC preencha esta lista con valores no formato '{\"servidor irc\", \"codificação\"}'.  Este serviço usa por padrão a codificação \"~s\"."}.

% web/ejabberd_web_admin.erl
{"Users", "Usuários"}.
{"ejabberd access control lists configuration", "Configuração das Listas de Controle de Acesso do ejabberd"}.
{"Delete Selected", "Remover os selecionados"}.
{"~s access rule configuration", "Configuração da Regra de Acesso ~s"}.
{"ejabberd users", "Usuários do ejabberd"}.
{"Registered users", "Usuários registados"}.
{"Authentificated users", "Usuários autenticados"}.
{"Online users", "Usuários conectados"}.
{"Change Password", "Mudar senha"}.
{"Password:", "Senha:"}.
{"DB Management", "Gestão do BD"}.
{"DB Tables at ", "Tabelas do BD em "}.
{"Storage Type", "Tipo de armazenamento"}.
{"Store a backup in a file", "Armazenar uma cópia de segurança no arquivo"}.
{"Restore a backup from a file", "Recuperar uma cópia de segurança a partir do arquivo"}.
{"Install a database fallback from a file", "Instalar uma recuperação de BD a partir de um arquivo"}.
{"Dump a database in a text file", "Exportar uma Base de Dados para um arquivo de texto"}.
{"Restore a database from a text file", "Restaurar uma Base de Dados a partir de um arquivo de texto"}.
{"Update", "Atualizar"}.
{"Add User", "Adicionar usuário"}.
{"Last Activity", "Última atividade"}.
{"Online", "Concetado"}.
{"Roster", "Lista de contatos"}.
{"Nickname", "Apelido"}.
{"User ", "Usuário"}.
{"Roster of ", "Lista de contatos de "}.
{"Shared Roster", "Lista de contatos compartilhada"}.

% Local Variables:
% mode: erlang
% End:
