% $Id$
% Language: Portuguese (português)
% Author: Iceburn

% jlib.hrl
{"No resource provided", "Não foi passado nenhum recurso"}.

% mod_configure.erl
{"DB Tables Configuration at ", "Configuração de tabelas da BD em "}.
{"Choose storage type of tables", "Seleccione o tipo de armazenagem das tabelas"}.
{"RAM copy", "Cópia em RAM"}.
{"RAM and disc copy", "Cópia em RAM e em disco"}.
{"Disc only copy", "Cópia apenas em disco"}.
{"Remote copy", "Cópia remota"}.
{"Stop Modules at ", "Parar módulos em "}.
{"Choose modules to stop", "Seleccione os módulos a parar"}.
{"Start Modules at ", "Iniciar os módulos em "}.
{"Enter list of {Module, [Options]}", "Introduza lista de {módulos, [opções]}"}.
{"List of modules to start", "Lista de módulos a iniciar"}.
{"Backup to File at ", "Guardar cópia de segurança para ficheiro em "}.
{"Enter path to backup file", "Introduza o caminho do ficheiro de cópia de segurança"}.
{"Path to File", "Caminho do ficheiro"}.
{"Restore Backup from File at ", "Restaura cópia de segurança a partir do ficheiro em "}.
{"Dump Backup to Text File at ", "Exporta cópia de segurança para ficheiro de texto em "}.
{"Enter path to text file", "Introduza caminho para o ficheiro de texto"}.
{"Import User from File at ", "Importar utilizador a partir do ficheiro em "}.
{"Enter path to jabberd1.4 spool file", "Introduza o caminho para o ficheiro de spool do jabberd1.4"}.
{"Import Users from Dir at ", "Importar utilizadores a partir do directório em "}.
{"Enter path to jabberd1.4 spool dir", "Introduza o caminho para o directório de spools do jabberd1.4"}.
{"Path to Dir", "Caminho para o directório"}.
{"Hostname Configuration", "Configuração do nome do servidor"}.
{"Choose host name", "Introduza o nome do servidor"}.
{"Host name", "Nome do servidor"}.
{"Access Control List Configuration", "Configuração da Lista de Controlo de Acesso"}.
{"Access control lists", "Listas de Controlo de Acesso"}.
{"Access Configuration", "Configuração de acessos"}.
{"Access rules", "Regras de acesso"}.
{"Remove Users", "Eliminar utilizadores"}.
{"Choose users to remove", "Seleccione utilizadores a eliminar"}.
{"Administration of ", "Administração de "}.
{"Action on user", "Acção no utilizador"}.
{"Edit Properties", "Editar propriedades"}.
{"Remove User", "Eliminar utilizador"}.

% mod_disco.erl
{"Configuration", "Configuração"}.
{"Online Users", "Utilizadores ligados"}.
{"All Users", "Todos os utilizadores"}.
{"Outgoing S2S connections", "Conexões S2S para fora"}.
{"To ~s", "A ~s"}.
{"From ~s", "De ~s"}.
{"Running Nodes", "Nodos a correr"}.
{"Stopped Nodes", "Nodos parados"}.
{"Host Name", "Nome do servidor"}.
{"Access Control Lists", "Listas de Controlo de Acesso"}.
{"Access Rules", "Regras de Acesso"}.
{"Remove Users", "Eliminar utilizadores"}.
{"DB", "BD"}.
{"Modules", "Módulos"}.
{"Start Modules", "Iniciar módulos"}.
{"Stop Modules", "Parar módulos"}.
{"Backup Management", "Gestão de cópias de segurança"}.
{"Import users from jabberd1.4 spool files", "Importar utilizadores a partir de ficheiros da spool do jabberd1.4"}.
{"Backup", "Guardar cópia de segurança"}.
{"Restore", "Restaurar"}.
{"Dump to Text File", "Exportar para ficheiro de texto"}.
{"Import File", "Importar ficheiro"}.
{"Import Directory", "Importar directório"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Escolha um nome de utilizador e palavra-chave para se registar neste servidor"}.

% mod_vcard.erl
{"Erlang Jabber Server", "Servidor Jabber em Erlang"}.
{"ejabberd vCard module", "Módulo vCard de ejabberd"}.
{"You need an x:data capable client to search", "É necessário um cliente com suporte de x:data para poder procurar"}.
{"Search users in ", "Procurar utilizadores em "}.
{"Fill in fields to search for any matching Jabber User", "Preencha os campos para procurar utilizadores Jabber coincidentes"}.
{"Results of search in ", "Resultados da procura em "}.
{"User",              "Utilizador"}.
{"Full Name", 	      "Nome completo"}.
{"Name", 	      "Nome"}.
{"Middle Name",       "Segundo nome"}.
{"Family Name",       "Apelido"}.
{"Nickname", 	      "Alcunha"}.
{"Birthday", 	      "Data de nascimento"}.
{"Country", 	      "País"}.
{"City", 	      "Cidade"}.
{"email", 	      "email"}.
{"Organization Name", "Nome da organização"}.
{"Organization Unit", "Unidade da organização"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module", "Módulo pub/sub de ejabberd"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "É necessário um cliente com suporte de x:data para poder registar a alcunha"}.
{"Nickname Registration at ", "Registo da alcunha em "}.
{"Enter nickname you want to register", "Introduza a alcunha que quer registar"}.
{"ejabberd MUC module", "Módulo MUC de ejabberd"}.
{"Only service administrators are allowed to send service messages", "Só os administradores do serviço têm permissão para enviar mensagens de serviço"}.
{"Conference room does not exist", "A sala não existe"}.
{"Access denied by service policy", "Acesso negado pela política de serviço"}.
{"You must fill in field \"nick\" in the form", "Deve preencher o campo \"alcunha\" no formulário"}.
{"Specified nickname is already registered", "A alcunha especificada já está registada"}.

% mod_muc/mod_muc_room.erl
{"Make room moderated", "Tornar a sala moderada"}.
{" has set the subject to: ", " colocou o tópico: "}.
{"You need an x:data capable client to configure room", "É necessário um cliente com suporte de x:data para configurar a sala"}.
{"Configuration for ", "Configuração para "}.
{"Room title", "Título da sala"}.
{"Allow users to change subject?", "Permitir aos utilizadores mudar o tópico?"}.
{"Allow users to query other users?", "Permitir aos utilizadores consultar outros utilizadores?"}.
{"Allow users to send private messages?", "Permitir que os utilizadores enviem mensagens privadas?"}.
{"Make room public searchable?", "Tornar a sala publicamente visível?"}.
{"Make participants list public?", "Tornar pública a lista de participantes?"}.
{"Make room persistent?", "Tornar a sala permanente?"}.
{"Make room moderated?", "Tornar a sala moderada?"}.
{"Default users as members?", "Os utilizadores são membros por omissão?"}.
{"Make room members only?", "Tornar a sala exclusiva a membros?"}.
{"Allow users to send invites?", "Permitir que os utilizadores enviem convites?"}.
{"Make room password protected?", "Proteger a sala com palavra-chave?"}.
{"Password", "Palavra-chave"}.
{"Make room anonymous?", "Tornar a sala anónima?"}.
{"Enable logging?", "Guardar históricos?"}.
{"Only moderators and participants are allowed to change subject in this room", "Só os moderadores e os participantes podem mudar o tópico desta sala"}.
{"Only moderators are allowed to change subject in this room", "Só os moderadores podem mudar o tópico desta sala"}.
{"Visitors are not allowed to send messages to all occupants", "Os visitantes não podem enviar mensagens para todos os ocupantes"}.
{"Only occupants are allowed to send messages to the conference", "Só os ocupantes podem enviar mensagens para a sala"}.
{"It is not allowed to send normal messages to the conference", "Impedir o envio de mensagens normais para a sala"}.
{"It is not allowed to send private messages to the conference", "Impedir o envio de mensagens privadas para a sala"}.
{"Improper message type", "Tipo de mensagem incorrecto"}.
{"Nickname is already in use by another occupant", "A alcunha já está a ser usado por outro ocupante"}.
{"Nickname is registered by another person", "A alcunha já está registada por outra pessoa"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Não é permitido enviar mensagens privadas do tipo \"groupchat\""}.
{"Recipient is not in the conference room", "O destinatário não está na sala"}.
{"Only occupants are allowed to send queries to the conference", "Só os ocupantes podem enviar consultas para a sala"}.
{"Queries to the conference members are not allowed in this room", "Nesta sala não são permitidas consultas aos seus membros"}.
{"You have been banned from this room", "Foi banido desta sala"}.
{"Membership required to enter this room", "É necessário ser membro desta sala para poder entrar"}.
{"Password required to enter this room", "É necessária a palavra-chave para poder entrar nesta sala"}.
{"Incorrect password", "Palavra-chave incorrecta"}.
{"Administrator privileges required", "São necessários privilégios de administrador"}.
{"Moderator privileges required", "São necessários privilégios de moderador"}.
{"JID ~s is invalid", "O JID ~s não é válido"}.
{"Nickname ~s does not exist in the room", "A alcunha ~s não existe na sala"}.
{"Invalid affiliation: ~s", "Afiliação inválida: ~s"}.
{"Invalid role: ~s", "Papel inválido: ~s"}.
{"Owner privileges required", "São necessários privilégios de dono"}.
{"private, ", "privado"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "Módulo de IRC ejabberd"}.
{"You need an x:data capable client to configure mod_irc settings", "É necessário um cliente com suporte de x:data para configurar as opções do mod_irc"}.
{"Registration in mod_irc for ", "Registo no mod_irc para"}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Introduza o nome de utilizador e codificações de caracteres que quer usar ao conectar-se aos servidores de IRC"}.
{"IRC Username", "Nome do utilizador de IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Se deseja especificar codificações de caracteres diferentes para cada servidor IRC preencha esta lista con valores no formato '{\"servidor irc\", \"codificação\"}'.  Este serviço usa por omissão a codificação \"~s\"."}.
{"Encodings", "Codificações"}.

% web/ejabberd_web_admin.erl
{"ejabberd administration", "Administração do ejabberd"}.
{"Users", "Utilizadores"}.
{"Nodes", "Nodos"}.
{"Statistics", "Estatísticas"}.
{"(raw)", "(modo texto)"}.
{"submitted", "enviado"}.
{"bad format", "formato inválido"}.
{"raw", "modo texto"}.
{"ejabberd access control lists configuration", "Configuração das Listas de Controlo de Acesso do ejabberd"}.
{"Delete Selected", "Eliminar os seleccionados"}.
{"Submit", "Enviar"}.
{"ejabberd access rules configuration", "Configuração das Regras de Acesso do ejabberd"}.
{"~s access rule configuration", "Configuração das Regra de Acesso ~s"}.
{"ejabberd users", "Utilizadores do ejabberd"}.
{"ejabberd stats", "Estatísticas do ejabberd"}.
{"Node not found", "Nodo não encontrado"}.
{"Add New", "Adicionar novo"}.
{"Registered users", "Utilizadores registados"}.
{"Online users", "Utilizadores ligados"}.
{"Outgoing S2S servers", "Servidores S2S de saída"}.
{"Change Password", "Mudar palavra-chave"}.
{"Connected Resources:", "Recursos conectados:"}.
{"Password:", "Palavra-chave:"}.
{"None", "Nenhum"}.
{"Node ", "Nodo"}.
{"DB Management", "Gestão da BD"}.
{"Listened Ports Management", "Gestão das portas em escuta"}.
{"Restart", "Reiniciar"}.
{"Stop", "Parar"}.
{"RPC call error", "Erro na chamada RPC"}.
{"DB Tables at ", "Tabelas da BD em "}.
{"Name", "Nome"}.
{"Storage Type", "Tipo de armazenagem"}.
{"Size", "Tamanho"}.
{"Memory", "Memória"}.
{"Backup Management at ", "Gestão da cópia de segurança em "}.
{"Store a backup in a file", "Armazenar uma cópia de segurança no ficheiro"}.
{"OK", "OK"}.
{"Restore a backup from a file", "Recuperar uma cópia de segurança a partir de ficheiro"}.
{"Install a database fallback from a file", "Instalar uma recuperação de BD desde um ficheiro"}.
{"Dump a database in a text file", "Exportar uma Base de Dados para um ficheiro de texto"}.
{"Restore a database from a text file", "Restaurar uma Base de Dados a partir de ficheiro de texto"}.
{"Listened Ports at ", "Portas em escuta em "}.
{"~p statistics", "Estatísticas de ~p"}.
{"Uptime", "Tempo de funcionamento"}.
{"CPU Time", "Tempo de processador consumido"}.
{"Transactions commited", "Transacções realizadas"}.
{"Transactions aborted", "Transacções abortadas"}.
{"Transactions restarted", "Transacções reiniciadas"}.
{"Transactions logged", "Transacções armazenadas"}.
{"Port", "Porta"}.
{"Module", "Módulo"}.
{"Options", "Opções"}.
{"Update", "Actualizar"}.
{"Delete", "Eliminar"}.
{"Add User", "Adicionar utilizador"}.
{"ejabberd (c) 2002-2005 Alexey Shchepin, 2005 Process One", "ejabberd (c) 2002-2005 Alexey Shchepin, 2005 Process One"}.
{"Offline messages", "Mensagens diferidas"}.
{"Last Activity", "Última actividade"}.
{"Online", "Ligado"}.
{"Never", "Nunca"}.
{"~s offline messages queue", "~s fila de mensagens diferidas"}.
{"Time", "Data"}.
{"From", "De"}.
{"To", "Para"}.
{"Packet", "Pacote"}.
{"Offline messages:", "Mensagens diferidas:"}.
{"Roster", "Lista de contactos"}.
{"Nickname", "Alcunha"}.
{"Subscription", "Subscrição"}.
{"Pending", "Pendente"}.
{"Groups", "Grupos"}.
{"Remove", "Remover"}.
{"Add JID", "Adicionar JID"}.
{"User ", "Utilizador"}.
{"Roster of ", "Lista de contactos de "}.
{"Shared Roster", "Lista de contactos partilhada"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
