{"Access Configuration","Конфигурация доступа"}.
{"Access Control List Configuration","Конфигурация списков управления доступом"}.
{"Access control lists","Списки управления доступом"}.
{"Access Control Lists","Списки управления доступом"}.
{"Access denied by service policy","Доступ запрещён политикой службы"}.
{"Access rules","Правила доступа"}.
{"Access Rules","Правила доступа"}.
{"Action on user","Действие над пользователем"}.
{"Add Jabber ID","Добавить Jabber ID"}.
{"Add New","Добавить"}.
{"Add User","Добавить пользователя"}.
{"Administration of ","Администрирование "}.
{"Administration","Администрирование"}.
{"Administrator privileges required","Требуются права администратора"}.
{"A friendly name for the node","Легко запоминаемое имя для узла"}.
{"All activity","Вся статистика"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Разрешить этому JID подписаться на данный узел?"}.
{"Allow users to change subject","Разрешить пользователям изменять тему"}.
{"Allow users to query other users","Разрешить iq-запросы к пользователям"}.
{"Allow users to send invites","Разрешить пользователям посылать приглашения"}.
{"Allow users to send private messages","Разрешить приватные сообщения"}.
{"Allow visitors to change nickname","Разрешить посетителям изменять псевдоним"}.
{"Allow visitors to send status text in presence updates","Разрешить посетителям вставлять текcт статуса в сообщения о присутствии"}.
{"All Users","Все пользователи"}.
{"Announcements","Объявления"}.
{"anyone","всем участникам"}.
{"April","апреля"}.
{"August","августа"}.
{"Backup Management","Управление резервным копированием"}.
{"Backup of ","Резервное копирование "}.
{"Backup to File at ","Резервное копирование в файл на "}.
{"Backup","Резервное копирование"}.
{"Bad format","Неправильный формат"}.
{"Birthday","День рождения"}.
{"Change Password","Сменить пароль"}.
{"Change User Password","Изменить пароль пользователя"}.
{"Chatroom configuration modified","Конфигурация комнаты изменилась"}.
{"Chatrooms","Комнаты"}.
{"Choose a username and password to register with this server","Выберите имя пользователя и пароль для регистрации на этом сервере"}.
{"Choose modules to stop","Выберите модули, которые следует остановить"}.
{"Choose storage type of tables","Выберите тип хранения таблиц"}.
{"Choose whether to approve this entity's subscription.","Решите: предоставить ли подписку этому объекту."}.
{"City","Город"}.
{"Commands","Команды"}.
{"Conference room does not exist","Конференция не существует"}.
{"Configuration for ","Конфигурация "}.
{"Configuration","Конфигурация"}.
{"Connected Resources:","Подключённые ресурсы:"}.
{"Country","Страна"}.
{"CPU Time:","Процессорное время:"}.
{"Database Tables at ","Таблицы базы данных на "}.
{"Database Tables Configuration at ","Конфигурация таблиц базы данных на "}.
{"Database","База данных"}.
{"December","декабря"}.
{"Default users as participants","Сделать пользователей участниками по умолчанию"}.
{"Delete message of the day on all hosts","Удалить сообщение дня со всех виртуальных серверов"}.
{"Delete message of the day","Удалить сообщение дня"}.
{"Delete Selected","Удалить выделенные"}.
{"Delete User","Удалить пользователя"}.
{"Delete","Удалить"}.
{"Deliver event notifications","Доставлять уведомления о событиях"}.
{"Deliver payloads with event notifications","Доставлять вместе с уведомлениями o публикациях сами публикации"}.
{"Description:","Описание:"}.
{"Disc only copy","только диск"}.
{"Displayed Groups:","Видимые группы:"}.
{"Dump Backup to Text File at ","Копирование в текстовый файл на "}.
{"Dump to Text File","Копирование в текстовый файл"}.
{"Edit Properties","Изменить параметры"}.
{"ejabberd IRC module","ejabberd IRC модуль"}.
{"ejabberd MUC module","ejabberd MUC модуль"}.
{"ejabberd Publish-Subscribe module","Модуль ejabberd Публикации-Подписки"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams модуль"}.
{"ejabberd vCard module","ejabberd vCard модуль"}.
{"ejabberd virtual hosts","Виртуальные хосты ejabberd"}.
{"ejabberd Web Admin","Web-интерфейс администрирования ejabberd"}.
{"Email","Электронная почта"}.
{"Enable logging","Включить журналирование"}.
{"Encodings","Кодировки"}.
{"End User Session","Завершить сеанс пользователя"}.
{"Enter list of {Module, [Options]}","Введите список вида {Module, [Options]}"}.
{"Enter nickname you want to register","Введите псевдоним, который Вы хотели бы зарегистрировать"}.
{"Enter path to backup file","Введите путь к резервному файлу"}.
{"Enter path to jabberd14 spool dir","Введите путь к директории спула jabberd14"}.
{"Enter path to jabberd14 spool file","Введите путь к файлу из спула jabberd14"}.
{"Enter path to text file","Введите путь к текстовому файлу"}.
{"Enter username and encodings you wish to use for connecting to IRC servers","Введите имя пользователя и кодировки, которые будут использоваться при подключении к IRC-серверам"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].","Примеры: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Family Name","Фамилия"}.
{"February","февраля"}.
{"Fill in fields to search for any matching Jabber User","Заполните форму для поиска пользователя Jabber"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Заполните форму для поиска пользователя Jabber (Если добавить * в конец поля, то происходит поиск подстроки)"}.
{"Friday","Пятница"}.
{"From ~s","От ~s"}.
{"From","От кого"}.
{"Full Name","Полное имя"}.
{"Get Number of Online Users","Получить количество подключённых пользователей"}.
{"Get Number of Registered Users","Получить количество зарегистрированных пользователей"}.
{"Get User Last Login Time","Получить время последнего подключения пользователя"}.
{"Get User Password","Получить пароль пользователя"}.
{"Get User Statistics","Получить статистику по пользователю"}.
{"Groups","Группы"}.
{"Group ","Группа "}.
{"has been banned","запретили входить в комнату"}.
{"has been kicked because of an affiliation change","выгнали из комнаты вследствие смены ранга"}.
{"has been kicked because of a system shutdown","выгнали из комнаты из-за останова системы"}.
{"has been kicked because the room has been changed to members-only","выгнали из комнаты потому что она стала только для членов"}.
{"has been kicked","выгнали из комнаты"}.
{" has set the subject to: "," установил(а) тему: "}.
{"Host","Хост"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","Чтобы указать различные кодировки для разных серверов IRC, заполните список значениями в формате '{\"irc server\", \"encoding\"}'. По умолчанию эта служба использует кодировку \"~s\"."}.
{"Import Directory","Импорт из директории"}.
{"Import File","Импорт из файла"}.
{"Import User from File at ","Импорт пользователя из файла на "}.
{"Import Users from Dir at ","Импорт пользователей из директории на "}.
{"Import Users From jabberd14 Spool Files","Импорт пользователей из спула jabberd14"}.
{"Improper message type","Неправильный тип сообщения"}.
{"Incorrect password","Неправильный пароль"}.
{"Invalid affiliation: ~s","Недопустимый ранг: ~s"}.
{"Invalid role: ~s","Недопустимая роль: ~s"}.
{"IP addresses","IP адреса"}.
{"IRC Transport","IRC Транспорт"}.
{"IRC Username","Имя пользователя IRC"}.
{"is now known as","изменил(а) имя на"}.
{"It is not allowed to send private messages of type \"groupchat\"","Нельзя посылать частные сообщения типа \"groupchat\""}.
{"It is not allowed to send private messages to the conference","Не разрешается посылать частные сообщения прямо в конференцию"}.
{"It is not allowed to send private messages","Запрещено посылать приватные сообщения"}.
{"Jabber ID","Jabber ID"}.
{"January","января"}.
{"Jabber ID ~s is invalid","JID ~s недопустимый"}.
{"joins the room","вошёл(а) в комнату"}.
{"July","июля"}.
{"June","июня"}.
{"Last Activity","Последнее подключение"}.
{"Last login","Время последнего подключения"}.
{"Last month","За последний месяц"}.
{"Last year","За последний год"}.
{"leaves the room","вышел(а) из комнаты"}.
{"Listened Ports at ","Прослушиваемые порты на "}.
{"Listened Ports","Прослушиваемые порты"}.
{"List of modules to start","Список запускаемых модулей"}.
{"Low level update script","Низкоуровневый сценарий обновления"}.
{"Make participants list public","Сделать список участников видимым всем"}.
{"Make room members-only","Комната только для зарегистрированных участников"}.
{"Make room moderated","Сделать комнату модерируемой"}.
{"Make room password protected","Сделать комнату защищённой паролем"}.
{"Make room persistent","Сделать комнату постоянной"}.
{"Make room public searchable","Сделать комнату видимой всем"}.
{"March","марта"}.
{"Maximum Number of Occupants","Максимальное количество участников"}.
{"Max # of items to persist","Максимальное число сохраняемых публикаций"}.
{"Max payload size in bytes","Максимальный размер полезной нагрузки в байтах"}.
{"May","мая"}.
{"Membership required to enter this room","В эту конференцию могут входить только её члены"}.
{"Members:","Члены:"}.
{"Memory","Память"}.
{"Message body","Тело сообщения"}.
{"Middle Name","Отчество"}.
{"Moderator privileges required","Требуются права модератора"}.
{"moderators only","только модераторам"}.
{"Modules at ","Модули на "}.
{"Modules","Модули"}.
{"Module","Модуль"}.
{"Monday","Понедельник"}.
{"Name:","Название:"}.
{"Name","Название"}.
{"Never","Никогда"}.
{"Nickname is already in use by another occupant","Псевдоним занят кем-то из присутствующих"}.
{"Nickname is registered by another person","Псевдоним зарегистрирован кем-то другим"}.
{"Nickname Registration at ","Регистрация псевдонима на "}.
{"Nickname ~s does not exist in the room","Псевдоним ~s в комнате отсутствует"}.
{"Nickname","Псевдоним"}.
{"No body provided for announce message","Тело объявления не должно быть пустым"}.
{"No Data","Нет данных"}.
{"Node ID","ID узла"}.
{"Node not found","Узел не найден"}.
{"Nodes","Узлы"}.
{"Node ","Узел "}.
{"No limit","Не ограничено"}.
{"None","Нет"}.
{"No resource provided","Не указан ресурс"}.
{"Notify subscribers when items are removed from the node","Уведомлять подписчиков об удалении публикаций из сборника"}.
{"Notify subscribers when the node configuration changes","Уведомлять подписчиков об изменении конфигурации сборника"}.
{"Notify subscribers when the node is deleted","Уведомлять подписчиков об удалении сборника"}.
{"November","ноября"}.
{"Number of occupants","Число присутствующих"}.
{"Number of online users","Количество подключённых пользователей"}.
{"Number of registered users","Количество зарегистрированных пользователей"}.
{"October","октября"}.
{"Offline Messages:","Офлайновые сообщения:"}.
{"Offline Messages","Офлайновые сообщения"}.
{"OK","Продолжить"}.
{"Online Users:","Подключённые пользователи:"}.
{"Online Users","Подключённые пользователи"}.
{"Online","Подключён"}.
{"Only deliver notifications to available users","Доставлять уведомления только доступным пользователям"}.
{"Only moderators and participants are allowed to change subject in this room","Только модераторы и участники могут изменять тему в этой комнате"}.
{"Only moderators are allowed to change subject in this room","Только модераторы могут изменять тему в этой комнате"}.
{"Only occupants are allowed to send messages to the conference","Только присутствующим разрешается посылать сообщения в конференцию"}.
{"Only occupants are allowed to send queries to the conference","Только присутствующим разрешается посылать запросы в конференцию"}.
{"Only service administrators are allowed to send service messages","Только администратор службы может посылать служебные сообщения"}.
{"Options","Параметры"}.
{"Organization Name","Название организации"}.
{"Organization Unit","Отдел организации"}.
{"Outgoing s2s Connections:","Исходящие s2s-серверы:"}.
{"Outgoing s2s Connections","Исходящие s2s-соединения"}.
{"Outgoing s2s Servers:","Исходящие s2s-серверы:"}.
{"Owner privileges required","Требуются права владельца"}.
{"Packet","Пакет"}.
{"Password required to enter this room","Чтобы войти в эту конференцию, нужен пароль"}.
{"Password Verification","Проверка пароля"}.
{"Password:","Пароль:"}.
{"Password","Пароль"}.
{"Path to Dir","Путь к директории"}.
{"Path to File","Путь к файлу"}.
{"Pending","Ожидание"}.
{"Period: ","Период"}.
{"Persist items to storage","Сохранять публикации в хранилище"}.
{"Ping","Пинг"}.
{"Pong","Понг"}.
{"Port","Порт"}.
{"Present real Jabber IDs to","Сделать реальные JID участников видимыми"}.
{"private, ","приватная, "}.
{"Publish-Subscribe","Публикация-Подписка"}.
{"PubSub subscriber request","Запрос подписчика PubSub"}.
{"Queries to the conference members are not allowed in this room","Запросы к пользователям в этой конференции запрещены"}.
{"RAM and disc copy","ОЗУ и диск"}.
{"RAM copy","ОЗУ"}.
{"(Raw)","(Необработанный формат)"}.
{"Raw","Необработанный формат"}.
{"Really delete message of the day?","Действительно удалить сообщение дня?"}.
{"Recipient is not in the conference room","Адресата нет в конференции"}.
{"Registered Users:","Зарегистрированные пользователи:"}.
{"Registered Users","Зарегистрированные пользователи"}.
{"Registration in mod_irc for ","Регистрация в mod_irc для "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Заметьте, что здесь производится резервное копирование только встроенной базы данных Mnesia. Если Вы также используете другое хранилище данных (например с помощью модуля ODBC), то его резервное копирование следует осуществлять отдельно."}.
{"Remote copy","не хранится локально"}.
{"Remove User","Удалить пользователя"}.
{"Remove","Удалить"}.
{"Replaced by new connection","Заменено новым соединением"}.
{"Resources","Ресурсы"}.
{"Restart Service","Перезапустить службу"}.
{"Restart","Перезапустить"}.
{"Restore Backup from File at ","Восстановление из резервной копии на "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Восстановить из бинарной резервной копии при следующем запуске (требует меньше памяти):"}.
{"Restore binary backup immediately:","Восстановить из бинарной резервной копии немедленно:"}.
{"Restore plain text backup immediately:","Восстановить из текстовой резервной копии немедленно:"}.
{"Restore","Восстановление из резервной копии"}.
{"Room Configuration","Конфигурация комнаты"}.
{"Room creation is denied by service policy","Cоздавать конференцию запрещено политикой службы"}.
{"Room title","Название комнаты"}.
{"Roster groups allowed to subscribe","Группы списка контактов, которым разрешена подписка"}.
{"Roster of ","Ростер пользователя "}.
{"Roster size","Размер списка контактов"}.
{"Roster","Ростер"}.
{"RPC Call Error","Ошибка вызова RPC"}.
{"Running Nodes","Работающие узлы"}.
{"~s access rule configuration","Конфигурация правила доступа ~s"}.
{"Saturday","Суббота"}.
{"Script check","Проверка сценария"}.
{"Search Results for ","Результаты поиска в "}.
{"Search users in ","Поиск пользователей в "}.
{"Send announcement to all online users on all hosts","Разослать объявление всем подключённым пользователям на всех виртуальных серверах"}.
{"Send announcement to all online users","Разослать объявление всем подключённым пользователям"}.
{"Send announcement to all users on all hosts","Разослать объявление всем пользователям на всех виртуальных серверах"}.
{"Send announcement to all users","Разослать объявление всем пользователям"}.
{"September","сентября"}.
{"Set message of the day and send to online users","Установить сообщение дня и разослать его подключённым пользователям"}.
{"Set message of the day on all hosts and send to online users","Установить сообщение дня на всех виртуальных серверах и разослать его подключённым пользователям"}.
{"Shared Roster Groups","Группы общих контактов"}.
{"Show Integral Table","Показать интегральную таблицу"}.
{"Show Ordinary Table","Показать обычную таблицу"}.
{"Shut Down Service","Остановить службу"}.
{"~s invites you to the room ~s","~s приглашает вас в комнату ~s"}.
{"Size","Размер"}.
{"Specified nickname is already registered","Указанный псевдоним уже зарегистрирован"}.
{"Specify the access model","Укажите механизм управления доступом"}.
{"Specify the publisher model","Условия публикации"}.
{"~s's Offline Messages Queue","Oчередь офлайновых сообщений ~s"}.
{"Start Modules at ","Запуск модулей на "}.
{"Start Modules","Запуск модулей"}.
{"Start","Запустить"}.
{"Statistics of ~p","статистика узла ~p"}.
{"Statistics","Статистика"}.
{"Stop Modules at ","Остановка модулей на "}.
{"Stop Modules","Остановка модулей"}.
{"Stopped Nodes","Остановленные узлы"}.
{"Stop","Остановить"}.
{"Storage Type","Тип таблицы"}.
{"Store binary backup:","Сохранить бинарную резервную копию:"}.
{"Store plain text backup:","Сохранить текстовую резервную копию:"}.
{"Subject","Тема"}.
{"Submitted","Отправлено"}.
{"Submit","Отправить"}.
{"Subscriber Address","Адрес подписчика"}.
{"Subscription","Подписка"}.
{"Sunday","Воскресенье"}.
{"the password is","пароль:"}.
{"This participant is kicked from the room because he sent an error message to another participant","Этого участника выгнали из комнаты за то, что он послал сообщение об ошибке другому участнику"}.
{"This participant is kicked from the room because he sent an error message","Этого участника выгнали из комнаты за то, что он послал сообщение об ошибке"}.
{"This participant is kicked from the room because he sent an error presence","Этого участника выгнали из комнаты за то, что он послал присутствие с ошибкой"}.
{"This room is not anonymous","Эта комната не анонимная"}.
{"Thursday","Четверг"}.
{"Time delay","По истечение"}.
{"Time","Время"}.
{"To ~s","К ~s"}.
{"To","Кому"}.
{"Traffic rate limit is exceeded","Превышен лимит скорости посылки информации"}.
{"Transactions Aborted:","Транзакции отмененные:"}.
{"Transactions Committed:","Транзакции завершенные:"}.
{"Transactions Logged:","Транзакции запротоколированные:"}.
{"Transactions Restarted:","Транзакции перезапущенные:"}.
{"Tuesday","Вторник"}.
{"Updated modules","Обновлённые модули"}.
{"Update message of the day (don't send)","Обновить сообщение дня (не рассылать)"}.
{"Update message of the day on all hosts (don't send)","Обновить сообщение дня на всех виртуальных серверах (не рассылать)"}.
{"Update plan","План обновления"}.
{"Update script","Сценарий обновления"}.
{"Update","Обновить"}.
{"Update ","Обновление "}.
{"Uptime:","Время работы:"}.
{"Use of STARTTLS required","Вы обязаны использовать STARTTLS"}.
{"User Management","Управление пользователями"}.
{"Users are not allowed to register accounts so fast","Пользователи не могут регистрировать учётные записи так быстро"}.
{"Users Last Activity","Статистика последнего подключения пользователей"}.
{"Users","Пользователи"}.
{"User ","Пользователь "}.
{"User","Пользователь"}.
{"Validate","Утвердить"}.
{"vCard User Search","Поиск пользователей по vCard"}.
{"Virtual Hosts","Виртуальные хосты"}.
{"Visitors are not allowed to change their nicknames in this room","Посетителям запрещено изменять свои псевдонимы в этой комнате"}.
{"Visitors are not allowed to send messages to all occupants","Посетителям не разрешается посылать сообщения всем присутствующим"}.
{"Wednesday","Среда"}.
{"When to send the last published item","Когда посылать последний опубликованный элемент"}.
{"Whether to allow subscriptions","Разрешить подписку"}.
{"You have been banned from this room","Вам запрещено входить в эту конференцию"}.
{"You must fill in field \"Nickname\" in the form","Вы должны заполнить поле \"Псевдоним\" в форме"}.
{"You need an x:data capable client to configure mod_irc settings","Чтобы настроить параметры mod_irc, требуется x:data-совместимый клиент"}.
{"You need an x:data capable client to configure room","Чтобы сконфигурировать комнату, требуется x:data-совместимый клиент"}.
{"You need an x:data capable client to register nickname","Чтобы зарегистрировать псевдоним, требуется x:data-совместимый клиент"}.
{"You need an x:data capable client to search","Чтобы воспользоваться поиском, требуется x:data-совместимый клиент"}.
{"Your contact offline message queue is full. The message has been discarded.","Очередь недоставленных сообщений Вашего адресата переполнена. Сообщение не было сохранено."}.
