% $Id$

% mod_configure.erl
{"DB Tables Configuration at ", "Конфигурация таблиц БД на "}.
{"Choose storage type of tables", "Выберите тип хранения таблиц"}.
{"RAM copy", "ОЗУ"}.
{"RAM and disc copy", "ОЗУ и диск"}.
{"Disc only copy", "только диск"}.
{"Remote copy", "не хранится локально"}.
{"Stop Modules at ", "Остановка модулей на "}.
{"Choose modules to stop", "Выберите модули, которые следует остановить"}.
{"Start Modules at ", "Запуск модулей на "}.
{"Enter list of {Module, [Options]}", "Введите список вида {Module, [Options]}"}.
{"List of modules to start", "Список запускаемых модулей"}.
{"Backup to File at ", "Резервное копирование в файл на "}.
{"Enter path to backup file", "Введите путь к резервному файлу"}.
{"Path to File", "Путь к файлу"}.
{"Restore Backup from File at ", "Восстановление из резервной копии на "}.
{"Dump Backup to Text File at ", "Копирование в текстовый файл на "}.
{"Enter path to text file", "Введите путь к текстовому файлу"}.
{"Import User from File at ", "Импорт пользователя из файла на "}.
{"Enter path to jabberd1.4 spool file", "Введите путь к файлу из спула jabberd1.4"}.
{"Import Users from Dir at ", "Импорт пользователей из директории на "}.
{"Enter path to jabberd1.4 spool dir", "Введите путь к директории спула jabberd1.4"}.
{"Path to Dir", "Путь к директории"}.
{"Hostname Configuration", "Конфигурация имени хоста"}.
{"Choose host name", "Выберите имя хоста"}.
{"Host name", "Имя хоста"}.
{"Access Control List Configuration", "Конфигурация списков управления доступом"}.
{"Access control lists", "Списки управления доступом"}.
{"Access Configuration", "Конфигурация доступа"}.
{"Access rules", "Правила доступа"}.
{"Remove Users", "Удаление пользователей"}.
{"Choose users to remove", "Выберите пользователей, которых следует удалить"}.
{"Administration of ", "Администрирование "}.
{"Action on user", "Действие над пользователем"}.
{"Edit Properties", "Изменить параметры"}.
{"Remove User", "Удалить пользователя"}.

% mod_disco.erl
{"Configuration", "Конфигурация"}.
{"Online Users", "Подключённые пользователи"}.
{"All Users", "Все пользователи"}.
{"Outgoing S2S connections", "Исходящие S2S-соединения"}.
{"To ~s", "К ~s"}.
{"From ~s", "От ~s"}.
{"Running Nodes", "Работающие узлы"}.
{"Stopped Nodes", "Остановленные узлы"}.
{"Host Name", "Имя хоста"}.
{"Access Control Lists", "Списки управления доступом"}.
{"Access Rules", "Правила доступа"}.
{"Remove Users", "Удаление пользователей"}.
{"DB", "БД"}.
{"Modules", "Модули"}.
{"Start Modules", "Запуск модулей"}.
{"Stop Modules", "Остановка модулей"}.
{"Backup Management", "Управление резервным копированием"}.
{"Import users from jabberd1.4 spool files", "Импорт пользователей из спула jabberd1.4"}.
{"Backup", "Резервное копирование"}.
{"Restore", "Восстановление из резервной копии"}.
{"Dump to Text File", "Копирование в текстовый файл"}.
{"Import File", "Импорт из файла"}.
{"Import Directory", "Импорт из директории"}.

% mod_register.erl
{"Choose a username and password to register with this server",
 "Выберите имя пользователя и пароль для регистрации на этом сервере"}.

% mod_vcard.erl
{"Erlang Jabber Server\nCopyright (c) 2002-2004 Alexey Shchepin",
 "Erlang Jabber Server\nCopyright (c) 2002-2004 Алексей Щепин"}.
{"ejabberd vCard module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd vCard модуль\nCopyright (c) 2003-2004 Алексей Щепин"}.
{"You need an x:data capable client to search",
 "Чтобы воспользоваться поиском, требуется x:data-совместимый клиент"}.
{"Search users in ", "Поиск пользователей в "}.
{"Fill in fields to search for any matching Jabber User",
 "Заполните поля для поиска пользователя Jabber"}.
{"Results of search in ", "Результаты поиска в "}.

{"User",              "Пользователь"}.
{"Full Name", 	      "Полное имя"}.
{"Name", 	      "Имя"}.
{"Middle Name",       "Отчество"}.
{"Family Name",       "Фамилия"}.
{"Nickname", 	      "Псевдоним"}.
{"Birthday", 	      "День рождения"}.
{"Country", 	      "Страна"}.
{"City", 	      "Город"}.
{"email", 	      "email"}.
{"Organization Name", "Название организации"}.
{"Organization Unit", "Отдел организации"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd pub/sub модуль\nCopyright (c) 2003-2004 Алексей Щепин"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname",
 "Чтобы зарегистрировать псевдоним, требуется x:data-совместимый клиент"}.
{"Nickname Registration at ", "Регистрация псевдонима на "}.
{"Enter nickname you want to register", "Введите псевдоним, который Вы хотели бы зарегистрировать"}.
{"ejabberd MUC module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd MUC модуль\nCopyright (c) 2003-2004 Алексей Щепин"}.

% mod_muc/mod_muc_room.erl
{" has set the subject to: ", " установил(а) тему: "}.
{"You need an x:data capable client to configure room",
 "Чтобы сконфигурировать комнату, требуется x:data-совместимый клиент"}.
{"Configuration for ", "Конфигурация "}.
{"Room title", "Название комнаты"}.
{"Allow users to change subject?", "Разрешить пользователям изменять тему?"}.
{"Allow users to query other users?",
 "Разрешить iq-запросы к пользователям?"}.
{"Allow users to send private messages?",
 "Разрешить приватные сообщения?"}.
{"Make room public searchable?", "Сделать комнату видимой всем?"}.
{"Make participants list public?", "Сделать список участников видимым всем?"}.
{"Make room persistent?", "Сделать комнату постоянной?"}.
{"Make room moderated?", "Сделать комнату модерируемой?"}.
{"Default users as members?",
 "Сделать пользователей участниками по умолчанию?"}.
{"Make room members only?",
 "Комната только для зарегистрированных участников?"}.
{"Allow users to send invites?",
 "Разрешить пользователям посылать приглашения?"}.
{"Make room password protected?", "Сделать комнату защищённой паролем?"}.
{"Password", "Пароль"}.
{"Make room anonymous?", "Сделать комнату анонимной?"}.
{"Enable logging?", "Включить журналирование?"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd IRC модуль\nCopyright (c) 2003-2004 Алексей Щепин"}.
{"You need an x:data capable client to configure mod_irc settings",
 "Чтобы настроить параметры mod_irc, требуется x:data-совместимый клиент"}.
{"Registration in mod_irc for ", "Регистрация в mod_irc для "}.
{"Enter username and encodings you wish to use for connecting to IRC servers",
 "Введите имя пользователя и кодировки, которые будут использоваться при подключении к IRC-серверам"}.
{"IRC Username", "Имя пользователя IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Чтобы указать различные кодировки для разных серверов IRC, заполните список значениями в формате '{\"irc server\", \"encoding\"}'. По умолчанию эта служба использует кодировку \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Примеры: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Кодировки"}.

% Local Variables:
% mode: erlang
% End:
