% $Id$
% Language: Russian (русский)
% Author: Evgeniy Khramtsov
% Author: Konstantin Khomoutov
% Author: Sergei Golovan

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Вы обязаны использовать STARTTLS"}.
{"Replaced by new connection", "Заменено новым соединением"}.

% jlib.hrl
{"No resource provided", "Не указан ресурс"}.

% mod_adhoc.erl
{"Commands", "Команды"}.
{"Ping", "Пинг"}.
{"Pong", "Понг"}.

% mod_announce.erl
{"Really delete message of the day?", "Действительно удалить сообщение дня?"}.
{"Subject", "Тема"}.
{"Message body", "Тело сообщения"}.
{"No body provided for announce message", "Тело объявления не должно быть пустым"}.
{"Announcements", "Объявления"}.
{"Send announcement to all users", "Разослать объявление всем пользователям"}.
{"Send announcement to all online users", "Разослать объявление всем подключённым пользователям"}.
{"Send announcement to all online users on all hosts", "Разослать объявление всем подключённым пользователям на всех виртуальных серверах"}.
{"Set message of the day and send to online users", "Установить сообщение дня и разослать его подключённым пользователям"}.
{"Update message of the day (don't send)", "Обновить сообщение дня (не рассылать)"}.
{"Delete message of the day", "Удалить сообщение дня"}.
{"Send announcement to all users on all hosts", "Разослать объявление всем пользователям на всех виртуальных серверах"}.
{"Set message of the day on all hosts and send to online users", "Установить сообщение дня на всех виртуальных серверах и разослать его подключённым пользователям"}.
{"Update message of the day on all hosts (don't send)", "Обновить сообщение дня на всех виртуальных серверах (не рассылать)"}.
{"Delete message of the day on all hosts", "Удалить сообщение дня со всех виртуальных серверов"}.

% mod_configure.erl
{"Database Tables Configuration at ", "Конфигурация таблиц базы данных на "}.
{"Choose storage type of tables", "Выберите тип хранения таблиц"}.
{"RAM copy", "ОЗУ"}.
{"RAM and disc copy", "ОЗУ и диск"}.
{"Disc only copy", "только диск"}.
{"Remote copy", "не хранится локально"}.
{"Stop Modules at ", "Остановка модулей на "}.
{"Choose modules to stop", "Выберите модули, которые следует остановить"}.
{"Start Modules at ", "Запуск модулей на "}.
{"Enter list of {Module, [Options]}", "Введите список вида {Module, [Options]}"}.
{"List of modules to start", "Список запускаемых модулей"}.
{"Backup to File at ", "Резервное копирование в файл на "}.
{"Enter path to backup file", "Введите путь к резервному файлу"}.
{"Path to File", "Путь к файлу"}.
{"Restore Backup from File at ", "Восстановление из резервной копии на "}.
{"Dump Backup to Text File at ", "Копирование в текстовый файл на "}.
{"Enter path to text file", "Введите путь к текстовому файлу"}.
{"Import User from File at ", "Импорт пользователя из файла на "}.
{"Enter path to jabberd1.4 spool file", "Введите путь к файлу из спула jabberd1.4"}.
{"Import Users from Dir at ", "Импорт пользователей из директории на "}.
{"Enter path to jabberd1.4 spool dir", "Введите путь к директории спула jabberd1.4"}.
{"Path to Dir", "Путь к директории"}.
{"Access Control List Configuration", "Конфигурация списков управления доступом"}.
{"Access control lists", "Списки управления доступом"}.
{"Access Configuration", "Конфигурация доступа"}.
{"Access rules", "Правила доступа"}.
{"Administration of ", "Администрирование "}.
{"Action on user", "Действие над пользователем"}.
{"Edit Properties", "Изменить параметры"}.
{"Remove User", "Удалить пользователя"}.
{"Restart Service", "Перезапустить службу"}.
{"Shut Down Service", "Остановить службу"}.
{"Delete User", "Удалить пользователя"}.
{"End User Session", "Завершить сеанс пользователя"}.
{"Get User Password", "Получить пароль пользователя"}.
{"Change User Password", "Изменить пароль пользователя"}.
{"Get User Last Login Time", "Получить время последнего подключения пользователя"}.
{"Get User Statistics", "Получить статистику по пользователю"}.
{"Get Number of Registered Users", "Получить количество зарегистрированных пользователей"}.
{"Get Number of Online Users", "Получить количество подключённых пользователей"}.
{"User Management", "Управление пользователями"}.
{"Time delay", "По истечение"}.
{"Password Verification", "Проверка пароля"}.
{"Number of registered users", "Количество зарегистрированных пользователей"}.
{"Number of online users", "Количество подключённых пользователей"}.
{"Last login", "Время последнего подключения"}.
{"Roster size", "Размер списка контактов"}.
{"IP addresses", "IP адреса"}.
{"Resources", "Ресурсы"}.

% mod_disco.erl
{"Configuration", "Конфигурация"}.
{"Online Users", "Подключённые пользователи"}.
{"All Users", "Все пользователи"}.
{"Outgoing s2s Connections", "Исходящие s2s-соединения"}.
{"To ~s", "К ~s"}.
{"From ~s", "От ~s"}.
{"Running Nodes", "Работающие узлы"}.
{"Stopped Nodes", "Остановленные узлы"}.
{"Access Control Lists", "Списки управления доступом"}.
{"Access Rules", "Правила доступа"}.
{"Database", "База данных"}.
{"Modules", "Модули"}.
{"Start Modules", "Запуск модулей"}.
{"Stop Modules", "Остановка модулей"}.
{"Backup Management", "Управление резервным копированием"}.
{"Import Users From jabberd 1.4 Spool Files", "Импорт пользователей из спула jabberd 1.4"}.
{"Backup", "Резервное копирование"}.
{"Restore", "Восстановление из резервной копии"}.
{"Dump to Text File", "Копирование в текстовый файл"}.
{"Import File", "Импорт из файла"}.
{"Import Directory", "Импорт из директории"}.

% mod_proxy65.erl

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams модуль"}.

% mod_register.erl
{"Users are not allowed to register accounts so fast", "Пользователи не могут регистрировать учётные записи так быстро"}.
{"Choose a username and password to register with this server", "Выберите имя пользователя и пароль для регистрации на этом сервере"}.

% mod_vcard.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"ejabberd vCard module", "ejabberd vCard модуль"}.
{"You need an x:data capable client to search", "Чтобы воспользоваться поиском, требуется x:data-совместимый клиент"}.
{"Search users in ", "Поиск пользователей в "}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Заполните форму для поиска пользователя Jabber (Если добавить * в конец поля, то происходит поиск подстроки)"}.
{"Search Results for ", "Результаты поиска в "}.
{"Jabber ID",         "Jabber ID"}.
{"User",              "Пользователь"}.
{"Full Name", 	      "Полное имя"}.
{"Name", 	      "Имя"}.
{"Middle Name",       "Отчество"}.
{"Family Name",       "Фамилия"}.
{"Nickname", 	      "Псевдоним"}.
{"Birthday", 	      "День рождения"}.
{"Country", 	      "Страна"}.
{"City", 	      "Город"}.
{"Email", 	      "Электронная почта"}.
{"Organization Name", "Название организации"}.
{"Organization Unit", "Отдел организации"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Заполните форму для поиска пользователя Jabber"}.

% mod_pubsub/mod_pubsub.erl
{"A friendly name for the node", "Легко запоминаемое имя для узла"}.
{"Roster groups allowed to subscribe", "Группы списка контактов, которым разрешена подписка"}.
{"Deliver payloads with event notifications", "Доставлять вместе с уведомлениями o публикациях сами публикации"}.
{"Notify subscribers when the node configuration changes", "Уведомлять подписчиков об изменении конфигурации сборника"}.
{"Notify subscribers when the node is deleted", "Уведомлять подписчиков об удалении сборника"}.
{"Notify subscribers when items are removed from the node", "Уведомлять подписчиков об удалении публикаций из сборника"}.
{"Persist items to storage", "Сохранять публикации в хранилище"}.
{"Max # of items to persist", "Максимальное число сохраняемых публикаций"}.
{"Whether to allow subscriptions", "Разрешить подписку"}.
{"Specify the publisher model", "Условия публикации"}.
{"Max payload size in bytes", "Максимальный размер полезной нагрузки в байтах"}.
{"Only deliver notifications to available users", "Доставлять уведомления только доступным пользователям"}.
{"Publish-Subscribe", "Публикация-Подписка"}.
{"ejabberd Publish-Subscribe module", "Модуль ejabberd Публикации-Подписки"}.
{"PubSub subscriber request", "Запрос подписчика PubSub"}.
{"Choose whether to approve this entity's subscription.", "Решите: предоставить ли подписку этому объекту."}.
{"Node ID", "ID узла"}.
{"Subscriber Address", "Адрес подписчика"}.
{"Allow this JID to subscribe to this pubsub node?", "Разрешить этому JID подписаться на данный узел?"}.
{"Deliver event notifications", "Доставлять уведомления о событиях"}.
{"Specify the access model", "Укажите механизм управления доступом"}.
{"When to send the last published item", "Когда посылать последний опубликованный элемент"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "Чтобы зарегистрировать псевдоним, требуется x:data-совместимый клиент"}.
{"Nickname Registration at ", "Регистрация псевдонима на "}.
{"Enter nickname you want to register", "Введите псевдоним, который Вы хотели бы зарегистрировать"}.
{"ejabberd MUC module", "ejabberd MUC модуль"}.
{"Only service administrators are allowed to send service messages", "Только администратор службы может посылать служебные сообщения"}.
{"Room creation is denied by service policy", "Cоздавать конференцию запрещено политикой службы"}.
{"Conference room does not exist", "Конференция не существует"}.
{"Access denied by service policy", "Доступ запрещён политикой службы"}.
{"You must fill in field \"Nickname\" in the form", "Вы должны заполнить поле \"Псевдоним\" в форме"}.
{"Specified nickname is already registered", "Указанный псевдоним уже зарегистрирован"}.
{"Chatrooms", "Комнаты"}.

% mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "выгнали из комнаты вследствие смены ранга"}.
{"has been kicked because the room has been changed to members-only", "выгнали из комнаты потому что она стала только для членов"}.
{"has been kicked because of a system shutdown", "выгнали из комнаты из-за останова системы"}.
{"Chatroom configuration modified", "Конфигурация комнаты изменилась"}.
{"joins the room", "вошёл(а) в комнату"}.
{"leaves the room", "вышел(а) из комнаты"}.
{"has been kicked", "выгнали из комнаты"}.
{"has been banned", "запретили входить в комнату"}.
{"is now known as", "изменил(а) имя на"}.
{"Monday", "Понедельник"}.
{"Tuesday", "Вторник"}.
{"Wednesday", "Среда"}.
{"Thursday", "Четверг"}.
{"Friday", "Пятница"}.
{"Saturday", "Суббота"}.
{"Sunday", "Воскресенье"}.
{"January", "января"}.
{"February", "февраля"}.
{"March", "марта"}.
{"April", "апреля"}.
{"May", "мая"}.
{"June", "июня"}.
{"July", "июля"}.
{"August", "августа"}.
{"September", "сентября"}.
{"October", "октября"}.
{"November", "ноября"}.
{"December", "декабря"}.
{"Room Configuration", "Конфигурация комнаты"}.

% mod_muc/mod_muc_room.erl
{"It is not allowed to send private messages", "Запрещено посылать приватные сообщения"}.
{"Visitors are not allowed to change their nicknames in this room", "Посетителям запрещено изменять свои псевдонимы в этой комнате"}.
{"Allow visitors to send status text in presence updates", "Разрешить посетителям вставлять текcт статуса в сообщения о присутствии"}.
{"Allow visitors to change nickname", "Разрешить посетителям изменять псевдоним"}.
{"This participant is kicked from the room because he sent an error message", "Этого участника выгнали из комнаты за то, что он послал сообщение об ошибке"}.
{"This participant is kicked from the room because he sent an error message to another participant", "Этого участника выгнали из комнаты за то, что он послал сообщение об ошибке другому участнику"}.
{"This participant is kicked from the room because he sent an error presence", "Этого участника выгнали из комнаты за то, что он послал присутствие с ошибкой"}.
{"Make room moderated", "Сделать комнату модерируемой"}.
{"This room is not anonymous", "Эта комната не анонимная"}.
{" has set the subject to: ", " установил(а) тему: "}.
{"You need an x:data capable client to configure room", "Чтобы сконфигурировать комнату, требуется x:data-совместимый клиент"}.
{"Configuration for ", "Конфигурация "}.
{"Room title", "Название комнаты"}.
{"Allow users to change subject", "Разрешить пользователям изменять тему"}.
{"Allow users to query other users", "Разрешить iq-запросы к пользователям"}.
{"Allow users to send private messages", "Разрешить приватные сообщения"}.
{"Make room public searchable", "Сделать комнату видимой всем"}.
{"Make participants list public", "Сделать список участников видимым всем"}.
{"Make room persistent", "Сделать комнату постоянной"}.
{"Default users as participants", "Сделать пользователей участниками по умолчанию"}.
{"Make room members-only", "Комната только для зарегистрированных участников"}.
{"Allow users to send invites", "Разрешить пользователям посылать приглашения"}.
{"Make room password protected", "Сделать комнату защищённой паролем"}.
{"Password", "Пароль"}.
{"Present real JIDs to", "Сделать реальные JID участников видимыми"}.
{"moderators only", "только модераторам"}.
{"anyone", "всем участникам"}.
{"Enable logging", "Включить журналирование"}.
{"Only moderators and participants are allowed to change subject in this room", "Только модераторы и участники могут изменять тему в этой комнате"}.
{"Only moderators are allowed to change subject in this room", "Только модераторы могут изменять тему в этой комнате"}.
{"Visitors are not allowed to send messages to all occupants", "Посетителям не разрешается посылать сообщения всем присутствующим"}.
{"Only occupants are allowed to send messages to the conference", "Только присутствующим разрешается посылать сообщения в конференцию"}.
{"It is not allowed to send private messages to the conference", "Не разрешается посылать частные сообщения прямо в конференцию"}.
{"Improper message type", "Неправильный тип сообщения"}.
{"Nickname is already in use by another occupant", "Псевдоним занят кем-то из присутствующих"}.
{"Nickname is registered by another person", "Псевдоним зарегистрирован кем-то другим"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Нельзя посылать частные сообщения типа \"groupchat\""}.
{"Recipient is not in the conference room", "Адресата нет в конференции"}.
{"Only occupants are allowed to send queries to the conference", "Только присутствующим разрешается посылать запросы в конференцию"}.
{"Queries to the conference members are not allowed in this room", "Запросы к пользователям в этой конференции запрещены"}.
{"You have been banned from this room", "Вам запрещено входить в эту конференцию"}.
{"Membership required to enter this room", "В эту конференцию могут входить только её члены"}.
{"Password required to enter this room", "Чтобы войти в эту конференцию, нужен пароль"}.
{"Incorrect password", "Неправильный пароль"}.
{"Administrator privileges required", "Требуются права администратора"}.
{"Moderator privileges required", "Требуются права модератора"}.
{"JID ~s is invalid", "JID ~s недопустимый"}.
{"Nickname ~s does not exist in the room", "Псевдоним ~s в комнате отсутствует"}.
{"Invalid affiliation: ~s", "Недопустимый ранг: ~s"}.
{"Invalid role: ~s", "Недопустимая роль: ~s"}.
{"Owner privileges required", "Требуются права владельца"}.
{"private, ", "приватная, "}.
{"Number of occupants", "Число присутствующих"}.
{"Traffic rate limit is exceeded", "Превышен лимит скорости посылки информации"}.
{"Maximum Number of Occupants", "Максимальное количество участников"}.
{"No limit", "Не ограничено"}.
{"~s invites you to the room ~s", "~s приглашает вас в комнату ~s"}.
{"the password is", "пароль:"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "ejabberd IRC модуль"}.
{"You need an x:data capable client to configure mod_irc settings", "Чтобы настроить параметры mod_irc, требуется x:data-совместимый клиент"}.
{"Registration in mod_irc for ", "Регистрация в mod_irc для "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Введите имя пользователя и кодировки, которые будут использоваться при подключении к IRC-серверам"}.
{"IRC Username", "Имя пользователя IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Чтобы указать различные кодировки для разных серверов IRC, заполните список значениями в формате '{\"irc server\", \"encoding\"}'. По умолчанию эта служба использует кодировку \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Примеры: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Кодировки"}.
{"IRC Transport", "IRC Транспорт"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "Web-интерфейс администрирования ejabberd"}.
{"Administration", "Администрирование"}.
{"Users", "Пользователи"}.
{"Nodes", "Узлы"}.
{"Statistics", "Статистика"}.
{"(Raw)", "(Необработанный формат)"}.
{"Submitted", "Отправлено"}.
{"Bad format", "Неправильный формат"}.
{"Raw", "Необработанный формат"}.
{"Delete Selected", "Удалить выделенные"}.
{"Submit", "Отправить"}.
{"~s access rule configuration", "Конфигурация правила доступа ~s"}.
{"Node not found", "Узел не найден"}.
{"Add New", "Добавить"}.
{"Registered Users", "Зарегистрированные пользователи"}.
{"Registered Users:", "Зарегистрированные пользователи:"}.
{"Online Users", "Подключённые пользователи"}.
{"Online Users:", "Подключённые пользователи:"}.
{"Outgoing s2s Connections:", "Исходящие s2s-серверы:"}.
{"Outgoing s2s Servers:", "Исходящие s2s-серверы:"}.
{"Change Password", "Сменить пароль"}.
{"Connected Resources:", "Подключённые ресурсы:"}.
{"Password:", "Пароль:"}.
{"None", "Нет"}.
{"Node ", "Узел "}.
{"Listened Ports", "Прослушиваемые порты"}.
{"Restart", "Перезапустить"}.
{"Stop", "Остановить"}.
{"RPC Call Error", "Ошибка вызова RPC"}.
{"Database Tables at ", "Таблицы базы данных на "}.
{"Name", "Название"}.
{"Storage Type", "Тип таблицы"}.
{"Size", "Размер"}.
{"Memory", "Память"}.
{"Backup of ", "Резервное копирование "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Заметьте, что здесь производится резервное копирование только встроенной базы данных Mnesia. Если Вы также используете другое хранилище данных (например с помощью модуля ODBC), то его резервное копирование следует осуществлять отдельно."}.
{"Store binary backup:", "Сохранить бинарную резервную копию:"}.
{"OK", "Продолжить"}.
{"Restore binary backup immediately:", "Восстановить из бинарной резервной копии немедленно:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Восстановить из бинарной резервной копии при следующем запуске (требует меньше памяти):"}.
{"Store plain text backup:", "Сохранить текстовую резервную копию:"}.
{"Restore plain text backup immediately:", "Восстановить из текстовой резервной копии немедленно:"}.
{"Listened Ports at ", "Прослушиваемые порты на "}.
{"Statistics of ~p", "статистика узла ~p"}.
{"Uptime:", "Время работы:"}.
{"CPU Time:", "Процессорное время:"}.
{"Transactions Commited:", "Транзакции завершенные:"}.
{"Transactions Aborted:", "Транзакции отмененные:"}.
{"Transactions Restarted:", "Транзакции перезапущенные:"}.
{"Transactions Logged:", "Транзакции запротоколированные:"}.
{"Update ", "Обновление "}.
{"Update plan", "План обновления"}.
{"Updated modules", "Обновлённые модули"}.
{"Update script", "Сценарий обновления"}.
{"Low level update script", "Низкоуровневый сценарий обновления"}.
{"Script check", "Проверка сценария"}.
{"Port", "Порт"}.
{"Module", "Модуль"}.
{"Options", "Параметры"}.
{"Update", "Обновить"}.
{"Delete", "Удалить"}.
{"Add User", "Добавить пользователя"}.
{"Offline Messages", "Офлайновые сообщения"}.
{"Offline Messages:", "Офлайновые сообщения:"}.
{"Last Activity", "Последнее подключение"}.
{"Never", "Никогда"}.
{"~s's Offline Messages Queue", "Oчередь офлайновых сообщений ~s"}.
{"Time", "Время"}.
{"From", "От кого"}.
{"To", "Кому"}.
{"Packet", "Пакет"}.
{"Roster", "Ростер"}.
{"Nickname", "Псевдоним"}.
{"Subscription", "Подписка"}.
{"Pending", "Ожидание"}.
{"Groups", "Группы"}.
{"Remove", "Удалить"}.
{"Add Jabber ID", "Добавить Jabber ID"}.
{"User ", "Пользователь "}.
{"Roster of ", "Ростер пользователя "}.
{"Online", "Подключён"}.
{"Validate", "Утвердить"}.
{"Shared Roster Groups", "Группы общих контактов"}.
{"Name:", "Название:"}.
{"Description:", "Описание:"}.
{"Members:", "Члены:"}.
{"Displayed Groups:", "Видимые группы:"}.
{"Group ", "Группа "}.
{"Users Last Activity", "Статистика последнего подключения пользователей"}.
{"Period: ", "Период"}.
{"Last month", "За последний месяц"}.
{"Last year", "За последний год"}.
{"All activity", "Вся статистика"}.
{"Show Ordinary Table", "Показать обычную таблицу"}.
{"Show Integral Table", "Показать интегральную таблицу"}.
{"Start", "Запустить"}.
{"Modules at ", "Модули на "}.
{"No Data", "Нет данных"}.
{"Virtual Hosts", "Виртуальные хосты"}.
{"ejabberd virtual hosts", "Виртуальные хосты ejabberd"}.
{"Host", "Хост"}.

% mod_vcard_odbc.erl
{"vCard User Search", "Поиск пользователей по vCard"}.
 
% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Очередь недоставленных сообщений Вашего адресата переполнена. Сообщение не было сохранено."}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
