% $Id$
% Language: Slovak (slovenčina)
% Author: Marek Becka
% Author: Juraj Michalek
% Author: SkLUG

% jlib.hrl
{"No resource provided", "Nebol poskytnutý žiadny zdroj"}.

% mod_configure.erl
{"Restart Service", "Reštartovať službu"}.
{"Shut Down Service", "Vypnúť službu"}.
{"Delete User", "Vymazať užívateľa"}.
{"End User Session", "Ukončiť reláciu užívateľa"}.
{"Get User Password", "Zobraziť heslo užívateľa"}.
{"Change User Password", "Zmeniť heslo užívateľa"}.
{"Get User Last Login Time", "Zobraziť čas posledného prihlásenia"}.
{"Get User Statistics", "Zobraziť štatistiku užívateľa"}.
{"Get Number of Registered Users", "Zobraziť počet registrovaných užívateľov"}.
{"Get Number of Online Users", "Zobraziť počet pripojených užívateľov"}.
{"User Management", "Správa užívateľov"}.
{"Time delay", "Časový posun"}.
{"Password Verification", "Overenie hesla"}.
{"Number of registered users", "Počet registrovaných užívateľov"}.
{"Number of online users", "Počet online užívateľov"}.
{"Last login", "Posledné prihlásenie"}.
{"Roster size", "Počet kontaktov v zozname"}.
{"IP addresses", "IP adresa"}.
{"Resources", "Zdroje"}.
{"Choose storage type of tables", "Vyberte typ úložiska pre tabuľky"}.
{"RAM copy", "Kópia RAM"}.
{"RAM and disc copy", "Kópia RAM a disku"}.
{"Disc only copy", "Len kópia disku"}.
{"Remote copy", "Vzdialená kópia"}.
{"Stop Modules at ", "Zastaviť moduly na "}.
{"Choose modules to stop", "Vyberte moduly, ktoré majú byť zastavené"}.
{"Start Modules at ", "Spustiť moduly na "}.
{"Enter list of {Module, [Options]}", "Vložte zoznam modulov {Modul, [Parametre]}"}.
{"List of modules to start", "Zoznam modulov, ktoré majú byť spustené"}.
{"Backup to File at ", "Záloha do súboru na "}.
{"Enter path to backup file", "Zadajte cestu k súboru so zálohou"}.
{"Path to File", "Cesta k súboru"}.
{"Restore Backup from File at ", "Obnoviť zálohu zo súboru na "}.
{"Dump Backup to Text File at ", "Uložiť zálohu do textového súboru na "}.
{"Enter path to text file", "Zadajte cestu k textovému súboru"}.
{"Import User from File at ", "Importovať užívateľa zo súboru na "}.
{"Enter path to jabberd1.4 spool file", "Zadajte cestu k spool súboru jabberd1.4"}.
{"Import Users from Dir at ", "Importovať užívateľov z adresára na "}.
{"Enter path to jabberd1.4 spool dir", "Zadajte cestu k jabberd1.4 spool adresáru"}.
{"Path to Dir", "Cesta k adresáru"}.
{"Access Control List Configuration", "Konfigurácia zoznamu prístupových oprávnení (ACL)"}.
{"Access control lists", "Zoznamy prístupových oprávnení (ACL)"}.
{"Access Configuration", "Konfigurácia prístupu"}.
{"Access rules", "Prístupové pravidlá"}.
{"Administration of ", "Administrácia "}.
{"Action on user", "Operácia aplikovaná na užívateľa"}.
{"Edit Properties", "Editovať vlastnosti"}.
{"Remove User", "Odstrániť užívateľa"}.
{"Database", "Databáza"}.
{"Outgoing s2s Connections", "Odchádzajúce s2s spojenia"}.
{"Import Users From jabberd 1.4 Spool Files", "Importovať užívateľov z jabberd 1.4 spool súborov"}.
{"Database Tables Configuration at ", "Konfigurácia databázových tabuliek "}.

% mod_disco.erl
{"Configuration", "Konfigurácia"}.
{"Online Users", "Online užívatelia"}.
{"All Users", "Všetci užívatelia"}.
{"To ~s", "Pre ~s"}.
{"From ~s", "Od  ~s"}.
{"Running Nodes", "Bežiace uzly"}.
{"Stopped Nodes", "Zastavené uzly"}.
{"Access Control Lists", "Zoznamy prístupových oprávnení (ACL)"}.
{"Access Rules", "Prístupové pravidlá"}.
{"Modules", "Moduly"}.
{"Start Modules", "Spustiť moduly"}.
{"Stop Modules", "Zastaviť moduly"}.
{"Backup Management", "Správa zálohovania"}.
{"Backup", "Zálohovať"}.
{"Restore", "Obnoviť"}.
{"Dump to Text File", "Uložiť do textového súboru"}.
{"Import File", "Import súboru"}.
{"Import Directory", "Import adresára"}.

% mod_register.erl
{"Users are not allowed to register accounts so fast", "Nieje možné vytvárať účty tak rýchlo po sebe"}.
{"Choose a username and password to register with this server", "Zvolte meno užívateľa a heslo pre registráciu na tomto servere"}.

% mod_vcard.erl
{"You need an x:data capable client to search", "Na vyhľadávanie potrebujete klienta podporujúceho x:data"}.
{"Search users in ", "Hľadať užívateľov v "}.
{"Fill in fields to search for any matching Jabber User", "Vyplnte políčka pre vyhľadávanie Jabber užívateľa"}.
{"User",              "Užívateľ: "}.
{"Full Name", 	      "Celé meno: "}.
{"Name", 	      "Meno: "}.
{"Middle Name",       "Prostredné meno: "}.
{"Family Name",       "Priezvisko: "}.
{"Nickname", 	      "Prezývka: "}.
{"Birthday", 	      "Dátum narodenia: "}.
{"Country", 	      "Krajina: "}.
{"City", 	      "Mesto: "}.
{"Organization Name", "Meno organizácie: "}.
{"Organization Unit", "Organizačná jednotka: "}.

% mod_muc/mod_muc.erl
{"Chatrooms", "Diskusné miestnosti"}.
{"You need an x:data capable client to register nickname", "Na registráciu prezývky potrebujete klienta podporujúceho z x:data"}.
{"Nickname Registration at ", "Registrácia prezývky na "}.
{"Enter nickname you want to register", "Zadajte prezývku, ktorú chcete registrovať"}.
{"Only service administrators are allowed to send service messages", "Iba správcovia služby majú povolené odosielanie servisných správ"}.
{"Conference room does not exist", "Diskusná miestnosť neexistuje"}.
{"Access denied by service policy", "Prístup bol zamietnutý nastavením služby"}.
{"You must fill in field \"nick\" in the form", "Musíte vyplniť políčko \"prezývka\"  vo formulári"}.
{"Specified nickname is already registered", "Zadaná prezývka je už registrovaná"}.
{"You must fill in field \"Nickname\" in the form", "Musíte vyplniť políčko \"Prezývka\" vo formulári"}.
{"ejabberd MUC module", "ejabberd MUC modul"}.

% mod_muc/mod_muc_room.erl
{"Traffic rate limit is exceeded", "Bol prekročený prenosový limit"}.
{"This participant is kicked from the room because he sent an error message", "Účastník bol vyhodený z miestnosti, pretože poslal chybovú správu"}.
{"This participant is kicked from the room because he sent an error message to another participant", "Účastník bol vyhodený z miestnosti, pretože poslal chybovú správu inému účastníkovi"}.
{"It is not allowed to send private messages", "Nieje povolené posielať súkromné správy"}.
{"This participant is kicked from the room because he sent an error presence", "Účastník bol vyhodený z miestnosti, pretože poslal chybovú správu o stave"}.
{"Visitors are not allowed to change their nicknames in this room", "V tejto miestnosti nieje povolené meniť prezývky"}.
{"Maximum Number of Occupants", "Počet účastníkov"}.
{"No limit", "Bez limitu"}.
{"Present real JIDs to", "Zobrazovať skutočné JID"}.
{"moderators only", "moderátorom"}.
{"anyone", "všetkým"}.
{"Allow visitors to send status text in presence updates", "Návštevníci môžu posielať textové informácie v stavových správach"}.
{"Allow visitors to change nickname", "Návštevníci môžu meniť prezývky"}.
{"~s invites you to the room ~s", "~s Vás pozýva do miestnosti ~s"}.
{"the password is", "heslo je"}.
{"Make room moderated", "Nastaviť miestnosť ako moderovanú"}.
{"This room is not anonymous", "Táto miestnosť nie je anonymná"}.
{"Make room persistent", "Nastaviť miestnosť ako trvalú"}.
{"Make room public searchable", "Nastaviť miestnosť ako verejne prehľadávateľnú"}.
{"Make participants list public", "Nastaviť zoznam zúčastnených ako verejný"}.
{"Make room password protected", "Chrániť miestnosť heslom"}.
{"Make room members-only", "Nastaviť miestnosť len pre členov"}.
{"Make room moderated", "Nastaviť miestnosť ako moderovanú"}.
{"Default users as participants", "Užívatelia sú implicitne členmi"}.
{"Allow users to change subject", "Povoliť užívateľom zmeniť tému tejto miestnosti"}.
{"Allow users to send private messages", "Povoliť užívateľom odosielať súkromné správy"}.
{"Allow users to query other users", "Povoliť užívateľom dotazovať sa informácie o iných užívateľoch"}.
{"Allow users to send invites", "Povoliť používateľom posielanie pozvánok"}.
{"Enable logging", "Zapnúť zaznamenávanie histórie"}.
{"Number of occupants", "Počet zúčastnených"}.
{" has set the subject to: ", "zmenil(a) tému na: "}.
{"You need an x:data capable client to configure room", "Na konfiguráciu miestnosti potrebujete klienta podporujúceho x:data"}.
{"Configuration for ", "Konfigurácia pre "}.
{"Room title", "Názov miestnosti"}.
{"Password", "Heslo"}.
{"Only moderators and participants are allowed to change subject in this room", "Len moderátori a zúčastnený majú povolené meniť tému tejto miestnosti"}.
{"Only moderators are allowed to change subject in this room", "Len moderátori majú povolené meniť tému miestnosti"}.
{"Visitors are not allowed to send messages to all occupants", "Návštevníci nemajú povolené zasielať správy všetkým prihláseným do konferencie"}.
{"Only occupants are allowed to send messages to the conference", "Len členovia majú povolené zasielať správy do konferencie"}.
{"It is not allowed to send private messages to the conference", "Nie je povolené odosielať súkromné správy do konferencie"}.
{"Improper message type", "Nesprávny typ správy"}.
{"Nickname is already in use by another occupant", "Prezývka je už používaná iným členom"}.
{"Nickname is registered by another person", "Prezývka je registrovaná inou osobou"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Nie je dovolené odoslanie súkromnej správy typu \"Skupinová správa\" "}.
{"Recipient is not in the conference room", "Príjemca sa nenachádza v konferenčnej miestnosti"}.
{"Only occupants are allowed to send queries to the conference", "Len členovia majú povolené dotazovať sa o konferencii"}.
{"Queries to the conference members are not allowed in this room", "Dotazovať sa o členoch nie je v tejto miestnosti povolené"}.
{"You have been banned from this room", "Boli ste vylúčený z tejto miestnosti"}.
{"Membership required to enter this room", "Pre vstup do miestnosti je potrebné byť členom"}.
{"Password required to enter this room", "Pre vstup do miestnosti je potrebné heslo"}.
{"Incorrect password", "Nesprávne heslo"}.
{"Administrator privileges required", "Sú potrebné práva administrátora"}.
{"Moderator privileges required", "Sú potrebné práva moderátora"}.
{"JID ~s is invalid", "JID ~s je neplatné"}.
{"Nickname ~s does not exist in the room", "Prezývka ~s v miestnosti neexistuje"}.
{"Invalid affiliation: ~s", "Neplatné priradenie: ~s"}.
{"Invalid role: ~s", "Neplatná rola: ~s"}.
{"Owner privileges required", "Sú vyžadované práva vlastníka"}.
{"private, ", "súkromná, "}.

% mod_irc/mod_irc.erl
{"IRC Transport", "IRC Transport"}.
{"You need an x:data capable client to configure mod_irc settings", "Pre konfiguráciu mod_irc potrebujete klienta podporujúceho x:data"}.
{"Registration in mod_irc for ", "Registrácia do mod_irc na "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Vložte meno používateľa a kódovanie, ktoré chcete používať pri pripojení na IRC server"}.
{"IRC Username", "IRC prezývka"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Príklad: [{\"irc.freenode.net\",\"utf-8\"}, {\"irc.freenode.net\", \"iso8859-2\"}]."}.
{"Encodings", "Kódovania"}.

% web/ejabberd_web_admin.erl
{"Uptime:", "Uptime:"}.
{"ejabberd Web Admin", "ejabberd Web Admin"}.
{"Users", "Používatelia"}.
{"Nodes", "Uzly"}.
{"Statistics", "Štatistiky"}.
{"Delete Selected", "Zmazať vybrané"}.
{"Submit", "Odoslať"}.
{"~s access rule configuration", "~s konfigurácia prístupového pravidla"}.
{"Node not found", "Uzol nenájdený"}.
{"Add New", "Pridať nový"}.
{"Change Password", "Zmeniť heslo"}.
{"Connected Resources:", "Pripojené zdroje:"}.
{"Password:", "Heslo:"}.
{"None", "Nič"}.
{"Node ", "Uzol "}.
{"Restart", "Reštart"}.
{"Stop", "Stop"}.
{"Name", "Meno"}.
{"Storage Type", "Typ úložiska"}.
{"Size", "Veľkosť"}.
{"Memory", "Pamäť"}.
{"OK", "OK"}.
{"Listened Ports at ", "Otvorené porty na "}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Nastavenia"}.
{"Update", "Aktualizovať"}.
{"Delete", "Zmazať"}.
{"Add User", "Pridať používateľa"}.
{"Last Activity", "Posledná aktivita"}.
{"Never", "Nikdy"}.
{"Time", "Čas"}.
{"From", "Od"}.
{"To", "Pre"}.
{"Packet", "Paket"}.
{"Roster", "Zoznam kontaktov"}.
{"Nickname", "Prezývka"}.
{"Subscription", "Prihlásenie"}.
{"Pending", "Čakajúce"}.
{"Groups", "Skupiny"}.
{"Remove", "Odstrániť"}.
{"User ", "Používateľ "}.
{"Roster of ", "Zoznam kontaktov "}.
{"Online", "Online"}.
{"Validate", "Overiť"}.
{"Name:", "Meno:"}.
{"Description:", "Popis:"}.
{"Members:", "Členovia:"}.
{"Displayed Groups:", "Zobrazené skupiny:"}.
{"Group ", "Skupina "}.
{"Period: ", "Čas:"}.
{"Last month", "Posledný mesiac"}.
{"Last year", "Posledný rok"}.
{"All activity", "Všetky aktivity"}.
{"Show Ordinary Table", "Zobraziť bežnú tabuľku"}.
{"Show Integral Table", "Zobraziť kompletnú tabuľku"}.
{"Start", "Štart"}.
{"Modules at ", "Moduly na "}.
{"Virtual Hosts", "Virtuálne servery"}.
{"ejabberd virtual hosts", "ejabberd virtuálne servery"}.
{"Host", "Server"}.
{"Administration", "Administrácia"}.
{"(Raw)", "(Raw)"}.
{"Submitted", "Odoslané"}.
{"Bad format", "Zlý formát"}.
{"Raw", "Raw"}.
{"Users Last Activity", "Posledná aktivita používateľa"}.
{"Registered Users", "Registrovaní používatelia"}.
{"Offline Messages", "Offline správy"}.
{"Registered Users:", "Registrovaní používatelia:"}.
{"Online Users:", "Online používatelia:"}.
{"Outgoing s2s Connections:", "Odchádzajúce s2s spojenia:"}.
{"Outgoing s2s Servers:", "Odchádzajúce s2s servery:"}.
{"Offline Messages:", "Offline správy"}.
{"~s's Offline Messages Queue", "~s Offline správy"}.
{"Add Jabber ID", "Pridať JID"}.
{"No Data", "Žiadne dáta"}.
{"Listened Ports", "Otvorené portov"}.
{"RPC Call Error", "Chyba RPC volania"}.
{"Database Tables at ", "Databázové tabuľky na "}.
{"Backup of ", "Záloha na "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Podotýkame, že tieto nastavenia budú zálohované do zabudovanej Mnesia databázy. Ak používate ODBC modul, musíte zálohovať vašu SQL databázu separátne."}.
{"Store binary backup:", "Uložiť binárnu zálohu:"}.
{"Restore binary backup immediately:", "Okamžite obnoviť binárnu zálohu:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Obnoviť binárnu zálohu pri nasledujúcom reštarte ejabberd (vyžaduje menej pamäte)"}.
{"Store plain text backup:", "Uložiť zálohu do textového súboru:"}.
{"Restore plain text backup immediately:", "Okamžite obnoviť zálohu z textového súboru:"}.
{"Statistics of ~p", "Štatistiky ~p"}.
{"CPU Time:", "Čas procesoru"}.
{"Transactions Commited:", "Transakcie potvrdená"}.
{"Transactions Aborted:", "Transakcie zrušená"}.
{"Transactions Restarted:", "Transakcie reštartovaná"}.
{"Transactions Logged:", "Transakcie zaznamenaná"}.
{"Update ", "Aktualizovať "}.
{"Update plan", "Aktualizovať plán"}.
{"Updated modules", "Aktualizované moduly"}.
{"Update script", "Aktualizované skripty"}.
{"Low level update script", "Nízkoúrovňový aktualizačný skript"}.
{"Script check", "Kontrola skriptu"}.
{"Shared Roster Groups", "Skupiny pre zdieľaný zoznam kontaktov"}.

% mod_vcard_odbc.erl
{"vCard User Search", "Hľadať užívateľov vo vCard"}.
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"Email", "E-mail"}.
{"ejabberd vCard module", "ejabberd vCard modul"}.
{"Search Results for ", "Hľadať výsledky pre "}.
{"Jabber ID", "Jabber ID"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Pre vyhľadanie Jabber používateľa vyplňte formulár (pridajte znak * na koniec, pre vyhľadanie podreťazca)"}.

% ejabberd_c2s.erl
{"Replaced by new connection", "Nahradené novým spojením"}.
{"Use of STARTTLS required", "Použitie STARTTLS je vyžadované"}.
{"Replaced by new connection", "Nahradené novým spojením"}.

% mod_vcard_ldap.erl

% mod_pubsub/mod_pubsub.erl
{"Publish-Subscribe", "Publish-Subscribe"}.
{"ejabberd Publish-Subscribe module", "ejabberd Publish-Subscribe modul"}.
{"PubSub subscriber request", "Žiadosť odberateľa PubSub"}.
{"Choose whether to approve this entity's subscription.", "Zvolte, či chcete povoliť toto odoberanie"}.
{"Node ID", "ID uzlu"}.
{"Subscriber Address", "Adresa odberateľa"}.
{"Allow this JID to subscribe to this pubsub node?", "Dovoliť tomuto JID odoberať PubSub uzol?"}.
{"Deliver event notifications", "Doručiť oznamy o udalosti"}.
{"A friendly name for the node", "Prístupný názov pre uzol"}.
{"Specify the access model", "Uveďte model prístupu"}.
{"Roster groups allowed to subscribe", "Skupiny kontaktov, ktoré môžu odoberať"}.
{"When to send the last published item", "Kedy odoslať posledne publikovanú položku"}.
{"Deliver payloads with event notifications", "Doručiť náklad s upozornením na udalosť"}.
{"Notify subscribers when the node configuration changes", "Upozorniť prihlásených používateľov na zmenu nastavenia uzlu"}.
{"Notify subscribers when the node is deleted", "Upozorniť prihlásených používateľov na zmazanie uzlu"}.
{"Notify subscribers when items are removed from the node", "Upozorniť prihlásených používateľov na odstránenie položiek z uzlu"}.
{"Persist items to storage", "Uložiť položky natrvalo do úložiska"}.
{"Max # of items to persist", "Maximálny počet položiek, ktoré je možné natrvalo uložiť"}.
{"Whether to allow subscriptions", "Povoliť prihlasovanie"}.
{"Specify the publisher model", "Špecifikovať model publikovania"}.
{"Max payload size in bytes", "Maximálny náklad v bajtoch"}.
{"Only deliver notifications to available users", "Doručovať upozornenia len aktuálne prihláseným používateľom"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "ejabberd IRC modul"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Ak chcete zadať iné kódovania pre IRC servery, vyplnte zoznam s hodnotami vo formáte '{\"irc server\",\"encoding\"}'. Predvolené kódovanie pre túto službu je \"~s\"."}.

% mod_muc/mod_muc.erl
{"Room creation is denied by service policy", "Vytváranie miestnosti nie je povolené"}.
{"ejabberd MUC module", "ejabberd MUC modul"}.

% mod_adhoc.erl
{"Commands", "Príkazy"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Send announcement to all users on all hosts", "Poslať oznámenie všetkým užívateľom na všetkých serveroch"}.
{"Set message of the day on all hosts and send to online users", "Nastaviť správu dňa na všetkých serveroch a poslať ju online užívateľom"}.
{"Update message of the day on all hosts (don't send)", "Upraviť správu dňa na všetkých serveroch"}.
{"Delete message of the day on all hosts", "Zmazať správu dňa na všetkých serveroch"}.
{"Really delete message of the day?", "Skutočne zmazať správu dňa?"}.
{"Subject", "Predmet"}.
{"Message body", "Telo správy"}.
{"No body provided for announce message", "Správa neobsahuje text"}.
{"Announcements", "Oznámenia"}.
{"Send announcement to all users", "Odoslať oznam všetkým používateľom"}.
{"Send announcement to all online users", "Odoslať zoznam všetkým online používateľom"}.
{"Send announcement to all online users on all hosts", "Odoslať oznam všetkým online používateľom na všetkých serveroch"}.
{"Set message of the day and send to online users", "Nastaviť správu dňa a odoslať ju online používateľom"}.
{"Update message of the day (don't send)", "Aktualizovať správu dňa (neodosielať)"}.
{"Delete message of the day", "Zmazať správu dňa"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "ejabberd IRC modul"}.

% mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "bol vyhodený(á) kvôli zmene priradenia"}.
{"has been kicked because the room has been changed to members-only", "bol vyhodený(á), pretože miestnosť bola vyhradená len pre členov"}.
{"has been kicked because of a system shutdown", "bol vyhodený(á) kvôli reštartu systému"}.
{"Chatroom configuration modified", "Nastavenie diskusnej miestnosti bolo zmenené"}.
{"joins the room", "vstúpil(a) do miestnosti"}.
{"leaves the room", "odišiel(a) z miestnosti"}.
{"has been kicked", "bol(a) vyhodený(á) z miestnosti"}.
{"has been banned", "bol(a) zablokovaný(á)"}.
{"is now known as", "sa premenoval(a) na"}.
{"Monday", "Pondelok"}.
{"Tuesday", "Utorok"}.
{"Wednesday", "Streda"}.
{"Thursday", "Štvrtok"}.
{"Friday", "Piatok"}.
{"Saturday", "Sobota"}.
{"Sunday", "Nedeľa"}.
{"January", "Január"}.
{"February", "Február"}.
{"March", "Marec"}.
{"April", "Apríl"}.
{"May", "Máj"}.
{"June", "Jún"}.
{"July", "Júl"}.
{"August", "August"}.
{"September", "September"}.
{"October", "Október"}.
{"November", "November"}.
{"December", "December"}.
{"Room Configuration", "Nastavenia miestnosti"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams modul"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Fronta offline správ tohoto kontaktu je plná. Správa bola zahodená."}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
