{"Access Configuration","Konfigurácia prístupu"}.
{"Access Control List Configuration","Konfigurácia zoznamu prístupových oprávnení (ACL)"}.
{"Access control lists","Zoznamy prístupových oprávnení (ACL)"}.
{"Access Control Lists","Zoznamy prístupových oprávnení (ACL)"}.
{"Access rules","Prístupové pravidlá"}.
{"Access Rules","Prístupové pravidlá"}.
{"Action on user","Operácia aplikovaná na užívateľa"}.
{"Add Jabber ID","Pridať Jabber ID"}.
{"Add New","Pridať nový"}.
{"Add User","Pridať používateľa"}.
{"Administration","Administrácia"}.
{"Administration of ","Administrácia "}.
{"Administrator privileges required","Sú potrebné práva administrátora"}.
{"A friendly name for the node","Prístupný názov pre uzol"}.
{"All activity","Všetky aktivity"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Dovoliť tomuto Jabber ID odoberať PubSub uzol?"}.
{"Allow users to change the subject","Povoliť užívateľom meniť tému"}.
{"Allow users to query other users","Povoliť užívateľom dotazovať sa informácie o iných užívateľoch"}.
{"Allow users to send invites","Povoliť používateľom posielanie pozvánok"}.
{"Allow users to send private messages","Povoliť užívateľom odosielať súkromné správy"}.
{"Allow visitors to change nickname","Návštevníci môžu meniť prezývky"}.
{"Allow visitors to send status text in presence updates","Návštevníci môžu posielať textové informácie v stavových správach"}.
{"All Users","Všetci užívatelia"}.
{"Announcements","Oznámenia"}.
{"anyone","všetkým"}.
{"A password is required to enter this room","Pre vstup do miestnosti je potrebné heslo"}.
{"April","Apríl"}.
{"August","August"}.
{"Backup Management","Správa zálohovania"}.
{"Backup of ","Záloha "}.
{"Backup to File at ","Záloha do súboru na "}.
{"Backup","Zálohovať"}.
{"Bad format","Zlý formát"}.
{"Birthday","Dátum narodenia"}.
{"Change Password","Zmeniť heslo"}.
{"Change User Password","Zmeniť heslo užívateľa"}.
{"Choose a username and password to register with this server","Zvolte meno užívateľa a heslo pre registráciu na tomto servere"}.
{"Choose modules to stop","Vyberte moduly, ktoré majú byť zastavené"}.
{"Choose storage type of tables","Vyberte typ úložiska pre tabuľky"}.
{"Choose whether to approve this entity's subscription.","Zvolte, či chcete povoliť toto odoberanie"}.
{"City","Mesto"}.
{"Commands","Príkazy"}.
{"Configuration","Konfigurácia"}.
{"Configuration of room ~s","Konfigurácia miestnosti ~s"}.
{"Connected Resources:","Pripojené zdroje:"}.
{"Country","Krajina"}.
{"CPU Time:","Čas procesoru"}.
{"Database","Databáza"}.
{"Database Tables at ","Databázové tabuľky na "}.
{"Database Tables Configuration at ","Konfigurácia databázových tabuliek "}.
{"December","December"}.
{"Default users as participants","Užívatelia sú implicitne členmi"}.
{"Delete message of the day on all hosts","Zmazať správu dňa na všetkých serveroch"}.
{"Delete message of the day","Zmazať správu dňa"}.
{"Delete Selected","Zmazať vybrané"}.
{"Delete User","Vymazať užívateľa"}.
{"Delete","Zmazať"}.
{"Deliver event notifications","Doručiť oznamy o udalosti"}.
{"Deliver payloads with event notifications","Doručiť náklad s upozornením na udalosť"}.
{"Description:","Popis:"}.
{"Disc only copy","Len kópia disku"}.
{"Dump Backup to Text File at ","Uložiť zálohu do textového súboru na "}.
{"Dump to Text File","Uložiť do textového súboru"}.
{"Edit Properties","Editovať vlastnosti"}.
{"ejabberd MUC module","ejabberd MUC modul"}.
{"ejabberd Publish-Subscribe module","ejabberd Publish-Subscribe modul"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams modul"}.
{"ejabberd vCard module","ejabberd vCard modul"}.
{"ejabberd virtual hosts","ejabberd virtuálne servery"}.
{"ejabberd Web Admin","ejabberd Web Admin"}.
{"Elements","Prvky"}.
{"Email","E-mail"}.
{"Enable logging","Zapnúť zaznamenávanie histórie"}.
{"End User Session","Ukončiť reláciu užívateľa"}.
{"Enter list of {Module, [Options]}","Vložte zoznam modulov {Modul, [Parametre]}"}.
{"Enter nickname you want to register","Zadajte prezývku, ktorú chcete registrovať"}.
{"Enter path to backup file","Zadajte cestu k súboru so zálohou"}.
{"Enter path to jabberd14 spool dir","Zadajte cestu k jabberd14 spool adresáru"}.
{"Enter path to jabberd14 spool file","Zadajte cestu k spool súboru jabberd14"}.
{"Enter path to text file","Zadajte cestu k textovému súboru"}.
{"Enter the text you see","Zadajte zobrazený text"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Chyba"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Exportovať dáta všetkých uživateľov na serveri do súborov PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Exportovať dáta uživateľov na hostitelovi do súborov PIEFXIS (XEP-0227):"}.
{"Family Name","Priezvisko"}.
{"February","Február"}.
{"Fill in fields to search for any matching Jabber User","Vyplnte políčka pre vyhľadávanie Jabber užívateľa"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Pre vyhľadanie Jabber používateľa vyplňte formulár (pridajte znak * na koniec, pre vyhľadanie podreťazca)"}.
{"Friday","Piatok"}.
{"From","Od"}.
{"From ~s","Od  ~s"}.
{"Full Name","Celé meno: "}.
{"Get Number of Online Users","Zobraziť počet pripojených užívateľov"}.
{"Get Number of Registered Users","Zobraziť počet registrovaných užívateľov"}.
{"Get User Last Login Time","Zobraziť čas posledného prihlásenia"}.
{"Get User Password","Zobraziť heslo užívateľa"}.
{"Get User Statistics","Zobraziť štatistiku užívateľa"}.
{"Group ","Skupina "}.
{"Groups","Skupiny"}.
{"has been banned","bol(a) zablokovaný(á)"}.
{"has been kicked because of an affiliation change","bol vyhodený(á) kvôli zmene priradenia"}.
{"has been kicked because of a system shutdown","bol vyhodený(á) kvôli reštartu systému"}.
{"has been kicked because the room has been changed to members-only","bol vyhodený(á), pretože miestnosť bola vyhradená len pre členov"}.
{"has been kicked","bol(a) vyhodený(á) z miestnosti"}.
{" has set the subject to: ","zmenil(a) tému na: "}.
{"Host","Server"}.
{"Import Directory","Import adresára"}.
{"Import File","Import súboru"}.
{"Import user data from jabberd14 spool file:","Importovať dáta užívateľov z jabberd14 spool súboru:"}.
{"Import User from File at ","Importovať užívateľa zo súboru na "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Importovat dáta užívateľov zo súboru PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Importovať dáta užívateľov z jabberd14 spool adresára:"}.
{"Import Users from Dir at ","Importovať užívateľov z adresára na "}.
{"Import Users From jabberd14 Spool Files","Importovať užívateľov z jabberd14 spool súborov"}.
{"Improper message type","Nesprávny typ správy"}.
{"Incorrect password","Nesprávne heslo"}.
{"Invalid affiliation: ~s","Neplatné priradenie: ~s"}.
{"Invalid role: ~s","Neplatná rola: ~s"}.
{"IP addresses","IP adresa"}.
{"IP","IP"}.
{"is now known as","sa premenoval(a) na"}.
{"It is not allowed to send private messages","Nieje povolené posielať súkromné správy"}.
{"It is not allowed to send private messages of type \"groupchat\"","Nie je dovolené odoslanie súkromnej správy typu \"Skupinová správa\" "}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s je neplatné"}.
{"January","Január"}.
{"joins the room","vstúpil(a) do miestnosti"}.
{"July","Júl"}.
{"June","Jún"}.
{"Last Activity","Posledná aktivita"}.
{"Last login","Posledné prihlásenie"}.
{"Last month","Posledný mesiac"}.
{"Last year","Posledný rok"}.
{"leaves the room","odišiel(a) z miestnosti"}.
{"Listened Ports at ","Otvorené porty na "}.
{"Listened Ports","Otvorené portov"}.
{"List of modules to start","Zoznam modulov, ktoré majú byť spustené"}.
{"Low level update script","Nízkoúrovňový aktualizačný skript"}.
{"Make participants list public","Nastaviť zoznam zúčastnených ako verejný"}.
{"Make room captcha protected","Chrániť miestnosť systémom captcha"}.
{"Make room members-only","Nastaviť miestnosť len pre členov"}.
{"Make room moderated","Nastaviť miestnosť ako moderovanú"}.
{"Make room password protected","Chrániť miestnosť heslom"}.
{"Make room persistent","Nastaviť miestnosť ako trvalú"}.
{"Make room public searchable","Nastaviť miestnosť ako verejne prehľadávateľnú"}.
{"March","Marec"}.
{"Maximum Number of Occupants","Počet účastníkov"}.
{"Max # of items to persist","Maximálny počet položiek, ktoré je možné natrvalo uložiť"}.
{"Max payload size in bytes","Maximálny náklad v bajtoch"}.
{"May","Máj"}.
{"Members:","Členovia:"}.
{"Membership is required to enter this room","Pre vstup do miestnosti je potrebné byť členom"}.
{"Memory","Pamäť"}.
{"Message body","Telo správy"}.
{"Middle Name","Prostredné meno: "}.
{"Moderator privileges required","Sú potrebné práva moderátora"}.
{"moderators only","moderátorom"}.
{"Modified modules","Modifikované moduly"}.
{"Module","Modul"}.
{"Modules at ","Moduly na "}.
{"Modules","Moduly"}.
{"Monday","Pondelok"}.
{"Name:","Meno:"}.
{"Name","Meno"}.
{"Never","Nikdy"}.
{"Nickname","Prezývka"}.
{"Nickname Registration at ","Registrácia prezývky na "}.
{"Nickname ~s does not exist in the room","Prezývka ~s v miestnosti neexistuje"}.
{"No Data","Žiadne dáta"}.
{"Node ID","ID uzlu"}.
{"Node not found","Uzol nenájdený"}.
{"Nodes","Uzly"}.
{"Node ","Uzol "}.
{"No limit","Bez limitu"}.
{"None","Nič"}.
{"Not Found","Nebol nájdený"}.
{"Notify subscribers when items are removed from the node","Upozorniť prihlásených používateľov na odstránenie položiek z uzlu"}.
{"Notify subscribers when the node configuration changes","Upozorniť prihlásených používateľov na zmenu nastavenia uzlu"}.
{"Notify subscribers when the node is deleted","Upozorniť prihlásených používateľov na zmazanie uzlu"}.
{"November","November"}.
{"Number of occupants","Počet zúčastnených"}.
{"Number of online users","Počet online užívateľov"}.
{"Number of registered users","Počet registrovaných užívateľov"}.
{"October","Október"}.
{"Offline Messages:","Offline správy"}.
{"Offline Messages","Offline správy"}.
{"OK","OK"}.
{"Online","Online"}.
{"Online Users:","Online používatelia:"}.
{"Online Users","Online užívatelia"}.
{"Only deliver notifications to available users","Doručovať upozornenia len aktuálne prihláseným používateľom"}.
{"Only moderators and participants are allowed to change the subject in this room","Len moderátori a zúčastnený majú povolené meniť tému tejto miestnosti"}.
{"Only moderators are allowed to change the subject in this room","Len moderátori majú povolené meniť tému miestnosti"}.
{"Options","Nastavenia"}.
{"Organization Name","Meno organizácie: "}.
{"Organization Unit","Organizačná jednotka: "}.
{"Outgoing s2s Connections:","Odchádzajúce s2s spojenia:"}.
{"Outgoing s2s Connections","Odchádzajúce s2s spojenia"}.
{"Outgoing s2s Servers:","Odchádzajúce s2s servery:"}.
{"Owner privileges required","Sú vyžadované práva vlastníka"}.
{"Packet","Paket"}.
{"Password:","Heslo:"}.
{"Password","Heslo"}.
{"Password Verification","Overenie hesla"}.
{"Path to Dir","Cesta k adresáru"}.
{"Path to File","Cesta k súboru"}.
{"Pending","Čakajúce"}.
{"Period: ","Čas:"}.
{"Persist items to storage","Uložiť položky natrvalo do úložiska"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Prosím, berte na vedomie, že tieto nastavenia zázálohujú iba zabudovnú Mnesia databázu. Ak používate ODBC modul, musíte zálohovať vašu SQL databázu separátne."}.
{"Pong","Pong"}.
{"Port","Port"}.
{"Present real Jabber IDs to","Zobrazovať skutočné Jabber ID"}.
{"private, ","súkromná, "}.
{"Protocol","Protokol"}.
{"Publish-Subscribe","Publish-Subscribe"}.
{"PubSub subscriber request","Žiadosť odberateľa PubSub"}.
{"Purge all items when the relevant publisher goes offline","Odstrániť všetky relevantné položky, keď užívateľ prejde do módu offline"}.
{"RAM and disc copy","Kópia RAM a disku"}.
{"RAM copy","Kópia RAM"}.
{"Raw","Raw"}.
{"Really delete message of the day?","Skutočne zmazať správu dňa?"}.
{"Registered Users:","Registrovaní používatelia:"}.
{"Registered Users","Registrovaní používatelia"}.
{"Remote copy","Vzdialená kópia"}.
{"Remove All Offline Messages","Odstrániť všetky offline správy"}.
{"Remove","Odstrániť"}.
{"Remove User","Odstrániť užívateľa"}.
{"Resources","Zdroje"}.
{"Restart","Reštart"}.
{"Restart Service","Reštartovať službu"}.
{"Restore Backup from File at ","Obnoviť zálohu zo súboru na "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Obnoviť binárnu zálohu pri nasledujúcom reštarte ejabberd (vyžaduje menej pamäte)"}.
{"Restore binary backup immediately:","Okamžite obnoviť binárnu zálohu:"}.
{"Restore","Obnoviť"}.
{"Restore plain text backup immediately:","Okamžite obnoviť zálohu z textového súboru:"}.
{"Room Configuration","Nastavenia miestnosti"}.
{"Room description","Popis miestnosti"}.
{"Room Occupants","Ľudí v miestnosti"}.
{"Room title","Názov miestnosti"}.
{"Roster groups allowed to subscribe","Skupiny kontaktov, ktoré môžu odoberať"}.
{"Roster of ","Zoznam kontaktov "}.
{"Roster size","Počet kontaktov v zozname"}.
{"Roster","Zoznam kontaktov"}.
{"RPC Call Error","Chyba RPC volania"}.
{"Running Nodes","Bežiace uzly"}.
{"~s access rule configuration","~s konfigurácia prístupového pravidla"}.
{"Saturday","Sobota"}.
{"Script check","Kontrola skriptu"}.
{"Search Results for ","Hľadať výsledky pre "}.
{"Search users in ","Hľadať užívateľov v "}.
{"Send announcement to all online users","Odoslať zoznam všetkým online používateľom"}.
{"Send announcement to all online users on all hosts","Odoslať oznam všetkým online používateľom na všetkých serveroch"}.
{"Send announcement to all users","Odoslať oznam všetkým používateľom"}.
{"Send announcement to all users on all hosts","Poslať oznámenie všetkým užívateľom na všetkých serveroch"}.
{"September","September"}.
{"Set message of the day and send to online users","Nastaviť správu dňa a odoslať ju online používateľom"}.
{"Set message of the day on all hosts and send to online users","Nastaviť správu dňa na všetkých serveroch a poslať ju online užívateľom"}.
{"Shared Roster Groups","Skupiny pre zdieľaný zoznam kontaktov"}.
{"Show Integral Table","Zobraziť kompletnú tabuľku"}.
{"Show Ordinary Table","Zobraziť bežnú tabuľku"}.
{"Shut Down Service","Vypnúť službu"}.
{"~s invites you to the room ~s","~s Vás pozýva do miestnosti ~s"}.
{"Specify the access model","Uveďte model prístupu"}.
{"Specify the event message type","Uveďte typ pre správu o udalosti"}.
{"Specify the publisher model","Špecifikovať model publikovania"}.
{"~s's Offline Messages Queue","~s Offline správy"}.
{"Start Modules at ","Spustiť moduly na "}.
{"Start Modules","Spustiť moduly"}.
{"Start","Štart"}.
{"Statistics of ~p","Štatistiky ~p"}.
{"Statistics","Štatistiky"}.
{"Stop Modules at ","Zastaviť moduly na "}.
{"Stop Modules","Zastaviť moduly"}.
{"Stopped Nodes","Zastavené uzly"}.
{"Stop","Zastaviť"}.
{"Storage Type","Typ úložiska"}.
{"Store binary backup:","Uložiť binárnu zálohu:"}.
{"Store plain text backup:","Uložiť zálohu do textového súboru:"}.
{"Subject","Predmet"}.
{"Submit","Odoslať"}.
{"Submitted","Odoslané"}.
{"Subscriber Address","Adresa odberateľa"}.
{"Subscription","Prihlásenie"}.
{"Sunday","Nedeľa"}.
{"That nickname is already in use by another occupant","Prezývka je už používaná iným členom"}.
{"That nickname is registered by another person","Prezývka je už zaregistrovaná inou osobou"}.
{"The captcha is valid.","Platná captcha."}.
{"The collections with which a node is affiliated","Kolekcie asociované s uzlom"}.
{"the password is","heslo je"}.
{"This participant is kicked from the room because he sent an error message to another participant","Účastník bol vyhodený z miestnosti, pretože poslal chybovú správu inému účastníkovi"}.
{"This participant is kicked from the room because he sent an error message","Účastník bol vyhodený z miestnosti, pretože poslal chybovú správu"}.
{"This participant is kicked from the room because he sent an error presence","Účastník bol vyhodený z miestnosti, pretože poslal chybovú správu o stave"}.
{"This room is not anonymous","Táto miestnosť nie je anonymná"}.
{"Thursday","Štvrtok"}.
{"Time","Čas"}.
{"Time delay","Časový posun"}.
{"To","Pre"}.
{"To ~s","Pre ~s"}.
{"Traffic rate limit is exceeded","Bol prekročený prenosový limit"}.
{"Transactions Aborted:","Transakcie zrušená"}.
{"Transactions Committed:","Transakcie potvrdená"}.
{"Transactions Logged:","Transakcie zaznamenaná"}.
{"Transactions Restarted:","Transakcie reštartovaná"}.
{"Tuesday","Utorok"}.
{"Unable to generate a captcha","Nepodarilo sa vygenerovat captcha"}.
{"Unauthorized","Neautorizovaný"}.
{"Update ","Aktualizovať "}.
{"Update","Aktualizovať"}.
{"Update message of the day (don't send)","Aktualizovať správu dňa (neodosielať)"}.
{"Update message of the day on all hosts (don't send)","Upraviť správu dňa na všetkých serveroch"}.
{"Update plan","Aktualizovať plán"}.
{"Update script","Aktualizované skripty"}.
{"Uptime:","Uptime:"}.
{"User Management","Správa užívateľov"}.
{"User ","Používateľ "}.
{"Users Last Activity","Posledná aktivita používateľa"}.
{"Users","Používatelia"}.
{"User","Užívateľ"}.
{"Validate","Overiť"}.
{"vCard User Search","Hľadať užívateľov vo vCard"}.
{"Visitors are not allowed to change their nicknames in this room","V tejto miestnosti nieje povolené meniť prezývky"}.
{"Visitors are not allowed to send messages to all occupants","Návštevníci nemajú povolené zasielať správy všetkým prihláseným do konferencie"}.
{"Wednesday","Streda"}.
{"When to send the last published item","Kedy odoslať posledne publikovanú položku"}.
{"Whether to allow subscriptions","Povoliť prihlasovanie"}.
{"You have been banned from this room","Boli ste vylúčený z tejto miestnosti"}.
{"You must fill in field \"Nickname\" in the form","Musíte vyplniť políčko \"Prezývka\" vo formulári"}.
{"You need an x:data capable client to configure room","Na konfiguráciu miestnosti potrebujete klienta podporujúceho x:data"}.
{"You need an x:data capable client to register nickname","Na registráciu prezývky potrebujete klienta podporujúceho z x:data"}.
{"You need an x:data capable client to search","Na vyhľadávanie potrebujete klienta podporujúceho x:data"}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Správa určená pre ~s bola zablokovaná. Oblokovať ju môžete na ~s"}.
