% $Id$
% Language: Slovak (slovenčina)
% Author: Juraj Michalek
% Author: SkLUG

% jlib.hrl
{"No resource provided", "Nebol poskytnutý žiadny zdroj"}.

% mod_configure.erl
{"Choose storage type of tables", "Vyberte typ úložiska pre tabuľky"}.
{"RAM copy", "Kópia RAM"}.
{"RAM and disc copy", "Kópia RAM a disku"}.
{"Disc only copy", "Len kópia disku"}.
{"Remote copy", "Vzdialená kópia"}.
{"Stop Modules at ", "Zastaviť moduly na "}.
{"Choose modules to stop", "Vyberte moduly, ktoré majú byť zastavené"}.
{"Start Modules at ", "Spustiť moduly na "}.
{"Enter list of {Module, [Options]}", "Vložte zoznam modulov {Modul, [Parametre]}"}.
{"List of modules to start", "Zoznam modulov, ktoré majú byť spustené"}.
{"Backup to File at ", "Záloha do súboru na "}.
{"Enter path to backup file", "Zadajte cestu k súboru so zálohou"}.
{"Path to File", "Cesta k súboru"}.
{"Restore Backup from File at ", "Obnoviť zálohu zo súboru na "}.
{"Dump Backup to Text File at ", "Uložiť zálohu do textového súboru na "}.
{"Enter path to text file", "Zadajte cestu k textovému súboru"}.
{"Import User from File at ", "Importovať používateľa zo súboru na "}.
{"Enter path to jabberd1.4 spool file", "Zadajte cestu k spool súboru jabberd1.4"}.
{"Import Users from Dir at ", "Importovať používateľov z adresára na "}.
{"Enter path to jabberd1.4 spool dir", "Zadajte cestu k jabberd1.4 spool adresáru"}.
{"Path to Dir", "Cesta k adresáru"}.
{"Hostname Configuration", "Konfigurácia mena servera"}.
{"Choose host name", "Vyberte meno servera"}.
{"Host name", "Host name"}.
{"Access Control List Configuration", "Konfigurácia zoznamu prístupových oprávnení (ACL)"}.
{"Access control lists", "Zoznamy prístupových oprávnení (ACL)"}.
{"Access Configuration", "Konfigurácia prístupu"}.
{"Access rules", "Prístupové pravidlá"}.
{"Remove Users", "Odstrániť používateľov"}.
{"Choose users to remove", "Zvoliť používateľov, ktorí budú odstránení"}.
{"Administration of ", "Administrácia "}.
{"Action on user", "Operácia aplikovaná na používateľa"}.
{"Edit Properties", "Editovať vlastnosti"}.
{"Remove User", "Odstrániť používateľa"}.
{"DB Tables Configuration at ", "Databázové tabuľky s konfiguráciou na "}.
{"Database", "Databáza"}.
{"Outgoing s2s Connections", "Odchdazájuce s2s spojenie"}.
{"Import Users From jabberd 1.4 Spool Files", "Importovať používateľov z jabber 1.4 spool súborov"}.
{"Database Tables Configuration at ", "Konfigurácia databázových tabuliek "}.

% mod_disco.erl
{"Configuration", "Konfigurácia"}.
{"Online Users", "Online používatelia"}.
{"All Users", "Všetci používatelia"}.
{"Outgoing S2S connections", "Odchádzajúce spojenie S2S"}.
{"To ~s", "Pre ~s"}.
{"From ~s", "Od  ~s"}.
{"Running Nodes", "Bežiace uzly"}.
{"Stopped Nodes", "Zastavené uzly"}.
{"Host Name", "Host name"}.
{"Access Control Lists", "Zoznamy prístupových oprávnení (ACL)"}.
{"Access Rules", "Prístupové pravidlá"}.
{"Remove Users", "Odstrániť používateľov"}.
{"DB", "DB"}.
{"Modules", "Moduly"}.
{"Start Modules", "Spustiť moduly"}.
{"Stop Modules", "Zastaviť moduly"}.
{"Backup Management", "Správa zálohovania"}.
{"Import users from jabberd1.4 spool files", "Importovať používateľov z jabberd1.4 spool súborov"}.
{"Backup", "Zálohovať"}.
{"Restore", "Obnoviť"}.
{"Dump to Text File", "Uložiť do textového súboru"}.
{"Import File", "Import súboru"}.
{"Import Directory", "Import adresára"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Vybrať meno používateľa a heslo pre registráciu na tomto serveri"}.

% mod_vcard.erl
{"You need an x:data capable client to search", "Na vyhľadávanie potrebujete klienta podporujúceho x:data"}.
{"Search users in ", "Hľadať používateľov v "}.
{"Fill in fields to search for any matching Jabber User", "Vyplnte políčka pre vyhľadávanie Jabber používateľa"}.
{"Results of search in ", "Výsledky vyhľadávania v "}.
{"User",              "Používateľ: "}.
{"Full Name", 	      "Celé meno: "}.
{"Name", 	      "Meno: "}.
{"Middle Name",       "Prostredné meno: "}.
{"Family Name",       "Priezvisko: "}.
{"Nickname", 	      "Prezývka: "}.
{"Birthday", 	      "Dátum narodenia: "}.
{"Country", 	      "Krajina: "}.
{"City", 	      "Mesto: "}.
{"email", 	      "E-mail: "}.
{"Organization Name", "Meno organizácie: "}.
{"Organization Unit", "Organizačná jednotka: "}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "Na registráciu prezývky potrebujete klienta podporujúceho z x:data"}.
{"Nickname Registration at ", "Registrácia prezývky na "}.
{"Enter nickname you want to register", "Zadajte prezývku, ktorú chete registrovať"}.
{"Only service administrators are allowed to send service messages", "Iba správcovia služby majú povolené odosielanie servisných správ"}.
{"Conference room does not exist", "Konferenčná miestnosť neexistuje"}.
{"Access denied by service policy", "Prístup bol zamiestnutý nastavení služby"}.
{"You must fill in field \"nick\" in the form", "Musíte vyplniť políčko \"prezývka\"  vo formulári"}.
{"Specified nickname is already registered", "Zadaná prezývka je už registrovaná"}.
{"You must fill in field \"Nickname\" in the form", "Musíte vyplniť políčko \"Prezývka\" vo formulári"}.
{"ejabberd MUC module", "Ejabberd MUC modul"}.

% mod_muc/mod_muc_room.erl
{"Make room moderated", "Nastaviť miestnosť ako moderovanú"}.
{"This room is not anonymous", "Táto miestnosť nie je anonymná"}.
{"Make room persistent", "Nastaviť miestnosť ako trvalú"}.
{"Make room public searchable", "Nastaviť miestnosť ako verejne prehľadávateľnú"}.
{"Make participants list public", "Nastaviť zoznam zúčastnených ako verejný"}.
{"Make room password protected", "Chrániť miestnosť heslom"}.
{"Make room semianonymous", "Nastaviť miestnosť ako čiastočne anonymnú"}.
{"Make room members-only", "Nastaviť miestnosť len pre členov"}.
{"Make room moderated", "Nastaviť miestnosť ako moderovanú"}.
{"Default users as participants", "Používatelia sú implicitne členmi"}.
{"Allow users to change subject", "Povoliť používateľom zmeniť tému tejto miestnosti"}.
{"Allow users to send private messages", "Povoliť používateľom odosielať súkromné správy"}.
{"Allow users to query other users", "Povoliť používateľom odosielať požiadavky (query) ostatným používateľom"}.
{"Allow users to send invites", "povoliť používateľom posielanie pozvánok"}.
{"Enable logging", "Zapnúť zaznamenávanie histórie"}.
{"Description", "Popis"}.
{"Number of occupants", "Počet zúčastnených"}.
{" has set the subject to: ", "zmiel(a) tému na: "}.
{"You need an x:data capable client to configure room", "Na konfiguráciu miestnosti potrebujete klienta podporujúceho x:data"}.
{"Configuration for ", "Konfigurácia pre "}.
{"Room title", "Názov miestnosti"}.
{"Allow users to change subject?", "Povoliť používateľom meniť tému?"}.
{"Allow users to query other users?", "Povoliť používateľom odosielať požiadavky (query) ostatným používateľom?"}.
{"Allow users to send private messages?", "Povoliť používateľom odosielať súkromné správy?"}.
{"Make room public searchable?", "Nastaviť miestnosť ako verejne prehľadávateľnú?"}.
{"Make participants list public?", "Nastaviť zoznam zúčastnených ako verejný?"}.
{"Make room persistent?", "Nastaviť miestnosť ako trvalú (persistent)?"}.
{"Make room moderated?", "Nastaviť miestnosť ako moderovanú?"}.
{"Default users as members?", "Používatelia sú implicitne členmi?"}.
{"Make room members only?", "Nastaviť miestnosť len pre členov?"}.
{"Allow users to send invites?", "Povoliť používateľom odosielať pozvánky?"}.
{"Make room password protected?", "Chrániť miestnosť heslom?"}.
{"Password", "Heslo"}.
{"Make room anonymous?", "Nastaviť miestnosť ako anonymnú?"}.
{"Enable logging?", "Zapnúť zaznamenávanie histórie?"}.
{"Only moderators and participants are allowed to change subject in this room", "Len moderátori a zúčastnený majú povolené meniť tému tejto miestnosti"}.
{"Only moderators are allowed to change subject in this room", "Len moderátori majú povolené meniť tému miestnosti"}.
{"Visitors are not allowed to send messages to all occupants", "Návštevníci nemajú povolené zasielať správy všetkým prihláseným do konferencie"}.
{"Only occupants are allowed to send messages to the conference", "Len členovia majú povolené zasielať správy do konferencie"}.
{"It is not allowed to send normal messages to the conference", "Nie je povolené odosielať normálne správy do konferencie"}.
{"It is not allowed to send private messages to the conference", "Nie je povolené odosielať súkromné správy do konferencie"}.
{"Improper message type", "Nesprávny typ správy"}.
{"Nickname is already in use by another occupant", "Prezývka je už používaná iným členom"}.
{"Nickname is registered by another person", "Prezývka je registrovaná inou osobou"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Nie je dovolené odoslanie súkromnej správy typu \"Skupinová správa\" "}.
{"Recipient is not in the conference room", "Príjemca sa nenachádza v konferenčnej miestnosti"}.
{"Only occupants are allowed to send queries to the conference", "Len členovia majú povolené odosielať požiadavky (query) do konferencie"}.
{"Queries to the conference members are not allowed in this room", "Požiadavky (queries) na členov konferencie nie sú povolené v tejto miestnosti"}.
{"You have been banned from this room", "Boli ste vylúčený z tejto miestnosti"}.
{"Membership required to enter this room", "Pre vstup do miestnosti je potrebné byť členom"}.
{"Password required to enter this room", "Pre vstup do miestnosti je potrebné heslo"}.
{"Incorrect password", "Nesprávne heslo"}.
{"Administrator privileges required", "Sú potrebné práva administrátora"}.
{"Moderator privileges required", "Sú potrebné práva moderátora"}.
{"JID ~s is invalid", "JID ~s je neplatné"}.
{"Nickname ~s does not exist in the room", "Prezývka ~s v miestnosti neexistuje"}.
{"Invalid affiliation: ~s", "Neplatné priradenie: ~s"}.
{"Invalid role: ~s", "Neplatná rola: ~s"}.
{"Owner privileges required", "Sú vyžadované práva vlastníka"}.
{"private, ", "súkromná, "}.

% mod_irc/mod_irc.erl
{"You need an x:data capable client to configure mod_irc settings", "Pre konfiguráciu mod_irc potrebujete klienta podporujúceho x:data"}.
{"Registration in mod_irc for ", "Registrácia do mod_irc na "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Vložte meno používateľa a kódovanie, ktoré chcete používať pri pripojení na IRC server"}.
{"IRC Username", "IRC prezývka"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Príklad: [{\"irc.freenode.net\",\"utf-8\"}, {\irc.freenode.net\", \"iso8859-2\"}]."}.
{"Encodings", "Kódovania"}.

% web/ejabberd_web_admin.erl
{"ejabberd administration", "Administrácia Ejabberd"}.
{"Users", "Používatelia"}.
{"Nodes", "Uzly"}.
{"Statistics", "Štatistiky"}.
{"(raw)", "(raw)"}.
{"submitted", "odoslané"}.
{"bad format", "zlý formát"}.
{"raw", "raw"}.
{"ejabberd access control lists configuration", "Konfigurácia zoznamu prístupových oprávnení (ACL) Ejabberd"}.
{"Delete Selected", "Zmazať vybrané"}.
{"Submit", "Odoslať"}.
{"ejabberd access rules configuration", "Konfigurácia prístupových pravidiel Ejabberd"}.
{"~s access rule configuration", "~s konfigurácia prístupového pravidla"}.
{"ejabberd users", "Používatelia Ejabberd"}.
{"ejabberd stats", "Štatistiky Ejabberd"}.
{"Node not found", "Uzol nenájdený"}.
{"Add New", "Pridať nový"}.
{"Registered users", "Registrovaní používatelia"}.
{"Online users", "Online používatelia"}.
{"Outgoing S2S servers", "Servery S2S pre odchádzajúcu komunikáciu"}.
{"Change Password", "Zmeniť heslo"}.
{"Connected Resources:", "Pripojené zdroje:"}.
{"Password:", "Heslo:"}.
{"None", "Nič"}.
{"Node ", "Uzol "}.
{"DB Management", "Správa databázy"}.
{"Listened Ports Management", "Správa otvorených portov"}.
{"Restart", "Reštart"}.
{"Stop", "Stop"}.
{"RPC call error", "Chyba RPC volania"}.
{"DB Tables at ", "Databázové tabuľky na "}.
{"Name", "Meno"}.
{"Storage Type", "Typ úložiska"}.
{"Size", "Veľkosť"}.
{"Memory", "Pamäť"}.
{"Backup Management at ", "Správa záloh na "}.
{"Store a backup in a file", "Uložiť zálohu do súboru "}.
{"OK", "OK"}.
{"Restore a backup from a file", "Obnoviť zálohu zo súboru"}.
{"Install a database fallback from a file", "Inštalovať fallback pre databázu zo súboru"}.
{"Dump a database in a text file", "Uložiť databázu do textového súboru"}.
{"Restore a database from a text file", "Obnoviť databázu z textového súboru"}.
{"Listened Ports at ", "Otvorené porty na "}.
{"~p statistics", "~p štatistiky"}.
{"Uptime", "Uptime"}.
{"CPU Time", "Čas procesoru"}.
{"Transactions commited", "Transakcie potvrdená"}.
{"Transactions aborted", "Transakcie zrušená"}.
{"Transactions restarted", "Transakcie reštartovaná"}.
{"Transactions logged", "Transakcie zaznamenaná"}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Nastavenia"}.
{"Update", "Aktualizovať"}.
{"Delete", "Zmazať"}.
{"Add User", "Pridať používateľa"}.
{"Offline messages", "Offline správy"}.
{"Last Activity", "Posledná aktivita"}.
{"Never", "Nikdy"}.
{"~s offline messages queue", "~s offline správy"}.
{"Time", "Čas"}.
{"From", "Od"}.
{"To", "Pre"}.
{"Packet", "Paket"}.
{"Offline messages:", "Offline správy:"}.
{"Roster", "Zoznam kontaktov"}.
{"Nickname", "Prezývka"}.
{"Subscription", "Prihlásenie"}.
{"Pending", "Čakajúce"}.
{"Groups", "Skupiny"}.
{"Remove", "Odstrániť"}.
{"Add JID", "Pridať JID"}.
{"User ", "Používateľ "}.
{"Roster of ", "Zoznam kontaktov "}.
{"Shared Roster", "Zdieľaný zoznam kontaktov"}.
{"Online", "Online"}.
{"Validate", "Overiť"}.
{"Not found", "Nenájdené"}.
{"Shared roster groups", "Skupiny pre zdieľaný zoznam kontaktov"}.
{"Name:", "Meno:"}.
{"Description:", "Popis:"}.
{"Members:", "Členovia:"}.
{"Displayed Groups:", "Zobrazené skupiny:"}.
{"Group ", "Skupina "}.
{"Users last activity", "Posledná aktivita používateľa"}.
{"Period: ", "Čas:"}.
{"Last month", "Posledný mesiac"}.
{"Last year", "Posledný rok"}.
{"All activity", "Všetky aktivity"}.
{"Show Ordinary Table", "Zobraziť bežnú tabuľku"}.
{"Show Integral Table", "Zobraziť kompletnú tabuľku"}.
{"Start", "Štart"}.
{"Modules Management", "Správa modulov"}.
{"Modules at ", "Moduly na "}.
{"No data", "Žiadne dáta"}.
{"Virtual Hosts", "Virtuálne servery"}.
{"ejabberd virtual hosts", "Ejabberd virtuálne servery"}.
{"Host", "Server"}.
{"ejabberd Web Interface", "Ejabberd Web rozhranie"}.
{"(raw)", "(raw)"}.
{"raw", "raw"}.
{"Authenticated users", "Autentifikovaný používatelia"}.
{"ejabberd Web Interface", "Ejabberd Web rozhranie"}.
{"Administration", "Administrácia"}.
{"ejabberd (c) 2002-2008 Alexey Shchepin, 2004-2008 Process One", "Ejabberd (c) 2002-2008 Alexey Shchepin, 2004-2008 Process One"}.
{"(Raw)", "(Raw)"}.
{"Submitted", "Odoslané"}.
{"Bad format", "Zlý formát"}.
{"Raw", "Raw"}.
{"Users Last Activity", "Posledná aktivita používateľa"}.
{"Registered Users", "Registrovaní používatelia"}.
{"Offline Messages", "Offline správy"}.
{"Registered Users:", "Registrovaní používatelia:"}.
{"Authenticated Users:", "Autentifikovaný používatelia:"}.
{"Online Users:", "Online používatelia:"}.
{"Outgoing s2s Connections:", "Odchádzajúce s2s spojenia:"}.
{"Outgoing s2s Servers:", "Odchádzajúce s2s servery:"}.
{"Offline Messages:", "Offline správy"}.
{"~s's Offline Messages Queue", "~s Offline správy"}.
{"Add Jabber ID", "Pridať JID"}.
{"No Data", "Žiadne dáta"}.
{"Listened Ports", "Otvorené portov"}.
{"RPC Call Error", "Chyba RPC volania"}.
{"Database Tables at ", "Databázové tabuľky na "}.
{"Backup of ", "Záloha na "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Podotýkame, že tieto nastavenia budú zálohované do zabudovanej Mnesia databázy. Ak používate ODBC modul, musíte zálohovať vašu SQL databázu separátne."}.
{"Store binary backup:", "Uložiť binárnu zálohu:"}.
{"Restore binary backup immediately:", "Okamžite obnoviť binárnu zálohu:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Obnoviť binárnu zálohu pri nasledujúcom reštarte Ejabberd (vyžaduje menej pamäte)"}.
{"Store plain text backup:", "Uložiť zálohu do textového súboru:"}.
{"Restore plain text backup immediately:", "Okamžite obnoviť zálohu z textového súboru:"}.
{"Statistics of ~p", "Štatistiky ~p"}.
{"Uptime:", "Uptime"}.
{"CPU Time:", "Čas procesoru"}.
{"Transactions Commited:", "Transakcie potvrdená"}.
{"Transactions Aborted:", "Transakcie zrušená"}.
{"Transactions Restarted:", "Transakcie reštartovaná"}.
{"Transactions Logged:", "Transakcie zaznamenaná"}.
{"Update ", "Aktualizovať "}.
{"Update plan", "Aktualizovať plán"}.
{"Updated modules", "Aktualizované moduly"}.
{"Update script", "Aktualizované skripty"}.
{"Low level update script", "Nízkoúrovňový aktualizačný skript"}.
{"Script check", "Kontrola skriptu"}.
{"Not Found", "Nenájdené"}.
{"Shared Roster Groups", "Skupiny pre zdieľaný zoznam kontaktov"}.

% mod_vcard_odbc.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"Email", "E-mail"}.
{"ejabberd vCard module", "Ejabberd vCard modul"}.
{"Search Results for ", "Hľadať výsledky pre "}.
{"Jabber ID", "Jabber ID"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Pre vyhľadanie Jabber používateľa vyplňte formulár (pridajte znak * na koniec, pre vyhľadanie podreťazca)"}.
{"JID", "JID"}.

% ejabberd_c2s.erl
{"Replaced by new connection", "Nahradené novým spojením"}.
{"Use of STARTTLS required", "Použitie STARTTLS je vyžadované"}.
{"Replaced by new connection", "Nahradené novým spojením"}.

% mod_vcard_ldap.erl
{"Given Name", "Meno"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module", "ejabberd pub/sub modul"}.
{"Node Creator", "Tvorca uzlu"}.
{"Deliver payloads with event notifications", "Doručovanie payload s upozorňovaním na udalosti"}.
{"Notify subscribers when the node configuration changes", "Upozorniť prihlásených používateľov na zmenu nastavenia uzlu"}.
{"Notify subscribers when the node is deleted", "Upozorniť prihlásených používateľov na zmazanie uzlu"}.
{"Notify subscribers when items are removed from the node", "Upozorniť prihlásených používateľov na odstránenie položiek z uzlu"}.
{"Persist items to storage", "Uložiť položky natrvalo do úložiska"}.
{"Max # of items to persist", "Maximálny počet položiek, ktoré je možné natrvalo uložiť"}.
{"Whether to allow subscriptions", "Povoliť prihlasovanie"}.
{"Specify the subscriber model", "Špecifikovať prihlasovací model"}.
{"Specify the publisher model", "Špecifikovať model publikovania"}.
{"Max payload size in bytes", "Maximálny payload v bajtoch"}.
{"Send items to new subscribers", "Odoslať položky novým používateľom"}.
{"Only deliver notifications to available users", "Doručovať upozornenia len aktuálne prihláseným používateľom"}.
{"Specify the current subscription approver", "Zadať súčasného schvaľovateľa prihlásení "}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "Ejabberd IRC module"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Ak chcete zadať iné kódovania pre IRC servery, vyplnte zoznam s hodnotami vo formáte '{\"irc server\",\"encoding\"}'. Predvolené kódovanie pre túto službu je \"~s\"."}.

% mod_muc/mod_muc.erl
{"Room creation is denied by service policy", "Vytváranie miestnosti nie je povolené"}.
{"ejabberd MUC module", "Ejabberd MUC modul"}.

% mod_adhoc.erl
{"Commands", "Príkazy"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Really delete message of the day?", "Skutočne zmazať správu dňa?"}.
{"Subject", "Predmet"}.
{"Message body", "Telo správy"}.
{"No body provided for announce message", "Správa neobsahuje text"}.
{"Announcements", "Oznámenia"}.
{"Send announcement to all users", "Odoslať oznam všetkým používateľom"}.
{"Send announcement to all online users", "Odoslať zoznam všetkým online používateľom"}.
{"Send announcement to all online users on all hosts", "Odoslať oznam všetkým online používateľom na všetkých serveroch"}.
{"Set message of the day and send to online users", "Nastaviť správu dňa a odoslať ju online používateľom"}.
{"Update message of the day (don't send)", "Aktualizovať správu dňa (neodosielať)"}.
{"Delete message of the day", "Zmazať správu dňa"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "Ejabberd IRC modul"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Nastavenie diskusnej miestnosti bolo zmenené"}.
{"joins the room", "vstúpil(a) do miestnosti"}.
{"leaves the room", "odišiel(a) z miestnosti"}.
{"has been kicked", "bol(a) vyhodený(á) z miestnosti"}.
{"has been banned", "bol(a) zablokovaný(á)"}.
{"is now known as", "sa premenoval(a) na"}.
{"Monday", "Pondelok"}.
{"Tuesday", "Utorok"}.
{"Wednesday", "Streda"}.
{"Thursday", "Štvrtok"}.
{"Friday", "Piatok"}.
{"Saturday", "Sobota"}.
{"Sunday", "Nedeľa"}.
{"January", "Január"}.
{"February", "Február"}.
{"March", "Marec"}.
{"April", "Apríl"}.
{"May", "Máj"}.
{"June", "Jún"}.
{"July", "Júl"}.
{"August", "August"}.
{"September", "September"}.
{"October", "Október"}.
{"November", "November"}.
{"December", "December"}.
{"Room Configuration", "Nastavenia miestnosti"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
