% $Id$
% Language: Swedish (svenska)
% Author: Thore Alstromer
% Author: Heysan
% Author: Magnus Henoch
% Author: Jonas Ådahl

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Du måste använda STARTTLS"}.
{"Replaced by new connection", "Ersatt av ny anslutning"}.

% jlib.hrl
{"No resource provided", "Ingen resurs angiven"}.

% mod_configure.erl
{"Database", "Databas"}.
{"Restart Service", "Starta om servicen"}.
{"Shut Down Service", "Stäng ner servicen"}.
{"Delete User", "Ta bort användare"}.
{"End User Session", "Avsluta användarsession"}.
{"Get User Password", "Hämta användarlösenord"}.
{"Change User Password", "Andra användarlösenord"}.
{"Get User Last Login Time", "Hämta användarens senast inloggade tid"}.
{"Get User Statistics", "Hämta användarstatistik"}.
{"Get Number of Registered Users", "Hämta antal registrerade användare"}.
{"Get Number of Online Users", "Hämta antal inloggade användare"}.
{"User Management", "Användarmanagement"}.
{"Outgoing s2s Connections", "Utgaende s2s anslutning"}.
{"Import Users From jabberd 1.4 Spool Files", "Importera användare från jabberd 1.4 Spool filer"}.
{"Database Tables Configuration at ", "Databastabellers konfiguration"}.
{"Time delay", "Tidsförsening"}.
{"Password Verification", "Lösenordsverifikation"}.
{"Number of registered users", "Antal registrerade användare"}.
{"Number of online users", "Antal inloggade användare"}.
{"Last login", "Senaste login"}.
{"Roster size", "Roster storlek"}.
{"IP addresses", "IP adresser"}.
{"Resources", "Resurser"}.
{"Choose storage type of tables", "Välj lagringstyp för tabeller"}.
{"RAM copy", "RAM-kopia"}.
{"RAM and disc copy", "RAM- och diskkopia"}.
{"Disc only copy", "Endast diskkopia"}.
{"Remote copy", "Sparas inte lokalt"}.
{"Stop Modules at ", "Stoppa moduler på "}.
{"Choose modules to stop", "Välj vilka moduler som skall stoppas"}.
{"Start Modules at ", "Starta moduler på "}.
{"Enter list of {Module, [Options]}", "Skriv in en lista av {Module, [Options]}"}.
{"List of modules to start", "Lista av moduler som skall startas"}.
{"Backup to File at ", "Säkerhetskopiera till fil på "}.
{"Enter path to backup file", "Skriv in sökväg till fil för säkerhetskopia"}.
{"Path to File", "Sökväg till fil"}.
{"Restore Backup from File at ", "Återställ säkerhetskopia från fil på "}.
{"Dump Backup to Text File at ", "Dumpa säkerhetskopia till textfil på "}.
{"Enter path to text file", "Skriv in sökväg till textfil"}.
{"Import User from File at ", "Importera användare från fil på "}.
{"Enter path to jabberd1.4 spool file", "Skriv in sökväg till spoolfil från jabberd1.4"}.
{"Import Users from Dir at ", "Importera användare från katalog på "}.
{"Enter path to jabberd1.4 spool dir", "Skriv in sökväg till spoolkatalog från jabberd1.4"}.
{"Path to Dir", "Sökväg till katalog"}.
{"Access Control List Configuration", "Konfiguera ACL"}.
{"Access control lists", "ACL"}.
{"Access Configuration", "Åtkomstkonfiguration"}.
{"Access rules", "Åtkomstregler"}.
{"Administration of ", "Administration av "}.
{"Action on user", "Handling mot användare"}.
{"Edit Properties", "Redigera egenskaper"}.
{"Remove User", "Ta bort användare"}.

% mod_disco.erl
{"Configuration", "Konfiguration"}.
{"Online Users", "Anslutna användare"}.
{"All Users", "Alla användare"}.
{"To ~s", "Till ~s"}.
{"From ~s", "Från ~s"}.
{"Running Nodes", "Körande noder"}.
{"Stopped Nodes", "Stannade noder"}.
{"Access Control Lists", "ACL"}.
{"Access Rules", "Åtkomstregler"}.
{"Modules", "Moduler"}.
{"Start Modules", "Starta moduler"}.
{"Stop Modules", "Stanna moduler"}.
{"Backup Management", "Hantera säkerhetskopior"}.
{"Backup", "Säkerhetskopiera"}.
{"Restore", "Återställ"}.
{"Dump to Text File", "Dumpa till textfil"}.
{"Import File", "Importera fil"}.
{"Import Directory", "Importera katalog"}.

% mod_register.erl
{"Users are not allowed to register accounts so fast", "Det är inte tillåtet för användare att skapa konton så fort"}.
{"Choose a username and password to register with this server", "Välj ett användarnamn och lösenord för att registrera mot denna server"}.

% mod_vcard.erl
{"Email", "Email"}.
{"vCard User Search", "vCard användare sök"}.
{"Search Results for ", "Sökresultat för"}.
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"ejabberd vCard module", "ejabberd vCard-modul"}.
{"You need an x:data capable client to search", "Du behöver en klient som stödjer x:data, för att kunna söka"}.
{"Search users in ", "Sök efter användare på "}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Fyll i formuläret för att söka efter en användare (lägg till * på slutet av fältet för att hitta alla som börjar så)"}.
{"User",              "Användarnamn"}.
{"Full Name", 	      "Fullständigt namn"}.
{"Name", 	      "Förnamn"}.
{"Middle Name",       "Mellannamn"}.
{"Family Name",       "Efternamn"}.
{"Nickname", 	      "Smeknamn"}.
{"Birthday", 	      "Födelsedag"}.
{"Country", 	      "Land"}.
{"City", 	      "Stad"}.
{"Organization Name", "Organisationsnamn"}.
{"Organization Unit", "Organisationsenhet"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Fyll i fält för att söka efter jabberanvändare"}.

% mod_vcard_odbc.erl

% mod_pubsub/mod_pubsub.erl
{"Publish-Subscribe", "Publikprenumeration"}.
{"ejabberd Publish-Subscribe module", "ejabberd publikprenumerations modul"}.
{"PubSub subscriber request", "Pubsub prenumerationsforfrågan"}.
{"Choose whether to approve this entity's subscription.", "Välj om du vill godkänna hela denna  prenumertion."}.
{"Node ID", "Node ID"}.
{"Subscriber Address", "Prenumerationsadress"}.
{"Allow this JID to subscribe to this pubsub node?", "Tillåt denna JID att prenumerera på denna pubsub node"}.
{"Deliver event notifications", "Skicka eventnotifikation"}.
{"A friendly name for the node", "Ett vänligt namn for noden"}.
{"Specify the access model", "Specificera accessmodellen"}.
{"Roster groups allowed to subscribe", "Rostergrupper tillåts att prenumerera"}.
{"When to send the last published item", "När att skicka senast publicerade ämne"}.
{"Deliver payloads with event notifications", "Skicka innehåll tillsammans med notifikationer"}.
{"Notify subscribers when the node configuration changes", "Meddela prenumeranter när nodens konfiguration ändras"}.
{"Notify subscribers when the node is deleted", "Meddela prenumeranter när noden tas bort"}.
{"Notify subscribers when items are removed from the node", "Meddela prenumeranter när dataposter tas bort från noden"}.
{"Persist items to storage", "Spara dataposter permanent"}.
{"Max # of items to persist", "Högsta antal dataposter som sparas"}.
{"Whether to allow subscriptions", "Tillåta prenumerationer?"}.
{"Specify the publisher model", "Ange publiceringsmodell"}.
{"Max payload size in bytes", "Högsta innehållsstorlek i bytes"}.
{"Only deliver notifications to available users", "Skicka notifikationer bara till uppkopplade användare"}.

% mod_muc/mod_muc.erl
{"Chatrooms", "Chattrum"}.
{"You must fill in field \"Nickname\" in the form", "Du måste fylla i fält \"smeknamn\" i formen"}.
{"You need an x:data capable client to register nickname", "Du behöver en klient som stödjer x:data för att registrera smeknamn"}.
{"Nickname Registration at ", "Registrera smeknamn på "}.
{"Enter nickname you want to register", "Skriv in smeknamnet du vill registrera"}.
{"ejabberd MUC module", "ejabberd MUC modul"}.
{"Only service administrators are allowed to send service messages", "Endast administratörer får skicka tjänstmeddelanden"}.
{"Room creation is denied by service policy", "Skapandet av rum är förbjudet enligt lokal policy"}.
{"Conference room does not exist", "Rummet finns inte"}.
{"Access denied by service policy", "Åtkomst nekad enligt lokal policy"}.
{"You must fill in field \"nick\" in the form", "Du måste fylla i fältet \"nick\" i formuläret"}.
{"Specified nickname is already registered", "Detta smeknamnet är redan registrerat"}.

% mod_muc/mod_muc_room.erl
{"Traffic rate limit is exceeded", "Trafikgränsen har överstigits"}.
{"This participant is kicked from the room because he sent an error message", "Deltagaren har blivit kickad fran rummet p.g.a att han skickade ett errormeddelande"}.
{"This participant is kicked from the room because he sent an error message to another participant", "Deltagaren har blivit kickad från rummet p.g.a att han skickade ett errormeddelande till en annan deltagare"}.
{"It is not allowed to send private messages", "Det ar inte tillåtet att skicka privata meddelanden"}.
{"This participant is kicked from the room because he sent an error presence", "Denna deltagaren är kickad från rummet p.g.a att han skickade en errorstatus"}.
{"Visitors are not allowed to change their nicknames in this room", "Det är inte tillåtet for gäster att ändra sina smeknamn i detta rummet"}.
{"This room is not anonymous", "Detta rum är inte anonymt"}.
{"Make room persistent", "Gör rummet permanent"}.
{"Make room public searchable", "Gör rummet publikt sökbart"}.
{"Make participants list public", "Gör deltagarlistan publik"}.
{"Make room password protected", "Gör losenorden i rummet publika"}.
{"Maximum Number of Occupants", "Maximalt antal av användare"}.
{"No limit", "Ingen gräns"}.
{"Present real JIDs to", "Nuvarande äkta JIDs till"}.
{"moderators only", "endast moderatorer"}.
{"anyone", "Vemsomhelst"}.
{"Make room members-only", "Gör om rummet till endast medlemmar"}.
{"Default users as participants", "Gör om användare till deltagare"}.
{"Allow users to change subject", "Tillåt användare att byta ämne"}.
{"Allow users to send private messages", "Tillåt användare att skicka privata meddelanden"}.
{"Allow users to query other users", "Tillåt användare att söka efter andra användare"}.
{"Allow users to send invites", "Tillåt användare att skicka inbjudningar"}.
{"Allow visitors to send status text in presence updates", "Tillåt gäster att skicka statustext som uppdatering"}.
{"Allow visitors to change nickname", "Tillåt gäster att kunna ändra smeknamn"}.
{"Enable logging", "Möjliggör login"}.
{"Number of occupants", "Antal besökare"}.
{"~s invites you to the room ~s", "~s bjöd in dig till rummet ~s"}.
{"the password is", "Lösenordet är"}.
{"Make room moderated", "Gör rummet modererat"}.
{" has set the subject to: ", " har satt ämnet till: "}.
{"You need an x:data capable client to configure room", "Du behöver en klient som stödjer x:data för att konfiguera detta rum"}.
{"Configuration for ", "Konfiguration för "}.
{"Room title", "Rumstitel"}.
{"Password", "Lösenord"}.
{"Only moderators and participants are allowed to change subject in this room", "Endast moderatorer och deltagare har tillåtelse att ändra ämnet i det här rummet"}.
{"Only moderators are allowed to change subject in this room", "Endast moderatorer får ändra ämnet i det här rummet"}.
{"Visitors are not allowed to send messages to all occupants", "Besökare får inte skicka medelande till alla"}.
{"Only occupants are allowed to send messages to the conference", "Utomstående får inte skicka medelanden till den här konferensen"}.
{"It is not allowed to send private messages to the conference", "Det är inte tillåtet att skicka privata medelanden till den här konferensen"}.
{"Improper message type", "Felaktig medelandetyp"}.
{"Nickname is already in use by another occupant", "Smeknamnet används redan"}.
{"Nickname is registered by another person", "Smeknamnet är reserverat"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Det är inte tillåtet att skicka privata medelanden med typen \"groupchat\""}.
{"Recipient is not in the conference room", "Mottagaren finns inte i rummet"}.
{"Only occupants are allowed to send queries to the conference", "Utomstående får inte skicka iq-queries till den här konferensen"}.
{"Queries to the conference members are not allowed in this room", "Det är förbjudet att skicka iq-queries till konferensdeltagare"}.
{"You have been banned from this room", "Du har blivit bannlyst från det här rummet"}.
{"Membership required to enter this room", "Du måste vara medlem för att komma in i det här rummet"}.
{"Password required to enter this room", "Lösenord erfordras"}.
{"Incorrect password", "Fel lösenord"}.
{"Administrator privileges required", "Administrationsprivilegier krävs"}.
{"Moderator privileges required", "Moderatorprivilegier krävs"}.
{"JID ~s is invalid", "Otillåtet JID ~s"}.
{"Nickname ~s does not exist in the room", "Smeknamnet ~s existerar inte i det här rummet"}.
{"Invalid affiliation: ~s", "Ogiltlig rang: ~s"}.
{"Invalid role: ~s", "Ogiltlig roll: ~s"}.
{"Owner privileges required", "Ägarprivilegier krävs"}.
{"private, ", "privat, "}.

% mod_irc/mod_irc.erl
{"IRC Transport", "IRC transport"}.
{"ejabberd IRC module", "ejabberd IRC-modul"}.
{"You need an x:data capable client to configure mod_irc settings", "Du behöer en klient som stöjer x:data för att konfigurera mod_irc"}.
{"Registration in mod_irc for ", "mod_irc-registrering för "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Skriv in användarnamn och textkodning du vill använda för att ansluta till IRC-servrar"}.
{"IRC Username", "IRC-användarnamn"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Om du vill specifiera textkodning för IRC-servrar, fyll i listan med värden i formatet '{\"irc server\", \"encoding\"}'. Som standard används \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Exempel: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Textkodningar"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "ejabberd Web Admin"}.
{"Administration", "Administration"}.
{"(Raw)", "(Ra)"}.
{"Raw", "Ra"}.
{"Users Last Activity", "Användarens senaste aktivitet"}.
{"Registered Users", "Registrerade användare"}.
{"Offline Messages", "Offline meddelanden"}.
{"Registered Users:", "Registrerade användare"}.
{"Online Users:", "Inloggade användare"}.
{"Outgoing s2s Connections:", "Utgående s2s anslutning"}.
{"Outgoing s2s Servers:", "Utgående s2s server"}.
{"No Data", "Ingen data"}.
{"Listened Ports", "Lyssnarport"}.
{"RPC Call Error", "RPC Uppringningserror"}.
{"Database Tables at ", "Databas tabell pa"}.
{"Backup of ", "Backup av"}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Kom ihåg att dessa inställningar endast tar backup pa builtin Mnesias databas. Om du använder ODBC modul så måste du ta backup på SQLs databas enskilt"}.
{"Store binary backup:", "Lagra den binära backupen"}.
{"Restore binary backup immediately:", "återställ den binära backupen omedelbart"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "återställ den binära backupen efter nästa ejabberd omstart"}.
{"Store plain text backup:", "Lagra textbackup"}.
{"Restore plain text backup immediately:", "återställ textbackup omedelbart"}.
{"Statistics of ~p", "Statistik på ~p"}.
{"Uptime:", "Tid upp"}.
{"CPU Time:", "CPU tid"}.
{"Transactions Commited:", "Transaktioner kommittade"}.
{"Transactions Aborted:", "Transaktioner borttagna"}.
{"Transactions Restarted:", "Transaktioner omstartade"}.
{"Transactions Logged:", "Transaktioner loggade "}.
{"Update ", "Uppdatera"}.
{"Update plan", "Uppdateringsplan"}.
{"Updated modules", "Uppdaterade moduler"}.
{"Update script", "Uppdatera skript"}.
{"Low level update script", "Uppdaterade laglevel skript"}.
{"Script check", "Skript kollat"}.
{"Users", "Användare"}.
{"Nodes", "Noder"}.
{"Statistics", "Statistik"}.
{"Delete Selected", "Tabort valda"}.
{"Submit", "Skicka"}.
{"~s access rule configuration", "Åtkomstregelkonfiguration för ~s"}.
{"Node not found", "Noden finns inte"}.
{"Add New", "Lägg till ny"}.
{"Change Password", "Ändra lösenord"}.
{"Connected Resources:", "Anslutna resurser:"}.
{"Password:", "Lösenord:"}.
{"None", "Inga"}.
{"Node ", "Nod "}.
{"Restart", "Omstart"}.
{"Stop", "Stoppa"}.
{"Name", "Namn"}.
{"Storage Type", "Lagringstyp"}.
{"Size", "Storlek"}.
{"Memory", "Minne"}.
{"OK", "OK"}.
{"Listened Ports at ", "Lyssnande portar på "}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Parametrar"}.
{"Update", "Uppdatera"}.
{"Delete", "Ta bort"}.
{"Add User", "Lägg till användare"}.
{"Last Activity", "Senast aktivitet"}.
{"Never", "Aldrig"}.
{"Time", "Tid"}.
{"From", "Från"}.
{"To", "Till"}.
{"Packet", "Paket"}.
{"Roster", "Kontaktlista"}.
{"Nickname", "Smeknamn"}.
{"Subscription", "Prenumeration"}.
{"Pending", "Ännu inte godkända"}.
{"Groups", "Grupper"}.
{"Remove", "Ta bort"}.
{"User ", "Användare "}.
{"Roster of ", "Kontaktlista för "}.
{"Online", "Ansluten"}.
{"Validate", "Validera"}.
{"Name:", "Namn:"}.
{"Description:", "Beskrivning:"}.
{"Members:", "Medlemmar:"}.
{"Displayed Groups:", "Visade grupper:"}.
{"Group ", "Grupp "}.
{"Virtual Hosts", "Virtuella servrar"}.
{"ejabberd virtual hosts", "Virtuella ejabberd-servrar"}.
{"Period: ", "Period: "}.
{"Last month", "Senaste månaden"}.
{"Last year", "Senaste året"}.
{"All activity", "All aktivitet"}.
{"Show Ordinary Table", "Visa normal tabell"}.
{"Show Integral Table", "Visa kumulativ tabell"}.
{"Host", "Server"}.
{"Modules at ", "Moduler på"}.
{"Start", "Starta"}.

% mod_roster_odbc.erl
{"Jabber ID", "Jabber ID"}.
{"Submitted", "Skicka in"}.
{"Bad format", "Dåligt format"}.
{"Add Jabber ID", "Lägg till Jabber ID"}.

% mod_announce.erl
{"Really delete message of the day?", "Verkligen ta bort dagens meddelanden?"}.
{"Subject", "Ämne"}.
{"Message body", "Meddelande kropp"}.
{"No body provided for announce message", "Ingen kropp behövs för dessa meddelanden"}.
{"Announcements", "Meddelanden"}.
{"Send announcement to all users", "Sänd meddelanden till alla användare"}.
{"Send announcement to all users on all hosts", "Sänd meddelanden till alla  användare på alla värdar"}.
{"Send announcement to all online users", "Sänd meddelanden till alla inloggade användare"}.
{"Send announcement to all online users on all hosts", "Sänd meddelanden till alla inloggade användare på alla värdar"}.
{"Set message of the day and send to online users", "Sätt dagens status meddelande och skicka till alla användare"}.
{"Set message of the day on all hosts and send to online users", "Sätt dagens status meddelande pa alla värdar och skicka till alla användare"}.
{"Update message of the day (don't send)", "Uppdatera dagens status meddelande (skicka inte)"}.
{"Update message of the day on all hosts (don't send)", "Uppdatera dagens status meddelande på alla värdar (skicka inte)"}.
{"Delete message of the day", "Ta bort dagens meddelande"}.
{"Delete message of the day on all hosts", "Ta bort dagens meddelande på alla värdar"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestrem modul"}.

% mod_offline.erl
{"Your contact offline message queue is full. The message has been discarded.", "Din kontaktkö for offlinekontakter ar full"}.
{"~s's Offline Messages Queue", "~s's offline meddelandekö"}.
{"Offline Messages:", "Offline meddelanden:"}.

% mod_adhoc.erl
{"Commands", "Kommandon"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_shared_roster.erl
{"Shared Roster Groups", "Delade Rostergrupper"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Chattrum konfiguration modifierad"}.
{"joins the room", "joinar rummet"}.
{"leaves the room", "lämnar rummet"}.
{"has been banned", "har blivit bannad"}.
{"has been kicked", "har blivit kickad"}.
{"has been kicked because of an affiliation change", "har blivit kickad p.g.a en ändring av tillhörighet"}.
{"has been kicked because the room has been changed to members-only", "har blivit kickad p.g.a att rummet har ändrats till endast användare"}.
{"has been kicked because of a system shutdown", "har blivit kickad p.g.a en systemnerstängning"}.
{"is now known as", "är känd som"}.
{"Monday", "Måndag"}.
{"Tuesday", "Tisdag"}.
{"Wednesday", "Onsdag"}.
{"Thursday", "Torsdag"}.
{"Friday", "Fredag"}.
{"Saturday", "Lördag"}.
{"Sunday", "Söndag"}.
{"January", "Januari"}.
{"February", "Februari"}.
{"March", "Mars"}.
{"April", "April"}.
{"May", "Maj"}.
{"June", "Juni"}.
{"July", "Juli"}.
{"August", "Augusti"}.
{"September", "September"}.
{"October", "Oktober"}.
{"November", "November"}.
{"December", "December"}.
{"Room Configuration", "Rumkonfiguration"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
