% $Id$
% Language: Swedish (svenska)
% Author: Magnus Henoch
% Author: Jonas Ådahl

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Du måste använda STARTTLS"}.
{"Replaced by new connection", "Ersatt av ny anslutning"}.

% jlib.hrl
{"No resource provided", "Ingen resurs angiven"}.

% mod_configure.erl
{"DB Tables Configuration at ", "Konfigurera DB-tabeller på "}.
{"Choose storage type of tables", "Välj lagringstyp för tabeller"}.
{"RAM copy", "RAM-kopia"}.
{"RAM and disc copy", "RAM- och diskkopia"}.
{"Disc only copy", "Endast diskkopia"}.
{"Remote copy", "Sparas inte lokalt"}.
{"Stop Modules at ", "Stoppa moduler på "}.
{"Choose modules to stop", "Välj vilka moduler som skall stoppas"}.
{"Start Modules at ", "Starta moduler på "}.
{"Enter list of {Module, [Options]}", "Skriv in en lista av {Module, [Options]}"}.
{"List of modules to start", "Lista av moduler som skall startas"}.
{"Backup to File at ", "Säkerhetskopiera till fil på "}.
{"Enter path to backup file", "Skriv in sökväg till fil för säkerhetskopia"}.
{"Path to File", "Sökväg till fil"}.
{"Restore Backup from File at ", "Återställ säkerhetskopia från fil på "}.
{"Dump Backup to Text File at ", "Dumpa säkerhetskopia till textfil på "}.
{"Enter path to text file", "Skriv in sökväg till textfil"}.
{"Import User from File at ", "Importera användare från fil på "}.
{"Enter path to jabberd1.4 spool file", "Skriv in sökväg till spoolfil från jabberd1.4"}.
{"Import Users from Dir at ", "Importera användare från katalog på "}.
{"Enter path to jabberd1.4 spool dir", "Skriv in sökväg till spoolkatalog från jabberd1.4"}.
{"Path to Dir", "Sökväg till katalog"}.
{"Hostname Configuration", "Värdnamnkonfiguration"}.
{"Choose host name", "Välj värdnamn"}.
{"Host name", "Värdnamn"}.
{"Access Control List Configuration", "Konfiguera ACL"}.
{"Access control lists", "ACL"}.
{"Access Configuration", "Åtkomstkonfiguration"}.
{"Access rules", "Åtkomstregler"}.
{"Remove Users", "Ta bort användare"}.
{"Choose users to remove", "Välj användare att ta bort"}.
{"Administration of ", "Administration av "}.
{"Action on user", "Handling mot användare"}.
{"Edit Properties", "Redigera egenskaper"}.
{"Remove User", "Ta bort användare"}.

% mod_disco.erl
{"Configuration", "Konfiguration"}.
{"Online Users", "Anslutna användare"}.
{"All Users", "Alla användare"}.
{"Outgoing S2S connections", "Utgående S2S-anslutningar"}.
{"To ~s", "Till ~s"}.
{"From ~s", "Från ~s"}.
{"Running Nodes", "Körande noder"}.
{"Stopped Nodes", "Stannade noder"}.
{"Host Name", "Värdnamn"}.
{"Access Control Lists", "ACL"}.
{"Access Rules", "Åtkomstregler"}.
{"Remove Users", "Ta bort användare"}.
{"DB", "DB"}.
{"Modules", "Moduler"}.
{"Start Modules", "Starta moduler"}.
{"Stop Modules", "Stanna moduler"}.
{"Backup Management", "Hantera säkerhetskopior"}.
{"Import users from jabberd1.4 spool files", "Importera användare från spoolfiler från jabberd1.4"}.
{"Backup", "Säkerhetskopiera"}.
{"Restore", "Återställ"}.
{"Dump to Text File", "Dumpa till textfil"}.
{"Import File", "Importera fil"}.
{"Import Directory", "Importera katalog"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Välj ett användarnamn och lösenord för att registrera mot denna server"}.

% mod_vcard.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"ejabberd vCard module", "ejabberd vCard-modul"}.
{"You need an x:data capable client to search", "Du behöver en klient som stödjer x:data, för att kunna söka"}.
{"Search users in ", "Sök efter användare på "}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Fyll i formuläret för att söka efter en användare (lägg till * på slutet av fältet för att hitta alla som börjar så)"}.
{"Results of search in ", "Sökresultat på "}.
{"User",              "Användarnamn"}.
{"Full Name", 	      "Fullständigt namn"}.
{"Name", 	      "Förnamn"}.
{"Middle Name",       "Mellannamn"}.
{"Family Name",       "Efternamn"}.
{"Nickname", 	      "Smeknamn"}.
{"Birthday", 	      "Födelsedag"}.
{"Country", 	      "Land"}.
{"City", 	      "Stad"}.
{"email", 	      "email"}.
{"Organization Name", "Organisationsnamn"}.
{"Organization Unit", "Organisationsenhet"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Fyll i fält för att söka efter jabberanvändare"}.
{"Given Name", "Förnamn"}.

% mod_vcard_odbc.erl
{"JID", "JID"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module", "ejabberd pub/sub-modul"}.
{"Node Creator", "Nodskapare"}.
{"Deliver payloads with event notifications", "Skicka innehåll tillsammans med notifikationer"}.
{"Notify subscribers when the node configuration changes", "Meddela prenumeranter när nodens konfiguration ändras"}.
{"Notify subscribers when the node is deleted", "Meddela prenumeranter när noden tas bort"}.
{"Notify subscribers when items are removed from the node", "Meddela prenumeranter när dataposter tas bort från noden"}.
{"Persist items to storage", "Spara dataposter permanent"}.
{"Max # of items to persist", "Högsta antal dataposter som sparas"}.
{"Whether to allow subscriptions", "Tillåta prenumerationer?"}.
{"Specify the subscriber model", "Ange prenumerationsmodell"}.
{"Specify the publisher model", "Ange publiceringsmodell"}.
{"Max payload size in bytes", "Högsta innehållsstorlek i bytes"}.
{"Send items to new subscribers", "Skicka dataposter till nya prenumeranter"}.
{"Only deliver notifications to available users", "Skicka notifikationer bara till uppkopplade användare"}.
{"Specify the current subscription approver", "Ange prenumerationsgodkännare"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "Du behöver en klient som stödjer x:data för att registrera smeknamn"}.
{"Nickname Registration at ", "Registrera smeknamn på "}.
{"Enter nickname you want to register", "Skriv in smeknamnet du vill registrera"}.
{"ejabberd MUC module", "ejabberd MUC modul"}.
{"Only service administrators are allowed to send service messages", "Endast administratörer får skicka tjänstmeddelanden"}.
{"Room creation is denied by service policy", "Skapandet av rum är förbjudet enligt lokal policy"}.
{"Conference room does not exist", "Rummet finns inte"}.
{"Access denied by service policy", "Åtkomst nekad enligt lokal policy"}.
{"You must fill in field \"nick\" in the form", "Du måste fylla i fältet \"nick\" i formuläret"}.
{"Specified nickname is already registered", "Detta smeknamnet är redan registrerat"}.

% mod_muc/mod_muc_room.erl
{"Make room moderated", "Gör rummet modererat"}.
{" has set the subject to: ", " har satt ämnet till: "}.
{"You need an x:data capable client to configure room", "Du behöver en klient som stödjer x:data för att konfiguera detta rum"}.
{"Configuration for ", "Konfiguration för "}.
{"Room title", "Rumstitel"}.
{"Allow users to change subject?", "Tillåt användare att ändra ämnet?"}.
{"Allow users to query other users?", "Tillåt användare att skicka iq-queries"}.
{"Allow users to send private messages?", "Tillåt användare att skicka privata meddelanden"}.
{"Make room public searchable?", "Gör rummet synligt för alla?"}.
{"Make participants list public?", "Gör användarlistan publik?"}.
{"Make room persistent?", "Gör rummet permanent?"}.
{"Make room moderated?", "Gör rummet modererat?"}.
{"Default users as members?", "Gör användare deltagare som standard?"}.
{"Make room members only?", "Stäng ute icke medlemmar?"}.
{"Allow users to send invites?", "Tillåt användare att skicka inbjudningar?"}.
{"Make room password protected?", "Lösenordsskydda rummet?"}.
{"Password", "Lösenord"}.
{"Make room anonymous?", "Anonymt rum?"}.
{"Enable logging?", "Aktivera loggning?"}.
{"Only moderators and participants are allowed to change subject in this room", "Endast moderatorer och deltagare har tillåtelse att ändra ämnet i det här rummet"}.
{"Only moderators are allowed to change subject in this room", "Endast moderatorer får ändra ämnet i det här rummet"}.
{"Visitors are not allowed to send messages to all occupants", "Besökare får inte skicka medelande till alla"}.
{"Only occupants are allowed to send messages to the conference", "Utomstående får inte skicka medelanden till den här konferensen"}.
{"It is not allowed to send normal messages to the conference", "Det är inte tillåtet att skicka normala medelanden till den här konferensen"}.
{"It is not allowed to send private messages to the conference", "Det är inte tillåtet att skicka privata medelanden till den här konferensen"}.
{"Improper message type", "Felaktig medelandetyp"}.
{"Nickname is already in use by another occupant", "Smeknamnet används redan"}.
{"Nickname is registered by another person", "Smeknamnet är reserverat"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Det är inte tillåtet att skicka privata medelanden med typen  \"groupchat\""}.
{"Recipient is not in the conference room", "Mottagaren finns inte i rummet"}.
{"Only occupants are allowed to send queries to the conference", "Utomstående får inte skicka iq-queries till den här konferensen"}.
{"Queries to the conference members are not allowed in this room", "Det är förbjudet att skicka iq-queries till konferensdeltagare"}.
{"You have been banned from this room", "Du har blivit bannlyst från det här rummet"}.
{"Membership required to enter this room", "Du måste vara medlem för att komma in i det här rummet"}.
{"Password required to enter this room", "Lösenord erfordras"}.
{"Incorrect password", "Fel lösenord"}.
{"Administrator privileges required", "Administrationsprivilegier krävs"}.
{"Moderator privileges required", "Moderatorprivilegier krävs"}.
{"JID ~s is invalid", "Otillåtet JID ~s"}.
{"Nickname ~s does not exist in the room", "Smeknamnet ~s existerar inte i det här rummet"}.
{"Invalid affiliation: ~s", "Ogiltlig rang: ~s"}.
{"Invalid role: ~s", "Ogiltlig roll: ~s"}.
{"Owner privileges required", "Ägarprivilegier krävs"}.
{"private, ", "privat, "}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "ejabberd IRC-modul"}.
{"You need an x:data capable client to configure mod_irc settings", "Du behöer en klient som stöjer x:data för att konfigurera mod_irc"}.
{"Registration in mod_irc for ", "mod_irc-registrering för "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Skriv in användarnamn och textkodning du vill använda för att ansluta till IRC-servrar"}.
{"IRC Username", "IRC-användarnamn"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Om du vill specifiera textkodning för IRC-servrar, fyll i listan med värden i formatet '{\"irc server\", \"encoding\"}'. Som standard används \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Exempel: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Textkodningar"}.

% web/ejabberd_web_admin.erl
{"ejabberd administration", "ejabberd-administration"}.
{"Users", "Användare"}.
{"Nodes", "Noder"}.
{"Statistics", "Statistik"}.
{"(raw)", "(obehandlat format)"}.
{"submitted", "inskickat"}.
{"bad format", "otillåtet format"}.
{"raw", "obehandlat format"}.
{"ejabberd access control lists configuration", "ejabberd ACL-konfiguration"}.
{"Delete Selected", "Tabort valda"}.
{"Submit", "Skicka"}.
{"ejabberd access rules configuration", "ejabberd åtkomstregler-konfiguration"}.
{"~s access rule configuration", "Åtkomstregelkonfiguration för ~s"}.
{"ejabberd users", "ejabberd-användare"}.
{"ejabberd stats", "ejabberd-statistik"}.
{"Node not found", "Noden finns inte"}.
{"Add New", "Lägg till ny"}.
{"Registered users", "Registrerade användare"}.
{"Authenticated users", "Inloggade användare"}.
{"Online users", "Anslutna användare"}.
{"Outgoing S2S servers", "Utgående S2S-servrar"}.
{"Change Password", "Ändra lösenord"}.
{"Connected Resources:", "Anslutna resurser:"}.
{"Password:", "Lösenord:"}.
{"None", "Inga"}.
{"Node ", "Nod "}.
{"DB Management", "DB-hantering"}.
{"Listened Ports Management", "Hantering av lyssnande portar"}.
{"Restart", "Omstart"}.
{"Stop", "Stoppa"}.
{"RPC call error", "RPC-fel"}.
{"DB Tables at ", "DB-tabeller på "}.
{"Name", "Namn"}.
{"Storage Type", "Lagringstyp"}.
{"Size", "Storlek"}.
{"Memory", "Minne"}.
{"Backup Management at ", "Hantering av säkerhetskopiering på "}.
{"Store a backup in a file", "Lagra en säkerhetskopiering i en fil"}.
{"OK", "OK"}.
{"Restore a backup from a file", "Återställ en säkerhetskopia från en fil"}.
{"Install a database fallback from a file", "Installera en databasfallback från en fil"}.
{"Dump a database in a text file", "Dumpa en databas i en textfil"}.
{"Restore a database from a text file", "Återställ en databas från en textfil"}.
{"Listened Ports at ", "Lyssnande portar på "}.
{"~p statistics", "~p-statistik"}.
{"Uptime", "Driftstid"}.
{"CPU Time", "CPU-tid"}.
{"Transactions commited", "Skickade transaktioner"}.
{"Transactions aborted", "Avbrutna transaktioner"}.
{"Transactions restarted", "Omstartade transaktioner"}.
{"Transactions logged", "Loggade transaktioner"}.
{"Port", "Port"}.
{"Module", "Modul"}.
{"Options", "Parametrar"}.
{"Update", "Uppdatera"}.
{"Delete", "Ta bort"}.
{"Add User", "Lägg till användare"}.
{"ejabberd (c) 2002-2005 Alexey Shchepin, 2004-2005 Process One", "ejabberd (c) 2002-2005 Alexej Sjtjepin, 2004-2005 Process One"}.
{"Offline messages", "Offline-medelanden"}.
{"Last Activity", "Senast aktivitet"}.
{"Never", "Aldrig"}.
{"~s offline messages queue", "~s offlinemedelande i kö"}.
{"Time", "Tid"}.
{"From", "Från"}.
{"To", "Till"}.
{"Packet", "Paket"}.
{"Offline messages:", "Offlinemedelande:"}.
{"Roster", "Kontaktlista"}.
{"Nickname", "Smeknamn"}.
{"Subscription", "Prenumeration"}.
{"Pending", "Ännu inte godkända"}.
{"Groups", "Grupper"}.
{"Remove", "Ta bort"}.
{"Add JID", "Lägg till JID"}.
{"User ", "Användare "}.
{"Roster of ", "Kontaktlista för "}.
{"Shared Roster", "Gemensam kontaktlista"}.
{"Online", "Ansluten"}.
{"Validate", "Validera"}.
{"Not found", "Finns inte"}.
{"Shared roster groups", "Gemensamma kontaktlistagrupper"}.
{"Name:", "Namn:"}.
{"Description:", "Beskrivning:"}.
{"Members:", "Medlemmar:"}.
{"Displayed Groups:", "Visade grupper:"}.
{"Group ", "Grupp "}.
{"Virtual Hosts", "Virtuella servrar"}.
{"ejabberd virtual hosts", "Virtuella ejabberd-servrar"}.
{"Users last activity", "Senaste aktivitet från användare"}.
{"Period: ", "Period: "}.
{"Last month", "Senaste månaden"}.
{"Last year", "Senaste året"}.
{"All activity", "All aktivitet"}.
{"Show Ordinary Table", "Visa normal tabell"}.
{"Show Integral Table", "Visa kumulativ tabell"}.
{"Host", "Server"}.
{"No data", "Inga data"}.
{"Modules Management", "Modulhantering"}.
{"Modules at ", "Moduler på"}.
{"Start", "Starta"}.
{"ejabberd Web Interface", "Webbgränssnitt till ejabberd"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
