% $Id$
% Language: Thai (ภาษาไทย)
% Author: EQHO Communications (Thailand) Ltd. - http://www.eqho.com

% mod_vcard_odbc.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"You need an x:data capable client to search", "คุณต้องใช้ไคลเอ็นต์ที่รองรับ x:data เพื่อค้นหา"}.
{"Search users in ", "ค้นหาผู้ใช้ใน "}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "กรอกข้อมูลในแบบฟอร์มเพื่อค้นหาผู้ใช้ Jabber ที่ตรงกัน (ใส่เครื่องหมาย * ที่ท้ายสุดของฟิลด์เพื่อจับคู่กับสตริงย่อย)"}.
{"User", "ผู้ใช้"}.
{"Full Name", "ชื่อเต็ม"}.
{"Name", "ชื่อ"}.
{"Middle Name", "ชื่อกลาง"}.
{"Family Name", "นามสกุล"}.
{"Nickname", "ชื่อเล่น"}.
{"Birthday", "วันเกิด"}.
{"Country", "ประเทศ"}.
{"City", "เมือง"}.
{"Email", "อีเมล"}.
{"Organization Name", "ชื่อองค์กร"}.
{"Organization Unit", "หน่วยขององค์กร"}.
{"vCard User Search", "ค้นหาผู้ใช้ vCard "}.
{"ejabberd vCard module", "ejabberd vCard module"}.
{"Search Results for ", "ผลการค้นหาสำหรับ "}.
{"Jabber ID", "Jabber ID"}.

% mod_roster.erl
{"None", "ไม่มี"}.
{"Subscription", "การสมัครสมาชิก"}.
{"Pending", "ค้างอยู่"}.
{"Groups", "กลุ่ม"}.
{"Validate", "ตรวจสอบ"}.
{"Remove", "ลบ"}.
{"Roster of ", "บัญชีรายชื่อของ "}.
{"Submitted", "ส่งแล้ว"}.
{"Bad format", "รูปแบบที่ไม่ถูกต้อง"}.
{"Add Jabber ID", "เพิ่ม Jabber ID"}.
{"Roster", "บัญชีรายชื่อ"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "ลำดับข้อความออฟไลน์ของผู้ที่ติดต่อของคุณเต็มแล้ว ข้อความถูกลบทิ้งแล้ว"}.
{"~s's Offline Messages Queue", "~s's ลำดับข้อความออฟไลน์"}.
{"Packet", "แพ็กเก็ต"}.
{"Delete Selected", "ลบข้อความที่เลือก"}.
{"Offline Messages:", "ข้อความออฟไลน์:"}.

% ejabberd_c2s.erl
{"Use of STARTTLS required", "ต้องใช้ STARTTLS"}.
{"No resource provided", "ไม่ได้ระบุข้อมูล"}.
{"Replaced by new connection", "แทนที่ด้วยการเชื่อมต่อใหม่"}.

% mod_register.erl
{"Choose a username and password to register with this server", "เลือกชื่อผู้ใช้และรหัสผ่านเพื่อลงทะเบียนกับเซิร์ฟเวอร์นี้"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "กรอกข้อมูลลงในฟิลด์เพื่อค้นหาผู้ใช้ Jabber ที่ตรงกัน"}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams module"}.

% mod_shared_roster.erl
{"Add New", "เพิ่มผู้ใช้ใหม่"}.
{"Shared Roster Groups", "กลุ่มบัญชีรายชื่อที่ใช้งานร่วมกัน"}.
{"Name:", "ชื่อ:"}.
{"Description:", "รายละเอียด:"}.
{"Members:", "สมาชิก:"}.
{"Displayed Groups:", "กลุ่มที่แสดง:"}.
{"Group ", "กลุ่ม"}.
{"Submit", "ส่ง"}.

% mod_announce.erl
{"Really delete message of the day?", "แน่ใจว่าต้องการลบข้อความของวันหรือไม่"}.
{"Subject", "หัวเรื่อง"}.
{"Message body", "เนื้อหาของข้อความ"}.
{"No body provided for announce message", "ไม่ได้ป้อนเนื้อหาสำหรับข้อความที่ประกาศ"}.
{"Announcements", "ประกาศ"}.
{"Send announcement to all users", "ส่งประกาศถึงผู้ใช้ทั้งหมด"}.
{"Send announcement to all users on all hosts", "ส่งประกาศถึงผู้ใช้ทั้งหมดบนโฮสต์ทั้งหมด"}.
{"Send announcement to all online users", "ส่งประกาศถึงผู้ใช้ออนไลน์ทั้งหมด"}.
{"Send announcement to all online users on all hosts", "ส่งประกาศถึงผู้ใช้ออนไลน์ทั้งหมดบนโฮสต์ทั้งหมด"}.
{"Set message of the day and send to online users", "ตั้งค่าข้อความของวันและส่งถึงผู้ใช้ออนไลน์"}.
{"Set message of the day on all hosts and send to online users", "ตั้งค่าข้อความของวันบนโฮสต์ทั้งหมดและส่งถึงผู้ใช้ออนไลน์"}.
{"Update message of the day (don't send)", "อัพเดตข้อความของวัน (ไม่ต้องส่ง)"}.
{"Update message of the day on all hosts (don't send)", "อัพเดตข้อความของวันบนโฮสต์ทั้งหมด (ไม่ต้องส่ง) "}.
{"Delete message of the day", "ลบข้อความของวัน"}.
{"Delete message of the day on all hosts", "ลบข้อความของวันบนโฮสต์ทั้งหมด"}.

% mod_adhoc.erl
{"Commands", "คำสั่ง"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_irc/mod_irc.erl
{"Access denied by service policy", "การเข้าถึงถูกปฏิเสธโดยนโยบายการบริการ"}.
{"IRC Transport", "การส่ง IRC"}.
{"ejabberd IRC module", "ejabberd IRC module"}.
{"You need an x:data capable client to configure mod_irc settings", "คุณต้องใช้ไคลเอ็นต์ที่รองรับ x:data เพื่อกำหนดการตั้งค่า mod_irc"}.
{"Registration in mod_irc for ", "การลงทะเบียนใน mod_irc สำหรับ"}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "ป้อนชื่อผู้ใช้และการเข้ารหัสที่คุณต้องการใช้สำหรับเชื่อมต่อกับเซิร์ฟเวอร์ IRC"}.
{"IRC Username", "ชื่อผู้ใช้ IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "ถ้าคุณต้องการระบุการเข้ารหัสที่ต่างกันสำหรับเซิร์ฟเวอร์ IRC ให้กรอกค่าโดยใช้รูปแบบ '{\"irc server\", \"encoding\"}' ลงในรายการ  การบริการนี้ใช้การเข้ารหัสในรูปแบบ \"~s\" โดยค่าดีฟอลต์ "}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "ตัวอย่าง: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "การเข้ารหัส"}.

% mod_configure.erl
{"Configuration", "การกำหนดค่า"}.
{"Database", "ฐานข้อมูล"}.
{"Start Modules", "เริ่มโมดูล"}.
{"Stop Modules", "หยุดโมดูล"}.
{"Backup", "การสำรองข้อมูล "}.
{"Restore", "การคืนค่า"}.
{"Dump to Text File", "ถ่ายโอนข้อมูลไปยังไฟล์ข้อความ"}.
{"Import File", "อิมพอร์ตไฟล์"}.
{"Import Directory", "อิมพอร์ตไดเร็กทอรี"}.
{"Restart Service", "เริ่มต้นการบริการใหม่อีกครั้ง"}.
{"Shut Down Service", "ปิดการบริการ"}.
{"Add User", "เพิ่มผู้ใช้"}.
{"Delete User", "ลบผู้ใช้"}.
{"End User Session", "สิ้นสุดเซสชันของผู้ใช้"}.
{"Get User Password", "ขอรับรหัสผ่านของผู้ใช้"}.
{"Change User Password", "เปลี่ยนรหัสผ่านของผู้ใช้"}.
{"Get User Last Login Time", "แสดงเวลาเข้าสู่ระบบครั้งล่าสุดของผู้ใช้"}.
{"Get User Statistics", "แสดงสถิติของผู้ใช้"}.
{"Get Number of Registered Users", "แสดงจำนวนผู้ใช้ที่ลงทะเบียน"}.
{"Get Number of Online Users", "แสดงจำนวนผู้ใช้ออนไลน์"}.
{"Access Control Lists", "รายการควบคุมการเข้าถึง"}.
{"Access Rules", "กฎการเข้าถึง"}.
{"User Management", "การจัดการผู้ใช้"}.
{"Online Users", "ผู้ใช้ออนไลน์"}.
{"All Users", "ผู้ใช้ทั้งหมด"}.
{"Outgoing s2s Connections", "การเชื่อมต่อ s2s ขาออก"}.
{"Running Nodes", "โหนดที่ทำงาน"}.
{"Stopped Nodes", "โหนดที่หยุด"}.
{"Modules", "โมดูล"}.
{"Backup Management", "การจัดการข้อมูลสำรอง"}.
{"Import Users From jabberd 1.4 Spool Files", "อิมพอร์ตผู้ใช้จากไฟล์เก็บพักข้อมูล jabberd 1.4"}.
{"To ~s", "ถึง ~s"}.
{"From ~s", "จาก ~s"}.
{"Database Tables Configuration at ", "การกำหนดค่าตารางฐานข้อมูลที่"}.
{"Choose storage type of tables", "เลือกชนิดการจัดเก็บของตาราง"}.
{"RAM copy", "คัดลอก RAM"}.
{"RAM and disc copy", "คัดลอก RAM และดิสก์"}.
{"Disc only copy", "คัดลอกเฉพาะดิสก์"}.
{"Remote copy", "คัดลอกระยะไกล"}.
{"Stop Modules at ", "หยุดโมดูลที่"}.
{"Choose modules to stop", "เลือกโมดูลเพื่อหยุดการทำงาน"}.
{"Start Modules at ", "เริ่มโมดูลที่"}.
{"Enter list of {Module, [Options]}", "ป้อนรายการของ {โมดูล, [ตัวเลือก]}"}.
{"List of modules to start", "รายการของโมดูลที่จะเริ่มการทำงาน"}.
{"Backup to File at ", "สำรองไฟล์ข้อมูลที่"}.
{"Enter path to backup file", "ป้อนพาธเพื่อสำรองไฟล์ข้อมูล"}.
{"Path to File", "พาธของไฟล์ข้อมูล"}.
{"Restore Backup from File at ", "คืนค่าการสำรองข้อมูลจากไฟล์ที่"}.
{"Dump Backup to Text File at ", "ถ่ายโอนการสำรองข้อมูลไปยังไฟล์ข้อความที่"}.
{"Enter path to text file", "ป้อนพาธของไฟล์ข้อความ"}.
{"Import User from File at ", "อิมพอร์ตผู้ใช้จากไฟล์ที่"}.
{"Enter path to jabberd1.4 spool file", "ป้อนพาธไปยังไฟล์เก็บพักข้อมูล jabberd 1.4"}.
{"Import Users from Dir at ", "อิมพอร์ตผู้ใช้จาก Dir ที่"}.
{"Enter path to jabberd1.4 spool dir", "ป้อนพาธไปยัง jabberd 1.4 spool dir"}.
{"Path to Dir", "พาธไปยัง Dir"}.
{"Time delay", "การหน่วงเวลา"}.
{"Access Control List Configuration", "การกำหนดค่ารายการควบคุมการเข้าถึง"}.
{"Access control lists", "รายการควบคุมการเข้าถึง"}.
{"Access Configuration", "การกำหนดค่าการเข้าถึง"}.
{"Access rules", "กฎการเข้าถึง"}.
{"Password", "รหัสผ่าน"}.
{"Password Verification", "การตรวจสอบรหัสผ่าน"}.
{"Number of registered users", "จำนวนผู้ใช้ที่ลงทะเบียน"}.
{"Number of online users", "จำนวนผู้ใช้ออนไลน์"}.
{"Never", "ไม่เคย"}.
{"Online", "ออนไลน์"}.
{"Last login", "การเข้าสู่ระบบครั้งล่าสุด"}.
{"Roster size", "ขนาดของบัญชีรายชื่อ"}.
{"IP addresses", "ที่อยู่ IP"}.
{"Resources", "ทรัพยากร"}.
{"Administration of ", "การดูแล "}.
{"Action on user", "การดำเนินการกับผู้ใช้"}.
{"Edit Properties", "แก้ไขคุณสมบัติ"}.
{"Remove User", "ลบผู้ใช้"}.

% mod_pubsub/mod_pubsub.erl
{"Publish-Subscribe", "เผยแพร่-สมัครเข้าใช้งาน"}.
{"ejabberd Publish-Subscribe module", "ejabberd Publish-Subscribe module"}.
{"PubSub subscriber request", "คำร้องขอของผู้สมัครเข้าใช้งาน PubSub"}.
{"Choose whether to approve this entity's subscription.", "เลือกว่าจะอนุมัติการสมัครเข้าใช้งานของเอนทิตี้นี้หรือไม่"}.
{"Node ID", "ID โหนด"}.
{"Subscriber Address", "ที่อยู่ของผู้สมัคร"}.
{"Allow this JID to subscribe to this pubsub node?", "อนุญาตให้ JID นี้เข้าร่วมเป็นสมาชิกของโหนด pubsub หรือไม่"}.
{"Deliver payloads with event notifications", "ส่งส่วนของข้อมูล (payload) พร้อมกับการแจ้งเตือนเหตุการณ์"}.
{"Deliver event notifications", "ส่งการแจ้งเตือนเหตุการณ์"}.
{"Notify subscribers when the node configuration changes", "แจ้งเตือนผู้สมัครสมาชิกเมื่อการกำหนดค่าโหนดเปลี่ยนแปลง"}.
{"Notify subscribers when the node is deleted", "แจ้งเตือนผู้สมัครสมาชิกเมื่อโหนดถูกลบ"}.
{"Notify subscribers when items are removed from the node", "แจ้งเตือนผู้สมัครสมาชิกเมื่อรายการถูกลบออกจากโหนด"}.
{"Persist items to storage", "ยืนยันรายการที่จะจัดเก็บ"}.
{"Max # of items to persist", "จำนวนสูงสุดของรายการที่ยืนยัน"}.
{"Whether to allow subscriptions", "อนุญาตให้เข้าร่วมเป็นสมาชิกหรือไม่"}.
{"Specify the access model", "ระบุโมเดลการเข้าถึง"}.
{"Roster groups that may subscribe (if access model is roster)", "กลุ่มบัญชีรายชื่อที่อาจจะสมัครเป็นสมาชิก (ถ้าโมเดลการเข้าถึงคือบัญชีรายชื่อ)"}.
{"Specify the publisher model", "ระบุโมเดลผู้เผยแพร่"}.
{"Max payload size in bytes", "ขนาดสูงสุดของส่วนของข้อมูล (payload) มีหน่วยเป็นไบต์"}.
{"When to send the last published item", "เวลาที่ส่งรายการที่เผยแพร่ครั้งล่าสุด"}.
{"Only deliver notifications to available users", "ส่งการแจ้งเตือนถึงผู้ใช้ที่สามารถติดต่อได้เท่านั้น"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Interface", "เว็บอินเทอร์เฟซของ ejabberd"}.
{"Administration", "การดูแล"}.
{"Virtual Hosts", "โฮสต์เสมือน"}.
{"Nodes", "โหนด"}.
{"Statistics", "สถิติ"}.
{"Users", "ผู้ใช้"}.
{"Last Activity", "กิจกรรมล่าสุด"}.
{"(Raw)", "(ข้อมูลดิบ)"}.
{"Raw", "ข้อมูลดิบ"}.
{"~s access rule configuration", "~s การกำหนดค่ากฎการเข้าถึง"}.
{"ejabberd virtual hosts", "โฮสต์เสมือน ejabberd"}.
{"Users Last Activity", "กิจกรรมล่าสุดของผู้ใช้"}.
{"Period: ", "ระยะเวลา:"}.
{"Last month", "เดือนที่แล้ว"}.
{"Last year", "ปีที่แล้ว"}.
{"All activity", "กิจกรรมทั้งหมด"}.
{"Show Ordinary Table", "แสดงตารางทั่วไป"}.
{"Show Integral Table", "แสดงตารางรวม"}.
{"Node not found", "ไม่พบโหนด"}.
{"Host", "โฮสต์"}.
{"Registered Users", "ผู้ใช้ที่ลงทะเบียน"}.
{"Offline Messages", "ข้อความออฟไลน์"}.
{"Registered Users:", "ผู้ใช้ที่ลงทะเบียน:"}.
{"Online Users:", "ผู้ใช้ออนไลน์:"}.
{"Outgoing s2s Connections:", "การเชื่อมต่อ s2s ขาออก:"}.
{"Outgoing s2s Servers:", "เซิร์ฟเวอร์ s2s ขาออก:"}.
{"Change Password", "เปลี่ยนรหัสผ่าน"}.
{"User ", "ผู้ใช้"}.
{"Connected Resources:", "ทรัพยากรที่เชื่อมต่อ:"}.
{"Password:", "รหัสผ่าน:"}.
{"No Data", "ไม่มีข้อมูล"}.
{"Node ", "โหนด "}.
{"Listened Ports", "พอร์ทฟัง"}.
{"Update", "อัพเดต"}.
{"Restart", "เริ่มต้นใหม่"}.
{"Stop", "หยุด"}.
{"RPC Call Error", "ข้อผิดพลาดจากการเรียกใช้ RPC"}.
{"Database Tables at ", "ตารางฐานข้อมูลที่"}.
{"Storage Type", "ชนิดที่เก็บข้อมูล"}.
{"Size", "ขนาด"}.
{"Memory", "หน่วยความจำ"}.
{"Backup of ", "การสำรองข้อมูล"}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "โปรดทราบว่าตัวเลือกเหล่านี้จะสำรองข้อมูลในฐานข้อมูล builtin Mnesia เท่านั้น หากคุณใช้โมดูล ODBC คุณต้องสำรองข้อมูลของฐานข้อมูล SQL แยกต่างหากด้วย"}.
{"Store binary backup:", "จัดเก็บข้อมูลสำรองแบบไบนารี:"}.
{"OK", "ตกลง"}.
{"Restore binary backup immediately:", "คืนค่าข้อมูลสำรองแบบไบนารีโดยทันที:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "คืนค่าข้อมูลสำรองแบบไบนารีหลังจากที่ ejabberd ถัดไปเริ่มการทำงานใหม่ (ใช้หน่วยความจำน้อยลง):"}.
{"Store plain text backup:", "จัดเก็บข้อมูลสำรองที่เป็นข้อความธรรมดา:"}.
{"Restore plain text backup immediately:", "คืนค่าข้อมูลสำรองที่เป็นข้อความธรรมดาโดยทันที:"}.
{"Listened Ports at ", "พอร์ทฟังที่"}.
{"Modules at ", "โมดูลที่ "}.
{"Statistics of ~p", "สถิติของ ~p"}.
{"Uptime:", "เวลาการทำงานต่อเนื่อง:"}.
{"CPU Time:", "เวลาการทำงานของ CPU:"}.
{"Transactions Commited:", "ทรานแซกชันที่ได้รับมอบหมาย:"}.
{"Transactions Aborted:", "ทรานแซกชันที่ถูกยกเลิก:"}.
{"Transactions Restarted:", "ทรานแซกชันที่เริ่มทำงานใหม่อีกครั้ง:"}.
{"Transactions Logged:", "ทรานแซกชันที่บันทึก:"}.
{"Update ", "อัพเดต "}.
{"Update plan", "แผนการอัพเดต"}.
{"Updated modules", "โมดูลที่อัพเดต"}.
{"Update script", "อัพเดตสคริปต์"}.
{"Low level update script", "อัพเดตสคริปต์ระดับต่ำ"}.
{"Script check", "ตรวจสอบคริปต์"}.
{"Port", "พอร์ท"}.
{"Module", "โมดูล"}.
{"Options", "ตัวเลือก"}.
{"Delete", "ลบ"}.
{"Start", "เริ่ม"}.

% mod_muc/mod_muc.erl
{"Only service administrators are allowed to send service messages", "ผู้ดูแลด้านการบริการเท่านั้นที่ได้รับอนุญาตให้ส่งข้อความการบริการ"}.
{"Room creation is denied by service policy", "การสร้างห้องสนทนาถูกปฏิเสธโดยนโยบายการบริการ"}.
{"Conference room does not exist", "ไม่มีห้องประชุม"}.
{"Chatrooms", "ห้องสนทนา"}.
{"You need an x:data capable client to register nickname", "คุณต้องใช้ไคลเอ็นต์ที่รองรับ x:data เพื่อลงทะเบียนชื่อเล่น"}.
{"Nickname Registration at ", "การลงทะเบียนชื่อเล่นที่ "}.
{"Enter nickname you want to register", "ป้อนชื่อเล่นที่คุณต้องการลงทะเบียน"}.
{"Specified nickname is already registered", "ชื่อเล่นที่ระบุได้รับการลงได้ทะเบียนแล้ว"}.
{"You must fill in field \"Nickname\" in the form", "คุณต้องกรอกฟิลด์ \"Nickname\" ในแบบฟอร์ม"}.
{"ejabberd MUC module", "ejabberd MUC module"}.

% mod_muc/mod_muc_room.erl
{"Traffic rate limit is exceeded", "อัตราของปริมาณการเข้าใช้เกินขีดจำกัด"}.
{"It is not allowed to send private messages to the conference", "ไม่อนุญาตให้ส่งข้อความส่วนตัวไปยังห้องประชุม"}.
{"Improper message type", "ประเภทข้อความไม่เหมาะสม"}.
{"Only occupants are allowed to send messages to the conference", "ผู้ครอบครองห้องเท่านั้นที่ได้รับอนุญาตให้ส่งข้อความไปยังห้องประชุม"}.
{"It is not allowed to send private messages of type \"groupchat\"", "ไม่อนุญาตให้ส่งข้อความส่วนตัวไปยัง \"กลุ่มสนทนา\""}.
{"Recipient is not in the conference room", "ผู้รับไม่ได้อยู่ในห้องประชุม"}.
{"Only occupants are allowed to send queries to the conference", "ผู้ครอบครองห้องเท่านั้นที่ได้รับอนุญาตให้ส่งกระทู้ถามไปยังห้องประชุม"}.
{"Queries to the conference members are not allowed in this room", "ห้องนี้ไม่อนุญาตให้ส่งกระทู้ถามถึงสมาชิกในห้องประชุม"}.
{"private, ", "ส่วนตัว, "}.
{"Only moderators and participants are allowed to change subject in this room", "ผู้ดูแลการสนทนาและผู้เข้าร่วมเท่านั้นที่ได้รับอนุญาตให้เปลี่ยนหัวข้อในห้องนี้"}.
{"Only moderators are allowed to change subject in this room", "ผู้ดูแลการสนทนาเท่านั้นที่ได้รับอนุญาตให้เปลี่ยนหัวข้อในห้องนี้"}.
{"Visitors are not allowed to send messages to all occupants", "ผู้เยี่ยมเยือนไม่ได้รับอนุญาตให้ส่งข้อความถึงผู้ครอบครองห้องทั้งหมด"}.
{"Nickname is already in use by another occupant", "ชื่อเล่นถูกใช้งานอยู่โดยผู้ครอบครองห้อง"}.
{"Nickname is registered by another person", "ชื่อเล่นถูกลงทะเบียนใช้งานโดยบุคคลอื่น"}.
{"You have been banned from this room", "คุณถูกสั่งห้ามไมให้เข้าห้องนี้"}.
{"Membership required to enter this room", "ต้องเป็นสมาชิกจึงจะสามารถเข้าห้องนี้ได้"}.
{"This room is not anonymous", "ห้องนี้ไม่ปิดบังชื่อ"}.
{"Password required to enter this room", "ต้องใส่รหัสผ่านเพื่อเข้าห้องนี้"}.
{"Incorrect password", "รหัสผ่านไม่ถูกต้อง"}.
{" has set the subject to: ", " ตั้งหัวข้อว่า: "}.
{"Administrator privileges required", "ต้องมีสิทธิพิเศษของผู้ดูแลระบบ"}.
{"Moderator privileges required", "ต้องมีสิทธิพิเศษของผู้ดูแลการสนทนา"}.
{"JID ~s is invalid", "JID ~s ไม่ถูกต้อง"}.
{"Nickname ~s does not exist in the room", "ไม่มีชื่อเล่น ~s อยู่ในห้องนี้"}.
{"Invalid affiliation: ~s", "การเข้าร่วมที่ไม่ถูกต้อง: ~s"}.
{"Invalid role: ~s", "บทบาทไม่ถูกต้อง: ~s"}.
{"Owner privileges required", "ต้องมีสิทธิพิเศษของเจ้าของ"}.
{"Configuration for ", "การกำหนดค่าสำหรับ "}.
{"Room title", "ชื่อห้อง"}.
{"Make room persistent", "สร้างเป็นห้องถาวร"}.
{"Make room public searchable", "สร้างเป็นห้องที่บุคคลทั่วไปสามารถค้นหาได้"}.
{"Make participants list public", "สร้างรายการผู้เข้าร่วมสำหรับใช้งานโดยบุคคลทั่วไป"}.
{"Make room password protected", "สร้างห้องที่มีการป้องกันด้วยรหัสผ่าน"}.
{"Maximum Number of Occupants", "จำนวนผู้ครอบครองห้องสูงสุด"}.
{"No limit", "ไม่จำกัด"}.
{"Present real JIDs to", "แสดง JIDs ที่ถูกต้องแก่"}.
{"moderators only", "สำหรับผู้ดูแลการสนทนาเท่านั้น"}.
{"anyone", "ทุกคน"}.
{"Make room members-only", "สร้างห้องสำหรับสมาชิกเท่านั้น"}.
{"Default users as participants", "ผู้ใช้เริ่มต้นเป็นผู้เข้าร่วม"}.
{"Allow users to change subject", "อนุญาตให้ผู้ใช้เปลี่ยนหัวข้อได้"}.
{"Allow users to send private messages", "อนุญาตให้ผู้ใช้ส่งข้อความส่วนตัว"}.
{"Allow users to query other users", "อนุญาตให้ผู้ใช้ถามคำถามกับผู้ใช้คนอื่นๆ ได้"}.
{"Allow users to send invites", "อนุญาตให้ผู้ใช้ส่งคำเชิญถึงกันได้"}.
{"Enable logging", "เปิดใช้งานการบันทึก"}.
{"You need an x:data capable client to configure room", "คุณต้องใช้ไคลเอ็นต์ที่รองรับ x:data เพื่อกำหนดค่าห้องสนทนา "}.
{"Number of occupants", "จำนวนผู้ครอบครองห้อง"}.
{"~s invites you to the room ~s", "~s เชิญคุณเข้าร่วมสนทนาในห้อง ~s"}.
{"the password is", "รหัสผ่านคือ"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "มีการปรับเปลี่ยนการกำหนดค่าของห้องสนทนา"}.
{"joins the room", "เข้าห้องสนทนานี้"}.
{"leaves the room", "ออกจากห้อง"}.
{"has been kicked", "ถูกไล่ออก"}.
{"has been banned", "ถูกสั่งห้าม"}.
{"is now known as", "ซึ่งรู้จักกันในชื่อ"}.
{"Monday", "วันจันทร์"}.
{"Tuesday", "วันอังคาร"}.
{"Wednesday", "วันพุธ"}.
{"Thursday", "วันพฤหัสบดี"}.
{"Friday", "วันศุกร์"}.
{"Saturday", "วันเสาร์"}.
{"Sunday", "วันอาทิตย์"}.
{"January", "มกราคม"}.
{"February", "กุมภาพันธ์"}.
{"March", "มีนาคม"}.
{"April", "เมษายน"}.
{"May", "พฤษภาคม"}.
{"June", "มิถุนายน"}.
{"July", "กรกฎาคม"}.
{"August", "สิงหาคม"}.
{"September", "กันยายน"}.
{"October", "ตุลาคม"}.
{"November", "พฤศจิกายน"}.
{"December", "ธันวาคม"}.
{"Room Configuration", "การกำหนดค่าห้องสนทนา"}.

% mod_offline.erl
{"Time", "เวลา"}.
{"From", "จาก"}.
{"To", "ถึง"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
