% $Id$
% Language: Turkish (türkçe)
% Author: Doruk Fisek 

% jlib.hrl
{"No resource provided", "Hiç kaynak sağlanmadı"}.

% mod_configure.erl
{"Restart Service", "Servisi Tekrar Başlat"}.
{"Shut Down Service", "Servisi Kapat"}.
{"Delete User", "Kullanıcıyı Sil"}.
{"End User Session", "Kullanıcı Oturumunu Kapat"}.
{"Get User Password", "Kullanıcı Parolasını Al"}.
{"Change User Password", "Kullanıcı Parolasını Değiştir"}.
{"Get User Last Login Time", "Kullanıcı Son Giriş Zamanınlarını Al"}.
{"Get User Statistics", "Kullanıcı İstatistiklerini Al"}.
{"Get Number of Registered Users", "Kayıtlı Kullanıcı Sayısını Al"}.
{"Get Number of Online Users", "Bağlı Kullanıcı Sayısını Al"}.
{"User Management", "Kullanıcı Yönetimi"}.
{"Time delay", "Zaman gecikmesi"}.
{"Password Verification", "Parola Doğrulaması"}.
{"Number of registered users", "Kayıtlı kullanıcı sayısı"}.
{"Number of online users", "Bağlı kullanıcı sayısı"}.
{"Last login", "Son giriş"}.
{"Roster size", "İsim listesi boyutu"}.
{"IP addresses", "IP adresleri"}.
{"Resources", "Kaynaklar"}.
{"Choose storage type of tables", "Tabloların veri depolama tipini seçiniz"}.
{"RAM copy", "RAM kopyala"}.
{"RAM and disc copy", "RAM ve disk kopyala"}.
{"Disc only copy", "Sadece disk kopyala"}.
{"Remote copy", "Uzak kopyala"}.
{"Stop Modules at ", "Modülleri Durdur : "}.
{"Choose modules to stop", "Durdurulacak modülleri seçiniz"}.
{"Start Modules at ", "Modülleri Başlat : "}.
{"Enter list of {Module, [Options]}", "{Module, [Options]} listesi giriniz"}.
{"List of modules to start", "Başlatılacak modüllerin listesi"}.
{"Backup to File at ", "Dosyaya Yedekle : "}.
{"Enter path to backup file", "Yedek dosyasının yolunu giriniz"}.
{"Path to File", "Dosyanın Yolu"}.
{"Restore Backup from File at ", "Dosyadaki Yedekten Geri Al : "}.
{"Dump Backup to Text File at ", "Metin Dosyasına Döküm Alarak Yedekle : "}.
{"Enter path to text file", "Metin dosyasının yolunu giriniz"}.
{"Import User from File at ", "Dosyadan Kullanıcıları İçe Aktar : "}.
{"Enter path to jabberd1.4 spool file", "jabberd1.4 spool dosyası için yol giriniz"}.
{"Import Users from Dir at ", "Dizinden Kullanıcıları İçe Aktar : "}.
{"Enter path to jabberd1.4 spool dir", "jabberd1.4 spool dosyası için yol giriniz"}.
{"Path to Dir", "Dizinin Yolu"}.
{"Hostname Configuration", "Makina İsmi Ayarı"}.
{"Choose host name", "Makina ismi seçiniz"}.
{"Host name", "Makina ismi"}.
{"Access Control List Configuration", "Erişim Kontrol Listelerinin Ayarlanması (ACL)"}.
{"Access control lists", "Erişim kontrol listeleri (ACL)"}.
{"Access Configuration", "Erişim Ayarları"}.
{"Access rules", "Erişim kuralları"}.
{"Remove Users", "Kullanıcıları Kaldır"}.
{"Choose users to remove", "Kaldırılacak kullanıcıları seçin"}.
{"Administration of ", "Yönetim : "}.
{"Action on user", "Kullanıcıya uygulanacak eylem"}.
{"Edit Properties", "Özellikleri Düzenle"}.
{"Remove User", "Kullanıcıyı Kaldır"}.
{"Database", "Veritabanı"}.
{"Outgoing s2s Connections", "Giden s2s Bağlantıları"}.
{"Import Users From jabberd 1.4 Spool Files", "Jabberd 1.4 Spool Dosyalarından Kullanıcıları İçeri Aktar"}.
{"Database Tables Configuration at ", "Veritabanı Tablo Ayarları : "}.

% src/ejabberd_c2s.erl
{"Use of STARTTLS required", "STARTTLS kullanımı gereklidir"}.
{"Replaced by new connection", "Eski bağlantı yenisi ile değiştirildi"}.

% mod_disco.erl
{"Configuration", "Ayarlar"}.
{"Online Users", "Bağlı Kullanıcılar"}.
{"All Users", "Tüm Kullanıcılar"}.
{"To ~s", "Kime ~s"}.
{"From ~s", "Kimden ~s"}.
{"Running Nodes", "Çalışan Düğümler"}.
{"Stopped Nodes", "Durdurulmuş Düğümler"}.
{"Host Name", "Sunucu Adı"}.
{"Access Control Lists", "Erişim Kontrol Listeleri (ACL)"}.
{"Access Rules", "Erişim Kuralları"}.
{"Remove Users", "Kullanıcıları Kaldır"}.
{"Modules", "Modüller"}.
{"Start Modules", "Modülleri Başlat"}.
{"Stop Modules", "Modülleri Durdur"}.
{"Backup Management", "Yedek Yönetimi"}.
{"Backup", "Yedekle"}.
{"Restore", "Yedekten Geri Al"}.
{"Dump to Text File", "Metin Dosyasına Döküm Al"}.
{"Import File", "Dosyayı İçe Aktar"}.
{"Import Directory", "Dizini İçe Aktar"}.

% mod_register.erl
{"Choose a username and password to register with this server", "Bu sunucuya kayıt olmak için bir kullanıcı ismi ve parola seçiniz"}.

% src/mod_vcard_ldap.erl
{"Erlang Jabber Server", "Erlang Jabber Sunucusu"}.
{"ejabberd vCard module", "ejabberd vCard modülü"}.
{"Email", "E-posta"}.
{"Search Results for ", "Arama sonuçları : "}.
{"Jabber ID", "Jabber ID"}.

% mod_vcard.erl
{"You need an x:data capable client to search", "Arama yapabilmek için x:data becerisine sahip bir istemciye gereksinimiz var"}.
{"Search users in ", "Kullanıcılarda arama yap : "}.
{"vCard User Search", "vCard Kullanıcı Araması"}.
{"Fill in fields to search for any matching Jabber User", "Eşleşen jabber kullanıcılarını aramak için alanları doldurunuz"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Eşleşen jabber kullanıcılarını aramak için formu doldurunuz (Alt dizgi eşlemek için alanın sonuna * ekleyin)"}.

{"User",              "Kullanıcı"}.
{"Full Name", 	      "Tam İsim"}.
{"Name", 	      "İsim"}.
{"Middle Name",       "Ortanca İsim"}.
{"Family Name",       "Soyisim"}.
{"Nickname", 	      "Takma isim"}.
{"Birthday", 	      "Doğumgünü"}.
{"Country", 	      "Ülke"}.
{"City", 	      "İl"}.
{"Organization Name", "Kurum İsmi"}.
{"Organization Unit", "Kurumun İlgili Birimi"}.

% mod_adhoc.erl
{"Commands", "Komutlar"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Send announcement to all users on all hosts", "Tüm sunuculardaki tüm kullanıcılara duyuru yolla"}.
{"Set message of the day on all hosts and send to online users", "Tüm sunucularda günün mesajını belirle ve bağlı tüm kullanıcılara gönder"}.
{"Update message of the day on all hosts (don't send)", "Tüm sunuculardaki günün mesajını güncelle (gönderme)"}.
{"Delete message of the day on all hosts", "Tüm sunuculardaki günün mesajını sil"}.
{"Really delete message of the day?", "Günün mesajını silmek istediğinize emin misiniz?"}.
{"Subject", "Konu"}.
{"Message body", "Mesajın gövdesi"}.
{"No body provided for announce message", "Duyuru mesajının gövdesi yok"}.
{"Announcements", "Duyurular"}.
{"Send announcement to all users", "Duyuruyu tüm kullanıcılara yolla"}.
{"Send announcement to all online users", "Duyuruyu tüm bağlı kullanıcılara yolla"}.
{"Send announcement to all online users on all hosts", "Duyuruyu tüm sunuculardaki tüm bağlı kullanıcılara yolla"}.
{"Set message of the day and send to online users", "Günün mesajını belirle"}.
{"Update message of the day (don't send)", "Günün mesajını güncelle (gönderme)"}.
{"Delete message of the day", "Günün mesajını sil"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd Publish-Subscribe module", "ejabberd Publish-Subscribe modülü"}.
{"PubSub subscriber request", "PubSub üye isteği"}.
{"Choose whether to approve this entity's subscription.", "Bu varlığın üyeliğini onaylayıp onaylamamayı seçiniz."}.
{"Node ID", "Düğüm ID"}.
{"Subscriber Address", "Üye Olanın Adresi"}.
{"Allow this JID to subscribe to this pubsub node?", "Bu JID bu pubsub düğümüne üye olmasına izin verilsin mi?"}.
{"Deliver event notifications", "Olay uyarıları gönderilsin"}.
{"Specify the access model", "Erişim modelini belirtiniz"}.
{"Roster groups that may subscribe (if access model is roster)", "Üye olabilecek kontak listesi grupları (eğer erişim modeli 'kontak listesi' ise)"}.
{"When to send the last published item", "Son yayınlanan öğe ne zaman gönderilsin"}.
{"ejabberd pub/sub module", "pub/sub ejabberd modülü"}.
{"Node Creator", "Düğüm Oluşturucu"}.
{"Notify subscribers when the node configuration changes", "Düğüm ayarları değiştiğinde üyeleri uyar"}.
{"Notify subscribers when the node is deleted", "Bir düğüm silindiğinde üyeleri uyar"}.
{"Notify subscribers when items are removed from the node", "Düğümden öğeler kaldırıldığında üyeleri uyar"}.
{"Whether to allow subscriptions", "Üyeliklere izin verilsin mi"}.
{"Specify the subscriber model", "Üye olma modelini belirtiniz"}.
{"Specify the publisher model", "Yayıncı modelini belirtiniz"}.
{"Max payload size in bytes", "En fazla yük (payload) boyutu (bayt olarak)"}.
{"Send items to new subscribers", "Yeni üyelere öğeleri yolla"}.
{"Only deliver notifications to available users", "Uyarıları sadece durumu uygun kullanıcılara ulaştır"}.
{"Specify the current subscription approver", "Mevcut üyelik onaylayıcısını belirtiniz"}.
{"Publish-Subscribe", "Yayınla-Üye Ol"}.

% mod_muc/mod_muc_log.erl
{"Chatroom configuration modified", "Sohbet odası ayarı değiştirildi"}.
{"joins the room", "odaya katıldı"}.
{"leaves the room", "odadan ayrıldı"}.
{"has been kicked", "odadan atıldı"}.
{"has been banned", "odaya girmesi yasaklandı"}.
{"is now known as", "isim değiştirdi :"}.
{"Monday", "Pazartesi"}.
{"Tuesday", "Salı"}.
{"Wednesday", "Çarşamba"}.
{"Thursday", "Perşembe"}.
{"Friday", "Cuma"}.
{"Saturday", "Cumartesi"}.
{"Sunday", "Pazar"}.
{"January", "Ocak"}.
{"February", "Şubat"}.
{"March", "Mart"}.
{"April", "Nisan"}.
{"May", "Mayıs"}.
{"June", "Haziran"}.
{"July", "Temmuz"}.
{"August", "Ağustos"}.
{"September", "Eylül"}.
{"October", "Ekim"}.
{"November", "Kasım"}.
{"December", "Aralık"}.
{"Room Configuration", "Oda Ayarları"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname", "Takma isminizi kaydettirmek için x:data becerisine sahip bir istemciye gereksinimiz var"}.
{"Nickname Registration at ", "Takma İsim Kaydı : "}.
{"Enter nickname you want to register", "Kaydettirmek istediğiniz takma ismi giriniz"}.
{"ejabberd MUC module", "ejabberd MUC modülü"}.
{"Only service administrators are allowed to send service messages", "Sadece servis yöneticileri servis mesajı gönderebilirler"}.
{"Room creation is denied by service policy", "Odanın oluşturulması servis politikası gereği reddedildi"}.
{"Conference room does not exist", "Konferans odası bulunamadı"}.
{"Access denied by service policy", "Servis politikası gereği erişim engellendi"}.
{"Specified nickname is already registered", "Belirtilen takma isim daha önce bir başkası tarafından kaydettirilmiş"}.
{"You must fill in field \"Nickname\" in the form", "Formda \"Takma isim\" alanını doldurmanız gerekiyor"}.
{"Chatrooms", "Sohbet Odaları"}.

% mod_muc/mod_muc_room.erl
{"Traffic rate limit is exceeded", "Trafik oran sınırı aşıldı"}.
{"Maximum Number of Occupants", "Odada En Fazla Bulunabilecek Kişi Sayısı"}.
{"No limit", "Sınırsız"}.
{"~s invites you to the room ~s", "~s sizi ~s odasına davet ediyor"}.
{"the password is", "parola :"}.
{" has set the subject to: ", " konuyu değiştirdi: "}.
{"You need an x:data capable client to configure room", "Odayı ayarlamak için x:data becerisine sahip bir istemciye gereksinimiz var"}.
{"Configuration for ", "Ayarlar : "}.
{"Room title", "Oda başlığı"}.
{"Password", "Parola"}.
{"Only moderators and participants are allowed to change subject in this room", "Sadece moderatörlerin ve katılımcıların bu odanın konusunu değiştirmesine izin veriliyor"}.
{"Only moderators are allowed to change subject in this room", "Sadece moderatörlerin bu odanın konusunu değiştirmesine izin veriliyor"}.
{"Visitors are not allowed to send messages to all occupants", "Ziyaretçilerin odadaki tüm sakinlere mesaj göndermesine izin verilmiyor"}.
{"Only occupants are allowed to send messages to the conference", "Sadece oda sakinlerinin konferansa mesaj göndermesine izin veriliyor"}.
{"It is not allowed to send normal messages to the conference", "Konferansa normal mesajlar gönderilmesine izin verilmiyor"}.
{"It is not allowed to send private messages to the conference", "Konferansa özel mesajlar gönderilmesine izin verilmiyor"}.
{"Improper message type", "Uygunsuz mesaj tipi"}.
{"Nickname is already in use by another occupant", "Takma isim odanın başka bir sakini tarafından halihazırda kullanımda"}.
{"Nickname is registered by another person", "Takma isim başka biri tarafından kaydettirilmiş"}.
{"It is not allowed to send private messages of type \"groupchat\"", "\"groupchat\" tipinde özel mesajlar gönderilmesine izin verilmiyor"}.
{"Recipient is not in the conference room", "Alıcı konferans odasında değil"}.
{"Only occupants are allowed to send queries to the conference", "Sadece oda sakinlerinin konferansa sorgu göndermesine izin veriliyor"}.
{"Queries to the conference members are not allowed in this room", "Bu odada konferans üyelerine sorgu yapılmasına izin verilmiyor"}.
{"You have been banned from this room", "Bu odaya girmeniz yasaklandı"}.
{"Membership required to enter this room", "Bu odaya girmek için üyelik gerekiyor"}.
{"Password required to enter this room", "Bu odaya girmek için parola gerekiyor"}.
{"Incorrect password", "Yanlış parola"}.
{"Administrator privileges required", "Yönetim yetkileri gerekli"}.
{"Moderator privileges required", "Moderatör yetkileri gerekli"}.
{"JID ~s is invalid", "JID ~s geçersiz"}.
{"Nickname ~s does not exist in the room", "~s takma ismi odada yok"}.
{"Invalid affiliation: ~s", "Geçersiz ilişki: ~s"}.
{"Invalid role: ~s", "Geçersiz rol: ~s"}.
{"Owner privileges required", "Sahip yetkileri gerekli"}.
{"private, ", "özel"}.
{"This room is not anonymous", "Bu oda anonim değil"}.
{"Make room persistent", "Odayı kalıcı hale getir"}.
{"Make room public searchable", "Odayı herkes tarafından aranabilir hale getir"}.
{"Make participants list public", "Katılımcı listesini herkese açık hale getir"}.
{"Make room password protected", "Odayı parola korumalı hale getir"}.
{"Make room members-only", "Odayı sadece üyelere açık hale getir"}.
{"Make room moderated", "Odayı moderasyonlu hale getir"}.
{"Default users as participants", "Kullanıcılar öntanımlı olarak katılımcı olsun"}.
{"Allow users to change subject", "Kullanıcıların konu değiştirmesine izin ver"}.
{"Allow users to send private messages", "Kullanıcıların özel mesaj göndermelerine izin ver"}.
{"Allow users to query other users", "Kullanıcıların diğer kullanıcıları sorgulamalarına izin ver"}.
{"Allow users to send invites", "Kullanıcıların davetiye göndermelerine izin ver"}.
{"Enable logging", "Kayıt tutma özelliğini aç"}.
{"Description", "Tanım"}.
{"Number of occupants", "Oda sakini sayısı"}.
{"Present real JIDs to", "Gerçek JID'lerini göster :"}.
{"moderators only", "sadece moderatörler"}.
{"anyone", "herkes"}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module", "ejabberd IRC modülü"}.
{"You need an x:data capable client to configure mod_irc settings", "mod_irc ayarlarını düzenlemek için x:data becerisine sahip bir istemciye gereksinimiz var"}.
{"Registration in mod_irc for ", "mod_irc'ye kayıt : "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "IRC sunuculara bağlanmak için kullanmak istediğiniz kullanıcı isimleri ve kodlamaları giriniz"}.
{"IRC Username", "IRC Kullanıcı İsmi"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "IRC sunucuları için farklı kodlamalar belirtmek istiyorsanız, '{\"irc sunucusu\", \"kodlama\"}' biçeminde değerlerle bu listeyi doldurunuz. Öntanımlı olarak bu servis \"~s\" kodlamasını kullanıyor."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Örnek: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Kodlamalar"}.
{"IRC Transport", "IRC Nakli (Transport)"}.

% web/ejabberd_web_admin.erl
{"Administration", "Yönetim"}.
{"Users", "Kullanıcılar"}.
{"Nodes", "Düğümler"}.
{"Shared Roster", "Paylaşılmış Kontak Listesi"}.
{"Statistics", "İstatistikler"}.
{"ejabberd (c) 2002-2008 Alexey Shchepin, 2004-2008 Process One", "ejabberd (c) 2002-2008 Alexey Shchepin, 2004-2008 Process One"}.
{"(Raw)", "(Ham)"}.
{"Submitted", "Gönderilenler"}.
{"Bad format", "Kötü biçem"}.
{"Raw", "Ham"}.
{"Delete Selected", "Seçilenleri Sil"}.
{"Submit", "Gönder"}.
{"~s access rule configuration", "~s erişim kuralları ayarları"}.
{"Node not found", "Düğüm bulunamadı"}.
{"Add New", "Yeni Ekle"}.
{"Registered Users", "Kayıtlı Kullanıcılar"}.
{"Registered Users:", "Kayıtlı Kullanıcılar:"}.
{"Change Password", "Parola Değiştir"}.
{"Connected Resources:", "Bağlı Kaynaklar:"}.
{"Password:", "Parola:"}.
{"None", "Hiçbiri"}.
{"Node ", "Düğüm "}.
{"Listened Ports", "Dinlenen Kapılar (Portlar)"}.
{"Restart", "Tekrar Başlat"}.
{"Stop", "Durdur"}.
{"RPC Call Error", "RPC Çağrı Hatası"}.
{"Name", "İsim"}.
{"Storage Type", "Depolama Tipi"}.
{"Size", "Boyut"}.
{"Memory", "Bellek"}.
{"OK", "Tamam"}.
{"Listened Ports at ", "Dinlenen Kapılar (Portlar) : "}.
{"Uptime:", "Hizmet Süresi:"}.
{"CPU Time:", "İşlemci Zamanı:"}.
{"Transactions Commited:", "Tamamlanan Hareketler (Transactions Commited):"}.
{"Transactions Aborted:", "İptal Edilen Hareketler (Transactions):"}.
{"Transactions Restarted:", "Tekrar Başlatılan Hareketler (Transactions):"}.
{"Transactions Logged:", "Kaydı Tutulan Hareketler (Transactions):"}.
{"Port", "Kapı (Port)"}.
{"Module", "Modül"}.
{"Options", "Seçenekler"}.
{"Update", "GÜncelle"}.
{"Delete", "Sil"}.
{"Add User", "Kullanıcı Ekle"}.
{"Offline Messages", "Çevirim-dışı Mesajlar"}.
{"Users Last Activity", "Kullanıcıların Son Aktiviteleri"}.
{"Never", "Asla"}.
{"~s's Offline Messages Queue", "~s Kullanıcısının Mesaj Kuyruğu"}.
{"Time", "Zaman"}.
{"From", "Kimden"}.
{"To", "Kime"}.
{"Packet", "Paket"}.
{"Offline Messages:", "Çevirim-dışı Mesajlar:"}.
{"Roster", "Kontak Listesi"}.
{"Nickname", "Takma isim"}.
{"Subscription", "Üyelik"}.
{"Pending", "Sıra Bekleyen"}.
{"Groups", "Gruplar"}.
{"Remove", "Kaldır"}.
{"Add Jabber ID", "Jabber ID'si Ekle"}.
{"User ", "Kullanıcı "}.
{"Roster of ", "Kontak Listesi : "}.
{"Online", "Bağlı"}.
{"Validate", "Geçerli"}.
{"Name:", "İsim:"}.
{"Description:", "Tanım:"}.
{"Members:", "Üyeler:"}.
{"Displayed Groups:", "Gösterilen Gruplar:"}.
{"Group ", "Group "}.
{"Period: ", "Periyot:"}.
{"Last month", "Geçen ay"}.
{"Last year", "Geçen yıl"}.
{"All activity", "Tüm aktivite"}.
{"Show Ordinary Table", "Sıradan Tabloyu Göster"}.
{"Show Integral Table", "Önemli Tabloyu Göster"}.
{"Modules at ", "Modüller : "}.
{"Start", "Başlat"}.
{"Virtual Hosts", "Sanal Sunucular"}.
{"ejabberd virtual hosts", "ejabberd sanal sunucuları"}.
{"Host", "Sunucu"}.
{"Authenticated Users:", "Doğrulanmış Kullanıcılar:"}.
{"No Data", "Veri Yok"}.
{"ejabberd Web Interface", "ejabberd Web Arayüzü"}.
{"Online Users:", "Bağlı Kullanıcılar:"}.
{"Outgoing s2s Connections:", "Giden s2s Bağlantıları:"}.
{"Outgoing s2s Servers:", "Giden s2s Sunucuları"}.
{"Database Tables at ", "Veritabanı Tabloları : "}.
{"Backup of ", "Yedek : "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database seperately.", "Bu seçeneklerin sadece gömülü Mnesia veritabanını yedekleyeceğine dikkat edin. Eğer ODBC modülünü kullanıyorsanız, SQL veritabanınızı ayrıca yedeklemelisiniz."}.
{"Store binary backup:", "İkili yedeği sakla:"}.
{"Restore binary backup immediately:", "Hemen ikili yedekten geri al:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "ejabberd'nin bir sonraki tekrar başlatılışında ikili yedekten geri al (daha az bellek gerektirir)"}.
{"Store plain text backup:", "Düz metin yedeği sakla:"}.
{"Restore plain text backup immediately:", "Hemen düz metin yedekten geri al"}.
{"Statistics of ~p", "~p istatistikleri"}.
{"Update ", "Güncelle "}.
{"Update plan", "Planı güncelle"}.
{"Updated modules", "Güncellenen modüller"}.
{"Update script", "Betiği Güncelle"}.
{"Low level update script", "Düşük seviye güncelleme betiği"}.
{"Script check", "Betik kontrolü"}.
{"Not Found", "Bulunamadı"}.
{"Shared Roster Groups", "Paylaşımlı Kontak Listesi Grupları"}.
{"Last Activity", "Son Aktivite"}.

% mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams modülü"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Çevirim-dışı mesaj kuyruğunuz dolu. Mesajını dikkate alınmadı."}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
