% $Id$

% mod_configure.erl
{"DB Tables Configuration at ", "Конфігурація таблиць БД на "}.
{"Choose storage type of tables", "Оберіть тип збереження таблиць"}.
{"RAM copy", "ОЗУ"}.
{"RAM and disc copy", "ОЗУ та диск"}.
{"Disc only copy", "тільки диск"}.
{"Remote copy", "не зберігаеться локально"}.
{"Stop Modules at ", "Зупинка модулів на "}.
{"Choose modules to stop", "Оберіть модулі, які необхідно зупинити"}.
{"Start Modules at ", "Запуск модулів на "}.
{"Enter list of {Module, [Options]}", "Введіть список такого виду {Module, [Options]}"}.
{"List of modules to start", "Список завантажуваних модулів"}.
{"Backup to File at ", "Резервне копіювання в файл на "}.
{"Enter path to backup file", "Введіть шлях до резервного файла"}.
{"Path to File", "Шлях до файла"}.
{"Restore Backup from File at ", "Відновлення з резервної копії на "}.
{"Dump Backup to Text File at ", "Копіювання в текстовий файл на "}.
{"Enter path to text file", "Введіть шлях до текстового файла"}.
{"Import User from File at ", "Імпортування користувача з файла на "}.
{"Enter path to jabberd1.4 spool file", "Введіть шлях до файла зі спула jabberd1.4"}.
{"Import Users from Dir at ", "Імпортування користувача з директорії на "}.
{"Enter path to jabberd1.4 spool dir", "Введіть шлях до директорії спула jabberd1.4"}.
{"Path to Dir", "шлях до директорії"}.
{"Hostname Configuration", "Конфігурація назви хоста"}.
{"Choose host name", "Оберіть назву хоста"}.
{"Host name", "Назва хоста"}.
{"Access Control List Configuration", "Конфігурація списків управління доступом"}.
{"Access control lists", "Списки управління доступом"}.
{"Access Configuration", "Конфігурація доступа"}.
{"Access rules", "Правила доступу"}.
{"Remove Users", "Видалення користувачів"}.
{"Choose users to remove", "Оберіть користувачів, яких необхідно видалити"}.
{"Administration of ", "Адміністрування "}.
{"Action on user", "Дія над користувачем"}.
{"Edit Properties", "Змінити параметри"}.
{"Remove User", "Видалити коростувача"}.

% mod_disco.erl
{"Configuration", "Конфігурація"}.
{"Online Users", "Підключені користувачі"}.
{"All Users", "Всі коритстувачі"}.
{"Outgoing S2S connections", "Вихідні S2S-з`єднання"}.
{"To ~s", "До ~s"}.
{"From ~s", "Від ~s"}.
{"Running Nodes", "Рабочі вузли"}.
{"Stopped Nodes", "Зупинені вузли"}.
{"Host Name", "Назва хоста"}.
{"Access Control Lists", "Списки управління доступом"}.
{"Access Rules", "Правила доступу"}.
{"Remove Users", "Видалення користувачів"}.
{"DB", "БД"}.
{"Modules", "Модулі"}.
{"Start Modules", "Запуск модулів"}.
{"Stop Modules", "Зупинка модулів"}.
{"Backup Management", "Управління резервним копіюванням"}.
{"Import users from jabberd1.4 spool files", "Імпортування користувачів зі спулу jabberd1.4"}.
{"Backup", "Резервне копіювання"}.
{"Restore", "Відновлення з резервної копії"}.
{"Dump to Text File", "Копіювання в текстовий файл"}.
{"Import File", "Імпорт з файла"}.
{"Import Directory", "Імпорт з директорії"}.

% mod_register.erl
{"Choose a username and password to register with this server",
 "Оберіь назву користувача та пароль для реєстрації на цьому сервері"}.

% mod_vcard.erl
{"Erlang Jabber Server\nCopyright (c) 2002-2004 Alexey Shchepin",
 "Erlang Jabber Server\nCopyright (c) 2002-2004 Алексей Щепин"}.
{"ejabberd vCard module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd vCard модуль\nCopyright (c) 2003-2004 Алексей Щепин"}.
{"You need an x:data capable client to search",
 "Для пошуку необхідний x:data-сумісний кліент"}.
{"Search users in ", "Пошук користувачів в "}.
{"Fill in fields to search for any matching Jabber User",
 "Заповніть поля для пошуку користувача Jabber"}.
{"Results of search in ", "Результати пошуку в "}.

{"User",              "Користувач"}.
{"Full Name", 	      "Повне ім`я"}.
{"Name", 	      "Ім`я"}.
{"Middle Name",       "По-батькові"}.
{"Family Name",       "Фамілія"}.
{"Nickname", 	      "Псевдонім"}.
{"Birthday", 	      "День нарождення"}.
{"Country", 	      "Країна"}.
{"City", 	      "Місто"}.
{"email", 	      "email"}.
{"Organization Name", "Назва организації"}.
{"Organization Unit", "Відділ организації"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd pub/sub module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd pub/sub модуль\nCopyright (c) 2003-2004 Алексей Щепин"}.

% mod_muc/mod_muc.erl
{"You need an x:data capable client to register nickname",
 "Для реєстрації псевдоніму необхідний x:data-сумісний кліент"}.
{"Nickname Registration at ", "Реєстрація псевдоніма на "}.
{"Enter nickname you want to register", "Введіть псевдонім, який ви хочете зареєструвати"}.
{"ejabberd MUC module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd MUC модуль\nCopyright (c) 2003-2004 Алексей Щепин"}.
{"Only service administrators are allowed to send service messages",
 "Тільки адміністратор сервісу може надсилати службові повідомлення"}.
{"Room creation is not allowed by service policy",
 "Створювати конференцію не дозволяється політикою сервіса"}.
{"Conference room does not exist", "Конференція не існує"}.
{"Access denied by service policy", "Доступ зоборонений політикою сервіса"}.
{"You must fill in field \"nick\" in the form",
 "Вам необхідно заповнити поле \"nick\" у формі"}.
{"Specified nickname is already registered", "Вказаний псевдонім вже зареєстрований"}.

% mod_muc/mod_muc_room.erl
{" has set the subject to: ", " встановив(ла) тему: "}.
{"You need an x:data capable client to configure room",
 "Для конфігурування кімнати необхідний x:data-сумісний кліент"}.
{"Configuration for ", "Конфігурація "}.
{"Room title", "Назва кімнати"}.
{"Allow users to change subject?", "Дозволити користувачам змінювати тему?"}.
{"Allow users to query other users?",
 "Дозволити iq-запити до користувачів?"}.
{"Allow users to send private messages?",
 "Дозволити приватні повідомлення?"}.
{"Make room public searchable?", "Зробити кімнату видимою всім?"}.
{"Make participants list public?", "Зробити список участників видимим всім?"}.
{"Make room persistent?", "Зробити кімнату постійною?"}.
{"Make room moderated?", "Зробити кімнату модерованою?"}.
{"Default users as members?",
 "Зробити користувачів участниками за замовчуванням?"}.
{"Make room members only?",
 "Кімната тільки для зареєтрованых участників?"}.
{"Allow users to send invites?",
 "Дозволити користувачам посилати запрошення?"}.
{"Make room password protected?", "Зробити кімнату захищеною паролем?"}.
{"Password", "Пароль"}.
{"Make room anonymous?", "Зробити кімнату анонімною?"}.
{"Enable logging?", "Включити журнал роботи?"}.
{"Only moderators and participants are allowed to change subject in this room",
 "Тільки модератори та участники можуть змінювати тему в цій комнаті"}.
{"Only moderators are allowed to change subject in this room",
 "Тільки модератори можуть змінювати тему в цій комнаті"}.
{"Visitors are not allowed to send messages to all occupants",
 "Відвідувачам не дозволяється посилати повідомлення всім присутнім"}.
{"Only occupants are allowed to send messages to the conference",
 "Тільки присутнім дозволяється посилати повідомленняя в конференцію"}.
{"It is not allowed to send normal messages to the conference",
 "Не дозволяється посилати звичайні повідомленняя в конференцію"}.
{"It is not allowed to send private messages to the conference",
 "Не дозволяється посилати приватні повідомлення  в конференцію"}.
{"Improper message type", "Неправильний тип повідомлення"}.
{"Nickname is already in use by another occupant", "Псевдонім зайнятий кимось з присутніх"}.
{"Nickname is registered by another person", "Псевдонім зайнятий кимось іншим"}.
{"It is not allowed to send private messages of type \"groupchat\"",
 "Не дозволяється посилати приватні повідомлення типу \"groupchat\""}.
{"Recipient is not in the conference room", "Адресата немає в конференції"}.
{"Only occupants are allowed to send queries to the conference",
 "Тільки присутнім дозволяється відправляти запити в конференцію"}.
{"Queries to the conference members are not allowed in this room",
 "Запити до користувачів в цій конференції зоборонені"}.
{"You have been banned from this room", "Вам заборонено входити в цю конференцію"}.
{"Membership required to enter this room", "В цю конференціию можуть входити тільки її члени"}.
{"Password required to enter this room", "Щоб зайти в цю конференцію, необхідний пароль"}.
{"Incorrect password", "Неправильний пароль"}.
{"Administrator privileges required", "Необхідні права адміністратора"}.
{"Moderator privileges required", "Необхідні права модератора"}.
{"JID ~s is invalid", "JID ~s недопустимий"}.
{"Nickname ~s does not exist in the room", "Псевдонім ~s в кімнаті відсутній"}.
{"Invalid affiliation: ~s", "Недопустимий ранг: ~s"}.
{"Invalid role: ~s", "Недопустима роль: ~s"}.
{"Owner privileges required", "Необхідні права власника"}.
{"private, ", "приватна, "}.

% mod_irc/mod_irc.erl
{"ejabberd IRC module\nCopyright (c) 2003-2004 Alexey Shchepin",
 "ejabberd IRC модуль\nCopyright (c) 2003-2004 Алексей Щепин"}.
{"You need an x:data capable client to configure mod_irc settings",
 "Для налагодження параметрів mod_irc необхідний x:data-сумісний кліент"}.
{"Registration in mod_irc for ", "Реєстрація в mod_irc для "}.
{"Enter username and encodings you wish to use for connecting to IRC servers",
 "Введіть ім`я користувача та кодування, які будуть використовуватися при підключенні до IRC-серверів"}.
{"IRC Username", "Ім`я користувача IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Щоб вказати різні кодування для різних серверів IRC, заповніть список значеннями в форматі '{\"irc server\", \"encoding\"}'. За замовчуванням ця служба використовує кодування \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Приклад: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Кодування"}.

% web/ejabberd_web_admin.erl
{"ejabberd administration", "Адміністрування ejabberd"}.
{"Users", "Користувачі"}.
{"Nodes", "Вузли"}.
{"Statistics", "Статистика"}.
{"ejabberd (c) 2002-2004 Alexey Shchepin", "ejabberd (c) 2002-2004 Алексей Щепин"}.
{"(raw)", "(необроблений формат)"}.
{"submitted", "відправлено"}.
{"bad format", "неправильний формат"}.
{"raw", "необроблений формат"}.
{"ejabberd access control lists configuration", "Конфігурація списків управління доступом ejabberd"}.
{"Delete Selected", "Видалити виділені"}.
{"Submit", "Відправити"}.
{"ejabberd access rules configuration", "Конфігурація правил доступу ejabberd"}.
{"~s access rule configuration", "Конфігурація правила доступу ~s"}.
{"ejabberd users", "Користувачі ejabberd"}.
{"ejabberd stats", "Статистика ejabberd"}.
{"Node not found", "Вузол не знайдено"}.
{"Add New", "Добавити"}.
{"Registered users", "Зареєстровані користувачі"}.
{"Authentificated users", "Аутентифіковані користувачі"}.
{"Online users", "Підключені користувачі"}.
{"Outgoing S2S servers", "Вихідні S2S-сервери"}.
{"Change Password", "Змінити пароль"}.
{"Connected Resources:", "Підключені ресурси:"}.
{"Password:", "Пароль:"}.
{"None", "Ні"}.
{"Node ", "Вузол "}.
{"DB Management", "Управління БД"}.
{"Listened Ports Management", "Управління відкритими портами"}.
{"Restart", "Перезапустити"}.
{"Stop", "Зупинити"}.
{"RPC call error", "Помилка визову RPC"}.
{"DB Tables at ", "Таблиці БД на "}.
{"Name", "Назва"}.
{"Storage Type", "Тип таблиці"}.
{"Size", "Розмір"}.
{"Memory", "Пам`ять"}.
{"Backup Management at ", "Управління резервним копіюванням на "}.
{"Store a backup in a file", "Зберігти резервну копію в файл"}.
{"OK", "Продовжити"}.
{"Restore a backup from a file", "Відновити резервну копію з файла"}.
{"Install a database fallback from a file", "Встановити базу даних для відновлення при слідуючому запуску"}.
{"Dump a database in a text file", "Копіювати базу даних в текстовий файл"}.
{"Restore a database from a text file", "Відновити базу даних з текстового файла"}.
{"Listened Ports at ", "Відкриті порти на "}.
{"~p statistics", "статистика вузла ~p"}.
{"Uptime", "Час роботи сервера"}.
{"CPU Time", "Процесорний час"}.
{"Transactions commited", "Транзакції завершені"}.
{"Transactions aborted", "Транзакції відмінені"}.
{"Transactions restarted", "Транзакції перезапущені"}.
{"Transactions logged", "Транзакції запротокольовані"}.
{"Port", "Порт"}.
{"Module", "Модуль"}.
{"Options", "Параметри"}.
{"Update", "Обновити"}.
{"Delete", "Видалити"}.
{"", ""}.

% Local Variables:
% mode: erlang
% End: