{"Access Configuration","Конфігурація доступа"}.
{"Access Control List Configuration","Конфігурація списків керування доступом"}.
{"Access control lists","Списки керування доступом"}.
{"Access Control Lists","Списки керування доступом"}.
{"Access rules","Правила доступу"}.
{"Access Rules","Правила доступу"}.
{"Action on user","Дія над користувачем"}.
{"Add Jabber ID","Додати Jabber ID"}.
{"Add New","Додати"}.
{"Add User","Додати користувача"}.
{"Administration of ","Адміністрування "}.
{"Administration","Адміністрування"}.
{"Administrator privileges required","Необхідні права адміністратора"}.
{"A friendly name for the node","Псевдонім для вузла"}.
{"All activity","Вся статистика"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","Чи дозволити цьому Jabber ID абонувати новини наданого вузла"}.
{"Allow users to change the subject","Дозволити користувачам змінювати тему"}.
{"Allow users to query other users","Дозволити iq-запити до користувачів"}.
{"Allow users to send invites","Дозволити користувачам надсилати запрошення"}.
{"Allow users to send private messages","Дозволити приватні повідомлення"}.
{"Allow visitors to change nickname","Дозволити відвідувачам змінювати псевдонім"}.
{"Allow visitors to send status text in presence updates","Дозволити відвідувачам відсилати текст статусу в оновленнях присутності"}.
{"All Users","Всі користувачі"}.
{"Announcements","Сповіщення"}.
{"anyone","всім учасникам"}.
{"A password is required to enter this room","Щоб зайти в цю конференцію, необхідно ввести пароль"}.
{"April","квітня"}.
{"August","серпня"}.
{"Backup Management","Керування резервним копіюванням"}.
{"Backup of ","Резервне копіювання "}.
{"Backup to File at ","Резервне копіювання в файл на "}.
{"Backup","Резервне копіювання"}.
{"Bad format","Неправильний формат"}.
{"Birthday","День народження"}.
{"Change Password","Змінити пароль"}.
{"Change User Password","Змінити Пароль Користувача"}.
{"Choose a username and password to register with this server","Виберіть назву користувача та пароль для реєстрації на цьому сервері"}.
{"Choose modules to stop","Виберіть модулі, які необхідно зупинити"}.
{"Choose storage type of tables","Оберіть тип збереження таблиць"}.
{"Choose whether to approve this entity's subscription.","Вирішіть, чи задовольнити запит цього об'єкту на підписку"}.
{"City","Місто"}.
{"Commands","Команди"}.
{"Configuration of room ~s","Конфігурація кімнати ~s"}.
{"Configuration","Конфігурація"}.
{"Connected Resources:","Підключені ресурси:"}.
{"Country","Країна"}.
{"CPU Time:","Процесорний час:"}.
{"Database Tables at ","Таблиці бази даних на "}.
{"Database Tables Configuration at ","Конфігурація таблиць бази даних на "}.
{"Database","База даних"}.
{"December","грудня"}.
{"Default users as participants","Зробити користувачів учасниками за замовчуванням"}.
{"Delete message of the day on all hosts","Видалити повідомлення дня на усіх хостах"}.
{"Delete message of the day","Видалити повідомлення дня"}.
{"Delete Selected","Видалити виділені"}.
{"Delete User","Видалити Користувача"}.
{"Delete","Видалити"}.
{"Deliver event notifications","Доставляти сповіщення про події"}.
{"Deliver payloads with event notifications","Доставляти разом з повідомленнями про публікації самі публікації"}.
{"Description:","Опис:"}.
{"Disc only copy","Тільки диск"}.
{"Dump Backup to Text File at ","Копіювання в текстовий файл на "}.
{"Dump to Text File","Копіювання в текстовий файл"}.
{"Edit Properties","Змінити параметри"}.
{"ejabberd MUC module","ejabberd MUC модуль"}.
{"ejabberd Publish-Subscribe module","Модуль ejabberd Публікації-Абонування"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams модуль"}.
{"ejabberd vCard module","ejabberd vCard модуль"}.
{"ejabberd Web Admin","Веб-інтерфейс Адміністрування ejabberd"}.
{"Elements","Елементи"}.
{"Email","Електронна пошта"}.
{"Enable logging","Включити журнал роботи"}.
{"End User Session","Закінчити Сеанс Користувача"}.
{"Enter list of {Module, [Options]}","Введіть перелік такого виду {Module, [Options]}"}.
{"Enter nickname you want to register","Введіть псевдонім, який ви хочете зареєструвати"}.
{"Enter path to backup file","Введіть шлях до резервного файла"}.
{"Enter path to jabberd14 spool dir","Введіть шлях до директорії спула jabberd14"}.
{"Enter path to jabberd14 spool file","Введіть шлях до файла зі спула jabberd14"}.
{"Enter path to text file","Введіть шлях до текстового файла"}.
{"Enter the text you see","Введіть текст, що ви бачите"}.
{"Erlang Jabber Server","Erlang Jabber Server"}.
{"Error","Помилка"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","Експорт даних всіх користувачів сервера до файлу PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","Експорт даних користувачів домена до файлу PIEFXIS (XEP-0227):"}.
{"Family Name","Прізвище"}.
{"February","лютого"}.
{"Fill in fields to search for any matching Jabber User","Заповніть поля для пошуку користувача Jabber"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","Заповніть поля для пошуку користувача Jabber (Додайте * в кінець поля для пошуку підрядка)"}.
{"Friday","П'ятниця"}.
{"From ~s","Від ~s"}.
{"From","Від кого"}.
{"Full Name","Повне ім'я"}.
{"Get Number of Online Users","Отримати Кількість Підключених Користувачів"}.
{"Get Number of Registered Users","Отримати Кількість Зареєстрованих Користувачів"}.
{"Get User Last Login Time","Отримати Час Останнього Підключення Користувача"}.
{"Get User Password","Отримати Пароль Користувача"}.
{"Get User Statistics","Отримати Статистику по Користувачу"}.
{"Groups","Групи"}.
{"Group ","Група "}.
{"has been banned","заборонили вхід в кімнату"}.
{"has been kicked because of an affiliation change","вигнано з кімнати як наслідок зміни ранга"}.
{"has been kicked because of a system shutdown","вигнано з кімнати як наслідок зупинки системи"}.
{"has been kicked because the room has been changed to members-only","вигнано з кімнати тому, що воня стала тільки для учасників"}.
{"has been kicked","вигнали з кімнати"}.
{" has set the subject to: "," встановив(ла) тему: "}.
{"Host","Хост"}.
{"Import Directory","Імпорт з директорії"}.
{"Import File","Імпорт з файла"}.
{"Import user data from jabberd14 spool file:","Імпорт користувачів з файла спула jabberd14:"}.
{"Import User from File at ","Імпортування користувача з файла на "}.
{"Import users data from a PIEFXIS file (XEP-0227):","Імпорт даних користовучів з файлу PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","Імпорт користувачів з діректорії спула jabberd14:"}.
{"Import Users from Dir at ","Імпортування користувача з директорії на "}.
{"Import Users From jabberd14 Spool Files","Імпорт користувачів зі спулу jabberd14"}.
{"Improper message type","Неправильний тип повідомлення"}.
{"Incorrect password","Неправильний пароль"}.
{"Invalid affiliation: ~s","Недопустимий ранг: ~s"}.
{"Invalid role: ~s","Недопустима роль: ~s"}.
{"IP addresses","IP адреси"}.
{"IP","IP"}.
{"is now known as","змінив(ла) им'я на"}.
{"It is not allowed to send private messages of type \"groupchat\"","Не дозволяється надсилати приватні повідомлення типу \"groupchat\""}.
{"It is not allowed to send private messages","Приватні повідомлення не дозволені"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s недопустимий"}.
{"January","січня"}.
{"joins the room","увійшов(ла) в кімнату"}.
{"July","липня"}.
{"June","червня"}.
{"Last Activity","Останнє підключення"}.
{"Last login","Останнє підключення"}.
{"Last month","За останній місяць"}.
{"Last year","За останній рік"}.
{"leaves the room","вийшов(ла) з кімнати"}.
{"Listened Ports at ","Відкриті порти на "}.
{"Listened Ports","Відкриті порти"}.
{"List of modules to start","Список завантажуваних модулів"}.
{"Low level update script","Низькорівневий сценарій поновлення"}.
{"Make participants list public","Зробити список учасників видимим всім"}.
{"Make room captcha protected","Зробити кімнату захищеною капчею"}.
{"Make room members-only","Кімната тільки для зареєтрованых учасників"}.
{"Make room moderated","Зробити кімнату модерованою"}.
{"Make room password protected","Зробити кімнату захищеною паролем"}.
{"Make room persistent","Зробити кімнату постійною"}.
{"Make room public searchable","Зробити кімнату видимою всім"}.
{"March","березня"}.
{"Maximum Number of Occupants","Максимальна кількість учасників"}.
{"Max # of items to persist","Максимальне число збережених публікацій"}.
{"Max payload size in bytes","Максимальний розмір корисного навантаження в байтах"}.
{"May","травня"}.
{"Membership is required to enter this room","В цю конференціию можуть входити тільки її члени"}.
{"Members:","Члени:"}.
{"Memory","Пам'ять"}.
{"Message body","Тіло повідомлення"}.
{"Middle Name","По-батькові"}.
{"Moderator privileges required","Необхідні права модератора"}.
{"moderators only","тільки модераторам"}.
{"Modified modules","Змінені модулі"}.
{"Modules at ","Модулі на "}.
{"Modules","Модулі"}.
{"Module","Модуль"}.
{"Monday","Понеділок"}.
{"Name:","Назва:"}.
{"Name","Назва"}.
{"Never","Ніколи"}.
{"Nickname Registration at ","Реєстрація псевдоніма на "}.
{"Nickname ~s does not exist in the room","Псевдонім ~s в кімнаті відсутній"}.
{"Nickname","Псевдонім"}.
{"No Data","Немає даних"}.
{"Node ID","ID вузла"}.
{"Node not found","Вузол не знайдено"}.
{"Nodes","Вузли"}.
{"Node ","Вузол "}.
{"No limit","Без обмежень"}.
{"None","Немає"}.
{"Not Found","не знайдено"}.
{"Notify subscribers when items are removed from the node","Повідомляти абонентів про видалення публікацій із збірника"}.
{"Notify subscribers when the node configuration changes","Повідомляти абонентів про зміни в конфігурації збірника"}.
{"Notify subscribers when the node is deleted","Повідомляти абонентів про видалення збірника"}.
{"November","листопада"}.
{"Number of occupants","Кількість присутніх"}.
{"Number of online users","Кількість підключених користувачів"}.
{"Number of registered users","Кількість зареєстрованих користувачів"}.
{"October","грудня"}.
{"Offline Messages:","Офлайнові повідомлення:"}.
{"Offline Messages","Офлайнові повідомлення"}.
{"OK","Продовжити"}.
{"Online Users:","Підключені користувачі:"}.
{"Online Users","Підключені користувачі"}.
{"Online","Підключений"}.
{"Only deliver notifications to available users","Доставляти повідомленнями тільки доступним користувачам"}.
{"Only moderators and participants are allowed to change the subject in this room","Тільки модератори та учасники можуть змінювати тему в цій кімнаті"}.
{"Only moderators are allowed to change the subject in this room","Тільки модератори можуть змінювати тему в цій кімнаті"}.
{"Options","Параметри"}.
{"Organization Name","Назва організації"}.
{"Organization Unit","Відділ організації"}.
{"Outgoing s2s Connections:","Вихідні s2s-з'єднання:"}.
{"Outgoing s2s Connections","Вихідні s2s-з'єднання"}.
{"Outgoing s2s Servers:","Вихідні s2s-сервери:"}.
{"Owner privileges required","Необхідні права власника"}.
{"Packet","Пакет"}.
{"Password Verification","Перевірка Пароля"}.
{"Password:","Пароль:"}.
{"Password","Пароль"}.
{"Path to Dir","шлях до директорії"}.
{"Path to File","Шлях до файла"}.
{"Pending","Очікування"}.
{"Period: ","Період"}.
{"Persist items to storage","Зберегати публікації до сховища"}.
{"Ping","Пінг"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","Зауважте, що ця опція відповідає за резервне копіювання тільки вбудованної бази даних Mnesia. Якщо Ви також використовуєте інше сховище для даних (наприклад за допомогою модуля ODBC), то його резервне копіювання потрібно робити окремо."}.
{"Pong","Понг"}.
{"Port","Порт"}.
{"Present real Jabber IDs to","Зробити реальні Jabber ID учасників видимими"}.
{"private, ","приватна, "}.
{"Protocol","Протокол"}.
{"Publish-Subscribe","Опублікувати-Абонувати"}.
{"PubSub subscriber request","Запит на абонування PubSub"}.
{"Purge all items when the relevant publisher goes offline","Видалити всі елементи, коли особа, що їх опублікувала, вимикається від мережі"}.
{"RAM and disc copy","ОЗП та диск"}.
{"RAM copy","ОЗП"}.
{"Raw","необроблений формат"}.
{"Really delete message of the day?","Насправді видалити повідомлення дня?"}.
{"Registered Users:","Зареєстровані користувачі:"}.
{"Registered Users","Зареєстровані користувачі"}.
{"Remote copy","не зберігаеться локально"}.
{"Remove All Offline Messages","Видалити всі офлайнові повідомлення"}.
{"Remove User","Видалити користувача"}.
{"Remove","Видалити"}.
{"Resources","Ресурси"}.
{"Restart Service","Перезапустити Сервіс"}.
{"Restart","Перезапустити"}.
{"Restore Backup from File at ","Відновлення з резервної копії на "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","Відновити з бінарної резервної копії при наступному запуску (потребує менше пам'яті):"}.
{"Restore binary backup immediately:","Відновити з бінарної резервної копії негайно:"}.
{"Restore plain text backup immediately:","Відновити з текстової резервної копії негайно:"}.
{"Restore","Відновлення з резервної копії"}.
{"Room Configuration","Конфігурація кімнати"}.
{"Room description","Опис кімнати"}.
{"Room Occupants","Учасники кімнати"}.
{"Room title","Назва кімнати"}.
{"Roster groups allowed to subscribe","Дозволені для абонування групи ростера"}.
{"Roster of ","Ростер користувача "}.
{"Roster size","Кількість контактів"}.
{"Roster","Ростер"}.
{"RPC Call Error","Помилка виклику RPC"}.
{"Running Nodes","Працюючі вузли"}.
{"~s access rule configuration","Конфігурація правила доступу ~s"}.
{"Saturday","Субота"}.
{"Script check","Перевірка сценарію"}.
{"Search Results for ","Результати пошуку в "}.
{"Search users in ","Пошук користувачів в "}.
{"Send announcement to all online users on all hosts","Надіслати сповіщення всім підключеним користувачам на всіх віртуальних серверах"}.
{"Send announcement to all online users","Надіслати сповіщення всім підключеним користувачам"}.
{"Send announcement to all users on all hosts","Надіслати сповіщення до усіх користувачів на усіх хостах"}.
{"Send announcement to all users","Надіслати сповіщення всім користувачам"}.
{"September","вересня"}.
{"Set message of the day and send to online users","Встановити повідомлення дня та надіслати його підключеним користувачам"}.
{"Set message of the day on all hosts and send to online users","Встановити повідомлення дня на всіх хостах та надійслати його підключеним користувачам"}.
{"Shared Roster Groups","Спільні групи контактів"}.
{"Show Integral Table","Показати інтегральну таблицю"}.
{"Show Ordinary Table","Показати звичайну таблицю"}.
{"Shut Down Service","Вимкнути Сервіс"}.
{"~s invites you to the room ~s","~s запрошує вас до кімнати ~s"}.
{"Specify the access model","Визначити модель доступу"}.
{"Specify the event message type","Вкажіть тип повідомлень зі сповіщеннями про події"}.
{"Specify the publisher model","Умови публікації"}.
{"~s's Offline Messages Queue","Черга офлайнових повідомлень ~s"}.
{"Start Modules at ","Запуск модулів на "}.
{"Start Modules","Запуск модулів"}.
{"Start","Запустити"}.
{"Statistics of ~p","статистика вузла ~p"}.
{"Statistics","Статистика"}.
{"Stop Modules at ","Зупинка модулів на "}.
{"Stop Modules","Зупинка модулів"}.
{"Stopped Nodes","Зупинені вузли"}.
{"Stop","Зупинити"}.
{"Storage Type","Тип таблиці"}.
{"Store binary backup:","Зберегти бінарну резервну копію:"}.
{"Store plain text backup:","Зберегти текстову резервну копію:"}.
{"Subject","Тема"}.
{"Submitted","Відправлено"}.
{"Submit","Відправити"}.
{"Subscriber Address","Адреса абонента"}.
{"Subscription","Підписка"}.
{"Sunday","Неділя"}.
{"That nickname is already in use by another occupant","Псевдонім зайнято кимось з присутніх"}.
{"That nickname is registered by another person","Псевдонім зареєстровано кимось іншим"}.
{"The captcha is valid.","Перевірку капчею закінчено успішно"}.
{"The collections with which a node is affiliated","Колекція, до якої входить вузел"}.
{"the password is","пароль:"}.
{"This participant is kicked from the room because he sent an error message to another participant","Цього учасника було відключено від кімнати через те, що він надіслав помилкове повідомлення іншому учаснику"}.
{"This participant is kicked from the room because he sent an error message","Цього учасника було відключено від кімнати через те, що він надіслав помилкове повідомлення"}.
{"This participant is kicked from the room because he sent an error presence","Цього учасника було відключено від кімнати через те, що він надіслав помилковий статус присутності"}.
{"This room is not anonymous","Ця кімната не анонімна"}.
{"Thursday","Четвер"}.
{"Time delay","Час затримки"}.
{"Time","Час"}.
{"To ~s","До ~s"}.
{"To","Кому"}.
{"Traffic rate limit is exceeded","Швидкість передачі інформації було перевищено"}.
{"Transactions Aborted:","Транзакції відмінені:"}.
{"Transactions Committed:","Транзакції завершені:"}.
{"Transactions Logged:","Транзакції запротокольовані:"}.
{"Transactions Restarted:","Транзакції перезапущені:"}.
{"Tuesday","Вівторок"}.
{"Unable to generate a captcha","Не має можливості сгенерувати капчу"}.
{"Unauthorized","Не авторізован"}.
{"Update message of the day (don't send)","Поновити повідомлення дня (не надсилати)"}.
{"Update message of the day on all hosts (don't send)","Оновити повідомлення дня на всіх хостах (не надсилати)"}.
{"Update plan","План поновлення"}.
{"Update script","Сценарій поновлення"}.
{"Update","Обновити"}.
{"Update ","Поновлення "}.
{"Uptime:","Час роботи:"}.
{"User Management","Управління Користувачами"}.
{"Users Last Activity","Статистика останнього підключення користувачів"}.
{"Users","Користувачі"}.
{"User ","Користувач "}.
{"User","Користувач"}.
{"Validate","Затвердити"}.
{"vCard User Search","Пошук користувачів по vCard"}.
{"Virtual Hosts","віртуальні хости"}.
{"Visitors are not allowed to change their nicknames in this room","Відвідувачам не дозволяється змінювати псевдонім в цій кімнаті"}.
{"Visitors are not allowed to send messages to all occupants","Відвідувачам не дозволяється надсилати повідомлення всім присутнім"}.
{"Wednesday","Середа"}.
{"When to send the last published item","Коли надсилати останній опублікований елемент"}.
{"Whether to allow subscriptions","Дозволити передплату"}.
{"You have been banned from this room","Вам заборонено входити в цю конференцію"}.
{"You must fill in field \"Nickname\" in the form","Вам необхідно заповнити поле \"Псевдонім\" у формі"}.
{"You need an x:data capable client to configure room","Для конфігурування кімнати потрібно використовувати клієнт з підтримкою x:data"}.
{"You need an x:data capable client to register nickname","Для реєстрації псевдоніму необхідно використовувати клієнт з ідтримкою x:data"}.
{"You need an x:data capable client to search","Для пошуку необхідний x:data-придатний клієнт"}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","Ваші повідомлення до ~s блокуються. Для розблокування відвідайте ~s"}.
