% $Id$
% Language: Ukrainian (українська)
% Author: Ruslan Rakhmanin
% Author: Stoune
% Author: Sergei Golovan

% ejabberd_c2s.erl
{"Use of STARTTLS required", "Ви мусите використовувати STARTTLS"}.
{"Replaced by new connection", "Замінено новим з'єднанням"}.

% jlib.hrl
{"No resource provided", "Не вказаний ресурс"}.

% mod_adhoc.erl
{"Commands", "Команди"}.
{"Ping", "Пінг"}.
{"Pong", "Понг"}.

% mod_announce.erl
{"Send announcement to all users on all hosts", "Надіслати сповіщення до усіх користувачів на усіх хостах"}.
{"Set message of the day on all hosts and send to online users", "Встановити повідомлення дня на всіх хостах та надійслати його підключеним користувачам"}.
{"Update message of the day on all hosts (don't send)", "Оновити повідомлення дня на всіх хостах (не надсилати)"}.
{"Delete message of the day on all hosts", "Видалити повідомлення дня на усіх хостах"}.
{"Really delete message of the day?", "Дійсно видалити повідомлення дня"}.
{"Subject", "Тема"}.
{"Message body", "Тіло повідомлення"}.
{"No body provided for announce message", "Тіло оголошення має бути непустим"}.
{"Announcements", "Оголошення"}.
{"Send announcement to all users", "Надіслати оголошення всім користувачам"}.
{"Send announcement to all online users", "Надіслати оголошення всім підключеним користувачам"}.
{"Send announcement to all online users on all hosts", "Надіслати оголошення всім підключеним користувачам на всіх віртуальних серверах"}.
{"Set message of the day and send to online users", "Встановити повідомлення дня та надіслати його підключеним користувачам"}.
{"Update message of the day (don't send)", "Поновити повідомлення дня (не надсилати)"}.
{"Delete message of the day", "Видалити повідомлення дня"}.

% mod_configure.erl
{"Restart Service", "Перезапустити Сервіс"}.
{"Shut Down Service", "Відключити Сервіс"}.
{"Delete User", "Видалити Користувача"}.
{"End User Session", "Закінчити Сеанс Користувача"}.
{"Get User Password", "Отримати Пароль Користувача"}.
{"Change User Password", "Змінити Пароль Користувача"}.
{"Get User Last Login Time", "Отримати Час Останнього Підключення Користувача"}.
{"Get User Statistics", "Отримати Статистику по Користувачу"}.
{"Get Number of Registered Users", "Отримати Кількість Зареєстрованих Користувачів"}.
{"Get Number of Online Users", "Отримати Кількість Підключених Користувачів"}.
{"User Management", "Управління Користувачами"}.
{"Time delay", "Час затримки"}.
{"Password Verification", "Перевірка Пароля"}.
{"Number of registered users", "Кількість Зареєстрованих Користувачів"}.
{"Number of online users", "Кількість Підключених Користувачів"}.
{"Last login", "Останнє підключення"}.
{"Roster size", "Кількість контактів"}.
{"IP addresses", "IP адреси"}.
{"Resources", "Ресурси"}.
{"Database Tables Configuration at ", "Конфігурація таблиць бази даних на "}.
{"Choose storage type of tables", "Оберіть тип збереження таблиць"}.
{"RAM copy", "ОЗП"}.
{"RAM and disc copy", "ОЗП та диск"}.
{"Disc only copy", "тільки диск"}.
{"Remote copy", "не зберігаеться локально"}.
{"Stop Modules at ", "Зупинка модулів на "}.
{"Choose modules to stop", "Виберіть модулі, які необхідно зупинити"}.
{"Start Modules at ", "Запуск модулів на "}.
{"Enter list of {Module, [Options]}", "Введіть перелік такого виду {Module, [Options]}"}.
{"List of modules to start", "Список завантажуваних модулів"}.
{"Backup to File at ", "Резервне копіювання в файл на "}.
{"Enter path to backup file", "Введіть шлях до резервного файла"}.
{"Path to File", "Шлях до файла"}.
{"Restore Backup from File at ", "Відновлення з резервної копії на "}.
{"Dump Backup to Text File at ", "Копіювання в текстовий файл на "}.
{"Enter path to text file", "Введіть шлях до текстового файла"}.
{"Import User from File at ", "Імпортування користувача з файла на "}.
{"Enter path to jabberd1.4 spool file", "Введіть шлях до файла зі спула jabberd1.4"}.
{"Import Users from Dir at ", "Імпортування користувача з директорії на "}.
{"Enter path to jabberd1.4 spool dir", "Введіть шлях до директорії спула jabberd1.4"}.
{"Path to Dir", "шлях до директорії"}.
{"Access Control List Configuration", "Конфігурація списків керування доступом"}.
{"Access control lists", "Списки керування доступом"}.
{"Access Configuration", "Конфігурація доступа"}.
{"Access rules", "Правила доступу"}.
{"Administration of ", "Адміністрування "}.
{"Action on user", "Дія над користувачем"}.
{"Edit Properties", "Змінити параметри"}.
{"Remove User", "Видалити користувача"}.

% mod_disco.erl
{"Configuration", "Конфігурація"}.
{"Online Users", "Підключені користувачі"}.
{"All Users", "Всі користувачі"}.
{"Outgoing s2s Connections", "Вихідні s2s-з'єднання"}.
{"To ~s", "До ~s"}.
{"From ~s", "Від ~s"}.
{"Running Nodes", "Працюючі вузли"}.
{"Stopped Nodes", "Зупинені вузли"}.
{"Access Control Lists", "Списки керування доступом"}.
{"Access Rules", "Правила доступу"}.
{"Database", "База даних"}.
{"Modules", "Модулі"}.
{"Start Modules", "Запуск модулів"}.
{"Stop Modules", "Зупинка модулів"}.
{"Backup Management", "Керування резервним копіюванням"}.
{"Import Users From jabberd 1.4 Spool Files", "Імпорт користувачів зі спулу jabberd 1.4"}.
{"Backup", "Резервне копіювання"}.
{"Restore", "Відновлення з резервної копії"}.
{"Dump to Text File", "Копіювання в текстовий файл"}.
{"Import File", "Імпорт з файла"}.
{"Import Directory", "Імпорт з директорії"}.

% mod_proxy65.erl

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "ejabberd SOCKS5 Bytestreams модуль"}.

% mod_register.erl
{"Users are not allowed to register accounts so fast", "Користувачам не дозволено так часто реєструвати облікові записи"}.
{"Choose a username and password to register with this server", "Виберіть назву користувача та пароль для реєстрації на цьому сервері"}.

% mod_vcard.erl
{"Erlang Jabber Server", "Erlang Jabber Server"}.
{"ejabberd vCard module", "ejabberd vCard модуль"}.
{"You need an x:data capable client to search", "Для пошуку необхідний x:data-придатний клієнт"}.
{"Search users in ", "Пошук користувачів в "}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Заповніть поля для пошуку користувача Jabber (Додайте * в кінець поля для пошуку підрядка)"}.
{"Search Results for ", "Результати пошуку в "}.
{"Jabber ID",         "Jabber ID"}.
{"User",              "Користувач"}.
{"Full Name", 	      "Повне ім'я"}.
{"Name", 	      "Ім'я"}.
{"Middle Name",       "По-батькові"}.
{"Family Name",       "Прізвище"}.
{"Nickname", 	      "Псевдонім"}.
{"Birthday", 	      "День народження"}.
{"Country", 	      "Країна"}.
{"City", 	      "Місто"}.
{"Email", 	      "Електронна пошта"}.
{"Organization Name", "Назва організації"}.
{"Organization Unit", "Відділ організації"}.

% mod_vcard_ldap.erl
{"Fill in fields to search for any matching Jabber User", "Заповніть поля для пошуку користувача Jabber"}.

% mod_pubsub/mod_pubsub.erl
{"A friendly name for the node", "Псевдонім для вузла"}.
{"Roster groups allowed to subscribe", "Дозволені для абонування групи ростера"}.
{"Publish-Subscribe", "Опублікувати-Абонувати"}.
{"ejabberd Publish-Subscribe module", "Модуль ejabberd Публікації-Абонування"}.
{"PubSub subscriber request", "Запит на абонування PubSub"}.
{"Choose whether to approve this entity's subscription.", "Вирішіть, чи задовольнити запит цього об'єкту на підписку"}.
{"Node ID", "ID вузла"}.
{"Subscriber Address", "Адреса абонента"}.
{"Allow this JID to subscribe to this pubsub node?", "Чи дозволити цьому JID абонувати новини наданого вузла"}.
{"Deliver event notifications", "Доставляти сповіщення про події"}.
{"Specify the access model", "Визначити модель доступу"}.
{"When to send the last published item", "Коли надсилати останній опублікований елемент"}.
{"Deliver payloads with event notifications", "Доставляти разом з повідомленнями про публікації самі публікації"}.
{"Notify subscribers when the node configuration changes", "Повідомляти абонентів про зміни в конфігурації збірника"}.
{"Notify subscribers when the node is deleted", "Повідомляти абонентів про видалення збірника"}.
{"Notify subscribers when items are removed from the node", "Повідомляти абонентів про видалення публікацій із збірника"}.
{"Persist items to storage", "Зберегати публікації до сховища"}.
{"Max # of items to persist", "Максимальне число збережених публікацій"}.
{"Whether to allow subscriptions", "Дозволити передплату"}.
{"Specify the publisher model", "Умови публікації"}.
{"Max payload size in bytes", "Максимальний розмір корисного навантаження в байтах"}.
{"Only deliver notifications to available users", "Доставляти повідомленнями тільки доступним користувачам"}.

% mod_muc/mod_muc.erl
{"Chatrooms", "Кімнати"}.
{"You need an x:data capable client to register nickname", "Для реєстрації псевдоніму необхідний x:data-придатний клієнт"}.
{"Nickname Registration at ", "Реєстрація псевдоніма на "}.
{"Enter nickname you want to register", "Введіть псевдонім, який ви хочете зареєструвати"}.
{"ejabberd MUC module", "ejabberd MUC модуль"}.
{"Only service administrators are allowed to send service messages", "Тільки адміністратор сервісу може надсилати службові повідомлення"}.
{"Room creation is denied by service policy", "Створювати конференцію заборонено політикою служби"}.
{"Conference room does not exist", "Конференція не існує"}.
{"Access denied by service policy", "Доступ заборонений політикою служби"}.
{"You must fill in field \"Nickname\" in the form", "Вам необхідно заповнити поле \"Псевдонім\" у формі"}.
{"Specified nickname is already registered", "Вказаний псевдонім вже зареєстрований"}.

% /home/sergei/src/ejabberd/ejabberd/src/mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "вигнано з кімнати як наслідок зміни ранга"}.
{"has been kicked because the room has been changed to members-only", "вигнано з кімнати тому, що воня стала тільки для учасників"}.
{"has been kicked because of a system shutdown", "вигнано з кімнати як наслідок зупинки системи"}.
{"Chatroom configuration modified", "Конфігурація кімнати змінилась"}.
{"joins the room", "увійшов(ла) в кімнату"}.
{"leaves the room", "вийшов(ла) з кімнати"}.
{"has been kicked", "вигнали з кімнати"}.
{"has been banned", "заборонили вхід в кімнату"}.
{"is now known as", "змінив(ла) им'я на"}.
{"Monday", "Понеділок"}.
{"Tuesday", "Вівторок"}.
{"Wednesday", "Середа"}.
{"Thursday", "Четвер"}.
{"Friday", "П'ятниця"}.
{"Saturday", "Субота"}.
{"Sunday", "Неділя"}.
{"January", "січня"}.
{"February", "лютого"}.
{"March", "березня"}.
{"April", "квітня"}.
{"May", "травня"}.
{"June", "червня"}.
{"July", "липня"}.
{"August", "серпня"}.
{"September", "вересня"}.
{"October", "грудня"}.
{"November", "листопада"}.
{"December", "грудня"}.
{"Room Configuration", "Конфігурація кімнати"}.

% mod_muc/mod_muc_room.erl
{"It is not allowed to send private messages", "Приватні повідомлення не дозволені"}.
{"Visitors are not allowed to change their nicknames in this room", "Відвідувачам не дозволяється змінювати псевдонім в цій кімнаті"}.
{"Allow visitors to send status text in presence updates", "Дозволити відвідувачам відсилати текст статусу в оновленнях присутності"}.
{"Allow visitors to change nickname", "Дозволити відвідувачам змінювати псевдонім"}.
{"This participant is kicked from the room because he sent an error message", "Цього учасника було відключено від кімнати через те, що він надіслав помилкове повідомлення"}.
{"This participant is kicked from the room because he sent an error message to another participant", "Цього учасника було відключено від кімнати через те, що він надіслав помилкове повідомлення іншому учаснику"}.
{"This participant is kicked from the room because he sent an error presence", "Цього учасника було відключено від кімнати через те, що він надіслав помилковий статус присутності"}.
{"Make room moderated", "Зробити кімнату модерованою"}.
{"Traffic rate limit is exceeded", "Швидкість передачі інформації було перевищено"}.
{"Maximum Number of Occupants", "Максимальна кількість учасників"}.
{"No limit", "Без обмежень"}.
{"~s invites you to the room ~s", "~s запрошує вас до кімнати ~s"}.
{"the password is", "пароль:"}.
{" has set the subject to: ", " встановив(ла) тему: "}.
{"This room is not anonymous", "Ця кімната не анонімна"}.
{"You need an x:data capable client to configure room", "Для конфігурування кімнати необхідний x:data-придатний кліент"}.
{"Configuration for ", "Конфігурація "}.
{"Room title", "Назва кімнати"}.
{"Allow users to change subject", "Дозволити користувачам змінювати тему"}.
{"Allow users to query other users", "Дозволити iq-запити до користувачів"}.
{"Allow users to send private messages", "Дозволити приватні повідомлення"}.
{"Make room public searchable", "Зробити кімнату видимою всім"}.
{"Make participants list public", "Зробити список учасників видимим всім"}.
{"Make room persistent", "Зробити кімнату постійною"}.
{"Make
 room moderated", "Зробити кімнату модерованою"}.
{"Default users as participants", "Зробити користувачів учасниками за замовчуванням"}.
{"Make room members-only", "Кімната тільки для зареєтрованых учасників"}.
{"Allow users to send invites", "Дозволити користувачам надсилати запрошення"}.
{"Make room password protected", "Зробити кімнату захищеною паролем"}.
{"Password", "Пароль"}.
{"Present real JIDs to", "Зробити реальні JID учасників видимими"}.
{"moderators only", "тільки модераторам"}.
{"anyone", "всім учасникам"}.
{"Enable logging", "Включити журнал роботи"}.
{"Only moderators and participants are allowed to change subject in this room", "Тільки модератори та учасники можуть змінювати тему в цій кімнаті"}.
{"Only moderators are allowed to change subject in this room", "Тільки модератори можуть змінювати тему в цій кімнаті"}.
{"Visitors are not allowed to send messages to all occupants", "Відвідувачам не дозволяється надсилати повідомлення всім присутнім"}.
{"Only occupants are allowed to send messages to the conference", "Тільки присутнім дозволяється надсилати повідомленняя в конференцію"}.
{"It is not allowed to send private messages to the conference", "Не дозволяється надсилати приватні повідомлення  в конференцію"}.
{"Improper message type", "Неправильний тип повідомлення"}.
{"Nickname is already in use by another occupant", "Псевдонім зайнятий кимось з присутніх"}.
{"Nickname is registered by another person", "Псевдонім зареєстрований кимось іншим"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Не дозволяється надсилати приватні повідомлення типу \"groupchat\""}.
{"Recipient is not in the conference room", "Адресата немає в конференції"}.
{"Only occupants are allowed to send queries to the conference", "Тільки присутнім дозволяється відправляти запити в конференцію"}.
{"Queries to the conference members are not allowed in this room", "Запити до користувачів в цій конференції зоборонені"}.
{"You have been banned from this room", "Вам заборонено входити в цю конференцію"}.
{"Membership required to enter this room", "В цю конференціию можуть входити тільки її члени"}.
{"Password required to enter this room", "Щоб зайти в цю конференцію, необхідний пароль"}.
{"Incorrect password", "Неправильний пароль"}.
{"Administrator privileges required", "Необхідні права адміністратора"}.
{"Moderator privileges required", "Необхідні права модератора"}.
{"JID ~s is invalid", "JID ~s недопустимий"}.
{"Nickname ~s does not exist in the room", "Псевдонім ~s в кімнаті відсутній"}.
{"Invalid affiliation: ~s", "Недопустимий ранг: ~s"}.
{"Invalid role: ~s", "Недопустима роль: ~s"}.
{"Owner privileges required", "Необхідні права власника"}.
{"private, ", "приватна, "}.
{"Number of occupants", "Кількість присутніх"}.

% mod_irc/mod_irc.erl
{"IRC Transport", "IRC Транспорт"}.
{"ejabberd IRC module", "ejabberd IRC модуль"}.
{"You need an x:data capable client to configure mod_irc settings", "Для налагодження параметрів mod_irc необхідний x:data-придатний клієнт"}.
{"Registration in mod_irc for ", "Реєстрація в mod_irc для "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Введіть ім'я користувача та кодування, які будуть використовуватися при підключенні до IRC-серверів"}.
{"IRC Username", "Ім'я користувача IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Щоб вказати різні кодування для різних серверів IRC, заповніть список значеннями в форматі '{\"irc server\", \"encoding\"}'. За замовчуванням ця служба використовує кодування \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Приклад: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Кодування"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "Веб-інтерфейс Адміністрування ejabberd"}.
{"Administration", "Адміністрування"}.
{"Users", "Користувачі"}.
{"Nodes", "Вузли"}.
{"Statistics", "Статистика"}.
{"(Raw)", "(Необроблений формат)"}.
{"Submitted", "Відправлено"}.
{"Bad format", "Неправильний формат"}.
{"Raw", "необроблений формат"}.
{"Delete Selected", "Видалити виділені"}.
{"Submit", "Відправити"}.
{"~s access rule configuration", "Конфігурація правила доступу ~s"}.
{"Node not found", "Вузол не знайдено"}.
{"Add New", "Додати"}.
{"Registered Users", "Зареєстровані користувачі"}.
{"Registered Users:", "Зареєстровані користувачі:"}.
{"Online Users", "Підключені користувачі"}.
{"Online Users:", "Підключені користувачі:"}.
{"Outgoing s2s Connections:", "Вихідні s2s-з'єднання:"}.
{"Outgoing s2s Servers:", "Вихідні s2s-сервери:"}.
{"Change Password", "Змінити пароль"}.
{"Connected Resources:", "Підключені ресурси:"}.
{"Password:", "Пароль:"}.
{"None", "Немає"}.
{"Node ", "Вузол "}.
{"Listened Ports", "Відкриті порти"}.
{"Restart", "Перезапустити"}.
{"Stop", "Зупинити"}.
{"RPC Call Error", "Помилка виклику RPC"}.
{"Database Tables at ", "Таблиці бази даних на "}.
{"Name", "Назва"}.
{"Storage Type", "Тип таблиці"}.
{"Size", "Розмір"}.
{"Memory", "Пам'ять"}.
{"Backup of ", "Резервне копіювання "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Зауважте, що тут відбувається резервне копіювання тільки вбудованної бази даних Mnesia. Якщо Ви також використовуєте інше сховище для даних (наприклад за допомогою модуля ODBC), то його резервне копіювання потрібно робити окремо."}.
{"Store binary backup:", "Зберегти бінарну резервну копію:"}.
{"OK", "Продовжити"}.
{"Restore binary backup immediately:", "Відновити з бінарної резервної копії негайно:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Відновити з бінарної резервної копії при наступному запуску (потребує менше пам'яті):"}.
{"Store plain text backup:", "Зберегти текстову резервну копію:"}.
{"Restore plain text backup immediately:", "Відновити з текстової резервної копії негайно:"}.
{"Listened Ports at ", "Відкриті порти на "}.
{"Statistics of ~p", "статистика вузла ~p"}.
{"Uptime:", "Час роботи:"}.
{"CPU Time:", "Процесорний час:"}.
{"Transactions Commited:", "Транзакції завершені:"}.
{"Transactions Aborted:", "Транзакції відмінені:"}.
{"Transactions Restarted:", "Транзакції перезапущені:"}.
{"Transactions Logged:", "Транзакції запротокольовані:"}.
{"Update ", "Поновлення "}.
{"Update plan", "План поновлення"}.
{"Updated modules", "Поновлені модулі"}.
{"Update script", "Сценарій поновлення"}.
{"Low level update script", "Низькорівневий сценарій поновлення"}.
{"Script check", "Перевірка сценарію"}.
{"Port", "Порт"}.
{"Module", "Модуль"}.
{"Options", "Параметри"}.
{"Update", "Обновити"}.
{"Delete", "Видалити"}.
{"Add User", "Додати користувача"}.
{"Offline Messages", "Офлайнові повідомлення"}.
{"Offline Messages:", "Офлайнові повідомлення:"}.
{"Last Activity", "Останнє підключення"}.
{"Never", "Ніколи"}.
{"~s's Offline Messages Queue", "Черга офлайнових повідомлень ~s"}.
{"Time", "Час"}.
{"From", "Від кого"}.
{"To", "Кому"}.
{"Packet", "Пакет"}.
{"Roster", "Ростер"}.
{"Nickname", "Псевдонім"}.
{"Subscription", "Підписка"}.
{"Pending", "Очікування"}.
{"Groups", "Групи"}.
{"Remove", "Видалити"}.
{"Add Jabber ID", "Додати Jabber ID"}.
{"User ", "Користувач "}.
{"Roster of ", "Ростер користувача "}.
{"Online", "Підключений"}.
{"Validate", "Затвердити"}.
{"Shared Roster Groups", "Спільні групи контактів"}.
{"Name:", "Назва:"}.
{"Description:", "Опис:"}.
{"Members:", "Члени:"}.
{"Displayed Groups:", "Видимі групи:"}.
{"Group ", "Група "}.
{"Users Last Activity", "Статистика останнього підключення користувачів"}.
{"Period: ", "Період"}.
{"Last month", "За останній місяць"}.
{"Last year", "За останній рік"}.
{"All activity", "Вся статистика"}.
{"Show Ordinary Table", "Показати звичайну таблицю"}.
{"Show Integral Table", "Показати інтегральну таблицю"}.
{"Start", "Запустити"}.
{"Modules at ", "Модулі на "}.
{"No Data", "Немає даних"}.
{"Virtual Hosts", "Віртуальні хости"}.
{"ejabberd virtual hosts", "віртуальні хости ejabberd"}.
{"Host", "Хост"}.

% mod_vcard_odbc.erl
{"vCard User Search", "Пошук користувачів по vCard"}.

% mod_offline_odbc.erl
{"Your contact offline message queue is full. The message has been discarded.", "Черга повідомлень, що не були доставлені, переповнена. Повідомлення не було збережено."}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
