% $Id$				
% Language: Vietnamese (tiếng việt)
% Author: EQHO Communications (Thailand) Ltd. - http://www.eqho.com

% mod_vcard_odbc.erl				
{"Erlang Jabber Server", "Erlang Jabber Server Bản quyền"}.
{"You need an x:data capable client to search", "Bạn cần có một trình ứng dụng khách hỗ trợ định dạng dữ liệu x: để tìm kiếm"}.
{"Search users in ", "Tìm kiếm người sử dụng trong"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Điền vào mẫu này để tìm kiếm bất kỳ thông tin nào khớp với Người sử dụng Jabber (Thêm dấu * vào cuối ô để thông tin khớp với chuỗi bên trong)"}.
{"User", "Người sử dụng"}.
{"Full Name", "Tên Đầy Đủ"}.
{"Name", "Tên"}.
{"Middle Name", "Họ Đệm"}.
{"Family Name", "Họ"}.
{"Nickname", "Bí danh"}.
{"Birthday", "Ngày sinh"}.
{"Country", "Quốc gia"}.
{"City", "Thành phố"}.
{"Email", "Email"}.
{"Organization Name", "Tên Tổ Chức"}.
{"Organization Unit", "Bộ Phận"}.
{"vCard User Search", "Tìm Kiếm Người Sử Dụng vCard"}.
{"ejabberd vCard module", "Môdun ejabberd vCard Bản quyền"}.
{"Search Results for ", "Kết Quả Tìm Kiếm cho "}.
{"Jabber ID", "Jabber ID"}.

% mod_roster.erl				
{"None", "Không có"}.
{"Subscription", "Đăng ký"}.
{"Pending", "Chờ"}.
{"Groups", "Nhóm"}.
{"Validate", "Xác nhận hợp lệ"}.
{"Remove", "Gỡ bỏ"}.
{"Roster of ", "Bảng phân công của "}.
{"Submitted", "Đã gửi"}.
{"Bad format", "Định dạng hỏng"}.
{"Add Jabber ID", "Thêm Jabber ID"}.
{"Roster", "Bảng phân công"}.

% mod_offline_odbc.erl				
{"Your contact offline message queue is full. The message has been discarded.", "Danh sách chờ thư liên lạc ngoại tuyến của bạn đã đầy. Thư này đã bị loại bỏ."}.
{"~s's Offline Messages Queue", "~s's Danh Sách Chờ Thư Ngoại Tuyến"}.
{"Packet", "Gói thông tin"}.
{"Delete Selected", "Tùy chọn Xóa được Chọn"}.
{"Offline Messages:", "Thư Ngoại Tuyến:"}.

% ejabberd_c2s.erl				
{"Use of STARTTLS required", "Yêu cầu sử dụng STARTTLS"}.
{"No resource provided", "Không có nguồn lực cung cấp"}.
{"Replaced by new connection", "Được thay thế bởi kết nối mới"}.

% mod_register.erl				
{"Choose a username and password to register with this server", "Chọn một tên truy cập và mật khẩu để đăng ký với máy chủ này"}.

% mod_vcard_ldap.erl				
{"Fill in fields to search for any matching Jabber User", "Điền vào các ô để tìm kiếm bất kỳ các thông tin nào khớp với Người sử dụng Jabber"}.

% mod_proxy65/mod_proxy65_service.erl				
{"ejabberd SOCKS5 Bytestreams module", "Môdun SOCKS5 Bytestreams Bản quyền"}.

% mod_shared_roster.erl				
{"Add New", "Thêm Mới"}.
{"Shared Roster Groups", "Nhóm Phân Công Chia Sẻ"}.
{"Name:", "Tên:"}.
{"Description:", "Miêu tả:"}.
{"Members:", "Thành viên:"}.
{"Displayed Groups:", "Nhóm được hiển thị:"}.
{"Group ", "Nhóm "}.
{"Submit", "Gửi"}.

% mod_announce.erl				
{"Really delete message of the day?", "Có thực sự xóa thư trong ngày này không?"}.
{"Subject", "Tiêu đề"}.
{"Message body", "Thân thư"}.
{"No body provided for announce message", "Không có nội dung trong thư thông báo"}.
{"Announcements", "Thông báo"}.
{"Send announcement to all users", "Gửi thông báo đến tất cả người sử dụng"}.
{"Send announcement to all users on all hosts", "Gửi thông báo đến tất cả người sử dụng trên tất cả các máy chủ"}.
{"Send announcement to all online users", "Gửi thông báo đến tất cả người sử dụng trực tuyến"}.
{"Send announcement to all online users on all hosts", "Gửi thông báo đến tất cả người sử dụng trực tuyến trên tất cả các máy chủ"}.
{"Set message of the day and send to online users", "Tạo lập thư trong ngày và gửi đến những người sử dụng trực tuyến"}.
{"Set message of the day on all hosts and send to online users", "Tạo lập thư trong ngày trên tất cả các máy chủ và gửi đến những người sử dụng trực tuyến"}.
{"Update message of the day (don't send)", "Cập nhật thư trong ngày (không gửi)"}.
{"Update message of the day on all hosts (don't send)", "Cập nhật thư trong ngày trên tất cả các máy chủ (không gửi)"}.
{"Delete message of the day", "Xóa thư trong ngày"}.
{"Delete message of the day on all hosts", "Xóa thư trong ngày trên tất cả các máy chủ"}.

% mod_adhoc.erl				
{"Commands", "Lệnh"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_irc/mod_irc.erl				
{"Access denied by service policy", "Sự truy cập bị chặn theo chính sách phục vụ"}.
{"IRC Transport", "Truyền tải IRC"}.
{"ejabberd IRC module", "Môdun ejabberd IRC Bản quyền"}.
{"You need an x:data capable client to configure mod_irc settings", "Bạn cần có một trình ứng dụng khách hỗ trợ định dạng dữ liệu x: để xác định các thiết lập mod_irc"}.
{"Registration in mod_irc for ", "Đăng ký trong mod_irc cho "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Nhập tên truy cập và mã hóa mà bạn muốn sử dụng khi kết nối với các máy chủ IRC"}.
{"IRC Username", "Tên truy cập IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Nếu bạn muốn xác định các cách thức mã hóa khác nhau cho các máy chủ IRC, hãy điền vào danh sách này những giá trị theo định dạng '{\"máy chủ irc\", \"mã hóa\"}'. Dịch vụ này mặc định sử dụng định dạng mã hóa \"~s\"."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Ví dụ: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]"}.
{"Encodings", "Mã hóa"}.

% mod_configure.erl				
{"Configuration", "Cấu hình"}.
{"Database", "Cơ sở dữ liệu"}.
{"Start Modules", "Môđun Khởi Động"}.
{"Stop Modules", "Môđun Dừng"}.
{"Backup", "Sao lưu dự phòng"}.
{"Restore", "Khôi phục"}.
{"Dump to Text File", "Kết xuất ra Tập Tin Văn Bản"}.
{"Import File", "Nhập Tập Tin"}.
{"Import Directory", "Nhập Thư Mục"}.
{"Restart Service", "Khởi Động Lại Dịch Vụ"}.
{"Shut Down Service", "Tắt Dịch Vụ"}.
{"Add User", "Thêm Người Sử Dụng"}.
{"Delete User", "Xóa Người Sử Dụng"}.
{"End User Session", "Kết Thúc Phiên Giao Dịch Người Sử Dụng"}.
{"Get User Password", "Nhận Mật Khẩu Người Sử Dụng"}.
{"Change User Password", "Thay Đổi Mật Khẩu Người Sử Dụng"}.
{"Get User Last Login Time", "Nhận Thời Gian Đăng Nhập Cuối Cùng Của Người Sử Dụng"}.
{"Get User Statistics", "Nhận Thông Tin Thống Kê Người Sử Dụng"}.
{"Get Number of Registered Users", "Nhận Số Người Sử Dụng Đã Đăng Ký"}.
{"Get Number of Online Users", "Nhận Số Người Sử Dụng Trực Tuyến"}.
{"Access Control Lists", "Danh Sách Kiểm Soát Truy Cập"}.
{"Access Rules", "Quy Tắc Truy Cập"}.
{"User Management", "Quản Lý Người Sử Dụng"}.
{"Online Users", "Người Sử Dụng Trực Tuyến"}.
{"All Users", "Tất Cả Người Sử Dụng"}.
{"Outgoing s2s Connections", "Kết Nối Bên Ngoài s2s"}.
{"Running Nodes", "Nút Hoạt Động"}.
{"Stopped Nodes", "Nút Dừng"}.
{"Modules", "Môđun"}.
{"Backup Management", "Quản lý Sao Lưu Dự Phòng"}.
{"Import Users From jabberd 1.4 Spool Files", "Nhập Người Sử Dụng Từ Các Tập Tin Spool jabberd 1,4"}.
{"To ~s", "Gửi đến ~s"}.
{"From ~s", "Nhận từ ~s"}.
{"Database Tables Configuration at ", "Cấu Hình Bảng Cơ Sở Dữ Liệu tại"}.
{"Choose storage type of tables", "Chọn loại bảng lưu trữ"}.
{"RAM copy", "Sao chép vào RAM"}.
{"RAM and disc copy", "Sao chép vào RAM và đĩa"}.
{"Disc only copy", "Chỉ sao chép vào đĩa"}.
{"Remote copy", "Sao chép từ xa"}.
{"Stop Modules at ", "Môđun Dừng tại"}.
{"Choose modules to stop", "Chọn môđun để dừng"}.
{"Start Modules at ", "Môđun Khởi Động tại "}.
{"Enter list of {Module, [Options]}", "Nhập danh sách {Môđun, [Các Tùy Chọn]}"}.
{"List of modules to start", "Danh sách các môđun khởi động"}.
{"Backup to File at ", "Sao lưu dự phòng ra Tập Tin tại"}.
{"Enter path to backup file", "Nhập đường dẫn đến tập tin sao lưu dự phòng"}.
{"Path to File", "Đường dẫn đến Tập Tin"}.
{"Restore Backup from File at ", "Phục hồi Sao Lưu từ Tập Tin tại "}.
{"Dump Backup to Text File at ", "Kết Xuất Sao Lưu ra Tập Tin Văn Bản tại"}.
{"Enter path to text file", "Nhập đường dẫn đến tập tin văn bản"}.
{"Import User from File at ", "Nhập Người Sử Dụng từ Tập Tin tại"}.
{"Enter path to jabberd1.4 spool file", "Nhập đường dẫn đến tập tin spool jabberd1,4"}.
{"Import Users from Dir at ", "Nhập Người Sử Dụng từ Thư Mục tại"}.
{"Enter path to jabberd1.4 spool dir", "Nhập đường dẫn đến thư mục spool jabberd1,4"}.
{"Path to Dir", "Đường Dẫn đến Thư Mục"}.
{"Time delay", "Thời gian trì hoãn"}.
{"Access Control List Configuration", "Cấu Hình Danh Sách Kiểm Soát Truy Cập"}.
{"Access control lists", "Danh sách kiểm soát truy cập"}.
{"Access Configuration", "Cấu Hình Truy Cập"}.
{"Access rules", "Quy tắc Truy Cập"}.
{"Password", "Mật Khẩu"}.
{"Password Verification", "Kiểm Tra Mật Khẩu"}.
{"Number of registered users", "Số người sử dụng đã đăng ký"}.
{"Number of online users", "Số người sử dụng trực tuyến"}.
{"Never", "Không bao giờ"}.
{"Online", "Trực tuyến"}.
{"Last login", "Đăng nhập lần cuối"}.
{"Roster size", "Kích thước bảng phân công"}.
{"IP addresses", "Địa chỉ IP"}.
{"Resources", "Nguồn tài nguyên"}.
{"Administration of ", "Quản trị về "}.
{"Action on user", "Hành động đối với người sử dụng"}.
{"Edit Properties", "Chỉnh Sửa Thuộc Tính"}.
{"Remove User", "Gỡ Bỏ Người Sử Dụng"}.

% mod_pubsub/mod_pubsub.erl				
{"Publish-Subscribe", "Xuất Bản-Đăng Ký"}.
{"ejabberd Publish-Subscribe module", "Môdun ejabberd Xuất Bản-Đăng Ký Bản quyền"}.
{"PubSub subscriber request", "Yêu cầu người đăng ký môđun Xuất Bản Đăng Ký"}.
{"Choose whether to approve this entity's subscription.", "Chọn có nên chấp nhận sự đăng ký của đối tượng này không"}.
{"Node ID", "ID Nút"}.
{"Subscriber Address", "Địa Chỉ Người Đăng Ký"}.
{"Allow this JID to subscribe to this pubsub node?", "Cho phép JID đăng ký nút môđun xuất bản đăng ký này không?"}.
{"Deliver payloads with event notifications", "Đưa ra thông tin dung lượng với các thông báo sự kiện"}.
{"Deliver event notifications", "Đưa ra các thông báo sự kiện"}.
{"Notify subscribers when the node configuration changes", "Thông báo cho người đăng ký khi nào cấu hình nút thay đổi"}.
{"Notify subscribers when the node is deleted", "Thông báo cho người đăng ký khi nào nút bị xóa bỏ"}.
{"Notify subscribers when items are removed from the node", "Thông báo cho người đăng ký khi nào các mục chọn bị gỡ bỏ khỏi nút"}.
{"Persist items to storage", "Những mục cần để lưu trữ"}.
{"Max # of items to persist", "Số mục tối đa để lưu trữ"}.
{"Whether to allow subscriptions", "Xác định nên cho phép đăng ký không"}.
{"Specify the access model", "Xác định mô hình truy cập"}.
{"Roster groups that may subscribe (if access model is roster)", "Các nhóm phân công có thể đăng ký (nếu mô hình truy cập là dạng phân công)"}.
{"Specify the publisher model", "Xác định mô hình nhà xuất bản"}.
{"Max payload size in bytes", "Kích thước dung lượng byte tối đa"}.
{"When to send the last published item", "Khi cần gửi mục được xuất bản cuối cùng"}.
{"Only deliver notifications to available users", "Chỉ gửi thông báo đến những người sử dụng hiện có"}.

% web/ejabberd_web_admin.erl				
{"ejabberd Web Interface", "Giao diện Web ejabberd"}.
{"Administration", "Quản trị"}.
{"Virtual Hosts", "Máy Chủ Ảo"}.
{"Nodes", "Nút"}.
{"Statistics", "Số liệu thống kê"}.
{"Users", "Người sử dụng"}.
{"Last Activity", "Hoạt Động Cuối Cùng"}.
{"(Raw)", "(Thô)"}.
{"Raw", "Thô"}.
{"~s access rule configuration", "~s cấu hình quy tắc truy cập"}.
{"ejabberd virtual hosts", "Máy chủ ảo ejabberd"}.
{"Users Last Activity", "Hoạt Động Cuối Cùng Của Người Sử Dụng"}.
{"Period: ", "Giai đoạn: "}.
{"Last month", "Tháng trước"}.
{"Last year", "Năm trước"}.
{"All activity", "Tất cả hoạt động"}.
{"Show Ordinary Table", "Hiển Thị Bảng Thường"}.
{"Show Integral Table", "Hiển Thị Bảng Đầy Đủ"}.
{"Node not found", "Nút không tìm thấy"}.
{"Host", "Máy chủ"}.
{"Registered Users", "Người Sử Dụng Đã Đăng Ký"}.
{"Offline Messages", "Thư Ngoại Tuyến"}.
{"Registered Users:", "Người Sử Dụng Đã Đăng Ký:"}.
{"Online Users:", "Người Sử Dụng Trực Tuyến:"}.
{"Outgoing s2s Connections:", "Kết Nối Bên Ngoài s2s:"}.
{"Outgoing s2s Servers:", "Máy chủ Bên Ngoài s2s:"}.
{"Change Password", "Thay Đổi Mật Khẩu"}.
{"User ", "Người sử dụng "}.
{"Connected Resources:", "Tài Nguyên Được Kết Nối:"}.
{"Password:", "Mật Khẩu:"}.
{"No Data", "Không Dữ Liệu"}.
{"Node ", "Nút "}.
{"Listened Ports", "Cổng Kết Nối"}.
{"Update", "Cập Nhật"}.
{"Restart", "Khởi động lại"}.
{"Stop", "Dừng"}.
{"RPC Call Error", "Lỗi Gọi RPC"}.
{"Database Tables at ", "Bảng Cơ Sở Dữ Liệu tại"}.
{"Storage Type", "Loại Lưu Trữ"}.
{"Size", "Kích thước"}.
{"Memory", "Bộ Nhớ"}.
{"Backup of ", "Sao lưu dự phòng về"}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Lưu ý rằng những tùy chọn này sẽ chỉ được sao lưu cơ sở dữ liệu bên trong Mnesia. Nếu bạn đang sử dụng môđun ODBC, bạn cũng cần sao lưu cơ sở dữ liệu SQL của bạn riêng biệt."}.
{"Store binary backup:", "Lưu dữ liệu sao lưu dạng nhị phân:"}.
{"OK", "OK"}.
{"Restore binary backup immediately:", "Khôi phục bản sao lưu dự phòng dạng nhị phận ngay lập tức:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Khôi phục bản sao lưu dự phòng dạng nhị phân sau lần khởi động ejabberd kế tiếp (yêu cầu ít bộ nhớ hơn):"}.
{"Store plain text backup:", "Khôi phục bản sao lưu dự phòng thuần văn bản"}.
{"Restore plain text backup immediately:", "Khôi phục bản sao lưu dự phòng thuần văn bản ngay lập tức:"}.
{"Listened Ports at ", "Cổng Liên Lạc tại"}.
{"Modules at ", "Môđun tại "}.
{"Statistics of ~p", "Thống kê về ~p"}.
{"Uptime:", "Thời gian tải lên:"}.
{"CPU Time:", "Thời Gian CPU:"}.
{"Transactions Commited:", "Giao Dịch Được Cam Kết:"}.
{"Transactions Aborted:", "Giao Dịch Hủy Bỏ:"}.
{"Transactions Restarted:", "Giao Dịch Khởi Động Lại:"}.
{"Transactions Logged:", "Giao Dịch Được Ghi Nhận:"}.
{"Update ", "Cập Nhật "}.
{"Update plan", "Kế hoạch cập nhật"}.
{"Updated modules", "Môđun cập nhật"}.
{"Update script", "Cập nhận lệnh"}.
{"Low level update script", "Lệnh cập nhật mức độ thấp"}.
{"Script check", "Lệnh kiểm tra"}.
{"Port", "Cổng"}.
{"Module", "Môđun"}.
{"Options", "Tùy chọn"}.
{"Delete", "Xóa"}.
{"Start", "Khởi động"}.

% mod_muc/mod_muc.erl				
{"Only service administrators are allowed to send service messages", "Chỉ có người quản trị dịch vụ mới được phép gửi những thư dịch vụ"}.
{"Room creation is denied by service policy", "Việc tạo phòng bị ngăn lại theo chính sách dịch vụ"}.
{"Conference room does not exist", "Phòng họp không tồn tại"}.
{"Chatrooms", "Phòng trò chuyện"}.
{"You need an x:data capable client to register nickname", "Bạn cần có một trình ứng dụng khách hỗ trợ định dạng dữ liệu x: để đăng ký bí danh"}.
{"Nickname Registration at ", "Đăng Ký Bí Danh tại"}.
{"Enter nickname you want to register", "Nhập bí danh bạn muốn đăng ký"}.
{"Specified nickname is already registered", "Bí danh xác định đã đăng ký rồi"}.
{"You must fill in field \"Nickname\" in the form", "Bạn phải điền thông tin vào ô \"Nickname\" trong biểu mẫu này"}.
{"ejabberd MUC module", "Môdun ejabberd MUC Bản quyền"}.

% mod_muc/mod_muc_room.erl				
{"Traffic rate limit is exceeded", "Quá giới hạn tỷ lệ lưu lượng truyền tải"}.
{"It is not allowed to send private messages to the conference", "Không được phép gửi những thư riêng đến phòng họp"}.
{"Improper message type", "Loại thư không phù hợp"}.
{"Only occupants are allowed to send messages to the conference", "Chỉ có những đối tượng tham gia mới được phép gửi thư đến phòng họp"}.
{"It is not allowed to send private messages of type \"groupchat\"", "Không được phép gửi những thư riêng loại \"groupchat\""}.
{"Recipient is not in the conference room", "Người nhận không có trong phòng họp"}.
{"Only occupants are allowed to send queries to the conference", "Chỉ có những đối tượng tham gia mới được phép gửi yêu cầu đến phòng họp"}.
{"Queries to the conference members are not allowed in this room", "Không được phép gửi các yêu cầu gửi đến các thành viên trong phòng họp này"}.
{"private, ", "riêng,"}.
{"Only moderators and participants are allowed to change subject in this room", "Chỉ có những người điều phối và những người tham gia được phép thay đổi chủ đề trong phòng này"}.
{"Only moderators are allowed to change subject in this room", "Chỉ có những người điều phối được phép thay đổi chủ đề trong phòng này"}.
{"Visitors are not allowed to send messages to all occupants", "Người ghé thăm không được phép gửi thư đến tất cả các người tham dự"}.
{"Nickname is already in use by another occupant", "Bí danh đang do một người tham dự khác sử dụng"}.
{"Nickname is registered by another person", "Một người khác đã đăng ký bí danh này rồi"}.
{"You have been banned from this room", "Bạn bị cấm tham gia phòng này"}.
{"Membership required to enter this room", "Yêu cầu tư cách thành viên khi tham gia vào phòng này"}.
{"This room is not anonymous", "Phòng này không nặc danh"}.
{"Password required to enter this room", "Yêu cầu nhập mật khẩu để vào phòng này"}.
{"Incorrect password", "Mật khẩu sai"}.
{" has set the subject to: ", " đã đặt chủ đề thành: "}.
{"Administrator privileges required", "Yêu cầu đặc quyền của nhà quản trị"}.
{"Moderator privileges required", "Yêu cầu đặc quyền của nhà điều phối"}.
{"JID ~s is invalid", "JID ~s không hợp lệ"}.
{"Nickname ~s does not exist in the room", "Bí danh ~s không tồn tại trong phòng này"}.
{"Invalid affiliation: ~s", "Tư cách không hợp lệ: ~s"}.
{"Invalid role: ~s", "Vai trò không hợp lệ: ~s"}.
{"Owner privileges required", "Yêu cầu đặc quyền của người sở hữu"}.
{"Configuration for ", "Cấu hình cho "}.
{"Room title", "Tên phòng"}.
{"Make room persistent", "Tạo phòng bền vững"}.
{"Make room public searchable", "Tạo phòng có thể tìm kiếm công khai"}.
{"Make participants list public", "Tạo danh sách người tham dự công khai"}.
{"Make room password protected", "Tạo phòng được bảo vệ bằng mật khẩu"}.
{"Maximum Number of Occupants", "Số Lượng Người Tham Dự Tối Đa"}.
{"No limit", "Không giới hạn"}.
{"Present real JIDs to", "JID thực tế hiện hành đến"}.
{"moderators only", "nhà điều phối duy nhất"}.
{"anyone", "bất kỳ ai"}.
{"Make room members-only", "Tạo phòng chỉ cho phép tư cách thành viên tham gia"}.
{"Default users as participants", "Người sử dụng mặc định là người tham dự"}.
{"Allow users to change subject", "Cho phép người sử dụng thay đổi chủ đề"}.
{"Allow users to send private messages", "Cho phép người sử dụng gửi thư riêng"}.
{"Allow users to query other users", "Cho phép người sử dụng hỏi người sử dụng khác"}.
{"Allow users to send invites", "Cho phép người sử dụng gửi lời mời"}.
{"Enable logging", "Cho phép ghi nhật ký"}.
{"You need an x:data capable client to configure room", "Bạn cần có một trình ứng dụng khách hỗ trợ định dạng dữ liệu x: để xác định cấu hình phòng họp"}.
{"Number of occupants", "Số người tham dự"}.
{"~s invites you to the room ~s", "~s mời bạn vào phòng ~s"}.
{"the password is", "mật khẩu là"}.

% mod_muc/mod_muc_log.erl				
{"Chatroom configuration modified", "Cấu hình phòng trò chuyện được chỉnh sửa"}.
{"joins the room", "tham gia phòng này"}.
{"leaves the room", "rời khỏi phòng này"}.
{"has been kicked", "đã bị đẩy ra khỏi"}.
{"has been banned", "đã bị cấm"}.
{"is now known as", "bây giờ được biết như"}.
{"Monday", "Thứ Hai"}.
{"Tuesday", "Thứ Ba"}.
{"Wednesday", "Thứ Tư"}.
{"Thursday", "Thứ Năm"}.
{"Friday", "Thứ Sáu"}.
{"Saturday", "Thứ Bảy"}.
{"Sunday", "Chủ Nhật"}.
{"January", "Tháng Một"}.
{"February", "Tháng Hai"}.
{"March", "Tháng Ba"}.
{"April", "Tháng Tư"}.
{"May", "Tháng Năm"}.
{"June", "Tháng Sáu"}.
{"July", "Tháng Bảy"}.
{"August", "Tháng Tám"}.
{"September", "Tháng Chín"}.
{"October", "Tháng Mười"}.
{"November", "Tháng Mười Một"}.
{"December", "Tháng Mười Hai"}.
{"Room Configuration", "Cấu Hình Phòng"}.

% mod_offline.erl
{"Time", "Thời Gian"}.
{"From", "Từ"}.
{"To", "Đến"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
