% $Id$
% Language: Walon (Walloon)
% Author: Pablo Saratxaga

% jlib.hrl
{"No resource provided", "Nole rissoûce di dnêye"}.

% mod_configure.erl
{"Choose storage type of tables", "Tchoezi l' sôre di wårdaedje po les tåves"}.
{"RAM copy", "Copeye e memwere (RAM)"}.
{"RAM and disc copy", "Copeye e memwere (RAM) et sol deure plake"}.
{"Disc only copy", "Copeye seulmint sol deure plake"}.
{"Remote copy", "Copeye å lon"}.
{"Stop Modules at ", "Arester les modules so "}.
{"Choose modules to stop", "Tchoezixhoz les modules a-z arester"}.
{"Start Modules at ", "Renonder les modules so "}.
{"Enter list of {Module, [Options]}", "Dinez ene djivêye del cogne {Module, [Tchuzes]}"}.
{"List of modules to start", "Djivêye di modules a-z enonder"}.
{"Backup to File at ", "Fé ene copeye di såvrité dins on fitchî so "}.
{"Enter path to backup file", "Dinez l' tchimin viè l' fitchî copeye di såvrité"}.
{"Path to File", "Tchimin viè l' fitchî"}.
{"Restore Backup from File at ", "Rapexhî dispoy li fitchî copeye di såvrité so "}.
{"Dump Backup to Text File at ", "Copeye di såvritè viè on fitchî tecse so "}.
{"Enter path to text file", "Dinez l' tchimin viè l' fitchî tecse"}.
{"Import User from File at ", "Sititchî uzeu d' on fitchî so "}.
{"Enter path to jabberd1.4 spool file", "Dinez l' tchimin viè l' fitchî di spool jabberd1.4"}.
{"Import Users from Dir at ", "Sitichî des uzeus d' on ridant so "}.
{"Enter path to jabberd1.4 spool dir", "Dinez l' tchimin viè l' ridant di spool jabberd1.4"}.
{"Path to Dir", "Tchimin viè l' ridant"}.
{"Access Control List Configuration", "Apontiaedje des droets (ACL)"}.
{"Access control lists", "Droets (ACL)"}.
{"Access Configuration", "Apontiaedje des accès"}.
{"Access rules", "Rîles d' accès"}.
{"Administration of ", "Manaedjaedje di "}.
{"Action on user", "Accion so l' uzeu"}.
{"Edit Properties", "Candjî les prôpietés"}.
{"Remove User", "Disfacer l' uzeu"}.
{"Database", "Båze di dnêyes"}.
{"Outgoing s2s Connections", "Raloyaedjes s2s e rexhowe"}.
{"Import Users From jabberd 1.4 Spool Files", "Sititchî des uzeus Jabberd 1.4"}.
{"Database Tables Configuration at ", "Apontiaedje des tåves del båze di dnêyes so "}.
{"Change User Password", "Candjî l' sicret d' l' uzeu"}.
{"Get User Last Login Time", "Riçure li date/eure do dierin elodjaedje di l' uzeu"}.
{"Get User Statistics", "Riçure les statistikes di l' uzeu"}.
{"Get Number of Registered Users", "Riçure li nombe d' uzeus edjîstrés"}.
{"Get Number of Online Users", "Riçure li nombe d' uzeus raloyîs"}.
{"User Management", "Manaedjaedje des uzeus"}.
{"Time delay", "Tårdjaedje"}.
{"Password Verification", "Acertinaedje do scret"}.
{"Number of registered users", "Nombe d' uzeus edjîstrés"}.
{"Number of online users", "Nombe d' uzeus raloyîs"}.
{"Last login", "Dierin elodjaedje"}.
{"Roster size", "Grandeu del djivêye des soçons"}.
{"IP addresses", "Adresses IP"}.
{"Resources", "Rissoûces"}.

% src/ejabberd_c2s.erl
{"Use of STARTTLS required", "L' eployaedje di STARTTL est oblidjî"}.
{"Replaced by new connection", "Replaecî pa on novea raloyaedje"}.

% mod_disco.erl
{"Configuration", "Apontiaedjes"}.
{"Online Users", "Uzeus raloyîs"}.
{"All Users", "Tos les uzeus"}.
{"To ~s", "Viè ~s"}.
{"From ~s", "Dispoy ~s"}.
{"Running Nodes", "Nuks en alaedje"}.
{"Stopped Nodes", "Nuks essoctés"}.
{"Access Control Lists", "Droets (ACL)"}.
{"Access Rules", "Rîles d' accès"}.
{"Modules", "Modules"}.
{"Start Modules", "Enonder des modules"}.
{"Stop Modules", "Arester des modules"}.
{"Backup Management", "Manaedjaedje des copeyes di såvrité"}.
{"Backup", "Copeye di såvrité"}.
{"Restore", "Rapexhî"}.
{"Dump to Text File", "Schaper en on fitchî tecse"}.
{"Import File", "Sititchî d' on fitchî"}.
{"Import Directory", "Sititchî d' on ridant"}.

% mod_register.erl
{"Users are not allowed to register accounts so fast", "Les noveas uzeus n' si polèt nén edjîstrer si raddimint"}.
{"Choose a username and password to register with this server", "Tchoezixhoz on no d' uzeu eyet on scret po vs edjîstrer so ç' sierveu ci"}.

% mod_vcard_ldap.erl
{"Erlang Jabber Server", "Sierveu Jabber Erlang"}.
{"ejabberd vCard module", "Module vCard ejabberd"}.
{"Email", "Emile"}.
{"Search Results for ", "Rizultats do cweraedje po "}.
{"Jabber ID", "ID Jabber"}.

% mod_vcard_odbc.erl
{"vCard User Search", "Calpin des uzeus"}.

% mod_vcard.erl
{"You need an x:data capable client to search", "Vos avoz mezåjhe d' on cliyint ki sopoite x:data po fé on cweraedje"}.
{"Search users in ", "Cweri des uzeus dins "}.

{"Fill in fields to search for any matching Jabber User", "Rimplixhoz les tchamps po cweri èn uzeu Jabber"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)", "Rimplixhoz les tchamps do formulaire po cweri èn uzeu Jabber (radjouter «*» al fén do tchamp po cweri tot l' minme kéne fén d' tchinne"}.

{"User",              "Uzeu"}.
{"Full Name", 	      "No etir"}.
{"Name", 	      "Pitit no"}.
{"Middle Name",       "No do mitan"}.
{"Family Name",       "No d' famile"}.
{"Nickname", 	      "Metou no"}.
{"Birthday", 	      "Date d' askepiaedje"}.
{"Country", 	      "Payis"}.
{"City", 	      "Veye"}.
{"Organization Name", "No d' l' organizåcion"}.
{"Organization Unit", "Unité d' l' organizåcion"}.

% mod_adhoc.erl
{"Commands", "Comandes"}.
{"Ping", "Ping"}.
{"Pong", "Pong"}.

% mod_announce.erl
{"Really delete message of the day?", "Voloz vs vormint disfacer l' messaedje do djoû?"}.
{"Subject", "Sudjet"}.
{"Message body", "Coir do messaedje"}.
{"No body provided for announce message", "I n' a nou coir do messaedje po ciste anonce la"}.
{"Announcements", "Anonces"}.
{"Send announcement to all users", "Evoyî l' anonce a tos les uzeus"}.
{"Send announcement to all users on all hosts", "Evoyî l' anonce a tos les uzeus so tos les lodjoes"}.
{"Send announcement to all online users", "Evoyî l' anonce a tos les uzeus raloyîs"}.
{"Send announcement to all online users on all hosts", "Evoyî l' anonce a tos les uzeus raloyîs so tos les lodjoes"}.
{"Set message of the day and send to online users", "Defini l' messaedje do djoû et l' evoyî åzès uzeus raloyîs"}.
{"Set message of the day on all hosts and send to online users", "Defini l' messaedje do djoû so tos les lodjoes et l' evoyî åzès uzeus raloyîs"}.
{"Update message of the day (don't send)", "Mete a djoû l' messaedje do djoû (nén l' evoyî)"}.
{"Update message of the day on all hosts (don't send)", "Mete a djoû l' messaedje do djoû so tos les lodjoes (nén l' evoyî)"}.
{"Delete message of the day", "Disfacer l' messaedje do djoû"}.
{"Delete message of the day on all hosts", "Disfacer l' messaedje do djoû so tos les lodjoes"}.

% mod_pubsub/mod_pubsub.erl
{"ejabberd Publish-Subscribe module", "Module d' eplaidaedje-abounmint po ejabberd"}.
{"PubSub subscriber request", "Dimande d' eplaidaedje-abounmint d' èn abouné"}.
{"Choose whether to approve this entity's subscription.", "Tchoezi s' i fåt aprover ou nén l' abounmint di ciste intité."}.
{"Node ID", "ID d' nuk"}.
{"Subscriber Address", "Adresse di l' abouné"}.
{"Allow this JID to subscribe to this pubsub node?", "Permete ki ci JID ci si poye abouner a ç' nuk eplaidaedje-abounmint ci?"}.
{"Deliver payloads with event notifications", "Evoyî l' contnou avou les notifiaedjes d' evenmints"}.
{"Deliver event notifications", "Evoyî des notifiaedjes d' evenmints"}.
{"Persist items to storage", "Cayets permanints a wårder"}.
{"A friendly name for the node", "On no uzeu-ahessåve pol nuk"}.
{"Max # of items to persist", "Nombe macsimoms di cayets permanints"}.
{"Specify the access model", "Sipecifyî l' modele d' accès"}.
{"Roster groups allowed to subscribe", "Pårtaedjîs groupes di soçons k' on s' î pout abouner"}.
{"Max payload size in bytes", "Contnou macsimom en octets"}.
{"When to send the last published item", "Cwand evoyî l' dierin cayet eplaidî"}.
{"Publish-Subscribe", "Eplaidaedje-abounmint"}.
{"Notify subscribers when the node configuration changes", "Notifyî åzès abounés cwand l' apontiaedje do nuk candje"}.
{"Notify subscribers when the node is deleted", "Notifyî åzès abounés cwand l' nuk est disfacé"}.
{"Notify subscribers when items are removed from the node", "Notifyî åzès abounés cwand des cayets sont oisté foû do nuk"}.
{"Whether to allow subscriptions", "Si on permete les abounmints"}.
{"Specify the publisher model", "Dinez l' modele d' eplaideu"}.
{"Only deliver notifications to available users", "Seulmint evoyî des notifiaedje åzès uzeus disponibes"}.

% mod_muc/mod_muc_log.erl
{"has been kicked because of an affiliation change", "a stî pité evoye cåze d' on candjmint d' afiyaedje"}.
{"has been kicked because the room has been changed to members-only", "a stî pité evoye cåze ki l' såle a stî ristrindowe åzès mimbes seulmint"}.
{"has been kicked because of a system shutdown", "a stî pité evoye cåze d' èn arestaedje do sistinme"}.
{"Chatroom configuration modified", "L' apontiaedje del såle di berdelaedje a candjî"}.
{"joins the room", "arive sol såle"}.
{"leaves the room", "cwite li såle"}.
{"has been kicked", "a stî pité evoye"}.
{"has been banned", "a stî bani"}.
{"is now known as", "est asteure kinoxhou come"}.
{"Monday", "londi"}.
{"Tuesday", "mårdi"}.
{"Wednesday", "mierkidi"}.
{"Thursday", "djudi"}.
{"Friday", "vénrdi"}.
{"Saturday", "semdi"}.
{"Sunday", "dimegne"}.
{"January", "djanvî"}.
{"February", "fevrî"}.
{"March", "måss"}.
{"April", "avri"}.
{"May", "may"}.
{"June", "djun"}.
{"July", "djulete"}.
{"August", "awousse"}.
{"September", "setimbe"}.
{"October", "octôbe"}.
{"November", "nôvimbe"}.
{"December", "decimbe"}.
{"Room Configuration", "Apontiaedje del såle"}.

% mod_muc/mod_muc.erl
{"Chatrooms", "Såles di berdelaedje"}.
{"You need an x:data capable client to register nickname", "Vos avoz mezåjhe d' on cliyint ki sopoite x:data po-z edjîstrer on metou no"}.
{"Nickname Registration at ", "Edjîstraedje di metou no amon "}.
{"Enter nickname you want to register", "Dinez l' metou no ki vos vloz edjîstrer"}.
{"ejabberd MUC module", "Module MUC (såles di berdelaedje) po ejabberd"}.
{"Only service administrators are allowed to send service messages", "Seulmint les manaedjeus d' siervices polèt evoyî des messaedjes di siervice"}.
{"Room creation is denied by service policy", "L' ahivaedje del såle est rfuzé pal politike do siervice"}.
{"Conference room does not exist", "Li såle di conferince n' egzistêye nén"}.
{"Access denied by service policy", "L' accès a stî rfuzé pal politike do siervice"}.
{"Specified nickname is already registered", "Li no metou dné est ddja edjîstré"}.
{"You must fill in field \"Nickname\" in the form", "Vos dvoz rimpli l' tchamp «Metou no» dins l' formiulaire"}.

% mod_muc/mod_muc_room.erl
{"This participant is kicked from the room because he sent an error message", "Ci pårticipant ci a stî pité evoye del såle cåze k' il a-st evoyî on messaedje d' aroke"}.
{"This participant is kicked from the room because he sent an error message to another participant", "Ci pårticipant ci a stî pité evoye del såle cåze k' il a-st evoyî on messaedje d' aroke a èn ôte pårticipant"}.
{"It is not allowed to send private messages", "Ci n' est nén permetou d' evoyî des messaedjes privés"}.
{"This participant is kicked from the room because he sent an error presence", "Ci pårticipant ci a stî pité evoye del såle cåze k' il a-st evoyî ene aroke di prezince"}.
{"Visitors are not allowed to change their nicknames in this room", "Les viziteus èn polèt nén candjî leus metous no po ç' såle ci"}.
{"Invalid affiliation: ~s", "Afiyaedje nén valide: ~s"}.
{"Make room persistent", "Rinde li såle permaninte"}.
{"Allow visitors to send status text in presence updates", "Permete ki les viziteus evoyexhe des tecse d' estat dins leus messaedjes di prezince"}.
{"Allow visitors to change nickname", "Permete ki les viziteus candjexhe leus metous nos"}.
{"~s invites you to the room ~s", "~s vos preye sol såle ~s"}.
{" has set the subject to: ", " a candjî l' tite a: "}.
{"You need an x:data capable client to configure room", "I vs fåt on cliyint ki sopoite x:data por vos poleur apontyî l' såle"}.
{"Configuration for ", "Apontiaedje po "}.
{"Room title", "Tite del såle"}.
{"Password", "Sicret"}.
{"Only moderators and participants are allowed to change subject in this room", "Seulmint les moderateus et les pårticipants polèt candjî l' sudjet dins cisse såle ci"}.
{"Only moderators are allowed to change subject in this room", "Seulmint les moderateus polèt candjî l' sudjet dins cisse såle ci"}.
{"Visitors are not allowed to send messages to all occupants", "Les viziteus n' polèt nén evoyî des messaedjes a tos les prezints"}.
{"Only occupants are allowed to send messages to the conference", "Seulmint les prezints polèt evoyî des messaedjes al conferince"}.
{"It is not allowed to send private messages to the conference", "On n' pout nén evoyî des messaedjes privés dins cisse conferince ci"}.
{"Nickname is already in use by another occupant", "Li metou no est ddja eployî pa ene ôte sakî sol såle"}.
{"Nickname is registered by another person", "Li metou no est ddja edjîstré pa ene ôte sakî"}.
{"It is not allowed to send private messages of type \"groupchat\"", "C' est nén possibe d' evoyî des messaedjes privés del sôre «groupchat»"}.
{"Recipient is not in the conference room", "Li riçuveu n' est nén dins l' såle
di conferince"}.
{"Only occupants are allowed to send queries to the conference", "Seulmint les prezints polèt evoyî des cweraedjes sol conferince"}.
{"Queries to the conference members are not allowed in this room", "Les cweraedjes des mimbes del conferince ni sont nén permetous dins cisse såle ci"}.
{"You have been banned from this room", "Vos avoz stî bani di cisse såle ci"}.
{"Membership required to enter this room", "I fåt esse mimbe po poleur intrer dins cisse såle ci"}.
{"Password required to enter this room", "I fåt dner on scret po poleur intrer dins cisse såle ci"}.
{"Incorrect password", "Sicret nén corek"}.
{"Administrator privileges required", "I fåt des priviledjes di manaedjeu"}.
{"Moderator privileges required", "I fåt des priviledjes di moderateu"}.
{"JID ~s is invalid", "Li JID ~s n' est nén valide"}.
{"Nickname ~s does not exist in the room", "Li metou no ~s n' egzistêye nén dins l' såle"}.
{"Invalid role: ~s", "Role nén valide: ~s"}.
{"Owner privileges required", "I fåt des priviledjes di prôpietaire"}.
{"private, ", "privé, "}.
{"This room is not anonymous", "Cisse såle ci n' est nén anonime"}.
{"Make room public searchable", "Rinde li såle di berdelaedje cweråve publicmint"}.
{"Make participants list public", "Rinde publike li djivêye des pårticipants"}.
{"Make room password protected", "Rinde li såle di berdelaedje protedjeye pa scret"}.
{"Make room members-only", "Rinde li såle di berdelaedje ristrindowe ås mimbes seulmint"}.
{"Make room moderated", "Rinde li såle di berdelaedje moderêye"}.
{"Default users as participants", "Les uzeus sont des pårticipants come prémetowe dujhance"}.
{"Allow users to change subject", "Les uzeus polèt candjî l' tite"}.
{"Allow users to send private messages", "Les uzeus polèt evoyî des messaedjes privés"}.
{"Allow users to query other users", "Les uzeus polèt cweri ls ôtes uzeus"}.
{"Allow users to send invites", "Les uzeus polèt evoyî priyaedjes"}.
{"Enable logging", "Mete en alaedje li djournå"}.
{"Number of occupants", "Nombe di prezints"}.
{"Present real JIDs to", "Mostrer les vraiys JIDs a"}.
{"moderators only", "les moderateus seulmint"}.
{"anyone", "tot l' minme kî"}.
{"Traffic rate limit is exceeded", "Li limite pol volume di trafik a stî passêye"}.
{"Improper message type", "Sôre di messaedje nén valide"}.
{"Maximum Number of Occupants", "Nombe macsimom di prezints"}.
{"No limit", "Pont d' limite"}.
{"the password is", "li scret est"}.


% mod_irc/mod_irc.erl
{"IRC Transport", "Transpoirt IRC"}.
{"ejabberd IRC module", "Module IRC po ejabberd"}.
{"You need an x:data capable client to configure mod_irc settings", "Vos avoz mezåjhe d' on cliyint ki sopoite x:data po candjî ls apontiaedjes di mod_irc"}.
{"Registration in mod_irc for ", "Edjîstraedje dins mod_irc po "}.
{"Enter username and encodings you wish to use for connecting to IRC servers", "Dinez les nos d' uzeu et ls ecôdaedjes ki vos vloz eployî po vs raloyî åzès sierveus IRC"}.
{"IRC Username", "No d' uzeu IRC"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.", "Si vos vloz dner des ecôdaedjes diferins po les sierveus IRC, rimplixhoz cisse djivêye ci avou des valixhances del cogne «{\"sierveu irc\", \"ecôdaedje\"}». Li prémetou ecôdaedje do siervice c' est «~s»."}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].", "Egzimpe: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Encodings", "Ecôdaedjes"}.

% web/ejabberd_web_admin.erl
{"ejabberd Web Admin", "Manaedjeu waibe ejabberd"}.
{"Administration", "Manaedjaedje"}.
{"Users", "Uzeus"}.
{"Nodes", "Nuks"}.
{"Statistics", "Sitatistikes"}.
{"(Raw)", "(Dinêyes brutes)"}.
{"Submitted", "Candjmints evoyîs"}.
{"Bad format", "Mwais fôrmat"}.
{"Raw", "Dinêyes brutes"}.
{"Delete Selected", "Disfacer les elemints tchoezis"}.
{"Submit", "Evoyî"}.
{"~s access rule configuration", "Apontiaedje des rîles d' accès a ~s"}.
{"Node not found", "Nuk nén trové"}.
{"Add New", "Radjouter"}.
{"Registered Users", "Uzeus edjistrés"}.
{"Registered Users:", "Uzeus edjistrés:"}.
{"Change Password", "Candjî l' sicret"}.
{"Connected Resources:", "Raloyî avou les rsoûces:"}.
{"Password:", "Sicret:"}.
{"None", "Nole"}.
{"Node ", "Nuk "}.
{"Listened Ports", "Pôrts drovous"}.
{"Restart", "Renonder"}.
{"Stop", "Arester"}.
{"Restart Service", "Renonder siervice"}.
{"Shut Down Service", "Arester siervice"}.
{"RPC Call Error", "Aroke di houcaedje RPC"}.
{"Name", "No"}.
{"Storage Type", "Sôre di wårdaedje"}.
{"Size", "Grandeu"}.
{"Memory", "Memwere"}.
{"OK", "'l est bon"}.
{"Listened Ports at ", "Pôrts drovous so "}.
{"Uptime:", "Tins dispoy l' enondaedje:"}.
{"CPU Time:", "Tins CPU:"}.
{"Transactions Commited:", "Transaccions evoyeyes:"}.
{"Transactions Aborted:", "Transaccions arestêyes:"}.
{"Transactions Restarted:", "Transaccions renondêyes:"}.
{"Transactions Logged:", "Transaccions wårdêyes e djournå:"}.
{"Port", "Pôrt"}.
{"Module", "Module"}.
{"Options", "Tchuzes"}.
{"Update", "Mete a djoû"}.
{"Delete", "Disfacer"}.
{"Add User", "Radjouter èn uzeu"}.
{"Delete User", "Disfacer èn uzeu"}.
{"End User Session", "Fini l' session d' l' uzeu"}.
{"Get User Password", "Riçure sicret d' l' uzeu"}.
{"Offline Messages", "Messaedjes ki ratindèt"}.
{"Users Last Activity", "Dierinne activité des uzeus"}.
{"Never", "Måy"}.
{"~s's Offline Messages Queue", "messaedjes ki ratindèt el cawêye po ~s"}.
{"Time", "Date"}.
{"From", "Di"}.
{"To", "Po"}.
{"Packet", "Paket"}.
{"Offline Messages:", "Messaedjes ki ratindèt:"}.
{"Roster", "Djivêye des soçons"}.
{"Nickname", "Metou no"}.
{"Subscription", "Abounmimnt"}.
{"Pending", "Ratindant"}.
{"Groups", "Groupes"}.
{"Remove", "Oister"}.
{"Add Jabber ID", "Radjouter èn ID Jabber"}.
{"User ", "Uzeu "}.
{"Roster of ", "Djivêye des soçons da "}.
{"Online", "Raloyî"}.
{"Validate", "Valider"}.
{"Name:", "Pitit no:"}.
{"Description:", "Discrijhaedje:"}.
{"Members:", "Mimbes:"}.
{"Displayed Groups:", "Groupes håynés:"}.
{"Group ", "Groupe "}.
{"Period: ", "Termene:"}.
{"Last month", "Dierin moes"}.
{"Last year", "Dierinne anêye"}.
{"All activity", "Dispoy todi"}.
{"Show Ordinary Table", "Mostrer crexhince"}.
{"Show Integral Table", "Mostrer totå"}.
{"Modules at ", "Modules so "}.
{"Start", "Enonder"}.
{"Virtual Hosts", "Forveyous sierveus"}.
{"ejabberd virtual hosts", "Forveyous sierveus da ejabberd"}.
{"Host", "Sierveu"}.
{"No Data", "Nole dinêye disponibe"}.
{"Online Users:", "Uzeus raloyîs:"}.
{"Outgoing s2s Connections:", "Raloyaedjes s2s e rexhowe:"}.
{"Outgoing s2s Servers:", "Sierveus s2s e rexhowe:"}.
{"Database Tables at ", "Tåves del båze di dnêyes so "}.
{"Backup of ", "Copeye di såvrité po "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.", "Notez ki ces tchuzes la vont seulmint fé ene copeye di såvrité del båze di dnêyes Mnesia costrûte å dvins do programe. Si vos eployîz ene difoûtrinne båze di dnêyes avou l' module ODBC, vos dvoz fé ene copeye di såvrité del båze SQL da vosse sepårumint."}.
{"Store binary backup:", "Copeye di såvrité binaire:"}.
{"Restore binary backup immediately:", "Rapexhî do côp foû d' ene copeye di såvrité binaire:"}.
{"Restore binary backup after next ejabberd restart (requires less memory):", "Rapexhî l' copeye di såvrité binaire après l' renondaedje ki vént d' ejabberd (çoula prind moens d' memwere del fé insi):"}.
{"Store plain text backup:", "Copeye di såvrité tecse:"}.
{"Restore plain text backup immediately:", "Rapexhî do côp foû d' ene copeye di såvrité tecse:"}.
{"Statistics of ~p", "Sitatistikes di ~p"}.
{"Update ", "Metaedje a djoû "}.
{"Update plan", "Plan d' metaedje a djoû"}.
{"Updated modules", "Modules metous a djoû"}.
{"Update script", "Sicripe di metaedje a djoû"}.
{"Low level update script", "Sicripe di metaedje a djoû d' bas livea"}.
{"Script check", "Acertinaedje do scripe"}.
{"Shared Roster Groups", "Pårtaedjîs groupes ezès djivêyes di soçons"}.
{"Last Activity", "Dierinne activité"}.

% mod_offline.erl
{"Your contact offline message queue is full. The message has been discarded.", "Li cawêye di messaedjes e môde disraloyî di vosse soçon est plinne. Li messaedje a stî tapé å diale."}.

% mod_proxy65/mod_proxy65_service.erl
{"ejabberd SOCKS5 Bytestreams module", "Module SOCKS5 Bytestreams po ejabberd"}.

% Local Variables:
% mode: erlang
% End:
% vim: set filetype=erlang tabstop=8:
