{"Access Configuration","访问配置"}.
{"Access Control List Configuration","访问控制列表(ACL)配置"}.
{"Access control lists","访问控制列表(ACL)"}.
{"Access Control Lists","访问控制列表(ACL)"}.
{"Access rules","访问规则"}.
{"Access Rules","访问规则"}.
{"Action on user","对用户的动作"}.
{"Add Jabber ID","添加 Jabber ID"}.
{"Add New","添加新用户"}.
{"Add User","添加用户"}.
{"Administration of ","管理"}.
{"Administration","管理"}.
{"Administrator privileges required","需要管理员权限"}.
{"A friendly name for the node","该节点的友好名称"}.
{"All activity","所有活动"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","允许该 Jabber ID 订阅该pubsub节点?"}.
{"Allow users to change the subject","允许用户更改主题"}.
{"Allow users to query other users","允许用户查询其它用户"}.
{"Allow users to send invites","允许用户发送邀请"}.
{"Allow users to send private messages","允许用户发送私聊消息"}.
{"Allow visitors to change nickname","允许用户更改昵称"}.
{"Allow visitors to send status text in presence updates","更新在线状态时允许用户发送状态文本"}.
{"All Users","所有用户"}.
{"Announcements","通知"}.
{"anyone","任何人"}.
{"A password is required to enter this room","进入此房间需要密码"}.
{"April","四月"}.
{"August","八月"}.
{"Backup Management","备份管理"}.
{"Backup of ","备份来源 "}.
{"Backup to File at ","备份到文件位于"}.
{"Backup","备份"}.
{"Bad format","格式错误"}.
{"Birthday","出生日期"}.
{"Change Password","更改密码"}.
{"Change User Password","更改用户密码"}.
{"Choose a username and password to register with this server","请选择在此服务器上注册所需的用户名和密码"}.
{"Choose modules to stop","请选择要停止的模块"}.
{"Choose storage type of tables","请选择表格的存储类型"}.
{"Choose whether to approve this entity's subscription.","选择是否允许该实体的订阅"}.
{"City","城市"}.
{"Commands","命令"}.
{"Configuration of room ~s","房间~s的配置 "}.
{"Configuration","配置"}.
{"Connected Resources:","已连接资源:"}.
{"Country","国家"}.
{"CPU Time:","CPU 时间："}.
{"Database Tables at ","数据库列表位于 "}.
{"Database Tables Configuration at ","数据库表格配置位于"}.
{"Database","数据库"}.
{"December","十二月"}.
{"Default users as participants","用户默认被视为参与人"}.
{"Delete message of the day on all hosts","删除所有主机上的每日消息"}.
{"Delete message of the day","删除每日消息"}.
{"Delete Selected","删除已选内容"}.
{"Delete User","删除用户"}.
{"Delete","删除"}.
{"Deliver event notifications","传递事件通知"}.
{"Deliver payloads with event notifications","用事件通告传输有效负载"}.
{"Description:","描述:"}.
{"Disc only copy","仅磁盘复制"}.
{"Dump Backup to Text File at ","转储备份到文本文件于"}.
{"Dump to Text File","转储到文本文件"}.
{"Edit Properties","编辑属性"}.
{"ejabberd MUC module","ejabberd MUC 模块"}.
{"ejabberd Publish-Subscribe module","ejabberd 发行-订阅模块"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 字节流模块"}.
{"ejabberd vCard module","ejabberd vCard 模块"}.
{"ejabberd virtual hosts","ejabberd 虚拟主机"}.
{"ejabberd Web Admin","ejabberd 网页管理"}.
{"Elements","元素"}.
{"Email","电子邮件"}.
{"Enable logging","启用服务器端聊天记录"}.
{"End User Session","结束用户会话"}.
{"Enter list of {Module, [Options]}","请输入{模块, [选项]}列表"}.
{"Enter nickname you want to register","请输入您想要注册的昵称"}.
{"Enter path to backup file","请输入备份文件的路径"}.
{"Enter path to jabberd14 spool dir","请输入 jabberd14 spool 目录的路径"}.
{"Enter path to jabberd14 spool file","请输入 jabberd14 spool 文件的路径"}.
{"Enter path to text file","请输入文本文件的路径"}.
{"Enter the text you see","请输入您所看到的文本"}.
{"Erlang Jabber Server","Erlang Jabber 服务器"}.
{"Error","错误"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","将服务器上所有用户的数据导出到 PIEFXIS 文件 (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","将某主机的用户数据导出到 PIEFXIS 文件 (XEP-0227):"}.
{"Family Name","姓氏"}.
{"February","二月"}.
{"Fill in fields to search for any matching Jabber User","填充字段以搜索任何匹配的 Jabber 用户"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","填充表单以搜索任何匹配的 Jabber 用户(在字段末添加*来匹配子串)"}.
{"Friday","星期五"}.
{"From ~s","来自~s"}.
{"From","从"}.
{"Full Name","全名"}.
{"Get Number of Online Users","获取在线用户数"}.
{"Get Number of Registered Users","获取注册用户数"}.
{"Get User Last Login Time","获取用户上次登陆时间"}.
{"Get User Password","获取用户密码"}.
{"Get User Statistics","获取用户统计"}.
{"Groups","组"}.
{"Group ","组"}.
{"has been banned","已被禁止"}.
{"has been kicked because of an affiliation change","因联属关系改变而被踢出"}.
{"has been kicked because of a system shutdown","因系统关机而被踢出"}.
{"has been kicked because the room has been changed to members-only","因该房间改为只对会员开放而被踢出"}.
{"has been kicked","已被踢出"}.
{" has set the subject to: ","已将标题设置为: "}.
{"Host","主机"}.
{"Import Directory","导入目录"}.
{"Import File","导入文件"}.
{"Import user data from jabberd14 spool file:","从 jabberd14 Spool文件导入用户数据:"}.
{"Import User from File at ","导入用户的文件位于 "}.
{"Import users data from a PIEFXIS file (XEP-0227):","从 PIEFXIS 文件 (XEP-0227)导入用户数据:"}.
{"Import users data from jabberd14 spool directory:","从 jabberd14 Spool目录导入用户数据:"}.
{"Import Users from Dir at ","导入用户的目录位于 "}.
{"Import Users From jabberd14 Spool Files","从 jabberd14 Spool 文件导入用户"}.
{"Improper message type","不正确的消息类型"}.
{"Incorrect password","密码不正确"}.
{"Invalid affiliation: ~s","无效加入: ~s"}.
{"Invalid role: ~s","无效角色: ~s"}.
{"IP addresses","IP 地址"}.
{"IP","IP"}.
{"is now known as","现在称呼为"}.
{"It is not allowed to send private messages of type \"groupchat\"","\"群组聊天\"类型不允许发送私聊消息"}.
{"It is not allowed to send private messages","不允许发送私聊消息"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s无效"}.
{"January","一月"}.
{"joins the room","加入房间"}.
{"July","七月"}.
{"June","六月"}.
{"Last Activity","上次活动"}.
{"Last login","上次登陆"}.
{"Last month","上个月"}.
{"Last year","上一年"}.
{"leaves the room","离开房间"}.
{"Listened Ports at ","监听的端口位于 "}.
{"Listened Ports","被监听的端口"}.
{"List of modules to start","要启动的模块列表"}.
{"Low level update script","低级别更新脚本"}.
{"Make participants list public","公开参与人列表"}.
{"Make room captcha protected","保护房间验证码"}.
{"Make room members-only","设置房间只接收会员"}.
{"Make room moderated","只有有\"发言权\"的用户才可以发送消息给所有驻留者"}.
{"Make room password protected","进入此房间需要密码"}.
{"Make room persistent","永久保存该房间"}.
{"Make room public searchable","使房间可被公开搜索"}.
{"March","三月"}.
{"Maximum Number of Occupants","允许的驻留者最大数"}.
{"Max # of items to persist","允许持久化的最大内容条目数"}.
{"Max payload size in bytes","最大有效负载比特数"}.
{"May","五月"}.
{"Membership is required to enter this room","进入此房间需要会员身份"}.
{"Members:","会员:"}.
{"Memory","内存"}.
{"Message body","消息主体"}.
{"Middle Name","中间名"}.
{"Moderator privileges required","需要主持人权限"}.
{"moderators only","仅主持人"}.
{"Modified modules","被修改模块"}.
{"Modules at ","模块位于 "}.
{"Modules","模块"}.
{"Module","模块"}.
{"Monday","星期一"}.
{"Name:","姓名:"}.
{"Name","姓名"}.
{"Never","从未"}.
{"Nickname Registration at ","昵称注册于 "}.
{"Nickname ~s does not exist in the room","昵称~s不在该房间"}.
{"Nickname","昵称"}.
{"No Data","没有数据"}.
{"Node ID","节点 ID"}.
{"Node not found","没有找到节点"}.
{"Nodes","节点"}.
{"Node ","节点 "}.
{"No limit","不限"}.
{"None","无"}.
{"Not Found","没有找到"}.
{"Notify subscribers when items are removed from the node","当从节点删除内容条目时通知订阅人"}.
{"Notify subscribers when the node configuration changes","当节点设置改变时通知订阅人"}.
{"Notify subscribers when the node is deleted","当节点被删除时通知订阅人"}.
{"November","十一月"}.
{"Number of occupants","驻留人数"}.
{"Number of online users","在线用户数"}.
{"Number of registered users","注册用户数"}.
{"October","十月"}.
{"Offline Messages:","离线消息:"}.
{"Offline Messages","离线消息"}.
{"OK","确定"}.
{"Online Users:","在线用户:"}.
{"Online Users","在线用户"}.
{"Online","在线"}.
{"Only deliver notifications to available users","仅将通知发送给可发送的用户"}.
{"Only moderators and participants are allowed to change the subject in this room","只允许监管人和参与人在此房间里更改主题"}.
{"Only moderators are allowed to change the subject in this room","只允许监管人更改此房间的主题"}.
{"Options","选项"}.
{"Organization Name","组织名称"}.
{"Organization Unit","组织单位"}.
{"Outgoing s2s Connections:","出站 s2s 连接:"}.
{"Outgoing s2s Connections","出站 s2s 连接"}.
{"Outgoing s2s Servers:","出站 s2s 服务器"}.
{"Owner privileges required","需要持有人权限"}.
{"Packet","数据包"}.
{"Password Verification","确认密码"}.
{"Password:","密码: "}.
{"Password","密码"}.
{"Path to Dir","目录的路径"}.
{"Path to File","文件路径"}.
{"Pending","挂起"}.
{"Period: ","持续时间: "}.
{"Persist items to storage","持久化内容条目"}.
{"Ping","Ping"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","注意：这些选项仅将备份内置的 Mnesia 数据库. 如果您正在使用 ODBC 模块, 您还需要分别备份您的数据库."}.
{"Pong","Pong"}.
{"Port","端口"}.
{"Present real Jabber IDs to","将真实 Jabber ID 显示给"}.
{"private, ","保密, "}.
{"Protocol","协议"}.
{"Publish-Subscribe","发行-订阅"}.
{"PubSub subscriber request","PubSub 订阅人请求"}.
{"Purge all items when the relevant publisher goes offline","相关发布人离线后清除所有选项"}.
{"RAM and disc copy","内存与磁盘复制"}.
{"RAM copy","内存(RAM)复制"}.
{"Raw","原始格式"}.
{"Really delete message of the day?","确实要删除每日消息吗?"}.
{"Registered Users:","注册用户:"}.
{"Registered Users","注册用户"}.
{"Remote copy","远程复制"}.
{"Remove All Offline Messages","移除所有离线消息"}.
{"Remove User","删除用户"}.
{"Remove","移除"}.
{"Resources","资源"}.
{"Restart Service","重启服务"}.
{"Restart","重启"}.
{"Restore Backup from File at ","要恢复的备份文件位于"}.
{"Restore binary backup after next ejabberd restart (requires less memory):","在下次 ejabberd 重启后恢复二进制备份(需要的内存更少):"}.
{"Restore binary backup immediately:","立即恢复二进制备份:"}.
{"Restore plain text backup immediately:","立即恢复普通文本备份:"}.
{"Restore","恢复"}.
{"Room Configuration","房间配置"}.
{"Room description","房间描述"}.
{"Room Occupants","房间人数"}.
{"Room title","房间标题"}.
{"Roster groups allowed to subscribe","允许订阅的花名册组"}.
{"Roster of ","花名册属于 "}.
{"Roster size","花名册大小"}.
{"Roster","花名册"}.
{"RPC Call Error","RPC 调用错误"}.
{"Running Nodes","运行中的节点"}.
{"~s access rule configuration","~s 访问规则配置"}.
{"Saturday","星期六"}.
{"Script check","脚本检查"}.
{"Search Results for ","搜索结果属于关键词 "}.
{"Search users in ","搜索用户于 "}.
{"Send announcement to all online users on all hosts","发送通知给所有主机的在线用户"}.
{"Send announcement to all online users","发送通知给所有在线用户"}.
{"Send announcement to all users on all hosts","发送通知给所有主机上的所有用户"}.
{"Send announcement to all users","发送通知给所有用户"}.
{"September","九月"}.
{"Set message of the day and send to online users","设定每日消息并发送给所有在线用户"}.
{"Set message of the day on all hosts and send to online users","设置所有主机上的每日消息并发送给在线用户"}.
{"Shared Roster Groups","共享的花名册组群"}.
{"Show Integral Table","显示完整列表"}.
{"Show Ordinary Table","显示普通列表"}.
{"Shut Down Service","关闭服务"}.
{"~s invites you to the room ~s","~s邀请你到~s房间"}.
{"Specify the access model","指定访问模式"}.
{"Specify the event message type","指定事件消息类型"}.
{"Specify the publisher model","指定发布人样式"}.
{"~s's Offline Messages Queue","~s 的离线消息队列"}.
{"Start Modules at ","要启动的模块位于 "}.
{"Start Modules","启动模块"}.
{"Start","开始"}.
{"Statistics of ~p","~p 的统计"}.
{"Statistics","统计"}.
{"Stop Modules at ","要停止的模块位于 "}.
{"Stop Modules","停止模块"}.
{"Stopped Nodes","已经停止的节点"}.
{"Stop","停止"}.
{"Storage Type","存储类型"}.
{"Store binary backup:","存储为二进制备份:"}.
{"Store plain text backup:","存储为普通文本备份:"}.
{"Subject","标题"}.
{"Submitted","已提交"}.
{"Submit","提交"}.
{"Subscriber Address","订阅人地址"}.
{"Subscription","订阅"}.
{"Sunday","星期天"}.
{"That nickname is already in use by another occupant","该昵称已被另一用户使用"}.
{"That nickname is registered by another person","该昵称已被另一个人注册了"}.
{"The captcha is valid.","验证码有效."}.
{"The collections with which a node is affiliated","加入结点的集合"}.
{"the password is","密码是"}.
{"This participant is kicked from the room because he sent an error message to another participant","该用户由于给其他人发送了出错消息而被踢出了聊天室"}.
{"This participant is kicked from the room because he sent an error message","该用户由于发送了错误消息而被踢出了聊天室"}.
{"This participant is kicked from the room because he sent an error presence","该用户由于发送了错误状态而被踢出了聊天室"}.
{"This room is not anonymous","此房间不是匿名房间"}.
{"Thursday","星期四"}.
{"Time delay","时间延迟"}.
{"Time","时间"}.
{"To ~s","发送给~s"}.
{"To","到"}.
{"Traffic rate limit is exceeded","已经超过传输率限制"}.
{"Transactions Aborted:","取消的事务:"}.
{"Transactions Committed:","提交的事务:"}.
{"Transactions Logged:","记入日志的事务:"}.
{"Transactions Restarted:","重启的事务:"}.
{"Tuesday","星期二"}.
{"Unable to generate a captcha","无法产生验证码"}.
{"Unauthorized","未认证的"}.
{"Update message of the day (don't send)","更新每日消息(不发送)"}.
{"Update message of the day on all hosts (don't send)","更新所有主机上的每日消息(不发送)"}.
{"Update plan","更新计划"}.
{"Update script","更新脚本"}.
{"Update ","更新 "}.
{"Update","更新"}.
{"Uptime:","正常运行时间:"}.
{"User Management","用户管理"}.
{"Users Last Activity","用户上次活动"}.
{"Users","用户"}.
{"User ","用户 "}.
{"User","用户"}.
{"Validate","确认"}.
{"vCard User Search","vCard 用户搜索"}.
{"Visitors are not allowed to change their nicknames in this room","此房间不允许用户更改昵称"}.
{"Visitors are not allowed to send messages to all occupants","不允许访客给所有占有者发送消息"}.
{"Wednesday","星期三"}.
{"When to send the last published item","何时发送最新发布的内容条目"}.
{"Whether to allow subscriptions","是否允许订阅"}.
{"You have been banned from this room","您已被禁止进入该房间"}.
{"You must fill in field \"Nickname\" in the form","您必须填充表单中\"昵称\"项"}.
{"You need an x:data capable client to configure room","您需要一个兼容 x:data 的客户端来配置房间"}.
{"You need an x:data capable client to register nickname","您需要一个兼容 x:data 的客户端来注册昵称"}.
{"You need an x:data capable client to search","您需要一个兼容 x:data 的客户端来搜索"}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","您发送给 ~s 的消息已被阻止. 要解除阻止, 请访问 ~s"}.
