{"Access Configuration","访问配置"}.
{"Access Control List Configuration","访问控制列表(ACL)配置"}.
{"Access control lists","访问控制列表(ACL)"}.
{"Access Control Lists","访问控制列表(ACL)"}.
{"Access denied by service policy","访问被服务策略拒绝"}.
{"Access rules","访问规则"}.
{"Access Rules","访问规则"}.
{"Action on user","对用户的动作"}.
{"Add Jabber ID","添加Jabber ID"}.
{"Add New","添加新用户"}.
{"Add User","添加用户"}.
{"Administration of ","管理"}.
{"Administration","管理"}.
{"Administrator privileges required","需要管理员权限"}.
{"A friendly name for the node","该节点的友好名称"}.
{"All activity","所有活动"}.
{"Allow this JID to subscribe to this pubsub node?","允许该JID订阅该pubsub节点?"}.
{"Allow users to change subject","允许用户更改主题"}.
{"Allow users to query other users","允许用户查询其它用户"}.
{"Allow users to send invites","允许用户发送邀请"}.
{"Allow users to send private messages","允许用户发送私聊消息"}.
{"Allow visitors to change nickname","允许用户更改昵称"}.
{"Allow visitors to send status text in presence updates","更新在线状态时允许用户发送状态文本"}.
{"All Users","所有用户"}.
{"Announcements","通知"}.
{"anyone","任何人"}.
{"April","四月"}.
{"August","八月"}.
{"Backup Management","备份管理"}.
{"Backup of ","备份来源 "}.
{"Backup to File at ","备份到文件位于"}.
{"Backup","备份"}.
{"Bad format","格式错误"}.
{"Birthday","出生日期"}.
{"Change Password","更改密码"}.
{"Change User Password","更改用户密码"}.
{"Chatroom configuration modified","聊天室配置已修改"}.
{"Chatrooms","聊天室"}.
{"Choose a username and password to register with this server","请选择在此服务器上注册所需的用户名和密码"}.
{"Choose modules to stop","请选择要停止的模块"}.
{"Choose storage type of tables","请选择表格的存储类型"}.
{"Choose whether to approve this entity's subscription.","选择是否允许该实体的订阅"}.
{"City","城市"}.
{"Commands","命令"}.
{"Conference room does not exist","会议室不存在"}.
{"Configuration for ","配置 "}.
{"Configuration","配 置"}.
{"Connected Resources:","已连接资源"}.
{"Country","国家"}.
{"CPU Time:","CPU时间："}.
{"Database Tables at ","数据库列表位于 "}.
{"Database Tables Configuration at ","数据库表格配置位于"}.
{"Database","数据库"}.
{"December","十二月"}.
{"Default users as participants","将默认用户视为参与人"}.
{"Delete message of the day on all hosts","删除所有主机上的每日消息"}.
{"Delete message of the day","删除每日消息"}.
{"Delete Selected","删除已选内容"}.
{"Delete User","删除用户"}.
{"Delete","删除"}.
{"Deliver event notifications","传递事件通知"}.
{"Deliver payloads with event notifications","用事件通告传输有效负载"}.
{"Description:","描述:"}.
{"Disc only copy","仅磁盘复制"}.
{"Displayed Groups:","已显示的组:"}.
{"Dump Backup to Text File at ","转储备份到文本文件于"}.
{"Dump to Text File","转储到文本文件"}.
{"Edit Properties","编辑属性"}.
{"ejabberd IRC module","ejabberd IRC 模块"}.
{"ejabberd MUC module","ejabberd MUC模块"}.
{"ejabberd Publish-Subscribe module","ejabberd发行-订阅模块"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5字节流模块"}.
{"ejabberd vCard module","ejabberd vCard 模块"}.
{"ejabberd virtual hosts","ejabberd虚拟主机"}.
{"ejabberd Web Admin","ejabberd网页管理"}.
{"Email","电子邮件"}.
{"Enable logging","启用服务器端聊天记录"}.
{"Encodings","编码"}.
{"End User Session","结束用户会话"}.
{"Enter list of {Module, [Options]}","请输入{模块, [选项]}列表"}.
{"Enter nickname you want to register","请输入您想要注册的昵称"}.
{"Enter path to backup file","请输入备份文件的路径"}.
{"Enter path to jabberd1.4 spool dir","请输入jabberd1.4 spool目录的路径"}.
{"Enter path to jabberd1.4 spool file","请输入jabberd1.4 spool文件的路径"}.
{"Enter path to text file","请输入文本文件的路径"}.
{"Enter username and encodings you wish to use for connecting to IRC servers","请输入您想使用的用来连接到IRC服务器的用户名和编码"}.
{"Erlang Jabber Server","Erlang Jabber 服务器"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}].","例如: [{\"irc.lucky.net\", \"koi8-r\"}, {\"vendetta.fef.net\", \"iso8859-1\"}]."}.
{"Family Name","姓氏"}.
{"February","二月"}.
{"Fill in fields to search for any matching Jabber User","填充字段以搜索任何匹配的Jabber用户"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","填充表单以搜索任何匹配的Jabber用户(在字段末添加*来匹配子串)"}.
{"Friday","星期五"}.
{"From ~s","来自~s"}.
{"From","从"}.
{"Full Name","全名"}.
{"Get Number of Online Users","获取在线用户数"}.
{"Get Number of Registered Users","获取注册用户数"}.
{"Get User Last Login Time","获取用户上次登陆时间"}.
{"Get User Password","获取用户密码"}.
{"Get User Statistics","获取用户统计"}.
{"Groups","组"}.
{"Group ","组"}.
{"has been banned","已被禁止"}.
{"has been kicked because of an affiliation change","因联属关系改变而被踢出"}.
{"has been kicked because of a system shutdown","因系统关机而被踢出"}.
{"has been kicked because the room has been changed to members-only","因该房间改为只对会员开放而被踢出"}.
{"has been kicked","已被踢出"}.
{" has set the subject to: ","已将标题设置为： "}.
{"Host","主机"}.
{"If you want to specify different encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\"}'.  By default this service use \"~s\" encoding.","如果您想为IRC服务器指定不同的编码, 请用'{\"irc 服务器\", \"编码\"}'格式的值填充此表单. 默认情况下此服务使用\"~s\"编码."}.
{"Import Directory","导入目录"}.
{"Import File","导入文件"}.
{"Import User from File at ","导入用户的文件位于 "}.
{"Import Users from Dir at ","导入用户的目录位于 "}.
{"Import Users From jabberd 1.4 Spool Files","从Jabberd 1.4 Spool文件导入用户"}.
{"Improper message type","消息类型不恰当"}.
{"Incorrect password","密码不正确"}.
{"Invalid affiliation: ~s","无效加入: ~s"}.
{"Invalid role: ~s","无效角色: ~s"}.
{"IP addresses","IP地址"}.
{"IRC Transport","IRC传输"}.
{"IRC Username","IRC用户名"}.
{"is now known as","现在称呼为"}.
{"It is not allowed to send private messages of type \"groupchat\"","\"群组聊天\"类型不允许发送私聊消息"}.
{"It is not allowed to send private messages to the conference","不允许向会议发送私聊消息"}.
{"It is not allowed to send private messages","不允许发送私聊消息"}.
{"Jabber ID","Jabber ID"}.
{"January","一月"}.
{"JID ~s is invalid","JID ~s无效"}.
{"joins the room","加入房间"}.
{"July","七月"}.
{"June","六月"}.
{"Last Activity","上次活动"}.
{"Last login","上次登陆"}.
{"Last month","上个月"}.
{"Last year","上一年"}.
{"leaves the room","离开房间"}.
{"Listened Ports at ","监听的端口位于 "}.
{"Listened Ports","监听端口"}.
{"List of modules to start","要启动的模块列表"}.
{"Low level update script","低级别更新脚本"}.
{"Make participants list public","公开参与人列表"}.
{"Make room members-only","设置房间只接收会员"}.
{"Make room moderated","使房间处于监管状态"}.
{"Make room password protected","保护房间密码"}.
{"Make room persistent","在服务器端保存该房间"}.
{"Make room public searchable","使房间可被公开搜索"}.
{"March","三月"}.
{"Maximum Number of Occupants","占有人最大数"}.
{"Max # of items to persist","允许持久化的最大内容条目数"}.
{"Max payload size in bytes","最大有效负载比特数"}.
{"May","五月"}.
{"Membership required to enter this room","进入此房间需要会员身份"}.
{"Members:","会员:"}.
{"Memory","内存"}.
{"Message body","消息主体"}.
{"Middle Name","中间名"}.
{"Moderator privileges required","需要调解人权限"}.
{"moderators only","仅一般人"}.
{"Modules at ","模块位于 "}.
{"Modules","模块"}.
{"Module","模块"}.
{"Monday","星期一"}.
{"Name:","名称:"}.
{"Name","名称"}.
{"Never","从未"}.
{"Nickname is already in use by another occupant","昵称已被另一用户占用"}.
{"Nickname is registered by another person","昵称已被另一人注册"}.
{"Nickname Registration at ","昵称注册于 "}.
{"Nickname ~s does not exist in the room","昵称~s不在该房间"}.
{"Nickname","昵称"}.
{"No body provided for announce message","通知消息无正文内容"}.
{"No Data","没有数据"}.
{"Node ID","节点ID"}.
{"Node not found","没有找到节点"}.
{"Nodes","节点"}.
{"Node ","节点 "}.
{"No limit","不限"}.
{"None","无"}.
{"No resource provided","无资源提供"}.
{"Notify subscribers when items are removed from the node","当从节点删除内容条目时通知订阅人"}.
{"Notify subscribers when the node configuration changes","当节点设置改变时通知订阅人"}.
{"Notify subscribers when the node is deleted","当节点被删除时通知订阅人"}.
{"November","十一月"}.
{"Number of occupants","占用人数"}.
{"Number of online users","在线用户数"}.
{"Number of registered users","注册用户数"}.
{"October","十月"}.
{"Offline Messages:","离线消息:"}.
{"Offline Messages","离线消息"}.
{"OK","OK"}.
{"Online Users:","在线用户:"}.
{"Online Users","在线用户"}.
{"Online","在线"}.
{"Only deliver notifications to available users","仅将通知发送给可发送的用户"}.
{"Only moderators and participants are allowed to change subject in this room","只允许监管人和参与人更改此房间的主题"}.
{"Only moderators are allowed to change subject in this room","只允许监管人更改此房间的主题"}.
{"Only occupants are allowed to send messages to the conference","只允许占有者向会议发送消息"}.
{"Only occupants are allowed to send queries to the conference","只允许占有者发出查询请求"}.
{"Only service administrators are allowed to send service messages","只有服务管理员可以发送服务消息"}.
{"Options","选项"}.
{"Organization Name","组织名称"}.
{"Organization Unit","组织单位"}.
{"Outgoing s2s Connections:","出站s2s连接:"}.
{"Outgoing s2s Connections","出站s2s连接"}.
{"Outgoing s2s Servers:","出站s2s服务器"}.
{"Owner privileges required","需要持有人权限"}.
{"Packet","数据包"}.
{"Password required to enter this room","进入此房间需要密码"}.
{"Password Verification","确认密码"}.
{"Password:","密码："}.
{"Password","密码"}.
{"Path to Dir","目录的路径"}.
{"Path to File","文件路径"}.
{"Pending","挂起"}.
{"Period: ","持续时间:"}.
{"Persist items to storage","持久化内容条目"}.
{"Ping","Ping"}.
{"Pong","Pong"}.
{"Port","端口"}.
{"Present real JIDs to","将真实JID显示给"}.
{"private, ","保密"}.
{"Publish-Subscribe","发布-订阅"}.
{"PubSub subscriber request","PubSub订阅人请求"}.
{"Queries to the conference members are not allowed in this room","本房间不允许发出成员查询请求"}.
{"RAM and disc copy","内存与磁盘复制"}.
{"RAM copy","内存(RAM)复制"}.
{"(Raw)","(原始格式)"}.
{"Raw","原始格式"}.
{"Really delete message of the day?","确实要删除每日消息吗?"}.
{"Recipient is not in the conference room","接收人不在会议室"}.
{"Registered Users:","注册用户："}.
{"Registered Users","注册用户"}.
{"Registration in mod_irc for ","mod_irc中的注册是为 "}.
{"Remark that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","注意：这些选项仅将备份内置的Mnesia数据库. 如果您在使用ODBC模块, 您还需要分别备份您的数据库."}.
{"Remote copy","远程复制"}.
{"Remove User","删除用户"}.
{"Remove","移除"}.
{"Replaced by new connection","被新的连接替换"}.
{"Resources","资源"}.
{"Restart Service","重启服务"}.
{"Restart","重启"}.
{"Restore Backup from File at ","要恢复的备份文件位于"}.
{"Restore binary backup after next ejabberd restart (requires less memory):","在下次ejabberd重启后恢复二进制备份(需要的内存更少):"}.
{"Restore binary backup immediately:","立即恢复二进制备份:"}.
{"Restore plain text backup immediately:","立即恢复普通文本备份:"}.
{"Restore","恢复"}.
{"Room Configuration","房间配置"}.
{"Room creation is denied by service policy","创建房间被服务策略拒绝"}.
{"Room title","房间标题"}.
{"Roster groups allowed to subscribe","允许订阅的花名册组"}.
{"Roster of ","花名册属于 "}.
{"Roster size","花名册大小"}.
{"Roster","花名册"}.
{"RPC Call Error","RPC调用错误"}.
{"Running Nodes","正在运行的节点"}.
{"~s access rule configuration","~s访问规则配置"}.
{"Saturday","星期六"}.
{"Script check","检查脚本"}.
{"Search Results for ","搜索结果属于关键词 "}.
{"Search users in ","要搜索的用户位于 "}.
{"Send announcement to all online users on all hosts","将通知发送给所有主机的所有用户"}.
{"Send announcement to all online users","将通知发送给所有在线用户"}.
{"Send announcement to all users on all hosts","给所有主机上的所有用户发送通知"}.
{"Send announcement to all users","将通知发送给所有用户"}.
{"September","九月"}.
{"Set message of the day and send to online users","设定每日消息并发送给所有在线用户"}.
{"Set message of the day on all hosts and send to online users","设置所有主机上的每日消息并发送给在线用户"}.
{"Shared Roster Groups","共享的花名册组群"}.
{"Show Integral Table","显示完整列表"}.
{"Show Ordinary Table","显示普通列表"}.
{"Shut Down Service","关闭服务"}.
{"~s invites you to the room ~s","~s邀请你到~s房间"}.
{"Size","大小"}.
{"Specified nickname is already registered","指定的名称已被注册"}.
{"Specify the access model","指定访问模式"}.
{"Specify the publisher model","指定发布人样式"}.
{"~s's Offline Messages Queue","~s的离线消息队列"}.
{"Start Modules at ","要启动的模块位于 "}.
{"Start Modules","启动模块"}.
{"Start","开始"}.
{"Statistics of ~p","~p的统计"}.
{"Statistics","统计"}.
{"Stop Modules at ","要停止的模块位于 "}.
{"Stop Modules","停止模块"}.
{"Stopped Nodes","已经停止的节点"}.
{"Stop","停止"}.
{"Storage Type","存储类型"}.
{"Store binary backup:","存储为二进制备份:"}.
{"Store plain text backup:","存储为普通文本备份:"}.
{"Subject","标题"}.
{"Submitted","已提交"}.
{"Submit","提交"}.
{"Subscriber Address","订阅人地址"}.
{"Subscription","订阅"}.
{"Sunday","星期天"}.
{"the password is","密码是"}.
{"This participant is kicked from the room because he sent an error message to another participant","该用户由于给其他人发送了出错信息而被踢出了聊天室"}.
{"This participant is kicked from the room because he sent an error message","该用户由于发生了错误而被踢出了聊天室"}.
{"This participant is kicked from the room because he sent an error presence","该用户由于状态信息错误而被踢出了聊天室"}.
{"This room is not anonymous","此房间不是匿名房间"}.
{"Thursday","星期四"}.
{"Time delay","时间延迟"}.
{"Time","时间"}.
{"To ~s","发送给~s"}.
{"To","到"}.
{"Traffic rate limit is exceeded","已经超过传输率限制"}.
{"Transactions Aborted:","取消的事务:"}.
{"Transactions Commited:","提交的事务:"}.
{"Transactions Logged:","记入日志的事务:"}.
{"Transactions Restarted:","重启的事务:"}.
{"Tuesday","星期二"}.
{"Updated modules","更新模块"}.
{"Update message of the day (don't send)","更新每日消息(不发送)"}.
{"Update message of the day on all hosts (don't send)","更新所有主机上的每日消息(不发送)"}.
{"Update plan","更新计划"}.
{"Update script","更新脚本"}.
{"Update ","更新 "}.
{"Update","更新"}.
{"Uptime:","正常运行时间:"}.
{"Use of STARTTLS required","要求使用STARTTLS"}.
{"User Management","用户管理"}.
{"Users are not allowed to register accounts so fast","不允许用户注册帐户太快"}.
{"Users Last Activity","用户上次活动"}.
{"Users","用户"}.
{"User ","用户 "}.
{"User","用户"}.
{"Validate","确认"}.
{"vCard User Search","vCard用户搜索"}.
{"Virtual Hosts","虚拟主机"}.
{"Visitors are not allowed to change their nicknames in this room","此房间不允许用户更改昵称"}.
{"Visitors are not allowed to send messages to all occupants","不允许访客给所有占有者发送消息"}.
{"Wednesday","星期三"}.
{"When to send the last published item","何时发送最新发布的内容条目"}.
{"Whether to allow subscriptions","是否允许订阅"}.
{"You have been banned from this room","您已被禁止进入该房间"}.
{"You must fill in field \"Nickname\" in the form","您必须填充表单中\"昵称\"项"}.
{"You need an x:data capable client to configure mod_irc settings","您需要一个兼容x:data的客户端来配置mod_irc设置"}.
{"You need an x:data capable client to configure room","您需要一个兼容x:data的客户端来配置房间"}.
{"You need an x:data capable client to register nickname","您需要一个兼容x:data的客户端来注册昵称"}.
{"You need an x:data capable client to search","您需要一个兼容x:data的客户端来搜索"}.
{"Your contact offline message queue is full. The message has been discarded.","您的离线消息队列已满. 消息已被丢弃"}.
