EJABBERD-MIB DEFINITIONS ::= BEGIN

IMPORTS
    MODULE-IDENTITY, OBJECT-TYPE, NOTIFICATION-TYPE,
    enterprises, Counter64, Gauge32
        FROM SNMPv2-SMI
    DisplayString
        FROM SNMPv2-TC
    MODULE-COMPLIANCE, OBJECT-GROUP, NOTIFICATION-GROUP
        FROM SNMPv2-CONF
    ;

ejabberdRegModule MODULE-IDENTITY
    LAST-UPDATED "201106131122Z"
    ORGANIZATION "oovoo.com"
    CONTACT-INFO "oovoo.com"
    DESCRIPTION
	"The root MIB module for oovoo.com"
    ::= {ejabberdMIB 3}


ejabberd		OBJECT IDENTIFIER ::= {enterprises 40005}
ejabberdMIB	OBJECT IDENTIFIER ::= {ejabberd 1}

ejabberdMIBConformance	OBJECT IDENTIFIER ::= {ejabberdMIB 1}
ejabberdMIBObjects		OBJECT IDENTIFIER ::= {ejabberdMIB 2}

-- Managed Objects
ejabberdSystemStats	OBJECT IDENTIFIER ::= {ejabberdMIBObjects 1}

generalUptime	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"System's uptime (in seconds)"
    ::= {ejabberdSystemStats 1}

generalNodeName	OBJECT-TYPE
    SYNTAX	DisplayString
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"The name of the node"
    ::= {ejabberdSystemStats 2}

xmppMessagesSent	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP message stanzas sent by the users"
    ::= {ejabberdSystemStats 3}

xmppMessagesReceived	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP message stanzas received by the users"
    ::= {ejabberdSystemStats 4}

xmppMessagesBounced	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP messages bounced"
    ::= {ejabberdSystemStats 5}

xmppPresencesSent	OBJECT-TYPE
    SYNTAX 	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP presence stanzas sent by the users"
    ::= {ejabberdSystemStats 6}

xmppPresencesReceived	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP presence stanzas received by the users"
    ::= {ejabberdSystemStats 7}

xmppIqsSent		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP iq stanzas sent by the users"
    ::= {ejabberdSystemStats 8}

xmppIqsReceived		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP iq stanzas received by the users"
    ::= {ejabberdSystemStats 9}

xmppStanzasSent		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP stanzas sent by the users"
    ::= {ejabberdSystemStats 10}

xmppStanzasReceived	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP stanzas received by the users"
    ::= {ejabberdSystemStats 11}

xmppRosterGets		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP iq requests sent to the server"
    ::= {ejabberdSystemStats 12}

xmppErrorIqsGenerated	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of 'error' iqs generated by the server"
    ::= {ejabberdSystemStats 13}

xmppStanzasDenied	OBJECT-TYPE
    SYNTAX 	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of XMPP messages denied by the privacy module"
    ::= {ejabberdSystemStats 14}

sessionSuccessfulLogins	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of successful login attempts"
    ::= {ejabberdSystemStats 15}

sessionLogouts		OBJECT-TYPE
    SYNTAX 	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of logouts"
    ::= {ejabberdSystemStats 16}

sessionAuthFails	OBJECT-TYPE
   SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of authentication failures on login"
    ::= {ejabberdSystemStats 17}

sessionCount 		OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of sessions on this node"
    ::= {ejabberdSystemStats 18}

globalSessionCount  OBJECT-TYPE
    SYNTAX Gauge32
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION
    "Number of sessions in the cluster"
    ::= {ejabberdSystemStats 19}

globalUniqueSessionCount OBJECT-TYPE
    SYNTAX Gauge32
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION
    "Number of unique sessions in the cluster"
    ::= {ejabberdSystemStats 20}

sessionFrozen		OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of frozen sessions"
    ::= {ejabberdSystemStats 21}

dbMessagesSentToOffline	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS 	read-only
    STATUS	current
    DESCRIPTION
	"Number of messages sent to offline storage"
    ::= {ejabberdSystemStats 22}

dbRosterGets		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS 	read-only
    STATUS	current
    DESCRIPTION
	"Number of roster fetches from database"
    ::= {ejabberdSystemStats 23}

dbRosterSets		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of roster update queries"
    ::= {ejabberdSystemStats 24}

dbVCardGets		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of VCard get queries"
    ::= {ejabberdSystemStats 25}

dbVCardSets		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of VCard set queries"
    ::= {ejabberdSystemStats 26}

dbPrivacyGets		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of privacy get queries"
    ::= {ejabberdSystemStats 27}

dbPrivacySets		OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of privacy set queries"
    ::= {ejabberdSystemStats 28}

dbOfflineMsgRetrievals	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of offline messages retrievals"
    ::= {ejabberdSystemStats 29}

clusterLinks		OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of inter-cluster links"
    ::= {ejabberdSystemStats 30}

clusterTrafficTable	OBJECT-TYPE
    SYNTAX	SEQUENCE OF TrafficEntry
    MAX-ACCESS	not-accessible
    STATUS	current
    DESCRIPTION
	"Table for inter-cluster traffic"
    ::= {ejabberdSystemStats 31}

clusterTrafficEntry	OBJECT-TYPE
    SYNTAX     	TrafficEntry
    MAX-ACCESS	not-accessible
    STATUS	current
    DESCRIPTION
	"A conceptual row for clusterTrafficTable"
    INDEX	{clusterNode}
    ::= {clusterTrafficTable 1}

TrafficEntry ::= SEQUENCE {
    clusterNode	  	DisplayString,
    clusterBytesSent	Counter64,
    clusterBytesRecvd	Counter64
}

clusterNode    		OBJECT-TYPE
    SYNTAX	DisplayString
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Node to which this row refers"
    ::= {clusterTrafficEntry 1}

clusterBytesSent	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Bytes sent to the node"
    ::= {clusterTrafficEntry 2}

clusterBytesRecvd	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Bytes received from the node"
    ::= {clusterTrafficEntry 3}

s2sStanzasSent	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of stanzas sent out using s2s connections"
    ::= {ejabberdSystemStats 32}

s2sStanzasReceived	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of stanzas received using s2s connections"
    ::= {ejabberdSystemStats 33}

s2sConnections		OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of s2s connections"
    ::= {ejabberdSystemStats 34}

s2sConnectionsOut	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of outgoing s2s connections"
    ::= {ejabberdSystemStats 35}

s2sConnectionsIn	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of incoming s2s connections"
    ::= {ejabberdSystemStats 36}

s2sOutEstablished	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of times outgoing s2s connections has been established"
    ::= {ejabberdSystemStats 37}

s2sInEstablished	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of times incoming s2s connections has been established"
    ::= {ejabberdSystemStats 38}

s2sOutClosed	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of times outgoing s2s connections has been closed"
    ::= {ejabberdSystemStats 39}

s2sInClosed	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of times incoming s2s connections has been closed"
    ::= {ejabberdSystemStats 40}

fedStanzasSent	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of stanzas sent out using fed connections"
    ::= {ejabberdSystemStats 41}

fedStanzasReceived	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of stanzas received using s2s connections"
    ::= {ejabberdSystemStats 42}

fedConnections		OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of fed connections"
    ::= {ejabberdSystemStats 43}

fedConnectionsOut	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of outgoing fed connections"
    ::= {ejabberdSystemStats 44}

fedConnectionsIn	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of incoming fed connections"
    ::= {ejabberdSystemStats 45}

fedOutEstablished	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of times outgoing fed connections has been established"
    ::= {ejabberdSystemStats 46}

fedInEstablished	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of times incoming fed connections has been established"
    ::= {ejabberdSystemStats 47}

fedOutClosed	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of times outgoing fed connections has been closed"
    ::= {ejabberdSystemStats 48}

fedInClosed	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of times incoming fed connections has been closed"
    ::= {ejabberdSystemStats 49}

c2sReceiverTimeouts	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of c2s-related receiver timeouts"
    ::= {ejabberdSystemStats 50}

s2sReceiverTimeouts	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of s2s-related receiver timeouts"
    ::= {ejabberdSystemStats 51}

fedReceiverTimeouts	OBJECT-TYPE
    SYNTAX	Counter64
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of fed-related receiver timeouts"
    ::= {ejabberdSystemStats 52}

dbConnectionsTable	OBJECT-TYPE
    SYNTAX	SEQUENCE OF WorkerEntry
    MAX-ACCESS	not-accessible
    STATUS	current
    DESCRIPTION
	"Table for lengths of db connections queues"
    ::= {ejabberdSystemStats 53}

dbConnectionEntry	OBJECT-TYPE
    SYNTAX	WorkerEntry
    MAX-ACCESS	not-accessible
    STATUS	current
    DESCRIPTION
	"A conceptual row for dbConnectionsTable"
    INDEX	{dbConnQueueLength}
    ::= {dbConnectionsTable 1}

WorkerEntry ::= SEQUENCE {
    dbConnQueueLength	Gauge32
}

dbConnQueueLength	OBJECT-TYPE
    SYNTAX	Gauge32
    MAX-ACCESS	read-only
    STATUS	current
    DESCRIPTION
	"Number of messages in the processes queue"
    ::= {dbConnectionEntry 1}

-- Conformance information
ejabberdMIBCompliances	OBJECT IDENTIFIER ::= {ejabberdMIBConformance 1}
ejabberdMIBGroups		OBJECT IDENTIFIER ::= {ejabberdMIBConformance 2}

ejabberdBasicCompliance	MODULE-COMPLIANCE
    STATUS	current
    DESCRIPTION
        "The compliance statement for SNMPv2 entities which
        implement the OTP-MIB."
    MODULE  -- this module
        MANDATORY-GROUPS {
                          monitorGroup
                         }
    ::= {ejabberdMIBCompliances 1}

monitorGroup OBJECT-GROUP
    OBJECTS {
    generalUptime,
    generalNodeName,
    xmppMessagesSent,
    xmppMessagesReceived,
    xmppMessagesBounced,
    xmppPresencesSent,
    xmppPresencesReceived,
    xmppIqsSent,
    xmppIqsReceived,
    xmppStanzasSent,
    xmppStanzasReceived,
    xmppRosterGets,
    xmppErrorIqsGenerated,
    xmppStanzasDenied,
    sessionSuccessfulLogins,
    sessionLogouts,
    sessionAuthFails,
    sessionCount,
    globalSessionCount,
    globalUniqueSessionCount,
    sessionFrozen,
    dbMessagesSentToOffline,
    dbRosterGets,
    dbRosterSets,
    dbVCardGets,
    dbVCardSets,
    dbPrivacyGets,
    dbPrivacySets,
    dbOfflineMsgRetrievals,
    dbConnQueueLength,
    clusterLinks,
    clusterNode,
    clusterBytesSent,
    clusterBytesRecvd,
    s2sStanzasSent,
    s2sStanzasReceived,
    s2sConnections,
    s2sConnectionsIn,
    s2sConnectionsOut,
    s2sOutEstablished,
    s2sInEstablished,
    s2sOutClosed,
    s2sInClosed,
    fedStanzasSent,
    fedStanzasReceived,
    fedConnections,
    fedConnectionsIn,
    fedConnectionsOut,
    fedOutEstablished,
    fedInEstablished,
    fedOutClosed,
    fedInClosed,
    c2sReceiverTimeouts,
    s2sReceiverTimeouts,
    fedReceiverTimeouts
    }
    STATUS current
    DESCRIPTION
        "A collection of objects providing basic instrumentation
        of the ejabberd runtime system."
    ::= {ejabberdMIBGroups 1}

END
