
include ..\Makefile.inc

EFLAGS = -I .. -pz ..

OUTDIR = ..
BEAMS = ..\stun_codec.beam ..\ejabberd_stun.beam

ALL : $(BEAMS)

CLEAN :
	-@erase $(BEAMS)

$(OUTDIR)\stun_codec.beam : stun_codec.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) stun_codec.erl

$(OUTDIR)\ejabberd_stun.beam : ejabberd_stun.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) ejabberd_stun.erl
