#!/bin/bash

TOOLS=`dirname $0`
if [ `uname` = "Darwin" ]; then
    BASE=$(cd "$TOOLS/.."; pwd -P)
else
    BASE=`readlink -f $TOOLS/..`
fi
SUMMARIES_GLOB=$BASE'/test/ejabberd_tests/ct_report/ct_run*/ejabberd_tests.*.logs/*/suite.summary'

EJD2=$BASE/dev/ejabberd_node2
EJD2CTL=$EJD2/bin/ejabberd

make devclean devrel testrel

echo -n "starting auxiliary s2s node: "
$EJD2CTL start && echo ok || echo failed
sleep 5s
echo -n "pinging auxiliary s2s node: "
$EJD2CTL ping

make cover_test

echo -n "stopping auxiliary s2s node: "
$EJD2CTL stop

if [ `uname` = "Darwin" ]; then
    $TOOLS/summarise-ct-results `ls -t $SUMMARIES_GLOB | head -n 1`
else
    $TOOLS/summarise-ct-results `eval ls $SUMMARIES_GLOB --sort time | head -n 1`
fi

CT_STATUS=$?
echo
echo "All tests done."
exit $CT_STATUS
