#!/bin/bash

TOOLS=`dirname $0`
if [ `uname` = "Darwin" ]; then
    BASE=$(cd "$TOOLS/.."; pwd -P)
else
    BASE=`readlink -f $TOOLS/..`
fi

CFGS="$BASE/rel/vars.config $BASE/rel/reltool_vars/*.config"
sed -e "s/%ODBC_PASSWORD%/$1/" -i -- $CFGS
