#!/bin/bash

TOOLS=`dirname $0`
if [ `uname` = "Darwin" ]; then
    BASE=$(cd "$TOOLS/.."; pwd -P)
    SED=gsed
else
    BASE=`readlink -f $TOOLS/..`
    SED=sed
fi

CFGS="$BASE/rel/vars.config $BASE/rel/reltool_vars/*.config"
$SED -e "s/%ODBC_PASSWORD%/$1/" -i -- $CFGS
