#!/bin/sh
##############################################################
#
#     yahoo-transport-2 -- script to start Yahoo-transport-2.
#
#############################################################

DAEMON=/usr/local/sbin/jabberd-yahoo-transport-2
CONF=/etc/jabber/yahoo-transport-2.xml
NAME=jabberd-yahoo-transport-2
HOME=/etc/jabber/
USER=ejabberd

#############################################################

if [ "`/usr/bin/whoami`" != "$USER" ]; then

       echo "You need to be" $USER "user to run this script."
       exit 1
fi

case "$1" in
  debug)
        test -f $DAEMON -a -f $CONF || exit 0
        echo "Starting $NAME in debugging mode."
        $DAEMON -D -H $HOME -c $CONF &
        ;;
  start)
	test -f $DAEMON -a -f $CONF || exit 0
	echo "Starting $NAME."
	$DAEMON -H $HOME -c $CONF &
	;;
  stop)
	echo "Stopping $NAME."
	killall $NAME &
  	;;
  restart|reload)
	$0 stop
        sleep 3
	$0 start
	;;
  *)
	echo "Usage: $0 {debug|start|stop|restart}"
	exit 1
esac
